### ISSUE TITLE
No Push notifications on data

### ISSUE THREAD

**Issue by tgt26** [signalapp/Signal-Android#8400] opened 2018-11-26 22:35 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I'm connected to data I don't get push notifications untill I open Signal. When I do so, then I get all the messages. The app is not being optimized and the background data is allowed. 

### Steps to reproduce
- Be on data
-Tell contact to send message
- messages are not received

**Actual result:** push notifications don't arrive until app is opened or you connect to WiFi.
**Expected result:** receive push notifications even when not inside app

### Device info

**Device:** OnePlus 5T 
**Android version:** 8.1.0
**Signal version:** 4.31.0

### Link to debug log

https://debuglogs.org/698d21985e2c3ecd75516115c07909bbe09a723964bcbfb82cfb2889137a1db7

**Comment by tuxayo** [comment] 2018-12-10 10:44
Can this help?
https://support.signal.org/hc/en-us/articles/360007318711-Troubleshooting-Notifications

in particular «Battery optimization» and «Optimize battery»

**Comment by tgt26** [comment] 2018-12-10 13:46
Nope. The app isn't being optimized and data usage is unrestricted.

**Comment by CyBiS** [comment] 2019-02-07 21:29
I can confirm this issue on my OnePlus 3T (Android 8, OxygenOS v28181206) and Signal v4.32.8. Following settings are applied:

- Settings --> Data usage --> Menu --> Data saver --> Off
  - Unrestricted data access --> Signal app added (although this shouldn't have an effect with data saver off)
- Settings --> Battery --> Battery saver --> Off
  - Turn on automatically --> Off
- Settings --> Battery --> Battery optimisation --> set Signal app to "Don't optimise"
- The Signal app is locked in the recent app list and therefore cannot be removed from that list.

I was able to collect two debug logs on both the Signal desktop and Android app where a certain message was received immediatly via the desktop app but took 13 minutes to be finally received via the Android app, i.e. the push notification didn't show up for 13 minutes on the Android device.

Signal desktop app debug log: [https://debuglogs.org/9cd4b7e6fa24d9c0cc47763041f843af7acb16451f0cc79b322aa2622d4135db](https://debuglogs.org/9cd4b7e6fa24d9c0cc47763041f843af7acb16451f0cc79b322aa2622d4135db)
Signal Android app debug log: [https://debuglogs.org/228ba530b7673d797e902a0dfded318190ecd8ba5c364f60f5621c81aabadf1d](https://debuglogs.org/228ba530b7673d797e902a0dfded318190ecd8ba5c364f60f5621c81aabadf1d)

The message was received on February 1st at 16:16 CET (last 3 phone number digits: 850, sent message ID 1549034215519) via the desktop app. As mentioned previously, the notification arrived roughly 13 minutes later on the mobile phone.

Do the logs help to narrow down whether this is a Signal or OnePlus/OxygenOS issue?

**Comment by greyson-signal** [comment] 2019-05-31 14:31
Doing some cleanup. Closing as dupe of #8692.

**Closed by greyson-signal** 2019-05-31 14:31 UTC
