### ISSUE TITLE
It is possible to make screenshots of view-once media

### ISSUE THREAD

**Issue by qwerty287** [signalapp/Signal-Android#13014] opened 2023-06-21 14:28 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
You can take screenshots of view-once media which kind of is against the principles of this feature.

### Steps to reproduce
- send/receive a view-once media
- open it
- take a screenshot

**Actual result:** a screenshot is taken and stored
**Expected result:** the screenshot should be blocked

### Device info

**Android version:** 12
**Signal version:** 6.23.5

**Comment by greyson-signal** [comment] 2023-06-21 17:25
We're aware of this and do not consider it to be a bug. There's lot of ways to capture screen contents outside of taking a screenshot (like taking a picture of the screen). We may make changes in the future around this, but for now I'm going to close this.

**Closed by greyson-signal** 2023-06-21 17:25 UTC

**Comment by olfek** [comment] 2023-09-24 10:22
> There's lot of ways to capture screen contents outside of taking a screenshot **(like taking a picture of the screen)**.

We get it. But why are you making it easier for them by _allowing_ screenshots? ...

When you can disallow them with a simple Android app window flag `FLAG_SECURE`
https://developer.android.com/reference/android/view/WindowManager.LayoutParams#FLAG_SECURE

This would literally take less than 60 seconds to implement.

I dislike bureaucracy so much.

As a firm believer in "the customer is always right" I command you @greyson-signal to implement this ... Please? 🥺

**Comment by olfek** [comment] 2023-09-24 10:24
And also, someone reopen this issue, I need to move to Signal after the recent WhatsApp update 🤢

**Comment by olfek** [comment] 2023-09-25 15:56
duplicate of - https://github.com/signalapp/Signal-Android/issues/12350
