### ISSUE TITLE
Messages received by server but not delivered to contact

### ISSUE THREAD

**Issue by nightbluepn** [signalapp/Signal-Android#7966] opened 2018-07-04 17:04 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
With one particular conversation partner, both of us being on the non-playstore version (all other contacts use the playstore version), messages will often not be delivered and be stuck on one checkmark.
Pretty much the same as described in #6246 by @EvanK - my conversation partner and i are on Lineageos 14.1 as well.
Additional info: 
-It also happens that my conv. partner has single checkmarks too, but i did receive the messages. This was the case when i made the screenshot. On the other phone, sent messages had one single checkmark, my messages were missing.
-It may happen for only one of us, i.e. unidirectional communication, other side is stuck with single checkmarks
-Force quitting & restarting, resetting network etc. does not help. Not even a reboot.

After upgrading the app, the error was gone for about 24h and then started again.

I am opening another ticket after reading #7598.

### Steps to reproduce
- My best guess is to use two non-playstore versions and to exchange messages for a couple of days
- If that doesn't make the bug occur, it might even have to do with LineageOs. I will try out if this is true by making someone with stock Android install the web version.

**Actual result:** At any point in a conversation, messages will stop to obtain a second checkmark for an indefinite amount of time.
**Expected result:** Messages should be delivered as usual.

### Screenshots
![screenshot_20180704-183800](https://user-images.githubusercontent.com/26491995/42288447-01c7e73e-7fbb-11e8-908e-81d92caeb2a1.png)

### Device info

**Device:** Sony Xperia Z5 Compact (suzuran)
**Android version:** 7.1.2
**Signal version:** 4.21.6

### Link to debug log

https://pastebin.com/9wf80arh

**Comment by nightbluepn** [comment] 2018-07-04 17:15
Debug log of the other end: https://debuglogs.org/f1e601c46416d3600cdedcbac49e93e5a6dcd62c14a369fc4c5e2d8a205e8735

By the way: the same thing happens when sending from signal desktop.

I will try to single out what makes it happen/stop ..

**Comment by erik55** [comment] 2018-07-11 23:29
I can confirm that bug with two Samsung phones (S7 with Android 8.0 and S5 mini with Android 6.0.1) and with the playstore version of Signal Messenger. This only happens from time to time, and I have no idea how to reproduce it. Other times it just works. But I have to admit, that I haven’t experienced that bug since about 10 days.

The bug here: The message arrives at one phone, but the other phone shows the message only with one check mark.

I think (as far as I remember) the bug could be related to the bug #7733 of not being able to start/receive calls and only getting a message of a missed call, while the caller continues hearing the submarine echo sound.

**Comment by dpapavas** [comment] 2018-08-03 11:58
> Could it be connected to #7638 ?

I'm not sure.  At first glance, the logs seem to indicate that the network connection is ok.  For some reason though receipts are not received (or processed) and there are also suspicious messages about delayed notifications, which are then canceled.

As a first step, I'd suggest upgrading to the latest stable version, as this one is more than a month old and the logs seem to contain failure messages of the autoupdate mechanism.  I recently had similar problems after staying with an old version of Signal, even though it was patched to take care of #7638.

**Comment by a9e78rauijasdf** [comment] 2018-08-27 08:39
Im seeing this issue as well. Im on the beta via play store (4.25.5) - contact is on regular version from play store (4.24.8).
It kind looks like the recipient device sleeps a bit too much - my initial thought was that it was due to some battery optimizer function, but turning optimize off hasnt changed anything.

Any suggestions, news, ideas?

**Comment by janvlug** [comment] 2018-09-10 09:29
I have a contact that does not receive notifications of messages that I send as well.
This is the debug log of my Signal Desktop (from where I sent the messages):
https://debuglogs.org/6d2f70749a11276477fe8765647a1ea926014efdf5bccbe6b37dbfea0d036466
This is the debug log of the contact who does not receive notifications (it looks like Signal does not wake up from the background, or is not running in the background). The debug log is taken after activating Signal and receiving the messages:
https://debuglogs.org/eb4a29c1253f2be64a3fcf15b3550682812a534ec214c45f913195c299872ee0
I also noted, that in Signal Desktop, one message was not marked as received by my contact while is was received:
![image](https://user-images.githubusercontent.com/5903208/45289088-9b903180-b4ec-11e8-9a8b-a432076f6521.png)

**Comment by jedie** [comment] 2018-09-22 19:15
Maybe it's because of battery optimisation in android if the user doesn't use signal often.

Many other apps check this and display a information about this with a link into the settings, so that the user can disable the optimisation.

**Comment by greyson-signal** [comment] 2021-07-09 14:33
A lot has changed in three years. Closing this. If people are having issues where you're not receiving messages or notifications are delayed, you can check out #8692

**Closed by greyson-signal** 2021-07-09 14:33 UTC
Labels: help wanted
