### ISSUE TITLE
Message takes long too receive, DuplicateMessageException in log

### ISSUE THREAD

**Issue by adeorato** [signalapp/Signal-Android#8623] opened 2019-02-18 07:16 UTC
### Bug description
Receiving a message on a Huawei cellphone takes too long (more than 20 minutes after desktop version already received the message). In the status bar the translated string of GcmBroadcastReceiver_retrieving_a_message (Retrieving a message) is shown. 

The debug log is showing a DuplicateMessageException (see link)

### When does it happen
* Huawei phone, Android 8
* Desktop PC in same wifi gets the message, so network is working
* Happens in wifi and also in cell (3G) network
* reproduceable with at least two different Huawei phones

**Actual result:** It takes long to get the message
**Expected result:** Receive time should be as fast as the desktop version in the same wifi

### Device info
**Device:** HUAWEI WAS-LX1
**Android version:** 8.0.0 (386(C432)
**Signal version:** 4.32.8

### Link to debug log
https://debuglogs.org/2ebfdc7da7cbf2cea049222ca187396ac69c4615ebf6790b25e598027bbf9b72

**Comment by greyson-signal** [comment] 2019-02-19 16:12
I'm looking into battery-optimization issues that cause Signal to be unable to access the network, resulting in exceptions like:

```java
02-18 08:09:01.592  1263  1429 W PushNotificationReceiveJob: org.whispersystems.signalservice.api.push.exceptions.PushNetworkException: java.net.SocketTimeoutException: timeout
02-18 08:09:01.592  1263  1429 W PushNotificationReceiveJob: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.getServiceConnection(PushServiceSocket.java:917)
02-18 08:09:01.592  1263  1429 W PushNotificationReceiveJob: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:778)
02-18 08:09:01.592  1263  1429 W PushNotificationReceiveJob: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:766)
02-18 08:09:01.592  1263  1429 W PushNotificationReceiveJob: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.getMessages(PushServiceSocket.java:232)
02-18 08:09:01.592  1263  1429 W PushNotificationReceiveJob: 	at org.whispersystems.signalservice.api.SignalServiceMessageReceiver.retrieveMessages(SignalServiceMessageReceiver.java:172)
02-18 08:09:01.592  1263  1429 W PushNotificationReceiveJob: 	at org.thoughtcrime.securesms.jobs.PushNotificationReceiveJob.pullAndProcessMessages(PushNotificationReceiveJob.java:60)
02-18 08:09:01.592  1263  1429 W PushNotificationReceiveJob: 	at org.thoughtcrime.securesms.jobs.PushNotificationReceiveJob.onRun(PushNotificationReceiveJob.java:55)
02-18 08:09:01.592  1263  1429 W PushNotificationReceiveJob: 	at org.thoughtcrime.securesms.jobmanager.Job.doWorkInternal(Job.java:111)
02-18 08:09:01.592  1263  1429 W PushNotificationReceiveJob: 	at org.thoughtcrime.securesms.jobmanager.Job.doWork(Job.java:64)
02-18 08:09:01.592  1263  1429 W PushNotificationReceiveJob: 	at androidx.work.Worker$1.run(Worker.java:84)
02-18 08:09:01.592  1263  1429 W PushNotificationReceiveJob: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
02-18 08:09:01.592  1263  1429 W PushNotificationReceiveJob: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
02-18 08:09:01.592  1263  1429 W PushNotificationReceiveJob: 	at java.lang.Thread.run(Thread.java:784)
02-18 08:09:01.592  1263  1429 W PushNotificationReceiveJob: Caused by: java.net.SocketTimeoutException: timeout
02-18 08:09:01.592  1263  1429 W PushNotificationReceiveJob: 	at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:593)
02-18 08:09:01.592  1263  1429 W PushNotificationReceiveJob: 	at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:601)
02-18 08:09:01.592  1263  1429 W PushNotificationReceiveJob: 	at okhttp3.internal.http2.Http2Stream.takeResponseHeaders(Http2Stream.java:146)
02-18 08:09:01.592  1263  1429 W PushNotificationReceiveJob: 	at okhttp3.internal.http2.Http2Codec.readResponseHeaders(Http2Codec.java:125)
02-18 08:09:01.592  1263  1429 W PushNotificationReceiveJob: 	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
02-18 08:09:01.592  1263  1429 W PushNotificationReceiveJob: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
02-18 08:09:01.592  1263  1429 W PushNotificationReceiveJob: 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
02-18 08:09:01.592  1263  1429 W PushNotificationReceiveJob: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
02-18 08:09:01.592  1263  1429 W PushNotificationReceiveJob: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
02-18 08:09:01.592  1263  1429 W PushNotificationReceiveJob: 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
02-18 08:09:01.592  1263  1429 W PushNotificationReceiveJob: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
02-18 08:09:01.592  1263  1429 W PushNotificationReceiveJob: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
02-18 08:09:01.592  1263  1429 W PushNotificationReceiveJob: 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
02-18 08:09:01.592  1263  1429 W PushNotificationReceiveJob: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
02-18 08:09:01.592  1263  1429 W PushNotificationReceiveJob: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
02-18 08:09:01.592  1263  1429 W PushNotificationReceiveJob: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
02-18 08:09:01.592  1263  1429 W PushNotificationReceiveJob: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
02-18 08:09:01.592  1263  1429 W PushNotificationReceiveJob: 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
02-18 08:09:01.592  1263  1429 W PushNotificationReceiveJob: 	at okhttp3.RealCall.execute(RealCall.java:77)
02-18 08:09:01.592  1263  1429 W PushNotificationReceiveJob: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.getServiceConnection(PushServiceSocket.java:910)
02-18 08:09:01.592  1263  1429 W PushNotificationReceiveJob: 	... 12 more
```

In the short term, try to verify that you have battery optimizations disabled for Signal. In the meantime, I'm trying out some different message download strategies to minimize how often this type of thing happens.

**Comment by greyson-signal** [comment] 2019-02-19 16:19
Closing as a dupe of #8604

**Closed by greyson-signal** 2019-02-19 16:19 UTC
