### ISSUE TITLE
Group SMS forked into duplicate conversation

### ISSUE THREAD

**Issue by mildmojo** [signalapp/Signal-Android#9213] opened 2019-11-21 21:27 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

After an update, my group SMS chats split in two. For each of the two group SMS conversations that have been active since I updated to 4.49.18 (maybe 2-4 weeks since the previous update), I now have an additional two conversations with the same participants. Here are examples; I've renamed the participants, but the renaming is consistent and preserves alphabetical order:

- "Me, Ben, James" (old)
- "James, Ben, Me" (new) 

and

- "Me, Ben, James, Bernie" (old)
- "James, Ben, Me, Bernie" (new)

No participants have changed, no contacts have been updated. Each contact has only one phone number attached. I can send messages from either conversation and I think they go to all recipients, but when I receive messages, they only go to the new conversation. So now my chat history for these groups  is spread across two conversations; several years' worth in the "old" convo and the last few days in the "new" convo.

### Steps to reproduce

- Start a group SMS conversation with friends
- Update to 4.49.18
- Have a friend send a group SMS to the group
- Observe that Signal creates a new conversation with the participants in a different order and delivers new messages there instead of the old group

**Actual result:** I have two conversations for the same group SMS with the same participants.
**Expected result:** All conversations with the same participants should be merged into a single conversation.

### Device info

**Device:** Blackberry Priv
**Android version:** 6.0.1
**Signal version:** 4.49.18

### Link to debug log

Not applicable, the new conversations were created a few days ago.

**Comment by Kage1** [comment] 2019-11-29 00:26
Could this be related to #9173, ATT MMS bug?

**Comment by legaresmith** [comment] 2019-12-08 18:24
Same issue here on Pixel 2 on Verizon. Multiple groups with the same people but the order is different and it treats them as separate!?

**Comment by bxm156** [comment] 2021-01-15 03:10
This is happening to me too. I sent a group text to 2 people without Signal, and their replies went to a new Group.

Image attached. Blurred the convo for privacy. 



Verizon, Galaxy note 10+, Signal 5.1.8.

![Screenshot_20210114-190720_Signal-01.jpeg](https://user-images.githubusercontent.com/136036/104676356-16108380-569c-11eb-88b6-fd78b5125a65.jpeg)

**Comment by akgrown** [comment] 2021-01-17 19:58
Same issue. Create new MMS group, send a message, rename the group before any replies come in, and then the replies get placed in a separate/new group, orphaning your original message. This is on Signal 5.1.9, AT&T, Galaxy Note 10+, Android 10.

**Comment by benmayne** [comment] 2021-05-02 17:21
I've got some debug logs for this as well and it happened to me back in 2018: https://github.com/signalapp/Signal-Android/issues/7683

I have some screenshots if it helps, but the reproduction is consistent with the OP and pretty straight forward: 

1. start a MMS group from signal
2. get a reply from either participant in a new thread

I can send to either thread, but all responses go to the new one. 

debug log right after sending the first message (which creates group 1): https://debuglogs.org/546008a19bf6bbf76c5115a97452f233c77142f0744aa58b89e7ad835ccab55c

debug log right after getting a reply to the new group: https://debuglogs.org/4daccb05878e90949c89db255d88c00cc468d81a30ee29af6371c65cd0b2a890

Device: Pixel 5
Android: 11
Signal 5.10.2
Google Fi on wifi (though I'm pretty sure this behavior is consistent across networks)

**Comment by fleapower** [comment] 2022-01-02 14:37
I thought I had reported this issue awhile back, but I can't find it.  It is also happening to me and has been since the beginning of '21.

**Comment by benmayne** [comment] 2022-03-03 15:33
I'm pretty confident this has happened within the last couple months. I can grab another debug log when it next happens if that will help

**Comment by legaresmith** [comment] 2022-03-03 15:36
I got a new phone (Pixel 5a, old was a Pixel 2) - transferred my Signal messages to the new phone and still experienced this bug. I resorted to deleting all of my conversations and now I have yet to experience it. But I would have preferred to be able to keep my conversations :-/

**Comment by fleapower** [comment] 2022-03-03 15:44
As recently as yesterday, this is still happening every time I create a group and someone responds.  Has anyone tried reinstalling and restoring conversations from a backup to see if this fixes it?

**Comment by fleapower** [comment] 2022-03-03 15:56
> Yes - see my post just above yours 🙃

Sorry...missed that.

OK...so it sounds like a database error.

**Comment by benmayne** [comment] 2022-05-02 18:18
Still happening I think

**Comment by fleapower** [comment] 2022-05-02 20:59
Confirmed still happening as of today.

**Comment by legaresmith** [comment] 2022-08-12 18:35
Still people with issues AFAIK - me being one of them. At this point, I've grown to expect it :-/

**Comment by greyson-signal** [comment] 2022-10-12 17:10
Hi there, given our future plans to [remove SMS support](https://signal.org/blog/sms-removal-android/), I'm gonna close this. Thanks!

**Closed by greyson-signal** 2022-10-12 17:10 UTC
Labels: mms, sms, acknowledged

**Comment by legaresmith** [comment] 2022-10-12 19:36
Yup. Much prefer to only have 1 app for messaging, a big draw of using Signal for me too. Very disappointed upon reading the above message and clicking the link to discover it's being discontinued. It provides a better messaging experience than the default android app regardless if the other user was on Signal or not :(
