### ISSUE TITLE
Cannot receive SMS I send myself anymore

### ISSUE THREAD

**Issue by schklom** [signalapp/Signal-Android#12165] opened 2022-04-14 22:22 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
As described in https://github.com/signalapp/Signal-Android/issues/12157, I often send myself notifications by text messages from myself (using an API).
Since an update a few days ago, Signal filters these messages 

I appreciate the need to have better security for the masses, but this "feature" prevents self-sent text notifications and this is a deal-breaker for me. Yes I could use a third-party online like Matrix, but this requires me to have 24/7 Internet on my phone and I just don't.
Texts only require some cellular service, and are much faster to receive (no need to ping a server every xxx seconds).

Filtering my messages without my consent is overreaching. Just because you don't send yourself texts doesn't mean others also don't.
No other common SMS app filters messages. Please don't be the first to filter without giving an opt-out option.

Opinions may differ, but I feel that not being able to receive my own texts is a bug.
It feels nonsensical that I need to argue that (what is intended as) a spam filter should be possible to turn off, but here we are.
Emails also have spam filters, but they can be turned off.

### Steps to reproduce
- set Signal as the default SMS app
- send yourself a regular non-Internet text

**Actual result:** Signal ignores the SMS
**Expected result:** Signal doesn't ignore the SMS

### Device info

**Device:**
**Android version:** 11
**Signal version:** 5.34.10

**Comment by eddyizm** [comment] 2022-04-15 04:34
This is a feature I use a bunch and offer to clients as a cheap way to keep tabs on stuff. Success messages or tail a log when something errors.

**Comment by clauz9** [comment] 2022-04-15 05:11
One of the developers has explained why receiving sms/mms from your own number has been disabled here https://github.com/signalapp/Signal-Android/issues/12157#issuecomment-1098079111

**Comment by schklom** [comment] 2022-04-15 05:29
@clauz9 Thanks for the reply, but this was not what I wrote about.
Although I completely understand making this a default setting for safety reasons, no reason has been given to justify not giving users a choice.
Spam filters on emails are also very useful, but it is very important that they can be turned off. Please show me where this filter can be disabled on Signal.

The people on the forum (link in https://github.com/signalapp/Signal-Android/issues/12157#issuecomment-1098079111) show some valid use-cases, and they are just ignored. Why? No one knows.
Dropping legitimate messages without an opt-out ***is not a call they should be able to make.***
It is unfortunate that they ask if people want this filter, people reply yes, and they just ignore these replies.

**Comment by greyson-signal** [comment] 2022-04-15 14:51
Hi there, closing as a duplicate of #12157

**Closed by greyson-signal** 2022-04-15 14:51 UTC

**Comment by schklom** [comment] 2022-04-16 04:58
Discussion moved to https://community.signalusers.org/t/provide-option-to-allow-sms-from-oneself/43677

**Comment by schklom** [comment] 2022-04-19 10:46
@clauz9 I think I was a little condescending for no reason in my reply to you. Sorry about that.
