### ISSUE TITLE
Trying to forward a text message to existing contact

### ISSUE THREAD

**Issue by havdaddy** [signalapp/Signal-Android#11209] opened 2021-04-15 03:08 UTC
I have the latest versions of Android and Signal installed. When I try to forward a text to an existing contact that I have texted before, the contact does not show up as an option to forward two. Nor can I put the phone number in to forward to that contact. Only about 1/4 of all of my contacts show up - at the top it says recent chats (although they're not recent), and below that are contacts but only a few are available.  I have more recent activity with the contact I'm trying to forward the message to than the ones in the recent contacts list.

**Comment by greyson-signal** [comment] 2021-04-15 17:36
Closing as duplicate of #10929

**Comment by havdaddy** [comment] 2021-04-15 18:06
I'm sorry but this is not a duplicate of #10929. I'm not trying to forward to a non-signal contact - I'm trying to forward to a signal contact - one that's in my contacts list. As a matter of fact, it's my wife. I was able to do this as recently as a couple of months ago but now I cannot. 

⁣Get BlueMail for Android ​

**Comment by greyson-signal** [comment] 2021-04-20 13:01
Can you please provide a debuglog? Do you have the contacts permission enabled?

**Comment by havdaddy** [comment] 2021-04-20 14:06
https://debuglogs.org/521ea6e694136b8f696e656eb1bd551b4d3336dd716fdee9213b23f5e7e4cde2

Looks like it to me. 

⁣Get BlueMail for Android ​

**Closed** 2022-02-02 15:36 UTC
Labels: wontfix
