### ISSUE TITLE
[Bug] Can't Answer Call When Signal Desktop Is Open

### ISSUE THREAD

**Issue by zero77** [signalapp/Signal-Android#10623] opened 2021-01-14 13:05 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When signal desktop is open and you receive a call you get a notification on the desktop and a silent notification in the drop down menu in android.

When opening the notification on android and attempting to answer it neither the answer or reject buttons work and you get multiple missed call messages in the chat, once the caller stops calling.

### Steps to reproduce
- Open signal desktop
- Attempt to answer call from dropdown menu in android.
- Either whate for the caller to stop calling of force kill the app from settings in android.

**Actual result:**
The android device should wake up from sleep, with an on screen  option to either answer or reject the call.

### Device info

**Device:** Samsung S8 Plus
**Android version:** 9
**Signal version:** 5.1.8

### Link to debug log
https://debuglogs.org/52cec978c9593f2a91a6c92ccf1a66dcfc2fa2095e603438a7ed6d78c964936d

**Comment by cody-signal** [comment] 2021-04-03 20:32
Are you still encountering this on the latest versions of the Android and Desktop apps? I'm unable to reproduce so curious if it resolved itself. Thanks!

**Comment by zero77** [comment] 2021-04-04 10:34
I will keep an eye on it but, i think it has been resolved.

**Comment by cody-signal** [comment] 2021-04-05 14:02
Closing for now, can reopen if OP encounters the issue again.

**Closed by cody-signal** 2021-04-05 14:02 UTC
