### ISSUE TITLE
Image half displayed after sharing

### ISSUE THREAD

**Issue by Juri-w** [signalapp/Signal-Android#11550] opened 2021-08-18 16:27 UTC
After I share Images sometimes the images after sharing only half displayed.
An exaple is here:
![signal-2021-08-18-173227_](https://user-images.githubusercontent.com/65091932/129935608-10535a9f-96d2-45b7-81e5-fc81ec46cbf2.png)

Here the attached debugslog, the Image was send at 17:31.
https://debuglogs.org/e9006419c8ed29700085d22167d111be2176c1bd40a6b41943f80fdef508162d

**Comment by Tursko** [comment] 2021-08-18 18:07
Duplicate of https://github.com/signalapp/Signal-Android/issues/9082

**Closed** 2021-08-19 03:43 UTC
