### ISSUE TITLE
Exception when uploading profile Name and contacting Server config

### ISSUE THREAD

**Issue by muncescu1** [signalapp/Signal-Android#9372] opened 2020-01-29 12:07 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I am using the Signal Server Version 2.92 and the latest  Signal Android Version 4.54.2. 
When I try to set the profile name in the app I get "Bad response: 400 Bad Request", also
I get an error when starting the app when it tries to contact the endpoint "/v1/config", which is not implemented on the server.

### Steps to reproduce
- Build and install the latest Signal Server
- Build and install the latest Signal Android
- Change profile name

**Actual result:** 
For the first issue with setting the profile image:
`2020-01-29 13:45:08.931 15058-15199/com.myapp I/InAppScheduler: Triggering a job retry.
2020-01-29 13:45:08.953 15058-15219/com.myapp I/JobRunner: [JOB::745d90d5-20dd-4f0e-9520-1e1157be00a2][ProfileUploadJob][1] Running job. (Time Since Submission: 1272846 ms, Lifespan: Immortal, Run Attempt: 46/Unlimited)
2020-01-29 13:45:08.964 15058-15219/com.myapp W/PushServiceSocket: Push service URL: https://myapp.com
2020-01-29 13:45:08.964 15058-15219/com.myapp W/PushServiceSocket: Opening URL: https://myapp.com/v1/profile/name/vymS7Qyy8mPs2dM38eFaI%2BXJBOnks7rjOke5zNoIXKy8NdkveYf4tY6AmYfE2INCE92tfd2av3BjJo%2Bjxxmt1i3ltJdpyJBXE%2FDYDWidKYOX
2020-01-29 13:45:09.272 15058-15219/com.myapp I/BaseJob: [JOB::745d90d5-20dd-4f0e-9520-1e1157be00a2][ProfileUploadJob] Encountered a retryable exception. (Time Since Submission: 1273164 ms, Lifespan: Immortal, Run Attempt: 46/Unlimited)
    org.whispersystems.signalservice.api.push.exceptions.NonSuccessfulResponseCodeException: Bad response: 400 Bad Request
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1112)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1004)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.setProfileName(PushServiceSocket.java:562)
        at org.whispersystems.signalservice.api.SignalServiceAccountManager.setProfileName(SignalServiceAccountManager.java:589)
        at org.thoughtcrime.securesms.jobs.ProfileUploadJob.uploadProfileName(ProfileUploadJob.java:75)
        at org.thoughtcrime.securesms.jobs.ProfileUploadJob.onRun(ProfileUploadJob.java:50)
        at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:21)
        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:82)
        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:46)
2020-01-29 13:45:09.275 15058-15219/com.myapp I/JobRunner: [JOB::745d90d5-20dd-4f0e-9520-1e1157be00a2][ProfileUploadJob][1] Job finished with result: RETRY (Time Since Submission: 1273168 ms, Lifespan: Immortal, Run Attempt: 46/Unlimited)
`
The second issue with the remote configuration:
`2020-01-29 13:53:13.998 20857-21017/om.myapp W/BaseJob: [JOB::2fdf8dfc-623e-4bc9-9476-6d68683fabd2][RemoteConfigRefreshJob] Encountered a failing exception. (Time Since Submission: 772 ms, Lifespan: 86400000 ms, Run Attempt: 1/Unlimited)
    org.whispersystems.signalservice.api.push.exceptions.NotFoundException: Not found
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1051)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1004)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.getRemoteConfig(PushServiceSocket.java:760)
        at org.whispersystems.signalservice.api.SignalServiceAccountManager.getRemoteConfig(SignalServiceAccountManager.java:518)
        at org.thoughtcrime.securesms.jobs.RemoteConfigRefreshJob.onRun(RemoteConfigRefreshJob.java:44)
        at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:21)
        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:82)
        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:46)`

**Expected result:** 
Since the latest version of the Signal Server is not updated, there should be a fallback to work with the old version of the server, or try to keep the Signal Server up to date.

**Comment by greyson-signal** [comment] 2020-01-29 15:12
Closing this because it's not a bug with the Android app. The server repository will update eventually. If you're already running your own server, it means you're running your own build of the Android app. In this case, I'd advise that you run an older Android version until the server is updated.

**Closed by greyson-signal** 2020-01-29 15:12 UTC
