### ISSUE TITLE
can't reply to group after reinstalling textsecure

### ISSUE THREAD

**Issue by agrajaghh** [signalapp/Signal-Android#2581] opened 2015-03-05 11:09 UTC
If I receive a group message to a group I'm member of after uninstalling/reinstalling TS, I can't send messages.

Steps to reproduce:
1) Device A creates a group with device B
2) Device B receives the group creation message
3) Device B uninstalls TS
4) Device B installs TS again and registers for push messages
5) Device A sends a message to the group
6) Device A verifies the new identity of device B
7) Device B receives the group message in an "Unnamed group". Device B is unable to reply. Its not possible to set the focus in the textfield/open the keyboard.

Debug log of Device B: https://gist.github.com/anonymous/b63eb752fdb728ff14c4

Tested with current HEAD

**Comment by tinloaf** [comment] 2015-03-05 11:59
Try re-adding Device B to the group on Device A. This should cause A to send the group-info to B again. I've had this problem quite a few times myself, some solution to this would be nice.

How about this: When B receives a message for an unknown group, it automatically sends a (silent) message to A saying 'please send me the group data' and displays something like 'fetching group information' in the thread. B then (automatically, silently) responds with the group info and everything is OK?

**Comment by agrajaghh** [comment] 2015-03-05 12:09
You're right. Adding B again works... But its just a workaround...

I think it could be done easier (async, without first requesting the group info):
When A tries to send the message to the group and has to verify the new identity, A knows the key of B changed. So A can directly send the group information to B.

I don't know how it is in bigger groups. What if A stays the 'group leader' and C sends the message to B? Can C send the group information to B? Will A do it again, if A writes a message? Possible solution could be, that B sends a silent message to the group once it received the group information to (mostly) avoid multiple group information messages.

**Comment by tinloaf** [comment] 2015-03-06 12:51
Correct me if I'm wrong, but there should be no such thing as a "group leader"? Everyone has the same information. Also, a device could for some reason (restoring an old Titanium Backup or something like that) forget a group, but not the key. Then, your solution would not work.

**Comment by agrajaghh** [comment] 2015-03-06 13:33
Oh, you're right, there is no group leader. But that means every group member can forward the group information to Device B, no? Your concern is that group members may forward wrong/outdated information to B?

**Comment by tinloaf** [comment] 2015-03-06 15:10
No, the question is just how those group members notice that they have to send the data to Device B. As I said, looking for a changeg key may not always be sufficient.

**Comment by manhole11** [comment] 2015-03-24 13:46
I have the same problem here

**Comment by rhodey** [comment] 2015-04-10 17:55
referencing #2185, #1254, & #1048

**Comment by gravyboot** [comment] 2015-04-12 17:52
Confirming same/similar issue on lollipop - 
- I created (and named) a group on different device, changed devices (same phone number)
- installed TS on new device, registered/verified no problems
- received new group message from someone in the same group, now shows as 'unnamed', can't rename
- group selection shows only member is "me"
- can't reply.  the only field in reply area that responds to a tap is the emoji field
- I can switch to the keyboard by clicking the keyboard icon from the emoji drawer, but no text displays upon typing

**Comment by Rocksteady18** [comment] 2015-05-21 17:03
I have a phone with kitkat and same thing, unnamed, can't rename or respond.

I was in a group and had to reinstall because of a corrupt key or something where it stopped encrypting.

Now when I get a group text, I get the text but when I tap the response area I never get a cursor; "it" won't let me respond.

**Comment by brumsoel** [comment] 2015-05-22 09:59
@Rocksteady18 As a quick workaround, ask a member of your group to do a group update (Settings button -> "Update group" and just confirm the update - there should be no need to actually change the group information). After you received the update, your client will know the group name and be able to post to it again.

**Comment by McLoo** [comment] 2015-05-22 13:47
Reason for not being able to to group stuff in such an unnamed group most likley is that the group is not set to active, which is done here: https://github.com/WhisperSystems/TextSecure/blob/master/src/org/thoughtcrime/securesms/groups/GroupMessageProcessor.java#L129 and on creating a group

Forgot to press comment this morning :) @brumsoel has your workaround
~~If I'm right the update will trigger the group to be active for you on your device, re-enabling you to do as you please :)~~

**Comment by Rocksteady18** [comment] 2015-05-22 16:35
I did what brumsoel said and it now works, has the right name, and I can text, thank you guys, great product.

**Comment by ph0b0z** [comment] 2015-12-03 13:09
We just ran into the same problem, since i re-flash my device quite regularly (sorry..) i broke a group again. Re-inviting me or changing the group name didn't help. The group members received "not delivered" error-message, even after i left the group. :)

**Comment by haffenloher** [comment] 2015-12-03 14:24
> The group members received "not delivered" error-message

They probably need to accept your new identity key before being able to send you messages and group updates (and receive group updates from you, saying @ph0b0z left the group) again. I think they just need to send you a one-on-one or group message, it should fail and display a "Verify" button.

Next time you have a support question, please use http://support.whispersystems.org (search the FAQ or submit a request) instead of the issue tracker :)

**Comment by farao** [comment] 2016-03-17 13:08
Problem still exists, is this being worked on? Can't a newly installed Signal iterate all "unknown" groups and automatically ask for a group update? This can't be wanted behaviour that every time you have a new device or reinstall Signal all the groups are broken and you have to contact for every group a member to update it, right?

**Comment by vanitasvitae** [comment] 2016-06-23 07:11
Interesting side fact:
When I connect my phone to Signal desktop while the phone displays an unknown group, the desktop app does not face the problem. There, I can see members, group name, Avatar... So it should be possible to fix.

**Comment by kanytu** [comment] 2016-06-29 11:38
Is this still open? More than one year later? In Chrome app this is working as expected, no need to edit a group whatsoever.

**Comment by kehugter** [comment] 2016-08-08 00:22
I also have issues. 2 group members (alice and bob) have new keys, now the communication is a mess:

- alice and bob can't write to the group in using the Android app
- alice can write to the group from the desktop app
- bob gets messages from only 3 of 6 group members in the Android app
- alice gets messages from 5 of 6 group members in the desktop app
- alice gets messages from 4 of 6 group members in the Android app

All participants already accepted alice's and bob's new keys.

**Comment by avh-on1** [comment] 2016-10-09 07:07
Just experienced this same problem. I couldn't bring up the keyboard to type messages into a group chat. The problem was fixed by getting another group member to re-add me to the group. It would be great if this bug was fixed, I was out of the chat for a couple of days before I could contact one of the members.

**Comment by pythoneer** [comment] 2016-10-13 13:56
Same happened here but the other where unable to reinvite me. The Desktop App had no issues whatsoever, but a renaming of the then called "unnamed group" from another groupmember (or changing the image) fixed for me and i can continue to send messages to the group.

**Comment by jeremymasters** [comment] 2016-10-14 15:19
All I had to do was to have one of the other members (texted them separately) to update the group, even if they don't make any changes it works.

**Comment by joshuap** [comment] 2016-11-30 06:18
I ran into this too (found this issue before creating a bug report). As a developer I'm fine with workarounds, but it's difficult to explain this sort of thing (or why they should use an app which doesn't "just work") to my non-developer friends.

**Comment by Trolldemorted** [comment] 2016-11-30 09:32
@joshuap moxie is [working on it](https://github.com/WhisperSystems/Signal-Android/tree/moxie/group_recovery).

**Comment by 2-4601** [comment] 2016-12-01 20:54
Fix in 3.24.0 (cf01959e16acc1ff31cd007d68b3ba43810b6c3a)

**Comment by zxvv** [comment] 2017-02-02 16:27
After a factory reset, and reinstalling signal 3.28.4, there are no contacts in android.  After using desktop to sending a message to a group,  I see the message, but the group is named "unnamed group" and has no contacts on android, while the desktop signal shows group name and group members.

**Comment by joshtriplett** [comment] 2017-02-04 04:08
I still experience this problem with current Signal, after migrating to a new phone.  The workaround (having someone "update group") worked, but Signal did not handle this automatically as https://github.com/WhisperSystems/Signal-Android/commit/cf01959e16acc1ff31cd007d68b3ba43810b6c3a suggests it should.  And even with that workaround, everyone in the group (along with all other messages) just shows up as a phone number, despite having a named contact entry with that number.

**Comment by 2-4601** [comment] 2017-02-04 14:06
So what happened when someone just sent a message to the group (before the group update workaround)?

**Comment by joshtriplett** [comment] 2017-02-04 14:28
@2-4601 I received the message, but the group remained "Unknown group", didn't have the group icon, and touching the text box didn't bring up a keyboard or allow typing.

**Comment by 2-4601** [comment] 2017-02-04 14:39
Did you by any chance happen to get a debug log? :)

**Comment by joshtriplett** [comment] 2017-02-04 14:43
@2-4601 I did not, sorry.

If it helps: Signal 3.29.1, though the problem persisted through many past versions.

**Comment by haffenloher** [comment] 2017-02-04 14:46
was the sending device an iPhone? cf01959e hasn't been implemented on iOS yet

**Comment by joshtriplett** [comment] 2017-02-04 17:10
On February 4, 2017 3:46:21 PM GMT+01:00, haffenloher <notifications@github.com> wrote:
>was the sending device an iPhone? cf01959e hasn't been implemented on
>iOS yet

Some of the senders used iOS, and some used Android.

**Comment by 2-4601** [comment] 2017-02-06 13:39
> Some of the senders used iOS, and some used Android.

Do you mean that you received messages from both iOS and Android users before the group update workaround was used?

**Comment by joshtriplett** [comment] 2017-02-06 20:12
On February 6, 2017 7:39:33 AM CST, 2-4601 <notifications@github.com> wrote:
>> Some of the senders used iOS, and some used Android.
>
>Do you mean that you received messages from both iOS and Android users
>before the group update workaround was used?

Yes.

**Comment by Trolldemorted** [comment] 2017-02-06 23:18
@joshtriplett are these android users running an up-to-date version of signal?

**Comment by joshtriplett** [comment] 2017-02-08 02:05
@Trolldemorted One of the Android users was running 3.28.4.  I think that's the latest non-beta version?

**Comment by Dannyzen** [comment] 2017-02-10 14:05
I was able to reproduce this issue from start to resolution. Renaming the room fixed.

**Comment by Trolldemorted** [comment] 2017-02-10 23:40
If you want to investigate whether your contact's signal is responding to your group updates correctly:

- link a [signal-cli](https://github.com/AsamK/signal-cli) instance to your account (use[ v0.5.2](https://github.com/AsamK/signal-cli/releases/download/v0.5.2/signal-cli-0.5.2.tar.gz), not v0.5.3)
- let your signal-cli receive messages so that it syncs the groups from your master
- remove the group from signal-cli's json storage (edit ~/.config/signal/data/YOURPHONENUMBER and remove it from the "groups" array)
- make them send a group message
- let your signal-cli receive messages (it will send a group info request now)
- let your signal-cli receive again, it should receive and print the group info request and save the group again

**Comment by hoodie** [comment] 2017-03-05 12:38
So this is still an issue, I reregistered on a new phone and all groups were gone until somebody wrote something. Updating groups is not possible until somebody else does it. How is this still a thing :D ?

**Comment by haffenloher** [comment] 2017-03-07 01:02
> I reregistered on a new phone and all groups were gone until somebody wrote something.

@hoodie That's expected behaviour as group info isn't stored server-side. As soon as you get a message _from an Android user_ in a group that is unknown to your Signal client, it should automatically request the group info from the sender (Name, avatar, list of members). Do you experience problems with that?

**Comment by hoodie** [comment] 2017-03-07 14:56
I reregistered on a new phone and had no groups. I then added the desktop app, there I saw groups, when I posted in one that I had created earlier it showed as "unnamed/unknown Group" (don't recall exactly). I was not able to edit or even leave the group until somebody else had changed the name of the group.
What kind of state am I in at that point? Why is it different after somebody made a change? Why can't I leave the group? Why does it work on the desktop client thought?

**Comment by Trolldemorted** [comment] 2017-03-07 15:08
The desktop client still uses the database it had before you registered on your new phone.

Naturally, it contains the groups from "back then", and is able to send messages (to the participants from that time). Your new phone does not know the group, receives a message from your desktop, notices that the group is unknown, sends a group info request to the sender (aka you), your desktop does not respond (https://github.com/WhisperSystems/Signal-Desktop/issues/1037), and thus the group remains unknown on your phone.

**Comment by jacobklan** [comment] 2017-09-13 07:40
Replicated issue just now on Signal 4.10.8 for Android. Debug log here (captured just after multiple messages from said group): https://gist.github.com/anonymous/569ee712301eb94e5f2d6f70af96b2f8

Group chat with 1 Android and 1 iOS client, both on latest stable. Wouldn't recieve group info despite multiple messages until one member updated the group information.

**Comment by automated-signal** [comment] 2018-04-02 21:33
GitHub Issue Cleanup:
See #7598 for more information.

**Closed by automated-signal** 2018-04-02 21:33 UTC
Labels: bug
