### ISSUE TITLE
java.lang.NegativeArraySizeException during Import crashes App

### ISSUE THREAD

**Issue by mad-de** [signalapp/Signal-Android#9186] opened 2019-11-13 12:48 UTC
- [x] I have searched open and closed issues for duplicates (https://github.com/signalapp/Signal-Android/issues/9154 is similar but a different error)
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Importing my 4.21 GB backup crashes after reaching one of the last or even the last message.

### Steps to reproduce
- Import backup-file

**Actual result:** Signal crashes 
**Expected result:** Database successfully imported screen

### Device info
**Device:** Xiaomi Redmi Note 4 (lineage_mido)
**Android version:** 10 (eng.giasen.20191027.101111, lineage_mido-userdebug 10 QP1A.191005.007 eng.giasen.20191027.101111 test-keys)
**Signal version:** 4.49.18 (5652)

### Link to debug log
https://debuglogs.org/26f95c05a37f202c28e4aa24c8fbbf2500dd76f7adc257cc630c6614aad5dc78

**Comment by greyson-signal** [comment] 2019-11-13 16:11
Duplicate of #9154

**Closed by greyson-signal** 2019-11-13 16:11 UTC
