### ISSUE TITLE
Feature Request: Please bring back the ability to share with more than top 5 groups

### ISSUE THREAD

**Issue by fongaboo** [signalapp/Signal-Android#7421] opened 2018-02-16 22:29 UTC
I have:
- [X ] searched open and closed issues for duplicates
- [X ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Ever since an update late last year, when you would share something from other apps to Signal it would only give you the option to select the 5 most recent group chats.

### Steps to reproduce
- In any other app, tap the share three-dot/less-than icon to share something... a link, an image, audio...
- In the list of available apps, choose Signal
- User is presented with entire list of individual Signal contacts, but only the last 5 recently used group chats

**Actual result:** Can only share with the 5 most recent group chats
**Expected result:** Ability to share with any and all group chats listed in chronological order

### Screenshots
![signal-2018-02-16-175038](https://user-images.githubusercontent.com/29614651/36332992-7da93ab4-1342-11e8-9ae4-2d661aaf46f4.png)
Only two of my group chats are in the top 5 at the moment. Three of the entries are individuals, which is redundant since all individual contacts are accessible immediately below. Another idea is, if a combined, abbreviated 'Recent Chats' section is desired, add another comprehensive 'Group Chats' section as well. The fact that any group chat is inaccessible from this interface is a real problem.

### Device info

**Device:** OnePlus 5
**Android version:** 7.1.2 LineageOS 14.1-20171009
**Signal version:** 4.15.5

### Link to debug log
(Feature restoration request)

The ability to share items with many groups was an important piece of functionality for me. On any given day I am juggling multiple group discussions on Signal. Often I have to share something with multiple groups in one instance, including groups I may not have been active in for a while.

This often means attempting to share to Signal, discovering the intended group is not in the top 5, then having to go back to the originating app, copy the link or media to clipboard, then back to Signal and manually paste. Having to repeat this for many groups in one sitting is a frequent reality for me now and it's cumbersome and slow.

It is especially unwieldy when sharing media (image, audio, video) because often it precludes the ability to cut and paste, so I have to switch out of the originating app, go into Signal, find the intended group, type a period so that the group registers in the top 5, then return the originating app, share, choose Signal, choose the group.

I urge you to avoid revisions that remove functionality. I had been running a deprecated version of Signal to maintain this functionality, but it expired, forcing me to upgrade. If there had been some concerns about the number of group chats listed in the share interface, may I suggest that you add a setting to specify the number of group chats that get displayed, set the default to 5, but allow the user to adjust it.

Thanks again for all your work in bringing Signal to society.

**Comment by FeuRenard** [comment] 2018-02-16 23:06
This is a duplicate of #7202.

**Comment by Wikinaut** [comment] 2018-02-17 00:37
If you can build Signal by yourself: this is fixed in my pull request https://github.com/signalapp/Signal-Android/pull/7416 .

**Comment by fongaboo** [comment] 2018-02-17 01:35
Thanks. Above my paygrade unfortunately. Nowhere to get binaries?

**Closed** 2018-02-17 05:00 UTC
