### ISSUE TITLE
first chat doesn't open when phone system is on Hebrew

### ISSUE THREAD

**Issue by yigals** [signalapp/Signal-Android#12264] opened 2022-05-24 19:34 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When phone system is on Hebrew, tapping the first chat in the list doesn't open the chat, but instead opens the chat details as if selected the chat image. In English all works well.
This reproduces on several Samsung phones as well.
Workaround: first select "search", then tap first chat

### Steps to reproduce
- switch system language to Hebrew (possibly other languages, maybe RTL)
- tap first chat

**Actual result:** chat info opens as if tapped the chat image
**Expected result:** chat opens

### Device info

**Device:** Redmi Note 7
**Android version:** 11
**Signal version:** 5.38.5

### Link to debug log

https://debuglogs.org/android/5.38.5/f2a73617581cb0da8d6985b0cb2aa4a9ee8efb97d32dd945369c6d71600dfba1

**Comment by alex-signal** [comment] 2022-05-26 12:18
@yigals The hotfix commit fixing the issue is at `926e3541e` whereas the mainline fix is in `ff4311d`

It's the exact same change in both cases, we just needed to make sure the avatar touch delegate rectangle is measured correctly based off the layout direction.

**Comment by clauz9** [comment] 2022-06-03 18:39
so... 🤔  this can be closed right ?

**Closed** 2022-06-05 17:34 UTC
