### ISSUE TITLE
Options to disable the "BEEP" at the end of voice messages

### ISSUE THREAD

**Issue by Krafting** [signalapp/Signal-Android#10154] opened 2020-10-31 16:25 UTC
- [ ] I have searched open and closed issues for duplicates
- [ X ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
when listening to an audio message; at the end, there is a "beep" sound. this is really annoying. sometimes; we need to turn up the volume because the person doesn't talk loudly; but the beep is extremely loud; and I just doesn't like that; I'd love a button to turn of this feature. (Note: this doesn't happen in the Desktop version, at least on linux)

### Steps to reproduce
- Listen to an audio message

**Actual result:** BEEP Sound
**Expected result:** Ability to disable it.

### Device info

**Device:** Note9 Samsung
**Android version:** 10.0
**Signal version:** 4.75.4

**Comment by Genis-Sage** [comment] 2020-10-31 17:14
Hey @Krafting 

Welcome to the Signal Android bug tracker

Please look for existing issues first, and only open a new issue, if you can mark all four check boxes
(they are meant as check list, and not as selection)

And your issue is a duplicate of #10150 which is from yesterday, so quite easy to find

**Comment by greyson-signal** [comment] 2020-11-02 13:30
Closing as a duplicate of #10150

**Closed by greyson-signal** 2020-11-02 13:30 UTC
