### ISSUE TITLE
No option to export anymore

### ISSUE THREAD

**Issue by LoveIsGrief** [signalapp/Signal-Android#7565] opened 2018-03-25 11:41 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description

Since the update to 4.17.5 the export option has disappeared entirely and only the import option remains. It was on 4.16.9 just before the update and I successfully exported my messages in plaintext. The update was an attempt to get the possibility to export media (supposedly in beta with #1619)

**Additional information**

I tried registering to the beta program after the export option disappeared and it didn't help.

### Steps to reproduce

 - Open Signal
 - Open the burger menu

**Actual result:** "Import" is the only option in the dropdown
**Expected result:** "Import/Export" option should be visisble

### Screenshots

- App doesn't allow taking screenshots

### Device info
**Device:** ONEPLUS A3003
**Android version:** 8.0.0
**Signal version:** 4.17.5

**Comment by 2-4601** [comment] 2018-03-25 13:17
Duplicate of #7473.

The export feature has been moved under Settings.

https://community.signalusers.org/t/signal-beta-4-17-4-export-function-missing/2154/2
>The 4.17 beta includes new functionality for a full encrypted backup of all messages and attachments. The new backups live the Signal settings under “Chats and media > Backups”. Unfortunately, this means that an export to Android Messages is no longer possible.

**Closed by 2-4601** 2018-03-25 13:17 UTC

**Comment by johanw666** [comment] 2018-03-28 00:10
But that's the full backup, which is quite buggy for some people (I can't get it to work at all even with a fresh setup with ony 2 test messages).

**Comment by tacobeard** [comment] 2018-08-22 06:02
The inability to export plain text backups really is a bummer.  I store messages in a secure location and sort them automatically after the fact.  Or at least used to :(

**Comment by dj-si** [comment] 2018-09-14 13:59
> The inability to export plain text backups really is a bummer. I store messages in a secure location and sort them automatically after the fact. Or at least used to :(

I recently found this thread, mentioning a utility called signal-back:

[https://community.signalusers.org/t/lets-talk-about-backups/2237/32](url)

The signal-back utility is available at the URL below, and I've used it successfully (on Win10) to extract messages in plain text (XML) from Signal encrypted backup files. (It can also extract to CSV, though I haven't tried that yet.)

[https://github.com/xeals/signal-back](url)

**Comment by thrdroom** [comment] 2019-09-26 09:21
It's really a shame that the folks decided to lockup signal even more and make it a walled garden...i don't understand why they removed the option to export only the sms-messages from signal to a format(xml) which is then readable from other apps. I now have the case, that i want to stop use signal as my main sms-app and switch to [silence.im](https://silence.im/) for that but i cant export only the sms from the signal install...also signals import-feature is gone, which means: if i ever want to leave or come back to use signal as my main sms-app i can't import nor export my sms. I dont understand, why someonce does this, remove a fully developed feature and dumb down his own software for no good reason.

**Comment by alan-signal** [comment] 2019-09-26 14:32
Please use the community forum for discussions https://community.signalusers.org/

**Comment by ekkis** [comment] 2019-10-05 17:38
I've used Signal for a long time.  I trust it.  but my ability to export a chat (so I can delete it) is critical to the value the product adds.  I cannot understand why this functionality would be removed.  it's a strong reason for me to abandon the product
