### ISSUE TITLE
MMS are either not received or delayed for up to 24 hours. Pixel 3 XL.

### ISSUE THREAD

**Issue by yuslepukhin** [signalapp/Signal-Android#9172] opened 2019-11-09 01:38 UTC
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
MMS messages addressed to me with photos OR simply long text are not received. At other times they are received with up to 24 house delay.

### Steps to reproduce
I have Wi-Fi features on at all times.

**Actual result:** MMS addressed to me are not received.
**Expected result:** I'd like to receive MMS.

### Screenshots
None

### Device info

**Device:** Pixel 3 XL
**Android version:** Android 10 Build Number QP1A.19005.007
**Signal version:** 4.49.17

**Comment by strugee** [comment] 2019-11-09 20:03
Looks like a duplicate of #9174. That one was filed later, but it also has a debug log which this one doesn't so it's more actionable.

**Comment by yuslepukhin** [comment] 2019-11-09 23:10
From the description it does look different. In this issue the MMS does not show up at all. I learnt about those messages postfactum or as a result of experiment. Asked someone to send MMS to me and it never shows up in any form.

Dmitri

________________________________

**Comment by strugee** [comment] 2019-11-10 03:28
Got it. Please post a debug log then.

**Comment by strugee** [comment] 2019-11-10 04:28
You might also try switching to the default Android messaging app temporarily, and getting a friend to send you a test message. That would eliminate carrier issues as the cause.

**Comment by yuslepukhin** [comment] 2019-11-10 15:54
Will post debug log soon. Stock Messaging works perfectly well on Google Fi.

Dmitri

________________________________

**Comment by yuslepukhin** [comment] 2019-11-10 22:07
https://debuglogs.org/b9c484b854c6015c7358779f086e3094db8bf814da668cca65cfb7da83ad8c3b debug log

Dmitri

________________________________

**Comment by amcguier** [comment] 2019-11-10 22:10
I can replicate this, I'm on release version, pixel 4. I also don't receive MMS and I get no notification that I missed any MMS messages.

[Debug log](https://debuglogs.org/4db082c5a388921fee00a30ff5f76a5c97a2a152d3ca9d93f22c0f82cba854f3) 

An MMS was sent and not received during this window.

**Comment by Cerberus0** [comment] 2019-11-11 00:29
Possibly related to https://github.com/signalapp/Signal-Android/issues/9013, which is tracking an MMS issue experienced by Google Fi users.

**Closed** 2022-02-04 08:38 UTC
Labels: wontfix
