### ISSUE TITLE
Saving media to storage fails without error

### ISSUE THREAD

**Issue by andrazznidar** [signalapp/Signal-Android#9440] opened 2020-03-03 06:54 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
This issue is very similar to issue #9415, might be a duplicate.

When I try to save one specific video (video can be played normally inline) to storage, I receive a toast notification that it has been saved to Movies, but in fact it has not been saved.
Other videos can be saved normally.
Saving this specific video on Signal Desktop reveals `.*` filename extension.

### Steps to reproduce
- Try to save a playable video to storage.
    - long-press on video, Save attachment, YES; or
    - play video, three dots, save, YES
- Receive a toast notification claiming that the video is saved.

**Actual result:** Video is claimed to be saved to storage, but it is not.

**Expected result:** Video is saved to storage. Or show an error explaining why it cannot be saved.

### Screenshots

There is nothing interesting to screenshot.

### Device info

**Device:** Samsung Galaxy S8+, Xiaomi Pocophone F1
**Android version:** 9, 10
**Signal version:** 4.55.8

### Link to debug log

https://debuglogs.org/90419219e7ad48b4359ec138c4d8b346a949f5f999ef8dbc26757413414be436
I have tried to save the video sometime after 2020-03-01 17:12:00.000 GMT+01:00

`2020-03-01 17:12:13.791 GMT+01:00 W SaveAttachmentTask: mkdirs() returned false, attempting to continue`

**Comment by guimspace** [comment] 2020-03-03 15:14
greyson says it is fixed in 4.56.2, and I guess he refers to commit 6184e5f. You can go to Google Play Store and join the beta channel of Signal to test if the issue is fixed and give feedback as well.

**Comment by andrazznidar** [comment] 2020-03-04 06:46
This issue is still present in Signal 4.56.4.

New debug log: https://debuglogs.org/eda2cfc22159abf9e64589494bbdb7742990e74ac4ac01ab13177d56821a2c71
`2020-03-04 06:07:06.266 GMT+01:00 W SaveAttachmentTask: mkdirs() returned false, attempting to continue`

**Closed** 2022-02-04 02:04 UTC
Labels: wontfix
