### ISSUE TITLE
v4.79.3 website release - Downloaded APK doesn't match digest...

### ISSUE THREAD

**Issue by Lion-box** [signalapp/Signal-Android#10255] opened 2020-12-05 22:42 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Android website release doesn't auto-upgrade to v4.79.3 because sha256 sum at  [https://updates.signal.org/android/latest.json](https://updates.signal.org/android/latest.json) doesn't match downloaded apk file. 

[4.78.5] 2020-12-05 23:15:21.033 CET W UpdateApkReadyListener: Downloaded APK doesn't match digest...

### Link to debug log
https://debuglogs.org/16f8ffdf94e2edbe7c5c2c40c1fe3c172a159c559cfab47b903f669e03cf1c47

**Comment by jtracey** [comment] 2020-12-10 00:57
I'm also seeing this, and confirmed a friend of mine is as well.

**Comment by doolo** [comment] 2020-12-11 17:52
The sha256 sum of `Signal-Android-website-prod-universal-release-4.79.3.apk` ([archive](https://web.archive.org/web/20201208184403/https://updates.signal.org/android/Signal-Android-website-prod-universal-release-4.79.3.apk)) is still different from what appears at https://updates.signal.org/android/latest.json ([archive](https://web.archive.org/web/20201211174236/https://updates.signal.org/android/latest.json)).

**Comment by greyson-signal** [comment] 2020-12-11 23:04
Yeah, so I think I screwed this up because I was updating some build scripts, and it ended up putting the sha256 of the unsigned APK in the latest.json on accident. Should be fixed now, lmk :+1:

**Closed by greyson-signal** 2020-12-11 23:04 UTC

**Comment by jtracey** [comment] 2020-12-11 23:16
Yup, just got the update. Thanks!
