### ISSUE TITLE
Add option to automatically/scheduled backup of SMS - Feature request

### ISSUE THREAD

**Issue by X-Ryl669** [signalapp/Signal-Android#6012] opened 2017-01-05 16:24 UTC
Currently, Signal plays in its own ballpark concerning SMS/MMS storage.
This breaks the SMS backup tools out down there (like *SMS Backup & restore*, *SMS Backup +*) because Signal does not fill the system's message storage.

This is fine, in terms of security of the message, however, it's not in terms of data security which will be lost if the phone is reset / lost etc...

I've seen the option to backup the sms to a file that's compatible with the format of *SMS Backup & restore*, but I have to trigger it manually (which is a pain), and yet, it does not all *SMS Backup & restore* to use it automatically (*SMS Backup & restore* does not see any new message, and as such does not upload the file.

So, there are 2 possible options here:

1. Add some scheduling mechanism to auto-backup the SMS in Signal (and expect some third party tool like *rsync* or *syncthing* to upload it to a server), but this defeat the security of Signal, since you now have a clear text copy of the SMS on the phone that accessible for anyone
2. Add some server upload feature to send the SMS/MMS directly to a server (every day, upon message receiving, etc...), but this requires some work server side to deal with the data. Ideally, you could create a JSON file containing all messages encrypted with a user's password key (from KDF) and post that to an GUI set up URL (let the open source community implement the server side code) and for restoring GET the same URL and ask the user's password to decrypt the JSON file.

I think the 2nd case will be easier to implement, and makes *SMS backup & restore* useless.

**Comment by FeuRenard** [comment] 2017-01-05 16:27
Duplicate of #339?

**Comment by X-Ryl669** [comment] 2017-01-05 16:46
The difference is that @moxie0 expect something to work with *SMS Backup & restore*, see PR #5907. I don't think it's the way to go for 3 reasons:
1. The XML format *SMS Backup & Restore* is not made for storing this information encrypted.
2. Even if it did, it'd still not work correctly, since most of the features for this software is based on monitoring the Android's message store and since there is no change, those features are failing.
3. This makes Signal dependent on a closed source third-party application that can decide to change the XML format tomorrow. 

I think it'd would be easier to completely drop this idea and instead implement an encrypted serialization of the Signal's message store as JSON and post that to a user-defined URL (respectively, get that from this user-defined URL). The URL could be local to store to the filesystem, or remote via HTTP. That way, you are not dependent on a third party application & format, there's less effort to try to fit circles in a cubic hole, and you let the user implement their own storage mecanism.

**Comment by lbarnett83** [comment] 2017-09-27 01:50
What about baking in support for Signal to create an encrypted backup of messages, which the app then can upload to GDrive, or a similar location, along with that ability to schedule this upload. Then you can also add in a restore function as well?  Keeps the messages encrypted, but still offer some data security?

**Comment by whysyn** [comment] 2017-11-30 18:02
I'd like to add my voice to the chorus here.

At minimum, could Signal push non-secure SMS/MMS messages back into the system message store so they will be automatically backed up by Android?  I'm partially OK with losing my secure messages, but no backup almost a dealbreaker for using Signal as my default messaging app, given how much work-related stuff goes over SMS/MMS now.

Ideally, I'd like to see an encrypted backup (possibly with a user-defined pre-shared key?) that will upload to GDrive, DropBox, OneDrive, or similar.

**Comment by automated-signal** [comment] 2018-04-03 01:01
GitHub Issue Cleanup:
See #7598 for more information.

**Closed by automated-signal** 2018-04-03 01:01 UTC
