### ISSUE TITLE
while calling from higher versioned device to lower, other phone gets a missed call message.

### ISSUE THREAD

**Issue by biplabbh** [signalapp/Signal-Android#8267] opened 2018-10-10 12:33 UTC
I have the problem while calling from lower versioned android device to Higher versioned android device.  When I am calling from a higher versioned device to a lower versioned device, the call is working fine, but when I am trying to call a higher versioned device from a lower versioned device the connecting option is shown from the calling device, but no call actually goes to the another phone. Instead of that the other phone gets a missed call message.

I have seen people have asked the question previously, but no one actually said anything, no answers or resolutions from anybody.

So I just wanted to check if anybody solved that issue by now?

I am stuck with that. I know you people did a great job till now..Please help to resolve instead of making it as duplicate, because it was not solved previously..please help..

**Comment by greyson-signal** [comment] 2018-10-10 17:37
Hi there, when it comes to these types of issues, we really need the details requested in the issue template. Things like device models, specific Android versions, and debug logs. In this case, it'd be most helpful to have all of these details for both devices involved in the calls. Otherwise, there really isn't much for us to go on. I'll post the template here for reference, but this is what you should see after clicking the "new issue" button.

In addition, if you know there's an existing issue, you should be posting these details on that existing issue. That way we can build up a set of knowledge around a bug. That's particularly important for issues like these, where they're highly device-dependent and incredibly difficult for us to reproduce.

Because you said there's an existing issue, I'm going to close this one. Please collect this data and post it on the relevant issue. Thanks!

> \
> 
> - [ ] I have searched open and closed issues for duplicates
> - [ ] I am submitting a bug report for existing functionality that does not work as intended
> - [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
> - [ ] This isn't a feature request or a discussion topic
> 
> ----------------------------------------
> 
> ### Bug description
> Describe here the issue that you are experiencing.
> 
> ### Steps to reproduce
> - using hyphens as bullet points
> - list the steps
> - that reproduce the bug
> 
> **Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
> **Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
> 
> ### Screenshots
> \
> 
> 
> ### Device info
> \
> **Device:** Manufacturer Model XVI
> **Android version:** 0.0.0
> **Signal version:** 0.0.0
> 
> ### Link to debug log
> \
>

**Closed by greyson-signal** 2018-10-10 17:37 UTC
