### ISSUE TITLE
Non securized messages

### ISSUE THREAD

**Issue by LilianCruanes** [signalapp/Signal-Android#8773] opened 2019-04-19 11:35 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Since yesterday, when I want to send a message to my friend, my message is not send as "Signal datas", but I receive them messages as securised by Signal.
In the other hand, all my other conversations work fine, the problem is just with this friend.
When I am on the desktop Signal version, I can only see the messages sent by my friend (messages that have been sent as Signal datas) and when I am trying to send him something, this error is raised : 
`Number is not registered. (original: promiseAjax: error response; code: 404)`

**Comment by greyson-signal** [comment] 2019-04-19 12:39
This looks to be a dupe of #8585. If possible, please get a debug log from your friend and post it there. Thanks!

**Closed by greyson-signal** 2019-04-19 12:39 UTC

**Comment by LilianCruanes** [comment] 2019-04-19 13:32
My debug log : https://debuglogs.org/6053f5734474843fa8a54e84ee66992c9f134fc4e5eb30999785c97f3e550204
My friend's debut log : https://debuglogs.org/ee46afe0dc212508ffa63c3b86b954745b3fec398359b1918157b44e7b4bb70f

Thanks.
