### ISSUE TITLE
[4.24.8] Input on keyboard does not show up

### ISSUE THREAD

**Issue by bisam** [signalapp/Signal-Android#8092] opened 2018-08-09 18:57 UTC
Let's begin with a checklist:

- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Since the latest update it can happen that I cannot input any text via keyboard after I click on a new message. This does only happen in the app, and not in the notification reply window. Also note that the issue was not present in the previous versions and i did not upgrade my OS.

### Steps to reproduce
- get new message
- click on it

**Actual result:** signal opens with open keyboard that is not responding
**Expected result:** working keyboard

### Device info

**Device:** Oneplus One
**Android version:** 8.1 (LineageOS microG Version)
**Signal version:** 4.24.8

### Link to debug log
https://debuglogs.org/2fff838a41025c67597711891cee26487934c1eb4cb86ed8a5a5001f1d0e94c5

**Comment by scottyjoe9** [comment] 2018-08-10 00:57
I have also seen this issue. I believe I saw it before the latest update though, so I'm not sure if the latest update is related.

Device info
Device: Google Pixel
Android version: 8.1
Signal version: 4.24.8

**Comment by JohnnyMT** [comment] 2018-08-11 06:08
I can confirm this behavior. It happened also in the previous version. The keyboard behave like it is typing (with word suggestions) but nothing shows up in the chat window. Workaround is to leave the chat and go back in again.
Hope this helps in finding the issue.

**Comment by greyson-signal** [comment] 2018-08-11 14:36
Yeah this is weird, and I know what you're talking about. I think it may be an Android issue with EditTexts, because this is something I've seen happen in several different apps over the past year or two. Because of that intuition, I'm going to close this issue. But if anyone comes up with any steps with a high repro-rate, let me know!

**Closed by greyson-signal** 2018-08-11 14:36 UTC
