### ISSUE TITLE
Messages not Received Until Android App is open in Foreground

### ISSUE THREAD

**Issue by hal88** [signalapp/Signal-Android#10276] opened 2020-12-11 00:02 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Messages are not received until the app is open in the foreground. Given this, I obviously no longer get signal notifications when messages arrive as they only arrive when I check for them.

### Steps to reproduce
- Open the app
- watch all the messages sent since the last time signal was open arrive and update the screen
- Lament the messages where a notification would have been very useful to prevent me from appearing a bit rude.
- I use the signal desktop client and love it. This issue persists when the signal desktop client is closed. 
- Same for wifi or mobile data

**Actual result:** No notifications. Messages not recieved until signal is open in the foreground.
**Expected result:** Receipt of message and notification when Signal is not in the foreground.

I have tried to remove every single possible OS restriction on Signal, battery optimsation, background data, as well as on google play services. Starting by following all possible interpretations of the steps here https://support.signal.org/hc/en-us/articles/360007318711-Troubleshooting-Notifications. Searched this issue database and various other things on the web. Nothing I tried worked out. Willing to do whatever to help.

I tried updating to the beta. I've run out of ideas. I love signal and have used and recommended it to everyone and anyone for years. This issue is the first one that's making signal use a little difficult.

### Device info
Time          : 1607643798898
Manufacturer  : Ulefone
Model         : Armor 9
Product       : Armor_9_EEA
Screen        : 1080x2113, xxxhdpi (480), 60.00 hz
Font Scale    : 1.0
Android       : 10 (root.20200605.114948, Armor 9_TF1_EEA_V01)
ABIs          : arm64-v8a, armeabi-v7a, armeabi
Memory        : 35M (60.64% free, 512M max)
Memclass      : 256
OS Host       : root
Censored      : false
Play Services : true
FCM           : true
Locale        : en_AU
Linked Devices: true
First Version : 740
App           : Signal 5.0.1 (752, 7522)
Package       : org.thoughtcrime.securesms (doDiFGKPO1r)

### Link to debug log
https://debuglogs.org/0bd3ed5684e2ae795c9f4f67059451c4bf54caf5b1b487a774d8b657a9a3064c

**Comment by keraba** [comment] 2020-12-12 00:13
Duplicate of 10065, fwiw. I'm seeing it too, and experimenting with turning off battery optimization for the app.

**Comment by hal88** [comment] 2020-12-15 09:31
![Screenshot_20201214-202653](https://user-images.githubusercontent.com/16928430/102196699-5b625980-3f14-11eb-818d-f1606b725dba.png)

Battery optimisation settings don't seem to be a viable fix for what I'm seeing.

**Comment by MorNando** [comment] 2020-12-20 14:29
I can confirm this is happening on my brothers android phone. It’s unusable for him as we have a group chat and notifications come through for around 10 minutes when he opens signal app up.

**Comment by hal88** [comment] 2020-12-23 20:35
Don't kill my app results from an overnight test. 100% is healthy.

![Screenshot_20201224-070134](https://user-images.githubusercontent.com/16928430/103035040-74c17080-45ba-11eb-8ab0-f9477dc29090.png)

**Comment by hal88** [comment] 2020-12-26 12:01
Manufacturer says:

"Dear friend, you can turn on the Dura speed.then you can put the apps you need to running in the background to the white list."

**Comment by gabrivera** [comment] 2020-12-27 05:28
In case y'all have not read [this official Signal support article](https://support.signal.org/hc/en-us/articles/360007318711-Troubleshooting-Notifications), it may help! I can't test it since I sadly don't have an Android device, but my friends do! And I'll have them try it out, since we have basically gone back to WhatsApp 😕 because some of them weren't getting notifications.

Strangely, a friend of mine just got a notification from me. It's strange because he hadn't received a single notification/message from me ever since he installed Signal a couple of months ago. He used to have to open the app to see my messages. And now that he finally got a couple of those messages, neither of us know what happened! Anyway, I hope the article helps, and I'm glad I had a reason to post, since this is a massive issue for me. We (my friends and I) basically had to stop using this software because of this bug.

**Comment by greyson-signal** [comment] 2020-12-29 15:34
Consolidating this into #8692

**Closed by greyson-signal** 2020-12-29 15:34 UTC

**Comment by hal88** [comment] 2021-01-06 11:14
Ulefone:
"""ok, we know the problems, the app of "signal"cannot received the notifications. Since Armor 9 is an Android 10 mobile phone, Signal is not compatible with the relevant version, so this will cause some software problems. this is the not the phone problems."""

**Comment by MrTuffaha** [comment] 2021-01-17 13:08
@hal88 hope hope this help i do have an ulefone armor 9 and i think i finally made signal notification work

go to:
1- settings
2- smart settings
3- app blocker
4- find signal (in my case it was partially blocked)
5- disable all blocking
for me i ended up dissabling app blocker all together, i will look to its functionality later

**Comment by hal88** [comment] 2021-01-17 22:37
@MrTuffaha Thank you kindly, this appears to be working well.

settings->smart assistant->app blocker and uncheck "boot blocker" "start blocker" "background blocker" "background cleanup"

Doing the same for "dontkillmyapp" got the score up to 100%. 

How do we request to get this info on to the device specific portion of the signal check list for notifications? https://support.signal.org/hc/en-us/articles/360007318711-Troubleshooting-Notifications


So many places where android cripples things. "App blocker" was entirely new to me and I thought I'd been through all the settings

**Comment by hal88** [comment] 2021-01-18 05:39
Created #10714 as an open issue. I hope that's the right thing to do.
