### ISSUE TITLE
Sent images with black box

### ISSUE THREAD

**Issue by orschiro** [signalapp/Signal-Android#11141] opened 2021-03-27 13:33 UTC
Whenever I send an image, it shows only half with this black box.

Screenshot from my Samsung Galaxy 2017:

![image](https://user-images.githubusercontent.com/170947/112722367-5d6f8780-8f09-11eb-9106-0dd9fc22d10a.png)

**Comment by Nisc3d** [comment] 2021-03-27 15:27
Duplicate of #9082.

**Closed** 2022-02-02 17:36 UTC
Labels: wontfix
