### ISSUE TITLE
In 1hr video call it consumed 1gb data

### ISSUE THREAD

**Issue by d5stroy5r** [signalapp/Signal-Android#10651] opened 2021-01-15 09:35 UTC
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Consuming too much data during video call.
In 1hr video call it consumed 1gb data.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI Samsung Galaxy A51 (SM-A515F/DSN)
**Android version:** 10.0
**Signal version:** 5.1.7

**Comment by Frivolous2** [comment] 2021-01-15 10:10
I understand your frustration, but this is not a bug/problem, and this GitHub is only for bug/problem reporting. 

However, you can upvote [this feature request](https://community.signalusers.org/t/reduce-video-call-data-usage/4716) using your existing GitHub account by using the _Log In_ button at the top right, and then _with Github_. 

I hope this helps. 😇

**Comment by jobic10** [comment] 2021-01-15 10:31
This is not an issue.

**Comment by tanujkucp** [comment] 2021-01-15 16:04
It is fixed with version 5.2
Now there is a setting to choose low call quality in settings.

**Comment by greyson-signal** [comment] 2021-01-15 17:20
Hi there, yes, in 5.2 (currently in beta) we've added a setting to enable "low data usage mode" for calls.  Currently we optimize Signal for the best possible call quality, which can use a lot of data. Hopefully the new setting will help, and we'll continue to optimize data usage for different network conditions in the future. Thanks!

**Closed by greyson-signal** 2021-01-15 17:20 UTC
