### ISSUE TITLE
Cannot Download MMS Through Signal

### ISSUE THREAD

**Issue by PilotJoker** [signalapp/Signal-Android#5706] opened 2016-09-20 19:58 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

I've been having trouble getting MMS messages to download using Signal on my LG V10 on the AT&T network. I started looking for an alternative to the clunky stock app, and for a while the Google Messenger app was working perfectly. Recently, that stopped working as well, so I tried Signal as an alternative with no success in downloading MMS messages from non Signal users. I've tried using different APNs for AT&T, but I'm unsure if I'm even using the correct ones.
### Steps to reproduce
- Requested MMS messages from an iPhone and another Android on AT&T
- Signal displays MMS Download Failed!
- Tried on both cellular data and WiFi
- Switched to stock LG messaging app as default to try retrieving MMS, and the stock app doesn't even see that the message exists.

**Actual result:** Signal unable to download MMS messages from non Signal users, stock app can no longer download the message I attempted to download in Signal when switching default apps.
**Expected result:** To be able to use Signal as my SMS app and have MMS messages be able to download to my device.
### Device info

**Device:** LG V10
**Android version:** 6.0
**Signal version:** 3.19.1
### Link to debug log

https://gist.github.com/anonymous/389214cab2d1687b7d49214a07b03c31
- I did my best to get this right away, please let me know if I need another one.

**Comment by FeuRenard** [comment] 2016-09-21 08:40
I cannot see anything MMS download related in the log. Can you capture another one directly after the download failed?

**Comment by PilotJoker** [comment] 2016-09-21 16:51
I just asked my wife to send me another MMS with her iPhone, here's is the debug log I captured immediately after it failed to download:

 https://gist.github.com/anonymous/0c751a5ec8fba0a8cc5b03d96e64e281

Many thanks.

**Comment by sabret00the** [comment] 2016-09-23 19:51
MMS is broken for me too suddenly. Was working Wednesday and broken Thursday.

**Comment by PilotJoker** [comment] 2016-10-12 04:05
Just got the new Android update, still no joy on the MMS.

**Comment by effigies** [comment] 2016-10-13 02:22
Duplicate of #4878?

**Comment by PilotJoker** [comment] 2016-10-13 03:29
Not necessarily. I saw the fix in that thread by changing Advanced MMS settings in Signal, but I don't have that option in my settings.

**Comment by FeuRenard** [comment] 2016-10-13 10:03
Relevant part of the log seems to be this:

```
09-21 10:49:20.665 22194 22194 W MmsListener: Got MMS broadcast...android.provider.Telephony.WAP_PUSH_DELIVER
09-21 10:49:20.671 22194 22194 W MmsListener: Relevant!
09-21 10:49:20.729 22194 22212 W PduParser: parse() called...
09-21 10:49:20.733 22194 22212 W PduParser: Message Type: 130
09-21 10:49:20.735 22194 22194 W MmsListener: Got MMS broadcast...android.provider.Telephony.WAP_PUSH_RECEIVED
09-21 10:49:20.750 22194 22212 V TelephonyAutoProfiling: [loadFeatureFromXml] *** start feature loading from xml
09-21 10:49:20.751 22194 22212 D TelephonyAutoProfiling: [parse] Load xml
09-21 10:49:20.753 22194 22212 V TelephonyAutoProfiling: [getMatchedProfile] selected file : /etc/featureset.xml
09-21 10:49:20.754 22194 22212 V TelephonyAutoProfiling: [loadFeatureFromXml] load feature from xml complete : {support_volte_if=true, support_srvcc=true, srvcc_call_context_transfer=true, support_blocking_sms_in_frp=true, spam=true, MANUAL_SELECTION_WITH_RAT=true, seperate_processing_sms_uicc=true, SUPPORT_LOG_RF_INFO=true, cmas_mlock_cb=true, KREncodingScheme=false, KRWapPushWithSpam=true, GLOBALspam=true, KSC5601Decoding=true, support_emoji_in_concat_message=true, do_not_save_sms_to_isis_short_code=true, SUPPORT_INFO_FOR_IMS=true, lge_call_att=true, att_vvm=true, SHOW_NETWORK_NAME_WHEN_MANUAL_NETWORK_SETTING_FAIL=true, increase_user_permit_sent_sms_max_count=true, block_private_log_level=0x111, OperatorMessage=true, set_clir_option_by_call_setting=true}
09-21 10:49:20.769 22194 22212 W         : Unable to open '/system/framework/qcom.fmradio.jar': No such file or directory
09-21 10:49:20.771 22194 22212 W art     : Failed to open zip archive '/system/framework/qcom.fmradio.jar': I/O Error
09-21 10:49:20.771 22194 22212 W         : Unable to open '/system/framework/oem-services.jar': No such file or directory
09-21 10:49:20.771 22194 22212 W art     : Failed to open zip archive '/system/framework/oem-services.jar': I/O Error
09-21 10:49:20.795 22194 22212 W MmsDatabase: Message received type: 130
09-21 10:49:20.847 22194 22212 W MmsReceiveJob: Inserted received MMS notification...
09-21 10:49:20.876 22194 22214 W MmsDownloadJob: Downloading mms at 166.216.166.67
09-21 10:49:20.876 22194 22214 W CompatMmsConnection: Falling back to try receiving via Lollipop API
09-21 10:49:20.879 22194 22214 W IncomingLollipopMmsConnection: downloading multimedia from http://166.216.166.67:8003/0921164919600003000060000 to content://org.thoughtcrime.provider.securesms.mms/mms/1474476560878
```
That's not the same behavior as in #4878. Over there appears an exception.
Here the download seems to start or to be initiated and then nothing more is logged about it. That seems strange.

**Comment by mfb** [comment] 2016-11-14 04:19
I'm seeing this with android 6.0 and verizon.  Currently I have to use `adb logcat` to get the URL of the MMS message, and then I can download from that URL on my phone, and use various open-source tools to decode the resulting blob of SMIL and JPEG.

**Comment by mfb** [comment] 2016-12-08 00:11
Not sure if this points to a bug in Signal or Android 6.0 or what, but if I switch my default SMS app to "Messaging" (and make no other changes), then I can tap on old MMS messages in Signal that failed to download, and download them!  They seem to fail to download only when Signal is the default messaging app?

**Comment by moxie0** [comment] 2016-12-08 17:10
@mfb And then if you re-enable Signal as the default SMS app, you *can't* download old MMS messages again?

**Comment by mfb** [comment] 2016-12-08 17:54
and MMS is now working in Signal, after a reboot. I wonder if it's this Android 6.0 bug, which indicates rebooting can fix it: http://www.androidpolice.com/2015/12/09/android-6-0-1-fixes-the-annoying-failed-mms-bug-in-marshmallow/

**Comment by databaseindays** [comment] 2017-03-12 17:30
rebooting does not solve the issue. So there is no fix for this?

**Comment by ecwinslow** [comment] 2017-07-14 23:34
"Error downloading MMS
message. Tap to retry."
loops

A group message.

Still no solution? (I rebooted, have excellent WiFi, have checked [Settings]/[Chats and media]/[When using Wi-Fi] and all on)

**Comment by douglasg14b** [comment] 2018-03-11 22:07
This is still a problem....

A complete deal breaker for me. If I can't receive mms messages, what's the point?

**Comment by automated-signal** [comment] 2018-04-03 00:35
GitHub Issue Cleanup:
See #7598 for more information.

**Closed by automated-signal** 2018-04-03 00:35 UTC
Labels: mms
