### ISSUE TITLE
Message timestamp doesn't update with the passage of time

### ISSUE THREAD

**Issue by gabrc52** [signalapp/Signal-Android#11085] opened 2021-03-10 04:24 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The timestamp of the message (like "now", "2m", "5m", "9m", etc) doesn't get updated unless another message is sent, received, or a reaction is sent.

## New steps to reproduce

1. Open a browser 
2. Open a Signal chat and send or receive a message. Wait a minute. The message will say 1m
3. Switch from Signal to the browser. 
4. Wait 5 minutes. 
5. Go back to Signal. 
6. The message will still say 1m and will take a whole minute to update to 6m. 

*Expected result*: when I return to Signal the message will say 6m
*Actual result*: the message will still say 1m and I have to reopen the conversation, send or receive a message, or wait a minute for the timestamp to update. 

### Steps to reproduce (Fixed for this case except for chat bubbles)
- Open a conversation with someone
- Receive a message from them
- Don't leave the app
- Wait 2 minutes

**Actual result:** The message says "now" in the bottom part
**Expected result:** The message says "2m" in the bottom part

### Screenshots

The bug can't be represented using screenshots
A screen recording could work, but I believe this is enough information to reproduce it. If it isn't, let me know.

### Device info

**Device:** Xiaomi Redmi Note 8
**Android version:** 10 (LineageOS)
**Signal version:** Signal 5.3.12 (785, 78502)

### Link to debug log

I don't believe it's necessary, but if it is and can't be reproduced on other devices, please let me know.

**Comment by rforrizwan55** [comment] 2021-03-26 04:15
I was able to reproduce the same on OnePlus 6 running Android 10

**Comment by JordyEGNL** [comment] 2021-03-27 11:00
Same for me on Samsung Galaxy A71 running Android 11

**Comment by gabrc52** [comment] 2021-05-28 23:35
I can still reproduce in the latest beta.

**Comment by gabrc52** [comment] 2021-06-19 04:18
I can confirm this happens on chat bubbles as well, and closing and reopening the bubble doesn't help.

For chats inside the app and not on a bubble, going back to the list of chats and opening the chat again updates the time.

**Comment by cody-signal** [comment] 2021-06-19 15:07
Are you running 5.14.3 or later? They should be updating in that version or later.

**Comment by gabrc52** [comment] 2021-06-20 07:21
On version 5.14.3 this was slightly improved but the issue is still not fixed:

It seems like *when Signal is the active activity/window*, it does update once a minute. However:

1. If only Signal is kept as the active window, the timer may be one minute behind. 

2. When switching to another window for 5 minutes and returning to Signal (assuming it's still in RAM which is the case for devices with sufficient RAM) to a message that says now or 1m, you have to wait a full minute for it to say 5m or 6m. The message timestamp should be updated *on activity join* too. 

3. This doesn't seem to work on chat bubbles at all.

**Comment by gabrc52** [comment] 2021-06-20 07:27
I've updated the steps to reproduce to reflect this. Please let me know if you need any additional information.

**Comment by alex-signal** [comment] 2021-06-21 19:51
Hi, I've adjusted the timer so that it will execute immediately when onResume is hit instead of waiting for a minite. This'll be released in the next 5.15.x beta.

**Comment by infinitewaveparticle** [comment] 2021-07-25 13:30
@alex-signal I've also noticed that brand new received messages never say "Now" anymore... they only say "2m" or "3m" as soon as I receive them. This is the same for every conversation an has been happening for at least a month now... likely longer.

**Comment by greyson-signal** [comment] 2021-07-26 15:09
@infinitewaveparticle I can't reproduce, but we show that relative time stamp based on the sent time of the message from the sender's perspective. It could be the case that your clock, or the clock of the sender, is off by a couple minutes.

Anyway, the original issue is fixed as of a few weeks ago.

**Closed by greyson-signal** 2021-07-26 15:09 UTC

**Comment by infinitewaveparticle** [comment] 2021-07-28 22:08
That makes sense. I thought it was from the perspective of our device time. My one device is always fast by 2-3 minutes so this explains that.

Sent from ProtonMail mobile

-------- Original Message --------
