### ISSUE TITLE
Screen lock inactivity timeout

### ISSUE THREAD

**Issue by giuliovale** [signalapp/Signal-Android#10788] opened 2021-01-24 10:43 UTC
https://github.com/signalapp/Signal-Android/blob/234e4be92413b6d47d54af5d01ebc993bf3a960b/app/src/main/java/org/thoughtcrime/securesms/preferences/AppProtectionPreferenceFragment.java#L252

Time is always one minute even if a second is entered

**Comment by Genis-Sage** [comment] 2021-01-24 11:08
Hey @giuliovale
this is currently intended behaviour, at least as far as I know it

Apart from that, duplicate of  #10208

**Comment by giuliovale** [comment] 2021-01-24 11:10
> Hey @giuliovale
> this is currently intended behaviour, at least as far as I know it
> 
> Apart from that, duplicate of #10208

Thanks for reply but interface accept also some seconds as input so I think there is any case a problem

**Comment by giuliovale** [comment] 2021-01-26 09:05
What I don't understand is why it's so complicated to enable blocking in less than a minute. I think I'm not the only one who finds this feature important

**Closed** 2021-04-21 20:48 UTC
