### ISSUE TITLE
SMS message sent via Android Auto does not appear in Signal

### ISSUE THREAD

**Issue by anoxi** [signalapp/Signal-Android#8238] opened 2018-10-02 19:51 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
An sms message that I have sent via Android Auto does not appear in Signal. The message was sent successfully by Android Auto. My conversation partner has even responded in Signal, but I do not see my text of the sms in the Signal conversation.

### Steps to reproduce
- Send sms message via voice input in Android Auto
- Then open the Signal and check the corresponding message history

**Actual result:** The sent message does not appear in message history
**Expected result:** The sent message appears in message history

### Device info

**Device:** Moto Z
**Android version:** 8.0.0
**Signal version:** 4.26.2
Android Auto 3.6.583534 release

**Comment by FeuRenard** [comment] 2018-10-02 20:13
Duplicate of #7627 
This is a technical limitation of Signal's and Android Auto's SMS feature. The SMS is sent via Android Auto directly and Android Auto doesn't notify Signal that it sent an SMS. See also https://github.com/signalapp/Signal-Android/issues/7627#issuecomment-378568313 for an official answer from the Signal team.

**Closed** 2018-10-02 20:15 UTC
