### ISSUE TITLE
MMS from Grops is sent as direct message from individual contact with error.

### ISSUE THREAD

**Issue by nickorka** [signalapp/Signal-Android#9187] opened 2019-11-13 12:48 UTC
### Bug description
MMS from Grops is sent as direct message from individual contact with error.

### Steps to reproduce
- create a group with one or more NON-Signal contacts
- send MMS from non-Signal account
- Signal account receives error MMS
- try to download the MMS
- Signal fails to download
- on a next day or so you receive the error MMS as direct (non-group) message when the non-Signal contact never even tried to send any direct message.

### Device info
Any

### Carrier 
ATT

**Comment by Cerberus0** [comment] 2019-11-13 14:31
Could you capture a [debug log](https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports#android_debug) immediately after the issue occurs and share it here or with the developers through support@signal.org? What carrier are you on? Thanks!

**Comment by Tursko** [comment] 2019-11-13 18:12
This issue has already been created. Please make sure you check before creating an issue - https://github.com/signalapp/Signal-Android/issues/9173

"I have searched open and closed issues for duplicates"

Please Link your debug log in the issue linked.

**Comment by nickorka** [comment] 2019-11-13 21:45
This issue is quite different. Read carefully. The error MMS from Group chat duplicates as an individual MMS from the contact that posted it to the Group. I would consider this as more dangerous because it britches the message destination.

**Comment by Tursko** [comment] 2019-11-13 22:16
Oh sorry, I just noticed that. Regardless it's most likely related to the one I tagged. It's still a good idea to attach a debug log as it might be hard for them to reproduce this problem. It also doesn't hurt to attach it to the other Issue and just mention your different scenarios.

**Comment by greyson-signal** [comment] 2019-11-22 17:22
Closing as a duplicate of #9173. I understand you're describing a different aspect of the problem, but it's the same underlying issue.

**Closed by greyson-signal** 2019-11-22 17:22 UTC

**Comment by nickorka** [comment] 2019-11-22 18:49
Ok. It looks like a BIG problem for the Signal developers. I'm switching back to native SMS messenger.
