### ISSUE TITLE
Beta - Selfie taken on Huawei P20 lite is rotated and stretched always.

### ISSUE THREAD

**Issue by leifrod** [signalapp/Signal-Android#8696] opened 2019-03-19 10:06 UTC
Hi

- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When taking a selfie from the app it is rotated and badly scaled/stretched.
This bug has been present since about 3 months on both main and beta channels.
Signal used to take good selfie camera pictures before this.

### Steps to reproduce
- Take selfie with Signal , see the result

**Actual result:**  
Rotated and stretched picture - unusable
**Expected result:**
Correct orientation

### Device info

**Device:** Huawei P20 Lite
**Android version:** 8.0
**Signal version:** 4.36.0

**Comment by greyson-signal** [comment] 2019-03-19 18:04
Duplicate of #8292

**Closed by greyson-signal** 2019-03-19 18:04 UTC
