### ISSUE TITLE
Each message gets two notifications

### ISSUE THREAD

**Issue by Condalmo** [signalapp/Signal-Android#8570] opened 2019-01-28 21:47 UTC
- [x] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

**Saw someone else with the same problem, but no solution. "one thing that I've been having a problem with is that when I receive a text I can see the notification then open the app to read it and the notification quickly disappears but then by the time get three words into a message it reloads that notification and plays the notification sound again."**

### Device info
Moto G6 Play
Android 8.0.0
Signal 4.32.8

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

### Link to debug log
https://debuglogs.org/2a14ac4b49f3942285a6af7990bc2a3f1ce63564855c34d3c911103fd3142797

**Comment by Condalmo** [comment] 2019-01-28 21:52
Somebody just mentioned that they'd seen something similar happen when fingerprint lock was in use. Not sure if it's related.

**Comment by Cerberus0** [comment] 2019-01-29 09:53
Do you have the screen lock option enabled in Signal's privacy settings? Is the first notification you see a "locked message" notification? In that case, I think this may be a duplicate of https://github.com/signalapp/Signal-Android/issues/8321.

**Comment by Condalmo** [comment] 2019-01-29 15:49
Yes, I do have that option enabled. Might be a duplicate of that issue. No solution on that one.

**Comment by greyson-signal** [comment] 2019-03-03 09:08
Marking as dupe of #8321

**Closed by greyson-signal** 2019-03-03 09:08 UTC
