### ISSUE TITLE
Not seeing double checkmarks (Delivered) even though contact is receiving messages

### ISSUE THREAD

**Issue by Bout2GitIt** [signalapp/Signal-Android#8423] opened 2018-12-02 21:00 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I have one Signal contact to whom I send messages and see only 1 checkmark, not 2. That contact is receiving and replying to my messages. I have this problem with only 1 contact. All other contacts are showing 2 checkmarks as per usual. 

I do not use read receipts and never have. A screengrab from my contact's phone shows me that they see 2 checkmarks on the messages they send me. But I only see 1 on messages sent to them.

### Steps to reproduce
- This happens anytime I send a message to 1 particular contact. 
- This happens when I send from my phone and when I send from Signal desktop
- This happens when I send over data and over WiFi

**Actual result:** The message is delivered to my contact, but in my app it appears as though it has not been delivered. (It only shows 1 checkmark.)

**Expected result:** I should see 2 checkmarks.

### Screenshots
<img width="345" alt="screen shot 2018-12-02 at 12 57 16 pm" src="https://user-images.githubusercontent.com/45543439/49344891-de682e00-f631-11e8-81ad-42cf0dd7a047.png">

### Device info
**Device:** Sony G8441
**Android version:** 8.0.0
**Signal version:** 4.30.8

My contact is on an iPhone 7. I do not know which version of iOS they are using.

**Comment by ascisco** [comment] 2018-12-02 21:16
Im having the same problem on Signal 4.31.3 with Android 9.

**Comment by MomentofClarity** [comment] 2018-12-02 23:08
Same here, and I've been up for over 36 hrs at this point and I am too exhausted to help diagnose the issue (by trying it from multiple platforms and with various contacts, etc).

But I have some potentially useful observations and a debug log.  I'm staying far, far away from the phone today so this is on desktop clients, first time was this afternoon at 3:26 EST from Ubuntu 18.04 running the latest Signal going to an iPhone.  I noticed only one checkmark after some time (maybe 10 mins) had passed which was odd, so I clicked on the "more info"  thing and it said it was received the minute it was sent.  So I figured the 2nd checkmark didn't come thru..

BUT

It happened to me again just now (from a Windows client, to the same person, still on iPhone) and just for kicks I went and checked the first message... and it had a very different story to tell. 

> Sent | Sunday, December 2, 2018 3:26 PM (1543782418702)
> Received | Sunday, December 2, 2018 4:32 PM (1543786356824)

So even though when I first checked it, it said received at the exact same time (3:26), now looking back it claims it was received much later.  Could it have gotten updated to the time it was "read"? Or did it actually only get delivered then? I don't know, you guys are the developers. 

(It's still doing it now, with every msg I send - not sure if the time (saying it was delivered instantly) can be trusted any more - maybe the 2nd check mark has the authority here?)

Thank you for all your hard work. (Oh and I have the latest Signal on Android if that matters)

Log:
https://debuglogs.org/56e3fb5a433857160bf4013d4b138ebbd72b5e1e049f37490107368c3cfe90f4

**Comment by greyson-signal** [comment] 2018-12-02 23:48
Hey, this was confirmed as an iOS issue and is actively being worked on.
Thank you everyone for the detailed information!

**Comment by charlesmchen-signal** [comment] 2018-12-03 14:05
This issue has been fixed in a new version of Signal iOS which will be released soon.

**Closed** 2018-12-03 18:32 UTC

**Comment by yasharya2901** [comment] 2021-06-29 05:02
I'm having this issue in my Android 9 phone running the latest stable MIUI. Plus, the person on the other side uses a Realme phone Android 10. In my case, it only shows double Tick delivered but not read even though the person has read it and also replying to it. I can also see the same issue being reflected in my Desktop Signal app running on Linux Mint 20.

**Comment by greyson-signal** [comment] 2021-06-29 13:50
@yasharya2901 On Signal you can disable read receipts. I would check and ask the person your chatting with if that's the case.

**Comment by yasharya2901** [comment] 2021-06-29 14:02
Thanks, @greyson-signal! I made him turn on the Read Receipt under Privacy settings and now the issue is sorted. Thanks!
