### ISSUE TITLE
Messages in a particular groups is getting delayed in delivery

### ISSUE THREAD

**Issue by iamrahul10** [signalapp/Signal-Android#8386] opened 2018-11-21 16:24 UTC
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Messages in a particular groups is getting delayed in delivery. The issue is only with this group, as I have many others groups, which do not have this issue. Apart from me, other members of the same group has this similar issue. I guess it's not with the network, as I can sent PM's, video calls and group messages [to other groups]. The group in question only has six members including me. 

### Steps to reproduce
- Send messages and wait

**Actual result:** Message gets delivered. But after quite a long time.
**Expected result:** Immediate delivery.

### Screenshots
![screenshot_20181121-202804](https://user-images.githubusercontent.com/33648855/48854366-a9461b00-eda9-11e8-916f-e1691fae27c0.png)

### Device info

**Device:** Manufacturer Xiaomi Redmi Note 4 [Mido]
**Android version:** 8.1.0
**Signal version:** 4.31.0

### Link to debug log
https://debuglogs.org/b3578341937ca2d1c4e3aeedd81c0500839f6a855cc324d4b1e83ba835ea5722

**Comment by greyson-signal** [comment] 2018-11-21 18:38
Duplicate of #8305

**Closed by greyson-signal** 2018-11-21 18:38 UTC
