### ISSUE TITLE
Feature request: Mentions/tag user in groups

### ISSUE THREAD

**Issue by josh-unwin** [signalapp/Signal-Android#9127] opened 2019-10-24 10:15 UTC
I'll be unsurprised if this is a duplicate, but searching for keywords didn't seem to return a match.

It'd be great if we could tag/mention a user in a group chat with @PersonsName

**Comment by Cerberus0** [comment] 2019-10-24 14:20
Hi @josh-unwin,

This is not the right place for feature requests. As stated in the [bug report template](https://raw.githubusercontent.com/signalapp/Signal-Android/master/.github/ISSUE_TEMPLATE.md) that you appear to have deleted, as well as the project's [CONTRIBUTING.md](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md), this issue tracker is only meant for bug reports. Bug reports should only be submitted for existing functionality that does not work as intended. You are welcome to submit and discuss ideas for non-existing functionality on the community forum. Please close this issue and continue the discussion there:

* https://community.signalusers.org/t/mention-tagging-in-groups/2939

You can easily sign up/login on the forums with your existing GitHub account.

**Closed** 2019-10-24 15:26 UTC
