### ISSUE TITLE
Instant crash upon saving audio attachments

### ISSUE THREAD

**Issue by Xashyar** [signalapp/Signal-Android#10242] opened 2020-12-03 13:42 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I save any sort of audio attachment, voice note or otherwise the app instantly crashes.

### Steps to reproduce
- Try to save an audio attachment

### Device info

**Android version:** 6.0.0
**Signal version:** 4.79.2

### Link to debug log

https://debuglogs.org/7c02a262515eb1c82782fd63e490aa6e35a5d834731089799b2beb9ba06b8f7d

**Comment by greyson-signal** [comment] 2020-12-03 14:29
Closing as a duplicate of #10159

**Closed by greyson-signal** 2020-12-03 14:29 UTC
