### ISSUE TITLE
Messages don't get delivered, and there's no way to know or even retry

### ISSUE THREAD

**Issue by TheQuantumPhysicist** [signalapp/Signal-Android#10693] opened 2021-01-17 12:10 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I'm a developer, and I understand my bug report is probably hard to reproduce because it's in the protocol. But this is an issue I've seen for some time.

So, a friend sends me a message (a voice message especially), and it's simply not delivered. He then contacts me on Threema and tells me "hey, didn't you get my message I sent you on signal", and my response is "no", and then, we go to signal. I find absolutely nothing, and he finds a status that doesn't make sense. I see here, for example, 1 hollow check mark for messages I know that my friend has received. 

This problem happened before the spike in the number of users of signal last week. However, after the spike, it got much, much worse.

The thing is, this should never happen. Message statuses should be 100% consistent and should indicate whether my contacts received the messages or not. There shouldn't be states in between. Also, more importantly, there should a "retry" option, just like Whatsapp. It seems to me the protocol now just sends the message, and the confirmation can be lost somehow.

Thank you for a great app. 

### Steps to reproduce
Some times (especially voice) messages don't arrive, and more importantly, there's no way to know they didn't arrive. I don't know how to reproduce that.

### Screenshots
Not needed

### Device info

**Device:** Galaxy Note 10
**Android version:** 10
**Signal version:** 5.1.9

### Link to debug log
https://debuglogs.org/d068fb572b2ed8216c4bcd13218dc258855f798316d40300f0a29bee548e8acb

**Comment by jtracey** [comment] 2021-01-18 20:35
>Message statuses should be 100% consistent and should indicate whether my contacts received the messages or not. There shouldn't be states in between.

If you're having problems with messages going through, that's one thing, but what you're claiming should be the case here is [provably impossible](https://en.wikipedia.org/wiki/Two_Generals%27_Problem). You can make a best effort at synchronizing state across two devices, which is what read receipts are, but it will never be the case that you can be 100% sure both you and your contact agree on whether all messages were successfully received or not.

**Comment by TheQuantumPhysicist** [comment] 2021-01-18 21:48
Thank you for your response.

Allow me to disagree with you. The generals problem doesn't apply here for many reasons. Probably the reason for this misunderstanding is that you're attempting to do this operation in one roundtrip and let's add that there are no bad actors in Signal who will try to fool you as in the case of the generals, especially that e2e encryption is used, which is a good assumption. Taking this to a practical level, I assure you, that you can be 100% sure that the message is delivered. Simply, create a fingerprint of the message (hash or otherwise), and when unsure whether the message was delivered, send another message asking "did you receive the message with fingerprint XYZ?". You keep asking the peer whether they got that message. If no response is received, then the message is assumed to not have been delivered. After a few attempts, you declare it a failure and offer the user to retry. A retry will attempt to ask again and wait for the peer to say yes or no on having received the message. If yes, mission accomplished. If no, you send the message and wait for the confirmation again. This simple algorithm will 100% succeed. I wrote such protocols years ago. I'm assuming here there are no other challenges to achieving this that I'm not aware of, but certainly, the generals problem doesn't apply here.

Thanks again for the response.

**Comment by jtracey** [comment] 2021-01-18 23:00
What you described is precisely the two generals problem. Suppose the person you're sending a message to can receive data, but can't send it (at this level of the network stack); or equivalently, that you can send data, but not receive it. Then they will have your message, but you can never know they got it, and will repeatedly send requests for confirmation forever. No amount of retries can solve this completely, only increase the probability of success (and honestly, with only marginal utility too, since if you e.g. try sending 1000 times and it doesn't work, the 1001st isn't likely to work either, so you're ultimately just spamming the servers).

Whether you believe it or not is really immaterial at the end of the day, the fact is it's not possible. I'm just suggesting you focus on problems that are solvable, and with reasonable expectations.

**Comment by TheQuantumPhysicist** [comment] 2021-01-19 07:04
Thanks for explaining further. I understand that you think that I said we should keep "spamming" the server forever on failure, but this is not what I said. Again, there are reasonable assumptions one can make to ensure the message is delivered before any new message is sent, or at least give the user the choice to deal with it. I don't understand why you're resisting the idea of a retry button. Your app will never, ever, be smart enough to recognize when the other party is possibly available, which is why all the messaging apps since the 90s had a retry button. All other alternatives that I use now, including Threema, Whatsapp and Telegram have a retry option (and I never faced this problem with them), and that option is basically the solution to the generals problem you're describing, because logically speaking, if you can send any new message at all, it should be the message that asks for a confirmation. Sending a message then hoping it's delivered and then forgetting about it without informing the user is the worst way of doing this. I'm sorry, and please don't take this the wrong way, but these are computer science problems that were solved with reasonable assumptions like decades ago. I've never dealt with another app that fails to deliver messages + doesn't offer a retry + continues sending new messages in the future without being able to determine whether older messages were delivered. This is a recipe for disaster. Please take my words as critique, not as criticism. I can't really believe that a problem I never faced in decades is impossible to solve reasonably. 

And honestly, I'm not sure what else we can focus on. With your assumption you're just gonna tell me that "we had overloaded servers" and close the issue. Is there anything else we can do?

Thanks again for the response.

**Comment by TheQuantumPhysicist** [comment] 2021-01-19 10:30
Hi again :-)

I'd like to add that I just finished discussing this problem with a colleague from my workplace who works on chat systems to ensure that I'm not missing something due to my ignorance in the details of the topic. He confirmed that in any practical chat program, messages should never be lost. Perhaps there's a misunderstanding in our discussion that I'm asking for synchronous delivery of messages. If that's the case, I'd like to emphasize that this is not the case. Of course, if we try to deliver the messages synchronously, then failures of all kinds can happen on the way. However, this should not be the basis on how signal should deliver messages (or any reliable chat application for that matter). As a suggestion, Signal should use some asynchronous form of message delivery, where messages are stored on the server, and are only removed from the server when the receiver confirms they're received (or if a very long time period has passed, which is offered automatically through TTL by distributed NoSQL like Cassandra), which also should include a reattempt at delivery when the connection to the receiver is restored.

I really hope I'm not overstepping here, but the claims that this is an "unsolvable problem" and that signal will remain unreliable for the rest of its lifetime is... too much.

**Comment by meinto** [comment] 2021-01-19 14:38
Apart from that "Two Generals Problem" which applies here, the point is, that some Messages dont get through. It seems like it's the same Problem I described yesterday:

https://github.com/signalapp/Signal-Android/issues/10727

**Comment by meinto** [comment] 2021-01-19 14:54
> As a suggestion, Signal should use some asynchronous form of message delivery, where messages are stored on the server, and are only removed from the server when the receiver confirms they're received (or if a very long time period has passed, which is offered automatically through TTL by distributed NoSQL like Cassandra), which also should include a reattempt at delivery when the connection to the receiver is restored.

Seems like a good suggestion for this case.

**Comment by ryannathans** [comment] 2021-01-24 03:40
I am experiencing an issue where random messages will get one tick and NEVER be received by the recipient. Immediately sending another message works successfully though.

**Comment by TheQuantumPhysicist** [comment] 2021-01-24 07:54
The problem that @ryannathans mentioned is part of this issue, since as I mentioned earlier, a new message should NEVER be sent before confirming that an older message was received (of course unless the server can't deliver it specifically because of size or similar safety constraint).

**Comment by TheQuantumPhysicist** [comment] 2021-02-02 05:18
I have a bad feeling that this issue will be buried here for months if not years and no one will investigate it, and that funny discussion up there is the most we'll get from it. I hope I'm wrong.

**Comment by plmayer** [comment] 2021-06-10 06:29
@TheQuantumPhysicist Thank you for your answers above, I was torn between hilarity and sadness upon reading that discussion. Kudos for staying so calm, and obviously I completely agree with everything you said. 

@Devs It would be good to get an official comment on this as well, this is another thing which hurts Signal adoption in my view (along with the issue that sync to Desktop is unreliable)

**Comment by TheQuantumPhysicist** [comment] 2022-01-26 10:35
Hey... look at me reading into the future correctly!

**Comment by TheQuantumPhysicist** [comment] 2022-03-27 11:30
More...

**Comment by greyson-signal** [comment] 2022-03-28 15:59
Is it still happening to you? Do you have logs taken after it's happened? There's been a lot of changes over the last year.

**Comment by TheQuantumPhysicist** [comment] 2022-04-04 10:23
Apologies for the late reply. Health issues.

I'm actually holding off to using signal until this problem gets solved (being serious, undeliverable messages can cause huge social problems, I'm really afraid of that). I'm glad to hear that many things have changed as you mentioned, but I'd love to understand what the changes are. Because as described in the description of the problem, increasing the number of servers has enough side effect to fix the issue from the outside. But it doesn't really fix the underlying problem that's under scrutiny, that messages can be lost due to the protocol (being synchronous?). I wish whoever worked on this could explain the changes and how these are supposed to fix this issue, and then we close the issue and monitor the status and then we reopen the issue if it happens again.

**Comment by greyson-signal** [comment] 2022-06-06 12:19
Just to generally address some of your concerns:

Signal is not a 'synchronous' service. You can send messages when someone else is offline, the server will enqueue them (for 30 days), and when the receiver is online they will get them. This is how it has always worked.

When you send a message, it will have a single hollow check mark. When the recipient receives the message, they send back a delivery receipt, which will update it to two hollow check marks. Finally, when they have read it, they will send a read receipt, which will update it to two filled check marks (if you both have read receipts enabled).

If you are running into a scenario where the recipient is receiving your messages but you're not getting a delivery receipt, I would need logs from both devices so I can discover where the failure is occurring. I have seen zero reports of this (besides yours) over the last year and a half since this issue has been opened. I feel comfortable closing it based on that. Please open a new issue if it happens to you.

If you're running into an issue where notifications are delayed, see #8692

**Closed by greyson-signal** 2022-06-06 12:19 UTC
Labels: wontfix

**Comment by alwa** [comment] 2023-02-26 21:00
I can confirm that this still happens. But in all cases that I can think of the messages eventually get delivered (with correct timestamps), usually when a new message is sent.

**Comment by Mansarde** [comment] 2023-02-27 13:11
> I can confirm that this still happens. But in all cases that I can think of the messages eventually get delivered (with correct timestamps), usually **when a new message is sent**.

Just out of curiosity: Does that also trigger when you send a message to your yourself (i.e. via the "notes" contact)?

**Comment by alwa** [comment] 2023-02-27 19:29
> > I can confirm that this still happens. But in all cases that I can think of the messages eventually get delivered (with correct timestamps), usually **when a new message is sent**.
> 
> Just out of curiosity: Does that also trigger when you send a message to your yourself (i.e. via the "notes" contact)?

I plead ignorance

**Comment by Mansarde** [comment] 2023-02-28 22:49
> I plead ignorance

Ah well, no bigge. I just thought that might be a workaround to manually pull new messages without having to disturb a contact. 😁
