### ISSUE TITLE
Direct video capture

### ISSUE THREAD

**Issue by mcginty** [signalapp/Signal-Android#3564] opened 2015-07-08 23:14 UTC
Similar to how we do direct photo capture, maybe letting users hold the shutter for video.

Spawned from https://github.com/WhisperSystems/TextSecure/issues/520.

**Comment by cdonc** [comment] 2016-03-08 06:44
Any news or milestones for this feature?

**Comment by moxie0** [comment] 2016-03-08 07:30
@cdonc Please do not bump issues: https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#dont-bump-issues

**Comment by zero77** [comment] 2017-10-20 20:22
Duplicate of #6279

**Comment by nrizzio** [comment] 2017-10-20 20:47
@zero77 This is not a duplicate of #6279. #6279 is about being about to switch to the front facing camera within a video call. This issue is about being able to record a video to send to someone without ever having to leave the app.

**Comment by zero77** [comment] 2017-10-22 12:49
yes, sorry you are right

**Comment by automated-signal** [comment] 2018-04-02 21:42
GitHub Issue Cleanup:
See #7598 for more information.

**Closed by automated-signal** 2018-04-02 21:42 UTC
Labels: feature
