### ISSUE TITLE
NEW FEATURE THAT CAN BE INTRODUCED

### ISSUE THREAD

**Issue by agrawalrajat310** [signalapp/Signal-Android#10505] opened 2021-01-11 18:33 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by C4P4E7** [comment] 2021-01-11 18:59
What?

**Comment by Cerberus0** [comment] 2021-01-11 19:38
Hi @agrawalrajat310,

Please note that this issue tracker is [only meant for bug reports](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md#issues). Bug reports should only be submitted for existing functionality that does not work as intended. This is not the right place for questions, comments, or feature requests, as stated in the project's [CONTRIBUTING.md](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md) and [issue template](https://raw.githubusercontent.com/signalapp/Signal-Android/master/.github/ISSUE_TEMPLATE.md). I suggest moving this discussion over to the [community forum](https://community.signalusers.org/). Thanks!

**Closed** 2021-01-11 20:27 UTC
