### ISSUE TITLE
Media sent by the Desktop app don't get updated unless the specific chat is opened

### ISSUE THREAD

**Issue by quaqo** [signalapp/Signal-Android#13347] opened 2024-01-03 17:20 UTC
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Sending a picture with Signal Desktop doesn't get the chat updated in Signal Android: one has to click on the contact, open the chat and then exit. At that point the chat gets updated and bumped to the top of the list.

### Steps to reproduce
- Send a picture from Signal Desktop
- Open Signal on Android

**Actual result:** The chat list doesn't get updated. It gets updated if instead of a picture a text is sent.
**Expected result:** The chat list should get updated like when a text is sent. Viceversa is not true (if a picture is sent by Signal Android, Desktop chatlist gets updated immediately with the new content).

### Device info

**Device:** Samsung Galaxy A52
**Android version:** 14.0.0
**Signal version:** ~~6.41.3~~ 6.42.3

**EDIT**: I just got updated from 6.41.3 to 6.42.3 and I confirm the issue is still present.

**Comment by LageTs** [comment] 2024-01-03 23:28
This also happens for generic files like .txt

As far as I can see this only happens in "Note to Self" and not within messages to other Accounts.

Device info
Device: Oneplus 5T
Android Version: 14 - without google services
Signal version: 6.42.3
Signal Desktop OS: Linux
Signal Desktop Version: 6.42.1

Device info for the "other Account":
Device: Oneplus One
Android Version: 11 - with google services
Signal version: 6.41.3

**Comment by quaqo** [comment] 2024-01-03 23:37
> This also happens for generic files like .txt

I confirm it happens for any "attachment". It happens also for reactions.

> As far as I can see this only happens in "Note to Self" and not within messages to other Accounts.

For me it happens on both Note to self and other accounts.

**Comment by LageTs** [comment] 2024-01-04 01:16
> 
> > As far as I can see this only happens in "Note to Self" and not within messages to other Accounts.
> 
> For me it happens on both Note to self and other accounts.

Oh yeah my fault. It happens on the sender's mobile also if files are sent to other accounts. But the receiver gets notified as intended.

**Comment by quaqo** [comment] 2024-01-04 10:26
I just got updated from 6.41.3 to 6.42.3 and I confirm the issue is still present (I edited to original post to reflect this).

**Comment by Ugau943** [comment] 2024-02-12 12:25
I have something similar. In my case, the problem appears whether the specific chat is open or not, and only with images and videos, if I disable auto-download images and videos. With images/videos auto-download enabled, no problem.

The problem only appears for one account. I have another account, and if I connect it to my same apps (Desktop and Android), it works.

**Comment by JonFStr** [comment] 2024-02-13 16:35
On my device, I have auto-download disabled and am now unable to download any media manually to my phone as soon as I opened them on Signal Desktop.

When I click on the download button, it instantly "fails" and shows a "retry" button with a upload icon in the top left corner of the media.

Logcat outputs the following (I restricted to level:warn):
```
17:35:02.908  W  [JOB::56aa6233-5292-46ed-9883-47ff4f6cd865][AttachmentCompressionJob] Encountered a failing exception. (Time Since Submission: 25 ms, Lifespan: 86400000 ms, Run Attempt: 1/Unlimited, Queue: GENERIC_TRANSCODE)
                 org.thoughtcrime.securesms.transport.UndeliverableMessageException: No attachment URI!
                 	at org.thoughtcrime.securesms.jobs.AttachmentCompressionJob.compressImage(AttachmentCompressionJob.java:393)
                 	at org.thoughtcrime.securesms.jobs.AttachmentCompressionJob.compress(AttachmentCompressionJob.java:208)
                 	at org.thoughtcrime.securesms.jobs.AttachmentCompressionJob.onRun(AttachmentCompressionJob.java:168)
                 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:31)
                 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
                 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
17:35:02.908  W  [JOB::56aa6233-5292-46ed-9883-47ff4f6cd865][AttachmentCompressionJob][4] Job failed. (Time Since Submission: 26 ms, Lifespan: 86400000 ms, Run Attempt: 1/Unlimited, Queue: GENERIC_TRANSCODE)
17:35:02.921  W  [onDataNeededAroundIndex(4), size: 6] Invalidated! Just after data was loaded.
17:35:02.922  W  [onDataNeededAroundIndex(4), size: 6] Invalidated! At beginning of load task.
17:35:02.922  W  Notified of key MessageBackedKey(id=28342) but it wasn't in the cache!
17:35:02.939  W  [onDataNeededAroundIndex(4), size: 6] Invalidated! Just after data was loaded.
```

**Comment by itkfm** [comment] 2024-02-19 18:41
Mobile app wants the “retry” sending a message that has already been sent from a different device.
<details>

![image](https://github.com/signalapp/Signal-Android/assets/53079668/184aa6b5-e040-4edb-bb69-7da9251309a7)

</details>

but on the Desktop app that sent it…
<details>

is everything already

![image](https://github.com/signalapp/Signal-Android/assets/53079668/8ddaf2fd-98fc-440a-a669-351b68248478)

</details>

**Comment by cody-signal** [comment] 2024-02-19 19:58
This is addressed in the latest version of the app and will be available 100% soon.

**Closed** 2024-04-22 14:27 UTC
Labels: wontfix
