### ISSUE TITLE
Edit typos in sent messages

### ISSUE THREAD

**Issue by TurkeyMan** [signalapp/Signal-Android#10190] opened 2020-11-13 02:21 UTC
### Bug description
I ***really*** want to be able to edit typos in sent messages. Every other messaging client I interact with regularly can do it, but it's annoying that Signal can't, especially considering it's used on a phone, where predictive text guarantees ~1 in 4 words are incorrect.

I expect that the signal protocol is generally resistant to this because of the encryption scheme, but I think a simple protocol to describe an edit message which applies a correction to a prior message could be interpreted by the client to amend the prior message rather than to display a new one.

### Steps to reproduce
1 Open Signal
2 Send a text message to someone containing a really lame typo
3 Experience the feelings of upset, crushing judgement, and desperation that if you could just edit your last message, you wouldn't feel like a nob that can't type properly

**Comment by Cerberus0** [comment] 2020-11-13 09:20
Hi @TurkeyMan,

Please note that this issue tracker is [only meant for bug reports](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md#issues). Bug reports should only be submitted for existing functionality that does not work as intended. This is not the right place for questions, comments, or feature requests, as stated in the project's [CONTRIBUTING.md](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md) and [issue template](https://raw.githubusercontent.com/signalapp/Signal-Android/master/.github/ISSUE_TEMPLATE.md). I suggest moving this discussion over to the [community forum](https://community.signalusers.org/). Thanks!

**Comment by Genis-Sage** [comment] 2020-11-13 17:04
Hey @TurkeyMan 
Why do you not just delete the last message for everyone and send a new message?

**Closed** 2020-11-16 15:24 UTC

**Comment by TurkeyMan** [comment] 2020-11-26 12:46
That would rearrange the order, and it's also a hassle to highlight the message, copy, delete, re-paste (messing up order), then edit the text. It's just a bad experience, and functionally weak. Most other modern messengers allows to correct typos.

**Comment by erikw** [comment] 2021-10-30 06:21
Upvote this feature request here:
https://community.signalusers.org/t/edit-or-delete-messages-after-theyre-sent/975
