### ISSUE TITLE
Import Android Plaintext SMSs

### ISSUE THREAD

**Issue by JeremyRubin** [signalapp/Signal-Android#8937] opened 2019-07-22 06:09 UTC
Commit: https://github.com/signalapp/Signal-Android/commit/3134837d56bf5d20b7475a78d43f6f3ac4757b40

Seems to have removed the ability to sync a plaintext SMS store -- while this makes sense given there is no longer a need to *export* plaintext backups, importing is still super useful because it allows one to import SMSs from other platforms/services or old phones.

**Comment by JeremyRubin** [comment] 2019-07-22 06:10
Accidentally pressed enter early: Suggestion is to revert this commit, and then re-work the language to allow importing.

**Comment by greyson-signal** [comment] 2019-07-23 18:04
Users are still prompted to import their SMS database after installing the app. I can look into what it would take to bring back this flow in a more limited way.

**Comment by JeremyRubin** [comment] 2019-07-24 18:48
When I originally used the SMS import it failed to import all of my SMSs, so now I'm locked out of repeating the process.

This used to not be a huge issue; I would just search the messages in the SMS app or the signal app, but not google's messenger doesn't let you view any messages unless their SMS app is default.

**Comment by WillyKaze** [comment] 2019-08-06 09:01
Same here, nothing happened when trying to import SMSs by clicking on the banner.
No error was shown and I can't repeat the import process

**Comment by klawrow** [comment] 2019-08-15 16:27
Would be a nice feature to import SMS at anytime instead of just at app install.

**Comment by sudotestuser** [comment] 2019-08-17 17:29
Same as JeremyRubin as WillyKaze

**Comment by u32i64** [comment] 2019-08-17 17:39
@sudotestuser If you do not have anything new to add, please use the :+1: reaction to support comments instead. In fact you already did that on the (previous to yours) comment.

**Comment by go2null** [comment] 2021-01-20 12:24
Still here in 2021 - #10618

**Comment by Graeme22** [comment] 2021-07-19 23:51
Still a big need, I'm sure this is keeping a lot of people from using Signal.

**Comment by greyson-signal** [comment] 2021-07-20 14:01
Closing as a duplicate of #10618.

**Closed by greyson-signal** 2021-07-20 14:01 UTC
Labels: sms
