### ISSUE TITLE
Signal App on Phone Stopping, Unusable

### ISSUE THREAD

**Issue by Summerspeaker** [signalapp/Signal-Android#12375] opened 2022-08-05 16:17 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Singal app on phone stops almost as soon as I open it, booting me back to the main screen. A "Signal keeps stopping" error message often appears, with "App info" & "Close app" & "Send feedback" as options. It's version 5.44.3 on a Motorola Moto G Power phone. The crashing prevents me from accessing the debug log. I first noticed the problem this morning. The app on my laptop is still working fine. 

### Steps to reproduce
- open Signal app on phone

**Actual result:** The app crashes, remaining open in background but dumping me back to main screen & not letting me use it.
**Expected result:** I can use the Signal app to read & send messages, make calls, etc.

### Device info
**Device:** Motorola Moto G Power
**Android version:** RPMS31.Q1-54-13-10-2
**Signal version:** 5.44.3

**Comment by mmgoilf** [comment] 2022-08-05 19:30
Same problem on my end. It seems this has been an issue Signal has had all the way back in 2018 even [https://github.com/signalapp/Signal-Android/issues/8180] , but this is the first time I'm experiencing it. 

Interestingly, here it says it only happens when there is internet, and I confirmed and Signal does work without internet: https://github.com/signalapp/Signal-Android/issues/10081

**Comment by wecacuee** [comment] 2022-08-05 20:48
Same issue. 

Device info

Device: Motorola Moto G Power
Android version: RPMS31.Q1-54-13-11
Signal version: 5.45.3

I have tried rebooting, uninstalling and reinstalling. 

It does work in the airplane mode. It closes when airplane mode is disabled.

**Comment by Summerspeaker** [comment] 2022-08-05 21:06
> It does work in the airplane mode. It closes when airplane mode is disabled.

I'm getting the same results. When I turned wifi off & used just phone data, Signal took perhaps slightly more time to close but still closed quickly. With airplane mode on, it doesn't close but closes again as soon as I turn airplane mode off.

**Comment by wecacuee** [comment] 2022-08-05 21:49
Can you upload the debug log using the airplane mode? I think that will be useful.

**Comment by Summerspeaker** [comment] 2022-08-05 21:56
> Can you upload the debug log using the airplane mode? I think that will be useful.

How do I upload when I'm not connected to the internet because of airplane mode? When I hit submit it just says "Failed to submit logs". I can't seem to select the text to copy it. Taking screenshots would be impractical because of the extreme length of the displayed log.

**Comment by greyson-signal** [comment] 2022-08-05 22:19
Thank you for the logs! Just released 5.45.4 to beta (may take a few hours for it to show up on the Play Store) with a hopeful fix. Whether it's fixed or still broken, another log will be helpful to confirm our theories :) Thanks!

(@Summerspeaker as of 5.45.3, you can save the log locally using the three-dot menu on the debuglog screen and then upload the zip here manually)

**Comment by Summerspeaker** [comment] 2022-08-05 22:42
> (@Summerspeaker as of 5.45.3, you can save the log locally using the three-dot menu on the debuglog screen and then upload the zip here manually)

How do I get 5.45.3? I just updated via the Play Store & it's on 5.44.4.

**Comment by Summerspeaker** [comment] 2022-08-05 23:54
I also got the beta & was able to save the debug log in airplane mode:

[signal-log-1659743491391.zip](https://github.com/signalapp/Signal-Android/files/9274005/signal-log-1659743491391.zip)

**Comment by StevenAlexander44** [comment] 2022-08-06 00:23
Replicated on my Moto G Play before and after the August 5th update

The issue has been fixed (for 20 minutes, so far) after uninstalling and reinstalling the newest (google play) update

**Comment by Emporea** [comment] 2022-08-06 15:57
Log from crash
https://paste.crdroid.net/9MX7jV

**Comment by greyson-signal** [comment] 2022-08-06 17:16
Hi there, I'm looking for logs/confirmation of the fix in 5.45.4. It's currently in beta, but Google is still reviewing it. If someone wants to test ASAP, you can get 5.45.4 from Firebase App Distribution:
https://community.signalusers.org/t/get-the-latest-android-releases-even-faster-with-firebase-app-distribution/17538

**Comment by greyson-signal** [comment] 2022-08-06 17:49
This is a dupe of #12370, and I didn't want to redirect this one to risk people dropping off, but now that the fix in the 5.45.4 beta has been confirmed, I'm gonna put out a production hotfix in 5.44.5. Thanks everyone! (You can see the other ticket for an explanation if you're curious).

**Closed by greyson-signal** 2022-08-06 17:49 UTC

**Comment by wecacuee** [comment] 2022-08-06 19:15
I installed 4.54.4 beta from firebase. I confirm that the issue is fixed for me.

**Comment by Emporea** [comment] 2022-08-08 06:19
Man, How long does it Google take to publish this update.. I cant use Signal.

**Comment by ViewMind** [comment] 2022-08-08 14:16
HI I also have the same problem. The application keeps on crashing. I just installed 5.44.5 and it's the same thing. Won't crash on flight mode. I don't really know how to send the log files. Is there any fix for this?

**Comment by ViewMind** [comment] 2022-08-08 14:51
I've managed to generate the logs for my phone as well. I'll copy them here.
I also have a motorola G phone. https://debuglogs.org/android/5.44.5/da4b6280a2591fea253bc4c2d0f3f50d538835603853973c9230ecf0d58559a2

**Comment by Emporea** [comment] 2022-08-08 14:58
Just to be clear. I dont have a Motorola Phone.
Xiaomi Poco F3
Crdroid 8.7 (build 05.08.2022)
Gapps installed
Signal 5.44.5

**Comment by Summerspeaker** [comment] 2022-08-08 17:21
Signal is still crashing for me with 5.45.3 installed, though I am getting notifications for messages without the app being open now. I'd prefer not to have to reinstall & lose all my messages on phone.
[signal-log-1659978967618.zip](https://github.com/signalapp/Signal-Android/files/9283782/signal-log-1659978967618.zip)

**Comment by aarelovich** [comment] 2022-08-09 10:10
I just downloaded version 5.44.5 and very unfortunately nothing changed. The option to generate the Debug Logs is now gone, so I'm not sure how to proceed.

I also have a Motorola Phone. I tried uninstalling the application and re-installing it, however as soon as I went out of the app and then inside it started doing the same thing again.

Furthermore I've noticed that my initials AA are changed to +2 whenever I go into the app and I can no longer change them back. 

How should I proceed?

**Comment by Emporea** [comment] 2022-08-11 11:02
Installed 5.45.6 from Play Store and the problem seems to be solved for me! Thanks.

**Comment by vbatts** [comment] 2022-08-13 20:30
@greyson-signal this issue is not resolved for me. On neither the current stable of 5.45.6 nor the beta 5.46.3.

I just found this issue and the airplane mode trick so that I could use the app long enough to save the debug log:
[signal-log-1660422302024.zip](https://github.com/signalapp/Signal-Android/files/9332123/signal-log-1660422302024.zip)

**Comment by vbatts** [comment] 2022-08-13 20:55
I've gone ahead an opened a new issue, as it does not seem exactly related nor is fixed by the versions stated. 
https://github.com/signalapp/Signal-Android/issues/12392
