### ISSUE TITLE
Signal crashes when importing backup (version 4.49.18)

### ISSUE THREAD

**Issue by TommyMudd** [signalapp/Signal-Android#9197] opened 2019-11-16 18:42 UTC
Hello,

Moving from a Samsung Galaxy S6 to Galaxy S9. At first, I created a backup, moved the file to my desktop, loaded it into the signal backups folder. It loaded thousands of messages but crashed towards the end. I noticed the versions were different, 4.49.15 on S6, 4.49.18 on S9, so I updated on S6 to the same version, recreated the backup, tried again twice, crashed both times before completing the backup. 

I pulled the log from the S9: https://debuglogs.org/401c3de3ac7ab18bd3597dd1f52f6f92de9bc1a1f6dec10940add51ab985d88d 

Please let me know if this log shows the information needed or how I need to go about getting that information if this does not suffice and I will resubmit.

Thanks for your help

**Comment by bepaald** [comment] 2019-11-17 14:51
Looks like #9154 again.

**Comment by greyson-signal** [comment] 2019-11-18 14:11
Closing as duplicate of #9154

**Closed by greyson-signal** 2019-11-18 14:11 UTC
