### ISSUE TITLE
Android 7.1 Contact Names Vanished

### ISSUE THREAD

**Issue by gene-git** [signalapp/Signal-Android#5808] opened 2016-10-26 01:57 UTC
### Bug description

After switching to Android 7.1 (Google Pixel XL) names for my contacts vanished.
Android Message is my default SMS client. Any contact which is visible to signal has no name - only a phone number where the name is displayed. This happens in both signal and the android message client. 

This was fine on all versions up to Android 7.0. The problem began with Android 7.1.

I have tried below which made zero difference
.http://support.whispersystems.org/hc/en-us/articles/216595418-How-can-I-see-the-names-of-my-contacts-in-my-contact-list-I-am-only-seeing-numbers-

**Comment by gene-git** [comment] 2016-10-26 02:09
The contact photos do show up - just no name. Even after uninstalling signal - my message app has no names for the contacts which signal 'lknew' about. 
The contacts are all fine - but somrehow signal has 'messed up' the contacts.

Can you please provide instructions how to remove the mess and fix it so contact names display again?

thank you.

At least until the app has been updated to work with current version of Android.

**Comment by moxie0** [comment] 2016-10-26 06:42
If this problem persists in apps that aren't Signal even after Signal has been uninstalled, what leads you to believe this is a Signal issue? There should be no way that an app can affect anything on Android after it has been uninstalled. If it happened after updating your Android ROM, it sounds like an Android issue.

**Comment by gene-git** [comment] 2016-10-27 02:28
I did not update my rom - i bought a new phone. It was fine. Then I installed and ran signal - after that the contacts were essed up as described above.

The old phone was running Android 7.0 - the new phone is running Android 7.1

Hope that is more clear.

**Comment by gene-git** [comment] 2016-10-27 15:35
Well as I said. It only affects contacts that signal sees and it happened after starting signal.

I dont know enough about the API or what changed in 7.1. seems to me signal has stored something via the contact API.

The test would be to factory reset the phone and start again without signal. I just would prefer to avoid this.

Googling also shows a long history of name missing related issues all the back to when signal was called textsecure.

I'm not technical so I am not equipped to do justice to your question. May I suggest you ask your program development team? If you are a developer then I suppose you should know?

There is certainly evidence indicating signal issues.

That's my best answer.

My question to you which you did not answer is whether your dev team has tested signal on 7.1 Android. Have they? 

Let me how those tests work out.

Gene




Sent from my android device.

-----Original Message-----

**Comment by gene-git** [comment] 2016-10-28 11:49
Additional info - signal appears to create a linked contact which has only the number but no name. I suspect in pre 7.1 android - that linked contact was ordered second when apps call the API - and now it comes up first - when that happens there is no name as the 'real' contact is not being found.

I can definitely see new contacts created as belonging to signal and they are linked to the real contact - so it seems to me what signal is doing in creating these 'linked' contacts needs to be updated somehow for it to work properly.

**Comment by moxie0** [comment] 2016-10-28 16:56
Signal creates an "account" and raw contact rows for each contact on the device registered with Signal.  However, on Android multiple raw contact records get aggregated into a single contact record. Also, when you uninstall Signal, the Signal "account" and all its associated raw contact rows get deleted.

**Comment by gene-git** [comment] 2016-10-28 17:09
Good - then a possible way to fix the bug would be to ensure that Signal adds the name to that raw contact not just a number - try it see if it fixes the bug,.

**Comment by gene-git** [comment] 2016-10-28 17:11
if you don't have android 7.1 (i,e a google pixel phone) - send me privately and I can test for you.

thanks.

**Comment by moxie0** [comment] 2016-10-28 17:54
Signal intentionally does not add names to the raw contacts, since they would then get out of sync. The phone number is enough for the raw contact to get aggregated into the contact record, so the name for that contact comes from the raw contact record from a different "account" (presumably your gmail account or whatever).

As I said, the raw Signal contacts are deleted when Signal is uninstalled, so if they persist something is very wrong with your OS.

**Comment by gene-git** [comment] 2016-10-28 18:26
The deletion issue may have cleared when cache updated - which I may not have given enough time - so let's not focus on that.

Then it seems very clear to me that signal has a bug under 7.1 - (rather than somethign is very wrong with my brand new phone and brand new OS) -  far more likely instead of blaming Google - it seems signal is not compatible with Android 7.1. Please stop pointing the finger and be objective - 

You haven't even tested under 7.1 yet you are insisting Google is at fault .. seriously????

Be obective - and consider that signal doesn't work correctly with Android 7,.1 - call it compatibility call it a bug ... whatever ... 
I'm done.

**Comment by blunden** [comment] 2016-11-10 13:57
Names show up just fine for me on 7.1 (CM 14.1) on my Nexus 6P. For one contact I had to link the contact created by Signal with the normal contact but after that is was back to normal.

Signal no longer shows up in recents though which is surprising. I have not looked at the changes yet though so it might be an intended change in behaviour.

**Comment by paulnivin** [comment] 2016-11-20 16:40
I experienced this issue when moving from a Nexus 6P to a Pixel XL and transferring over phone data using Google's recommended sync process documented at https://support.google.com/pixelphone/answer/7129955?hl=en.

After the transfer, Signal contacts end up being linked to a new no-name/phone number only Google contact (This contact contains the avatar and phone number listed as other -- no other data). The original Google account contact (with full data) is still there, but most Android apps (including Signal) seem to prefer the contact that just has the phone number and those apps never display names. The Contacts app will show the contacts with full data but do not consider the new phantom contacts as duplicates. So we end up with 3 contacts -- original Google contact with full data that is unlinked, and a Signal contact that's linked to a no-name/phone-number-only Google contact.

Fix/workaround:
- Select avatar icon in Signal for the user displaying a phone number only, to open the contact screen
- Select delete from the hamburger/top right menu
- Confirm "The contact to be deleted has details from multiple accounts. Details from read-only accounts will be hidden, not deleted", and select OK.

Signal will now display the name from the only remaining Google contact with a phone number. In the Contacts app, it's then possible to relink the Signal contact to the remaining Google account, but this step isn't required.

**Comment by rhd** [comment] 2016-11-30 06:58
Exact same thing has happened to me. Only numbers show up, not names. Workaround above seems to fix it. Thanks!

**Comment by cryptomilk** [comment] 2016-12-19 18:09
The issue seems to be that all Signal numbers get added to the Contacts store not are not mapped into account with matching phone numbers. At least if the phone number doesn't exist.

You can go to the "Contacts" App and in the menu choose to only display Signal contacts. Then you can hide them by "deleting" them.

The question which raises is can you turn off the Sync for Signal in the Accounts Setting?

**Comment by cryptomilk** [comment] 2016-12-19 18:17
**Workaround**

- Open the "Contacts" App
- Open the menu and select "Contacts to display"
- Select Signal
- Long press on the first phone number (opens multiple selection option)
- Select all your Signal contacts
- In the menu select "Delete"

The Signal contacts are read-only contacts. This will hide all Signal contacts and Signal will map all accounts to your contacts (Google, DAV, etc.)

**Comment by RiseT** [comment] 2016-12-19 20:14
Mh. I'm running 7.1.1 on a Nexus 5X and I don't experience this issue. I've done a factory reset after updating to 7.1.1, though, and did not auto-import Android's settings from the cloud (reconfigured manually). Don't know if this matters.

**Comment by moxie0** [comment] 2016-12-23 02:38
I think the problem is the "import" process for when people transfer contacts over from their old device.  It seems that the new 7.1 device creates new contacts for all the entries that were under the Signal "account," but doesn't move the account.  Those contacts don't get aggregated for some reason.

I think we're going to have to start storing contact names w/ the contact records Signal creates. We didn't want to do that to avoid problems like this, but in the end it seems like we might be having more problems like this as a result of not doing it.

**Comment by MaxXor** [comment] 2017-01-04 09:21
I'm experiencing the same problem, all contact names vanished on Android 7.1.1.

**Comment by automated-signal** [comment] 2018-04-03 00:46
GitHub Issue Cleanup:
See #7598 for more information.

**Closed by automated-signal** 2018-04-03 00:46 UTC
