### ISSUE TITLE
Can't send regular SMS

### ISSUE THREAD

**Issue by MaximeL** [signalapp/Signal-Android#7481] opened 2018-03-09 07:22 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When I try to send regular SMS to someone not using signal it instantly fail. For signal user it works pefectly fine. 
When the text is send to non-user it instantly fail with error message. When I touch for detail, I can try to resend. If I do, it hang but nothing happens until I go back and the message is still in error.
It happen for every contact not using signal.

### Steps to reproduce
- Send text to a non-user of signal

**Actual result:** The text is not send with an error message
**Expected result:** The text should be send without error

### Screenshots

![screenshot_20180309-080234](https://user-images.githubusercontent.com/14075126/37195194-16a88f78-2372-11e8-91c1-3e4cf45cb7d0.png)

### Device info

**Device:** WIko FEVER
**Android version:** 6.0.0
**Signal version:** 4.16.9

### Link to debug log

https://hastebin.com/basazekihi

**Comment by RichJeanes** [comment] 2018-03-09 14:40
Can you confirm that the recipient is not actually getting the messages? I have run into this before, but sometimes they are still getting the messages and sometimes they aren't. Does this only happen with a specific contact or is it all of your contacts? When i experience this, it is typically only with a specific person or two.

**Comment by jeremymasters** [comment] 2018-03-09 16:27
I had this too if it's what @RichJeanes describes, but when I would send an MMS, it showed no error and worked fine.  I wrote up a bug about it, but it was closed in favor of another which was also closed in favor of another.  It's around somewhere though.  I my case, the first check mark would show and then it would show not delivered but my recipient would reply to the message anyway.

**Comment by moxie0** [comment] 2018-03-09 18:56
I don't see any attempt to send an SMS message in that debug log. In any case, it's generally not something we have a ton of control over - we hand the SMS to the OS, and it tells us whether it succeeded or failed.

**Comment by MaximeL** [comment] 2018-03-10 08:46
I can confirm that the message is not received. I tried MMS and it doesn't work neither. 
For the debug log, I got the link right after trying to send a message. Tell me if I can give you more relevant information.

**Comment by wdkrnls** [comment] 2018-04-01 17:16
I had this same issue for that same link (but the English version). Other sms messages went through to the non-signal user just fine. Could the problem be specific to the code that sends that message?

**Comment by MaximeL** [comment] 2018-04-03 07:10
If that can help, I already used applications that replace the native one without this kind of problem.

**Comment by moxie0** [comment] 2018-04-03 09:37
I'm unable to reproduce this issue and there is no debug log that covers the failure to send messages. In general there's not much we can do here, we pass the SMS to the OS and it handles the rest. Please reopen if you can either:

1) Provide steps to reproduce on any device and carrier from a clean install.
2) Provide a debug log captured immediately after an attempt to send an SMS that fails.

**Closed by moxie0** 2018-04-03 09:37 UTC
Labels: mms, sms

**Comment by MaximeL** [comment] 2018-04-05 09:28
Please tell me what kind of pattern you look for in log so I can give you one that is relevant to you. I can provide you with tons of logs catched right after a fail, but if you tell me the previous log I provided was not relevant, I don't want to give you more of this kind.

**Comment by 5frank** [comment] 2018-12-11 08:52
This problem occurred yesterday - repeated attempts to send SMS failed (MMS and signal messages works). Problem disappeared after reboot. I was able to capture log for both success and fail, and as far as I can tell difference is the following:
Fail:
`SmsSentJob: Got SMS callback: org.thoughtcrime.securesms.SendReceiveService.SENT_SMS_ACTION , 1`

Success:
`SmsSentJob: Got SMS callback: org.thoughtcrime.securesms.SendReceiveService.SENT_SMS_ACTION , -1`

i.e `-1` vs `1` which seems to be the return value from `getResultCode()` in 
class SmsDeliveryListener (extends BroadcastReceiver) and where `RESULT_OK = -1` (why it is not zero is beyond me). Not sure on return value `1`. Cold be `STATUS_ON_ICC_READ = 1`, but I'm new to the code base and have not used Java in a decade, so don't take my word for it.

**Comment by Jumanjii** [comment] 2019-01-03 08:56
I have the same issue since I updated my Pocophone to MIUI 10 (android 9)

**Comment by douglasg14b** [comment] 2020-12-01 08:45
This has been an issue since I started using signal in 2016. Signal has NEVER reliably sent SMS messages. Wait till you try to send or even receive MMS messages, probably talking <5% success rate there.

It's also the biggest barrier to getting friends and family to use it, if they can't reliably send SMS to their SMS friends, they don't want to use signal.

I'm just amazed that's it's been almost 5 years, and this is still an ongoing problem.

**Comment by jordyprovost** [comment] 2021-01-01 15:52
Same bug here for months.

I have:
- checked my APN settings (even if standard messages application can send SMS correctly)
- switch the default SMS App to the base app, and re-switch tio signal
- checked the application rights.

Everytime i want to send a SMS to a non signal user, i have an error.

Fun fact, my GF have the same smartphone, same Android version, same provider... and it works for her...
