### ISSUE TITLE
Camera: landscape pictures with Portrait lock have wrong orientation

### ISSUE THREAD

**Issue by lambdaupb** [signalapp/Signal-Android#8611] opened 2019-02-13 18:24 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

See also: #3693 (closed in clean-up)

### Bug description
Built-In Camera will produce pictures with wrong orientation if holding the device in landscape and taking a picture. This only happens when the device has orientation locked to Portrait.

### Steps to reproduce
- lock device orientation to Portrait
- take picture with built-in camera in landscape

**Actual result:** vertical picture is sent with wrong orientation
**Expected result:** picture should have landscape orientation

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 8.0.0
**Signal version:** 4.33.5

**Comment by greyson-signal** [comment] 2019-02-13 18:44
Closing as dupe of #8350

**Comment by greyson-signal** [comment] 2019-02-13 18:45
Sorry, wrong issue, I feel like there's a dupe somewhere though, just gotta find it...

**Comment by lambdaupb** [comment] 2019-02-13 18:47
@greyson-signal see #3693 - describes this issue exactly. But editing the rotation afterwards would help as well (as suggested in #8350)

**Comment by Mushoz** [comment] 2020-01-16 09:52
This issue is still happening. For correct behavior, please have a look at how Whatsapp does it. I assume it uses accelerometer to determine the current orientation of the phone when making a picture, even when screen orientation itself is locked to portrait.

**Comment by hex-m** [comment] 2020-11-22 19:11
Seems independent of Device and OS Version. Got this issue on my device too.

### Device info

**Device:** Fairphone 3 (FP3)
**Android version:** 10 (Security patch level 2020-10-05)
**Signal version:** 4.76.3

**Comment by TriggerMeister** [comment] 2021-01-15 03:36
Moto e5 Supra.  Same problem.  It rotates incorrectly in all positions except in standard portrait mode.

**Comment by DirkR** [comment] 2021-01-18 18:51
Same problem here, with a Motorola Moto G5. When the display orientation is not locked, then rotating the phone clockwise into landscape mode rotates the camera picture 180° counter-clockwise and vice versa.

**Comment by lambdaupb** [comment] 2022-01-27 07:18
This still happens. It's ridiculous.

**Comment by Mushoz** [comment] 2022-01-27 11:39
Can confirm. Still an issue today.

**Comment by lambdaupb** [comment] 2022-03-28 11:54
Still an issue.

**Comment by morremeyer** [comment] 2022-05-27 12:21
This is still an issue. Can someone prevent the stale bot from staling this issue?

**Closed** 2022-06-14 19:26 UTC
Labels: acknowledged
