### ISSUE TITLE
[bug] thumbnail not charging properly. half blur

### ISSUE THREAD

**Issue by JodyVanden** [signalapp/Signal-Android#10757] opened 2021-01-21 21:56 UTC
Bug description
Thumbnail displays only half of the photo correctly and the other half is blur. This happen times to times, not sure if it's while the photo gets uploaded or when it gets generated

Steps to reproduce
in a conversation, select the camera
select any photo to be shared
once the photo selected click share
Actual result:

photo appears half ok and half blur
Expected result:
photo should be entirely displayed

Screenshots
![Screenshot_20210121_231020](https://user-images.githubusercontent.com/25408202/105417329-8c5e4880-5c8f-11eb-8d7a-ef40c6a5f179.jpg)

Device info
Device: Huawei 20 pro

Android version: 10.0.0

Signal version: 5.2.3

Link to debug log
https://debuglogs.org/9b131a4889f86e4d8e5812932fb1791fe5861193a47caf716472d306f45c0f66

**Comment by Tursko** [comment] 2021-01-22 19:02
This is a known glide bug that has yet to be solved.

**Comment by JodyVanden** [comment] 2021-01-24 00:11
I checked the open issues before reporting that one.
I am not cropping the image before sending so I think it's a different issue; might be related on how the thumbnail is created but still different behaviour

**Comment by greyson-signal** [comment] 2021-01-24 08:15
Closing as duplicate of #9082

**Closed by greyson-signal** 2021-01-24 08:15 UTC

**Comment by Tursko** [comment] 2021-01-24 19:28
> I checked the open issues before reporting that one.
> I am not cropping the image before sending so I think it's a different issue; might be related on how the thumbnail is created but still different behaviour

It's the same issue. It was just easily reproducible at the time by cropping.

It'll happen some what randomly. Same issue.
