### ISSUE TITLE
5.52.5 Front facing camera not working Pixel 3

### ISSUE THREAD

**Issue by Vggh** [signalapp/Signal-Android#12521] opened 2022-10-14 01:53 UTC
Bug description:
Front facing camera not working if launched from Signal app. Camera works fine if launched from Linked Devices. Camera works fine outside of Signal. Issue persisting last few versions.

Steps to reproduce:
open Signal chat
press camera icon
black camera screen
press camera trigger
Actual result: Black screen

Expected result: 
Signal camera works

Device info:
Device: Pixel 3
Android version: SP1A.210812.016.C2.2022090700
Signal version: 5.52.5

Link to debug log:
https://debuglogs.org/android/5.52.5/c114445422aec18ad23ef2e6ededa7c55f2d6f691db636c14ff89cfcca5a802b

Signal Camera screenshot:
![signal-2022-10-14-12-43-43-156](https://user-images.githubusercontent.com/115045800/195743736-c401c4b6-cf23-4272-9693-a91b9aba1bbd.png)

Signal Linked Devices screenshot:
![signal-2022-10-14-12-43-48-850](https://user-images.githubusercontent.com/115045800/195743819-ff65534d-3271-4a57-82bf-4d30152f73f3.png)

**Comment by Tursko** [comment] 2022-10-14 15:22
This is a duplicate. https://github.com/signalapp/Signal-Android/issues/12491

**Comment by greyson-signal** [comment] 2022-10-17 14:02
Closing as a duplicate of #12491

**Closed by greyson-signal** 2022-10-17 14:02 UTC
