### ISSUE TITLE
Panning sideways over a zoomed image causes switching to other image

### ISSUE THREAD

**Issue by Meteor0id** [signalapp/Signal-Android#10324] opened 2020-12-20 16:51 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- Full screen some image
- Zoom in with pinch zoom
- Pan around all you like
- Pan all the way to the right till you can go no further
- Attempt to pan back left

**Actual result:** You switch to another image
**Expected result:** Since you are still zoomed, swiping in any direction should only let you pan. You should be able to pan left.

### Device info

**Device:** Motorola Moto G7 Plus
**Android version:** 10.0
**Signal version:** 50.0.8

**Comment by mdatla** [comment] 2022-11-04 22:29
I'm seeing this issue as well.
Android, Pixel 7 Pro

**Comment by mdatla** [comment] 2022-11-04 22:31
What's the process to reopen this ticket?

**Comment by zeyadtamimi** [comment] 2023-04-10 06:46
Hey,

I saw the comments on #12629 and I see where you are coming from, allowing paging while zoomed in does have benefits for some people.  However, in trying to get my own circle of friends to use signal I have encountered multiple complains regarding this behavior.  In fact there are times where we download images so we can use a separate photo viewing application.

Given the fact that there will always be two differing opinions on this behavior, wouldn't  it be better to have a setting so that the user can chose which behavior best suites their use case? 

If you are open to the idea then I can try reviving the changes with a new "Image Viewer" setting under which will allow people to switch to a mode where the image viewer does not page while panning a zoomed in photo. 

Lastly, i am not really sure if this is good etiquette so I apologize in advance. However, since @greyson-signal was the last person to comment on the PR I am `@` ing him for some continuity.

**Comment by Meteor0id** [comment] 2023-04-10 12:41
These days Signal had a team of designers  every change of the app goes through them and they rarely take feedback like this seriously. Thanks for trying but good luck.

**Comment by Starcommander** [comment] 2023-07-09 08:47
I think, this is a bit confusing.

I also have sometimes the issue:
You zoom in, and try to pan left.
But Signal switches the image instead allowing to pan left.
Switching the image should only happen, when reaching the border of the image.

Unfortunately, I was not able to reproduce and record this behaviour.

**Comment by Starcommander** [comment] 2023-07-09 09:03
@Meteor0id I would suggest to update the "**expected result**" in this issue.
Expected should be only the possibility to "**pan left**".

When you reach the border, the signal-developers want to be able to switch the image, as you see in PR #12629 (what is ok for me)

**Comment by gregreen** [comment] 2023-09-24 09:22
The most important questions are:
1. What do users expect?
2. Is the current behavior useful to anyone?

On question 1, I think the vast majority of users do not expect the current behavior. When you're zoomed into the middle of an image, you don't expect panning slightly to the left or right to cause the entire image to switch. You might expect the image to switch when you reach the edge, but not right in the middle of the image.

On question 2, I can't actually think of a use case for the current behavior. If you want to switch to the next image, you just zoom out and swipe. Who actually needs to switch images immediately when they're zoomed into the middle of an image? The current behavior prioritizes a very niche behavior, and in doing so prevents the obvious behavior most users will expect and want.

**Comment by michelberger** [comment] 2024-01-26 19:29
I've found a fairly repeatable way to reproduce the problem behavior (Pixel 8 Pro, app version 6.44.3).

1. Open an image from any chat
2. Zoom into the image so that the top and bottom of the image extends beyond the frame of the viewer/screen (so you can now pan up/down as well).  _If zoomed into the center, swiping left and right should pan the image as normal, every time._
4. Pan up or down so that the top or bottom borders of the image are against the viewer border, preventing you from panning up/down further.
5. Let the "smooth" pan animation settle.
6. Panning left or right will now cause the gallery to switch images instead of panning, every time.

Basically, if you're zoomed far in and the top of the image is resting against the top of the viewer, panning any direction except for down will trigger the switch image action, not pan. If you're zoomed into the bottom of the image, panning any direction except for up do the same.

It seems like when zoomed in, to determine if it should pan or switch images, the viewer is only checking if _an_ image border is touching _a_ viewer border (and you are not swiping _away_ from that border), not specifically the left/right border as it should be. 

It does seem like a bug to me, because why would swiping any direction at the top/bottom borders trigger an image change? There will never be anything above or below your current image, so checking if those extents are "maxed out" is pointless, and should not be used to determine if the user intends to pan or switch. 

If a user wanted to view the previous image, they'd go to the left border; not the top or bottom, then wait for the animation to settle, then swipe left.

**Comment by zoli13** [comment] 2024-02-01 13:40
It's **incredible** annoying and makes image viewing basically impossible within the app!

There is a very simple solution for this:

- If image is zoomed, do NOT switch image during panning, just scroll it.

- If image is not zoomed, switch image during panning.

**Comment by thanhtacles** [comment] 2024-06-12 23:22
Can't believe they still have this ridiculous after all these years. It's really bothersome. Like, you don't even need photos to pan when zoomed in anyway, there is no use case for that

**Comment by Meteor0id** [comment] 2024-06-12 23:43
I once asked a signal android dev why they didn't make time to fix obvious oversights. He responded with some reply that he doesn't plan what they work on, generally the design team plans what gets worked on. Guess what, the design team never ever interacts with users directly, they just do whatever the fuck they themselves feel is important and consistently refer to 'uset studies' as their reference wfor what matters. A user study never brings details to the surface, they should know that, but appearently just don't care to change their workflow.

The feeling I get is that everyone is getting paid their salery and no one really cares about small design issues. Only when an issue is technical does it get addressed because it doesn't involve the design team.
The ceo ? God do you even recall her name? We never hear from her either.

**Comment by greyson-signal** [comment] 2024-06-13 20:26
> I once asked a signal android dev why they didn't make time to fix obvious oversights. He responded with some reply that he doesn't plan what they work on, generally the design team plans what gets worked on.

Not sure who said that or if there was some miscommunication, but while the design team is certainly crucial when designing new features or helping with new UI-related things, they definitely don't plan out what bugs we fix.

I think this didn't get fixed because, to be honest, it's actually relatively difficult for me to trigger. I likely just use the app differently from ya'll though. Looking at how other apps do it, it seems like Telegram takes our approach (pan while zoomed in until you hit the edge, then go to next photo) but doesn't have the bug. WhatsApp doesn't let you change to the next photo while you're zoomed in. The latter is definitely easier, can see if I can do it.

**Comment by zoli13** [comment] 2024-06-14 04:22
WhatsApp solution is perfect.
See my note: https://github.com/signalapp/Signal-Android/issues/10324#issuecomment-1921350257

**Comment by mstange** [comment] 2024-06-14 05:07
> it's actually relatively difficult for me to trigger.

Here's a way that should work well:

 1. Send three pictures, with [this random picture of text I found on wikimedia](https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Kelvinsong%E2%80%94Font_test_page.pdf/page1-926px-Kelvinsong%E2%80%94Font_test_page.pdf.jpg) being the second picture.
 2. On your Android phone, in portrait mode, open the second picture in Signal.
 3. Zoom in far enough that the picture is slightly taller than the screen.
 4. Panning around in the picture without lifting your finger from the screen, try to read all the text on the page.

**Comment by michelberger** [comment] 2024-06-14 05:42
The easiest, most repeatable way to trigger the bug 100% of the time is to:

1. Open the latest picture (or any picture that isn't the oldest) in any chat where more than one image has been shared. JPG, PNG, GIF... doesn't matter.
2. Zoom in all the way to the center of the image.
3. Pan to the very top-middle of the image, so that the image hits the top of the screen and stops moving.
4. Now drag your finger down and right diagonally.

The expected behavior is that it will pan left. Instead, your image gallery will go to the previous image _every time_. Even if you're still in the middle of the image's x-axis and nowhere near the left border of the image. The same is true for panning right if there are newer images in the gallery.

So long as you're not panning "away" from any of the four borders of the image (hence the diagonal swipe in Step 4, which has you pan slightly into the top border), it registers the entire swipe action as the the user trying to switch.

It's only checking that the zoomed in image is "up against" any border. It's not checking which border that is, and seems to consider the top-most and bottom-most borders to be fair game. Instead, it should only care about the left-most or right-most borders when deciding if it should trigger an image switch in the respective direction.

**Comment by greyson-signal** [comment] 2024-06-14 16:15
I believe I've found the issue, as well as why I have difficulty reproducing. We have two different zoomable image views that we choose between depending on image size. The one for smaller images is the one that has the bug, while the one for bigger images appears to work as intended. At least for my testing. 

The only reason the malfunctioning one is still around is because we used to have an EXIF bug in the other one, but that bug was fixed a while ago, so we should be able to use the working one all the time now. That change will be in 7.10, lemme know if you still see the issue :+1:

**Closed** 2024-06-24 19:49 UTC
Labels: acknowledged
