### ISSUE TITLE
Schedule Send Shows up on Lock Screen

### ISSUE THREAD

**Issue by lhhel9l3** [signalapp/Signal-Android#12903] opened 2023-04-15 22:46 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Hello, if you use the "schedule send" feature on a Google pixel device, the send time shows up on the lock screen and always on display with an alarm clock icon. It makes it look like an alarm was set for waking up using the clock app.

Could you please fix the signal app so that the schedule send time does not show up on the lock screen always on display? Thanks.

### Steps to reproduce
- Schedule send the message
- Lock the phone

**Actual result:** There is a picture of an "alarm" on the always on display
**Expected result:** The schedule send should be internal to the app and not make it look like the clock app alarm will ring at that time

### Screenshots
![Screenshot_20230415-153847](https://user-images.githubusercontent.com/113508618/232256205-7e352f0c-8d8c-4ac0-9354-69b3f3c6eb16.png)

### Device info

**Device:** Google Pixel 6A
**Android version:** 13
**Signal version:** 6.17.3

### Link to debug log

N/A, should be easily reproducible

**Comment by Sgn-32** [comment] 2023-04-16 09:00
Related #12848

**Comment by greyson-signal** [comment] 2023-04-16 15:11
Closing as a duplicate of #12806

**Closed by greyson-signal** 2023-04-16 15:11 UTC
