### ISSUE TITLE
Handle group name and picture for multimedia messages

### ISSUE THREAD

**Issue by Codain** [signalapp/Signal-Android#8754] opened 2019-04-11 07:15 UTC
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Enhancement description
Mutlimedia groups (i.e. groups with non-signal user members) can't have a group name, which makes it difficult to find and use them.

### Steps to reproduce
- Create a group made of non-signal users

**Actual result:** The group name and picture disappear
**Expected result:** Allow to set group name and picture

### Device info
**Device:** BlackBerry Priv
**Android version:** 6.0.1
**Signal version:** 4.37.2

**Comment by Cerberus0** [comment] 2019-04-11 10:24
Duplicate of https://github.com/signalapp/Signal-Android/issues/7675

**Closed** 2019-04-12 19:23 UTC
