### ISSUE TITLE
No longer able to connect to proxy

### ISSUE THREAD

**Issue by tinyboxvk** [signalapp/Signal-Android#11586] opened 2021-09-02 01:19 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I have been running a proxy without issues for months until recently. I tried rebuilding the server again using the procedure in https://signal.org/blog/help-iran-reconnect/, same as how I deployed the old one, but no luck.

### Steps to reproduce
- Deploy a new Ubuntu 20.04 (LTS) x64 droplet in DigitalOcean
- Follow the steps in https://signal.org/blog/help-iran-reconnect/
- Enable "Use proxy"

**Actual result:**  
Connection failed

**Expected result:** 
Connection successful

### Device info
**Device:** OnePlus 6
**Android version:** 11
**Signal version:** 5.22.6

### Link to debug log
https://debuglogs.org/6c80eb0d5319f91460c845537210a3d99580487248cca8c46f58d9b4ae108080

**Comment by cody-signal** [comment] 2021-09-02 14:25
Logs show that the SSL certificate is not setup properly on the proxy. Can you make sure it is and try again. Everything seems to be working as expected.

**Comment by tinyboxvk** [comment] 2021-09-03 12:36
```
Requesting a certificate for xxx.xxx.xxx

Successfully received certificate.
Certificate is saved at: /etc/letsencrypt/live/xxx.xxx.xxx/fullchain.pem
Key is saved at:         /etc/letsencrypt/live/xxx.xxx.xxx/privkey.pem
This certificate expires on 2021-12-02.
These files will be updated when the certificate renews.
```

I believe the cert was set up correctly, but Signal still shows failed connection.

**Comment by cody-signal** [comment] 2021-09-03 15:20
Hrm. We haven't changed much around the proxy code, and I can't reproduce it. Not sure what else to tell you. Are there other proxies you can test with that you know are working for others? I can probably get one for testing if you email me at <my-github-name>@signal.org

**Comment by azurvii** [comment] 2021-09-05 13:59
I think I'm hitting the same issue, after upgrading to 5.22.7.
I have 2 cases of unable to connect to the proxy, after installing the latest version in the past 2 days (Unfortunately I am unable to figure out what version these were on). And I have one case able to connect without the upgrade (I'd need some time to find out what version this case is on).
All 3 are trying to connect to the same proxy.
`curl` said the proxy's certificate was valid. So my proxy seems to be healthy.

I have not advertised my proxy, so I don't think I'm using the same proxy as @tinyboxvk.

To me these suggest that the latest android app seems to introduce some issue with the proxy. Lemme know if you need any additional info.

**Comment by azurvii** [comment] 2021-09-05 14:01
@cody-signal if the log suggests the SSL certificate is not setup properly on the proxy, then I guess it might worth to check whether the SSL cert verification in the 5.22.[67] android versions still works as intended.

**Comment by WhyRoy** [comment] 2021-09-06 02:55
I have the same issue，when update to the newest version, you can not use proxy

**Comment by azurvii** [comment] 2021-09-06 07:33
> And I have one case able to connect without the upgrade (I'd need some time to find out what version this case is on).

FWIW, the case of mine that currently still works with the proxy is with 5.15.6.

**Comment by cody-signal** [comment] 2021-09-06 18:26
Alright, thanks for all the extra info folks. Looks like we've introduced a regression on the proxy.

**Comment by WhyRoy** [comment] 2021-09-07 01:56
> Alright, thanks for all the extra info folks. Looks like we've introduced a regression on the proxy.

thx for replying, looking forward to an new edition that fix this vital issue for us users that who must use signal through proxy

**Comment by WhyRoy** [comment] 2021-09-07 08:18
seems signal has fixed this issue, I can use proxy now on version 5.22.7

**Comment by azurvii** [comment] 2021-09-07 09:06
@WhyRoy which version did you use when it was not working?

I'm using 5.22.7 (apk downloaded from signal, not the play store version) and I'm unable to connect to a proxy.

**Comment by greyson-signal** [comment] 2021-09-07 14:46
Hi there, we just released 5.22.8 with a fix for this. Thanks!

**Closed by greyson-signal** 2021-09-07 14:46 UTC

**Comment by azurvii** [comment] 2021-09-08 00:56
Thanks @greyson-signal, I just got an update popup from signal. It updated my client to 5.22.8 and the proxy connection started to work.

Looking at the [change](https://github.com/signalapp/Signal-Android/compare/v5.22.7...v5.22.8), it seemed the main change was the signal url.

**Comment by tinyboxvk** [comment] 2021-09-08 01:57
Re-deploying the proxy also works. This commit https://github.com/signalapp/Signal-TLS-Proxy/commit/c2198487ba6712992929cae9b5d79ce656b65772 updated the domain list and fixed the issue.

**Comment by greyson-signal** [comment] 2021-09-08 12:46
Yeah, what will likely happen is that in about 3 months or so we'll update the domain again, and hope that by then people have deployed the new proxy image. So I recommend updating your proxies whenever you get the chance.
