### ISSUE TITLE
Signal App crashes immediately upon trying to open a conversation on OnePlus 7 Pro

### ISSUE THREAD

**Issue by GSarathChandra** [signalapp/Signal-Android#10716] opened 2021-01-18 06:26 UTC
Bug description: 
Signal app crashes immediately upon trying to open a conversation on my OnePlus 7 Pro.

Symptoms and observations:
1. Installed the app from Google Play Store and was able to register successfully. App opens fine when I try to open it from the launcher. I have a conversation (individual, not a group) already present. The app crashes when I try to open the conversation.
2. Clicking on the pencil icon to create a new conversation is also crashing the app.
3. I am able to see the notifications for the conversation in the notification bar. Also able to respond to messages from the notification bar itself.
4. Device details:
Android version running on the device: 10
Location: India 

Please let me if any further info is needed.

**Comment by Leptopoda** [comment] 2021-01-18 07:10
Hi there and welcome!
Sadly you did not seem to have used the issue template. Could you please update your post (or comment below) the filled in template (I've posted it below)?
Especially a debuglog would help emense because it contains information about the crash and also your signal version. 

Another troubleshooting step is could you try opening the app while being in flightmode? There was a bug in a previous version causing the app to crash but should be fixed with an updated version.

Let's begin with a checklist: Replace the empty checkboxes [ ] below with checked ones [x] accordingly.

- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Screenshots
you can drag and drop images below


### Device info
replace the examples with your info
**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

### Link to debug log
immediately after the bug has happened capture a debug log via Signal's advanced settings and paste the link below

**Comment by GSarathChandra** [comment] 2021-01-18 13:40
https://debuglogs.org/006e2d19770c67aa45754866ec8e0cf864c2369290b97acf967dd2abfd7f7904

**Comment by Leptopoda** [comment] 2021-01-19 23:08
Hi there,
A fix was made with 5.2.3 I don't know if it applies to your exact problem but worth a try

**Comment by GSarathChandra** [comment] 2021-01-20 11:44
Seeing this after updating to Signal 5.2.3:
https://debuglogs.org/d18d802971c19a3886854b74de0783ed0b260af9beeb9f30b74d44a5404a29d1

**Comment by Leptopoda** [comment] 2021-01-20 12:03
```
java.io.EOFException
	at okio.RealBufferedSource.require(RealBufferedSource.java:65)
	at okio.RealBufferedSource.readByte(RealBufferedSource.java:78)
	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:117)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
```

```
service.whispersystems.org:443, proxy=DIRECT hostAddress=textsecure-service.whispersystems.org/13.248.212.111:443 cipherSuite=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 protocol=http/1.1}
[5.2.3] [11471] 2021-01-20 11:25:32.386 IST W RestStrategy: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.getServiceConnection(PushServiceSocket.java:1472)
[5.2.3] [11471] 2021-01-20 11:25:32.386 IST W RestStrategy: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1398)
[5.2.3] [11471] 2021-01-20 11:25:32.386 IST W RestStrategy: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.getMessages(PushServiceSocket.java:417)
[5.2.3] [11471] 2021-01-20 11:25:32.386 IST W RestStrategy: 	at org.whispersystems.signalservice.api.SignalServiceMessageReceiver.retrieveMessages(SignalServiceMessageReceiver.java:270)
[5.2.3] [11471] 2021-01-20 11:25:32.386 IST W RestStrategy: 	at org.thoughtcrime.securesms.messages.RestStrategy.enqueuePushDecryptJobs(RestStrategy.java:85)
[5.2.3] [11471] 2021-01-20 11:25:32.386 IST W RestStrategy: 	at org.thoughtcrime.securesms.messages.RestStrategy.execute(RestStrategy.java:39)
[5.2.3] [11471] 2021-01-20 11:25:32.386 IST W RestStrategy: 	at org.thoughtcrime.securesms.messages.BackgroundMessageRetriever.executeBackgroundRetrieval(BackgroundMessageRetriever.java:87)
[5.2.3] [11471] 2021-01-20 11:25:32.386 IST W RestStrategy: 	at org.thoughtcrime.securesms.messages.BackgroundMessageRetriever.retrieveMessages(BackgroundMessageRetriever.java:67)
[5.2.3] [11471] 2021-01-20 11:25:32.386 IST W RestStrategy: 	at org.thoughtcrime.securesms.gcm.FcmFetchService.retrieveMessages(FcmFetchService.java:85)
[5.2.3] [11471] 2021-01-20 11:25:32.386 IST W RestStrategy: 	at org.thoughtcrime.securesms.gcm.FcmFetchService.fetch(FcmFetchService.java:75)
[5.2.3] [11471] 2021-01-20 11:25:32.386 IST W RestStrategy: 	at org.thoughtcrime.securesms.gcm.FcmFetchService.lambda$muilVNey22kbtVkSSKzu4MMnpho(Unknown Source:0)
[5.2.3] [11471] 2021-01-20 11:25:32.386 IST W RestStrategy: 	at org.thoughtcrime.securesms.gcm.-$$Lambda$FcmFetchService$muilVNey22kbtVkSSKzu4MMnpho.run(Unknown Source:2)
[5.2.3] [11471] 2021-01-20 11:25:32.386 IST W RestStrategy: 	at org.thoughtcrime.securesms.util.concurrent.SerialMonoLifoExecutor.lambda$enqueue$0(SerialMonoLifoExecutor.java:44)
[5.2.3] [11471] 2021-01-20 11:25:32.386 IST W RestStrategy: 	at org.thoughtcrime.securesms.util.concurrent.SerialMonoLifoExecutor.lambda$enqueue$0$SerialMonoLifoExecutor(Unknown Source:0)
[5.2.3] [11471] 2021-01-20 11:25:32.386 IST W RestStrategy: 	at org.thoughtcrime.securesms.util.concurrent.-$$Lambda$SerialMonoLifoExecutor$zGI5_MD8odfHaH2-Q_X27ikdsnk.run(Unknown Source:4)
[5.2.3] [11471] 2021-01-20 11:25:32.386 IST W RestStrategy: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[5.2.3] [11471] 2021-01-20 11:25:32.386 IST W RestStrategy: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[5.2.3] [11471] 2021-01-20 11:25:32.386 IST W RestStrategy: 	at java.lang.Thread.run(Thread.java:919)
[5.2.3] [11471] 2021-01-20 11:25:32.386 IST W RestStrategy: Caused by: java.io.IOException: unexpected end of stream on Connection{textsecure-service.whispersystems.org:443, proxy=DIRECT hostAddress=textsecure-service.whispersystems.org/13.248.212.111:443 cipherSuite=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 protocol=http/1.1}
[5.2.3] [11471] 2021-01-20 11:25:32.386 IST W RestStrategy: 	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:208)
[5.2.3] [11471] 2021-01-20 11:25:32.386 IST W RestStrategy: 	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
[5.2.3] [11471] 2021-01-20 11:25:32.386 IST W RestStrategy: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[5.2.3] [11471] 2021-01-20 11:25:32.386 IST W RestStrategy: 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
[5.2.3] [11471] 2021-01-20 11:25:32.386 IST W RestStrategy: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[5.2.3] [11471] 2021-01-20 11:25:32.386 IST W RestStrategy: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[5.2.3] [11471] 2021-01-20 11:25:32.386 IST W RestStrategy: 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
[5.2.3] [11471] 2021-01-20 11:25:32.386 IST W RestStrategy: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[5.2.3] [11471] 2021-01-20 11:25:32.386 IST W RestStrategy: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[5.2.3] [11471] 2021-01-20 11:25:32.386 IST W RestStrategy: 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
[5.2.3] [11471] 2021-01-20 11:25:32.386 IST W RestStrategy: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[5.2.3] [11471] 2021-01-20 11:25:32.386 IST W RestStrategy: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127)
[5.2.3] [11471] 2021-01-20 11:25:32.386 IST W RestStrategy: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[5.2.3] [11471] 2021-01-20 11:25:32.386 IST W RestStrategy: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[5.2.3] [11471] 2021-01-20 11:25:32.386 IST W RestStrategy: 	at org.thoughtcrime.securesms.net.DeprecatedClientPreventionInterceptor.intercept(DeprecatedClientPreventionInterceptor.java:36)
[5.2.3] [11471] 2021-01-20 11:25:32.386 IST W RestStrategy: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[5.2.3] [11471] 2021-01-20 11:25:32.386 IST W RestStrategy: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[5.2.3] [11471] 2021-01-20 11:25:32.386 IST W RestStrategy: 	at org.thoughtcrime.securesms.net.RemoteDeprecationDetectorInterceptor.intercept(RemoteDeprecationDetectorInterceptor.java:22)
[5.2.3] [11471] 2021-01-20 11:25:32.386 IST W RestStrategy: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[5.2.3] [11471] 2021-01-20 11:25:32.386 IST W RestStrategy: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[5.2.3] [11471] 2021-01-20 11:25:32.386 IST W RestStrategy: 	at org.thoughtcrime.securesms.net.UserAgentInterceptor.intercept(UserAgentInterceptor.java:20)
[5.2.3] [11471] 2021-01-20 11:25:32.386 IST W RestStrategy: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[5.2.3] [11471] 2021-01-20 11:25:32.386 IST W RestStrategy: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[5.2.3] [11471] 2021-01-20 11:25:32.386 IST W RestStrategy: 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)
[5.2.3] [11471] 2021-01-20 11:25:32.386 IST W RestStrategy: 	at okhttp3.RealCall.execute(RealCall.java:93)
[5.2.3] [11471] 2021-01-20 11:25:32.386 IST W RestStrategy: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.getServiceConnection(PushServiceSocket.java:1465)
[5.2.3] [11471] 2021-01-20 11:25:32.386 IST W RestStrategy: 	... 17 more
[5.2.3] [11471] 2021-01-20 11:25:32.386 IST W RestStrategy: Caused by: java.io.EOFException: \n not found: limit=0 content=â€¦
[5.2.3] [11471] 2021-01-20 11:25:32.386 IST W RestStrategy: 	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:240)
[5.2.3] [11471] 2021-01-20 11:25:32.386 IST W RestStrategy: 	at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:215)
[5.2.3] [11471] 2021-01-20 11:25:32.386 IST W RestStrategy: 	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
[5.2.3] [11471] 2021-01-20 11:25:32.386 IST W RestStrategy: 	... 42 more
```

This seems to be the problem

**Comment by GSarathChandra** [comment] 2021-01-21 19:57
Can anyone suggest any workarounds for this at least?

**Comment by Leptopoda** [comment] 2021-01-21 20:03
Can you open a conversation when bring in flight mode?
It seems to be some problem with the communication to the server.
Maybe you could try to clear the cache.

Also if you don't mind your chats you could just clear the storage of signal (like deleting the whole signal)

**Comment by GSarathChandra** [comment] 2021-02-01 12:41
I was able to reproduce the issue while in Airplane mode also.

Here's the latest debug log after I tried to Clear storage & Clear Cache:
https://debuglogs.org/19e267e0831e72e0552608f00323bf7540d2761f9f3d087ca2090f5844940200

**Closed** 2022-02-03 02:22 UTC
Labels: wontfix
