### ISSUE TITLE
Groups do not show up (and are not searchable) when 'sharing' media from other apps

### ISSUE THREAD

**Issue by ryannathans** [signalapp/Signal-Android#7552] opened 2018-03-22 06:55 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Groups are only shown in 'recent chats' when searching for a group/contact to share media. This makes it impossible to share media with a group unless its in the 'recent chats' section.

### Steps to reproduce
- Push share (with signal) on a photo in gallery

**Actual result:** Groups are only shown in the 'Recent chats' section at the top of the list on the 'Share with' signal screen (if actually one of the most recent chats). Groups do not show up in the search results or in the list of contacts below 'Recent chats'
**Expected result:** Groups appear in the list of contacts to share media with, additionally, groups appear in the search results

### Device info

**Device:** Sony Xperia XZ Premium
**Android version:** 8.0.0
**Signal version:** 4.17.5

**Comment by FeuRenard** [comment] 2018-03-22 09:25
Duplicate of #7202

**Comment by ryannathans** [comment] 2018-03-22 09:31
How I didn't find any of the duplicate issues really bothers me. Spent a good ten minutes looking...

**Comment by 2-4601** [comment] 2018-03-22 17:21
> How I didn't find any of the duplicate issues really bothers me. Spent a good ten minutes looking...

Because Github issue search feature sucks big time...

Closing as duplicate.

**Closed by 2-4601** 2018-03-22 17:21 UTC
