### ISSUE TITLE
Thumbnail is generated from deleted part of the video

### ISSUE THREAD

**Issue by M3DZIK** [signalapp/Signal-Android#13713] opened 2024-09-26 15:26 UTC
I've encountered an issue with thumbnail generation when trimming video clips. In my specific case, I trimmed a 60-second video, removing the first 50 seconds. However, the generated thumbnail appears to be a frame captured from the deleted portion of the video rather than the remaining 10 seconds.

**Steps to reproduce:**

- Upload a video for example a 60 seconds long.
- Trim the video for example to keep only the last 10 seconds.
- Send the video.
- Observe the generated thumbnail.

https://github.com/user-attachments/assets/050d68a3-d2dd-4b9d-a835-6f77ffc3998b

**Comment by Tursko** [comment] 2024-10-01 21:20
I believe this is essentially a duplicate of https://github.com/signalapp/Signal-Android/issues/12908

**Comment by greyson-signal** [comment] 2024-10-03 14:19
Yeah, closing as a duplicate of #12908.  Thumbnails are not transmitted as part of sending an attachment, meaning that the receiver generates their own thumbnail. So there's no data leakage. But I know it's not ideal and potentially alarming. We'll look into it.

**Closed by greyson-signal** 2024-10-03 14:19 UTC
