### ISSUE TITLE
Can't open the app, "tap to unlock" does nothing

### ISSUE THREAD

**Issue by oittaa** [signalapp/Signal-Android#11121] opened 2021-03-19 16:09 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Every now and then when I open the app "Signal is locked" fingerprint authentication screen doesn't work. Placing a finger on the reader does nothing, and clicking "tap to unlock" does nothing. Killing the application and opening it again usually solves the issue temporarily. After killing the app the OS "Unlock Signal" fingerprint request also pops up and I'm able to log in.

### Steps to reproduce
- Open the app
- 

**Actual result:** Can't do anything
**Expected result:** Placing a finger on the fingerprint reader logs in

### Device info

**Device:** Google Pixel 5
**Android version:** 11
**Signal version:** 5.4.12

**Comment by greyson-signal** [comment] 2021-03-19 18:49
Are you able to provide a debuglog taken after one of these incidents?

**Comment by greyson-signal** [comment] 2021-03-19 18:50
This seems similar enough that I'm going to mark it as a duplicate of #11122

**Closed by greyson-signal** 2021-03-19 18:50 UTC

**Comment by oittaa** [comment] 2021-03-19 20:54
Yeah, seems to be the same issue. It wasn't there when I made this report and tried to search something similar.
