### ISSUE TITLE
Phone's microphone not working during calls

### ISSUE THREAD

**Issue by Forage** [signalapp/Signal-Android#13497] opened 2024-04-01 16:48 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
For quite some time now, my microphone does not work when making calls. It's basically the same issue as #12259, which got closed without solution.

I can record Signal voice messages, I can call with other apps like WhatsApp or regular phone calls, but as soon as I call someone with Signal, they don't hear me. During neither a voice call, nor a video call.
The mic indication icon that normally moves when picking up sound does not show any activity.

It worked in the past, but for multiple months, at least 6, it doesn't anymore. I have not changed phone in between, only normal app and ROM updates. No compete ROM reinstalls/wipes nor major Android version updates.
I completely reinstalled the app, I made sure it has all the permissions needed (otherwise voice messages wouldn't have worked either). 

The weird thing is though, it does work through my Bluetooth headset's microphone. If that one is connected I can call with Signal, the mic icon shows activity and people can hear me.
As soon as I disconnect the headset, before or during a call, the phone's microphone does not get used.

Today I upgraded from Android 13 to 14, still to no avail.

### Steps to reproduce
- Call someone with Signal
- Talk when the person picks up

**Actual result:** There's no mic icon activity and the other side does not hear me
**Expected result:** The other side should hear me

### Device info

**Device:** OnePlus 6
**Android version:** 13/14
**Signal version:** 7.1.3

### Link to debug log
https://debuglogs.org/android/7.1.3/6006ca6ad942fabad5468e6c653df260b62ce14983986260a4e50f602adf751a

**Comment by kenballus** [comment] 2024-04-04 22:07
Have you tried switching off speaker? I have a OnePlus 6T with a similar issue, but only on speaker.

**Comment by Forage** [comment] 2024-04-05 10:15
@kenballus spot on. When not on speaker, the mic works as it should. As soon as I switch to speaker, the mic stops working. At least this offers a work-around for the time being, thanks.
This gives me the impression that the issue might have been introduced with the introduction of the speaker output switch during calls.

**Comment by Alth3r** [comment] 2024-04-05 12:38
> Have you tried switching off speaker? I have a OnePlus 6T with a similar issue, but only on speaker.

Can confirm, that this is the same issue for me as well. Whenever the speaker is on, the microphone does not work during (video) calls.

---
**Device:** OnePlus 6
**Android version:** 14 (Lineage OS 21)
**Signal version:** 7.1.3

**Comment by kenballus** [comment] 2024-04-05 13:47
This issue is a duplicate of #13423.

**Closed** 2024-04-05 17:45 UTC
