### ISSUE TITLE
Disappearing messages start ticking from time received and not time read

### ISSUE THREAD

**Issue by mderazon** [signalapp/Signal-Android#7688] opened 2018-04-16 10:09 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
According to the feature announcement on the [blog](https://signal.org/blog/disappearing-messages/):
> the clock starts ticking for each recipient once they’ve read their copy of the message.

From what I have tested, it seems that the clock start ticking from the time it has arrived on the device and not from the time it was read by the recepient

### Steps to reproduce
- Alice sets a short timer for her conversation with Bob, for example 5 sec
- Alice sends a message to Bob (both on Android)
- Bob doesn't open the phone, but hears notification sound for the message.
- Bob waits 10 seconds, opens the conversation with Alice
- Message has already disappeared.

**Actual result:** Message has already disappeared before Bob had time to read it
**Expected result:** Bob should be able to read the message first

### Device info

**Device:** Alice - Pixel XL (1st generation) and Bob - Nexus 5X
**Android version:** 8.1.0
**Signal version:** 4.18.3

Can anyone else confirm this is the current behaviour ?

Thanks.

**Comment by billie80** [comment] 2018-04-16 15:51
According to https://support.signal.org/hc/en-us/articles/213134237-Does-Signal-have-disappearing-messages- the timer for deletion should start after a received message being read.

So what you are experiencing is not the intended behaviour.

#7674 is related. The user experiences messages being deleted immediately after reading them. So the timeout starts after receiving the message. If the message is read after the timeout has completed it is quickly shown before actually getting deleted.

**Comment by 2-4601** [comment] 2018-04-16 17:39
Can't reproduce this. Motorola G4 Play and Nvidia K1. Signal 14.8.3.

Could you share more details for this step: "opens the conversation with Alice"
At what state is Bob's device when? Sleeping? Is Signal open (if it is in what activity)? Do you open the conversation via a notification?

**Comment by mderazon** [comment] 2018-04-18 06:05
I thought the clock starts ticking for both parties when the receiver gets the message, but after testing again, it seems that Alice clock starts ticking immediately and Bob's clock once he reads the message so each participant has their own clock basically.

So it seems like the behavior is okay, but I do think there's a usability issue here.
Alice sees her message disappear and thinks  "hmm, bob might have not had the chance to read it before it disappeared". So it raises question for the deliverability of the message for the user sending it.

On the other hand, having the same clock for both parties basically translates to having read recipients enabled because the message disappearing serves as an implicit hint that it was read.

So I guess it's a trade off between usability and privacy.

**Comment by moxie0** [comment] 2018-04-19 00:47
Closing as the intended functionality

**Closed by moxie0** 2018-04-19 00:47 UTC
