### ISSUE TITLE
"Mark as read" feature from notification channel not working after reply.

### ISSUE THREAD

**Issue by reversesh3ll** [signalapp/Signal-Android#9410] opened 2020-02-20 06:36 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

### Prefix

This issue was already closed on #9042 with the reason: this is designed Android behavior. 
I have recently tested this and this does not seem to be the case currently. I have tested this with Android 10 with the stock/default Messages app, and you can respond to the notification and then mark it as read.

### Original bug description

After answering a text through the notification channel it is no longer possible to mark the conversation as read.

### Steps to reproduce
- close signal
- receive a message
- view the notification, write an answer and hit reply in the notification channel
- try to mark the message(s) as read

**Actual result:** The notification does not disappear, the message is not marked as read.
**Expected result:** The notification disappears, the message is marked as read.

**Comment by moppman** [comment] 2020-07-24 19:33
I can confirm the behavior OP described is still present in v4.67.1.
I think this behavior is not intuitive:
A tap on "mark as read" should mark a message as, well, read. Currently the button doing nothing after replying to a message feels buggy and broken.

I think what Greyson was referring to as "default Android behavior" in the issue that OP linked to is  something else: 
If you reply via notification, the message is not supposed to be marked as read simultaneously. This is how Google Messages does it because they argue that one button should only do one thing. Conversations (xmpp app) behaves the same way.
(One could argue that if you reply to a message, you've obviously also read the message you're replying to, which is why WhatsApp marks messages as read if you reply to them via notification, but this is not the point here)

**Comment by billie80** [comment] 2020-07-25 21:31
From a UI perspective this makes no sense. In the notification channel you have the option to mark the message as read or enter a reply. If mark as read should not be possible after entering a reply then why is the option still there but inactive. If a reply should automatically mark the message as read then the option should not be shown after replying. Swiping should be possible in any case as it should just dismiss the notification but should not mark the message as read.

**Comment by dabat** [comment] 2020-09-01 20:44
I am experiencing this issue as well.
I accidentally posted a duplicate in #9979 because I didn't find this issue when I was searching.
Running Pixel 2 on Android 10, Signal 4.70.3

**Comment by mgohin** [comment] 2020-11-03 14:37
Same here with a OnePlus 3T, Android 9, Signal 4.74.3

**Comment by eduxstad** [comment] 2020-12-17 22:44
This appears to be a bug in Android. I have submitted a bug report [here](https://issuetracker.google.com/issues/175851630). My repo with a reproduction of the issue is [here](https://github.com/eduxstad/MarkReadDemo). Signal will either need to wait and see if the bug is fixed in Android, or rewrite `updateNotification()` to work around it.

**Comment by billie80** [comment] 2022-01-28 15:54
I think it is now possible to mark a message as read after answering, so this could be closed!

**Closed** 2022-01-28 23:06 UTC
