### ISSUE TITLE
Non-Signal SMS refuse to send (but non-Signal calls work)

### ISSUE THREAD

**Issue by Kalytis** [signalapp/Signal-Android#12382] opened 2022-08-09 22:16 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal is my main text app. Lately, sending ordinary SMS via Signal causes them to fail. I still receive them though. Wi-Fi calling is enabled.

**Actual result:** Sending fails

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

### Link to debug log

https://debuglogs.org/android/5.44.5/81b810dfce230604cb5e1725cca6a89dd02c650209dcc87dc32ee431745f41f7

**Comment by erik55** [comment] 2022-08-10 11:48
I have had the same problem many times. It keeps sending (rotating ring) for several minutes, sometimes hours. Then there seems to be a timeout and I get a «SMS sent failed». I can then tap on the failed sms and resend, then it always works immediately.

**Comment by erik55** [comment] 2022-08-10 11:59
I think this is a duplicate of #9030 and #12218

**Comment by greyson-signal** [comment] 2022-10-10 15:01
Closing as a duplicate of #9030

**Closed by greyson-signal** 2022-10-10 15:01 UTC
Labels: wontfix
