### ISSUE TITLE
System UI freezes after receiving a message with a photo on Signal

### ISSUE THREAD

**Issue by azmijewski-dc** [signalapp/Signal-Android#11685] opened 2021-10-14 11:57 UTC
### Bug description
After receiving a message with a photo on Signal System UI freezes and phone needs to be restarted. Does not happen with different messaging apps. Happens both when phone is asleep or on.

### Device info

**Device:** Huawei P30 Pro
**Android version:** 10 (EMUI 11.0.0.159)
**Signal version:** 5.23.14

### Link to debug log
https://debuglogs.org/8974134def86881d6ce1060aca28987cea511186260771c7bcad306763c45e92

**Comment by ilinojkovic** [comment] 2021-11-17 08:59
This is the case for me as well. I haven't noticed is it only when the photos are sent, will need to focus and see if that's the problem, but for sure, in some cases when I receive Signal notifications, System UI crashes. I've found [this reddit](https://www.reddit.com/r/oneplus/comments/p83x0v/signal_app_notifications_causes_system_ui_to_hang/) thread that reports the same.

Device: OnePlus 5
Android version: 10 (OxygenOS 10.0.1)
Signal version: 5.25.7

**Comment by frnsys** [comment] 2021-11-22 14:11
Having this issue was well on the latest signal version, on a Samsung Galaxy S9. Any time a Signal message with a photo is received, the whole system locks up and the phone needs to be rebooted.

**Comment by potash** [comment] 2021-11-23 16:24
What freezes for me is not signal but the system UI rendering the image in the notification. Disabling auto download of images fixes the problem for signal messages but MMS images (which still auto download) are still a problem. ---- On Wed, 17 Nov 2021 03:59:49 -0500  ***@***.***  wrote ----
This is the case for me as well. I haven't noticed is it only when the photos are sent, will need to focus and see if that's the problem, but for sure, in some cases when I receive Signal notifications, System UI crashes. I've found this reddit thread that reports the same.
Device: OnePlus 5
Android version: 10 (OxygenOS 10.0.1)
Signal version: 5.25.7

**Comment by this-is-rafa** [comment] 2021-12-09 21:11
Same issue. Not for every image, but will happen weekly, especially when a barrage of notifications pop up for a group chat. The System UI crashes with an message notification frozen at the top. Phone can't recover and has to be rebooted.

Device: OnePlus 5t
Android version: 10 (OxygenOS 10.0.1)
Signal version: 5.25.7

https://debuglogs.org/14831cc6158187f79471a8903f32799879da0a3e7e2cef513a1e563e8747e3e3
Image came in at 2021-12-09 15:41.

**Comment by azmijewski-dc** [comment] 2021-12-10 08:20
> What freezes for me is not signal but the system UI rendering the image in the notification. Disabling auto download of images fixes the problem for signal messages but MMS images (which still auto download) are still a problem. ---- On Wed, 17 Nov 2021 03:59:49 -0500 ***@***.*** wrote ---- This is the case for me as well. I haven't noticed is it only when the photos are sent, will need to focus and see if that's the problem, but for sure, in some cases when I receive Signal notifications, System UI crashes. I've found this reddit thread that reports the same. Device: OnePlus 5 Android version: 10 (OxygenOS 10.0.1) Signal version: 5.25.7 —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

This workaround worked for me. Hope they fix it in the future however for now I'm gonna pass on the previews in the notifications.

**Comment by potash** [comment] 2022-02-05 20:34
Could there be a setting (perhaps under privacy) to not show image previews in notifications? I think that would be a relatively simple but much more functional workaround for this issue. ---- On Fri, 10 Dec 2021 03:20:34 -0500  ***@***.***  wrote ----



What freezes for me is not signal but the system UI rendering the image in the notification. Disabling auto download of images fixes the problem for signal messages but MMS images (which still auto download) are still a problem. ---- On Wed, 17 Nov 2021 03:59:49 -0500 @.*** wrote ---- This is the case for me as well. I haven't noticed is it only when the photos are sent, will need to focus and see if that's the problem, but for sure, in some cases when I receive Signal notifications, System UI crashes. I've found this reddit thread that reports the same. Device: OnePlus 5 Android version: 10 (OxygenOS 10.0.1) Signal version: 5.25.7 —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.



This workaround worked for me. Hope they fix it in the future however for now I'm gonna pass on the previews in the notifications.

**Comment by azmijewski-dc** [comment] 2022-03-17 07:20
> I've saw this once or twice back when Android 12 came out, but haven't been able to reproduce it since. Do ya'll have a configuration/message/attachment that reliably reproduces the issue?

For me it was usually crashing when I was receiving a photo from someone and the app was showing a preview in the notification banner. It stopped crashing after I turned off photo auto-download.

**Comment by SZemanek** [comment] 2022-03-17 15:55
> > 
> 
> For me it was usually crashing when I was receiving a photo from someone and the app was showing a preview in the notification banner. It stopped crashing after I turned off photo auto-download.

Does the preview show a thumbnail or does it only show the text with maybe a camera emoji?

**Comment by this-is-rafa** [comment] 2022-03-17 16:54
In my case it would show the thumbnail in the preview and freeze the whole UI with the preview stuck in place.

**Comment by SZemanek** [comment] 2022-03-17 17:43
> In my case it would show the thumbnail in the preview and freeze the whole UI with the preview stuck in place.

okay, so in my case, I don't think my phone supports a preview thumbnail in the notification, it just shows a camera emoji.  **OR** if the phone is locked, it just says "Signal" 

I think the easiest way to solve this bug, is to add an option to disable thumbnails in notifications, so that Signal **ONLY** sends TEXT to android's notification process.

**Comment by azmijewski-dc** [comment] 2022-03-17 19:23
> > > 
> > 
> > 
> > For me it was usually crashing when I was receiving a photo from someone and the app was showing a preview in the notification banner. It stopped crashing after I turned off photo auto-download.
> 
> Does the preview show a thumbnail or does it only show the text with maybe a camera emoji?

Before turning off photo auto-download it was showing a thumbnail. However after disabling photo auto-download it just shows the camera emoji and "Photo" text.

**Comment by clauz9** [comment] 2022-04-02 21:32
> I've saw this once or twice back when Android 12 came out, but haven't been able to reproduce it since.

If I look back thru the beta threads, I've been suffering from this for quite a while now... 
https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-5-10-0-release/31813/89?u=clauz

here are some steps to reproduce, at least on my device

1. get 2 devices, a sender and a receiver. 
2. my affected device (the receiver) has Android 10,
and I haven't been able to reproduce the bug on my Android 11 device, so.... I assume it's hardware dependent. 
2. make sure you don't have any unread messages, in any conversations, (don't ask me why, it just made the bug more reliable)
3. remove signal from recent apps (app switcher), on the affected device 
4. stay on the home screen
5. Send a tall aspect ration picture with attached text to the affected device, 
6. Make the attached text 14 char long, I used `12345678901234` (again, don't ask me why 🤷 )

<details>
<summary>This is the image that works for me</summary>

![signal-2022-04-03-000635](https://user-images.githubusercontent.com/77681918/161401663-1a769acd-4c8a-44b0-975d-a4a0a7d2149b.jpeg)

</details>

8.  Wait for the notification to show up, and the UI to freeze. 

@cody-signal  if the steps don't work for you, let me know and I can give you whatever logs you need from my affected device 👍

**Comment by clauz9** [comment] 2022-05-12 21:05
fixed in: https://github.com/signalapp/Signal-Android/commit/8f2c5d43dfa61c59dd377c2c3e6f20b00e82ffc7

**Comment by alex-signal** [comment] 2022-05-13 12:28
Closing as duplicate.

**Closed by alex-signal** 2022-05-13 12:28 UTC
