### ISSUE TITLE
Full text search has incorrect styling in dark mode

### ISSUE THREAD

**Issue by burntcookie90** [signalapp/Signal-Android#7826] opened 2018-05-23 01:05 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

The styling for full text search is light for dark mode.

### Steps to reproduce
- be in dark mode
- search using full text search
- observe the incorrect ui

**Actual result:**  UI is white for full text search in dark mode

**Expected result:** UI should be dark

### Screenshots
[Screenshot](https://photos.app.goo.gl/SbbMC5yzZ8sUjpDw9)

### Device info

**Device:** Google Pixel 2XL
**Android version:** Android P
**Signal version:** 4.20.2

**Comment by jlund-signal** [comment] 2018-05-23 06:20
Duplicate of #7821. Thanks for being a beta tester!

**Closed by jlund-signal** 2018-05-23 06:20 UTC

**Comment by burntcookie90** [comment] 2018-05-23 13:32
Whoops, sorry about that! :man_facepalming:
