### ISSUE TITLE
Signal 5.46.6 crashes: cannot locate symbol "__read_chk"

### ISSUE THREAD

**Issue by jakobcornell** [signalapp/Signal-Android#12409] opened 2022-08-21 14:39 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

<hr>

Signal crashes with the following exception pretty much right away:

```
E/AndroidRuntime(16098): FATAL EXCEPTION: signal-io-bounded-0
E/AndroidRuntime(16098): Process: org.thoughtcrime.securesms, PID: 16098
E/AndroidRuntime(16098): java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__read_chk" referenced by "libsignal_jni.so"...
E/AndroidRuntime(16098): 	at java.lang.Runtime.loadLibrary(Runtime.java:364)
E/AndroidRuntime(16098): 	at java.lang.System.loadLibrary(System.java:526)
E/AndroidRuntime(16098): 	at org.signal.libsignal.internal.Native.loadLibrary(Native.java:59)
E/AndroidRuntime(16098): 	at org.signal.libsignal.internal.Native.<clinit>(Native.java:68)
E/AndroidRuntime(16098): 	at org.signal.libsignal.zkgroup.ServerPublicParams.<init>(ServerPublicParams.java:14)
E/AndroidRuntime(16098): 	at org.whispersystems.signalservice.api.groupsv2.ClientZkOperations.create(ClientZkOperations.java:31)
E/AndroidRuntime(16098): 	at org.whispersystems.signalservice.api.SignalServiceAccountManager.<init>(SignalServiceAccountManager.java:158)
E/AndroidRuntime(16098): 	at org.thoughtcrime.securesms.push.AccountManagerFactory.createUnauthenticated(AccountManagerFactory.java:76)
E/AndroidRuntime(16098): 	at org.thoughtcrime.securesms.registration.VerifyAccountRepository.requestVerificationCode$lambda-0(VerifyAccountRepository.kt:43)
E/AndroidRuntime(16098): 	at org.thoughtcrime.securesms.registration.VerifyAccountRepository.$r8$lambda$uSHrz4OYwDRwa1aThP55yTPXJEQ(VerifyAccountRepository.kt)
E/AndroidRuntime(16098): 	at org.thoughtcrime.securesms.registration.VerifyAccountRepository$$ExternalSyntheticLambda2.call(R8$$SyntheticClass)
E/AndroidRuntime(16098): 	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
E/AndroidRuntime(16098): 	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
E/AndroidRuntime(16098): 	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
E/AndroidRuntime(16098): 	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
E/AndroidRuntime(16098): 	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:25)
E/AndroidRuntime(16098): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime(16098): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime(16098): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime(16098): 	at java.lang.Thread.run(Thread.java:841)
E/AndroidRuntime(16098): 	at [[ ↑↑ Original Trace ↑↑ ]].(:0)
E/AndroidRuntime(16098): 	at [[ ↓↓ Exception Message ↓↓ ]].(:0)
E/AndroidRuntime(16098): 	at dlopen failed: cannot locate symbol "__read_chk" referenced by "libsignal_jni.so"....(:0)
W/ActivityManager(  691):   Force finishing activity org.thoughtcrime.securesms/.registration.RegistrationNavigationActivity
```

If I'm connected to the Internet it crashes as soon as I start it, whereas if I'm not connected I'm able to get past the welcome screen, enter and confirm my phone number, and confirm that my device is missing Google Play Services, and then it crashes. The trace above is from when I wasn't connected to the Internet.

It looks like a compatibility issue. Did Signal recently drop support for Android 4.4?

## Device info

Device: Samsung Galaxy Avant
Android version: Android 4.4.4 custom build
Signal version: 5.46.6

**Comment by stiltr** [comment] 2022-08-22 18:52
I'm seeing this as well after updating to 5.46.6 on Android 4.4.2. I'm able to open app in airplane mode, but as soon as I disable that, the app crashes.
Probably the same issue as #12407.

**Comment by greyson-signal** [comment] 2022-08-22 19:33
Closing as duplicate of #12407

**Closed by greyson-signal** 2022-08-22 19:33 UTC
