### ISSUE TITLE
If users are online it should show online like others app

### ISSUE THREAD

**Issue by nikuraj006** [signalapp/Signal-Android#10652] opened 2021-01-15 10:35 UTC
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by ninjan3rd** [comment] 2021-01-15 10:57
I believe this is not a bug..Feature requests should raise here..
https://community.signalusers.org/

**Comment by Frivolous2** [comment] 2021-01-15 11:01
You can upvote the following feature requests, using your existing GitHub account by pressing the Log In button at the top right:
https://community.signalusers.org/t/the-ability-to-set-an-away-status-message/5237
https://community.signalusers.org/t/ability-to-see-if-people-are-online/5218
https://community.signalusers.org/t/last-seen-indicator/4375

**Comment by oxygi** [comment] 2021-01-15 11:34
@nikuraj006 Please close this "Issue" because it is not a bug.

**Comment by ra0e** [comment] 2021-01-15 19:24
I think this is not what Signal will include it, since you need and can track users this way by wrapping the client. Not a good idea

**Comment by mehtaRohit** [comment] 2021-01-17 06:09
As @ra0e said it's not a good idea. 
And I personally don't like that too.

**Closed** 2021-01-17 09:36 UTC
