### ISSUE TITLE
[feature request] supporting several phone numbers for the same account

### ISSUE THREAD

**Issue by mazieres** [signalapp/Signal-Android#5590] opened 2016-07-31 17:26 UTC
I've just moved to a new country and got a new phone number (A), while keeping the old one active (B). I had to make all these changes for phone number-based app including Signal.  By doing so, I've lost the opportunity that someone having B and being new to Signal recognize me as a user since my registered number is now A.

So while changing my number in signal doesn't make me lose former Signal users, it make me lose part of future ones.

Among all phone-based apps I've installed (telegram, whatsapp, signal, messenger) it seems that messenger is the only to allow to register 2 cell phones (through facebook website interface though).

It would be nice to add this feature to Signal.

**Comment by Trolldemorted** [comment] 2016-08-09 06:53
duplicate of #5102 (?)

if you are not afraid of compiling and potentially messing around yourself, you might want to try [this](https://github.com/Trolldemorted/Signal-Android/tree/multidevice).

**Comment by automated-signal** [comment] 2018-04-03 00:14
GitHub Issue Cleanup:
See #7598 for more information.

**Closed** 2018-04-03 00:14 UTC
