### ISSUE TITLE
youtube preview does not work

### ISSUE THREAD

**Issue by sandoxy** [signalapp/Signal-Android#9305] opened 2019-12-27 16:45 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by sandoxy** [comment] 2019-12-27 16:48
When sending a youtube-link the preview function works neither on Android nor on desktop.

**Comment by Genis-Sage** [comment] 2019-12-27 17:34
i can confirm this

when I paste a link, a frame with a loading circle pops up for around a second
and then vanishes again

when I paste a reddit link, the frame pops up and after some loading the preview is shown

**Comment by Genis-Sage** [comment] 2019-12-31 18:21
Duplicate of #9086

just found out, that this problem was already reported,
and that this is a server-side problem

**Closed** 2020-01-02 00:45 UTC
