### ISSUE TITLE
Set Profile picture with "Set as"/"Use picture as" Button

### ISSUE THREAD

**Issue by SB97** [signalapp/Signal-Android#10360] opened 2021-01-07 18:00 UTC
The Messenger with the Green Chat Bubble uses the "Set picture as" Button (which is normally used to set a picture as an wallpaper) as a way to directly set a Profile Picture.

Implementing this feature in Signal would improve the user experience. 

This is an Example of this Button in the Oneplus Gallery App:
![Galarie](https://user-images.githubusercontent.com/20126520/103927119-25328700-511a-11eb-8dd2-84798b3bb070.jpg)

This is an Example of this Button in the Nextcloud App:
![Nextlcoud](https://user-images.githubusercontent.com/20126520/103927174-37142a00-511a-11eb-97b6-ac12b8a3d764.jpg)

This is the menu that comes up:
![WhatsApp](https://user-images.githubusercontent.com/20126520/103927200-42675580-511a-11eb-8363-5f589840bf59.jpg)

**Comment by Nisc3d** [comment] 2021-01-07 20:03
Hi @SB97,
Please note that this issue tracker is [only meant for bug reports](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md#issues). Bug reports should only be submitted for existing functionality that does not work as intended. This is not the right place for questions, comments, or feature requests, as stated in the project's [CONTRIBUTING.md](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md) and [issue template](https://raw.githubusercontent.com/signalapp/Signal-Android/master/.github/ISSUE_TEMPLATE.md). I suggest moving this discussion over to the [community forum](https://community.signalusers.org/). Thanks!

**Closed** 2022-02-03 13:26 UTC
Labels: wontfix
