### ISSUE TITLE
Signal does not display SMS delivery reports on Android 11

### ISSUE THREAD

**Issue by jliebers** [signalapp/Signal-Android#11807] opened 2021-12-03 10:00 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
On my Fairphone 4 5G I use Signal to send and receive SMS. 
Signal is set as Android's default messaging app.
In the Signal settings I have enabled the option to receive SMS delivery reports, yet the delivery reports are not shown in Signal.
There only appears a single tick indicator that shows that the message has been sent; but the second tick that the message was received is missing.
This issue appeared just recently as I switched from an old Sony phone (Android 9 or 10) to the Fairphone 4 with Android 11.

The app `Google Messages` works just fine in this regards and correctly displays the delivery reports.

### Steps to reproduce
- Open Signal on a Fairphone 4 5G
- Enable the option to receive delivery reports in "Settings" > "Conversations" > "SMS & MMS" > "SMS Delivery Reports" (actual naming might be a little bit off since I use a localized version of Signal)
- Send an SMS to a contact (force that the message is sent as an SMS by a long press on the send button)

**Actual result:** No SMS delivery report is shown in Signal, i.e., only a single tick mark appears below the mssage. No indication is given when viewing the details of the message as well.

**Expected result:** Two tickmarks should be shown to indicate that the delivery report was received, as well as an entry in the message details.

### Screenshots
![Signal Conversation](https://user-images.githubusercontent.com/24356915/144583077-63a84271-871c-4f68-bfb1-69f841a3940e.jpeg)
(No double-tick indicators are displayed as like no SMS delivery report has been received.)

![Signal Details](https://user-images.githubusercontent.com/24356915/144583131-ae65f9f5-1c34-43f8-a4e0-4d04b1ce8e31.jpeg)
(Details view of such an SMS message.)

![Signal Settings](https://user-images.githubusercontent.com/24356915/144583160-cb425f2e-04b3-4b11-bc68-a1ca2b227eaa.jpeg)
(Settings view)

![Google Messages](https://user-images.githubusercontent.com/24356915/144583229-47fda488-c311-414d-8938-149eb394cd1d.jpeg)
(Google Messages works just fine.)

### Device info
Fairphone 4. For more details please see the error log.

### Link to debug log
I have sent the message precisely at `2021-12-03 10:35:51.172 GMT+01:00` (line 23127)
https://debuglogs.org/1eb5b90aceca79683ed2e02d7a07708fb1feabbff07d28b089cb248bd1079eaa

**Comment by raph2705** [comment] 2021-12-03 17:47
Same issue, noticed on a Huawei P30 and a Samsung S21, with two different mobile operators, I also enabled SMS/MMS receipts on Android and on Signal. And I can confirm that SMS/MMS delivery receipts are indeed received using another application (hence no network or provider issue). It did work as expected before, so it's obviously some kind of regression. The problem is present on standard build and beta build for some time now, and it's also mentioned in issue https://github.com/signalapp/Signal-Android/issues/11444

**Comment by bme13** [comment] 2021-12-03 20:47
Hi @jliebers and welcome. This seems a duplicate of #11444.

**Comment by raph2705** [comment] 2021-12-19 23:30
I'm not a Signal dev, nor am I familiar with the project but I find a bit odd to have a member variable and a method share the exact same name, In file ```app/src/main/java/org/thoughtcrime/securesms/components/settings/app/chats/sms/SmsSettingsViewModel.kt``` at line 24, we have
```kotlin
SignalStore.settings().isSmsDeliveryReportsEnabled = enabled
```
While in file ```app/src/main/java/org/thoughtcrime/securesms/util/TextSecurePreferences.java``` at line 844, we have
```java
public static boolean isSmsDeliveryReportsEnabled(Context context) {
```
As they both belong to different classes/namespaces, compilation will be OK but such situations should be avoided. Apart from that, I do not see anything obvious that could explain the issue at hand. I'd need to setup a build env to better understand what happens here. Needless to say, an experienced Signal dev could pinpoint the bug way faster...

We have some more relevant code, pertaining to SMS delivery reports, in files ```app/src/main/java/org/thoughtcrime/securesms/jobs/SmsSentJob.java```, ```app/src/main/java/org/thoughtcrime/securesms/service/SmsDeliveryListener.java```, and ```app/src/main/java/org/thoughtcrime/securesms/keyvalue/SettingsValues.java```. And I'm also a bit confused on the difference between **DELIVERED_SMS_ACTION**, referenced in ```app/src/main/java/org/thoughtcrime/securesms/jobs/SmsSentJob.java``` and ```app/src/main/java/org/thoughtcrime/securesms/service/SmsDeliveryListener.java```, and **SMS_DELIVERED_ACTION**, referenced in ```app/src/main/java/org/thoughtcrime/securesms/service/SmsListener.java```.

**Comment by gongoscho** [comment] 2022-02-11 10:06
Same on Pocophone F1 with: lineage-18.1-20220205-nightly-beryllium-signed without Google Apps or microG

**Comment by FreaxMATE** [comment] 2022-03-19 00:34
Same for me after updating /e/ from Android 10 to Android 11 base. MicroG is installed.

**Comment by rkw95** [comment] 2022-03-21 20:10
Same here on Samsung S10+ with Android 11. On my old phone it worked properly. See my diagnostic report: https://debuglogs.org/android/5.32.15/95a2f158f6e765b29aaf2aa49a2b50baa9e9d5035635f7b6197857b80bb80e14

**Comment by Sgn-32** [comment] 2022-05-04 19:51
`Fix SMS delivery reports` in 5.37.0

https://github.com/signalapp/Signal-Android/commit/0d9a5ef9a669f4437d370496773d39616106960f

**Comment by FreaxMATE** [comment] 2022-05-04 19:57
@Sgn-32 Nice!

**Comment by jliebers** [comment] 2022-05-04 20:04
Amazing, thank you so much!

**Comment by pboesch** [comment] 2022-05-13 16:13
Thank you! Everything is working fine now!

**Comment by PluckyUnderdog** [comment] 2022-05-13 16:40
Amazing.  Thank you @Sgn-32.  SMS Delivery receipts are working again for me on 5.37.4 
It will allow me to ditch the stock messages app and go back to using signal for almost all messaging instead of hopping back and forth between signal and messages depending on the recipient.

Great job.

LG V50 (LG LM-V500EM) Android 11

**Comment by gongoscho** [comment] 2022-05-14 20:18
With Pocophone F1 and 5.37.4 on LineageOS 18.1 or on wifes Pocophone F1 LineageOS 17.1 not working 😕

**Comment by Sgn-32** [comment] 2022-05-15 13:29
@gongoscho 

Are the SMS delivery reports working with another SMS app on that phones?
Try to switch the "SMS delivery reports" off and on again in Signal SMS and MMS settings.
Please post a debug log directly after sending some SMS with Signal.

**Comment by jliebers** [comment] 2022-05-15 13:54
I just want to confirm that the functionality works for me on a Fairphone 4 5G. Thank you for the fix.

**Comment by UserX404** [comment] 2022-05-15 19:30
@jliebers 
Pls consider closing this issue.

**Closed** 2022-05-15 19:40 UTC

**Comment by gongoscho** [comment] 2022-05-19 11:57
> @gongoscho
> 
> Are the SMS delivery reports working with another SMS app on that phones? Try to switch the "SMS delivery reports" off and on again in Signal SMS and MMS settings. Please post a debug log directly after sending some SMS with Signal.

I Check this.

**Comment by gongoscho** [comment] 2022-05-25 17:35
@Sgn-32 [debug log](https://debuglogs.org/android/5.38.5/b74dc1fc8dd76bb7749bb6ee0815e9ed6ec629314bee92ff03f35a5fab4fc973)
