### ISSUE TITLE
Devs removing critical feature

### ISSUE THREAD

**Issue by bovineblitzkrieg** [signalapp/Signal-Android#12558] opened 2022-10-28 14:36 UTC
### Bug description
Devs are removing SMS support so the dozen plus people I've converted to using their app are going to be unable to keep using it.  It will become an app only for advanced users.

### Steps to reproduce
Exist in October 2022.

**Actual result:** Signal going to lose SMS abilities
**Expected result:** Users leave

### Device info
**Device:** Motorola One 5G UW
**Android version:** 011
**Signal version:** 5.53.8

### Link to debug log
Why u do dis

**Comment by mentalisttraceur** [comment] 2022-10-28 16:30
Funny story, for years now the main way I discover that people have Signal is I go to send them an SMS and I see that Signal auto-detects the number as registered with Signal. If Signal isn't my SMS app, if it's a separate messaging portal, then my secure messaging usage goes down.

It was also really nice to have my SMS saved encrypted on-device, without the overhead of yet another separate app.

Is the problem that you have vision for how to do secure messaging - the UI and so forth - that just can't fit insecure SMS inline? (Google and Apple manage to have a messaging app that gracefully degrades from their custom messaging to standard SMS, but maybe y'all got different vision or rationale or goals?)

I also get that manpower is probably low, and the SMS aspects are probably a particularly fiddly complication.

**Comment by burrm** [comment] 2022-10-28 20:51
see also, https://github.com/signalapp/Signal-Android/issues/12560

**Comment by kienner-philippe** [comment] 2022-10-29 10:37
With this feature removal the integration in contacts in android will also become worse. As mentalisttraceur said, how can I identify my contacts on Signal now?
Threema or Telegram warn me, not Signal.

**Comment by grandchild** [comment] 2022-10-29 10:56
@mentalisttraceur @kienner-philippe

Settings > Notifications > Notify when... > Contact joins Signal

**Comment by mentalisttraceur** [comment] 2022-10-29 15:23
@grandchild I don't save contacts, I just remember people's numbers, at least enough to recognize them when I scroll through my message or call history.

But even if I saved contacts, out-of-band notifications that happen at times when it's entirely irrelevant because I wasn't about to message that person is not the same mental and workflow hook.

*And* it still turns what can be an entirely computer-automatable decision (send by Signal or SMS, based on what's possible and my last configured preference) into something I have to manually do every time (unless I write an SMS app that can be configured to bounce me to the Signal conversation... assuming Signal exposes the right Intents for that, or whatever Android calls them nowadays).

**Comment by 0xquad** [comment] 2022-10-29 15:40
As beautifully stated in #12560, this is a terrible decision for the application and will effectively reduce the general adoption of secure messaging throughout the user base rather than increasing it. Interoperability with bare SMS is needed in order to retain the user base.

I myself work in information and computer security and value security more than the average person, but if Signal is removing this critical feature I will be forced to revert back to the built-in SMS app on my mobile, after more than 10 years using Signal as the default SMS app.

Frankly, I'm struggling to understand the rationale behind the decision, even after reading the reasons on Signal's blog. Please don't do this, for the sake of security and usability.

**Comment by bovineblitzkrieg** [comment] 2022-10-29 18:56
That was fast.  My SMS is disabled as of today.  I have been questioned about this from two people already, and I hesitate to direct them to an alternative now as it was hard enough convincing them to use Signal in the first place.  Maybe Google Messages, as much as Google sucks.

Mass uninstallation incoming.

**Comment by Cubly** [comment] 2022-10-30 00:27
I dont know what they are doing, they keep changing all the good features for what?

Just gonna be a mass exodus, they are completely out of touch with their user base.

**Comment by johnlane** [comment] 2022-10-30 20:12
Another request to retain SMS _please_. I would have never been able to get quite a few people to install and use Signal daily if it were not for the integrated SMS support. Those people will end up removing Signal if it won't send SMS - they want one app to send messages with and it must support SMS. Removal of SMS will be a serious disappointment and a farewell by many. Please... listen to your users or you will lose lots of them.

You could, perhaps, consider instead removing other brain-dead "enhancements " such as stickers, etc, or is your targeted audience the local pre-school...

**Comment by bovineblitzkrieg** [comment] 2022-10-30 20:59
> @mentalisttraceur @kienner-philippe
> 
> Settings > Notifications > Notify when... > Contact joins Signal

I like how SMS is too insecure and prone to user error, but the app announces your presence to literally everyone you know when you join up.  Oh also, "stories".

I guess I'm confused as to where the app is going in general.  The hardline security/privacy argument driving the removal of SMS is in contrast to the above.  Is it a social media platform, an insular messaging platform, or an SMS substitute?

**Comment by notnoxii** [comment] 2022-10-30 21:37
I personally know 6 people who have already removed signal because they don't want multiple messaging apps. Please undo this

**Comment by mistahBen** [comment] 2022-10-30 21:38
I want to chime in and try to emphasize the important negative outcome: users *will* leave Signal. And perhaps even worse, new users won't even consider it. The hurdle of "You can only message other Signal users" is going to be far too high. I genuinely do not know a casual user that I could convince to start using Signal if they could only ever use it to message other Signal users.

Signal got where it is based on word of mouth and ease of use. I could tell folks, "I use Signal and the messages it sends are more secure if both users are on Signal AND it can still send text messages to non-Signal users." *That* is a pitch that works.

**Comment by bovineblitzkrieg** [comment] 2022-10-30 21:43
> The hurdle of "You can only message other Signal users" is going to be far too high. I genuinely do not know a casual user that I could convince to start using Signal if they could only ever use it to message other Signal users.

Have you considered telling new users about the upcoming Instagram/Snapchat/Facebook/WhatsApp-like "stories" feature that will allow them to share their lives with other Signal users?

**Comment by notnoxii** [comment] 2022-10-31 00:05
> 

Considering I don't any of those, and the people who generally use those apps aren't privacy focused, no that will not be something I can suggest to people who don't want companies evesdropping

**Comment by ooterness** [comment] 2022-10-31 05:10
I cannot understand why Signal is making such a huge mistake. The whole reason I'm able to convince friends and family to use Signal is that it's a painless, completely drop-in replacement for SMS. i.e., If you have someone's phone number, you can contact them, full stop. If they also have Signal, it's encrypted. This is the must-have feature that elevates Signal above every other alternative. I cannot emphasize enough how critical this is in both conversion and retention.

**Comment by TheZestySquid** [comment] 2022-11-01 13:08
I truly don't understand the rational here... As an IT professional I understand the desire or want for encrypted messages, across the platform, but the simple fact of the matter is many services do not support it. And you will be losing most of your userbase. Only a fraction of my friends/family use signal to signal encrypted messages (msny use sms), not to mention the can of worms that is MFA, bank notifications or messages from other institutions. This is NOT a good decision signal revert it... Why is the current trend to remove good features?

**Comment by mufunyo** [comment] 2022-11-02 18:09
> Have you considered telling new users about the upcoming Instagram/Snapchat/Facebook/WhatsApp-like "stories" feature that will allow them to share their lives with other Signal users?

This is a joke, right? Literally nobody asked for stories. I have WhatsApp (which has stories), and the only stories I ever receive are product updates from WhatsApp itself. Because nobody wants, needs, or uses stories.

Is Signal out of touch? No, it's the users who are wrong.

**Comment by lanz** [comment] 2022-11-04 19:39
In other bad news, Signal's lawyers sent a DMCA order to Canonical to remove the Signal Desktop Linux snap package from snapcraft. Signal Desktop is AGPL and Canonical has every right to distribute it as a snap.

https://news.ycombinator.com/item?id=33450806

It seems Signal is racking up quite the list of awful decisions and hostile user actions:

1. Not publishing a years worth of commits, and when they finally do it includes the cryptocurrency MobileCoin.
2. Removing the much loved color feature that allowed users to assign colors to contacts.
3. Removing SMS integration, which is the main reason most Android users were attracted to Signal.
4. Hostile DMCA take downs for Signal Desktop snap packages.

I've been a Signal user for ~5 years, and I'm sad to see that Signal is heading down this awful path of self-destruction.

**Comment by bovineblitzkrieg** [comment] 2022-11-07 01:49
> > Have you considered telling new users about the upcoming Instagram/Snapchat/Facebook/WhatsApp-like "stories" feature that will allow them to share their lives with other Signal users?
> 
> This is a joke, right? Literally nobody asked for stories. I have WhatsApp (which has stories), and the only stories I ever receive are product updates from WhatsApp itself. Because nobody wants, needs, or uses stories.
> 
> Is Signal out of touch? No, it's the users who are wrong.

Yes of course.  It's classic mission creep.  Simple successful messaging app --> features competing with instagram for some reason, strange crypto scam, and removal of accessibility in favor of zealotry for perfection.

Or, it could be sabotage.

**Comment by ungutknut** [comment] 2022-11-08 12:19
Wait... what?! Without SMS, Signal will be absolutely useless on my phone. Only a tiny fraction of my contacts uses signal messages. And they will become even less when SMS is going to be dropped. Will there be a fork?

**Comment by greyson-signal** [comment] 2022-11-08 14:26
Closing as a duplicate of #12517. You can read [my comment](https://github.com/signalapp/Signal-Android/issues/12517#issuecomment-1277965716) there for more details.

**Closed by greyson-signal** 2022-11-08 14:26 UTC
