### ISSUE TITLE
"Update Available", despite being on the latest version (APK install)

### ISSUE THREAD

**Issue by ClayShoaf** [signalapp/Signal-Android#13273] opened 2023-11-20 23:19 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I'm running 6.40.5 and I keep getting a notification that an update is available, but when I tap on the notification, it just disappears. The same thing is happening to people I know and [others](https://www.reddit.com/r/signal/comments/17xlvm5/update_available_even_though_im_on_latest_version/)

### Steps to reproduce
- Have the APK version installed
- wait a few hours
- tap the update notification

**Actual result:** Nothing is installed. The notification just disappears, only to return again some time later
**Expected result:** An update should be installed, or there should be no notification.

### Screenshots
Unfortunately, I tapped it before I could take a screenshot, but it is the standard notification, so I don't know how much good that would do. I didn't see a version number or anything.

### Device info

**Device:** Multiple Android devices, some running stock android, some running GrapheneOS
**Android version:** 13+
**Signal version:** 6.40.5

### Link to debug log
Part of the reason I am using Signal is to avoid stuff like this being posted publicly online. Sorry. I'm sure this is happening to plenty of people, perhaps one of them could post it.

**Comment by ziguana** [comment] 2023-11-20 23:23
In my case, the notification doesn't even disappear. I think it freezes for a moment. GrapheneOS (Android 13) on Pixel 4a, Signal 6.40.4.

**Comment by bughunter2** [comment] 2023-11-21 08:37
I'm experiencing the same problem. Same symptoms. I'm using LineageOS with microG.

Observations:

When I delete the update file from Android/data/org.thoughtcrime.securesms/files/signal-update.apk, it's downloaded again around 00:09 AM and asks me to install the update the next day.

When I install the update, the update re-appears the next day or even the same day.

I'm already on the latest version. The version shown by Signal is the same version, even after installing the update, namely 6.40.5

**Comment by greyson-signal** [comment] 2023-11-21 15:10
Hi there, I'll need a log from someone :)

**Comment by Starcommander** [comment] 2023-11-21 23:47
I have the same issue.
Sometimes after clicking the notification there is a message like "Successfully updated", but nothing installed.
Issue was at 0:36 today.
And sometimes when I click the notification, nothing happens.
(not included in log)
[logcat4000.log](https://github.com/signalapp/Signal-Android/files/13432034/logcat4000.log)

**Comment by woheller69** [comment] 2023-11-22 17:15
Here is a log. I am always getting notifications. If I go to Android/data/.../files and try to install the apk it tells me that it has the same version code as the installed version.

https://debuglogs.org/android/6.40.5/3425faddc07ec09e7e9ba67177851cbfd9c56bfd89fc1506c72a1faf6256e2f7

**Comment by Dispatch3376** [comment] 2023-11-22 22:55
I have the same issue.

**Comment by syphyr** [comment] 2023-11-23 00:02
This issue would not be so intrusive if signal asked first before attempting to download the updates.

**Comment by syphyr** [comment] 2023-11-23 17:18
One thing I just noticed is that the false `update available ` notification disappears as soon as an actually signal message from new activity from a conversion occurs. That never happened before.

**Comment by romeojulietthotel** [comment] 2023-11-23 19:18
May be due to bug in your build script or compromised infrastructure? The UploadTimestamp is incorrect and most likely the cause of the symptoms from the bug/compromise/cut-n-paste programming or somethin....

- `versionCode	136105
- versionName	"6.40.5"
- sha256sum	"cc92693c3129cbbe50df2edeaa6c2aaacdbc29ecec3dffb86cd6ee5b11780807"
- url	"https://updates.signal.org/android/Signal-Android-website-prod-universal-release-6.40.5.apk"
- uploadTimestamp	1700249829657`

....very annoying issue.
....thread at the forums about this too.....
[https://community.signalusers.org/t/update-every-couple-hours/57187](url)

**Comment by sndwichm4n** [comment] 2023-11-25 09:37
@greyson-signal  @nicholas-signal  Is the bug being worked on? No response from the developers?

It looks like a showstopper to me, I have Signal installed on both my grandparents' smartphones. This endless updating is not practical. I will be looking for an alternative soon and will stop the financial donation every year.

**Comment by Starcommander** [comment] 2023-11-25 12:35
In my case the update notification did not appear again since 4 days.
No Idea why.
The only things that I did in the past:
Connecting via USB to computer, multiple reboots, and selecting the notification sometimes.
When it occurs again, i will try to provide a logcat-output again.

**Comment by micredd** [comment] 2023-11-25 20:41
While we wait on an ultimate resolution from the Signal devs, for those who are frustrated by these notifications, don't forget that Android lets you silence and hide notifications you don't want to see.

Long-press the app's update notification, touch the "gear" icon to open the app's notification settings, and toggle off the one for "App updates". Then just occasionally check Signal's "Android APK" page for version updates. Less convenient than having the app check for you, sure, but also less irritating in the interim. :)

**Comment by gothmog123** [comment] 2023-11-26 07:57
sorry devs, I know we are getting signal for free but can we at least get an ETA on when this will be fixed?

**Comment by syphyr** [comment] 2023-11-30 17:43
Maybe Signal should just remove the broken internal updater and post releases on F-Droid.

**Comment by woheller69** [comment] 2023-11-30 17:45
F-Droid would be great :-)
I removed the notification for app updates. Works perfect...

**Comment by syphyr** [comment] 2023-11-30 17:50
The problem with removing the notification for updates is that the app still keeps downloading the same ~100MB update every day.

**Comment by woheller69** [comment] 2023-11-30 18:05
for me last download is from Nov 27, when I disabled the notification...

**Comment by syphyr** [comment] 2023-11-30 19:12
For me, the modification date of the update changes every night around 11pm.

**Comment by MartinGebert** [comment] 2023-12-02 17:10
This is a permanent nuisance. I don't even have a choice to disable update notifications separately; I either terminate Signal, disable all notifictions, or live with it. I did the latter over serveral **months** now, and the frequency got worse; this is a real showstopper for using Signal!

**Comment by greyson-signal** [comment] 2023-12-04 15:38
Hey folks, sorry, as noted in #13261, I thought I had resolved this. Still seems like it's happening for people. I really need logs to be able to debug this, so I'd really appreciate someone posting a log  link.

My understanding is that for some reason clients aren't saving the last uploadTimestamp of the build they installed, and that this was getting resolved when they finally updated to the newest version, but sounds like there is still an issue. But I won't know what is is without a log :)

FWIW I actually have a nightly flavor with this same update mechanism installed on my personal phone that updates every day, so I _am_ using this to try to find bugs -- I'm just not hitting the same issue ya'll are hitting.

**Comment by jason-eu** [comment] 2023-12-04 16:52
> Hey folks, sorry, as noted in #13261, I thought I had resolved this. Still seems like it's happening for people. I really need logs to be able to debug this, so I'd really appreciate someone posting a log link.
> 
> My understanding is that for some reason clients aren't saving the last uploadTimestamp of the build they installed, and that this was getting resolved when they finally updated to the newest version, but sounds like there is still an issue. But I won't know what is is without a log :)
> 
> FWIW I actually have a nightly flavor with this same update mechanism installed on my personal phone that updates every day, so I _am_ using this to try to find bugs -- I'm just not hitting the same issue ya'll are hitting.

https://github.com/signalapp/Signal-Android/issues/13273#issuecomment-1823178001

**Comment by MartinGebert** [comment] 2023-12-04 18:13
@greyson-signal Does this help with notifications disabled?
[signal-log-1701713393059.zip](https://github.com/signalapp/Signal-Android/files/13549855/signal-log-1701713393059.zip)

**Comment by greyson-signal** [comment] 2023-12-04 19:13
@MartinGebert thank you, it looks like your device doesn't have a lastUploadTimestamp, which is what I had seen previously. I'm fairly confident this will go away when you do the next real update through the app. I have other fixes planned for 6.42.

**Comment by cherti** [comment] 2023-12-09 03:09
I can confirm that it seems to have fixed itself with the latest update here. So everyone who disabled that notification can now re-enable it and see if that's the case for you as well.

**Comment by syphyr** [comment] 2023-12-09 10:38
The latest update 41.3 seems to have fixed the problem

**Closed** 2023-12-11 16:41 UTC

**Comment by kimimaru4000** [comment] 2024-01-13 18:36
I am on version 6.42.3 and the auto-updater is still not working for me. I've heard of deleting the "update APK", which I presume is the APK downloaded by auto-updater. However, I can't find that anywhere - where can I find that and is anyone else still experiencing this problem?

**Comment by MartinGebert** [comment] 2024-01-13 19:15
@kimimaru4000 6.42.3 is working fine for me. Last week I seem to have on of those "empty" updates again, but the latest one two days ago worked fine. On my system the update file is `/storage/emulated/0/Android/data/org.thoughtcrime.securesms/files/signal-update.apk`; I'm using Ghost Commander to access it.

Anyhow I would be happier with updating it via F-Droid, too, which would leave me more control about the time when to perform it.
