### ISSUE TITLE
Call does not get through

### ISSUE THREAD

**Issue by hxy0097** [signalapp/Signal-Android#11058] opened 2021-03-05 03:06 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Calling out from my phone does not get through - right after initiated a call, receiver shows missed call.

### Steps to reproduce
- Prepare phone A **without camera**
- Make phone A call phone B in Signal

**Actual result:** Observe that phone B didn't ring and received a missed call, phone A showed "Recipient unavailable"  and hang up or keep calling.
**Expected result:** Phone B can receive a call to get through.

### Device info
**Phone A**
**Device:**  *(without camera)*
**Android version:** 8
**Signal version:** 5.2.3
**Phone B**
**Device:** Xiaomi
**Android version:** 11
**Signal version:** 5.4.7

### Link to debug log
https://debuglogs.org/ec3ae09654858526c36d15b6524de422aefa2bcefd1d145a9c39cb61c86e84c8

**Comment by Hiro-Okuyama** [comment] 2021-03-10 14:39
To see if the issue persists on the latest version, I have created an emulator without camera, run Signal 5.4.12 built on Android Studio without any mod from git-hub. Call from this emulator also does not get through.

Log below is captured on the device receiving the call (not the emulator).
https://debuglogs.org/73cbff75e30d52254876157a913c5eecb3b354ecf1b617e269d8dbdb970ce989

Does the line in bold show that if the caller has no video feature, the call is terminated?
=====
2021-03-09 17:50:07.715 22602-28455/org.thoughtcrime.securesms E/ringrtc::core::call: Proceed Future failed: SetSessionDescriptionObserver get result failure. error msg: SetSessionDescriptionObserver failure. error msg: Failed to set remote offer sdp: Failed to set remote video description send parameters for m-section with mid='video'., type: 3
2021-03-09 17:50:07.715 22602-28455/org.thoughtcrime.securesms I/ringrtc::core::call: received_ice(): id: 0x1a6062e3b03ae34b-1
2021-03-09 17:50:07.715 22602-28455/org.thoughtcrime.securesms E/ringrtc::core::call: Handle Received Ice Future failed: Connection not found in connection_map: 1
2021-03-09 17:50:07.715 22602-28454/org.thoughtcrime.securesms I/ringrtc::core::call_fsm: state: ConnectingBeforeAccepted, event: (InternalError: SetSessionDescriptionObserver get result failure. error msg: SetSessionDescriptionObserver failure. error msg: Failed to set remote offer sdp: Failed to set remote video description send parameters for m-section with mid='video'., type: 3)
2021-03-09 17:50:07.715 22602-28454/org.thoughtcrime.securesms I/ringrtc::core::call_fsm: handle_internal_error():
2021-03-09 17:50:07.715 22602-28454/org.thoughtcrime.securesms I/ringrtc::core::call_fsm: state: ConnectingBeforeAccepted, event: (InternalError: Connection not found in connection_map: 1)
**2021-03-09 17:50:07.715 22602-28455/org.thoughtcrime.securesms I/ringrtc::core::call_manager: internal_error(): call_id: 0x1a6062e3b03ae34b, error: SetSessionDescriptionObserver get result failure. error msg: SetSessionDescriptionObserver failure. error msg: Failed to set remote offer sdp: Failed to set remote video description send parameters for m-section with mid='video'., type: 3**
2021-03-09 17:50:07.715 22602-28454/org.thoughtcrime.securesms I/ringrtc::core::call_fsm: handle_internal_error():
2021-03-09 17:50:07.715 22602-28455/org.thoughtcrime.securesms I/ringrtc::core::call_manager: terminate_active_call():
2021-03-09 17:50:07.715 22602-28455/org.thoughtcrime.securesms I/ringrtc::core::call_manager: conclude_call(): call_id: 0x1a6062e3b03ae34b
2021-03-09 17:50:07.715 22602-28455/org.thoughtcrime.securesms I/ringrtc::core::call_manager: ringrtc!	1615308607715	cm -> app: event(EndedInternalFailure)
2021-03-09 17:50:07.715 22602-28455/org.thoughtcrime.securesms I/ringrtc::android::android_platform: on_event(): EndedInternalFailure
2021-03-09 17:50:07.716 22602-28455/org.thoughtcrime.securesms I/CallManager: onEvent():
2021-03-09 17:50:07.716 22602-28455/org.thoughtcrime.securesms I/WebRtcCallService: onCallEvent(): call_id: 0x1a6062e3b03ae34b, state: ANSWERING, event: ENDED_INTERNAL_FAILURE
2021-03-09 17:50:07.717 22602-22602/org.thoughtcrime.securesms I/WebRtcCallService: onStartCommand... action: ENDED_INTERNAL_FAILURE
2021-03-09 17:50:07.717 22602-28455/org.thoughtcrime.securesms I/ringrtc::core::call_manager: internal_error(): call_id: 0x1a6062e3b03ae34b, error: Connection not found in connection_map: 1
2021-03-09 17:50:07.718 22602-28355/org.thoughtcrime.securesms I/ringrtc::core::call_manager: send_hangup(): call_id: 0x1a6062e3b03ae34b
2021-03-09 17:50:07.718 22602-28355/org.thoughtcrime.securesms I/ringrtc::core::call_manager: send_next_message():
2021-03-09 17:50:07.718 22602-28355/org.thoughtcrime.securesms I/ringrtc::core::call_manager: send_next_message(): sending message, len: 0
2021-03-09 17:50:07.718 22602-28355/org.thoughtcrime.securesms I/ringrtc::core::call_manager: ringrtc!	1615308607718	cm -> app: send_hangup(Normal)	0x1a6062e3b03ae34b
=====

**Comment by szotsaki** [comment] 2021-03-19 07:22
This is most probably a duplicate of https://github.com/signalapp/Signal-Android/issues/7733. May I ask to close this issue (to avoid having duplicates) and continue the conversation in the linked ticket?

**Comment by Hiro-Okuyama** [comment] 2021-03-19 09:15
> This is most probably a duplicate of #7733. May I ask to close this issue (to avoid having duplicates) and continue the conversation in the linked ticket?

No, this is not the duplicate of #7733, the issue only started from end of Feb or early March, and peculiar to the call initiated from no-camera device.

**Comment by eabase** [comment] 2021-05-19 17:50
I have the same issue, regardless of the camera. 

However, I see we are both on a Xiaomi. 
Mine is Mi 10T Lite, MIUI 12.0.1

Settings: 
* Always relay call: OFF
* Reade Recipients: ON 
* Everything else off

**Comment by Hiro-Okuyama** [comment] 2021-05-19 20:17
@eabase this issue is very specific to no-camera device.
Xiaomi device, in the report "Phone B", is not the cause of the problem.

However, it does seem every now and then the call does not reach, probably due to Signal server congestion?

**Comment by eabase** [comment] 2022-01-26 11:21
Kill that fukcing bot!

**Closed** 2022-04-10 05:58 UTC
Labels: wontfix
