### ISSUE TITLE
When losing the internet connection while downloading, image downloads never complete

### ISSUE THREAD

**Issue by xyzzyxw** [signalapp/Signal-Android#8132] opened 2018-08-22 18:51 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When losing the internet connection while downloading, image downloads never complete.
This problem also seems to exist with uploads.

### Steps to reproduce
- set image download to WLAN only (probably not necessary, but it's my setting)
- be connected to a WLAN
- start downloading an image
- lose connection to the WLAN

**Actual result:** 
- Download animation is displayed forever, never completes.

**Expected result:**
- Image should complete downloading eventually. Restart download if necessary.

**Comment by PiCob** [comment] 2018-08-22 19:36
At least related, maybe even exact the same:
#6004 (closed during spring cleanup)
#8027 (closed as dupe of another issue, which actually wasn't nearly the same IMHO)

Maybe the logs included there could be of some help. I for my part decided to only download media when on Wi-Fi, 'cause constantly asking people to resend pictures and videos because of this bug was just not way to go for me anymore.

**Comment by PiCob** [comment] 2018-09-02 21:07
Don't know, if that's related as well, but today I faced a strange behavior when batch downloading a bunch of pictures in a row (quickly). Although all images were downloaded and even showed the thumbnail/preview, two of them still had the "download" label layer and I could tap them again (which resulted in the arrow symbol vanishing, but the half-opaque border staying there). I captured two logs: one immediately after it happened and the second one right after re-entered the conversation hours later, finding that I still could download again.

If screenshots are needed, I'll provide some as well.

https://debuglogs.org/4e7941db4078197a076a3fd006b1e2f16959385bb4fa719792961a066b35285c

https://debuglogs.org/d2b32865e3ef11d7474e36c443d9533821699370e3f07c23577ff1744d01fa77

**Comment by klorydryk** [comment] 2018-09-13 13:16
same problem here: I'm waiting for 3 images right now in a conversation. Not sure it is a network problem (I'm connected with Wifi), and it is not the first time.
For information, the desktop application is able to get the pictures in my case, but it is lost for Android app.

**Closed** 2022-02-04 17:16 UTC
Labels: wontfix
