### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by MeDDevil01** [signalapp/Signal-Android#11855] opened 2021-12-21 07:06 UTC
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by supermar1010** [comment] 2021-12-21 10:34
Hello :)
Please fill out a few more things from the big report like the actual result and the expected result. Otherwise it's really hard to understand what the problem is. Also a meaningful title would be great

**Comment by greyson-signal** [comment] 2021-12-21 14:58
Closing due to lack of information. Feel free to open another report. Thanks!

**Closed by greyson-signal** 2021-12-21 14:58 UTC
