### ISSUE TITLE
Automatic resend of failed media messages

### ISSUE THREAD

**Issue by mkroehnert** [signalapp/Signal-Android#6899] opened 2017-08-27 09:23 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Everytime a media message fails to send (especcially in an area with bad celular), I get notifications for each message that it failed to send.
Afterwards I have to go to each message, tap on the red '!', and then hit resend.
In an area with bad celular coverage, I typically have to do this 5-10+ times for each! of the images I want to send.

This is one of the major reasons for some of my friends to not use Signal as their main messenger. They even discourage other people from using Signal because of this.

There is #3068, but the ticket has been closed without adressing the main issue.

### Steps to reproduce
- go to area with bad celular coverage (e.g. a festival)
- try to send picture(s) to Signal contacts

**Actual result:**
- fail in trying to send picture(s) to Signal contacts and get annoyed by having to manually resend each and every message

**Expected result:**
- follow the usability of Telegram and WhatsApp and automatically try resending the images up to a certain threshold time (say one day)
- retry time should not increase linearly

### Device info
**Device:** Moto G3
**Android version:** 6.0.1
**Signal version:** 4.8.1

**Comment by FeuRenard** [comment] 2017-08-28 13:30
Duplicate of #6087
Related: #2384

**Comment by mkroehnert** [comment] 2017-08-28 18:57
Sorry for the noise. I did not come across those issues while searching the tracker.

I would just like to stress the point that people turn away from Signal because the current behavior is not acceptable for them.

**Comment by donnm** [comment] 2017-09-14 11:23
+1 I have this problem all the time too, often when using an unreliable 3g router, or in areas with bad cellular service. Auto-resend would be a fantastic solution, like how WhatsApp works!

**Comment by ebkalderon** [comment] 2018-01-02 19:52
Been using Signal for years, and this is a big problem for me too. Since I travel often, this makes Signal pretty much unusable in many places I visit that have slow or spotty coverage.

For every image or GIF attachment I send, I always need to manually resend it 10+ times before it finally arrives. Because of this behavior, I have reluctantly relegated my use of Signal to just within the United States and use WhatsApp everywhere else.

I really hope the developers implement an auto-resend feature soon. If I had more free time, I would happily hack together a pull request myself.

**Comment by deed02392** [comment] 2018-02-28 14:09
@FeuRenard I think you got those links the wrong way around. The first one was related, the second one looks more like the duplicate.

**Comment by automated-signal** [comment] 2018-04-03 04:17
GitHub Issue Cleanup:
See #7598 for more information.

**Closed by automated-signal** 2018-04-03 04:17 UTC
