### ISSUE TITLE
Video call uses ear speaker and not main speaker

### ISSUE THREAD

**Issue by heretoenhance** [signalapp/Signal-Android#10744] opened 2021-01-20 09:42 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The sound from a videocall comes out of the tiny ear speaker (the one used during phone calls) and not the main speaker.

### Steps to reproduce
- Start a videocall
- (possibly: switch cameras)

**Actual result:** The sound comes out of the ear speaker
**Expected result:** The sound comes out of the main speaker

### Device info

**Device:** Honor 9 STF-L09
**Android version:** Android 9
**Signal version:** 5.1.9 Play Store Version (And again 5.2.3)

### Link to debug log
https://debuglogs.org/6a29434567e19c7390b12f00cc822472e6cc94c082de30f99d5dc1bf9091c390

**Comment by szotsaki** [comment] 2021-01-23 14:17
This is a duplicate of https://github.com/signalapp/Signal-Android/issues/9796. If you also think so, please close this report.

**Comment by heretoenhance** [comment] 2021-01-23 17:02
I believe "Speaker volume is low" and "video call uses ear speaker" are different. Were you looking at logs and found something similar or just guessed from the description? If you found out something in the logs I will close the issue as duplicate

**Closed** 2022-02-03 05:47 UTC
Labels: wontfix
