### ISSUE TITLE
Emoji, Attachment, and 'Android Back' buttons not working in conversation

### ISSUE THREAD

**Issue by RensOliemans** [signalapp/Signal-Android#10110] opened 2020-10-20 21:44 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When in a conversation (private, old group, new group), the emoji button (the one left to the message input box), the attachment button (blue plus) and the Android back button are not working.
The camera, microphone, text input and send buttons are all working. The three dots (settings) button and the 'back button' (<-) in the top-left corner also work.
When you are entering text (so the keyboard is extended) and press one of the faulty buttons, the keyboard closes.

### Steps to reproduce
- Open Signal
- Open a conversation
- Press back/emoji/attachment button

**Actual result:** Nothing happens (or keyboard closes, depending on the state)
**Expected result:** The emoji or attachment menu should open (when pressing those buttons), or I should go back to the main conversation list (when pressing the Android back button).

### Screenshots
Well nothing really happens

### Device info
**Device:** Nokia 6.1
**Android version:** 10 (unrooted)
**Signal version:** 4.74.1 (yes, debug)

### Link to debug log
https://debuglogs.org/b0e47c44a612f1b4ecab000134b1b07fe0caa38a407a8df9b620d0e086704863

**Comment by RensOliemans** [comment] 2020-10-20 21:48
From the debug logs I see a lot of `NoSuchFieldException`s when calling `Landroid/view/View`, but I also see the line `crime.securesm: Accessing hidden field Landroid/view/View;->mAttachInfo:Landroid/view/View$AttachInfo; (greylist-max-p, reflection, denied)` a couple of times.
Not really familiar with Android, but this seems interesting to me.

**Comment by RensOliemans** [comment] 2020-10-20 21:50
I just updated my Signal version to `4.72.2` but the error still persists.
According new debug log: https://debuglogs.org/782342efb58290966a23ba6e4298aec6386566eeb1f349eced727c6b716209cb

**Comment by ni720** [comment] 2020-10-21 09:03
Same Problem here:

Device: OnePlus 7Pro
Android version: 10 (unrooted)
Signal Version: 4.72.2

**Comment by siburny** [comment] 2020-10-22 01:52
All identical problems here as well. Exact same setup as the poster above.

**Comment by id101010** [comment] 2020-10-22 08:39
Identical issue here as well.

* OnePlus7Pro
* Android 10 (unrooted)
* Oxygen OS 10.0.7.GM21BA
* Signal Version v4.74.3

**Comment by Kage1** [comment] 2020-10-22 11:59
I also have the same problem. Back arrow doesn't work and the rest like the others have stated. I am also using Nova Launcher. 

OnePlus7Pro
Android 10
Oxygen OS 10.3.4.GM21AA
Signal Version v4.74.3

**Comment by TurboGLH** [comment] 2020-10-22 17:18
Same.

Oneplus 7Pro
Android 10 (unrooted)
Oxygen OS 10.3.4.GM21AA
Signal Version v4.74.3

**Comment by l3u** [comment] 2020-10-22 19:04
Same here, Nokia 4.2, Android 10, Signal 4.74.3.

**Comment by Kage1** [comment] 2020-10-22 22:42
It looks like this issue maybe related to #10105 which will hopefully be fixed in 4.75.

**Comment by siburny** [comment] 2020-10-23 01:47
> It looks like this issue maybe related to #10105 which will hopefully be fixed in 4.75.
That ticket does mention this warning, but it's more about log size.  Let's see if v4.75 will address this.

**Comment by blunden** [comment] 2020-10-23 13:43
It seems the issue is that the app is accessing fields that aren't part of the public API.

https://developer.android.com/about/versions/10/non-sdk-q

If I run the ADB command to disable enforcement it starts working again.

**Comment by obfusk** [comment] 2020-10-23 15:14
@blunden I agree with your diagnosis.

The link lists `Landroid/view/View;->mAttachInfo:Landroid/view/View$AttachInfo;   # No public alternative` under "Non-SDK interfaces that are now blocked in Android 10".

And I can confirm that `adb shell settings put global hidden_api_policy 1` (+ reboot) "fixes" the issue for me on Android 10.

It also suggests that the "fix" for #10105 results in the errors being ignored (instead of at least logged) in v4.75.

**Comment by cody-signal** [comment] 2020-10-23 15:17
We've finally been able to repro this issue and will have a fix out soon.

**Comment by tripslip38** [comment] 2020-10-23 20:25
Came here to report, nice to see I'm not alone and devs are on it! Thanks guys.

**Comment by thelanranger** [comment] 2020-10-24 01:07
Same issue. Nokia 7.2 unrooted. Backed up, uninstalled/reinstalled, restored, issue is the same. 
Noted that the Blue popups during the fresh install have the same issue as the + and system back (respond to the click but do not operate). Submitted debug log. Thanks!

**Comment by ezaquarii** [comment] 2020-10-25 18:46
Same issue on Samsung A20. It works in landscape mode tho.

**Comment by Kage1** [comment] 2020-10-25 18:55
4.75.1 has resolved the problem for me

**Comment by siburny** [comment] 2020-10-25 19:29
I can confirm that v4.75.1 resolved this issue for me too.

**Closed** 2020-10-26 14:35 UTC

**Comment by thelanranger** [comment] 2020-10-26 15:41
How do you upgrade? 4.75.1 is not on play store...

**Comment by TurboGLH** [comment] 2020-10-26 15:50
> How do you upgrade? 4.75.1 is not on play store...

Join the beta, either on the app page in the play store or at

https://support.signal.org/hc/en-us/articles/360007318471-Signal-Beta
