### ISSUE TITLE
Bad encrypted message

### ISSUE THREAD

**Issue by merkste** [signalapp/Signal-Android#4736] opened 2015-11-27 14:28 UTC
After the update to 3.5.2, a friend of mine could not decrypt my messages anymore.  Restarting the encryption session solved the issue temporarily. The debug log reads as follows: https://gist.github.com/anonymous/a658f8a3b88ee1fcdbf7

**Comment by eosrei** [comment] 2016-02-24 01:07
Duplicate of  #1668. I have a debug log and screencap of the same issue.

**Comment by riyapenn** [comment] 2017-01-18 23:24
Adding to this issue vs the numerous other open ones: https://github.com/WhisperSystems/Signal-Android/issues/2514, https://github.com/WhisperSystems/Signal-Android/issues/1668, and more.  User states messages are out of order and seeing message failed to send errors, most similar to: https://github.com/WhisperSystems/Signal-Android/issues/5119

Bad Encrypted Message appeared at 23:47 gist.github.com/anonymous/a3ada33e4ba531ca77e0544e8514112b

**Comment by automated-signal** [comment] 2018-04-02 23:02
GitHub Issue Cleanup:
See #7598 for more information.

**Closed** 2018-04-02 23:02 UTC
