### ISSUE TITLE
Disappearing messages not currently working

### ISSUE THREAD

**Issue by GSPP** [signalapp/Signal-Android#8068] opened 2018-08-03 09:21 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

Disappearing messages currently do not work at all. I have multiple conversations where the timer is clearly set to 1 week and has been for month. Yet, I can still scroll up months back and see all messages.

I can see both the timer and the messages on my Nexus 5X and on my Signal Desktop.

### Device info

**Device:** Nexus 5X
**Android version:** 8
**Signal version:** 4.23.4 / 1.15.0

**Comment by 2-4601** [comment] 2018-08-03 12:33
Could you post a debug log and possibly try to find out the steps how to reproduce this?

**Comment by 2-4601** [comment] 2018-08-03 12:43
I tried this a little bit and stumbled upon this:
- in a group enable 5 second disappearing messages from your Android device
- send message from Desktop (your own slave) to the group
- messages don't disappear on Android

https://debuglogs.org/b9693a4b643451941fabda526885a1542c7c3b6b8add24424e3f4f7df7eaa4fe

Moto G4 Play, Android 7.1.1, Signal 4.24.5
Desktop v1.15.0-beta.10

**Comment by jeremymasters** [comment] 2018-08-03 14:17
if you send messages from your android device, do they disappear on the android device and/or desktop?

**Comment by 2-4601** [comment] 2018-08-03 14:44
> if you send messages from your android device, do they disappear on the android device and/or desktop?

Yes.

**Comment by jeremymasters** [comment] 2018-08-03 15:10
It might be worth updating your android version to the newest (4.24.6) just to be safe.  Also, it looks like there's been some work around disappearing messages on the desktop version.  Might be worth checking with @scottnonnenberg-signal on it with a debug log from desktop version.

**Comment by greyson-signal** [comment] 2018-08-03 16:24
@GSPP For the messages on Android, when you look at the timer on the message, is the timer empty? 

Also, for more specific info, can you long-press one of the messages that you think should be disappeared, then click the little info button in the action bar? It should take you to a message details screen, and that screen should have a field called "Disappears" that will tell you how much longer Signal thinks the message should last. Let me know what that says, or send a screenshot. 

Thanks!

**Comment by greyson-signal** [comment] 2018-08-03 16:31
@GSPP  Also, if you could describe your general usage patterns between Android and Desktop, that'd be super helpful. e.g. Did you set the timer's on one platform, and then message on another? Is it a group chat where someone else may have changed the timer? Stuff like that. Thanks again!

**Comment by greyson-signal** [comment] 2018-08-03 18:54
@2-4601 The issue you described should be fixed in 4.24.7. Thank you!

**Comment by 2-4601** [comment] 2018-08-03 19:11
@greyson-signal 4.24.7 indeed fixed that specific case.

**Comment by landry314** [comment] 2018-08-04 20:38
so this issue should be closed?

**Comment by GSPP** [comment] 2018-08-05 20:35
On mobile and on desktop the timer is clearly identified as "1 week". Messages have both been sent and received by both sides on both devices many times. They do not selectively disappear.

On mobile I openend message details of a very old message. There is no mention of anything related to disappearing. Just sent/received date and time.

I could try changing the timer. I avoided that so far in order to preserve evidence.

I have closed, opened and sent a test message on Signal Desktop. Debug log:

> INFO  2018-08-05T20:23:05.190Z Load expired messages
> INFO  2018-08-05T20:23:05.191Z Message expired {"sentAt":1532895784733}
> INFO  2018-08-05T20:23:05.202Z next message expires 2018-08-05T20:23:07.414Z
> INFO  2018-08-05T20:23:06.191Z Sending a keepalive message
> INFO  2018-08-05T20:23:08.190Z Load expired messages
> INFO  2018-08-05T20:23:08.192Z Message expired {"sentAt":1532895787016}
> INFO  2018-08-05T20:23:08.203Z next message expires 2018-08-05T20:52:31.375Z
> INFO  2018-08-05T20:24:02.192Z Sending a keepalive message
> INFO  2018-08-05T20:24:58.190Z Sending a keepalive message
> INFO  2018-08-05T20:25:54.190Z Sending a keepalive message
> INFO  2018-08-05T20:26:50.192Z Sending a keepalive message
> INFO  2018-08-05T20:27:46.194Z Sending a keepalive message
> INFO  2018-08-05T20:28:19.396Z Remove all notifications
> INFO  2018-08-05T20:28:19.893Z Updating BrowserWindow config: {"maximized":true,"autoHideMenuBar":false,"width":1296,"height":978,"x":-8,"y":-8}
> INFO  2018-08-05T20:28:20.397Z Update notifications: {"shouldClearNotifications":false,"shouldPlayNotificationSound":false,"shouldShowNotifications":false,"type":"noNotifications","isNotificationGroupingSupported":false}
> INFO  2018-08-05T20:28:20.869Z unloading conversation +[REDACTED]128 due to: inactivity
> INFO  2018-08-05T20:28:21.337Z Updating BrowserWindow config: {"maximized":true,"autoHideMenuBar":false,"width":1296,"height":978,"x":-8,"y":-8}
> INFO  2018-08-05T20:28:21.343Z unloading conversation +[REDACTED]128 due to: windows closed
> INFO  2018-08-05T20:28:21.343Z unloading conversation +[REDACTED]719 due to: windows closed
> INFO  2018-08-05T20:28:21.361Z Update notifications: {"shouldClearNotifications":false,"shouldPlayNotificationSound":false,"shouldShowNotifications":false,"type":"noNotifications","isNotificationGroupingSupported":false}
> INFO  2018-08-05T20:28:32.645Z app ready
> INFO  2018-08-05T20:28:32.653Z Ensure attachments directory exists
> INFO  2018-08-05T20:28:32.658Z updateSchema: Current schema version: 1; Most recent schema version: 1; SQLite version: 3.20.1; SQLCipher version: 3.4.2;
> INFO  2018-08-05T20:28:32.736Z Location reset needed
> INFO  2018-08-05T20:28:32.736Z Initializing BrowserWindow config: {"show":true,"width":1296,"height":978,"minWidth":640,"minHeight":360,"autoHideMenuBar":false,"webPreferences":{"nodeIntegration":false,"nodeIntegrationInWorker":false,"preload":"[REDACTED]\\app.asar\\preload.js","nativeWindowOpen":true},"icon":"[REDACTED]\\app.asar\\images\\icon_256.png","maximized":true}
> INFO  2018-08-05T20:28:34.852Z Updating BrowserWindow config: {"maximized":true,"autoHideMenuBar":false,"width":1296,"height":978,"x":-8,"y":-8}
> INFO  2018-08-05T20:28:35.342Z Using OS-level spell check API with locale de_DE
> INFO  2018-08-05T20:28:35.573Z pre-main prep time: 4 ms
> INFO  2018-08-05T20:28:35.609Z Build expires:  2018-11-01T06:10:28.000Z
> INFO  2018-08-05T20:28:35.636Z background page reloaded
> INFO  2018-08-05T20:28:35.636Z environment: production
> INFO  2018-08-05T20:28:35.638Z Start IndexedDB migrations
> INFO  2018-08-05T20:28:35.638Z Run migrations on database with attachment data
> INFO  2018-08-05T20:28:35.758Z Database status {"firstMigrationVersion":12,"lastMigrationVersion":18,"databaseVersion":18,"isAlreadyUpgraded":true}
> INFO  2018-08-05T20:28:35.758Z Storage fetch
> INFO  2018-08-05T20:28:35.806Z upgradeMessages: Mandatory message schema upgrade started. Target version: 7
> INFO  2018-08-05T20:28:35.812Z upgradeMessages: upgrade without index {"done":true}
> INFO  2018-08-05T20:28:35.812Z upgradeMessages: upgrade without index complete!
> INFO  2018-08-05T20:28:36.570Z upgradeMessages: upgrade with index {"done":true,"numProcessed":0,"fetchDuration":757,"upgradeDuration":0,"saveDuration":0,"totalDuration":757}
> INFO  2018-08-05T20:28:36.570Z upgradeMessages: upgrade with index complete!
> INFO  2018-08-05T20:28:36.570Z upgradeMessages: Message schema upgrade complete
> INFO  2018-08-05T20:28:36.862Z Starting background data migration. Target version: 8
> INFO  2018-08-05T20:28:36.864Z ConversationController: starting initial fetch
> INFO  2018-08-05T20:28:36.882Z ConversationController: done with initial fetch
> INFO  2018-08-05T20:28:36.883Z listening for registration events
> INFO  2018-08-05T20:28:36.885Z Next signed key rotation scheduled for 2018-08-06T19:21:54.805Z
> INFO  2018-08-05T20:28:36.886Z connect
> INFO  2018-08-05T20:28:36.887Z getAllFromCache
> INFO  2018-08-05T20:28:36.887Z opening message socket https://textsecure-service.whispersystems.org
> INFO  2018-08-05T20:28:37.971Z open inbox
> INFO  2018-08-05T20:28:38.017Z Sync read receipt configuration status: {"status":"skipped","reason":"hasPreviouslySynced"}
> INFO  2018-08-05T20:28:38.017Z Start idle detector
> INFO  2018-08-05T20:28:38.020Z next message expires 2018-08-05T20:52:31.375Z
> INFO  2018-08-05T20:28:38.020Z getAllFromCache loaded 1 saved envelopes
> WARN  2018-08-05T20:28:38.021Z getAllFromCache final attempt for envelope +[REDACTED]367.1 1532807021077
> INFO  2018-08-05T20:28:38.493Z websocket open
> INFO  2018-08-05T20:28:38.493Z got request PUT /api/v1/queue/empty
> ERROR 2018-08-05T20:28:39.126Z queueCached error handling item +[REDACTED]367.1 1532807021077
> INFO  2018-08-05T20:28:39.126Z MessageReceiver: emitting 'empty' event
> INFO  2018-08-05T20:28:40.128Z Update notifications: {"shouldClearNotifications":false,"shouldPlayNotificationSound":false,"shouldShowNotifications":false,"type":"noNotifications","isNotificationGroupingSupported":false}
> INFO  2018-08-05T20:28:41.306Z fetchMessages
> INFO  2018-08-05T20:28:41.314Z GET https://textsecure-service.whispersystems.org/v1/profile/+[REDACTED]719
> INFO  2018-08-05T20:28:41.814Z Conversation +[REDACTED]719 took 506 milliseconds to load
> INFO  2018-08-05T20:28:42.163Z GET https://textsecure-service.whispersystems.org/v1/profile/+[REDACTED]719 200 Success
> INFO  2018-08-05T20:28:42.169Z GET https://cdn.signal.org/profiles/x
> ERROR 2018-08-05T20:28:42.708Z GET https://cdn.signal.org/profiles/x 403 Error
> INFO  2018-08-05T20:28:42.712Z done with status fetch
> INFO  2018-08-05T20:28:44.183Z Upgrade message schema (with index): {"done":false,"numProcessed":1,"fetchDuration":6,"upgradeDuration":1,"saveDuration":9,"totalDuration":16}
> INFO  2018-08-05T20:28:44.187Z next message expires 2018-08-05T20:52:31.375Z
> INFO  2018-08-05T20:28:49.677Z Send pre-checks took 13 milliseconds
> INFO  2018-08-05T20:28:49.694Z Sending message to conversation +[REDACTED]719 with timestamp 1533500929693
> INFO  2018-08-05T20:28:49.950Z next message expires 2018-08-05T20:52:31.375Z
> INFO  2018-08-05T20:28:50.327Z PUT https://textsecure-service.whispersystems.org/v1/messages/+[REDACTED]719
> INFO  2018-08-05T20:28:50.711Z PUT https://textsecure-service.whispersystems.org/v1/messages/+[REDACTED]719 200 Success
> INFO  2018-08-05T20:28:50.722Z Set message expiration {"expiresAt":1534105730712,"sentAt":1533500929693}
> INFO  2018-08-05T20:28:50.827Z PUT https://textsecure-service.whispersystems.org/v1/messages/+[REDACTED]367
> INFO  2018-08-05T20:28:50.947Z next message expires 2018-08-05T20:52:31.375Z
> INFO  2018-08-05T20:28:51.147Z PUT https://textsecure-service.whispersystems.org/v1/messages/+[REDACTED]367 200 Success
> INFO  2018-08-05T20:28:51.785Z queueing envelope +[REDACTED]719.1 1533500929693
> INFO  2018-08-05T20:28:51.786Z delivery receipt from +[REDACTED]719.1 1533500929693
> INFO  2018-08-05T20:28:51.948Z next message expires 2018-08-05T20:52:31.375Z
> INFO  2018-08-05T20:28:54.907Z Send pre-checks took 11 milliseconds
> INFO  2018-08-05T20:28:54.923Z Sending message to conversation +[REDACTED]719 with timestamp 1533500934923
> INFO  2018-08-05T20:28:55.097Z next message expires 2018-08-05T20:52:31.375Z
> INFO  2018-08-05T20:28:55.310Z PUT https://textsecure-service.whispersystems.org/v1/messages/+[REDACTED]719
> INFO  2018-08-05T20:28:55.644Z PUT https://textsecure-service.whispersystems.org/v1/messages/+[REDACTED]719 200 Success
> INFO  2018-08-05T20:28:55.655Z Set message expiration {"expiresAt":1534105735644,"sentAt":1533500934923}
> INFO  2018-08-05T20:28:55.782Z PUT https://textsecure-service.whispersystems.org/v1/messages/+[REDACTED]367
> INFO  2018-08-05T20:28:56.098Z next message expires 2018-08-05T20:52:31.375Z
> INFO  2018-08-05T20:28:56.146Z PUT https://textsecure-service.whispersystems.org/v1/messages/+[REDACTED]367 200 Success
> INFO  2018-08-05T20:28:56.204Z queueing envelope +[REDACTED]719.1 1533500934923
> INFO  2018-08-05T20:28:56.204Z delivery receipt from +[REDACTED]719.1 1533500934923
> INFO  2018-08-05T20:28:57.099Z next message expires 2018-08-05T20:52:31.375Z
> INFO  2018-08-05T20:28:59.184Z Upgrade message schema (with index): {"done":false,"numProcessed":1,"fetchDuration":6,"upgradeDuration":0,"saveDuration":7,"totalDuration":13}
> INFO  2018-08-05T20:28:59.186Z next message expires 2018-08-05T20:52:31.375Z
> INFO  2018-08-05T20:28:59.590Z Send pre-checks took 12 milliseconds
> INFO  2018-08-05T20:28:59.606Z Sending message to conversation +[REDACTED]719 with timestamp 1533500939605
> INFO  2018-08-05T20:29:00.002Z PUT https://textsecure-service.whispersystems.org/v1/messages/+[REDACTED]719
> INFO  2018-08-05T20:29:00.187Z next message expires 2018-08-05T20:52:31.375Z
> INFO  2018-08-05T20:29:00.337Z PUT https://textsecure-service.whispersystems.org/v1/messages/+[REDACTED]719 200 Success
> INFO  2018-08-05T20:29:00.346Z Set message expiration {"expiresAt":1534105740337,"sentAt":1533500939605}
> INFO  2018-08-05T20:29:00.448Z PUT https://textsecure-service.whispersystems.org/v1/messages/+[REDACTED]367
> INFO  2018-08-05T20:29:00.666Z queueing envelope +[REDACTED]719.1 1533500939605
> INFO  2018-08-05T20:29:00.666Z delivery receipt from +[REDACTED]719.1 1533500939605
> INFO  2018-08-05T20:29:00.782Z PUT https://textsecure-service.whispersystems.org/v1/messages/+[REDACTED]367 200 Success
> INFO  2018-08-05T20:29:01.188Z next message expires 2018-08-05T20:52:31.375Z
> INFO  2018-08-05T20:29:09.183Z Upgrade message schema (with index): {"done":false,"numProcessed":1,"fetchDuration":1,"upgradeDuration":1,"saveDuration":8,"totalDuration":10}
> INFO  2018-08-05T20:29:09.185Z next message expires 2018-08-05T20:52:31.375Z
> INFO  2018-08-05T20:29:12.507Z Loaded this list of log files from logPath: log.log, log.log.0, log.log.1

**Comment by GSPP** [comment] 2018-08-06 08:10
I just noticed that recent messages disappear correctly. The chat log shows an entry where disappearing messages was enabled. Before that there is no expiry, though. It seems that the timer is not applied retroactively to existing messages.

If this is by design it's not what I want as a user. I'd need to clear the chat directly after enabling the timer to make sure that old messages eventually die.

**Comment by 2-4601** [comment] 2018-08-06 11:53
Good to hear that it's not a bug after all. If the timer applied to all messages then it would also remove other people's past messages from the conversation. I don't think that's what most users would expect or want.

Since this isn't a bug I'm going to close this issue and if you want to discuss more about disappearing messages and how they should work, please come to the [forum](https://community.signalusers.org) (you can use your GitHub account as login).

**Closed by 2-4601** 2018-08-06 11:53 UTC
