### ISSUE TITLE
Cannot delete Signal contact

### ISSUE THREAD

**Issue by RalfJung** [signalapp/Signal-Android#4678] opened 2015-11-22 19:25 UTC
A friend changed their phone number, and registered a new Signal account for the new number. I would like to get rid of the old number in my contacts. However, there is still a "Messaging" entry for that friend with the old number, right next to the "Nachrichten" entry with the new number (that's German for "messages", my phone UI is set to be German). I have found no way to delete the old number from the contacts, because the way Signal adds it, Android tells me this is a "read-only account" and I can't change it. I already tried deleting the conversations I had with that friend, to no avail. Note that the old account is still in some groups I am also in, which we can't do anything about since he no longer has access to the old account, and hence can't leave any groups.

This is frustrating. There should be some way to delete/update contacts.

Device info: Motorola E (2nd gen), CM 12.1, Signal v3.1.1

I wouldn't know what to catch a debug log of to document this. If you need further information, please let me know.

**Comment by mawed** [comment] 2015-11-22 20:42
Tell your friend to unregister here: https://whispersystems.org/textsecure/unregister/

**Comment by RalfJung** [comment] 2015-11-22 20:47
I will. However, he doesn't own the old number anymore, so I don't think that will be possible.

I upgraded to Signal v3.5.0, but found no way to delete a contact there either.

**Comment by darryl-grennan** [comment] 2015-11-30 01:35
Preferably there should be a means of doing within Signal exactly what happens if you uninstall and re-install Signal.  That is, it removes contact associations and re-associates upon re-install.

There are a lot of ways (deletion/separation) to break the contacts association after they've been created by Signal and a means of recovery and resynchronization needs to somehow be employed here.  It breaks too easily.

**Comment by 2-4601** [comment] 2015-12-24 12:22
#274 with its current title description is the same as this (the comments are not very relevant though)

**Comment by KommX** [comment] 2016-06-03 18:55
I also have this problem. Is there anything I can do to get rid off the contact's old number?

**Comment by nsturnitin** [comment] 2016-07-30 19:00
I've got this annoying conect that added me and I've not been able to delete this person out of my life.  Am I missing something or is there really no ability at this time to remove a contact from showing up as a contact. (I'm using the osx desktop version)

**Comment by riyapenn** [comment] 2016-08-05 00:01
Have you tried removing the contact entirely from your Android phone and then steps on the support page: http://support.whispersystems.org/hc/en-us/articles/218514998-How-do-I-update-contacts-on-Signal-Desktop-
Or contact support@whispersystems.org

**Comment by only1miller** [comment] 2016-11-22 05:21
Hi! Has there been any development on this? I looked at the instructions for purging contacts from Signal and I just have to believe there's an easier more streamlined process on the way... somthing in the realm of "right click, remove contact" :-)

**Comment by nlmunro** [comment] 2016-11-27 19:55
To explain, I have work contacts on my Android, but I don't want to contact them (or perhaps more to the point, I do not want them to contact me) via Signal. I only want people that I choose to add - period.

**Comment by Trolldemorted** [comment] 2016-11-27 20:08
@nlmunro I think what you request might be impossible (not literally of course, but impossible enough that it will not happen).

This would require your device to have influence on another person's contact discovery, and iirc contact discovery works by attempting to create a session for every contact in your contact list.

**Comment by nlmunro** [comment] 2016-11-27 20:17
Well I don't know the technical details, but I would have thought that allowing the "target" of the discovery to choose if they want to be discovered is pretty important - a bit like accepting a "friend" request except the requester should not even know if I exist. I suppose I could block people, but that risks offending them!

**Comment by Trolldemorted** [comment] 2016-11-27 20:38
I can think of no way to forbid clients to establish sessions (while looking "natural") but allowing a set of numbers to do that without having the server maintain that set (and i am pretty sure OWS does not want to do that).

Furthermore i believe that just blocking them should™ look like you have uninstalled signal without unregistering your number (but that requires you to block them before they send the first message. If that is a problem, you could try to convince OWS that it would be reasonable to not send delivery receipts for numbers not in your contact list or you have never responded to).
Your clients *could* try to establish more than 100 sessions to see if your pre-keys are refilling, but i doubt any of your clients will do that.
Please note that this is a rough guess, i did not have a look on the sourcecode, nor did i ever block anyone, so i suggest you try it out yourself. I also do not know how well Signal-Desktop handles blocked users, it might send delivery receipts which will disclose an active device.

**Comment by nlmunro** [comment] 2016-11-27 20:51
Thanks for the background info - though for me this is more of a UX issue. Perhaps I'm unusual, but it just seems odd having contacts added without asking and not being able to remove them.

**Comment by Trolldemorted** [comment] 2016-11-27 20:55
that you cannot remove them on your local device is indeed a ux issue, but making their devices think you are not a signal user is a completely different story!

Even if you were able to delete them, they could just message you again.

**Comment by nlmunro** [comment] 2016-11-27 21:49
I'm using the term UX in the sense of overall application usability rather than just the UI - obviously simply adding a "delete" button doesn't solve anything! If I ever find time I'll try and understand how it works...

**Comment by piusg** [comment] 2016-12-06 05:17
I just wanna delete the conversation thread in the viewer. It makes no sense that Signal can have self-destructing messages yet cannot delete a name off a list. If it's that hard, I don't care if it goes away; just give me the option to hide it.

I just broke up with someone whose name I'd rather not see on my Signal list anymore, dig?

**Comment by Sweater-Baron** [comment] 2016-12-06 06:58
@piusg If you just want to stop seeing the message thread, you can swipe a conversation right to archive it.

**Comment by riyapenn** [comment] 2016-12-06 07:16
If you are looking to remove Alice from your Signal conversation thread AND contact list:

1. Delete conversation thread with Alice
- [ ] - Go to the main list of conversations where Signal is in the top left corner and the blue circle with the white pencil is in the bottom right
- [ ] - Long press on the conversation thread with contact Alice
- [ ] - Tap on the trash can in the header
- [ ] - Confirm the delete

2. Delete contact Alice from your phone's contact list
- [ ] - Go to your phone's contact list app
- [ ] - Delete Alice's phone number or entire contact entry (Steps vary by phone)

3. Re-sync Signal contacts
- [ ] Go to Android Settings or 
- [ ] Android Contac'ts App > Menu 
- [ ] Choose Accounts
- [ ] Choose Signal
- [ ] Tap on the Menu
- [ ] Choose Remove Account (the alert of clearing data is incorrect, your messages will not be deleted)
- [ ] Open Signal
- [ ] Tap on the pencil icon in the blue circle
- [ ] Choose the Menu
- [ ] Tap Refresh

You need to have an existing conversation thread with a contact to block.[ Follow steps on the support page](https://support.whispersystems.org/hc/en-us/articles/212535898-How-do-I-block-a-number-) if that's your interest.

**Comment by piusg** [comment] 2016-12-07 04:02
Thank you!

**Comment by jblosser** [comment] 2017-01-26 20:56
Given that the provided solution requires removing the person from your phone contact list entirely, this is at best a workaround. Other general issues like #274 were closed in favor of this one. The goal of many is to be able to control their own contacts list inside of this app without just inheriting every possible contact from our phones, including the entire company address book. It's not particularly good UX to have to scroll through dozens of people you never actually contact, but still need in your address book for caller ID purposes "just in case".

**Comment by rejhgadellaa** [comment] 2017-02-07 17:29
Huh? How is this issue closed? Removing a contact from your Google Contacts is not the solution to delete them in Signal?

**Comment by piusg** [comment] 2017-02-07 21:00
Well, technically, it's working as designed. Now about the desirability of that solution...


Gregory

________________________________

**Comment by nlmunro** [comment] 2017-02-07 21:11
"Now about the desirability of that solution..."
Indeed - I just "had" to install WhatsApp (someone was ONLY on that network) and found it AWFUL - it asks for permission to access contacts and of course, they then import them all. I think if Signal could come up with a solution they really could differentiate themselves.

**Comment by josebrwn** [comment] 2017-03-31 15:46
Me too. The inability to delete contacts from Signal is an unfortunate fault. It should not be incumbent on the user(s) to correct for either phone numbers that are no longer active, or people who simply tried Signal, and stopped using it. Having them in your contacts FOREVER when they have no way of responding to you is untenable and unnecessary. It should be a simple matter of right clicking and choosing "remove contact".

**Comment by piusg** [comment] 2017-03-31 20:17
I'm glad I'm not the only one who agrees. Google Voice and Hangouts have "Archive." I'd settle for an "archive" feature.

________________________________

**Comment by josebrwn** [comment] 2017-06-07 19:55
I still can't fathom why this is closed, aside from the developer's hubris. For instance, why on earth would a keep a contact's phone number FOREVER when they change their phone number? Fortunately, I've found a workaround that works not only in Signal, but also in your phone's contacts:

Step 1. Uninstall Signal.
Step 2. There is no step 2.

**Comment by piusg** [comment] 2017-06-07 20:07
Me either. For Heaven's sake, every chat client in existence has at least an 'archive' feature. I'm pretty disappointed, WhisperSystems. There really is no practical reason why this cannot be addressed.

I hate to appear antagonistic, but in the absence of information, the mind goes to all kinds of crazy places, Like for instance: it feels to me like they're purposely tanking their own client to tacitly drive users to other secure platforms (e.g. platforms that can be monetized somehow). Further proof that when you don't know what the product is, it's you.

Anybody at WhisperSystems wanna step up and tell me I'm wrong? I know y'all are listening.

________________________________

**Comment by haffenloher** [comment] 2017-06-07 20:15
@piusg there's been an [archive function](https://support.whispersystems.org/hc/en-us/articles/214582088-How-can-I-archive-or-unarchive-a-chat-) for quite some time now.

**Comment by sarumpaet** [comment] 2017-07-24 16:22
I just ran into this scenario:
* a standard Android contact of mine had a secondary phone number "B" (that contact's flatmate, in case of emergencies etc.)
* B signed up on Signal (the main number wasn't on Signal)
* confusion in Signal ensues (I guess Signal isn't really to blame here)
* I delete the Signal conversation with B, also delete B from the Android address book

Now, the "fun" thing is...
* B keeps showing up as secondary number in the address book (it doesn't show up in edit mode)
* B keeps showing up in the Signal contact list

ZOMBIES! And basically Signal breaks the Android address book _as well_.

https://github.com/WhisperSystems/Signal-Android/issues/4678#issuecomment-265078478 fixed the issue for me, but that really is far too complicated and non-intuitive for just deleting something.

Please reopen this issue.

**Comment by boozezela** [comment] 2017-07-31 02:22
Just experienced this myself:
Edited my own contact details - I have a separate entry I use for sharing, separated from the "phone owner" one - to remove an mobile number as its corresponding SIM card expired.

Guess what ? I could still see the number in my contact details.
It took me several minutes to realise that the number was still linked from the contact list synced by Signal.

Then I had to google how to remove it, which led me to the whole "remove signal account", "open signal" charade detailed in comment #4678.

**Comment by githubmil** [comment] 2017-09-23 08:41
So https://github.com/WhisperSystems/Signal-Android/issues/4678?_pjax=%23js-repo-pjax-container#issuecomment-265078478 works, but wow is that a convoluted way to remove an old phone #

**Comment by ajford** [comment] 2017-10-23 14:28
I second the question as to why this is closed. Like said above what reasonable explanation is there for this thread being closed? I would venture to say it is actively user hostile to close this issue when it prevents people from controlling their contacts.

**Comment by blexicore** [comment] 2017-10-27 03:56
Well, on the Signal  Windows desktop version, I inherited somehow an Insurance Contact for no good reason and over time, two other phone numbers are there as well. I would like to get rid of all those.
Why can't I right-click on one Contact and delete it along with all the posts under it?
The length of this thread is astonishing.
What am I missing?

**Comment by cornfeedhobo** [comment] 2017-12-05 01:08
@moxie0 can we please address this problem in a holistic way? This is a huge PITA when a friend stops using Signal and all contact with them becomes a black hole because Signal still thinks they are a user. There should be a client-side choice to use signal or sms. Please!

**Comment by setibeings** [comment] 2018-02-11 06:16
The referenced feature request was closed. I feel like a more user friendly implementation of deleting extraneous numbers needs to exist. My buddy gave his old phone to his brother, and after some amount of trying, I could't get the now bad number to go away from that buddy's contact, so I lived with it for about 2 years.

**Comment by Reylak** [comment] 2018-03-26 09:44
What the "answer" [here](https://github.com/signalapp/Signal-Android/issues/4678#issuecomment-265078478) fails to assert, it that the contact is **read-only** until you remove your Signal account from your device.

The exact procedure is to remove the account **before** removing the contact, and then resyncing using the method in the comment (open Signal, blue pencil button, menu, refresh).

**Comment by automated-signal** [comment] 2018-04-02 23:05
GitHub Issue Cleanup:
See #7598 for more information.

**Closed** 2018-04-02 23:05 UTC
