### ISSUE TITLE
Attachment uploads fail on slower speeds than 1 Mbps

### ISSUE THREAD

**Issue by petcap** [signalapp/Signal-Android#9814] opened 2020-07-01 21:06 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Uploading attachments over a somewhat slow (1 Mbps in my case) connection usually fails and starts over an infinitely amount of times. When uploading a single image or file, the upload appears to reach 100%, then it starts over. When uploading an album, the upload indicator jumps around but never reaches 100%. This is most likely due to the individual image transfers starting over.

When reducing upload speeds to 0.5 Mbps, upload never finishes at all. At 1 Mbps, they seem to finish after about 4-5 retries, depending on if the below timeout is reached or not.

This is the related exception/timeout:
```
2020-07-01 22:45:18.634 GMT+02:00 I BaseJob: org.whispersystems.signalservice.api.push.exceptions.PushNetworkException: java.net.SocketTimeoutException: timeout
2020-07-01 22:45:18.634 GMT+02:00 I BaseJob: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.uploadToCdn0(PushServiceSocket.java:1146)
2020-07-01 22:45:18.634 GMT+02:00 I BaseJob: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.uploadAttachment(PushServiceSocket.java:980)
2020-07-01 22:45:18.634 GMT+02:00 I BaseJob: 	at org.whispersystems.signalservice.api.SignalServiceMessageSender.uploadAttachmentV2(SignalServiceMessageSender.java:409)
2020-07-01 22:45:18.634 GMT+02:00 I BaseJob: 	at org.whispersystems.signalservice.api.SignalServiceMessageSender.uploadAttachment(SignalServiceMessageSender.java:387)
2020-07-01 22:45:18.634 GMT+02:00 I BaseJob: 	at org.thoughtcrime.securesms.jobs.AttachmentUploadJob.onRun(AttachmentUploadJob.java:129)
2020-07-01 22:45:18.634 GMT+02:00 I BaseJob: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:25)
2020-07-01 22:45:18.634 GMT+02:00 I BaseJob: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:82)
2020-07-01 22:45:18.634 GMT+02:00 I BaseJob: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:46)
2020-07-01 22:45:18.634 GMT+02:00 I BaseJob: Caused by: java.net.SocketTimeoutException: timeout
2020-07-01 22:45:18.634 GMT+02:00 I BaseJob: 	at okio.Okio$4.newTimeoutException(Okio.java:232)
2020-07-01 22:45:18.634 GMT+02:00 I BaseJob: 	at okio.AsyncTimeout.exit(AsyncTimeout.java:286)
2020-07-01 22:45:18.634 GMT+02:00 I BaseJob: 	at okio.AsyncTimeout$1.write(AsyncTimeout.java:184)
2020-07-01 22:45:18.634 GMT+02:00 I BaseJob: 	at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:179)
2020-07-01 22:45:18.634 GMT+02:00 I BaseJob: 	at okio.RealBufferedSink.write(RealBufferedSink.java:42)
2020-07-01 22:45:18.634 GMT+02:00 I BaseJob: 	at okhttp3.internal.http1.Http1Codec$FixedLengthSink.write(Http1Codec.java:295)
2020-07-01 22:45:18.634 GMT+02:00 I BaseJob: 	at okio.ForwardingSink.write(ForwardingSink.java:35)
2020-07-01 22:45:18.634 GMT+02:00 I BaseJob: 	at okhttp3.internal.http.CallServerInterceptor$CountingSink.write(CallServerInterceptor.java:149)
2020-07-01 22:45:18.634 GMT+02:00 I BaseJob: 	at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:179)
2020-07-01 22:45:18.634 GMT+02:00 I BaseJob: 	at okio.RealBufferedSink$1.write(RealBufferedSink.java:201)
2020-07-01 22:45:18.634 GMT+02:00 I BaseJob: 	at org.whispersystems.signalservice.api.crypto.SkippingOutputStream.write(SkippingOutputStream.java:50)
2020-07-01 22:45:18.634 GMT+02:00 I BaseJob: 	at org.whispersystems.signalservice.api.crypto.DigestingOutputStream.write(DigestingOutputStream.java:29)
2020-07-01 22:45:18.634 GMT+02:00 I BaseJob: 	at org.whispersystems.signalservice.api.crypto.AttachmentCipherOutputStream.write(AttachmentCipherOutputStream.java:67)
2020-07-01 22:45:18.634 GMT+02:00 I BaseJob: 	at org.whispersystems.signalservice.internal.push.http.DigestingRequestBody.writeTo(DigestingRequestBody.java:65)
2020-07-01 22:45:18.634 GMT+02:00 I BaseJob: 	at okhttp3.MultipartBody.writeOrCountBytes(MultipartBody.java:173)
2020-07-01 22:45:18.634 GMT+02:00 I BaseJob: 	at okhttp3.MultipartBody.writeTo(MultipartBody.java:114)
2020-07-01 22:45:18.634 GMT+02:00 I BaseJob: 	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:72)
2020-07-01 22:45:18.634 GMT+02:00 I BaseJob: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2020-07-01 22:45:18.634 GMT+02:00 I BaseJob: 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
2020-07-01 22:45:18.634 GMT+02:00 I BaseJob: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2020-07-01 22:45:18.634 GMT+02:00 I BaseJob: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2020-07-01 22:45:18.634 GMT+02:00 I BaseJob: 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
2020-07-01 22:45:18.634 GMT+02:00 I BaseJob: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2020-07-01 22:45:18.634 GMT+02:00 I BaseJob: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2020-07-01 22:45:18.634 GMT+02:00 I BaseJob: 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
2020-07-01 22:45:18.634 GMT+02:00 I BaseJob: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2020-07-01 22:45:18.634 GMT+02:00 I BaseJob: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127)
2020-07-01 22:45:18.634 GMT+02:00 I BaseJob: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2020-07-01 22:45:18.634 GMT+02:00 I BaseJob: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2020-07-01 22:45:18.634 GMT+02:00 I BaseJob: 	at org.thoughtcrime.securesms.net.UserAgentInterceptor.intercept(UserAgentInterceptor.java:20)
2020-07-01 22:45:18.634 GMT+02:00 I BaseJob: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2020-07-01 22:45:18.634 GMT+02:00 I BaseJob: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2020-07-01 22:45:18.634 GMT+02:00 I BaseJob: 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)
2020-07-01 22:45:18.634 GMT+02:00 I BaseJob: 	at okhttp3.RealCall.execute(RealCall.java:93)
2020-07-01 22:45:18.634 GMT+02:00 I BaseJob: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.uploadToCdn0(PushServiceSocket.java:1144)
2020-07-01 22:45:18.634 GMT+02:00 I BaseJob: 	... 7 more
2020-07-01 22:45:18.634 GMT+02:00 I BaseJob: Caused by: java.net.SocketException: socket is closed
2020-07-01 22:45:18.634 GMT+02:00 I BaseJob: 	at org.conscrypt.ConscryptFileDescriptorSocket$SSLOutputStream.write(ConscryptFileDescriptorSocket.java:630)
2020-07-01 22:45:18.634 GMT+02:00 I BaseJob: 	at okio.Okio$1.write(Okio.java:79)
2020-07-01 22:45:18.634 GMT+02:00 I BaseJob: 	at okio.AsyncTimeout$1.write(AsyncTimeout.java:180)
2020-07-01 22:45:18.634 GMT+02:00 I BaseJob: 	... 39 more
```

### Video and debug logs

A video is available here, note that my 4G subscription is capped at 1 Mbps upload: https://caprioli.se/d/signal/VID_20200701_224444.mp4

Debug logs: https://caprioli.se/d/signal/debug.txt

### Device info

**Device:** Motorola Moto G8 Power (Also confirmed on multiple other Android phones)
**Android version:** 10 (Also confirmed on Android 7 and 9)
**Signal version:** 4.64.7

**Comment by petcap** [comment] 2020-07-01 21:12
Increasing the relevant timeout will most likely resolve this issue. In LTE, latency tends to get very high when fully utilizing the connection speed. This is due to how LTE queues data. I've seen latencies go up to 15-20 seconds in some cases.

**Comment by navid-zamani** [comment] 2020-07-07 09:29
I get maybe the samer error, but am not sure.
I’m on a throttled mobile connection (8kB/s) for half of every month, and since the last updates (~1-2 weeks ago?), I cannot upload images or longer audio messages anymore.

It just instantly shows ~20-25% done, and data rates jump to a impossible 25kB/s (as I said: it's an 8kB/s throttled connection!), and this 20-25% flickers every n seconds, as if it cancels and retries.

And it keeps doing that *forever*. Transferred 600MB (!!!) over said throttled 8kB/s connection this night! Could have drained my battery all by itself! Clearly completely unaccaptable.
And the worst part is, that deleting the message, and even closing Signal in the task switcher does not seem to stop it. Hell, I think not even force-closing/killing it, stops it. You also have to turn off mobile data, wait, and turn it back on. Even one of the previous steps forgotten, and if you re-open Signal, the impossible 25kB/s start again.

So of this isn the one you are describing, this really is a quite urgent bug.
An unlucky person who pays per kB, or relies on his battery not being drained, might have quite a bad time.

**Comment by navid-zamani** [comment] 2020-07-07 09:57
I can confirm now, that forcing your phone to 3G is a functioning workaround. Albeit multiple messages, being transferred in parallel to avoid stalling, causing latencies still to be high or even above the timeout. So it still won't work, if multiple ”bigger“ messages got queued up.

I think simply raising the timeout won't solve the underlying issue, as long as parallel transfers (from Signal, but even from e.g. Play Store updates in the background, or web browsing) can still cause very long delays.

A better solution might be, to set the size of the transferred segments relative to the real available bandwith, so the timeout can stay fixed, and Signal will just retry with a smaller segment, if the e.g. 8kB/s get bogged down to 3kB/s by two web surfing related transfers.
If the bandwith is something ridiculous, like 300 baud acoustic coupler speeds, then it should just not transfer at all, and wait until a faster rate is available. Ideally with a small "Your connection is currently too slow (30B/s). Waiting for a faster connection." message at the bottom (of the message itself, or the chat window).

Making that timeout and lower limit (for when to just wait) configurable, would be welcome. (Say, adding a ”[Change lower limit]“ button to the above message, that then shows the settings, where there would be a slider, to set the lower limit to anything between 300b/s and just shy of 1Mb/s. That way you can set the default lower limit higher, and not bother the network with small segments, unless the user actually needs it.)

**Comment by navid-zamani** [comment] 2020-07-07 10:04
An additional note:  I used LTE with Signal for a year now. This did not happen, even on LTE, until recently. I switched phones in that time, and sadly updated my OS to Andoid 10, so it might be new since Android 10, or due to my phone being different. In any case, it does not happen for all people with LTE.

**Comment by petcap** [comment] 2020-07-07 10:07
> I can confirm now, that forcing your phone to 3G is a functioning workaround.

This is because 3G handles packet queuing differently and does not reach the same latency levels under load. Try pinging google.com when uploading a large file on 3G and LTE, your latency will be drastically higher on LTE.

> I think simply raising the timeout won't solve the underlying issue

I haven't dug down into the Signal code, but under the assumption that an attachment upload fails after N seconds if no data is transferred over the TCP connection, then increasing the timeout would resolve this issue, even for parallell uploads. In my experience working with data intensive applications in LTE, around 90 seconds is generally a good timeout.

> Ideally with a small "Your connection is currently too slow (30B/s). Waiting for a faster connection."

Sorry, but I think this sounds like a bad idea. Even if you're on a very slow connection (like 5 KB/s), you should still be able to send attachments, even if it takes 10 minutes.

**Comment by navid-zamani** [comment] 2020-07-07 22:51
> if no data is transferred over the TCP connection, then increasing the timeout would resolve this issue, even for parallell uploads.

Aah, *then* increase it. Yes, that sounds reasonable. I had assumed the timeout was a static global setting, not an adaptive one.

> Sorry, but I think this sounds like a bad idea. Even if you're on a very slow connection (like 5 KB/s), you should still be able to send attachments, even if it takes 10 minutes.

Yes, definitely. This is why I also said there should be a [Change lower limit] button right next to that message, and thst it should (only) stop after a long timeout, not right away, where right now it just infinitely fails.
Nobody by default wants to drain 8 hours of battery to get something through. :) For nearly every case, it is nicer to ask first.

**Comment by petcap** [comment] 2020-07-08 18:49
> Aah, then increase it. Yes, that sounds reasonable. I had assumed the timeout was a static global setting, not an adaptive one.

Well, that's actually not what I meant. They just need to increase the timeout, period.

It looks like it's set to 30 seconds right now: https://github.com/signalapp/Signal-Android/blob/master/libsignal/service/src/main/java/org/whispersystems/signalservice/internal/push/PushServiceSocket.java#L208

However, when digging in the commit history, I found this: https://github.com/signalapp/Signal-Android/commit/2afb939ee6fc7d33526877aab16ee7eb4fd93278. It seems they are already implementing a new upload service with resumable upload support. I guess that would resolve this issue as well.

**Comment by navid-zamani** [comment] 2020-07-25 15:08
> Well, that's actually not what I meant. They just need to increase the timeout, period.

Well, as I said, that would not fix the problem. Only lower the count of people and situations for which it would still be fully broken. :/

> It seems they are already implementing a new upload service with resumable upload support. I guess that would resolve this issue as well.

Is there a schedule on this V3? (I'd switch to beta, if it is available there ...)

> Then again, just increasing the timeout to 90-120 sec would be a quick fix until V3 upload support is ready.

Only if I upload just one thing at a time and the connection is perfect.

**Closed** 2022-01-31 08:47 UTC
Labels: wontfix
