### ISSUE TITLE
Excessive data usage

### ISSUE THREAD

**Issue by jsoendermann** [signalapp/Signal-Android#7608] opened 2018-04-03 09:07 UTC
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal uses up exorbitant amounts of data. This seems to be the same bug as #6914. It appears on both mine and my friend's phone. We both have Google Play installed, don't make calls, don't use gif search or transmit any other kind of large media files.

This bug makes the app completely unusable for me since it cost me 60 Euros in data fees last month and has already used up all my data for this month.

![whatsapp image 2018-04-03 at 10 58 09](https://user-images.githubusercontent.com/3524691/38240039-b020036e-372e-11e8-975b-4d5773b292df.jpeg)
![img_2527](https://user-images.githubusercontent.com/3524691/38240040-b03f5b9c-372e-11e8-9c6a-c12c65c05705.png)

**Comment by sampablokuper** [comment] 2018-04-03 09:33
Possible duplicate of #7602 (no doubt due to the deeply misguided #7598).

**Comment by moxie0** [comment] 2018-04-03 10:32
@jsoendermann Please always include a debug log. I am unable to reproduce this issue, so I'll need something to go on.

**Comment by sampablokuper** [comment] 2018-04-03 10:38
@moxie0 there is already a debug log in the duplicate that I linked above, and also in the original issue that this one and that one both stem from (#6914), that was arbitrarily closed and locked due to #7598. Please can you intervene and roll back #7598 so that comprehensibility can be restored to the Signal bug tracker? Thanks.

**Comment by skorokithakis** [comment] 2018-04-03 11:04
I am also affected by this and available to troubleshoot. Disallowing background data seems to mitigate this (obviously), but then signal doesn't work (also obviously).

**Comment by Trolldemorted** [comment] 2018-04-03 11:24
@skorokithakis debug log?

**Comment by skorokithakis** [comment] 2018-04-03 11:28
@Trolldemorted #7602

**Comment by Trolldemorted** [comment] 2018-04-03 13:10
What happened to the linefeeds? And it is pretty short :|

**Comment by skorokithakis** [comment] 2018-04-03 13:11
I'm not sure, I pressed "send debug log" and that's what it gave me :(

**Comment by prototaxites** [comment] 2018-04-03 14:48
Also having a similar issue; Signal seems to have used ~1.1GB of my mobile data at 00:00:00 on 03/04/18, according to my phone provider. I am running Signal Beta on a Oneplus 3T running LineageOS 15.1 with no GAPPS (microG enabled and Signal registered with GCM). Looking at my chat history, I was making a video call somewhere during this time, but I was connected to WiFi and I'm pretty sure an hour-long call shouldn't use 1GB of data?

This is my debug log, but I'm not sure how much use it will be as it doesn't seem to cover the timeslot in question: [](https://debuglogs.org/194c24bb86852f649ac4672c44842b6600dc8c250d45f5890d6730e8b9fcb12e)

**Comment by moxie0** [comment] 2018-04-03 14:57
@skorokithakis There's nothing really in that debug log. You could try using `adb logcat` with Signal in the background to see if there's any activity.

In general, though, Signal doesn't do anything in the background unless it receives a GCM notification, at which point it simply retrieves the message.

There are exactly 4 periodic tasks:

1. APK update task (for non-play distribution APKs only). Happens once every 6 hours. Should only be a single small network request.
1. Local backup (if backups are enabled). Happens once a day. Should not require any network access.
1. Rotate signed prekey. Happens once every 2 days. Should only be a single small network request.
1. Directory update. Happens every 12 hours. The largest of the periodic requests, but only one.

The only other thing Signal *can* do in the background is the sync adapter, which runs whenever Android tells it to run. This is not defined, but it should roughly correspond to changes in the Android contact database. If there are no changes, it should only run very occasionally.

Possibilities that I see right now:

1. Anything involving LineagoeOS, microG, or any of that hacky stuff... who knows. None of that stuff seems to work very well, so there are often too many variables.
1. The Android OS is not reporting data usage correctly.
1. Android is running the sync adapter too often, and we should manually throttle it.

I think the most straightforward thing would be for someone affected by this to look at the activity on their network and see if Signal is doing something while in the background. And if so, what.

**Comment by skorokithakis** [comment] 2018-04-03 15:01
Hmm, the sync adapter made me wonder: I'm using DavDroid (which syncs contacts to my own server), is anyone else affected by this bug using it (or something similar)?

The heavy data usage is also happening when I'm on wifi, I see 1 GB of data on wifi as well, so I assume I can take a look at the network at some point and see what's going on.

**Comment by moxie0** [comment] 2018-04-03 15:24
@skorokithakis Sounds like a promising lead. When Signal's sync adapter is run, you should see that in logcat as well.

**Comment by skorokithakis** [comment] 2018-04-03 15:29
Ah, is there something I can filter for to get all the relevant messages?

**Comment by skorokithakis** [comment] 2018-04-03 15:33
I also saw something else in the logs, which is probably unrelated, but I figure I should mention it: Is anyone else using the Keepass2Android Autofill Helper? I think this problem started right about when I installed that.

**Comment by skorokithakis** [comment] 2018-04-30 23:55
I have uninstalled the Autofill Helper and the problem persists. Still not sure exactly how to debug it, I didn't see anything in the logs at first glance.

**Comment by moxie0** [comment] 2018-05-03 08:58
DavDroid seems like a much more likely culprit to me.

**Comment by skorokithakis** [comment] 2018-05-03 08:59
Is there a way I can debug it to make sure? I had a look at the logcat but nothing odd turned up.

**Comment by greyson-signal** [comment] 2018-10-07 16:15
If DavDroid was the problem, this should have been resolved by bf692e8da354d3bfd44fe85fb3abb3cadec5e857, which throttles the contact sync operation to once every 6 hours. Please re-open if it's still an issue. Thanks!

**Closed** 2018-10-07 16:16 UTC

**Comment by skorokithakis** [comment] 2018-10-08 00:30
I configured DavDroid to only sync on wifi and this problem largely went away. Hopefully this workaround mitigates the situation further, thank you.

**Comment by a-d-v-e-n-t-u-r-o-u-s** [comment] 2020-02-03 19:01
Hello, today I've find out that I've experienced this behavior, can you please tell me should I post full debug report here or should I open new issue ?
