### ISSUE TITLE
User still receiving messages after leaving a group

### ISSUE THREAD

**Issue by tfc** [signalapp/Signal-Android#8892] opened 2019-06-25 18:05 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

We have a work related signal group with all colleagues. One colleague left the company and hence left the signal group. Now he is *still* receiving messages *sometimes* from my signal account, but not from any other group member.

### Steps to reproduce

I am completely unsure how to reproduce this, but it looks like someone has to leave a signal group and then sometimes some people will still receive messages from some group members, so:

1. Leave a signal group.

**Actual result:** 

2. Still receive some messages from a limited set of group members.

**Expected result:**

2. Receive no messages from a group any longer that you have left already.

### Screenshots

![Point Blur_Jun252019_195042](https://user-images.githubusercontent.com/29044/60121204-da912a00-9782-11e9-8f00-529c651a188d.jpg)

### Device info

I am not sure which device info is relevant? 

- The ex-group-member still receives some of *my* messages (but not from other group members). My device info is:

**Device**: ZTE Axon 7 (A2017U)

**Android version**: 8.1.0 (LineageOS 15.1-20190517-NIGHTLY-axon7)

**Signal version:** 4.42.2

- His device info:

**Device**: GT-I9195

**Android version**:7.1.2 (LineageOS 14.1-20180629-UNOFFICIAL-jactivelte)

**Signal version:** 4.41.6

### Link to debug log

We are waiting for it to happen again to provide fresh logs and will post them then.

**Comment by mejo-** [comment] 2019-07-31 13:46
I just discovered a similar issue: even two months after a group member left the group, she still receives messages from the desktop client of one particular other group member. Messages from the main client (Android) aren't received by the unsubscribed member, just messages sent from the desktop client. So apparently the desktop client didn't get the notifiaction about the unsubscription.

That's a very unfortunate bug due to its security/privacy implications: in Signal groups where members left, I cannot be sure that these former members no longer receive the group messages.

**Comment by relikd** [comment] 2020-01-09 02:26
This is a logical bug and not OS specific. Have this reproduced on a couple of Android and iOS devices including Desktop versions. The full report is listed in my iOS bugreport https://github.com/signalapp/Signal-iOS/issues/4357

**Comment by Sgn-32** [comment] 2021-05-04 16:46
Should be resolved with the introduced "New groups". The groupsv2 are preventing asynchronous group member lists.

**Closed** 2022-02-02 13:08 UTC
Labels: wontfix
