### ISSUE TITLE
"Background connection enabled" displayed with wrong picture

### ISSUE THREAD

**Issue by JulienPalard** [signalapp/Signal-Android#7765] opened 2018-05-05 16:42 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

### Bug description

Picture for the "Background connection enabled" and "Unread messages" are identical. Having both use the same picture make them indistiguisable, so we're constantly thoughing "Hey I've got a message" "Oh now, it's just the background connection".

### Steps to reproduce
- Drop GCM
- Start Signal
- Look at the always-present "Background connection enabled" notification.

**Actual result:** Looking at the "Background connection enabled" we though "Hey a message!"
**Expected result:** Looking at the "Background connection enabled" we should though "Hey signal is connected".

### Device info
**Device:** Nexus 6P
**Android version:** 8.1.0 (LineageOS 15.1)
**Signal version:** 4.18.3

**Comment by p4nci** [comment] 2018-05-08 05:47
this is duplicate of https://github.com/signalapp/Signal-Android/issues/7255. There is also a PR (https://github.com/signalapp/Signal-Android/pull/7336) to fix this.

@milesmcc could you "finish" the PR? Imo, there are all needed info.

**Closed** 2018-05-08 07:57 UTC

**Comment by milesmcc** [comment] 2018-05-09 15:58
On it, @p4nci! Thanks.
