### ISSUE TITLE
Cannot link previously linked/unlinked devices  - QR Scanner not working

### ISSUE THREAD

**Issue by MichaelTS52** [signalapp/Signal-Android#11926] opened 2022-01-26 15:34 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------
### Workaround found:
- This suggested workaround solved my issue: [#5743](https://github.com/signalapp/Signal-Desktop/issues/5743)
- Cannot link device on desktop version 5.29.1 -> install and link to v.5.27.1 and then update.
- Sorry if this is incorrect but posting as an issue here also as I imagine this may be a wider issue as I am continuing to have problems with linking to IOS, however it was PC I was primarily concerned with. 

### Bug description
Recently did fresh install of windows and so re-installed signal desktop app and unlinked computer to relink to new install.

However I cannot re-link to desktop or ipad after unlinking from phone. QR preview is visible but scanning appears to do nothing, does not recognise signal QR or other random QR.

Initially thought this was a signal QR reader problem just with desktop as ipad initially linked straight away but after unlinking, it will also not re-connect.

Scanning with third party QR app gives string 
 - sgnl://linkdevice?uuid=XXXXXXXXXXXXXXXX...&pub_key=XXXXXXXXXXXXXXXXX... (desktop qr) 
 - tsdevice:/?uuid=XXXXXXXX...&pub_key=XXXXXXXXXXXXXXXXXXX... (ipad qr)

### Related tracked issues and attempted solutions:
**Signal-Android**
- [#11414](https://github.com/signalapp/Signal-Android/issues/11414)
    -  printing out or screenshot and zoom in
    - encoding above strings into another qr code
    - scanning in landscape mode
- [#11901](https://github.com/signalapp/Signal-Android/issues/11901)
    - scan from further away...
- [#4637](https://github.com/signalapp/Signal-Android/issues/4637)
    - suggest camera not in focus - other qr apps work and ipad worked initially
    - also very outdated issue potentially specific to samsung galaxy S2
**Signal-desktop**
- [#2211](https://github.com/signalapp/Signal-Desktop/issues/2211)
    - suggests using developer console - since removed from signal desktop

Additionally I have tried:
- uninstalling and reinstalling singal app from all devices
- deleting and remaking my account via android app
    - in my frustration I forgot to backup before doing this 
- 

### Steps to reproduce
- Cannot reconnect so have only been able to reproduce once per device tried (desktop + ipad)
- Link signal android to signal desktop or ios
- remove linked device from phone
- attempt to re-link device

**Actual result:** Stuck on QR scanner - no evident attempted scan/connection or problem.
**Expected result:** Phone should link to device being scanned

### Device info

**Device:**OnePlus6 A6003
**Android version:**OxygenOS 11.1.2.2
**Signal version:**5.28.10
**Signal IOS version:**5.26.10
**Signal desktop version:**5.29.1
**Desktop OS:**Win10 v.10.0.19044

### Link to debug log

https://debuglogs.org/f5f113d75d61ac7663f16cf5f43d2976cccab698f2e8ef23c78f2e2ada3c699c

**Comment by stheid** [comment] 2022-05-27 21:18
I have the same issue on iodé OS (linage+microg) on my fairphone 4.

I can also scan the QR codes without any issue on other scanning apps on the same device.

**Comment by stheid** [comment] 2022-05-28 14:47
# Workaround
@cody-signal  I have the suspicion that [my issue is a](https://community.iode.tech/t/signal-cant-link-devices-a-camera-issue/552/5?u=chinchillo) regression error.
[5.39.3](https://signal.org/android/apk/) -> works fine
5.40.0 -> qr code cant be read

**Comment by cody-signal** [comment] 2022-05-30 14:38
@stheid can you submit a debuglog running 5.40?

**Comment by stheid** [comment] 2022-05-30 15:02
i am not that eager to reinstall the broken version again. i am afraid to loose messages in the process. If it is not reproducible on your side i could do it though.

**Comment by cody-signal** [comment] 2022-05-30 17:25
I don't have a Fairphone and the scanning works fine on my test devices. I'm able to get a scan from a few feet away with the phone moving without issue.

**Comment by stheid** [comment] 2022-05-31 11:11
maybe this issue can be closed as duplicate of #7967 In the issue there it was already reproduced and there was a debug log provided. If more data is needed i can assist, but i have the impression that it is a general problem as it happens on different devices with different OSs

**Comment by greyson-signal** [comment] 2022-05-31 14:34
Merging into #12009, which is where most of the chatter seems to be.

**Closed by greyson-signal** 2022-05-31 14:34 UTC
