### ISSUE TITLE
Select -> Unselect all keeps Chat Bubbles moved

### ISSUE THREAD

**Issue by MorgeMoensch** [signalapp/Signal-Android#12568] opened 2022-10-31 19:16 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After unselecting all bubbles in a chat, the bubbles are still moved to the right instead of moved back to where they belong. When scrolling, new bubbles are placed correctly.

### Steps to reproduce
- enter chat
- select one or multiple messages
- unselect all

**Actual result:** Chat Bubbles stay aside
**Expected result:** Chat Bubbles move back to the left

### Screenshots
Chat upon entering:
![Screenshot_2022-10-31-20-08-18-39_4b14b257287ac0a6d1fd5fbb2487716f.jpg](https://user-images.githubusercontent.com/62468040/199091044-e3b7d8f4-9ae1-4b8d-ae6e-88a3b7f52556.jpg)

Selecting a bubble:
![Screenshot_2022-10-31-20-08-23-06_4b14b257287ac0a6d1fd5fbb2487716f.jpg](https://user-images.githubusercontent.com/62468040/199091085-afbefb05-4b2a-4cb4-833a-ac586d464899.jpg)

After unselecting all:
![Screenshot_2022-10-31-20-08-26-72_4b14b257287ac0a6d1fd5fbb2487716f.jpg](https://user-images.githubusercontent.com/62468040/199091190-2dce9a6c-dbc7-4698-9b5f-70d7c2b48af2.jpg)

### Device info

**Device:** OnePlus 8T
**Android version:** 12
**Signal version:** 5.53.8

**Comment by cody-signal** [comment] 2022-11-01 12:52
I can't reproduce this, does this happen every time for you? It may have been fixed in the latest beta too.

**Comment by MorgeMoensch** [comment] 2022-11-02 05:31
Yes, it happened every time.

But you're right, it seems to be fixed in 6.0.1 on my other device.

**Comment by MorgeMoensch** [comment] 2023-01-01 11:18
It still happens on the OnePlus 8T with Android 13 and Signal 6.6.3.
On a Samsung Device however, it does not occur on Signal 6.6.3.

**Comment by MorgeMoensch** [comment] 2023-03-03 19:47
Still happens with Signal 6.12.6

**Comment by MorgeMoensch** [comment] 2023-05-02 20:13
Still happens on 6.18.4

**Comment by MorgeMoensch** [comment] 2023-09-05 05:55
Still happens with 6.30.4

**Closed** 2023-09-12 07:39 UTC
Labels: wontfix

**Comment by MorgeMoensch** [comment] 2023-09-12 08:01
Stale-bot, seems like something didn't work right. The issue still occurs
