### ISSUE TITLE
Bombing notifications after re-connecting to the network

### ISSUE THREAD

**Issue by dr47** [signalapp/Signal-Android#8648] opened 2019-03-01 11:18 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If phone connect to the network and there are many messages in the queue, each new message invokes a separate notification and the phone is overwhelmed and unusable for some time.

### Steps to reproduce
- disable network connection.
- send many messages to yourself (from another account)
- enable network connection.

**Actual result:** A new notification will be displayed for each new message in the queue. For example, if in the queue is 30 new messanes, the phone vibrates and beeps for 30s (1s for each notification)
**Expected result:** One notification: "You have 30 new messages", etc....

### Device info

**Device:** Nexus 5X
**Android version:** 8.1.0
**Signal version:** 4.34.8

**Comment by hhenkel** [comment] 2019-03-02 16:04
I see a similar behavior between the two devices of my parents once they enable wifi, both devices get flooded by messages about a "wrongly encrypted message". The phones are connected to the wifi for around 10 minutes now and I already saw over 500 messages and new messages are still showing up. Both devices are on the signal version 4.34.8, one Device is a Samsung S8 with Android 8.0.0, the other device is a Galaxy S5 Neo with Android 6.0.1.

**Comment by greyson-signal** [comment] 2019-03-03 08:50
Duplicate of #8445

**Closed by greyson-signal** 2019-03-03 08:50 UTC

**Comment by RalfJung** [comment] 2019-08-08 06:17
@greyson-signal I don't think this is a duplicate. At least that other issue says it is specifically about messages that are "already read in the desktop app". But the issue here (which I am also affected by) is for when you e.g. have both your phone and your laptop turned off or at least offline for the night, then get your phone connected the next morning -- and then for a solid minute, it just keeps vibrating / playing the notification sound because it insists on doing that individually for each of the 40 messages that came in. These messages are all new, but it doesn't help to make my phone annoy me for one minute without pause. That's a pretty bad user experience.

**Comment by ZwergNaseXXL** [comment] 2022-03-12 16:45
Closed? This is still happening and rather annoying. As RalfJung says, not a duplicate.
