### ISSUE TITLE
MMS failure after Verizon phone switch

### ISSUE THREAD

**Issue by metsuke0** [signalapp/Signal-Android#8565] opened 2019-01-26 04:58 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
My two Verizon phones do not receive MMS messages correctly.  I had a Pixel XL, and Signal worked well in every aspect including MMS message sending and receiving.  I transferred the Pixel XL to my wife and I purchased a different phone.  After the transfer, neither phone would receive MMS message correctly.  Upon receiving an MMS message, an entry would be displayed saying "Error downloading MMS message, tap to retry".

I've gone through the MMS Troubleshooting page to the best of my ability to no avail.  For now, we must use a different messaging app since we _require_ MMS to work both for personal and business use, regardless of the reason why it doesn't work.

### Steps to reproduce
-Send MMS message from a non-Signal phone to one or both of the Signal phones.

**Actual result:** MMS message shows the error shown in the Screenshot
**Expected result:** MMS message can be read

### Screenshots
![screenshot_mms](https://user-images.githubusercontent.com/17973793/51782740-81916d00-20e2-11e9-857b-7055d2608a27.png)

### Device info

**Device:** Pixel XL
**Android version:** 9
**Signal version:** 4.32.8
**Device:** Sony Xperia XA2 (Sony H3123)
**Android version:** 8.0.0
**Signal version:** 4.32.8

### Link to debug log
https://debuglogs.org/0faef9882a7eb25307a9de1332c9238afefdc3f8071c6a8e0afa32ad1b4363e9

**Comment by dylskiMarcin** [comment] 2019-02-12 16:18
Duplicate of #8571

**Comment by CueHD** [comment] 2019-03-12 15:41
Based on the screenshot, you are not connected to the Verizon data network. As far as I can tell, Verizon only sends MMS through it's own data network, it does not send them through WiFi. Try turning off WiFi to see if that allows you to receive the MMS. If so, there is likely a setting that was correct in your old phone that needs to be changed back to allow simultaneous 3G/4G connection and WiFi.

**Comment by dylskiMarcin** [comment] 2019-03-14 11:49
@CueHD according to user description other apps are working correctly.

**Comment by CueHD** [comment] 2019-03-14 12:46
Some other messaging apps do transfer the MMS over WiFi. Specifically, Verizon's own "Verizon Messages" or "Message+" are able to retrieve over WiFi because the MMS is first transferred to Verizon's servers and is then pushed to their apps. I'm not certain, but I think that Google's "Android Messages" also can work this way.

**Comment by metsuke0** [comment] 2019-03-15 04:14
FWIW I've tried MMS on wifi and off wifi on both my Pixel and Sony Xperia XA2

**Comment by CueHD** [comment] 2019-03-20 18:10
It turns out I was wrong about Verizon not sending MMS over WiFi. When I turn "Airplane mode" on then turn WiFi back on, MMS sends and receives very fast. See if that changes the MMS behavior on your phone.

I think that Signal tries to always send over the mobile network if it is turned on even if the connection is poor.

My phone settings have WiFi calling enabled and Signal settings have "WiFi calling compatibility mode" enabled.

**Comment by schlomie** [comment] 2019-03-28 19:56
If I may add another anecdote.  I've been a long time Signal user as my primary SMS/MMS app.  Everything has always worked very well (also on Verizon.)

Recently I upgraded to a OnePlus 6T, which on Verizon had to be provisioned as an LTE only device.   3g/CDMA no longer works.

Since this upgrade, Signal no longer receives MMS - either with attachment or Group Messaging - from non-Signal users.  It does not matter what selection of options I toggle, be it WiFi calling, airplane mode, with Wifi turned on or anything else.   MMS messages always end up with "Error downloading MMS message, tap to retry"

SMS still works fine.  Sending MMS (with attachment) works (at least to a single recipient.)

Other apps, Stock Messaging and Textra work fine with MMS, able to both send and receive, so APN settings are in fact correct.

I wonder if Signal is attempting to use 3g on Verizon, which for this phone is no longer an option.

If in fact this is the reason MMS no longer works, it will be important to note that Verizon has goals of completely turning off their CDMA network by the end of this year and very likely any/all Verizon Signal users will be affected.

**Closed** 2022-02-04 13:14 UTC
Labels: mms, wontfix
