### ISSUE TITLE
Impossible to forward image as MMS

### ISSUE THREAD

**Issue by manuc66** [signalapp/Signal-Android#9630] opened 2020-05-16 14:00 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Impossible to forward by MMS an image recieved from Signal. 

If the picture comes from a conversation or saved from a conversation, the bug is present. But if I choose a picture that was taken by my device I have no problem. 

### Steps to reproduce
- choose a conversation with an image received by Signal
- tap on the image
- on the top right menu, choose forward
- try to send

**Actual result:** A delivery error occurs, retrying won't work. Recipient Don't received anything 

**Expected result:** A successful sent MMS

### Device info

**Device:** Samsung Galaxy A70 - SM-A705FN
**Android version:** 10
**Signal version:** 4.59.9

### Link to debug log

https://debuglogs.org/ef9d0869f01e41bd1100c63ea7b5ac42815f9d46f6506554ce88241847bdefc5

**Comment by UserX404** [comment] 2020-05-18 04:50
Looks like a duplicate of #9618 
`MmsSendJob: org.thoughtcrime.securesms.transport.UndeliverableMessageException: Both lollipop and legacy connections failed...`

**Comment by manuc66** [comment] 2020-05-18 07:17
@UserX404 I did post a new issue because I'm usually able to send picture taken from my phone but not forwarding them

**Comment by UserX404** [comment] 2020-05-18 09:12
@manuc66 
I don't remember if the picture in my issue-debuglog was forwarded and i also didn't check if it's specific where the picture comes from. But i'm pretty sure I tried both. Forwarding a picture from a signal-chat and picking one from the gallery. 
The lines in the debug log leads me to the assumption that it is a APN problem.

**Comment by manuc66** [comment] 2020-12-25 13:13
Hi @UserX404 wgat do you mean by APN ?

Here is another debug log from today: https://debuglogs.org/09f7de0afe9d5979b602741b436fed84e3219d4d40dfcb95d4041bd3b6662bca

**Closed** 2022-02-03 13:25 UTC
Labels: wontfix
