### ISSUE TITLE
invalid user phone number +2250XXXXXXX

### ISSUE THREAD

**Issue by guychou7** [signalapp/Signal-Android#10737] opened 2021-01-19 15:33 UTC
- [ ] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Registration alert (invalid user phone number) when phone number start by 0 after country code
sample: +2250XXXXXXX --- becomes ---> +225XXXXXXX 

### Steps to reproduce
it's my fisrt use after app installation
- open app
- click on Continue
- enter phone number : 0XXXXXXX (in my case 08893176)
- click on Next

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Screenshots

![Screenshot_20210119-153120_Signal](https://user-images.githubusercontent.com/16904408/105056667-61e07580-5a6c-11eb-81e7-d327c0289942.jpg)
![Screenshot_20210119-153109_Signal](https://user-images.githubusercontent.com/16904408/105056702-69a01a00-5a6c-11eb-8d1b-2ba2e9d8e9e1.jpg)

### Device info

**Device:** SAMSUNG S8 SM-G950FD
**Android version:** 5.2.3
**Signal version:** 0.0.0

**Comment by Sgn-32** [comment] 2021-01-19 19:12
There is this "solution" on the community website:

https://community.signalusers.org/t/unable-to-register-in-ivory-coast-or-congo/20001/14

**Comment by Genis-Sage** [comment] 2021-01-19 20:42
Also duplicate of  #10632

**Comment by Leptopoda** [comment] 2021-01-22 11:46
also should be fixed by 
https://github.com/signalapp/Signal-Android/commit/893749fcab65135e28cc09093f34cbe9d08d1018
this could be closed now

**Closed** 2022-02-03 05:47 UTC
Labels: wontfix
