### ISSUE TITLE
Receiving Signal call (incl missed) marks messages read

### ISSUE THREAD

**Issue by Hooloovoo** [signalapp/Signal-Android#7896] opened 2018-06-14 08:54 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If I have unread messages in a conversation and that person calls me, all unread messages are marked as read (blue check marks). This actually caused us a real issue, as the person was calling me to check I had seen the message and then stopped trying once the messages were marked as read.

### Steps to reproduce
- Send messages from phone A to phone B (phone B has screen off and is untouched through process). These messages are shown as unread.
- Signal Call phone B from phone A.
- Do not touch phone B or answer the call. Stop calling from phone A.
- The messages are now shown as read (blue check marks).

**Actual result:** Messages are marked read.
**Expected result:** Messages should not be marked read until the conversation is opened on phone B.

### Device info

**Device:** OnePlus 3T
**Android version:** 8.0.0
**Signal version:** 4.20.7

Also tested in both directions with another OnePlus 3T and a Samsung S8.

### Link to debug log
https://debuglogs.org/72ae8fa7a3a4f71014ee02bbee433ce10d038c21c676f9c68f788a4970659532

**Comment by 2-4601** [comment] 2018-06-14 10:33
Duplicate of or related #7641

**Comment by Hooloovoo** [comment] 2018-06-15 08:12
Thanks @2-4601 -- well done. I spent ages reviewing potential duplicates, but that didn't have "read receipt" in it (because it is typoed to "read reeipts") and searching for "call" or "read" returned too many to review.

**Closed** 2018-06-15 08:12 UTC
