### ISSUE TITLE
Images are altered when sent as "File"

### ISSUE THREAD

**Issue by circledot** [signalapp/Signal-Android#7865] opened 2018-05-30 17:28 UTC
If a pic is sent via File, the EXIF data is stripped and the filename extension is changed from ".jpg" to ".jpeg". Binary files should not be modified.

Imo, binary files (including pics) should only be auto-modified based on personal settings.

**Comment by jlund-signal** [comment] 2018-05-30 17:49
Dupe of #7862.

**Closed by jlund-signal** 2018-05-30 17:49 UTC

**Comment by Aerilius** [comment] 2023-12-19 19:15
Sorry for reviving an old topic. But I have difficulties understanding whether/why this is a really a duplicate of #7862.

- #7862 is about photos being sanitized (besides compression), and potential addition of a user option.
- #7865 is about files (which are pictures) not being sent as is.

The linked issue is closed and refers to a fizzled-out discussion about the photo sanitization. I don't see it enough respected or discussed that for certain use cases, files with missing metadata can be considered damaged. 

## Use case

Specifically, when friends who are not the threat share photos, the photo does not sort properly in time and space in a professionally managed photo collection.

## Relevance

Nowadays, large parts of Signal's user base give importance to privacy towards network&trackers, but not their intentional recipient, and their life is not at danger. I have a hard time persuading such people to use signal over other messengers and then persuade them to use Signal not for file sharing. This is a strong counter-argument.
