### ISSUE TITLE
Messages sent to self do not behave consistently

### ISSUE THREAD

**Issue by Trolldemorted** [signalapp/Signal-Android#7631] opened 2018-04-04 12:03 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal-Android displays a message to your self as an incoming and an outgoing message, but does not send the message to synced devices. Signal-Desktop displays the message as an incoming and an outgoing message too, but both messages (original and sync) are properly sent to all sibling devices.

Legacy issue: https://github.com/signalapp/Signal-Android/issues/4844
PRs that would fix this: https://github.com/signalapp/Signal-Android/pull/5905, https://github.com/signalapp/Signal-Desktop/pull/959

### Steps to reproduce
- send a message to yourself on Signal-Android and Signal-Desktop

**Actual result:** The clients behave consistently
**Expected result:** The message from Signal-Android stays on Signal-Android, the message from Signal-Desktop is synced to all siblings

### Device info

**Device:** Redmi Note 3 Pro
**Android version:** 7.1.2
**Signal version:** 4.15.5

### Link to debug log

https://pastebin.com/CgqF02Uk

**Comment by moxie0** [comment] 2018-04-05 11:47
This is currently the intended behavior, so I'm going to close this issue here. Let's move it over to the forums to discuss how a new feature would work, there are a lot of unanswered UX questions in the PR you reference. Thanks!

**Closed by moxie0** 2018-04-05 11:47 UTC
