### ISSUE TITLE
Duplicate emoji in emoji list.

### ISSUE THREAD

**Issue by Edu4rdSHL** [signalapp/Signal-Android#7749] opened 2018-04-30 19:44 UTC
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
In the emoji list there are several repeated emojis.

### Steps to reproduce
- Try to send a emoji from the emoji list
- look carefully at the list

**Actual result:** There are some repeated emojis
**Expected result:** Don't repeated emojis

### Screenshots
![photo_2018-04-30_14-41-37](https://user-images.githubusercontent.com/32582878/39446582-a1bbcf86-4c84-11e8-88db-6d3e9ffcae28.jpg)
![photo_2018-04-30_14-41-33](https://user-images.githubusercontent.com/32582878/39446600-abe285a4-4c84-11e8-8b75-5d7e6ab1c3a7.jpg)

### Device info
**Device:** Samsung Galaxy SM-G570M
**Android version:** 7.0
**Signal version:** 4.19.3

### Link to debug log
I think that it don't need debug log.

**Comment by labdsf** [comment] 2018-04-30 19:56
These are not duplicate, but generic/male/female. The problem is, male and generic are the same. See, for example: https://emojipedia.org/swimmer/ https://emojipedia.org/man-swimming/ and https://emojipedia.org/woman-swimming/

**Comment by Edu4rdSHL** [comment] 2018-04-30 20:04
Thank @labdsf. Anyways i think that *generic* emojis aren't necessary and can cause confusion, Signal is the only app in which I am experiencing that.

**Comment by labdsf** [comment] 2018-04-30 20:13
I would say that "male"/"female" emojis are not necessary and leave the generic one instead. The fact that it is the same image as "male" on most platforms is not the application problem. "Male swimmer" is a combination of "swimmer" and "male sign", after all. Telegram also supports "skin tone" modifiers, available on long press, and Signal doesn't, by the way.

In any case, the problem is identified, do whatever you want and I am going to stick with ASCII emojis.

**Comment by Edu4rdSHL** [comment] 2018-04-30 20:16
@labdsf thank you for explain me. We can wait for the opinions of the developers.

**Comment by johanw666** [comment] 2018-05-01 01:14
How about this flag that is double:
![signal](https://user-images.githubusercontent.com/8427572/39457355-f560116c-4cdc-11e8-8711-7837da2ceedf.jpg)

**Comment by labdsf** [comment] 2018-05-01 12:03
These are https://emojipedia.org/flag-for-us-outlying-islands/ and https://emojipedia.org/flag-for-united-states/

**Comment by link2xt** [comment] 2022-01-29 10:49
This stale bot is annoying, second time it annoys me in a week.

**Comment by alex-signal** [comment] 2022-01-31 14:02
These sheets are auto-generated via a script. I can see what the others think of deduping things but it's likely something we'd need to do manually and might be a pain to maintain. (imagine if they altered some variant to look different from generic, and we'd never really have a way of knowing besides people noticing and complaining.)

**Comment by link2xt** [comment] 2022-01-31 14:19
Non-system NB emojis are grey instead of blue now, so maybe the problem is solved already, at least the original one. No idea about the US flag.

**Comment by alex-signal** [comment] 2022-01-31 14:23
The US flag is actually 2 separate flags for 2 separate places, they just look the same. Since the problem  is solved, I'll close this out.

**Closed by alex-signal** 2022-01-31 14:23 UTC
Labels: emoji
