### ISSUE TITLE
Problems calling a certain contact

### ISSUE THREAD

**Issue by janvlug** [signalapp/Signal-Android#10884] opened 2021-02-01 19:55 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I have problems calling a certain contact. Sometimes Signal does not ring, sometimes it does.

### Steps to reproduce
- call a certain contact (voice call)

**Actual result:** The call is not established.
**Expected result:** A correctly working voice call is established.

### Device info
Time          : 1612208704109
Manufacturer  : HMD Global
Model         : Nokia 4.2
Product       : Panther_00EEA
Android       : 10 (00EEA_2_33E, 00EEA_2_330_SP05)
App           : Signal 5.3.7.1 (780, 78007)

### Link to debug log
https://debuglogs.org/20840925c67cbd6572d5038cf82525685b0e9b69d96dc54e5774b28b650b7a83

**Comment by szotsaki** [comment] 2021-02-02 19:59
Please, look around here: https://github.com/signalapp/Signal-Android/issues/7733. If you think this is a duplicate of either of the listed ones there, please, close this issue.

**Comment by AsamK** [comment] 2021-02-02 20:36
To pinpoint the source of the problem, the debug log of your contact would be interesting, preferably a caller and callee log for the same call.

In your debug log there's just a generic connection failed message after 20 seconds:
```
[5.3.7.1] [56188] 2021-02-01 20:44:07.564 GMT+01:00 I ringrtc::core::connection_fsm: state: ConnectingBeforeAccepted, event: (RemoteIceCandidates)
[5.3.7.1] [56188] 2021-02-01 20:44:07.566 GMT+01:00 I ringrtc::core::connection: ringrtc!	1612208647554	conn -> rtc: ice_candidates(8)
[5.3.7.1] [55688] 2021-02-01 20:44:07.573 GMT+01:00 I JobRunner: [JOB::7ce84180-97a0-40cb-a318-ee16d98ea337][PushProcessMessageJob][4] Job finished with result SUCCESS in 41 ms. (Time Since Submission: 85 ms, Lifespan: Immortal, Run Attempt: 1/Unlimited)
[5.3.7.1] [56179] 2021-02-01 20:44:26.125 GMT+01:00 I ringrtc::webrtc::peer_connection_observer: ringrtc!	1612208666123	rtc -> conn: ice_connection_change(Failed)	0xc6593b458c34567e-1
[5.3.7.1] [56188] 2021-02-01 20:44:26.126 GMT+01:00 I ringrtc::core::connection_fsm: state: ConnectingBeforeAccepted, event: (IceConnectionFailed)
```

**Closed** 2022-02-03 02:22 UTC
Labels: wontfix
