### ISSUE TITLE
Pictures fail to send ,see debug log

### ISSUE THREAD

**Issue by Kage1** [signalapp/Signal-Android#9114] opened 2019-10-20 22:36 UTC
- [x ] I have searched open and closed issues for duplicates

- [ x] I am submitting a bug report for existing functionality that does not work as intended

- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports

- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

When attempting to send a photo to another signal user it issues a error

### Steps to reproduce
- Select existing user
- Select a photo that was taken at an earlier time
- Attempt to send and issues that requires attention is issued

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

The signal install was just backed up and moved to a new device. Photos being sent have been taken with this new device. If I take the photo with signal or crop the photo it'll then send. The debug log is showing file not found.

### Device info
Time         : 1571609980653
Device       : OnePlus ONEPLUS A5000 (OnePlus5)
Android      : 9 (1907311824, ONEPLUS A5000_23_190731)
ABIs         : arm64-v8a, armeabi-v7a, armeabi
Memory       : 49M (35.54% free, 512M max)
Memclass     : 256
OS Host      : rd-build-191
First Version: 549
App          : Signal 4.49.3 (5502)

### Link to debug log

https://debuglogs.org/43134629e2f1b8203b17c57aaa3463491660a4b0a742063c9e59194eb2a2f7e5

**Comment by greyson-signal** [comment] 2019-10-21 04:50
Closing as a duplicate of #9109. Thank you!

**Closed by greyson-signal** 2019-10-21 04:50 UTC
