### ISSUE TITLE
Image Meta Data Removal

### ISSUE THREAD

**Issue by lailauch** [signalapp/Signal-Android#5968] opened 2016-12-17 16:21 UTC
This feature request is for an option to remove meta data from a picture being shared in a conversation to prevent location, device and other key data being shared.

**Comment by 2-4601** [comment] 2016-12-18 00:55
Isn't this how it already is?
I just tested this with three images: a picture taken with the direct camera, another one with the attachment drawer camera and the last one by attaching a picture taken with the system camera. None of them had any metadata.

**Comment by moxie0** [comment] 2016-12-18 02:58
I think it happens incidentally at the moment because of image scaling, but if an image were small enough to be sent without scaling or compression, I'm not sure the metadata would be removed.

**Comment by sweeper3000** [comment] 2016-12-18 05:05
Can confirm, after exporting an image, there is no metadata except for the megapixels and the time it was saved to the device (not capture time).

**Comment by FeuRenard** [comment] 2016-12-19 20:40
I took a small picture and sent it to another phone. I exported the picture on the same phone from which I sent it and the metadata were still there.
So this issue seems valid to me.

**Comment by tomrittervg** [comment] 2017-07-25 13:40
I can confirm that on Android EXIF data is **not** removed in many cases. Including the simplest one of "I'll attach a photo to a group chat."

### Bug description
I sent a photo from my camera to a group chat. I then thought to myself "Does Signal strip EXIF data?" So I asked someone in the group chat to check. They extracted my phone's model, date/time information, and the GPS coordinates from the EXIF data.

### Steps to reproduce
- Send a photo
- Extract EXIF Data

**Actual result:** EXIF Data is maintained when I send a photo
**Expected result:** I would expect Signal to do the 'safe' thing by default which would be at a minimum to strip geolocation data.

Obviously geolocation data is *extremely* sensitive (it's extremely common to take photos in your own home) and in many or most cases one does not want to share their home address with all the individuals one may wish to send a picture to.

### Device info
**Signal version:** 4.8.1

**Comment by FeuRenard** [comment] 2017-08-11 08:12
The code here could be helpful:
https://github.com/openssf/exif-remover-android/blob/master/app/src/main/java/org/openssf/exifremover/MainActivity.java#L119

**Comment by p4nci** [comment] 2017-08-11 09:31
@FeuRenard is this a coincidence? :thinking:  The last committer in that repo is @zanedb. Seems like he/she is ready to contribute here (commented here today, see https://github.com/WhisperSystems/Signal-Android/issues/6520#issuecomment-321734476)

**Comment by FeuRenard** [comment] 2017-08-11 09:59
No coincidence. I read his comment, browsed his Github page and discovered the repository. Thanks for mentioning @zanedb, I didn't think of it but should have done 😇

**Comment by zanedb** [comment] 2017-08-11 14:21
Well, I hope the code can be useful. A few pointers though:
- When I was working on that, I was (and still am, but less so) a pretty inexperienced Android programmer
- The code didn't always work on certain file formats and in certain environments (worked particularily well on JPEG files, but not JPG, which, if I understand correctly, are the same thing (see lines [83](https://github.com/openssf/exif-remover-android/blob/master/app/src/main/java/org/openssf/exifremover/MainActivity.java#L83)-[105](https://github.com/openssf/exif-remover-android/blob/master/app/src/main/java/org/openssf/exifremover/MainActivity.java#L105)
- The code is not particularly well done (see point 1), so if you have any issues/don't understand what I was trying to do please let me know
- If you review [the commit history](https://github.com/openssf/exif-remover-android/commits/master/app/src/main/java/org/openssf/exifremover/MainActivity.java) on that file, I tried it with multiple different libraries, such as it.sephiroth.android.library.exif2.ExifInterface and now, the default Android ExifInterface

**Comment by BHSPitMonkey** [comment] 2017-11-30 06:40
Can any Signal contributors confirm whether or not this idea has the support of the project? This issue is about a year old, and I'm wondering if a PR would even be considered at this time. The corresponding [Signal-iOS issue](https://github.com/WhisperSystems/Signal-iOS/issues/1984) contains even more chatter and support for stripping metadata, yet it doesn't look like anyone has made the call to move forward there either.

**Comment by moxie0** [comment] 2017-11-30 17:37
I'd accept a PR for something that strips out non-orientation exif metadata by default with an option to leave it in.

**Comment by tinkuge** [comment] 2017-12-09 01:10
Has this issues been assigned to anyone or can anyone work on it? I'd like to work on this.

**Comment by Lvl4Sword** [comment] 2018-01-24 20:06
I'm also experiencing this on Android 7.1.2 with Signal 4.14.10

**Comment by automated-signal** [comment] 2018-04-03 00:52
GitHub Issue Cleanup:
See #7598 for more information.

**Closed by automated-signal** 2018-04-03 00:52 UTC
Labels: feature
