### ISSUE TITLE
Messages not arriving until later when app is opened after another message came through

### ISSUE THREAD

**Issue by jeremymasters** [signalapp/Signal-Android#5994] opened 2016-12-27 01:11 UTC
I have:
- [ x] searched open and closed issues for duplicates
- [ x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Sometimes messages don't seem to show up until late or show  up after another message creates a notification. 

### Steps to reproduce
- have not found a way to reproduce, but it happens every so often, within the same day usually. 

**Actual result:** messages occasionally appear late or only after others appear
**Expected result:** each message appears individually as it comes in

`12-26 16:38:39.272 16720 16748 W PushDecryptJob: org.whispersystems.libsignal.DuplicateMessageException: Received message with old counter: 1 , 0
12-26 16:38:39.272 16720 16748 W PushDecryptJob: 	at org.whispersystems.libsignal.SessionCipher.getOrCreateMessageKeys(SessionCipher.java:365)
12-26 16:38:39.272 16720 16748 W PushDecryptJob: 	at org.whispersystems.libsignal.SessionCipher.decrypt(SessionCipher.java:297)
12-26 16:38:39.272 16720 16748 W PushDecryptJob: 	at org.whispersystems.libsignal.SessionCipher.decrypt(SessionCipher.java:254)
12-26 16:38:39.272 16720 16748 W PushDecryptJob: 	at org.whispersystems.libsignal.SessionCipher.decrypt(SessionCipher.java:235)
12-26 16:38:39.272 16720 16748 W PushDecryptJob: 	at org.whispersystems.libsignal.SessionCipher.decrypt(SessionCipher.java:203)
12-26 16:38:39.272 16720 16748 W PushDecryptJob: 	at org.whispersystems.signalservice.api.crypto.SignalServiceCipher.decrypt(SignalServiceCipher.java:142)
12-26 16:38:39.272 16720 16748 W PushDecryptJob: 	at org.whispersystems.signalservice.api.crypto.SignalServiceCipher.decrypt(SignalServiceCipher.java:111)
12-26 16:38:39.272 16720 16748 W PushDecryptJob: 	at org.thoughtcrime.securesms.jobs.PushDecryptJob.handleMessage(PushDecryptJob.java:141)
12-26 16:38:39.272 16720 16748 W PushDecryptJob: 	at org.thoughtcrime.securesms.jobs.PushDecryptJob.onRun(PushDecryptJob.java:120)
12-26 16:38:39.272 16720 16748 W PushDecryptJob: 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
12-26 16:38:39.272 16720 16748 W PushDecryptJob: 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
12-26 16:38:39.662 16720 16720 D ViewRootImpl: ViewPostImeInputStage processPointer 0
12-26 16:38:39.762 16720 16720 D ViewRootImpl: ViewPostImeInputStage processPointer 1`

### Device info

**Device:** Samsung Galaxy Note 5
**Android version:** 6.0.1
**Signal version:** 3.25.3

### Link to debug log
https://gist.github.com/37bed572ee95c60fecf3867bfd6acc5b

**Comment by ansisys** [comment] 2017-01-09 16:05
I've been able to reproduce the issue every time using sms gateway as I didn't want to bother anyone with my requests for new text messages. Anyway the text msgs don't come through as soon as the app is closed or shall I say once I use the "swipe" thingen to close all the running apps. The Signal app is of course set as a default sms app. 
**Steps to reproduce**
**Requirement** - Signal shall be set as a default sms app on the phone.
1. Close the app.
2. Send text or ask some one to do so
3. **Result** - no txt received.
4. Start Signal
5. Send another txt
**Result** : Txt is received properly. 

To make sure it's not the OS's fault by the first look I've changed a default sms app to messenger from facebook and the texts were comming in despite the fact that the facebook messenger app itself wasn't running. I hope this shall give enough material for the developers, where to look for. 

**Link to debug log**

[https://gist.github.com/anonymous/42c64a5d591b7b9da1de8651dafe5184](https://gist.github.com/anonymous/42c64a5d591b7b9da1de8651dafe5184)

**Comment by riyapenn** [comment] 2017-01-09 16:35
Did you check your phone's settings? i.e. if Signal is included in the list of apps that can start itself, or other battery optimization settings.  [See steps on the support page](https://support.whispersystems.org/hc/en-us/articles/213190487-Why-is-there-a-delay-in-receiving-messages-).

**Comment by ansisys** [comment] 2017-01-09 17:06
All set according to the page provided. Still, when app is "closed", no txts received. ps. Where do you check i Signal is inclueded in the list of apps that can start itself?

**Comment by riyapenn** [comment] 2017-01-09 17:09
Contact support@whispersystems.org for troubleshooting

**Comment by ansisys** [comment] 2017-01-09 17:16
btw. as soon as the app is started (even before I enter password) the txts can be received.

**Comment by 2-4601** [comment] 2017-01-09 19:01
@ansisys That's because some restriction with your phone (e.g. very common with Huawei devices). Please contact the support email address given above if the steps in the support page did not help.

At some point there were issues like this with TextSecure(Signal) itself but currently these kind of issues are most likely due to bad ROM behavior, intermittent GCM/Google Play Services and network issues. But there could me some rare Signal bugs still, can't say from the logs. But @jeremymasters is a long time TS/Signal user so he can probably recognize it's not any of the normal culprits listed in the support page :)

**Comment by jeremymasters** [comment] 2017-01-09 19:11
This had not been happening as far as I could tell in 3.24.x.  What I can say for sure is that it was happening on an internet connection that was super-busy.  At this point, I don't think I'm seeing it any more since I came home and the entire house is NOT watching Netflix. :smile:

**Comment by ansisys** [comment] 2017-01-10 13:36
I'll reset the whole phone to factory defaults real quick and if this won't help, I'll see what support will achieve. 

Btw. The issue has been tested on another phone (https://gist.github.com/anonymous/3961ea28f777ee9795f752832aee6599) but to no avail.

**Comment by ocram** [comment] 2017-01-10 22:46
@jeremymasters (and perhaps also @ansisys):

 * For Samsung devices: Open the menu with all apps and go to the "Smart Manager". Open "Battery". In the section "App Optimization", press "Detail". Using the switch at the top, disable this feature.
 * For Huawei devices: Open the "Phone Manager". Go to "Power saving". Open "Protected apps". Make sure that this feature is enabled for "Signal". Go back to the "Phone Manager" again. Go to "Notification center" and then choose "Signal". Make sure that all notification types are enabled here.

This is related to steps (3C) and (8) on the support page referenced by @riyapenn. Did you do this?

**Comment by jeremymasters** [comment] 2017-01-10 22:53
@ocram it's not optimized., and there's no "smart manager".  Also, it says signal has used 5% of my battery.  *shrug*

**Comment by ansisys** [comment] 2017-01-12 16:13
Today there was an update afaik and this brought a small but quite significant improvement. I could receive txt without starting the app, but only once the phone has been restarted. So I went ahead and reset the phone to factory defaults, disabled everything what had to do with optimization whatsoever, updated google play services and installed Push notification fixer, set the notifications to 5 minuts, rebooted the phone and...there is an improvement. I can receive txt from the reboot state of the phone. I can also receive the same, once signal has been "killed" by pressing "X" in the right hand upper corner, when you list all the apps running. BUT, when I use the (swipe) button from the list of the running apps, in other phones it's called "close all running apps" or something, then text messages, again, are not comming in. I then need reopen it and if needed closed it by pressing the "x" on the signal app, once I get all the apps running again. 

As you can see there must be something that kills/closes a bit more then running apps. Can Signal then not be started with some sort of highest priority or anything in that direction, so that no other process could kill it, or at least not so easy? It's just an idea.

**Comment by 2-4601** [comment] 2017-01-12 16:19
@ansisys I remember someone reporting before that closing from recent apps view affected notifications. I think it was a ROM issue, but not sure. I can't find that issue with search now. You might want to try searching with better luck.

The swipe closing is related to #1037.

**Comment by ocram** [comment] 2017-01-13 23:51
@jeremymasters If you have a Samsung Galaxy Note 5, there really should be a "Smart Manager" somewhere on your device [[1]](http://www.samsung.com/us/support/answer/ANS00043251/) [[2]](https://news.samsung.com/global/smart-manager-the-way-to-keep-your-galaxy-smartphone-as-good-as-new-always).

Most vendors have some weird "battery optimization" techniques now (which have been rendered obsolete with the introduction of "Doze" -- but they added these techniques before that). But at least for Samsung and Huawei devices, it's possible to fix the non-working notifications.

@ansisys There's no need, really, to close Signal from the "Recents", right?

**Comment by automated-signal** [comment] 2018-04-03 01:02
GitHub Issue Cleanup:
See #7598 for more information.

**Closed by automated-signal** 2018-04-03 01:02 UTC
