### ISSUE TITLE
can't send messages while on wi-fi

### ISSUE THREAD

**Issue by Same-Old-Issue** [signalapp/Signal-Android#8505] opened 2019-01-04 06:14 UTC
Hi,

I'm having trouble sending messages while on wi-fi

The message will get the "round dotted circle" and the message won't be send until I switch to data
While on wi-fi I can still receive text messages or calls from other signal accounts but I can't receive files - when I "click" them the rounded icon will initiate the download without any progress whatsoever

At the same time the desktop application will run with no issue on the same network connection - sending/receiving text and files will work flawlessly
The messages I sent from desktop will even show up on the mobile app while the ones composed on the cellphone are still pending to be sent

The same scenario will apply when using a different wi-fi connection (ex at work)

The phone is a Galaxy S7 running android 8.0.0, rooted and with most of the google services disabled (including services.framework and play.services)
Signal version is 4.31.6 but I had the same problem with previous versions as well
A firewall is also installed

Attached is a file containing the logcat filtered with the command below:
adb logcat | findstr org.thoughtcrime.securesms
The log will cover the time while a text message was composed on mobile and pending to be sent ; receiving (sync) a text message i sent from desktop app to the same counterpart ; switching to data so the mobile text message is send eventually
[adb_logcat.log](https://github.com/signalapp/Signal-Android/files/2726122/adb_logcat.log)

Thank you in advance for help

Regards

**Comment by CFPrulez** [comment] 2019-01-04 14:09
Depending on your firewall settings, this may be a duplicate of #8365 .

**Comment by greyson-signal** [comment] 2019-01-06 19:57
I'm assuming this is a firewall issue. The log indicates that the system doesn't think you have a network connection when you're connected to the wifi network, likely due to some firewall configuration.

**Closed by greyson-signal** 2019-01-06 19:57 UTC
