### ISSUE TITLE
PIN incorrect

### ISSUE THREAD

**Issue by vliedel** [signalapp/Signal-Android#9569] opened 2020-04-30 11:59 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Every time (2 times so far) signal asks me to verify my PIN, I get "incorrect PIN". The first time this happened, I made sure I set the right PIN via the "forgot PIN", and wrote it down.

### Steps to reproduce
- Set a PIN of 6 digits.
- Wait for the "verify your PIN".
- Fill in your PIN.

Unfortunately, I don't know how to trigger the "verify your pin".

**Actual result:** PIN in correct.
**Expected result:** PIN verified.

### Device info
**Device:** Samsung Galaxy S10e, SM-G970F
**Android version:** 10
**Signal version:** 4.59.5

**Comment by k3npachi** [comment] 2020-04-30 14:04
Same error for me

3 times signal ask me the NIP for don't forget it, each time error

**Comment by greyson-signal** [comment] 2020-04-30 14:27
Can you include logs and the language settings of your keyboard?

**Comment by k3npachi** [comment] 2020-04-30 14:42
https://debuglogs.org/90b77b1c34c64857b767735634410755993cbaba2dd565ba650b8ebcc8c9ce39

French keyboard

**Comment by greyson-signal** [comment] 2020-04-30 15:25
Your log indicates that you're seeing the correct dialog and stuff, so that's good.
Unfortunately I can't seem to reproduce this at all.

When you get the PIN reminder, is it showing the same keyboard that you used to create the PIN, and the same keyboard layout? 

I'm trying to think of whether there's any way what you entered in one screen could somehow be different from what you're entering in the reminder, even if it looks like you're typing the same thing.

**Comment by vliedel** [comment] 2020-04-30 15:32
I'll try to pay attention to the keyboard layout. Is there a way to trigger the pin verification?

**Comment by k3npachi** [comment] 2020-04-30 15:45
> Your log indicates that you're seeing the correct dialog and stuff, so that's good.
> Unfortunately I can't seem to reproduce this at all.
> 
> When you get the PIN reminder, is it showing the same keyboard that you used to create the PIN, and the same keyboard layout?
> 
> I'm trying to think of whether there's any way what you entered in one screen could somehow be different from what you're entering in the reminder, even if it looks like you're typing the same thing.

I don't know, I'll try to get a good look at it next time I ask.

Maybe the option "keyboard incognito" ?

**Comment by greyson-signal** [comment] 2020-04-30 16:10
> Is there a way to trigger the pin verification?

There isn't, unfortunately. But if you're interested, I can send you a build that will allow you to force a PIN verification prompt. If you'd like to try that, you can message my test device at +1 610 708 0800. Thanks!

**Comment by duncanam** [comment] 2020-04-30 17:10
Also having this error. I'd like to add that I've tried entering in my pin through several methods, including typing, copy and paste, and my password manager's keyboard input function and all of these fail.

**Comment by brozkeff** [comment] 2020-04-30 19:22
Comfirmed on my Xiaomi Redmi Note 4 mido.
Entered a 11char numeric PIN. When asked to test for remember it wrote bad PIN until I reset the pin again. Next time after that the same behaviour.
Signal 4.59.5
Debug log https://debuglogs.org/51efbfcd51d148d9dd2f71dae5bcdb7d98776f953a5ef2c2776de1b3617198f7

**Comment by MattLParker** [comment] 2020-04-30 19:31
Confirmed Galaxy s10 
US Keyboard
Signal 4.69.5
Same symptoms 
My Debug:https://debuglogs.org/9318d876a22804afb3169cd1efc07c843fddbf7a6e6a46a34838146badec4788

Wife's phones a Oneplus 6t Same symptoms... No Debug log right now.

**Comment by jeffbl** [comment] 2020-04-30 22:00
Confirmed on Pixel 3a. The first time it happened I thought I just forgot my PIN, so I changed it and put it in LastPass. Now it is asking again and keeps failing. I get a numeric keyboard. I have lastpass installed, and its popup comes up automatically, but disappears when I start typing. There is no error - it just keeps clearing the field when I hit "submit" and never accepts it.

**Comment by k3npachi** [comment] 2020-05-01 03:25
Are we all using SwiftKey or not ?

**Comment by vliedel** [comment] 2020-05-01 07:07
> Are we all using SwiftKey or not ?

I'm using the default "samsung keyboard" (5.0.10.41).

**Comment by ikino** [comment] 2020-05-01 09:46
Same error, Samsung S7, again set pin and again error.

**Comment by ikino** [comment] 2020-05-01 10:47
Its ok in version 4.59.6

**Comment by jeffbl** [comment] 2020-05-01 12:28
Confirmed working for me in 4.59.6 as well.

**Comment by MattLParker** [comment] 2020-05-01 12:34
Confirmed working on S10 in 4.59.6

**Comment by greyson-signal** [comment] 2020-05-01 14:12
Hey folks, yep, we were digging through it yesterday and figured it out.The fix is in 4.59.6. Had to do with incorrectly using the old registration lock v1 code verification in some situations when we should have been using the new Signal PIN verification. Sorry for the confusion!

**Closed by greyson-signal** 2020-05-01 14:12 UTC
