### ISSUE TITLE
Phonebook

### ISSUE THREAD

**Issue by olhor** [signalapp/Signal-Android#11114] opened 2021-03-17 22:47 UTC
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

### Link to debug log

Why I do not see whole my phonebook when sharing a picture, eg. via mms?

**Comment by greyson-signal** [comment] 2021-03-17 22:58
Closing as a duplicate of #11114

**Closed by greyson-signal** 2021-03-17 22:58 UTC

**Comment by Leptopoda** [comment] 2021-03-18 07:24
@greysonp  duplicate of what?
You accidentally referenced itself.

**Comment by greyson-signal** [comment] 2021-03-18 14:40
lol classic. I meant #10929

**Comment by olhor** [comment] 2021-03-18 15:09
Thanks.

**Comment by caitsith01** [comment] 2021-04-22 01:50
> 
> 
> Closing as a duplicate of #11114

Instead of just closing this bug report without any engagement, any chance anyone from Signal might actually respond in relation to the numerous related bugs which are breaking basis SMS/MMS functionality on Android?
