### ISSUE TITLE
Certain messages are not displayed in the inbox

### ISSUE THREAD

**Issue by sikand** [signalapp/Signal-Android#7769] opened 2018-05-07 17:54 UTC
If I use Google Assistant to send a text, I never see the message in the signal inbox. Same with sending messages from the phone app, like I'm busy, please call back

ATT Samsung S9±

**Comment by jlund-signal** [comment] 2018-05-07 18:28
Thanks for the submission, but please don't delete the issue template in the future.

This is also a duplicate of #7627, and there isn't anything that Signal can do to properly support this right now because Google Assistant does not provide the necessary APIs.

**Closed by jlund-signal** 2018-05-07 18:28 UTC

**Comment by anoxi** [comment] 2018-10-02 20:33
Is there any hope to get an API from Google Assistant that these SMS messages get to the Signal App? Otherwise, I understand the only alternative is to switch SMS handling back to the native SMS app.
