### ISSUE TITLE
Feature Request: Getting title from website link while sharing from browser.

### ISSUE THREAD

**Issue by jaypatelani** [signalapp/Signal-Android#6236] opened 2017-02-16 17:36 UTC
I have:
- [X ] searched open and closed issues for duplicates
- [ X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Feature description
Getting title when sharing link from any browser to signal one to one or group chat as shown in example. Attached is screenshot of example what signal does when link is shared and what other IM does.

### Screenshot of link shared from firefox to BBM 
![screenshot_20170216-224150](https://cloud.githubusercontent.com/assets/17174485/23032878/0bff57f6-f49c-11e6-8dfe-39fbb44aff63.png)

### Screenshot of link shared from firefox to signal

![screenshot_20170216-224234](https://cloud.githubusercontent.com/assets/17174485/23032901/24157c58-f49c-11e6-927a-2c6a3847c091.png)

### Device info

**Device:** BlackBerry Dtek50
**Android version:** 6.0.1
**Signal version:** 3.29.6

**Comment by Shenkaa** [comment] 2017-02-16 19:24
If I share directly from the CyanogenMod or AOSP browser, then an image of the web page is added above the URL. But, as @jaypatelani said, not from Firefox and Chrome.

**Comment by jaypatelani** [comment] 2017-02-18 03:46
![screenshot_20170218-085319](https://cloud.githubusercontent.com/assets/17174485/23090070/c4230ae8-f5ba-11e6-917a-7ea0686e6e1c.png) From Reddit App to Signal contact.

**Comment by snaggen** [comment] 2017-03-10 15:21
Isn't this just a simpler hyperlink preview and hence kind of a duplicate of #5724

**Comment by trymeouteh** [comment] 2017-11-12 04:36
This would be cool especially for youtube videos and news articles.

**Comment by nrizzio** [comment] 2017-11-12 16:17
@trymeouteh Please don't [bump issues.](https://github.com/WhisperSystems/Signal-Android/blob/f53d64ab7a77d4d79723729bfc4fba9685703c61/CONTRIBUTING.md#dont-bump-issues)

**Comment by automated-signal** [comment] 2018-04-03 02:01
GitHub Issue Cleanup:
See #7598 for more information.

**Closed by automated-signal** 2018-04-03 02:01 UTC
Labels: feature
