### ISSUE TITLE
Signal (4.16.4) crashed after incoming call

### ISSUE THREAD

**Issue by halb9** [signalapp/Signal-Android#7396] opened 2018-02-05 23:03 UTC
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I tried to place a Signal call for some other testing. On the receiving phone (this bug report) Signal crashed. Showed the below image and was unresponsive to further input. Normally there is an avatar shown for the caller since I've set one up. 

Another call about a minute after that worked fine. So did all calls after that. Sadly I was not able to reproduce it. Captured a debug log though. Hope this helps. Thanks!

### Steps to reproduce
unable

**Actual result:** Signal crashed
**Expected result:** Signal does not crash

### Screenshots

![incomingcallcrash](https://user-images.githubusercontent.com/18451020/35833098-a7d16808-0ac7-11e8-862a-e07f0051cd5b.png)

### Device info

**Device:** samsung GT-I9505 (jgedlteue)
**Android version:** 7.1.2 (16ea4b1148, lineage_jfltexx-userdebug 7.1.2 NJH47F 16ea4b1148)
**Signal version:** 4.16.4

### Link to debug log

https://gist.github.com/anonymous/12a4b6f54b2670eac2dd6b3817497982

**Comment by cegg1** [comment] 2018-02-06 00:39
Duplicate of #7375

**Comment by halb9** [comment] 2018-02-06 07:13
hmm yeah looks a lot like it. Sorry for duplicate. 
Interestingly the decline call button is again overlaying the accept button. This is similar to what I experienced in #7211.

**Closed** 2018-03-18 13:10 UTC
