### ISSUE TITLE
[UX bug] Message timestamps are too capital and too large 

### ISSUE THREAD

**Issue by burntcookie90** [signalapp/Signal-Android#8005] opened 2018-07-19 13:29 UTC
- [ x ] I have searched open and closed issues for duplicates
- [ x ] I am submitting a bug report for existing functionality that does not work as intended
- [ x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The timestamps on the new UI are way too big. They're very similar in size to the actual message font and are very distracting. Also, it seems like it's yelling at me -_-.

### Steps to reproduce
- Be on 4.24.1
- Send messages

**Actual result:** Timestamps are huge and capitalized, drawing user's attention.
**Expected result:** Don't be so eye catching with the timestamps, they're meta data.

### Screenshots
![image](https://user-images.githubusercontent.com/1452613/42945290-05207906-8b36-11e8-8273-4a44e00ca9e2.png)

### Device info

**Device:** Google Pixel 2 XL
**Android version:** 9 (build number: `PPP4.180612.004`)
**Signal version:** 4.24.1

**Comment by vvug** [comment] 2018-07-19 15:05
THEY ARE REALLY ANNOYING

**Comment by greyson-signal** [comment] 2018-07-19 19:08
I'm going to close this because this isn't technically a bug (they look as intended), but I will communicate this feedback to the team. FWIW I believe the size of the timestamp is the smallest font size you can use if you want to remain accessible, but we'll see if there's a way to make them less distracting. Thank you for the feedback!

If you're interested in continuing the discussion, feel free to make a post on the forum, or chime in via a [post we setup](https://community.signalusers.org/t/feedback-on-the-new-visual-changes-in-android-4-24-ios-2-28-and-desktop-1-15/3532) to collect design feedback. Thanks!

**Closed by greyson-signal** 2018-07-19 19:08 UTC

**Comment by pshem** [comment] 2018-08-11 00:32
I'm voting to reopen this bug. The increase in message timestamp font size to be BIGGER than the message font(when you use small font) and to not instead scale with the chosen font size makes the new graphic redesign a disaster. I can now, on average, see one less line of text with the keyboard open. Loosing 10% of screen real estate is NOT ok.
