### ISSUE TITLE
App crash on opening any chat

### ISSUE THREAD

**Issue by InLearningPhase** [signalapp/Signal-Android#10589] opened 2021-01-13 12:02 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Opening any chat (new or old) always crashes the app.

### Steps to reproduce
- open signal 
- click on any chat

**Actual result:** App crashes
**Expected result:** Chat should open 

### Device info

**Device:** Oneplus 7
**Android version:** 10
**Signal version:** 5.0.10

### Link to debug log

java.lang.RuntimeException: Unable to start activity ComponentInfo{org.thoughtcrime.securesms/org.thoughtcrime.securesms.conversation.ConversationActivity}: java.lang.SecurityException: getCarrierConfig
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3388)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3527)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2123)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7710)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: java.lang.SecurityException: getCarrierConfig
        at android.os.Parcel.createException(Parcel.java:2071)
        at android.os.Parcel.readException(Parcel.java:2039)
        at android.os.Parcel.readException(Parcel.java:1987)
        at com.android.internal.telephony.ISms$Stub$Proxy.isImsSmsSupportedForSubscriber(ISms.java:2292)
        at android.telephony.SmsManager.isImsSmsSupported(SmsManager.java:2011)
        at android.telephony.SmsMessage.useCdmaFormatForMoSms(SmsMessage.java:905)
        at android.telephony.SmsMessage.calculateLength(SmsMessage.java:374)
        at android.telephony.SmsMessage.calculateLength(SmsMessage.java:353)
        at android.telephony.SmsMessage.calculateLength(SmsMessage.java:511)
        at org.thoughtcrime.securesms.util.SmsCharacterCalculator.calculateCharacters(SmsCharacterCalculator.java:35)
        at org.thoughtcrime.securesms.TransportOption.calculateCharacters(TransportOption.java:84)
        at org.thoughtcrime.securesms.conversation.ConversationActivity.calculateCharactersRemaining(ConversationActivity.java:2500)
        at org.thoughtcrime.securesms.conversation.ConversationActivity.lambda$initializeViews$24(ConversationActivity.java:1936)
        at org.thoughtcrime.securesms.conversation.ConversationActivity.lambda$initializeViews$24$ConversationActivity(Unknown Source:0)
        at org.thoughtcrime.securesms.conversation.-$$Lambda$ConversationActivity$8_nfrdEIzbNViimV4rR21GKz6-s.onChange(Unknown Source:2)
        at org.thoughtcrime.securesms.TransportOptions.notifyTransportChangeListeners(TransportOptions.java:209)
        at org.thoughtcrime.securesms.TransportOptions.reset(TransportOptions.java:58)
        at org.thoughtcrime.securesms.components.SendButton.resetAvailableTransports(SendButton.java:79)
        at org.thoughtcrime.securesms.conversation.ConversationActivity.handleSecurityChange(ConversationActivity.java:1446)
        at org.thoughtcrime.securesms.conversation.ConversationActivity.initializeSecurity(ConversationActivity.java:1684)
        at org.thoughtcrime.securesms.conversation.ConversationActivity.onCreate(ConversationActivity.java:438)
        at org.thoughtcrime.securesms.PassphraseRequiredActivity.onCreate(PassphraseRequiredActivity.java:66)
        at android.app.Activity.performCreate(Activity.java:7820)
        at android.app.Activity.performCreate(Activity.java:7809)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1318)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3363)

**Comment by Ttt131** [comment] 2021-01-15 09:55
Hi ! Same issue here for few users of my work group.
Signal is crashing when entering the large group (>150).
Small groups and one to one are ok.
I will add debug log of these users a I receive it.

Android, Samsung :
https://debuglogs.org/c60f8e1d1cad22a1ed3ee315897ac10fdcfdea55393d493ccf361def50b0377c

**Comment by greyson-signal** [comment] 2021-01-15 17:31
Closing as a dupe of #9572

I believe this is a bug on OnePlus phones, and it appears they've fixed it in their latest software updates? In the meantime, you can fix this by going to your permissions and granting Signal phone permissions. Note that you shouldn't *have* to do this, it's a OnePlus bug where they erroneously expect this permission.

**Comment by greyson-signal** [comment] 2021-01-15 17:32
@Ttt131 You have a totally separate problem related to our calling library. I've notified the calling team and they're looking into it!

**Closed by greyson-signal** 2021-01-15 17:31 UTC

**Comment by Ttt131** [comment] 2021-01-15 17:38
Thanks !

**Comment by placydo** [comment] 2021-01-26 20:37
> @Ttt131 You have a totally separate problem related to our calling library. I've notified the calling team and they're looking into it!

@greyson-signal We have exactly same issue with multiple people. Is there any issue I can track? Thanks!
