### ISSUE TITLE
Occasional, Immediate Failure to Send/Resend Unsecured SMS

### ISSUE THREAD

**Issue by clguy24** [signalapp/Signal-Android#4927] opened 2015-12-19 23:00 UTC
Seemingly at random, text messages will fail to send to a non-signal user immediately after pressing send. "Tap for details" just reiterates that it failed to send. No details. Retrying instantly fails as well. Only solution has been to wait five minutes before entering and sending the text again. Has happened with multiple contacts. Text messages send again after waiting approximately 5 minutes or so. Attached are logs for three separate occurrences.

Device info: Motorola Droid RAZR, Android 4.1.2, Signal 3.7.2

Debug logs:
[TextSecureDebug1.txt](https://github.com/WhisperSystems/Signal-Android/files/67625/TextSecureDebug1.txt)
[TextSecureDebug2.txt](https://github.com/WhisperSystems/Signal-Android/files/67627/TextSecureDebug2.txt)
[TextSecureDebug3.txt](https://github.com/WhisperSystems/Signal-Android/files/67626/TextSecureDebug3.txt)

**Comment by jeremymasters** [comment] 2015-12-20 15:27
My brother has the same issue in his LG g4

**Comment by bacolite** [comment] 2015-12-23 14:58
I've run into this issue on my M8. I was unable to resend the message, or send new messages, but after I made a phone call I was able to send a new message to my contact.

**Comment by kordianbruck** [comment] 2015-12-30 04:03
Reboot helps as well. Have this happening also with MMS, so I guess it has to do with the carrier in some way.

**Comment by cascheberg** [comment] 2015-12-30 11:15
The logs show this, which is the same as in #4460, thrown [here](https://github.com/WhisperSystems/Signal-Android/blob/50c432aaf0b7deb8d8f4f890ff0a8542de5faf9f/src/org/thoughtcrime/securesms/jobs/SmsSendJob.java#L82)
> UndeliverableMessageException: Trying to send a secure SMS?

 @moxie0 would it help to know which of these types the message is?

**Comment by moxie0** [comment] 2015-12-30 15:49
@cascheberg My intuition is that there's something weird happening with `onNewIntent()` in `ConversationActivity`, such that some stuff isn't be appropriately reset.

**Comment by CCDKP** [comment] 2016-02-07 23:26
I've been seeing this pretty regularly for the last 2 months on 2 different phones. Thought it was carrier issues until I found this ticket. 

As it is happening fairly frequently, I would be glad to provide whatever is needed to help get it resolved. Are the debug traces from advanced sufficient? https://gist.github.com/3a11042c1bd3fc03d74e

**Comment by eosrei** [comment] 2016-02-09 05:57
Potential duplicate of #4765 Note attached debug log in this issue.

**Comment by markwalkom** [comment] 2016-02-12 07:49
I had this same thing with a non-Signal user. I ended up deleting all my (normal text) history with them as it was pretty long, and then the next message I sent went straight through.

**Comment by androclus** [comment] 2016-04-03 01:55
Similar mileage here.  I was sending a few messages to friends (both on Signal and on SMS) using Signal, and now I get "failed to send"s on three users I tried to send to.

I can continue to send Signal messaged to people.  And as I say SMS _was_ working as usual this evening.  But when I try to send SMS messages now, I get a message that "Some issues need your attention" and "Failed to send".

But WHAT issues those are, and WHY the failure occured,  are not specified on the message screen (which would have been more helpful).

NOR is there any help for where I could go to find out more or what to do.  Just, whenever I try to click on the "Resend" button in lower right, it just beeps and stays on same error screen.  So I am stuck, with no apparent way to proceed, and no help from the app itself.

Also, I notice I can still send to _some_ SMS (non-Signal) users, but not all..  Some work, some don't.  How odd.

The screenshot of a typical error screen and also when I try to resend is here:
https://drive.google.com/open?id=0B70lzkjE8GD0SmZYSnQtUXVHVm8

and the bug log is here:
https://gist.github.com/a76b518943c0b347fb0db5107626b5f6

OS is Android 6.0 (patch level 10/1/2015) on a Motorola Nexus 6. Signal version 3.15.2

BTW I am using Wifi at home.. and have tested that I can use all other apps, and have a good connection.  And, as I say, I *CAN* send perfectly fine to other Signal users, AND to some other SMS users.

This is repeatable and reproducible.  At least now in the evening.  (I don't know if things will get better tomorrow, etc.)

Let me know if I have left anything out, and/or if there is any additional information I can provide.

The only thing I can think of is that I was sending a lot of messages quickly, tonight, before it happened..  I tried waiting 5 minutes, (both with resending/retrying the same message to same person, and/or trying a new message to them) but no luck. Still just dings and stays on resend window.  Could theoretically be THEIR carrier, I guess..?  I will post if I get more info..  Maybe all the bounced recipients have a carrier in common? That would be interesting..

Thanks!
JS

**Comment by 2-4601** [comment] 2016-04-03 14:22
@androclus Did you capture that log immediately after a failed attempt to send SMS? There doesn't appear to be any errors there.

**Comment by riyapenn** [comment] 2016-04-06 01:59
Do you have 'SMS delivery reports' enabled through Signal > Menu > Settings > SMS and MMS? You can contact support for some trouble shooting too: support@whispersystems.org.

**Comment by androclus** [comment] 2016-04-07 04:17
hi, no i did not have sms delivery reports turned on.. :-/[]

2016-04-03 7:22 GMT-07:00 2-4601 <notifications@github.com>:

**Comment by androclus** [comment] 2016-04-07 04:18
yes, i did capture it immediately after the attempts.

2016-04-03 7:22 GMT-07:00 2-4601 <notifications@github.com>:

**Comment by juleabk08** [comment] 2016-05-02 02:26
I'm having the same issue as androclus and clguy 24. (log: https://gist.github.com/a329ccc1086f2f4c634577c047aa707c). I seem to be able to send to singal members without a problem but receive a failed to send when I try others.I'm also not reicievng texts from said contacts.

**Comment by FalconerTC** [comment] 2016-05-12 21:59
Any update on this? I'm having this issue on my LG G4. Once I made a phone call I received a week of back texts all at once.

**Comment by schock** [comment] 2016-06-11 17:49
I have the same issue. Any progress?

**Comment by joshproehl** [comment] 2017-02-11 19:37
A friend of mine is having this issue often now. He uses a Samsung Galaxy 6, T-Mobile network. [Debug log captured just after the most recent event](https //gist.github.com/anonymous/45a7a68f6e23480335757eaacc0416eb).

Message fails to send, and says "Not Delivered". Tapping for message details shows the same, and says "Some issues need your attention", but offers no additional information.

This issue appears to be **recipient  specific**, as sending an insecure message to another user will succeed, even a recipient who has this problem regularly. Recipients with problems have all been iPhone users, but on multiple networks, including T-Mobile.

The issue appears to happen randomly. Copy-pasting the message to try resending always fails. Sending a new message with different text has been able to resolve the issue. I've asked the user to try this message every time the issue occurs in the future to help diagnose this (and as a workaround), but I have no idea what causes the initial failure.

**Comment by moxie0** [comment] 2017-02-12 05:03
Thanks @joshproehl, from the log, it looks like we're handing the SMS to Android, and then later getting a callback with a result of "1," which is defined as ERROR_GENERIC_FAILURE in SmsManager. I would guess it's an OS or service issue, but can't say for sure, only that the error is occurring outside of Signal's code.

**Comment by joshproehl** [comment] 2017-02-12 05:14
@moxie0 Given an end-user who's likely to say "this app doesn't work" and stop using signal entirely due to the frequency of this (unless I can make them understand this issue), perhaps it be prudent to have the "more details" few display something to the effect of "Your OS has refused to send this text message and won't tell us why. :-(" or something? 

I'll continue to try and debug this when it occurs, so if there are any steps that would be helpful let me know.

**Comment by moxie0** [comment] 2017-02-12 05:19
@joshproehl It does seem like we could improve the error message. When you change the text of the message to make it work, then try sending the original message again, does that fail again?

**Comment by saturnine-fei** [comment] 2017-05-20 16:13
I have the exact same problem on My Nexus 6 running Lineage OS (and prior to a couple of weeks ago Carbon).  Sometimes I can just click the message to resend, sometimes I have to give up and use the OS's default messenger app.

It just happened about 10 Min. ago, with the resend working after I turned on data service with the carrier (I turn it off when using WiFi).  Is it an issue where the OS wants to see that data is on and will not use wifi for messaging?

**Comment by automated-signal** [comment] 2018-04-02 23:27
GitHub Issue Cleanup:
See #7598 for more information.

**Closed** 2018-04-02 23:28 UTC
Labels: bug
