### ISSUE TITLE
Messages and several conversations missing from restored backup

### ISSUE THREAD

**Issue by LearningAsIGo71** [signalapp/Signal-Android#12246] opened 2022-05-13 03:08 UTC
Running the latest version of GrapheneOS on a Pixel 5a I decided to move Signal from a secondary profile on the phone back to the main owner profile. I used the manual Signal backup method, transferred the file to my laptop and then to the owner profile and restored the backup. 

Notes to Self is missing entirely!
Several conversations (at least four) are empty with the exception that the four conversations have one message stating when that particular user tried to call me or I tried to call them. 
All group conversations are empty with the exception of a message that reads "You joined the group." 

Thankfully some important messages are still preserved on my Signal desktop app for Windows that I can copy and paste and save into a file for archiving. 

Nevertheless this is not the first time I am missing conversations after using Signal backup and restore.

**Comment by clauz9** [comment] 2022-05-13 09:11
Another tear shed by the developer who put that issue template there, that you completely ignored, 😢  please stop making the developers cry 🤣 and use the issue template. 

> Notes to Self is missing entirely!

This is interesting,
After the back-up restore, did you register with the same phone number, that you used on your secondary profile ? or with a different one ?  

> Several conversations (at least four) are empty with the exception that the four conversations have one message stating when that particular user tried to call me or I tried to call them.

if those conversation had "disappearing messages" enabled, then they are not back-up by design, because that would mean, you will be able to retain the disappearing messages past the point of their expiry. 

> All group conversations are empty with the exception of a message that reads "You joined the group."

if all group conversations have had "disappearing messages" enabled, then that's expected

**Comment by UserX404** [comment] 2022-05-15 11:10
Hi @LearningAsIGo71 
Sms/Mms should be included.
https://community.signalusers.org/t/are-sms-messages-included-in-the-encypted-backup/25449/2

**Comment by clauz9** [comment] 2022-05-15 17:33
@LearningAsIGo71  do you think you can close this now ?

**Closed** 2022-05-16 21:42 UTC
