### ISSUE TITLE
Audio save doesn't work

### ISSUE THREAD

**Issue by maximilian66** [signalapp/Signal-Android#10199] opened 2020-11-15 10:58 UTC
Hi,

When I try to save the audio files from multimedia section, a white screen appears, then initial chat screen returns and the files are not saved. I tried to update the app, install it again but nothing happens. Until 15 days ago it worked perfectly.

Someone can help me?

Thanks
Max

**Comment by Genis-Sage** [comment] 2020-11-15 12:16
Hey @maximilian66 
Right now, I guess, the information you give is not enough

Can you fill out the issue template and also post a debug log?



- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Screenshots



### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

### Link to debug log

**Comment by rcornea** [comment] 2020-11-18 01:10
I have been running into the exact same issue as @maximilian66 above.

Bug description:
Signal app crashes when trying to save voice messages to local storage

Steps to reproduce:
- select any voice recording in any chat
- click "save to storage" icon in the upper toolbar
- click "yes"

Actual result:
Screen turns white, then goes back to the recent chats/main/initial app screen. Nothing is written to disk.

Expected result: 
Signal writes the selected message as a distinct audio file in one of the user-accessible folders on the local disk.

Screen capture:
https://drive.google.com/file/d/1x4jtGSZJ59y1CEGdTuRnKGkgg2TiZD8o/view?usp=drivesdk

Device info:
Device: Xiaomi Mi A1
Android version: 9.0.0
Signal version: 4.77.3

Link to debug log:
https://debuglogs.org/ae1778627e0c426ded0803755c347b7ece942021d89d49cd0a1e33989867e013

**Comment by matt6575** [comment] 2020-11-21 02:19
Same issue here as well, Signal crashes each time I attempt to save audio file. I posted about this over on the forum as well.

Here is my debug log:
[https://debuglogs.org/4c371d388ae6e49f0a65aa48b61c9c9989fa540f2a29c69fe0f3128164cfa15c](url)

**Comment by liayn** [comment] 2020-11-26 13:41
Confirmed:

Device: Honor 8
Android: 8
Signal: 4.78.5

**Comment by mMuck** [comment] 2020-11-26 17:31
Confirmed 😢 
```
Manufacturer  : samsung
Model         : SM-G950F
Android       : 9 (G950FXXSADTI1, PPR1.180610.011.G950FXXSADTI1)
App           : Signal 4.78.5 (746, 7462)
```
https://debuglogs.org/d525c536289b5e2b2cee551fe2bc58939d2dc14fe5f847013faef7ea267b6974

**Comment by mMuck** [comment] 2020-11-26 17:38
Seems to be a duplicate of #10159

**Comment by greyson-signal** [comment] 2020-12-01 15:04
Closing as dupilcate of #10159

**Closed by greyson-signal** 2020-12-01 15:04 UTC
