### ISSUE TITLE
Prevent SS7 “bug”

### ISSUE THREAD

**Issue by leonardoporpora** [signalapp/Signal-Android#7415] opened 2018-02-15 10:01 UTC
What if during the installation of signal you implement a feature that could be enabled or not that makes the installer decide if after the sms of phone number verification he wants to link to that device codes backup like most of services do when you enable 2FA you usually print that codes. So furbo to the SS7 “bug” if someone’s Intercept my sms he can’t still login without those codes

**Comment by FeuRenard** [comment] 2018-02-15 10:12
This sounds like a duplicate of #5599.

**Comment by leonardoporpora** [comment] 2018-02-15 10:15
I think it could be done without problems. Just a code that someone have to copy and I repeat this feature is not enabled by default but someone who wants could enable it. I think it would be fair

**Comment by moxie0** [comment] 2018-02-15 19:08
@leonardoporpora Please don't delete the issue template when filing new issues, and try to check for duplicates if you can. Thanks!

**Closed** 2018-02-15 19:08 UTC
