### ISSUE TITLE
Crash after scrolling to the top of the chat in horizontal mode

### ISSUE THREAD

**Issue by DirkPitt1** [signalapp/Signal-Android#9957] opened 2020-08-25 10:48 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I experience crash when scrolling conversation all thew way to the top when my phone is rotated horizontally. It happens when contact's name and photo appears on the screen and seems to crash only for Signal contacts and Note to self, but not for all. I don't experience this when my phone is rotated vertically.

### Steps to reproduce
- open chat thread
- turn your phone horizontally
- scroll to the top

**Actual result:**
Signal crashes for some chats.

**Expected result:**
No crash.

### Device info

**Device:** LG G4
**Android version:** 6.0
**Signal version:** 4.69.6

### Link to debug log
https://debuglogs.org/46126d1b0e2e2f7adadfc8aeb61cc60aea025ab0050d78105a8163231b44fba4

**Comment by alex-signal** [comment] 2020-08-25 12:11
Duplicate of https://github.com/signalapp/Signal-Android/issues/9954

**Closed by alex-signal** 2020-08-25 12:11 UTC
