### ISSUE TITLE
Wikipedia link with bracket is not stripped correctly

### ISSUE THREAD

**Issue by call-me-matt** [signalapp/Signal-Android#11136] opened 2021-03-25 07:10 UTC
- [x] I have searched open and closed issues for duplicates. Possibly related to https://github.com/signalapp/Signal-Android/issues/10796
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Links to Wikipedia that end with a bracket are not stripped correctly.

### Steps to reproduce
sending a wikipedia link with brackets
https://en.wikipedia.org/wiki/Trade_(nightclub) - hyperlink to nightclub works

sending a link in brackets
(https://signal.org) - works

BUT

sending a wikipedia link in brackets
(https://de.wikipedia.org/wiki/Signal) - hyperlink does not work, as it does not strip the brackets correctly

All links are stripped correctly on the desktop client, by the way.

**Actual result:** The user gets redirected to https://de.wikipedia.org/wiki/Signal)
**Expected result:** The user gets redirected to https://de.wikipedia.org/wiki/Signal

### Device info

**Device:** Google Pixel 4a
**Android version:** 11
**Signal version:** 5.5.5

**Comment by findjigar** [comment] 2021-03-26 01:10
I did some research on this issue.

Issue is caused by Android's `Linkify` class itself when this line is called `Linkify.addLinks(spannable, Linkify.WEB_URLS);` inside `LinkPreviewUtil.findValidPreviewUrls()` method

Problem is,
- when input is given as `(https://signal.org)` --> Linkify add a `URLSpan` as `https://signal.org` with brackets removed
- when input is given as `(https://de.wikipedia.org/wiki/Signal)` --> Linkify add a `URLSpan` as `https://de.wikipedia.org/wiki/Signal)`. Thus only removing the opening bracket.

Now I'm not sure whether Signal team even wants to support this feature or not with URL inside the brackets.

If they want to support it then this bug is valid, and potentially either a bug should be logged for `Linkify` or a new logic would need to be added to fix a broken URL after it passed through `addLinks` method

This can be easily tested via adding two more unit tests in the `LinkPreviewUtilTest_findValidPreviewUrls` class.

```
  // this test passes
  @Test
  public void contains_a_link_in_bracket() {
    LinkPreviewUtil.Links links = LinkPreviewUtil.findValidPreviewUrls("(https://signal.org)");

    assertEquals(1, links.size());

    assertTrue(links.containsUrl("https://signal.org"));
  }

  // this test should pass but it fails
  @Test
  public void contains_a_link_in_bracket_2() {
    LinkPreviewUtil.Links links = LinkPreviewUtil.findValidPreviewUrls("(https://de.wikipedia.org/wiki/Signal)");

    assertEquals(1, links.size());

    assertTrue(links.containsUrl("https://de.wikipedia.org/wiki/Signal"));
  }
```

I even tried using `LinkifyCompat` but it produced same result.

**Comment by hiqua** [comment] 2021-03-26 16:25
From a UX perspective I think OP is right that Signal-Desktop has the best behavior. And in the case of http://example.com/url_with_)_in_it it's fine to get a broken link that results in [http://example.com/url_with_]() instead of the full url, since it should be quite a rare case, and the only way to detect it would be to fetch the possible pages and return a link corresponding to a 200 rather than 404 (which is probably too involved, and is still not 100% perfect).

The main reason why this corner case bug should be considered is that one of the main website, Wikipedia, regularly has this kind of URLs.

Regarding the opinion from the Signal devs, if you're not that far from an actual PR it might be better to open one to get their feedback (but it's indeed bothersome to work on something that is eventually not merged in).

**Closed** 2022-02-02 17:36 UTC
Labels: wontfix
