### ISSUE TITLE
in groups always "... has updated the group"

### ISSUE THREAD

**Issue by xseddx** [signalapp/Signal-Android#10362] opened 2021-01-07 19:00 UTC
### Bug description
Describe here the issue that you are experiencing.
In a signal group we have an issue.
It occours every time a specific user opens the group on an android smartphone

All other members of the group get the message "<username> has changed the group"
I reinstalled the app and restored all messages, but there is no change.

I don't know, what it could be. There is not matter, if the user is admin or not.

In the privat chat with the specific user, I alway get "<username> has changed profilename from <name> to <name♥♥>" but on her smartphone the name is just <name>

**Comment by alan-signal** [comment] 2021-01-07 19:24
Should be resolved in 5.1 which is in beta now.

Closing as a duplicate of #10344

**Closed by alan-signal** 2021-01-07 19:24 UTC
