### ISSUE TITLE
New phone number cant message more than 10 contacts

### ISSUE THREAD

**Issue by mollyuser** [signalapp/Signal-Android#12182] opened 2022-04-20 12:38 UTC
When i register my new phone number and i want to contact my friends that i have a new number, it pauses at the 11th contact. Notifying more than 10 contacts isnt possible with signal. This is really steange since everyone has more than 10 contacts. I hope this is a glitch since the new captcha is popping up every second contact i message, the app is really unfriendly to new users.

**Comment by clauz9** [comment] 2022-04-20 17:10
Use the issue template, please! 

I would like to try this myself 🤔  can I get some repo steps ?
are you using a custom ROM ? and what version of Signal are you using ?

**Comment by mollyuser** [comment] 2022-04-20 19:05
I am using Molly v5.34.9-2-FOSS. I register and then start contacting all my contacts tgat i have a new number. Every 2 or 3 contacts i get a captcha that i solve and then i can go on, but every time when i send message to the 11th contact the messege gets paused and no captcha shows up. From then on its stuck. So i can only talk to 10 contacts.

**Comment by mollyuser** [comment] 2022-04-20 20:56
Just tested this also with Signal v5.35.3 , same issue, the farest i came was adding 14 contacts before rest of the message got paused. I called 3 contacts and ask them to add me, because they were paused, they could message me and i recieved it, but when i send a message back it stays paused and the cirkle keeps rotating. I think the server anti span is too sensitive for new users.

**Comment by clauz9** [comment] 2022-04-20 20:58
I suppose you don't use Play services right ? 
Also, a debuglog would be helpful from that Signal 5.35.3 instance

**Comment by mollyuser** [comment] 2022-04-20 21:02
I dont use google play services indeed, i already deleted both apps because it was frustrating. I will do it tomorrow again and send thedebug log. Didnt know it was needed since it happens al the time if u are a new user, there is no way around it.

**Comment by clauz9** [comment] 2022-04-20 21:15
It does not happen all the time, and it has nothing to do with new users, it's just that you're not using play services, and you are sending multiple messages to multiple people, so probably as far as the server is concerned, that is spammer behavior 😄 

A debuglog would help the developers isolate the behavior that triggers the captcha, and debug that stuck message issue 🤔

**Comment by mollyuser** [comment] 2022-04-20 21:22
Well the first 10-12 contact i add, i already do like 4-5 captchas , so how can the server still think i am spam? And after that i cannot message anyone, and not activate new captchas to prove i am human.

**Comment by mollyuser** [comment] 2022-04-20 21:23
I will share a debug log tomorrow, hope someone can solve this. Thanks for the help already.

**Comment by mollyuser** [comment] 2022-04-21 08:49
https://debuglogs.org/android/5.35.3/d70a1856eb92ec27907c3566f7e1608292be076796b0814678dddecc975b2e7b

**Comment by mollyuser** [comment] 2022-04-21 08:50
I dont know where to post the debug log, so i did it right there. Maybe you can remove it when you copy the link. Thank you

**Comment by clauz9** [comment] 2022-04-21 09:32
thanks for  adding a log 👍  
Private info from the logs, is generally redacted... and the logs themselves get deleted after 30 days from the Signal servers. 
But wait for a developer to see it, developers are the ones that have "-Signal" attached to their name

**Comment by greyson-signal** [comment] 2022-06-20 12:53
Closing as duplicate of #12289

**Closed by greyson-signal** 2022-06-20 12:53 UTC
Labels: wontfix
