### ISSUE TITLE
4.25.9 crashes at start

### ISSUE THREAD

**Issue by LinuxArie** [signalapp/Signal-Android#8186] opened 2018-09-07 10:56 UTC
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I try to open Signal 4.25.9 it stops

### Steps to reproduce
cleared the data, rebooted the phone, no result

uninstalled the app and reïnstalled it, restored the backup, no result

### Device info

**Device: Nokia 3.1
**Android version: 8
**Signal version: 4.25.9

### Link to debug log
Signal does not start, so I don't have a debug log

**Comment by jrcresawn** [comment] 2018-09-07 13:59
This issue appears to be a duplicate of issue #8184.

**Comment by greyson-signal** [comment] 2018-09-07 15:16
Closing as dupe. Please continue discussion at #8184. Thanks!

**Closed by greyson-signal** 2018-09-07 15:16 UTC
