### ISSUE TITLE
Unable to use the app from the Store: Signal is locked

### ISSUE THREAD

**Issue by AlexTrotsenko** [signalapp/Signal-Android#10665] opened 2021-01-15 22:03 UTC
I have installed the app from the Google play store several days ago. 
I don't remember me doing any extra set-up in the settings.
Unfortunately when I received my very 1st notification and tapped it I got strange lock screen displayed.
There it's written "Signal is locked" and "Enter your passphrase" placeholder. 
As far as I see someone had similar issue.
https://www.reddit.com/r/signal/comments/kekgrs/setup_signal_with_pin_its_now_asking_for_a/
However I have only Fingerprint and graphical pattern in the system and no textual password to enter.

I have submitted debug log so that you can get some more info.
https://debuglogs.org/dd60dea5ed69f0032a4a8550db4f05163846012f4c42c44284003fa597ba67f9

**Comment by greyson-signal** [comment] 2021-01-15 22:24
Closing as a duplicate of #10367

**Closed by greyson-signal** 2021-01-15 22:24 UTC

**Comment by iamvitali** [comment] 2021-01-15 23:51
@greyson-signal but the original is also closed

**Comment by greyson-signal** [comment] 2021-01-16 01:05
Yep, and if you read the original, you'll see that's because it was resolved in 5.1.9 :) That's available to download now. There's a variation that isn't resolved, but the variation @AlexTrotsenko has should be fixed.

**Comment by iamvitali** [comment] 2021-01-16 12:24
@greyson-signal should I open a new issue for my variation then? Seeing I'm on 5.2.0, still locked out and all the tickets here are closed.
