### ISSUE TITLE
Signal sent the same SMS many times

### ISSUE THREAD

**Issue by zebastiane** [signalapp/Signal-Android#8268] opened 2018-10-10 12:42 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

I tried to send a SMS but due to bad signal (I was in the subway) it was not successful.
After Signal tried to resend the message over and over, and my phone asked if I still want Signal to send message because it was sending a lot of messages.
No matter if I tap allow or deny on the popup, it came back.
I had to restart my phone. After the restart, I opened Signal and the issue came back.
The SMS was not marked as sent.

After another restart I could send the debug log.

The person received ~200 times the same SMS.

Issues #6975 and #5997 describe the same issue.

### Steps to reproduce
- Bad/no connection or a sporadic signal like it is in a subway
- Send a SMS

I didn't try to reproduce because I don't want to spam one of my contacts.

**Actual result:** SMS is sent multiple times
**Expected result:** SMS is sent only one time

### Screenshots

I couldn't take a screenshot, but it is the same as in issue #8017.
I have only one SIM card.

### Device info

**Device:** Samsung Galaxy A5 2017 SM-A520F
**Android version:** 8.0.0
**Signal version:** 4.28.0

### Link to debug log

After restarting my phone I managed to sent a [debug log](https://debuglogs.org/a03f77d975837337dc6b15504eb9151aedb92b38196680228c3e018575591d1f).
I hope there is info about why Signal repeated the same message.

**Comment by greyson-signal** [comment] 2018-10-10 17:46
Hmm, it looks like what may be happening is that the message successfully sends, but the system tells us it failed, which causes us to try to send it again. I'll try to think of some ways to mitigate this problem.

In the meantime, if you're stuck in this message send loop, removing Signal as your default SMS app should prevent it from sending.

**Comment by zebastiane** [comment] 2018-10-15 19:41
I used the app without problems since the issue.
Today I could send messages with no error but this evening the issue came back with the same SMS as last time.
I wasn't using the app, a notification said a message couldn't be sent and the loop came back.
~70 SMS were sent, the same as last time. 
This time I deleted it, hoping the issue won't come back. 
[Here is a debug log](https://debuglogs.org/a07afcf1a430d91bb0a9aa0bd212463effaafcebd50863a0b0d0d2b468a29689) after a reboot and many crashes.

**Comment by zebastiane** [comment] 2018-10-30 17:49
Two days ago, I got a lot of Signal ringtones without any notifications and nothing in the app.

This time no SMS were sent, nothing received, but I submitted a [debug log](https://debuglogs.org/3cdd35cb5e9ed75c951ebcb06b18958c54a0bebbacc63f0d3fab0eb4a4d1dbe0).
The `messageId (37750`) from the message who was sent multiple times in the previous log is present.

**Comment by jmayday** [comment] 2018-11-03 17:32
I experienced similar issue. Due to bad reception Signal was not able to send some of my messages. After some retries all of messages were marked as sent. Receiver got around 36 messages! (while I sent only 3 or 4 distinct messages). This is critical issue as it might cause extra charges (depending on carrier, billing rates etc).

**Comment by PierrickV** [comment] 2018-11-04 22:08
Same issue with (really) bad reception.

I have the notification "Message delivery failed." for more than 3 days now.

After restarting my phone, I had to disable authorization for Signal App to send SMS.

My contact are sending me messages like "FYI I'm blocking you because I keep receiving the same text".


**Device info**

Device : Samsung Galaxy A310F
Android version : 7.0
Signal version : 4.29.7

**Comment by nucleoce** [comment] 2018-11-07 18:02
Hello,

I have had this issue today and spammed someone, and this caused a mess in my life. #whocares

Do you need any log?

**Comment by greyson-signal** [comment] 2018-11-07 20:22
Hi, for anyone with this problem, the most useful thing you can give me is a debug log. Without that and me being unable to reproduce the issue, I can't get any closer to a solution. Thanks!

**Comment by peter-strom** [comment] 2018-11-08 20:42
https://debuglogs.org/f50c3e02e2d95a6aa2499dc17c56eef892c93f4fcd455672f66082f8e61713bf

When sending MMS over wifi: The recipient received 1 message

When sending MMS over 4g: The recipient received messages till I delete the MMS. (Last 3 times in the log)

**Comment by greyson-signal** [comment] 2018-11-12 20:43
@peter-strom Thank you for testing.

It looks like this is a different variation of WorkManager running the same job twice. The fix in b7b9554364377e3f441667a19b605882dcf06003 prevented the same job from running twice _concurrently_, but what's happening here is that a job is stopped partway through, but still finishes, and then is run again afterwards. 

I'll think about the best way to handle this and make a fix. Thank you!

**Comment by byrdhouse8806** [comment] 2018-11-12 21:33
Hay do basically someone had my phone and now it's tapped?? How do I fix it?

Chance Byrd

**Comment by greyson-signal** [comment] 2018-11-12 21:51
@byrdhouse8806 I'm not completely sure what you're saying, but if you're having this issue, long-press and delete the message to prevent it from continually retrying.

**Comment by greyson-signal** [comment] 2018-11-13 23:08
@zebastiane Just pushed changes that should address your version of this problem, and that'll be in the next beta release. Thanks!

**Comment by greyson-signal** [comment] 2018-11-14 04:32
Just released 4.30.4 to beta. After you folks get that, let me know if you're still experiencing the issue. Thanks!

**Comment by peter-strom** [comment] 2018-11-14 07:11
https://debuglogs.org/3bf3aa64c0371b33ccb68b811879bae885071c9a437370db9ce8b914047b08ba

I'm sorry to say that the issue is not fixed in 4.30.4

**Comment by greyson-signal** [comment] 2018-11-14 16:05
@peter-strom You have a different form of the issue that I'm fixing today :)

**Comment by jmayday** [comment] 2018-11-27 09:44
For me this is also not fixed in 4.30.8 (receiver got the same message 4 times).

**Comment by biolypl** [comment] 2019-12-24 13:10
Hello, the issue is still there. It costed the person noticeable money, so IMO it's critical. Unfortunately I got the phone after the accident and seems the logs were somehow cleared. Here are current log probably without the bug but I hope with other helpful information:  https://debuglogs.org/ff567a95a54835adc664b22f70b4710e6267bebcf57c79ef593a2334830fa86e .

**Comment by edhilgendorf** [comment] 2020-06-13 01:04
Same issue here. I'll try to get debug logs

**Comment by agramian** [comment] 2020-06-17 00:15
I just experienced this issue as well and it resulted in a very unpleasant phone call from one of my friends.  I'm seriously looking at alternatives to Signal because of this.  I'm using Signal `4.63.3`.  If someone lets me know how to submit the debug logs from Android I'm happy to send them over.

**Comment by edhilgendorf** [comment] 2020-06-17 00:21
@zebastiane  it is pretty easy to get a hold of logs:
From Signal -> Three dots top-right -> Advanced -> Submit debug log

**Comment by agramian** [comment] 2020-06-25 15:39
I sent the report below via the Help option through the app with the debug log attached as well.

Every single sms I've tried to send so far today has resulted in the spinning indicator for much longer than usual.  I received responses back before the indicator stopped meaning the other party had already received my message even though signal was indicating that it was still pending.  I deleted the messages to prevent them from causing this same retry issue from occuring.
Both parties I sent to are not on Signal and are on iPhones.  I'm on Android.  I have WiFi calling compatibility mode enabled and I tried enabling Sms delivery reports to see if it would have any impact which it hasn't.  This might be the last straw for me with Signal.  I'm sharing the issue details anyway so you don't lose additional users after me.

**Comment by zebastiane** [comment] 2020-07-28 17:45
Hi,
I encountered the error today, message sent 18 times.
The log is available here https://debuglogs.org/bcb0df7857dba86035ce6c60722fee79e9e3949a5b96ce01b3324000c41bf1f0

What happened: really bad connection I sent a message but got a "message not sent" error. I tried to resend the message, and this time it was successful.
I think it starts at `2020-07-28 18:22:28.259 GMT+02:00` in the log.

I don't know if it's related, but a couple of days ago I sent a message to a friend and got an error (message not sent). I didn't resend the message right after the error, but my friend replied to me, so the message was sent but Signal hadn't received the confirmation I think.

**Comment by edhilgendorf** [comment] 2020-07-28 17:53
Why is this issue, and all related issues closed? Is this being tracked somewhere else? If there's no intention/plan to fix, would be good to know. Thanks!

**Comment by fabquenneville** [comment] 2020-11-28 23:38
I've had people complain that they had received the same SMS from me dozens of times this week turns out being from signal. Is there someone working on this ?

**Comment by greyson-signal** [comment] 2020-12-01 15:07
@zebastiane Unfortunately your log expired, apologies. If you could post another when you get a chance, that'd be very helpful.

@fabquenneville Can you post a log after you notice it happens, and let me know the time the message-in-question was sent?

**Comment by agramian** [comment] 2020-12-23 02:13
This just happened again when messaging a friend who's not on signal.

Here's the debug log link: https://debuglogs.org/d966f48d33dfb446e931623ded5c38f73d082407bd44681a7e9283db5a9e16a8

It's been quite some time without a resolution on this.  Why not seriously consider my previous suggestion of providing a setting to disable automatic retries or getting rid of that behavior altogether?  I'd rather have to manually initiate the retry than to look like a spam bot to people I'm communicating with!

**Comment by agramian** [comment] 2020-12-30 03:02
Any updates? This continues to happen on my device intermittently.  What else is necessary to help diagnose the issue and either try to fix it or else decide on another solution to the problem like providing a setting to disable retries?

**Comment by fabquenneville** [comment] 2020-12-30 14:04
I stopped using signal as it repeatedly messaged someone on my work phone so sorry I cannot offer logs.

**Comment by kbt12243** [comment] 2021-01-04 22:11
The same for me. It happened twice, so I just use my regular SMS app for SMS, and the Signal app for Signal messages.

**Comment by AdityaNair21** [comment] 2021-01-15 06:02
@greyson-signal 
Same error here, same thing as OP, if I pressed Allow or Deny it would reappear, and later someone received 30 versions of the same text. 
https://debuglogs.org/b8e3afeac2d1c17c780cfef345f1f8b12739bb39d9b6eaed374e6cf7f9ad9eef
I also have screenshots of the error message, if that helps.

**Comment by ostigaard** [comment] 2021-05-22 08:53
I have encountered the same issue. Hundreds of copies send to the recipients.
Huawei p30, two sims. (danish TDC and 3 networks)
Problem occurs on both sims, no matter if the sending sim was on or off when I hit send.
Recipients are not on Signal, so SMS or MMS are used.
There seem to be a pattern of 5 messages,, a few minutes without  and then another burst of messages.
How do I generate a log to attach?

**Comment by Ethan5150** [comment] 2021-05-25 19:20
Yep, same problem here - both my phone and my wife's phone - people regularly telling us they received a TON of the same message - causing a lot of frustration.  Please fix this Signal!!!

And since I'm Signal-griping - can you please make it so the desktop install can be done without a mobile number?

**Comment by nucleoce** [comment] 2022-01-26 07:43
I'm shocked that this is 'wontfix'
I actually never used Signal again for my SMS after this happened once.

**Comment by nigiord** [comment] 2022-01-26 09:18
I think this issue is a duplicate of https://github.com/signalapp/Signal-Android/issues/8390#issuecomment-903403572 that was fixed in August 2021.

Haven't tested myself though because I'm glad to keep SMS and Signal Messages separated on my phone.

**Closed** 2022-04-10 08:10 UTC
Labels: wontfix
