### ISSUE TITLE
Backup restore crashes signal: no such column: previews:

### ISSUE THREAD

**Issue by nExXxuS** [signalapp/Signal-Android#8666] opened 2019-03-07 09:31 UTC
### Bug description
When i try to restore a backup it crashes at the end, after loading last message

### Device info

**Device:** OP5
**Android version:** 9.0
**Signal version:** 4.34.8

### Link to debug log
https://pastebin.com/s9S0CTSL

**Comment by johanw666** [comment] 2019-03-07 13:28
No column "previews" . Is the backup made by the same version? Is this a very old installation (although extra columns present in the original data should not matter any more)?

My first guess from looking not too long at the long generated SQL query is that table mms somehow has no column "previews". Would manually adding it fix the issue?

**Comment by nExXxuS** [comment] 2019-03-07 13:45
Yes, backup was created with older version (from January i guess). By downgrading Signal i was able to restore the backup, finally. 


But IMO it should not fail in such a case.

**Comment by johanw666** [comment] 2019-03-07 14:35
Still a bug. Restoring a backup from a newer Signal with an older version is not supported, but the other way around should work.

**Comment by greyson-signal** [comment] 2019-03-11 03:29
Dupe of #8011. Going to fix this.

**Closed by greyson-signal** 2019-03-11 03:29 UTC
