### ISSUE TITLE
Call Buttons Toggle Reset When User Makes Call Window Minimized

### ISSUE THREAD

**Issue by trymeouteh** [signalapp/Signal-Android#8420] opened 2018-12-02 05:33 UTC
On Android (And maybe iOS) when you press the mute button during a call and then go onto another app and then go back to the signal call app the mute toggle shows it has not been pressed and to unmute your mic you need to tap the mute button twice. I am unsure if this is an issue with the other buttons such as the enable/disable camera button but it is a bug with the toggle mic mute button.

**Comment by gspencerfabian** [comment] 2018-12-11 06:02
This is still a issue. If you mute your mic during a signal phone call and lock your screen, it turns mute off.

**Comment by mueller-ma** [comment] 2019-03-29 07:12
If you switch to a different app and back to Signal during a video call, the "switch cameras" button is gone. You need to turn the camera off and on again to let the button re-appear.

**Comment by alan-signal** [comment] 2019-05-10 17:54
This bug though is resolved. Duplicate of #7827

> If you switch to a different app and back to Signal during a video call, the "switch cameras" button is gone. You need to turn the camera off and on again to let the button re-appear.

This comment is covered by #8221

**Closed by alan-signal** 2019-05-10 17:54 UTC
