### ISSUE TITLE
Backup restoration not prompted with external SD card

### ISSUE THREAD

**Issue by tuxayo** [signalapp/Signal-Android#7845] opened 2018-05-25 22:15 UTC
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Couldn't restore backup until we removed the SD card.
Even with the backup copied in both internal and external storage.

### Steps to reproduce
- make a backup (in our case it was another device)
- clear app data
- run the app
- see that there is no backup prompt
- copy the "Signal" folder containing the backup to external storage if it was in the internal storage or vice versa
- run the app
- see that there is no backup prompt
- remove the sd card
- reboot
- run the app
- see that the backup is prompted

Might be the counterpart of to #7692 (← which might needs to be reopened for other reasons)

### Device info
**Device:** Moto G3 (XT1541)
**Android version:** 7.1.2 (LineageOS for microG with GCM enabled)
**Signal version:** 4.19.3

**Comment by ckujau** [comment] 2018-05-27 01:33
Same here with a brand new Samsung Galaxy S8 (with whatever is their latest Android version installed):

**Device**  : samsung SM-G950F (dreamltexx)
**Android** : 8.0.0 (G950FXXU1CRB7, R16NW.G950FXXU1CRB7)
**App**     : Signal 4.19.3

Once the SD card was removed, the _restore_ prompt appeared. Thanks for the workaround!

**Comment by tjay31584** [comment] 2018-05-27 08:33
Brand new Galaxy S9, fairly new to Signal, Googled how to backup and restore messages and followed directions at this link:

https://support.signal.org/hc/en-us/articles/360001890291

So, I created the backup (which was made locally and I moved to the SD card), I moved the SD card from my S7 to the new S9, opened Signal, and never got the prompt.  I tried copying the backup folder to internal storage to see if that would trigger it, but still no prompt.

I googled the issue, found this thread.  Instead of physically removing the SD card though, I went to settings/device management/storage/storage settings and unmounted the card.  I then re-opened signal and was immediately prompted as expected.  Entered my code, and it appears to have restored. 

However, when I tried to register I now get "Unable to contact service.  Check network connection and try again."  Hopefully that's just a strange coincidence and it will work in a little while.

**Comment by greyson-signal** [comment] 2018-06-08 05:08
I believe this should be fixed as of 70c2a863cca7984fec072913148fb4651e9644e4 (which would be in 4.20.5). Please re-open if it's still an issue. Thanks!

**Comment by sweah82** [comment] 2018-06-18 17:20
I ran into the described case yesterday. Wanted to reinstall Signal and pushed the backup button in the settings menu. After some time i double checkt and saw a 'last backup: 22min'. So i reinstalled Signal, but there was no backup to restore. If the backup file was in /Android/data/org.thoughtcrime.securesms/files/Signal/Backups (is empty), it got deleted and i wasn' t abled to get my messages back.

**Comment by skorokithakis** [comment] 2018-06-20 00:44
I have the same problem. I changed phones and wanted to transfer my messages, I backed up on the old phone with no problem, but the new phone will neither see the `Signal` directory nor create any backups of its own (maybe because there are no messages, though).

**Comment by 1xPdd** [comment] 2018-06-21 10:53
I was having the same problem with the failed restoration with several recent versions of Signal (4.19.* and 4.20.*). The backup had been placed in /sdcard/Signal/Backups. No amount of messing with permissions, unplugging SD cards, or rebooting did anything. I could see in the log files that the directory was read but that no import attempt was made. After pulling my hair out, I found this thread and checked to see what was in /storage/[externalsdcard]/Android/data/org.thoughtcrime.securesms/files/Signal/Backups. There was no such directory but creating it and moving the back up to it solved the problem. Hope that helps someone else.

**Comment by skorokithakis** [comment] 2018-06-21 12:38
Hmm, that didn't work for me. How did you restore the backup in the UI, @1xPdd? I don't even see the option.

**Comment by haffenloher** [comment] 2018-06-21 13:20
@skorokithakis If Signal has not yet been registered (i.e. its app data has been cleared or it's a fresh install), it prompts you to restore upon starting the app, provided that it detects a backup file. After restoring, you go through the normal registration flow with SMS or voice call verification.

**Comment by skorokithakis** [comment] 2018-06-21 13:28
Thank you, @haffenloher. Unfortunately, clearing data and copying the backup over still didn't make Signal detect it. I'll wait, thanks again.

**Comment by 1xPdd** [comment] 2018-06-21 14:08
@skorokithakis. I cleared all storage and killed Signal. It finally detected the backup the next time I started Signal. I was pretty frustrated and was about to uninstall Signal. This seems a pretty poor design choice. I'm not sure why a small import button allowing the user to select the backup file is not possible.

**Comment by skorokithakis** [comment] 2018-06-21 14:14
@1xPdd I tried that again, this time putting the backup in the above directory but on the SD card. It worked after I did that, luckily. I agree, a button in the "restore backup" section (since there is one already) would have been much better UX.

**Comment by moxie0** [comment] 2018-06-21 18:04
Supporting external SD cards was a mistake. I got badgered into it by people here, but never should have done it. I think the action item for this ticket is to check both the external SD card location and the "external storage" location looking for a backup to restore, if there is an external SD card present.

**Comment by skorokithakis** [comment] 2018-06-21 18:54
I don't know, SD cards are extremely useful for backups. As you say, the bug is that the location isn't checked, not that SD is supported. Also, for some reason, selecting "backup" on my old phone put the backup on the root of the partition, not under the `Android` dir. That seems to me like a better location anyway, but I would like to mention the inconsistency.

**Comment by greyson-signal** [comment] 2018-06-21 19:00
@skorokithakis It's supposed to put it in the root. If it's in the `Android` dir, it'll get deleted when the user uninstalls the app. At least that's the case on internal storage. Maybe that folder on the external SD card doesn't get deleted? I have to investigate.

**Comment by skorokithakis** [comment] 2018-06-21 19:10
Ah I think that might be the problem. It backs up to the root but expects the backup to be in the Android dir. At least that's what I think worked for me (but I had the backup on all four possible locations).

**Comment by bbukowski** [comment] 2018-06-22 02:39
@greyson-signal It gets deleted there too.

**Comment by neurer** [comment] 2018-06-22 22:19
> It gets deleted there too.

Can confirm.

Placing it in something like `/Signal/Backups` on either internal or external storage sounds like a consistent thing to do and would re-enable the option to sync that path with apps like Nextcloud, which currently doesn't work with `.nomedia` in the directory tree.

**Comment by UserX404** [comment] 2018-06-23 01:56
Why not let the user choose the backup/restore path in the settings and during the registration settings?

**Comment by nekromoff** [comment] 2018-06-26 22:52
https://github.com/xeals/signal-back

**Comment by greyson-signal** [comment] 2018-06-29 21:32
Here's a rundown on what the issue is here:

1) Currently, if the user has an external SD card, we will store the backup there (and look for it there during the restore process).
2) Unfortunately, when storing the backup on the external SD card, it gets put in an app-specific folder that gets deleted when the app is uninstalled. This makes storing backup data in that folder a non-option.
3) There's no reliable way to store data in the root of an external SD card. Just obtaining permission to do so is a hilarious exercise that isn't practical for our purposes.

Given this, we've opted to revert to the previous behavior of always storing the backup in the regular 'ol `Environment.getExternalStorageDirectory()` -- which, despite it's name, is typically on internal storage.

We plan on shipping this change in 4.23.

Thank you!

**Closed by greyson-signal** 2018-06-29 21:32 UTC

**Comment by vbspam** [comment] 2018-07-12 18:12
@moxie0 I am just curious about argument behind "Supporting external SD cards was a mistake. I got badgered into it by people here, but never should have done it. ".  The thing is that being security inexperienced I see SD card as natural idea to backup location, just by curiosity I would like to know reasoning why it is not good idea?

**Comment by tuxayo** [comment] 2018-07-12 18:59
@vbspam 
>  The thing is that being security inexperienced I see SD card as natural idea to backup location

It's seems that it's a mess in Android to handle well all the cases because unfortunately, it doesn't seem so simple to use the SD card.

> I see SD card as natural idea to backup location

Me too, because is broken, then data on the SD card is still easily recoverable.

**Comment by SanZamoyski** [comment] 2018-10-18 16:39
@nekromoff 

many, many thanks for pointing signal-back. It helped me. Funny thing - when you import xml in SMS B&R, you need to put it into app's default directory with name like it's backup files.

Regards!
