### ISSUE TITLE
Reaction notification appears on mobile while read on desktop

### ISSUE THREAD

**Issue by lwesterhof** [signalapp/Signal-Android#9501] opened 2020-03-25 12:01 UTC
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
A reaction that is read on desktop is not marked as read on mobile. Mobile still receives notification about the reaction while reaction is marked read on desktop.

### Steps to reproduce
1. Someone reacts on a message from you
2. View reaction message on desktop
3. Unread reaction notification appears on mobile

**Actual result:** Unread reaction notification appears on mobile
**Expected result:** No unread reaction notification appears on mobile

### Device info
**Device:** Xiaomi Mi A2 Lite
**Android version:** 9
**Signal version:** 4.57.1 (6122) (v1.32.1 on desktop)

**Comment by rainerzufall** [comment] 2020-03-25 15:55
maybe somehow related:
**Signal desktop does not display a notification, when somebody reacts to one of your own messages**. 
It would make sense, that Signal desktop would also not send out read receipts to your mobile for reactions, when not even reactions from other people are shown via notification on desktop.

Discussion about this behavior and if it is really intended happens currently in the forum, you might want to chime in: 
https://community.signalusers.org/t/no-emoji-reaction-notification-on-desktop-really-intended/12707

**Comment by lwesterhof** [comment] 2020-03-25 16:09
> maybe somehow related:
> **Signal desktop does not display a notification, when somebody reacts to one of your own messages**.

It does display a notification on desktop for me.

**Comment by rainerzufall** [comment] 2020-03-25 18:52
Thanks for the info, that it works for you! I tested a bit more now - I do get a notification of a reaction when my desktop is backgrounded (not in focus). So it seems this is not related.
**Sorry for the noise in this issue!**

**Comment by EvanHahn-Signal** [comment] 2021-02-25 15:15
This is a duplicate of #4696 so I'm going to close. This is on our radar!

**Comment by KommX** [comment] 2021-02-25 16:46
@EvanHahn-Signal 
Are you sure? #4696 is a **pull request** that was closed 3 years before this issue was opened. Seems to some kind of typo, doesn't it?

**Comment by rainerzufall** [comment] 2021-02-25 16:52
It is PR4696, but from the Desktop repository: https://github.com/signalapp/Signal-Desktop/issues/4696
Most important info = it is on their radar 🥳

**Comment by EvanHahn-Signal** [comment] 2021-02-25 18:25
Whoops—I thought this was an issue on Desktop. Reopening.

**Comment by KommX** [comment] 2022-01-27 06:53
I can't reproduce this bug anymore in Signal 5.30.1 on Android.

**Comment by haffenloher** [comment] 2022-01-27 18:21
Yes, this got fixed a while ago, see also the closed Desktop issue: signalapp/Signal-Desktop#4696

**Closed** 2022-03-28 23:25 UTC
Labels: wontfix
