### ISSUE TITLE
Attachments and quoted replies not being sent

### ISSUE THREAD

**Issue by mfmansour** [signalapp/Signal-Android#10071] opened 2020-10-09 18:10 UTC
- [ X] I have searched open and closed issues for duplicates
- [ X] I am submitting a bug report for existing functionality that does not work as intended
- [ X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Problem refers to signal contacts, not SMS/MMS.
Never faced such an issue with years of use of signal.
Faced delays, due to obfuscation/circumvention, due to country I am located in.

Bug started on October 6.
Certain messages are not being sent. Getting the rotating (sending) circle indefinitely.
Those messages are:
1. Attachments (of any type or size)
2. Quoted replies
After 24 hours, I receive a "failure" to send message.

**Important to note:**
- Quoted replies sometimes get sent.
- Attachments never go through.
- Receiving all message types with no issue. 

This is probably a similar case: https://github.com/signalapp/Signal-Android/issues/10070
But missing log file, and much info, hence the repost.

### Steps to reproduce
- Send attached or quoted reply
- Attachment/quoted reply keeps trying to be sent
- Message gives a "failure to send" error after 24 hours of trying

**Actual result:** Messages are not being sent. Endless "sending".
**Expected result:** Messages would be sent immediately.

### Device info
**Device:** Pixel 3 (blueline)
**Android version:** 11 (6720564, RP1A.200720.009)
**Signal version:** 4.72.5
Signal package: org.thoughtcrime.securesms (doDiFGKPO1r)
Registration lock: false
Locale: en_US

### Link to debug log
https://debuglogs.org/76ad9e7af7ca911485e09fca3af8090d4b1dad17f2cb129fc04788657824e698

**Comment by Nisc3d** [comment] 2020-10-09 18:53
Thanks for the details and the debug log.
I see this line:

> org.whispersystems.signalservice.api.push.exceptions.PushNetworkException: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

So I think your issue and #10070 are both a duplicate of #10061.

**Comment by mfmansour** [comment] 2020-10-10 15:07
@greyson-signal  Please take note of this. Thanks

**Comment by josembosem** [comment] 2020-10-15 11:42
I am also facing the same issue on a pixel 2 xl on android 11 RP1A.201005.004.

**Comment by greyson-signal** [comment] 2020-10-15 15:03
Hi there, this is fixed in the upcoming beta, slated to go out today. Thanks!

**Closed by greyson-signal** 2020-10-15 15:03 UTC

**Comment by mfmansour** [comment] 2020-10-15 15:30
> 
> 
> Hi there, this is fixed in the upcoming beta, slated to go out today. Thanks!

Thanks a lot.
Appreciate your support.
