### ISSUE TITLE
Link Device Camera Issue

### ISSUE THREAD

**Issue by CommissarVoop** [signalapp/Signal-Android#12153] opened 2022-04-12 15:21 UTC
### Bug description
The issues is that when you want to add an device and the part where it does need to scan the QR code to link up, once opening or launching the camera part its takes a second when it freezes up the camera and making a still image or stuck.

### Steps to reproduce
- Open Settings
- Click on Linked Devices
- Click on the + icon or the add icon

**Actual result:** Then you open the link device option, the camera shows up a second passes by it freezes and nothing happens.
**Expected result:** There you can the QR code and lets you to use signal on desktop.

### Screenshots

N/A

### Device info

**Device:** Xiaomi Redmi Note 11 
**Android version:** 11 (MIUI 13.0.5)
**Signal version:** 5.35.0

### Link to debug log
https://debuglogs.org/android/5.35.0/1ae53f86b1e6d38821f5baf100c76118692ceb68c0d24cfeb9d1d5e650820de2

**Comment by greyson-signal** [comment] 2022-04-12 21:03
Closing as a duplicate of #12009. Thanks!

**Closed by greyson-signal** 2022-04-12 21:03 UTC
