### ISSUE TITLE
Migrating whatsapp chat to signal app

### ISSUE THREAD

**Issue by praveenvellaturi** [signalapp/Signal-Android#10399] opened 2021-01-09 12:38 UTC
Hello everyone,
I am representing many people and asking you to develop a code that can easily migrate our whatsapp chats to signal app, As many of our friends would ready to switch to signal, it would really help signal and ourselves.

**Note**: For **Telegram** there is already a software available in git which accepts **text** file of whatsapp chat and will directly import them into Telegram

**### Hoping this bug wouldn't be closed without a proper response from your side.**
Say hello to "privacy"

**Comment by AroraShreshth** [comment] 2021-01-09 14:55
This would be really important tool for migration from WhatsApp. It is really a big need.

**Comment by girinathtime** [comment] 2021-01-09 15:03
Can you tell me the name of the software which you mentioned for telegram to migrate chats.

**Comment by praveenvellaturi** [comment] 2021-01-09 15:12
Yeah sure you can get it here 
https://github.com/TelegramTools/TLImporter
Thanks

**Comment by bkqtnte10** [comment] 2021-01-09 15:16
dupe of #1014

**Comment by girinathtime** [comment] 2021-01-09 15:19
@praveenvellaturi  Thank You,
But i already went through this repo and tried it on my machine.
There is one complication with this, if we want to get the chats in 1:1 format then we need to login with  the second person's telegram as well  (which is not so cool). I thought there is some other software.
For saved messages its working fine.

**Comment by Genis-Sage** [comment] 2021-01-09 15:38
hey together
your dedication is great, but as stated in in [CONTRIBUTING.md](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md):
[GitHub is not a generic discussion forum](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md#github-is-not-a-generic-discussion-forum)

because:
_Bumping issues with a "+1" (or asking for updates) generates a lot of unnecessary email notifications and does not help anyone solve the issue any faster. Please be respectful of everyone's time and only comment when you have new information to add._


so you should open a thread on the [community forum](https://community.signalusers.org/) (or any other forum) to discuss your ideas

**Closed** 2021-01-11 04:57 UTC
