### ISSUE TITLE
T-Mobile / Moto X 2014 Unrooted / Wifi Connected / MMS 

### ISSUE THREAD

**Issue by Adalan** [signalapp/Signal-Android#2138] opened 2014-11-25 19:14 UTC
I've had this issue in the past, but was corrected. I've recently switched carriers from Verizon Wireless to T-Mobile. If I am connected to any WIFI and receive an MMS message, I can't open it. I get the "Download" button, but nothing happens. If I disconnect WIFI and hit download, I get the MMS.

Here's a link to a log: http://hastebin.com/oduwajemuv (taken after hitting the download button while connected to wifi).  --- couldn't connect to download

Here's another log: http://hastebin.com/obazuraquy (taken after hitting the download button while DISCONNECTED from wifi).  --- successfully downloaded MMS

**Comment by hlieberman** [comment] 2015-01-22 20:48
I am also a T-Mobile user and affected by this problem.  It seems to be network specific, rather than device specific - I have a Nexus 4, running Android 5.0.1.

**Comment by apmon** [comment] 2015-01-27 04:24
Could this be related to #1937? If yes, it lists a couple of work arounds until the issue is solved correctly in TextSecure.

**Comment by Adalan** [comment] 2015-01-27 13:28
If it is, none of those suggested fixes worked for me. At this point in
time, anytime I receive an MMS, I have to disconnect from WIFI to get it.

**Comment by eosrei** [comment] 2015-07-07 23:44
My workaround is also to temporarily disable Wifi.

I'm adding to this issue because it is the oldest open issue describing the problem; there seem to be many closed ones. This is an extremely common issue. Here are probable open duplicates: #2213, #2652, #2690, #2976, #3019, #3103, #3270.

**Comment by Adalan** [comment] 2015-07-07 23:46
I haven't had any issues lately.

**Comment by eosrei** [comment] 2015-07-07 23:48
I have just dealt with it again, so I decided it was time to update the Github issues on the matter. CM 12.0 T-mobile if that matters.

**Comment by Adalan** [comment] 2015-07-07 23:49
I'm on stock, unrooted, 5.1.

I'll do some tests just to verify.

**Comment by eosrei** [comment] 2015-07-07 23:54
Perhaps the problem is corrected by 5.1? CM12.1 isn't available yet for my device. It would be great if the maintainers could recommend 5.1/12.1 and close the other seven issues.

**Comment by skymoo** [comment] 2015-07-10 16:57
T-Mobile MMS doesn't work on WiFi only on Cellular data. In order to send/receive MMS on T-Mobile you need to use a cellular connection. Other SMS/MMS apps have an option to temporarily disable WiFi when sending/receiving MMS to workaround this.

**Comment by AlfonsoMuskedunder** [comment] 2015-07-11 09:53
I think my girl friend has the same issue. When WiFi is on, she cannot receive MMS. It works with mobile data though. 

The provider cannot be the problem: we're both on the same German provider, Simyo, and I can download MMS with WiFi on. We both have TS 2.21.0; she's still stuck on Android 4.1.2 (while I'm stuck on 4.2.2).

This is my first on GitHub, excuse me if I violated well-established standards by posting here. I have browsed the issues, but many were closed with the argument that issues should be fixed with an upcoming release.

I'd be willing to upload a debug log - is it safe to upload these unedited, or is it recommended to delete certain parts? (You see, I'm not very tech-savvy.)

**Comment by agrajaghh** [comment] 2015-07-11 10:19
> I'd be willing to upload a debug log - is it safe to upload these unedited, or is it recommended to delete certain parts? (You see, I'm not very tech-savvy.)

yes its safe, just the last two digits of your contact numbers are in the log

**Comment by notroot** [comment] 2015-11-04 00:35
I'm also experiencing issue with similar symptoms. 

Unrooted, Nexus 5X, T-Mobile

I always run into issues downloading MMS on WiFi. The gist below contains running into the issue. I was receiving messages fine while on the network, then got home and my phone connected to the WiFi and failures started. 

The last succesfull MMS was recieved at 18:01:15

https://gist.github.com/anonymous/9c0581c67e737a6cceb2

Just as a note, I ran into the same issue on my Nexus 5 before on Android 5.x but was able to fix it by modifying the APN setting to only use both IPv4 and IPv6. That same trick hasn't solved this issue.

**Comment by jeremymasters** [comment] 2015-11-04 02:42
Do you have WiFi calling enabled?

**Comment by notroot** [comment] 2015-11-04 03:50
I've tried both on and off with inconclusive results. It's hard for me to test without annoying my friends. 

At the time of that issue I had it on.

**Comment by jeremymasters** [comment] 2015-11-04 15:39
Have you tried changing the setting in signal for WiFi calling to see if that helps?

**Comment by notroot** [comment] 2015-11-04 19:13
Sorry, my answer was confusing. 
I have not enabled WiFi Calling on the phone. I had tried enabling "WiFi Calling compatibility mode" inside TextSecure just because I was trying anything to get it to work. 

I'll enable WiFi Calling on the phone and enable the compatibility and see if that helps.

**Comment by automated-signal** [comment] 2018-04-02 21:30
GitHub Issue Cleanup:
See #7598 for more information.

**Closed by automated-signal** 2018-04-02 21:30 UTC
Labels: mms
