### ISSUE TITLE
Don't show "share your profile with group" banner for empty profile

### ISSUE THREAD

**Issue by RalfJung** [signalapp/Signal-Android#6966] opened 2017-09-15 07:59 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Even though I never filled my profile, in every group I am in, there is a permanent banner to share my profile with the group. I tried hard and searched but found no way to get rid of this banner.

Profiles have been fairly recently added, and they're great! I am sure many people love them. However, I'd prefer to not use them, and I expect Signal to respect that choice. Right now, I have to say I feel coerced by Signal to use profiles. On first startup, when it asked to enter profile data, there was not even an option to say "No thanks, I don't want a profile" -- there only was "fill profile data later". That's the kind of UI I expect from software disrespecting their users, software that primarily wants to extract user's data. I am aware Signal does that, but then I have to wonder why the UI clearly tells me that the software does not want me to choose to not have a profile.

In every group chat, there now is a banner that lets me share my (empty) profile with the group. Clicking it, I again have the choice between sharing now (which I don't want to do) and cancelling, which leaves the banner enabled. There is no option, it seems (or it is well hidden), to just make the banner go away without enabling profile sharing.

### Steps to reproduce
- Never enter any data into the profile
- Join a group chat. There's a banner there taking ~15-20% of the screen space.
- Try to get rid of the banner that tells me that I can share my profile with the group. I tried swiping, tapping, and I went through the entire settings dialogue.

**Actual result:** The banner persists, in all group chats.
**Expected result:** There should be a way to make the banner go away without enabling profile sharing. Actually, given that my profile is empty, it should not even show the banner.

### Device info

**Device:** Moto E2 2015 LTE
**Android version:** 6.0.1
**Signal version:** 4.10.9

**Comment by p4nci** [comment] 2017-09-15 08:03
duplicate of https://github.com/WhisperSystems/Signal-Android/issues/6927

**Comment by RalfJung** [comment] 2017-09-15 08:16
Ah, it probably is. I searched for "share profile", while the term "share" doesn't appear over there, it seems.

**Comment by vvug** [comment] 2017-09-15 08:40
I fixed the title of #6927, there was indeed a "hide" instead of a "share".

**Comment by FeuRenard** [comment] 2017-09-15 08:40
It's not exactly the same, I think. You could rephrase your issue to something like: "Disable profile sharing banners while profile is empty"

**Comment by p4nci** [comment] 2017-09-15 08:52
@FeuRenard :thinking: probably you're right, but if the profile is empty the "share your profile with group" banner should not be visible at all

**Comment by RalfJung** [comment] 2017-09-15 08:55
Done. I would also add "please change profile configuration UI to clearly provide the option to not, ever, have a profile", but that one looks like it is deliberate. (Unfortunately.)

**Comment by RalfJung** [comment] 2017-09-15 09:04
FWIW, here's a work-around: <https://github.com/RalfJung/Signal-Android/tree/profile>

**Comment by p4nci** [comment] 2017-09-15 09:14
> @RalfJung "please change profile configuration UI to clearly provide the option to not, ever, have a profile"

for now, once you have set a profile there is no possibility to delete (https://github.com/WhisperSystems/Signal-Android/issues/6960)

**Comment by automated-signal** [comment] 2018-04-03 04:28
GitHub Issue Cleanup:
See #7598 for more information.

**Closed by automated-signal** 2018-04-03 04:28 UTC
