### ISSUE TITLE
Chat Backup generates no backup file

### ISSUE THREAD

**Issue by calando** [signalapp/Signal-Android#7763] opened 2018-05-04 14:29 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When trying to backup existing communication threads, the backup file is not generated. It is definitely not a memory problem, there is more than enough internal free memory available.

### Steps to reproduce
- Select 'Einstellungen' - 'Unterhaltungen und Medieninhalte' - 'Unterhaltungen sichern' (this is 'Settings' - 'Chats and media' - 'Chat backup')
- Tap 'Sicherung erstellen' (Start backup)

**Actual result:** Backup is started, message counter increments - and when all messages are done, the status is again 'last backup: never' (and no file is generated, not even the directories /Signal/Backups).
**Expected result:** backup file should be present in /Signal/Backups

Note that the backup does NOT start automatically for me - it did that only once. Now, even when I disable backups (thus clearing the non-existing files) and re-enable it, I get a new passphrase but the backup does only start after tapping the button. No problem so far, but I tried that now since two days and always get the same result ('last backup: never' and no file).
I also checked all chats manually and deleted quite some amount of messages (especially larger ones like videos), but this does not change the behaviour.
It also does not matter whether the /Signal and /Signal/Backups directories are present or not (I would assume that they are generated when not present, but that does not seem to happen as well, so I created them manually - again, no change of behaviour).

### Device info
**Device:** Sony Xperia Z1
**Android version:** 5.1.1
**Signal version:** 4.19.3

### Link to debug log
https://debuglogs.org/5e0e7e29f19f3cc535e7c84e530169402b8a57fff449be2b28e154253b19f79f

**Comment by jtracey** [comment] 2018-05-04 15:52
Do you have an external SD card? If so, try removing that and giving it another try.

The debug log is showing "java.io.IOException: Renaming temporary backup file failed!" from https://github.com/signalapp/Signal-Android/blob/e6f76159b0d1858718de355f6472aea7d2d3edf0/src/org/thoughtcrime/securesms/jobs/LocalBackupJob.java#L78

My guess is that there's something going on with the interaction between [`getExternalCacheDir()`](https://developer.android.com/reference/android/content/Context#getExternalCacheDir()) above, what [`getBackupDirectory()`](https://github.com/signalapp/Signal-Android/blob/fa99e8f0d0a530c0655fa25657d4f6eb44e78c08/src/org/thoughtcrime/securesms/util/StorageUtil.java#L18) is returning, and the "must be on same mountpoint" rule of [`renameTo()`](https://developer.android.com/reference/java/io/File#renameTo(java.io.File)).

**Comment by calando** [comment] 2018-05-04 21:59
Hi Justin, 

Seems to be a perfect analysis - ejecting the SD card did the trick. Would it possibly make sense to output a warning when the calls failed? 

Thank you so much! 

Cheers, 
Marco

Am 4. Mai 2018 17:52:48 MESZ schrieb Justin Tracey <notifications@github.com>:

**Comment by tribut** [comment] 2018-05-05 05:55
Possible dulicate of https://github.com/signalapp/Signal-Android/issues/7692
Should be fixed in 4.20

**Closed** 2018-05-05 09:37 UTC

**Comment by patrikhuber** [comment] 2018-05-29 10:17
@tribut I'm on 4.20.4 (Beta channel) and I've got this exact same issue, and there is no error message.
What are my options?

**Comment by patrikhuber** [comment] 2018-05-29 10:29
Aah - too bad :-) Thank you very much.

**Comment by DacodaNelson** [comment] 2018-05-30 20:35
So I know this is closed, but just wanted to note the beta channel literally just pushed an update for the Android app and this appears to have fixed the issue at least for me. Finally got the app to show a backup completed AND the Signal folder now has the backup file in it after manually running it. So - glad to see that's sorted.

For reference - Google Pixel XL running Android P DP 2 and the Signal App subscribed to the beta channel. Interestingly the Pixel XL doesn't have or support SD cards so it was odd to have this problem given so many people associated it with SD card insertion/removal, etc. But whatever, looks like it's fixed so good work and thanks!

**Comment by fallerOfFalls** [comment] 2019-04-29 10:44
This is happening for me. Nexus 5, running Lineage OS (Android 7.1.2), Signal version 4.38.3. I don't have an SD card.

**Comment by jtracey** [comment] 2019-04-29 15:08
@fallerOfFalls This issue was fixed almost a year ago, so it's unlikely to be the same bug. I'd file a new bug, with the issue template filled out, including a debug log.

**Comment by lefterav** [comment] 2019-10-13 16:29
I just had the same issue. Has a new bug filled in or not?

**Comment by fallerOfFalls** [comment] 2019-10-14 10:27
@lefterav I remember, I think, in trying to reproduce the issue in order to file a new bug report, I found a workaround, or a case in which it doesn't happen. I don't remember what I did though. But if you go through the steps to make a bug report you'll probably find it too.

**Comment by orion-v** [comment] 2019-12-08 19:16
I had the same issue today. I was not able to see the file inside Signal/Backups with windows explorer. Moving the file from the microsd Signal/Backup folder to microsd / using a file manager within the phone (Android v7.1.1 ) gave me access to the file from Windows 10. 

In my case, the microsd card is set to be used as internal storage.
