### ISSUE TITLE
Receiving MMS messages twice after about 4 days

### ISSUE THREAD

**Issue by nathanvy** [signalapp/Signal-Android#5396] opened 2016-03-29 18:11 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

A duplicate MMS or "picture message" is received after a period of about 4 days.  This does **not** appear to be a duplicate of #5355
### Steps to reproduce
- ask someone to send you an MMS
- wait

**Actual result:**
Receive the MMS as intended, but then receive it again about 4 days later.

**Expected result:**
Only receive the MMS once, when it is sent.
### Device info

**Device:** LG Nexus 5
**Android version:** 6.0.1
**Signal version:** 3.14.2
### Link to debug log

https://gist.github.com/899ad2de68957e3a7c86db4fedc4dd0d

**Comment by riyapenn** [comment] 2016-03-29 23:25
contact support@whispersystems.org

**Comment by nathanvy** [comment] 2016-03-29 23:34
I have, and was directed here.

**Comment by johanw666** [comment] 2016-03-29 23:49
Similar to https://github.com/SMSSecure/SMSSecure/issues/321 ?

**Comment by snaggen** [comment] 2016-03-30 07:59
I see this also, using the latest Marsmallow on my Nexus 5X. After reading the SMSSecure issue, this sounds very much like that. I get the first MMS as expected, then after a few days I get a message pointing me to the web for reading the message. So, it sounds likely that this is due to the provider are moving the message off the servers and Signal have not confirmed that it got the MMS in the first place.

**Comment by 2-4601** [comment] 2016-03-30 14:08
Related #5177 (or dupe?)

**Comment by fmikker** [comment] 2016-09-07 22:28
Can confirm that this issue is also present in my LG G4 as well. 

Device  : LGE LG-H815 (p1_global_com)
Android : 6.0 
Memory  : 39M (19.61% free, 256M max)
Memclass: 256
OS Host : LGEACI5R7
App     : Signal 3.18.2

**Comment by ashelley** [comment] 2016-09-14 21:57
Here to confirm this bug as well:

Device: Samsung S5 Model: SM-G900W8
Android: 6.0.1 (patch level june 1, 2016)
Signal: 3.17.0

**Comment by mchadrdk** [comment] 2016-11-02 08:40
Experiencing the same

Device: Oneplus 2
Android: 6.0.1 (patch level August 1, 2016)
OxygenOS 3.1.0
Signal 3.21.3
Carrier: Previuously Telia Denmark, now 3 Denmark

**Comment by smd2008** [comment] 2016-11-13 22:43
I also have this issue.  LG G3 Virgin Mobile Canada (Bell network).  Android 6.0,  Signal 3.21.3

**Comment by graffen** [comment] 2016-11-18 10:12
I am also receiving MMS messages twice. Usually within a few hours but sometimes after 1-2 days. 
  
Samsung Galaxy S7 Edge
Android 6.0.1
Patch level Oct 1, 2016
Carrier: 3 Denmark

**Comment by chrishii** [comment] 2016-11-21 19:51
Same issue for me, typically I get a duplicate MMS 3-4 days after the original.

LG G5, Bell Canada, Android 6.0.1, Signal 3.22.2.

**Comment by stephen-webresults** [comment] 2017-01-09 20:39
Issue is confirmed on an updated, unrooted Nexus 5x.  This problem existed in Marshmallow, persists in Nougat (same device).  MMS only.  Carrier: Virgin/Bell Canada

**Comment by andersekbom** [comment] 2017-01-19 10:54
Since most reports here seem to be from Bell Canada and 3 Denmark, I can confirm this bug on Swedish operator Telenor on an stock Nexus 5x running Android 7.1.1.

**Comment by LoweLand** [comment] 2017-01-31 21:55
Same issue here. Samsung S6. Bell Canada network.

Issue only occurs so far with MMS messages received from off-net. That is to say from customers of other carriers be they domestic (Telus, Rogers) or international (t mobile USA, Verizon). 

Android version:6.0.1

**Comment by xDeadpoolx** [comment] 2017-03-06 15:00
I have the same issue. 
Carrier : Bell Canada
Phone Sony z5 e6683
Previously with MM, now with Nougat (both had the issue). 
Signal version : 3.30.4

**Comment by andersekbom** [comment] 2017-03-06 20:26
I've only had this issue when communicating with non-Signal recipients. Recieving MMS from other Signal users does not result in repeated messages.

**Comment by graffen** [comment] 2017-03-07 13:18
@andersekbom, @LoweLand  Yeah it's only when receiving MMS from people outside of Signal. And it's starting to get _really_ annoying :( Enough so, that a couple of people I know have stopped using Signal altogether because of it. 

I wish this issue would get some attention from the devs - or at least that someone would tell us what more information they need to be able to identify and fix the issue.

**Comment by hessiebell** [comment] 2017-05-02 15:57
Same as everyone else.  MMS come in fine right away, then repeat three days later. This is very annoying and I'm probably going to stop using Signal if there isn't a resolve soon.

Carrier:  Bell Canada
Phone:  LG G5  RS988
Android Ver:  6.0.1
Signal Ver: 4.3.2

**Comment by moxie0** [comment] 2017-05-02 16:25
Like most MMS issues, this is a carrier-specific thing, and the fix will likely be slightly different for each carrier. If someone wants to tackle this, the best strategy is probably to observe the network traffic of the stock SMS app that came with the phone when receiving an MMS vs Signal.

**Comment by devlinzed** [comment] 2017-05-04 19:48
How can this be carrier-specific if the stock SMS app works?

**Comment by nlansing** [comment] 2017-05-09 15:23
Don't think this is a Signal-specific issue. Same problem occurred on Android Messages. Will test out stock SMS app next.

**Comment by nathanvy** [comment] 2017-05-09 22:59
I've never had the issue occur on any other app across 2 other devices
(Oneplus 3T, blackberry passport) with any app other than Signal.

Moxie seems to indicate that they have no interest in addressing this bug,
so I've stopped using Signal entirely.

**Comment by kasperkarlsson** [comment] 2017-05-12 06:41
Same problem on the following setup:

Carrier: Telenor
Phone: LG G4
Android Ver: 6.0
Signal Ver: 4.5.3

**Comment by stephen-webresults** [comment] 2017-05-12 16:51
I switched to using the stock SMS app for four days, I did not experience this issue.  I then switched testing to Google hangouts, no issue after an additional 4 days.  I switched back to signal, problem returned;  in my testing, the interval between duplicates is consistently within +/- 10 minutes of 72 hours.

Stock Nexus 5x / Canada, Bell Mobility

**Comment by moxie0** [comment] 2017-05-13 02:58
There's a chance this could be fixed in 4.6.0

**Comment by sabret00the** [comment] 2017-05-14 12:39
I'm seeing this also. Initially saw it on my LG G3 and now I'm seeing it on my LG G6, so it's a long standing problem.

I'll receive the MMS and then two days later I'll receive a message that says "I've sent you an EE Photo/Video Message. Go to https://ee.mms.ee.co.uk/eeuk/ Your message is valid for 7 days" and another that says "A Photo/Video message was sent to you but couldn't be delivered. A notification on how to view this message will follow shortly. Your password is:"

**Comment by johanw666** [comment] 2017-05-14 12:45
Apparently there are issues with Signal reporting to the provider the MMS has been delivered. Would it be possible for someone to place a network sniffer between Signal communication with the provider and the same with the standard MMS app to seer the differences?

**Comment by haffenloher** [comment] 2017-05-14 12:51
@johanw666 yes, that would be the way to debug MMS issues. There's a chance though that many of them are gone in version 4.6.0 due to 51d61445.

**Comment by sabret00the** [comment] 2017-05-14 12:59
4.6.0 is up on the Play Store as a beta, so I guess we'll find out in the next couple of days.

**Comment by sabret00the** [comment] 2017-05-20 10:48
I can confirm that this issue is fixed in 4.6.0 I received a picture message on Wednesday morning and haven't had the follow-up message.

**Comment by FaffeF** [comment] 2017-05-21 10:00
And I can confirm that the issue is still there this morning on 4.6.0, the second message was received 49 minutes after the first,

**Comment by graffen** [comment] 2017-05-22 06:44
I also still see this issue unfortunately. Received the second message after around 49 minutes as well.
Carrier: 3 Denmark

**Comment by stephen-webresults** [comment] 2017-05-22 16:35
Issue persists on 4.6.0, exactly as previously described.

Stock Nexus 5x / Canada, Bell Mobility

**Comment by moxie0** [comment] 2017-05-22 16:47
Are there people still seeing this on Lollipop+ devices?

**Comment by FaffeF** [comment] 2017-05-22 16:51
I'm running a Sony Z5 Compact with stock Android 7, on Swedish 3 carrier. Every MMS gets repeated.

**Comment by graffen** [comment] 2017-05-22 20:48
Yes, I'm seeing it on my Galaxy S8 with 7.0. 

null

**Comment by kasperkarlsson** [comment] 2017-05-23 19:29
I still have the same problem.

Carrier: Telenor (Sweden)
Phone: LG G4
Android Ver: 6.0
Signal Ver: 4.6.0

**Comment by deValmont** [comment] 2017-06-11 22:32
Same problem here. I keep on getting the same MMSs over weeks.

Carrier: Swisscom/Switzerland and Orange/France
Phone: Huawei Mate 9
Signal: 4.6.1.

**Comment by chuckmckinnon** [comment] 2017-06-25 15:53
Same here, MMS repeat a few days after the original message was received. 

LG-H831 (LG G5) 
Android 7.0
Signal 4.6.1
Virgin Mobile Canada (Bell Canada)

**Comment by idajon** [comment] 2017-07-04 06:20
Same issue. Does not seem to happen in other SMS apps.

Device: Sony Xperia XA1
Android: 7.0
Signal 4.7.4
Carrier: Vimla Sweden

**Comment by ongobongo** [comment] 2017-08-01 16:37
Same issue

Android 7.1.1 may 2017 security patch level
Signal 4.8.1
Carrier: 3 Denmark

**Comment by flatfourtwenty** [comment] 2017-08-14 13:24
Same issue 

Android 7.0, July 1st Security Patch
Signal 4.8.1
Bell Canada
Samsung Galaxy S8

**Comment by stephen-webresults** [comment] 2017-08-14 15:56
Issue persists on 4.9.8, exactly as previously described.

Stock Nexus 5x / Canada, Bell Mobility

**Comment by Lokdal** [comment] 2017-08-15 14:22
I have the same issue since I changed to Bell/Virgin network (Canada) a few months ago.
Device : One Plus 3
Android : 7.1.1 (and on previous versions too, I think as far as 7.0)
Signal 4.9.8
I submitted a debug log : https://gist.github.com/525605ff66f580a6667202aecb675356

**Comment by riyapenn** [comment] 2017-09-08 15:30
**Summary of providers with repeat mms**: 
- Telia, Sweden
- Telia, Denmark
- Telenor
- 3 Denmark
- Bell Canada / Virgin Mobile Canada
- Swisscom/Switzerland
- Orange/France
- Swedish 3
- Vimla Sweden

Additional logs for more recent Signal versions posted below: 

Device: Samsung Galaxy S7
Android version: 7.0
Signal version: 4.9.9
Provider: Telia, Sweden
Log: https://gist.github.com/919187bc407c39e92b24ff206e3f1f79

**Comment by Lokdal** [comment] 2017-10-23 19:46
The issue is still ongoing in version 4.11.5. I'm writing to support about this.
New log : https://gist.github.com/9a954b237630a898ec36fdb779624592

**Comment by DalaRille** [comment] 2017-11-19 11:49
Still the same issue on my **Nexus 5X** with Signal **4.12.3** (Swedish carrier **Telia**).
 
I get the first MMS as expected, then after aprox. 24 hours I get a message pointing me to 
the web in order to read the message.  Most likely this is due to the provider are moving 
the message off servers and Signal has not *confirmed* that it actually recieved the MMS?

This needs to be fixed. It's so annoying that many contacts are now uninstalling Signal 
to go back to stock sms app... 

Device : LG/Google Nexus 5X 
Android : 8.1.0 
App version: Signal 4.12.3 
Carrier: Telia, Sweden

**Comment by deValmont** [comment] 2017-12-03 11:17
Issue persists on the following setup:

Device : Huawei Mate 9 Pro
EMUI : 5
Android : 7.0
Signal : 4.13.6
Carriers: Swisscom/Switzerland and Orange/France

**Comment by gnoorod** [comment] 2017-12-04 16:41
Issue persists here:

Device : Huawei Nexus P (angler)
Android : 8.0.0 (4397986, OPR.170623.011)
Signal : 4.13.6
Carriers: Bell Canada

First MMS received: December 1st, 11h36
Duplicate MMS recevied: December  4th, 11h32

**Comment by flatfourtwenty** [comment] 2017-12-04 18:45
Same as above, 36hrs later I receive the same mms. 

Device  : samsung SM-G950W (dreamqltevl)
Android : 7.0
OS Host : SWHD2402
App     : Signal 4.13.6
Bell Canada

**Comment by johanw666** [comment] 2017-12-04 19:32
Of course the issue persists, nothing has been done to fix it.

**Comment by codeofcarson** [comment] 2017-12-19 15:47
Screenshots

https://drive.google.com/open?id=1xYLEvyCUwSgbtNh_sUT3gbELEwWjfg7S
https://drive.google.com/open?id=12ZDQnsTawsEV1SA8WQaVMapWTZlsA--J
Device info

Device: Google Pixel 2 (Bell Canada version)
Android version: 8.0.0
Signal version: 4.13.6
Link to debug log

https://gist.github.com/ea8351730a42f9d19c8bbc4f0bdf04d1

**Comment by UserX404** [comment] 2017-12-21 22:35
Same here. Receiving same MMS every 24h for 7 days.
Device : HTC ONE Mini 2 (memul)
Android : 7.1.2 (LOS14)
App : Signal 4.13.6
Carrier: Telering Austria

**Comment by cwillhelm** [comment] 2018-01-24 23:33
I am experiencing this issue as well, MMS are received a second time after 3-4 days, for every single one that is sent. I do not have this issue with other SMS/MMS apps.

Device: Moto Z2 Play
Android Version: 7.1.1
App: Signal 4.14.10
Carrier: Bell Canada

**Comment by daveribs** [comment] 2018-02-11 16:44
This is SUPER ANNOYING! Just switched from Rogers to Virgin Mobile (Bell) and could not for the life of me understand where this problem was coming from.

Device: Samsung S8+ G950W
Version: 7.1.2
Signal latest
Carrier: Virgin/Bell

**Comment by MichaelHarrisBlockAble** [comment] 2018-02-20 23:24
This is happening to me on a Nexus 4, on Virgin Mobile in Canada. It's very annoying, and is the main reason I'm considering switching from Signal back to the default sms app.

**Comment by Lokdal** [comment] 2018-02-23 14:47
Issue ongoing since December 2016
Device : One Plus 3
Android version : 8.0 (FreedomOS 3.3)
Signal version : 4.15.5
App State : everything else functionning as normal
Ran out of time to attach my debug log, just wanted to let you know it hasn't changed.

**Comment by SebastianGrans** [comment] 2018-02-25 16:57
I also have this issue. 

Device: OnePlus 5
Android version: 8.0 (OxygenOS 5.0.2)
Signal verison: 4.15.5

[Debug log](https://gist.github.com/anonymous/ac54266ef1b86bbfd1941516a05b573f)

**Comment by magdesign** [comment] 2018-03-11 22:23
Same issue, any hack to fix this so far ?

Android Version: 7.0
Signal Version: 4.16.9

**Comment by nathanvy** [comment] 2018-03-11 22:41
They're not interested in fixing this issue.

**Comment by johanw666** [comment] 2018-03-12 00:01
There is a fix in 4.17: https://github.com/signalapp/Signal-Android/commit/694a5de2c33db3550c3c3a1d4ee9e4793dd741fe and https://github.com/signalapp/Signal-Android/commit/40d14698b8acae34be18c8138f623f1739f55e14

**Comment by nathanvy** [comment] 2018-03-12 00:03
Only took a few years.

**Comment by johanw666** [comment] 2018-03-12 00:12
You could say it's too late in the day. I can't even test it here because most providers here have dropped support for mms already.

**Comment by automated-signal** [comment] 2018-04-02 23:50
GitHub Issue Cleanup:
See #7598 for more information.

**Closed by automated-signal** 2018-04-02 23:50 UTC
Labels: help wanted, mms
