### ISSUE TITLE
unable to send pictures

### ISSUE THREAD

**Issue by tipuraneo** [signalapp/Signal-Android#9155] opened 2019-11-03 10:13 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
It is not possible to send messages via signal with attached pictures. Sending just text or other attachements works. Behavior might be related to the latest update. Appeared just since a few days ago.

### Steps to reproduce
- open contact
- plus sign
- select picture by preview or by gallery
- press send arrow

**Actual result:** Message is not sent (neither text nor image), editor becomes empty, image disappears.
**Expected result:** Image will be send and shown in message history.

### Screenshots
none

### Device info
**Device:** samsung GT-I9195I (serranoveltexx)
**Android version:** 4.4.4
**Signal version:** 4.49.14 (5611)

### Link to debug log
https://debuglogs.org/7574221d06566a34f5603ce16ce4fe4fcd3724c2c9c8311a01c7dc637f5b6776

**Comment by tipuraneo** [comment] 2019-11-03 10:22
Issue looks similar to https://github.com/signalapp/Signal-Android/issues/9149.

**Comment by greyson-signal** [comment] 2019-11-06 23:57
Closing as a duplicate of #9149.

**Closed by greyson-signal** 2019-11-06 23:57 UTC
