### ISSUE TITLE
Video call forces audio re-routing through loud back speaker and the switch to change speakers is replaced by the switch for front and rear camera

### ISSUE THREAD

**Issue by mareck8** [signalapp/Signal-Android#10206] opened 2020-11-17 16:30 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Video call forces audio re-routing through loud back speaker and the switch to change speakers is replaced by the switch for front and rear camera

### Steps to reproduce
- start signal call
- open video function

**Actual result:** Audio is forced through back speaker and the switch to change speakers is replaced by the switch for front and rear camera
**Expected result:** Audio remains on front speaker, or at least some possibility to switch back to front speaker.

### Device info

**Device:** Ulefone Armor X5
**Android version:** 9.0
**Signal version:** 4.75.8

### Link to debug log
https://debuglogs.org/9b905e2c73771b7adb0b7b65180b769c84a07b6de7ac5613af04c7028e459555

**Comment by szotsaki** [comment] 2021-01-23 14:17
This is a duplicate of https://github.com/signalapp/Signal-Android/issues/9796. If you also think so, please close this report.

**Closed** 2022-02-03 05:47 UTC
Labels: wontfix
