### ISSUE TITLE
Audio stops transmitting mid call

### ISSUE THREAD

**Issue by txtsecusr** [signalapp/Signal-Android#6432] opened 2017-03-23 05:26 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Audio stops transmitting at random. I am not touching mic mute button.

### Steps to reproduce
- Establish a call and wait - at some point other party cannot hear anything
    - within few seconds to few minutes; in most cases within a minute
- Packet is still being transmitted/received; verified on the router
- Once this happens subsequent calls have no audio at all. Force stopping then calling works until audio cuts off again mid call.
- Inbound audio is also affected, but with slightly less frequency
- It appears only happen on Wifi
    - Also happens on in-network call (both devices on same wifi and making direct connection)
    - Tried different wifi & ISP with different AP/Router and still cuts off
- Same device on CM13.0 (Android 6.0.1) appears unaffected
- Oneplus One (Bacon) on same O/S (Lineage 14.1/7.1.1)  appears unaffected
    - when both sides have no audio, force stopping G3 fixes it however force stopping bacon does not; hence G3 is the culprit
- Subsequent calls between device B (OPO/801) and device C (Xperia Z2/801) isn't affected. Call to G3 with either is affected until G3 force stops app
- Disabling battery optimization does not solve it

### Device info
**Device:** LG G3 D852 (identical hardware to G3 D850 AT&T)
**Android version:** 7.1.1 (Lineage OS Official)
**Signal version:** 4.0.1

### Link to debug log
Debug log doesn't contain anything useful beyond model & O/S

**Comment by j12i** [comment] 2017-03-23 11:21
I have a similar issue. (Let me know if I should open a new report.)
I tried calling with Signal for the first time today. I use a Sony Xperia Z1 (C6903) with the latest stock ROM (Android 5.1.1), Signal is up to date as per Play Store (4.0.0).
I called a Signal user, me on WiFi, I think them too, they have the most recent iPhone I believe (the really big one).
_While they could hear me, I couldn't hear them at all._ We tried once with me calling them, once with them calling me, and then again after force closing the app on my phone. The result was always the same.

**Comment by hanswundersam** [comment] 2017-04-17 15:59
Can confirm this behaviour on my LG Nexus 5 with LineageOS 14 (Android 7.1.1) without Gapps installed. In calls with an iPhone 6 and another iPhone 7 my mic often suddebly stops working after 15min into the call. I can still hear people talking but they don't hear me anymore. In subsequent callsy mic continues to not work, only force-stopping Signal seems to work -- until it all happens again.

**Comment by icasdri** [comment] 2017-04-18 02:37
I can also confirm this issue on my LG device running Cyanogenmod/LineageOS, no Gapps. Exactly the same problem: my mic drops out (i.e. other end cannot hear anything I say, but I can still hear them fine) after a few minutes on a voice-only call. And refuses to work again (from call start) on subsequent calls until Force Stop. Then, I can call and get another few minutes before it happens again. Oddly, it seems if I activate video (i.e. make it a video instead of voice-only call), the issue does not arise.

**Comment by alcoolfire** [comment] 2017-04-24 05:52
I too can confirm this same problem occurring between two Google Nexus 5 phones running stock Android 6.0.1, no rooting. During a voice call, inevitably one or the other participant will stop hearing the other person. We'd been rebooting the phones to get it working again, but it doesn't last long. This makes Signal voice calling unusable so we are forced to switch to Skype or the POTS.

One more point, which may or may not be related. Up until the audio dies in one direction, one of the two phones always hears excellent quality audio. The other almost always hears static at the edges of words even though the rest of the word portions sound good.

Neither user is using earbuds, Bluetooth devices, nor any other peripheral device.

Had I a vote, I'd say this should be a very high priority bug to fix as it means for us that Signal voice calling is fatally flawed.

**Comment by hanswundersam** [comment] 2017-04-24 07:26
I've found out now how to work around the problem. When my mic goes off I can "revive" it by plugging in a cable headset. The headset works and after unplugging it again the built-in mic also works. But unfortunately only for a few minutes until the mic goes off again and I have to plug in the headset again. Needless to say that this makes Signal calls unusable except for family and close friends conversations (and even they start asking me why we don't switch to another app).

**Comment by moxie0** [comment] 2017-04-24 16:55
I have a Nexus 5 for testing, but can't reproduce this. I would need either a debug log or steps to reproduce in order to determine what's happening.

**Comment by alcoolfire** [comment] 2017-04-25 05:57
I've now got debug log files for you, Moxie. Unlike _every_ prior Nexus5-to-Nexus5 Signal voice call, this one took a very long time before the audio finally failed, but it eventually did. This is the log for the Nexus 5 that has static coming and going at the edges of words:

  Phone A (1st call):  [https://gist.github.com/501af383f908a469ed55302c1e981d64](https://gist.github.com/501af383f908a469ed55302c1e981d64)

And this is the log for the _same_ call from the other Nexus 5, which _never_ experiences static but did experience audio quality going up and down throughout the this particular call:

  Phone B (1st call):  [https://gist.github.com/c6f0819cce36119958244703606d4fe5](https://gist.github.com/c6f0819cce36119958244703606d4fe5)

In this particular phone call, it was the audio stream from A to B that stopped working, while B to A continued to work.

Both parties hung up and then phone B tried to call phone A again using Signal, *without* rebooting either phone nor doing anything else to address the problem. Phone A answered the call. B to A audio worked and A to B audio was still dead. Here is the log from phone B after that call:

  Phone B (2nd call):  [https://gist.github.com/2c5370cc7c3689705716dd3e4083712a](https://gist.github.com/2c5370cc7c3689705716dd3e4083712a)

I'm sorry, but I didn't get the log from phone A for this second call.

So far we have never had a call between these two phones in which audio doesn't eventually die in one direction, although this time we almost did. So far I also believe I can say that phone A _always_ experiences the static issue at least some of the time during calls between these two phones. Phone B has _never_ experienced the static problem.

It may not be relevant, but phone B also has the Skype app installed, whereas phone A does not.

The static problem is horrible. The dying audio problem is fatal.

**Comment by moxie0** [comment] 2017-04-25 06:49
Thanks, on the first call, approximately how long did you wait between the audio dropping out and hanging up?

**Comment by alcoolfire** [comment] 2017-04-25 07:05
I'm going to give a totally wild guess of less than 30 seconds, but I can't stand behind that at all. If the person whose audio has been cut off wasn't talking when it started, no one realizes it right away, so we've had some calls where that number was a lot longer. Even when we do realize something's odd, there's a period of confusion before certainty leads to anyone hanging up. Sorry, Moxie, I know that's not helpful.

**Comment by hanswundersam** [comment] 2017-04-25 07:52
Thanks a lot @moxie for looking into this. Here is my debug log from this morning: 

https://gist.github.com/9f0cab059c253a2a3e0b1ab7d66be82e

In this instance I had a test call with an iPhone 7 that lasted about 18 minutes before my mic muted. No video, both sides over wifi, me with cable headset (but this also happens without headset). As described in my previous post, I then unplugged the headset and the mic worked again. Plugging the headset back in allows me to continue the call normally until the mic goes off again later. It's as if the plugging/unplugging of a headset reinitialises the mic...

**Comment by moxie0** [comment] 2017-04-25 16:52
@hanswundersam How long has this been happening for you? Months, or did it just start with the last release?

**Comment by hanswundersam** [comment] 2017-04-25 17:00
@moxie0 Definitely not the last release since I was hoping this might fix it by coincidence. Rather several weeks or maybe 1-2 months. I intuitively linked it with the switch to WebRTC but I'm not 100% sure that the problem really appeared at the same time.

**Comment by moxie0** [comment] 2017-04-25 17:05
@alcoolfire @hanswundersam I have an APK that I'd like your help testing, could you email me at moxie+github@whispersystems.org?

**Comment by sigenc** [comment] 2017-04-25 20:31
I have the same error with nexus 6p - nexus 6p. Both running latest copperhead os release. 7.1.2. I never noticed this before. but today it happened quite a few times.

**Comment by txtsecusr** [comment] 2017-04-25 22:20
It happens within a minute in most cases. (LG G3) It definitely happens less while on the network (LTE).

I believe this has been problem since day 1 of new video/voice calling. I thought it was a minor bug so wasn't taking it seriously until I finally confirmed this was happening in such frequency. I am on the latest now. Unfortunately I've stopped making voice/video calls as it annoys other end when this happens.

**Comment by sigenc** [comment] 2017-04-26 19:11
I don't get it why you closed this issue. We have Nexus 5,  LG G3, Nexus 6P, and Sony Xperia Z1 with this problem. How would blacklisting nexus 5 solve this issue for the other phones?

**Comment by moxie0** [comment] 2017-04-26 23:35
Only debug logs I got were for Nexus 5, I'd need a debug log for other devices in order to investigate.

**Comment by txtsecusr** [comment] 2017-04-27 05:07
Here is log from G3

https://gist.github.com/714e20937316b247ff4f78b85d0c4516

**Comment by hanswundersam** [comment] 2017-04-27 10:47
Blacklisting the Nexus 5 ([4d889a4](https://github.com/WhisperSystems/Signal-Android/commit/4d889a45e25bd1e2298d991a6208f7c86f6eb9fa)) seems to solve the problem for me. No audio drops after this anymore. Thanks Moxie!

**Comment by sigenc** [comment] 2017-04-27 13:14
seems we need whitelisting here too...

**Comment by debfx** [comment] 2017-04-28 17:09
Debug log from a Pixel. Audio stopped transmitting after some minutes.

https://gist.github.com/8e4b70420b5ab30225e3966432d4bb84

**Comment by moxie0** [comment] 2017-04-28 20:22
@debfx Strange, I regularly test calls w/ a pixel for hours at a time and have never seen this. Do you see the same behavior whether you're using earbuds (wired headset), bluetooth, speakerphone, etc?

**Comment by cegg1** [comment] 2017-05-03 22:11
@moxie0 asked for debug logs from devices other than Nexus5. 

Here are some simultaneous debug logs, from both ends, that involve a Nexus4. At some point in the call the sound suddenly becomes like static/pulsating. You can tell someone is speaking but it's unintelligible. 

I've been experiencing this problem with all versions of Signal since WebRTC was introduced and it happens both on WiFi and while on cellular data. This did not happen with RedPhone calls. I am unable to identify what's triggering it. 

Sample 1 - after some time N5 starts hearing N4 with static/garbled/pulsating sound but N4 continues to hear N5 fine: 
Nexus5: https://gist.github.com/anonymous/b2ff37e334d736e205f8e9b3cbbb358a
Nexus4: https://gist.github.com/anonymous/d53ed67b9430ee8ae1319955d56cde7a

Sample 2 - after some time N5 starts hearing N4 with static/garbled/pulsating sound but N4 continues to hear N5 fine (a different occurence of the same problem):
Nexus5: https://gist.github.com/anonymous/748791c95f777c88b945c294e1f21cbe
Nexus4: https://gist.github.com/anonymous/984804721f079a23710fa6b10564921a

Sample 3 - Static sound (this time it's white noise) both ways, but the call continues and does not drop
Nexus5: https://gist.github.com/anonymous/16dd56c1781562c6f98303e3d27f1880
Nexus4: https://gist.github.com/anonymous/8aa611326db82864775ddb89f1b9f51c

Sample 4 - Call drops for no apparent reason
Nexus5: https://gist.github.com/anonymous/3adab792600c7390585feb8f9c5bb9dc
Nexus4: https://gist.github.com/anonymous/c41fb5b4a6a828e64fe1304f7efdacd0

N5 is on speakerphone, Stock Android 6.0.1
N4 uses wired headphones, Stock Android 5.1.1

**Comment by moxie0** [comment] 2017-05-04 17:40
Thanks @cegg1. Another question for everyone experiencing this, does it also happen when you have video enabled? Or is it only when you are doing an audio-only call?

**Comment by sigenc** [comment] 2017-05-04 21:26
for me with nexus 6 p it is only in audio

**Comment by moxie0** [comment] 2017-05-04 21:34
@sigenc Have you tried reproducing this with video? You're saying that it explicitly *does* work with video, or only that you have only tested with audio?

**Comment by cegg1** [comment] 2017-05-04 21:39
In my Nexus4 <--> Nexus5 calls, the audio bug happens on video calls too. 

During a video call, the audio suddenly stops/becomes unintelligible one-way, and the video continues unaffected. Sometimes the video quality is so good that, while you can't hear/understand the person, you can read their lips! What I mean by this is that the audio is not unintelligible due to a slow internet connection (low bandwidth/high latency) as that would degrade video performance too.

**Comment by sigenc** [comment] 2017-05-04 21:49
@moxie0 I will try it tomorrow and leave a comment here. But last time video quality was good and no prblems with audio in videochat.

**Comment by alcoolfire** [comment] 2017-05-04 22:02
@moxie0: I've never done a video call between the two Nexus 5 devices cited earlier, but had done a few between my Nexus 5 and a Moto X PE. There were problems in those video calls, but mostly due to Wi-Fi issues, I think. However, we did have at least a couple of times where audio died in one direction. I'm not sure whether those were the same bug as our Nexus 5/Nexus 5 audio-only situations though. I say this because merely ending the video calls and reestablishing them would fix the dead audio, whereas we had to reboot our Nexus 5 phones before the audio-only calls would work again.

**Comment by moxie0** [comment] 2017-05-05 17:56
Here is a link to a sample WebRTC application:
https://mega.nz/#!N11RmIpD!93YKePtndsWnDxiDQTgTVt3lQTEIGAXZ8moBgFihdh0

It would be really helpful if someone who can easily reproduce this could do me a favor and see if the same behavior occurs with this sample APK.

1) Install the AppRTC APK on two devices that reproduce this behavior with Signal.
2) Go to the AppRTC APK settings and enable "Use OpenSL ES for audio playback" on *both* devices.
3) Make a "call" by having both devices join the same "room."

Thanks!

**Comment by sigenc** [comment] 2017-05-05 21:28
@moxie0 will do it tomorrow. My friend is not in town today...

**Comment by icasdri** [comment] 2017-05-07 00:42
> @moxie0 ... does it also happen when you have video enabled? ...

I have never experienced the issue with a video call. Video calls (where both sides turn on video) for one hour+ have been fine (maybe with some AV desync, but otherwise solid with no audio transmission issues). It's sufficiently long post-WebRTC audio-only calls that seem to have the issue (one side's audio stops transmitting) for me.

**Comment by bowensong** [comment] 2017-05-08 07:59
I have the same problem. I'm using a Nexus 6 and the other party is using a Nexus 5.
I know 4d889a45e25bd1e2298d991a6208f7c86f6eb9fa is an attempt to solve the problem, but I'm currently not able to verify it, because the other party and I are thousands miles away, and sadly the other party is not a techie and do not have access to Google Play due to firewall rules.
I'm trying to convenience the other party download a new APK file and manually install it on the Nexus 5, I might able to get back to you with some updates on this after the weekend if the other party managed to install the v4.5.3 version.

**Comment by sigenc** [comment] 2017-05-08 08:08
@moxie0 I tried the APK with my friend. No Problems on both sides no matter if "Use OpenSL ES for audio playback is active or deactivated". 

This is really strange. We tested 3 calls for like 15 min each one. 
I will test again in a few days with Signal and with AppRTC APK.
We will test wifi - mobile, wifi - wifi


Nexus 6P - Nexus 6P

**Comment by moxie0** [comment] 2017-05-09 18:04
I'm disabling OpenSL ES by default in 4.6.0

**Comment by bowensong** [comment] 2017-05-13 14:38
I know this has been closed, but as I premised a few days before, I've tested the v4.5.3 version between a Nexus 6 and a Nexus 5, and the Signal call lasted for more than an hour without any problems. Thank you @moxie0 , you have fixed it.

**Comment by moxie0** [comment] 2017-06-16 16:57
This issue now seems to be in tension with #6737.  Disabling OpenSL ES fixes the audio dropping problem on devices referenced here, but causes audio degradation in devices referenced there.

**Comment by txtsecusr** [comment] 2017-06-19 23:59
Noticed previously blacklisted devices are not present in current blacklist. Do we need to Will you be adding them back? I only see Pixel and XL in there.

**Comment by moxie0** [comment] 2017-06-20 04:18
@txtsecusr For Open SL ES? It's still a whitelist, OpenSL ES is disabled by default.

**Comment by jacksonmarty1313** [comment] 2017-12-24 14:17
I am having the same problem on my Galaxy S4. It also powers down several times during the day by itself. I am not an expert at all on these issues but i follow instructions very well, if someone could help me please. I absolutely love my phone and do not want to invest in another. Thank you so much.

**Comment by calmingSurf** [comment] 2018-01-23 23:02
I am having this issue on a Comcast VoIP using a Panasonic phone and on an iPhone. The only commonality seems to be that they are both on the same Wi-Fi.

**Comment by automated-signal** [comment] 2018-04-03 02:19
GitHub Issue Cleanup:
See #7598 for more information.

**Closed by automated-signal** 2018-04-03 02:19 UTC
Labels: bug
