### ISSUE TITLE
Federation

### ISSUE THREAD

**Issue by notramo** [signalapp/Signal-Android#10660] opened 2021-01-15 17:39 UTC
Signal servers are down.
If Signal would be federated, like [Matrix](https://matrix.org) (which is **open source, encrypted**, and has unique cross-device verification feature, and **doesn't even require your phone number**), it could be possible to select another server, which is less overloaded. E.g. similarly how the matrix.org homeserver is overloaded, but you can choose from [many other free servers](https://publiclist.anchel.nl/), and talk to everybody, just like with e-mail.

**Comment by Dafnik** [comment] 2021-01-15 17:48
Hello! You can search for, upvote, and create feature requests for Signal here:

https://community.signalusers.org/c/feature-requests/17

You can even use your existing GitHub account: simply choose the GitHub option under the Log In menu at the top right.

I hope this helps. 😇 

P.S. I copied this text from @Frivolous2

**Comment by phil294** [comment] 2021-01-16 11:19
I opened a thread about Matrix protocol adoption here: https://community.signalusers.org/t/make-signal-use-matrix-protocol/23282
But it merely reflects my view, maybe you need to create another one with your specific suggestion.

**Comment by dreua** [comment] 2021-01-18 14:04
@notramo This is 100% not a bug please consider closing this issue.

**Closed** 2021-01-28 16:43 UTC
