### ISSUE TITLE
Possible to forward quoted message to other chat

### ISSUE THREAD

**Issue by mueller-ma** [signalapp/Signal-Android#9232] opened 2019-11-28 07:13 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
It is possible to forward a quoted message to a different chat.

### Steps to reproduce
- Open conversation A
- Quote message
- Close Signal by pressing home button
- Share image or text from other app to Signal
- Select conversation B
- Send message

**Actual result:** In chat B the quote from A is visible.
**Expected result:** Quotes shouldn't be forwarded.

### Device info

**Device:** Oneplus X
**Android version:** 7
**Signal version:** 4.50.6

**Comment by bme13** [comment] 2019-11-28 09:35
Seems a duplicate of https://github.com/signalapp/Signal-Android/issues/9175.

**Closed** 2019-11-28 09:49 UTC
