### ISSUE TITLE
Reactions to messages in restricted group chats reveal phone numbers of group members who reacted

### ISSUE THREAD

**Issue by mahurinj** [signalapp/Signal-Android#12983] opened 2023-06-07 03:59 UTC
Let's begin with a checklist: Replace the empty checkboxes [ ] below with checked ones [x] accordingly. -->

- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When you have a group where only admins can post, other members can still react to posts. This reveals their numbers to the other members which is undesirable. Either non posting members shouldn't be able to react, or a way to react without revealing numbers should be figured out. I'm assuming the latter isn't possible so I would suggest the former. But if the latter is possible that would be lovely too, as that is a desirable feature. However, the privacy of member phone numbers is the first priority.

### Steps to reproduce
Create a group with admin only posting permissions. Add other non admin members who haven't previously exchanged messages/participated in the same groups. Have the admin post something. At this stage, members won't be able to see each others phone numbers, which is desirable in large public groups. Then have a member react to the admin's post.

**Actual result:** After reacting, the other members can now see that member who reacted's phone number in the group details. 

**Expected result:** Ideally either, a reaction would not reveal a member's phone number, or a reaction simply wouldn't be possible, as they don't have posting rights in the first place. Whichever is needed to preserve the privacy of non posting members phone numbers.

### Device info

**Device:** Pixel 4a, Pixel 5a, iPhone also, though not sure the version
**Android version:** 13
**Signal version:** 6.21.3

**Comment by eugenezach** [comment] 2023-07-06 02:04
I've also experienced this. We'd like to have an announcement list that people can join without sharing their phone number. I didn't expect reactions to share numbers.

**Comment by greyson-signal** [comment] 2023-07-06 13:32
Hi there, at this current moment, Signal does not hide your phone number from people you send messages to. That's just not how it works right now. We've publicly stated that we're actively working on phone number privacy. Doing it right just takes longer than you would think :) Closing this issue because the behavior is currently working as intended, but we'll have this resolved down the line.

**Closed by greyson-signal** 2023-07-06 13:32 UTC
