### ISSUE TITLE
When sending picture it adds other pictures I did not select

### ISSUE THREAD

**Issue by wozney** [signalapp/Signal-Android#11137] opened 2021-03-25 19:29 UTC
### Bug description ###

When I send a person a image it is adding other images I did not select. Some of the pictures are pictures that I sent another person and another one was sent to me from someone else.

The messages I sent happened at this time, so you can look it up in the bug report

March 25, 2021, 1:01:20 PM EST
March 25, 2021, 2:36:48 PM EST

### Steps to reproduce ###

Send and receive mutiple images to different People. I have tried reproducing and its not happening anymore. 

**Actual result:**

Shows mutiple images in chat when i only selected one image to send.

**Expected result:**

Should only send the 1 image I selected.

### Screenshots ###
I have blanked out some details of the image for privacy reasons.

![Screenshot_20210325-145047_Signal](https://user-images.githubusercontent.com/31085107/112530129-75fe6700-8d7c-11eb-836d-0b17e2140cfe.jpg)
![Screenshot_20210325-145053_Signal](https://user-images.githubusercontent.com/31085107/112530130-7696fd80-8d7c-11eb-981f-27388f77d9a7.jpg)

### Device info ###

**Device:** 
Galaxy S20 Ultra 5g  SM-G988W

**Android version:** 
11

**Android Kernal**
4.19.113-20937596

**Signal version:**
5.5.5

### Link to debug log ###
https://debuglogs.org/54a48568b7011b82b8cb22809618454698267d5efa551d2c63bd0a639725089f

**Comment by wozney** [comment] 2021-03-25 20:31
It happened again when someone sent me an image. 

I sent an image 5 mins before and the person sent me a image and the image i sent was attached to the image he sent

![Screenshot_20210325-162917_Signal](https://user-images.githubusercontent.com/31085107/112539563-8700a580-8d87-11eb-9e23-f0945cd221a5.jpg)

**Comment by attila-lendvai** [comment] 2021-07-13 20:05
you're not crazy, i have a contact that experiences this.

he even sees my message displayed on his side with a random image attached to it, as if i have sent that image to him, even though that image is not even present on my phone.

it seems to be happening only with images that have been received by his signal app in the past.

**Comment by attila-lendvai** [comment] 2021-07-13 20:23
this bug is a duplicate of https://github.com/signalapp/Signal-Android/issues/10247

**Comment by greyson-signal** [comment] 2021-07-25 18:52
Closing as a duplicate of #10247

**Closed by greyson-signal** 2021-07-25 18:52 UTC
