### ISSUE TITLE
Calls on Fairphone 2 are echoing again

### ISSUE THREAD

**Issue by sadavat** [signalapp/Signal-Android#8935] opened 2019-07-20 18:04 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal calls made on the Fairphone 2 running the Android 7 stock ROM have an echo, even though this was briefly resolved in Signal 4.39 when FP2s were added to the AEC blacklist with https://github.com/signalapp/Signal-Android/pull/8733.

Faulty hardware AEC is a longstanding issue on the Fairphone 2 (see https://bugtracker.fairphone.com/project/fairphone-android-7/issue/179). Calls did not echo on Signal 4.39 when the FP2 was added to the AEC blacklist, but from Signal 4.40 onwards the echo is back again (no pun intended). 

I’ve experienced the echo when calling between two Fairphone 2s on Signal 4.43.8 and many previous versions (except 4.39). When I first experienced the problem both my and my partner's FP2s were running the stock Android 7.1.2 ROM, and echoes were heard on both phones during Signal calls. 

Since first experiencing this problem I have installed LineageOS (Android 9) on my FP2, while my partner's FP2 is still on the stock Android 7.1.2 ROM. Now, when I call my partner’s FP2 I hear my own voice echo back to me on my phone but she doesn’t hear her voice echo back on her phone. I think this means that the AEC issue is on her stock Android 7 FP2.

As per the issue on the Fairphone bugtracker, other FP2 users using the stock Android 7 ROM have had the same experience where the echo was gone in Signal 4.39 but has returned as of 4.40 onwards.

### Steps to reproduce
- Make a Signal call with a Fairphone 2 running the stock Android 7 ROM.

**Actual result:** When you make a Signal call with an Android 7 Fairphone 2, echoes are heard throughout the call.
**Expected result:** Fairphone 2 Android 7 Signal calls are echo-free.

### Device info

**Device:** Fairphone 2
**Android version:** 7.1.2
**Signal version:** 4.43.8

### Link to debug log
Not sure it’s relevant, but I can provide one if necessary.

**Comment by spipau** [comment] 2019-09-20 08:23
I can confirm this issue and I would be happy if you could resolve it again.

**Comment by billie80** [comment] 2020-07-25 12:00
Same here for a contact of mine. According to this issue
(https://bugtracker.fairphone.com/project/fp2-android9/issue/25) this will be fixed for the Fairphone 2 with Android 9. They now will use Androids software-based AEC instead of the hardware AEC. So it should work then but needs to remain in the Blacklist.

**Comment by billie80** [comment] 2021-04-24 22:36
As the Fairphone 2 now has received Android 9 the problem is gone. There is some initial echo at the start of the call but then it is fine.

**Comment by jimio-signal** [comment] 2022-01-28 05:09
ahoy there! we made some improvements to the echo-cancellation logic in our android 5.29 release. I’m running through some old AEC issues and resolving them now; please try out the latest release and holler if you have any issues :)

https://github.com/signalapp/Signal-Android/commit/47134e19f18fe7f6e611b7c228520e5d5c0791f5

**Closed by jimio-signal** 2022-01-28 05:09 UTC
Labels: calling, wontfix
