### ISSUE TITLE
Profile picture

### ISSUE THREAD

**Issue by inkSpace-Abhi** [signalapp/Signal-Android#10692] opened 2021-01-17 12:10 UTC
Profile is showing same as my contacts
And not as in the signal app

**Comment by batunii** [comment] 2021-01-17 12:40
You can change that in the recent update by going to Settings>Chats>Use Address book photos, and switching it off. I am using a beta but I think it's available in the main version too!

**Comment by atarek1** [comment] 2021-01-17 13:21
@inkSpace-Abhi logs will be helpful.
Seems duplicate of https://github.com/signalapp/Signal-Android/issues/10656

**Comment by mufunyo** [comment] 2021-01-21 17:23
I would like to add to this that the behaviour currently appears to be inconsistent. Signal is showing initials for some contacts and address book photos for others.

The setting "Use address book photos" is also unhelpful, as it overrides the Signal profile photo even if one is available. The behaviour should be as follows:

Is Signal profile photo available?
* Yes -> Display Signal profile photo
* No -> Is address book photo available?
   * Yes -> Display address book photo
   * No -> Display profile name initials

**Comment by ctribout** [comment] 2021-01-23 10:16
I don't think it's unhelpful or inconsistent at all. On the contrary. Please keep that setting as it is!

Personally, I don't want to display users' Signal profile pictures, I only want to see my own address book pictures: anything else would be some confusing noise I don't feel I need in a messaging app.
Currently I can quickly find my contacts using the pictures I've always known, without worrying about ever-changing meaningless unrelated pictures I don't really care about when I just need to talk to someone.
In my usage, one contact = one (fixed) face picture to recognize him/her in a blink, and that's it. No extra noise around it.

Being forced to depend on users' own pictures only would waste my time when navigating through the conversations on the main page, really. I faced it this morning when I discovered that new profile concept: I took quite some time to find the contact I needed, as he had a new crazy random picture. Of course he can choose whatever he wants there, but why would he be able to change remotely in my app what I use as the main way to identify my contact threads?
I would even prefer to have no image at all, for no one, and fixed coloured initials only, rather than random pictures changing out of my "control".

The current setting allows all use cases and preferences : the legacy behaviour I use, as well as the ones mentioned in the posts above. So **please** don't remove that possibility.

**Comment by mufunyo** [comment] 2021-01-23 12:45
> I don't think it's unhelpful or inconsistent at all. On the contrary. Please keep that setting as it is!

First off, the inconsistency I mentioned is a bug. With the "Use address book photos" setting *disabled*, some contacts are still showing address book photos, and some initials even though they have address book photos. I think you can agree that you wouldn't want such random behaviour.

Second, everybody can be happy if the fallback behaviour I described is what happens if the setting is disabled, and it overrides any Signal profile photos with address book photos if the setting is enabled. However, I think nobody wants a combination of initials and Signal profile photos, when perfectly good address book photos exist on their phones, hence the fallback.

**Comment by mufunyo** [comment] 2022-01-28 22:21
As far as I can tell this is fixed, as it is currently using the fallback behaviour I described above.

**Closed** 2022-01-31 13:57 UTC
