### ISSUE TITLE
Messages sent via Google Now voice assist do not show up in signal but are sent - Android 7, Signal 4.16.9

### ISSUE THREAD

**Issue by jcollum** [signalapp/Signal-Android#7568] opened 2018-03-25 20:00 UTC
Probably a duplicate but I couldn't find it

I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Messages sent via Google Now voice assist do not show up in signal but are sent

### Steps to reproduce
- start Google Now by long pressing on the Home button
- say "Send text message to Alice" 
- dictate and confirm sending message 
- open Signal

**Actual result:** Message does not show in list of messages sent to Alice in Signal. Message does show in messages sent to Alice in default messaging app. 

**Expected result:** All text messages are in the same place. 

### Screenshots
Can provide if needed, but I don't know how I'd capture it without doing a screen recording. 

### Device info 
**Device:** LG G5
**Android version:** see title 
**Signal version:** see title

**Comment by FeuRenard** [comment] 2018-03-25 20:55
Duplicate of #4037 and #5803 and #7536.

Please search open and closed issues for duplicates before opening new issues!

**Closed** 2018-03-25 23:15 UTC
