### ISSUE TITLE
Echo only when I call someone

### ISSUE THREAD

**Issue by nsmarcin** [signalapp/Signal-Android#9589] opened 2020-05-05 20:02 UTC
- [x ] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I initiate video call I hear echo on my phone. This happens only when I start call. If other party calls me everything is ok.

### Steps to reproduce
- make video call to someone
- turn on speakerphone

**Actual result:** I hear my own voice (echo) while talking.
**Expected result:** Clear call

### Device info
**Device:** Samsung Galaxy S7
**Android version:** 8.0.0
**Signal version:** 4.58.5

**Comment by ozgurakyazi** [comment] 2020-05-14 17:35
Similar to #9351 and #8935 . Can you please add the callee phone info? When I face this issue, this is caused by the callee side, Xiaomi Redmi Note 5 Plus and Note 7 . Redmi Note 8 works like a charm, together with 2 different samsungs.

**Comment by nsmarcin** [comment] 2020-05-20 19:36
Hi, callee uses Xiaomi Mi A2 Lite. In my case only when I initiate call this happens.

**Comment by ozgurakyazi** [comment] 2020-05-21 08:56
So this makes your issue duplicate of or very similar to #9351 .  In the title, they mention about Mi A2 and in the comments Mi A2 Lite is also mentioned. I think we can close this and keep all the echo problems under one issue.

**Comment by 12people** [comment] 2020-08-02 09:47
Same issue.
Caller device: Fairphone 3
Receiver device: OnePlus 3T

**Comment by nsmarcin** [comment] 2021-01-31 11:29
In my case only when I initiate call the echo is present. I also noticed that when I plug in and out headphones during call problem is fixed. I don't have to use headphones, just plug them in and out. Maybe that helps to solve the problem.

**Comment by ozgurakyazi** [comment] 2021-02-03 20:28
@nsmarcin  Does this happen all different types of callees?   FYI, this echo issue is with the one who do not hear the echo. At least this is the case in almost other issues.

To understand your case, can you please share the phone model of the callee?   And does the echo exist for all different types of callee phone model? If so, it would be great to have that list here. Maybe all your callee phone models are present in the issues of this repo :)

**Comment by isaackramer** [comment] 2021-02-13 16:48
I am having this issue with Redmi Note 5. Other caller hears Echo. Does not happen with other apps.

**Comment by ozgurakyazi** [comment] 2022-01-27 06:26
yes it is definitely. You can add the mentioned phones to echo cancellation blacklist.

**Comment by jimio-signal** [comment] 2022-01-28 05:09
ahoy there! we made some improvements to the echo-cancellation logic in our android 5.29 release. I’m running through some old AEC issues and resolving them now; please try out the latest release and holler if you have any issues :)

https://github.com/signalapp/Signal-Android/commit/47134e19f18fe7f6e611b7c228520e5d5c0791f5

**Closed by jimio-signal** 2022-01-28 05:09 UTC
