### ISSUE TITLE
Regression: No option in context menu to copy text of media message

### ISSUE THREAD

**Issue by FeuRenard** [signalapp/Signal-Android#7472] opened 2018-03-08 18:10 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
It is no longer possible to copy the text of media messges. This behaviour is introduced by 4bdb2acd29f06ec0782f33e20b3c8290a002bef3.

### Steps to reproduce
- send a media message with text
- long-press this message

**Actual result:** No copy button available.
**Expected result:** A copy button should allow users to copy the text.

### Screenshots
![bildschirmfoto von 2018-03-08 19-00-15](https://user-images.githubusercontent.com/16167751/37167771-2b47fe24-2303-11e8-80a7-4e9e67909f4f.png)

### Device info

**Device:** AVD Nexus 5X
**Android version:** 7.1.1
**Signal version:** 4.17.0

### Workaround
Use the forward button and select any conversation. Then copy the text from the text input box at the bottom of the conversation.

**Comment by addumb** [comment] 2018-03-11 17:33
¯\\\_(ツ)_/¯

**Comment by art1fa** [comment] 2018-03-12 01:57
This was actually intended behaviour. The `copy` icon makes the user expect to copy all selected content, not just the (less noticeable) text. 
But technically, if we want to keep letting `copy` be "copy text", you're right of course. However I suppose the previously showing hint on long tap, saying "copy text" was probably not much noticed, because who's long-tapping a familiar icon?

**Comment by addumb** [comment] 2018-03-13 03:02
Yeah, that also makes sense. What about taking a long-press on the text enter into the usual text selection mode instead of the conversation selector mode?

This kind...
<img width="394" alt="screenshot 2018-03-12 at 8 00 45 pm" src="https://user-images.githubusercontent.com/225812/37320267-2abd4330-2630-11e8-8ac4-a04c84a97354.PNG">

The tap precision is a bit dicey, but... that's kind of the case everywhere.

**Comment by moxie0** [comment] 2018-03-13 17:27
I think we should just restore the ability to copy text on media items if they have text captions

**Comment by greyson-signal** [comment] 2018-04-04 16:44
Fixed in #7620.

**Closed by greyson-signal** 2018-04-04 16:44 UTC
Labels: bug
