### ISSUE TITLE
Disappearing messages ( Quote or Forward) 

### ISSUE THREAD

**Issue by faisal1995** [signalapp/Signal-Android#9229] opened 2019-11-27 23:01 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Disappearing messages should not be able to Quote or Forward for Privacy Issues.

### Steps to reproduce
Set disappearing message for any time
Send a message
Quote (swipe to reply, hold to forwarding) the disappearing message 
Send

**Actual result:** The disappeared message can be quoted or forwarded.
**Expected result:** The disappeared message should not be able to Quote or Forwarded.

**Comment by PiCob** [comment] 2019-11-28 08:29
The current behaviour is most certainly not going to be changed, since it's intended:

- See here for official statements:
   - https://support.signal.org/hc/en-us/articles/360007320771-Set-and-manage-disappearing-messages
   - https://github.com/signalapp/Signal-Android/issues/9142#issuecomment-552041481

Also, please respect the template guidelines for filing issues:

>     * [x]  I have searched open and closed issues for duplicates
>     * [x]  I am submitting a bug report for existing functionality that does not work as intended
>     * [x]  I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
>     * [x]  This isn't a feature request or a discussion topic

Looks like you didn't really do any of this. It's intended and a duplicate of:
- https://github.com/signalapp/Signal-Android/issues/9142
- https://github.com/signalapp/Signal-Android/issues/8787
And related:
- https://github.com/signalapp/Signal-Android/issues/5757
- https://github.com/signalapp/Signal-Android/issues/6636

**Comment by alan-signal** [comment] 2019-12-02 18:17
Please use the community forum for feature requests https://community.signalusers.org/

**Closed by alan-signal** 2019-12-02 18:17 UTC
