### ISSUE TITLE
Scheduled messages are shown as alarms on the status bar

### ISSUE THREAD

**Issue by martino2002** [signalapp/Signal-Android#12848] opened 2023-03-18 13:29 UTC
I know this isn't a bug and it's probably intended, but that doesn't make it less stupid (I didn't have any other option apart from bug report in the New Issue page).
I simply want to understand why it was chosen to treat scheduled messages like alarms.

**Comment by danielsparing** [comment] 2023-03-20 01:31
Yeah I hope this wasn't intended, as it gives the user the impression of an alarm coming up.

Besides the Alarm notification tile it also comes up on the lock screen.

**Comment by greyson-signal** [comment] 2023-04-16 15:11
Closing as a duplicate of #12806

**Closed by greyson-signal** 2023-04-16 15:11 UTC
