### ISSUE TITLE
strings in the conversation settings doesn't use in-app language setting

### ISSUE THREAD

**Issue by Sgn-32** [signalapp/Signal-Android#9999] opened 2020-09-08 17:13 UTC
- [X] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
strings for disappearing message timer and the groups in common doesn't use the in-app language setting.

### Steps to reproduce
- set the in-app language different to the system default
- open the conversation settings

**Actual result:** strings for disappearing message timer and the groups in common doesn't use the in-app language setting.
**Expected result:** strings for disappearing message timer and the groups in common use the in-app language setting.

### Screenshots
![signal-2020-09-08-190453](https://user-images.githubusercontent.com/49990901/92507190-dfff5680-f206-11ea-9b42-ca4a4156a410.jpg)

### Device info
**Device:** Motorola X Play
**Android version:** 7.1.1
**Signal version:** 4.71.0

**Comment by Sgn-32** [comment] 2020-09-08 17:15
related #9872

**Comment by cody-signal** [comment] 2020-09-08 21:33
Thanks for reporting the issue @Sgn-32. This is pretty much a duplicate of the ticket you linked, would mind adding a comment about the additional string you found to that ticket and closing this one?

**Comment by 015203087630** [comment] 2020-09-09 07:26
Am Di., 8. Sep. 2020, 19:15 hat Sgn-32 <notifications@github.com>
geschrieben:

**Closed** 2020-09-09 16:36 UTC
