### ISSUE TITLE
Received image is not loaded

### ISSUE THREAD

**Issue by yan-** [signalapp/Signal-Android#8027] opened 2018-07-23 00:06 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Sometimes received images are not downloaded and displayed. Instead animated circle keeps spinning as if the image was beeing downloaded. 

### Steps to reproduce
- Receive an image (can't reproduce it, it just happens sometimes)

**Actual result:** Animated circle keeps spinning, image is never displayed.
**Expected result:** Animated circle should be displayed until image is downloaded. Then the image should appear.

### Screenshots
![screenshot_20180722-195712](https://user-images.githubusercontent.com/7913590/43051601-5ba3ebc6-8dea-11e8-812e-5576648963d4.png)

### Device info
**Device:** Oneplus X
**Android version:** 6.0.1 (OxygenOS 3.1.4)
**Signal version:** 2.24.2

### Link to debug log
https://debuglogs.org/22589a5dc191a287d4719640352d3ca58c9a4daac220ded946c455b5be50a497
(Using the same as in Issue #8025)

**Comment by greyson-signal** [comment] 2018-07-23 15:03
Closing as a dupe of #7992. Thanks!

**Closed by greyson-signal** 2018-07-23 15:03 UTC
