### ISSUE TITLE
4.73.3 update issues

### ISSUE THREAD

**Issue by anonanonanon50** [signalapp/Signal-Android#10120] opened 2020-10-23 01:24 UTC
[x] I have searched open and closed issues for duplicates
[X] I am submitting a bug report for existing functionality that does not work as intended
[x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
[x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After I updated to signal version 4.74.3 the bottom back button and the "+" button (to add pictures to a text) no longer work. 

### Steps to reproduce
- downloaded the 4.74.3 update
- open a message in Signal
- clicked the bottom back button (see image below). The button just lights up showing I have clicked it, but nothing happens.
- click on the "+" icon (see image below) to attempt to add an image to a message. This button no longer does anything after clicking it.

**Actual result:**
- bottom back button lights up, reacting to the button press, but does not take me back to the main message window. It stays in the same chat window. 
- the "+" icon does not open a add media window as it previously did. If you click on this icon while the keyboard is up, it removes the keyboard

**Expected result:** 
- on previous versions of the app, while in the conversation window, clicking the bottom back button takes me back to my main messages screen 
- on previous versions of the app when I click on the "+" button I was able to add an image/saved media to the chat

### Screenshots
![Screenshot_20201022-205804~2](https://user-images.githubusercontent.com/73320393/96945558-1853af00-14ac-11eb-8dc4-038cbfe4f8cc.jpg)

### Device info
**Device:** OnePlus 8 pro 
**Android version:** 10 Oxygen OS 10.5.13.IN11AA
**Signal version:** 4.74.3

### Link to debug log
https://debuglogs.org/45395f7f43365d804db448d5f21cdcf63bce8dc2c68c11175e03ce06a5d004d7

**Comment by blunden** [comment] 2020-10-23 09:28
I can confirm this behavior.

**Comment by obfusk** [comment] 2020-10-23 11:35
I have the same issue and I see the same `java.lang.NoSuchFieldException: No field mAttachInfo in class Landroid/view/View` error in my logs.

Also: the emoji/stickers "smiley" button doesn't work either.

**Comment by cody-signal** [comment] 2020-10-23 13:27
Duplicate of #10110

**Closed by cody-signal** 2020-10-23 13:27 UTC
