### ISSUE TITLE
Give the dark theme some blue

### ISSUE THREAD

**Issue by ghost** [signalapp/Signal-Android#2397] opened 2015-01-29 16:56 UTC
Hi, I'm testing the version with material design. I really like what you're doing!
One thing though. I love the dark theme, but I don't want to give up the new fancy design. So, could you make the top bar blue (dark blue, like the + button)? I don't think anyone will complain if you add some (dark) colours to it :)
Other than that it looks really awesome. The only thing TS needs now (design-wise) is the ability to set a profile pic.

**Comment by rhodey** [comment] 2015-03-13 20:12
hey @manhole11, trying to reproduce this but looks like it has been since resolved in master. let me know if you're still having this issue and I will re-open, thanks! :)

**Comment by riyapenn** [comment] 2015-09-24 00:52
Same as #2446 (point 1), #3281 (point 2) and #3560

**Comment by automated-signal** [comment] 2018-04-02 21:29
GitHub Issue Cleanup:
See #7598 for more information.

**Closed by automated-signal** 2018-04-02 21:29 UTC
Labels: ux
