### ISSUE TITLE
Front in-app camera distorts image on Huawei p20 lite

### ISSUE THREAD

**Issue by Jkocevska** [signalapp/Signal-Android#8464] opened 2018-12-18 00:25 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I'm using a Huawei p20 lite and when I'm taking the picture with the front camera, picture is distorting.
### Steps to reproduce
- Take a Huawei p20 lite
- Open Signal
- Take a picture with the front camera
- Send the picture

**Actual result:** distorted picture
**Expected result:** normal picture

### Screenshots
1. rear camera
2. front camera without autorotate
3. front camera with autorotate 

![santaback](https://user-images.githubusercontent.com/26821987/50123843-91f03580-0262-11e9-8c89-726ee137991d.jpeg)
![santafrontnoautorotate](https://user-images.githubusercontent.com/26821987/50123848-97e61680-0262-11e9-8966-3d5e22dc9ee5.jpeg)
![santafrontautorotate](https://user-images.githubusercontent.com/26821987/50124015-0a56f680-0263-11e9-9ddc-220f937ab3f5.jpeg)

### Device info

**Device:** Huawei p20 lite
**Android version:** 8.0.0
**Signal version:** 4.31.6

### Link to debug log

https://debuglogs.org/83060b224d62c0f8b2e329f85293b3d33eb6901425115bcd4f0478e4700ccc25

**Comment by rorist** [comment] 2018-12-20 12:56
I have the same bug on my P20 Lite, it's a bit better if you activate auto-rotate and rotate the phone horizontally. The image is distored but entirly displayed.

**Comment by greyson-signal** [comment] 2019-03-03 09:54
Dupe of #8292

**Closed by greyson-signal** 2019-03-03 09:54 UTC
