### ISSUE TITLE
Signal is leaking hidden messages on second and more devices

### ISSUE THREAD

**Issue by marakujaeu** [signalapp/Signal-Android#10962] opened 2021-02-13 11:31 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

### Bug description
When you have more than one device and when one of them is disconnected from the network, after connecting the second device to network again, Signal is starting to download messages. Hidden messages witch intended to never saw again are possible to read for second or two. You can just connect the second device to network and start recording screen.

### Steps to reproduce
- have two or more devices connected to the account
- turn off network connection on one of them
- send some disappearing messages and wait to hide them
- connect the second device to network on opened chat and watch the magic

**Actual result:** You can read hidden messages as simple as recording screen and slowing down video
**Expected result:** Hidden messages should never be able to read again. Never.

### Screenshots
Video is worth more than thousands of photos. https://www.youtube.com/watch?v=zaFu4J0R54c

**Comment by Genis-Sage** [comment] 2021-02-13 12:01
@marakujaeu 
If you mean disappearing messages, then be aware, that they are only a comfort feature, nothing secure

Anybody can make a fork of signal, who keeps disappearing messages

See this discussion
https://community.signalusers.org/t/privacy-and-security-concerns-forks-bypassing-features/27468

**Comment by marakujaeu** [comment] 2021-02-14 18:48
> @marakujaeu
> If you mean disappearing messages, then be aware, that they are only a comfort feature, nothing secure
> 
> Anybody can make a fork of signal, who keeps disappearing messages
> 
> See these discussions
> https://community.signalusers.org/t/how-come-a-message-that-is-deleted-appearing-again/27535
> 
> https://community.signalusers.org/t/privacy-and-security-concerns-forks-bypassing-features/27468

That's a good point, I think. Apart from the fact that the function is purely visual, it is probably worth using some function witch would check whether the message should already be hidden. I can imagine a situation where someone loses control of one of the devices and is eavesdropped on with virtually no programming skills involved.

**Comment by marekzytko** [comment] 2021-02-15 06:35
Why can't Signal client just send some sort of empty message when synchronizing if detects message that has expired? Double Ratchet Algorithm doesn't care what was written in message, because new keys for messages are generated using KDF which initial input is the key exchanged in X3DH

This is kinda strange and not safe imo, because, as far as I'm concerned, sending empty message (or some sign of message being deleted/expired) doesn't affect encryption keys at all

**Comment by bcronce** [comment] 2021-03-07 20:36
> Why can't Signal client just send some sort of empty message when synchronizing if detects message that has expired

Once the message is sent, even the recipient client is offline, the message is buffered to be sent later, possibly after the desired expiration. The server had no way of knowing when a message is supposed to expire. That is potentially leaky metadata, and is therefore hidden from the server. This means the recipient must be trusted to delete the expired message.

You have to choose, trust the central server or trust the client. Since this is an end-to-end-encrypted protocol, we do not trust the server, leaving only the client to be trusted.

And as others have said, disappearing/expired messages are purely a convenience feature. There is no security. Once the message is received the client is free to copy it. Deleting it after the fact is meaningless.

**Comment by greyson-signal** [comment] 2021-03-08 16:56
@bcronce Has the right idea. Some key things to note here: (1) The server queues messages while the user is offline so they can be delivered when they're back online, but *the server has no idea what the messages are*, and therefore cannot delete messages from the queue. (2) Messages are processed in-order, meaning a client will receive the disappearing message first, and then *afterwards* receive the message from a linked device that indicates the message was viewed already and should be expired.

It's important to note that message timers start not based on when a message was sent, but based on when a message was *read*. So we can't expire a message right when we process it -- we need to know if it was read first, which we may not know until later in the queue.

To be honest, we really just need to be processing messages faster than we are. Not only would that reduce the time window where a user could see this, but it'd also let us do things like process messages in batches, allowing us to not show disappeared messages at all, however briefly. The issue is that message processing isn't fast enough to make that change. But it's something we're working on!

Regardless, this isn't a technical bug in itself, so I'm going to close the issue.

**Closed by greyson-signal** 2021-03-08 16:56 UTC
