### ISSUE TITLE
Images not loading - circle keeps spinning until image times out and disappears

### ISSUE THREAD

**Issue by JRHLaw** [signalapp/Signal-Android#8375] opened 2018-11-16 16:03 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Images received on Android 9 (Pixel 2) with ephemeral flag spin for the full duration, do not load or display, and then disappear. Images sent are received correctly. 

### Steps to reproduce
- Receive image with downward-facing arrow
- Click to attempt download

**Actual result:** 
- See spinning circle
- Image does not load and disappears after the timeout period

**Expected result:**
- Image should load

### Screenshots
None available

### Device info

**Device:** Pixel 2
**Android version:** 9 kernel 4.4.116-g62fd7c7873da
**Signal version:** 4.30.6

**Comment by brownstic** [comment] 2018-11-16 16:12
No log available?

**Comment by greyson-signal** [comment] 2018-11-16 21:31
@GuardianMajor @brownstic Do you have the Signal screen lock enabled? There's a known issue with downloads being delayed in that situation that'll be fixed in an upcoming release. Debug logs would allow me to confirm.

**Comment by GuardianMajor** [comment] 2018-11-16 21:51
@greyson-signal I can only speak for myself and yes, I do. It is good to know, thank you. On Android it is a bit messy to submit debug logs because it is very hard to clean out the unnecessary junk, but if you like to point me to what I am looking for, if I find it, I will know which snip of the log would be useful and I can submit it.

**Comment by greyson-signal** [comment] 2018-11-16 21:54
@GuardianMajor You can look for logs like the ones mentioned here: https://github.com/signalapp/Signal-Android/issues/8370#issuecomment-439107532

If @JRHLaw gets back to me with a log and/or confirms they have a screen lock, then I can mark this as a dupe of that ticket.

Thanks!

**Comment by GuardianMajor** [comment] 2018-11-16 22:00
@greyson-signal Got it, thank you.

**Comment by greyson-signal** [comment] 2018-11-17 17:53
@JRHLaw No worries, it's by no means obvious that this is the same issue :) 

And to do the code window thing, do three tick marks:

\`\`\` 
followed by your content, and then end with three tick marks 
\`\`\`

Thanks!

**Closed by greyson-signal** 2018-11-17 17:53 UTC

**Comment by GuardianMajor** [comment] 2018-11-18 00:19
@greyson-signal I thought I wrote back, but I don't see it, so seems I missed it somehow, I found the exact same lines in mine, so as I said before (which I can't find for the life of me) I was able to confirm it is the same thing you mentioned in the other issue, so that's confirmed on my end.

**Comment by JRHLaw** [comment] 2018-12-01 19:54
Hi @greyson-signal,

An update. I turned off auto-download and the app still seems to have problems loading images. It does seem to be related since the app is either delayed (spinning circle) or fails to load before timeout only for images that are sent while the app is not unlocked and opened. If one is sent during an unlocked and foregrounded session, the image loads effectively immediately. 

I seem to also be getting the same kinds of errors:

```
2018-12-01 11:43:16.195 PST I PassphrasePromptActivity: onCreate() 2018-12-01 11:43:16.196 PST I Job: [f77cf0ad-c893-4b00-9fb9-c341a450c883] AttachmentDownloadJob :: doWork() (Time since submission: 31082924 ms, Run attempt: 69, isStopped: false
2018-12-01 11:43:16.196 PST I Job: [f77cf0ad-c893-4b00-9fb9-c341a450c883] AttachmentDownloadJob :: doWorkInternal() (Time since submission: 31082924 ms, Run attempt: 69, isStopped: false)
2018-12-01 11:43:16.202 PST I Job: [f77cf0ad-c893-4b00-9fb9-c341a450c883] AttachmentDownloadJob :: Retrying due to unmet requirements. (Time since submission: 31082931 ms, Run attempt: 69, isStopped: false) 
2018-12-01 11:43:16.229 PST I ApplicationContext: App is now visible
```
