### ISSUE TITLE
Deleted contact aren't really deleted

### ISSUE THREAD

**Issue by 002gRTEah3mRYH** [signalapp/Signal-Android#11633] opened 2021-09-20 13:24 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Deleted contacts on phone still show in Signal app

### Steps to reproduce
- Delete contact on phone
- Remove Signal account on Phone
- Open Signal contacts, still there

**Actual result:**  Contact still here
**Expected result:** Contact should be totally deleted

### Device info

**Device:** Samsung s10+
**Android version:** 11
**Signal version:** 5.23.8

**Comment by Tursko** [comment] 2021-09-20 19:44
You have to delete your Signal account completely for a Signal contact to be removed from your Signal contact list.

**Comment by miku86** [comment] 2021-09-24 04:54
This is not a bug, but a feature.

See:
- [#10891 ](https://github.com/signalapp/Signal-Android/issues/10891)
- [Signal FAQ: Remove someone from your Signal contact list](https://support.signal.org/hc/en-us/articles/360007319011-Manage-Contacts#android_contacts_delete)

**Comment by romdeau23** [comment] 2022-01-31 16:30
Probably a duplicate of #10891

**Closed** 2022-04-08 18:46 UTC
Labels: wontfix

**Comment by 002gRTEah3mRYH** [comment] 2023-11-26 15:59
You can now remove contacts.
