### ISSUE TITLE
Issue when look for info

### ISSUE THREAD

**Issue by azzizzi** [signalapp/Signal-Android#8916] opened 2019-07-08 20:11 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If I want to see in a group who have seen the message or who has received it, I have to hold on the message and click the info button and the bug that you'll see is that some name of the group is repeated 2/3 times overwriting the right one and/or some of them are inverted.

Another bug is that when I'm in the main page of Signal where I see all the chats that I have some of the letters of picture of the profile are wrong get inverted with some of the other users letters.

### Steps to reproduce
- send a message in a group
- look for more info
- some of the contacts is repeated more times overwriting the real one

**Actual result:** cannot see to who is delivered or seen and not
**Expected result:** should be able to do it

### Device info

**Device:** Pixel 2 xl
**Android version:** 9.0
**Signal version:** latest

### Link to debug log

if you need it I'll send it to you through Signal

**Comment by leonardoporpora** [comment] 2019-07-08 20:13
Same issue here

**Comment by greyson-signal** [comment] 2019-07-08 20:39
Hey, so it's not exactly clear what's happening here. I have groups with various member lengths, and the message info screen is always clear. I know this is tricky because the things that aren't being rendered correctly are people's names, but is there a ways you could send a screenshot and blur the names? I'm having trouble picturing it.

You can also send a signal message to one of my test numbers: +1 610 549 1426

**Comment by mueller-ma** [comment] 2019-07-09 06:17
> If I want to see in a group who have seen the message or who has received it, I have to hold on the message and click the info button and the bug that you'll see is that some name of the group is repeated 2/3 times overwriting the right one and/or some of them are inverted.

I have a group with 4 members (A,B,C and me) and when I go to this info screen, I can see the name of A with the picture of C, B with its picture and C with its picture. If I go back and scroll up and down to the same message again, the info screen is ok now.

Signal 4.42.3, Android 7.

**Comment by leonardoporpora** [comment] 2019-07-23 13:59
News on this issue?

**Comment by hwinnemoe** [comment] 2019-09-25 17:34
I do not see this issue anymore since bdf93af3db17c18f0d0fd886defc9c38b09fdc6c has been merged.

**Comment by Junkii7** [comment] 2019-10-11 12:16
I am experiencing this issue and have experienced this issue for a long time over many Signal versions. I have reproduced this issue countless times but was more focused on the sealed sender bug and other things but here we go. I can remember this issue as far back as 4.43.8 I think.
Here are my 2 relevant debug logs with relevant screen shots for each.
Debug log one with screenshot one-
https://debuglogs.org/744ad5785a852f46711981be1a37ae7ac3cb3ffc4d248a8354241446f09a7c31
...
![20191011_212616](https://user-images.githubusercontent.com/48514211/66650543-3a4d0b80-ec74-11e9-8d94-c4a518592831.jpg)
...
Debug log 2 with screenshot 2-
https://debuglogs.org/9bd956d651bc91dc7d81036ee5a48faf3f26027fcba18c3e5846ab55ec2f297c
...
![20191011_212903](https://user-images.githubusercontent.com/48514211/66650707-9b74df00-ec74-11e9-97b5-6265090bb974.jpg)
All the best @greyson-signal and keep me posted, cheers mate!

**Comment by Junkii7** [comment] 2019-10-23 13:08
Has this been patched because the bug is not reproducible for me anymore?

**Comment by greyson-signal** [comment] 2019-10-23 14:50
Oh thank you, I fixed this but couldn't find the issue :) Should be good now.

**Closed by greyson-signal** 2019-10-23 14:50 UTC
