### ISSUE TITLE
Feature Request: uncompressed images

### ISSUE THREAD

**Issue by isillo** [signalapp/Signal-Android#10658] opened 2021-01-15 16:34 UTC
Please allow to send/receive uncompressed images/video.

**Comment by Sgn-32** [comment] 2021-01-15 17:01
Please use the community forum for feature requests:

https://community.signalusers.org/search?q=uncompressed%20images%20%23feature-requests

**Comment by ra0e** [comment] 2021-01-15 19:25
Please close this "Issue" since it is not a bug

**Closed** 2022-01-20 10:01 UTC
