### ISSUE TITLE
Single quote in SMS prevents from restoring new backup

### ISSUE THREAD

**Issue by itmaciek** [signalapp/Signal-Android#7504] opened 2018-03-11 19:43 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When trying to restore almost 2GB encrypted backup from Signal 4.17.1 on another 4.17.1 device, it crashes after around 400 SMS. It seems to be caused by a single quote in the text I got from a friend.

Seems similar to #7491, I had that one too on 4.17.0, but now I'm facing this one.

Seems exactly like #7488, but that got opened in 4.17.0 and closed as resolved in 4.17.1, which seems not to be true.

### Steps to reproduce
- Send a text with a single quote
- Create a backup
- Clear app data/cache
- Start Signal and try to restore from backup

**Actual result:** Signals crashes
**Expected result:** Signal should restore the whole backup

### Device info
**Device:** motorola Moto C (namath_54)
**Android version:** 7.0.0
**Signal version:** 4.17.1

### Debug log
`Device : motorola Moto C (namath_54)
Android : 7.0 (1505098634, NRD90M.005)
Memory : 17M (8.54% free, 256M max)
Memclass: 128
OS Host : dell-PowerEdge-R730
App : Signal 4.17.1

--------- beginning of main 
03-11 19:34:00.700 31230 32089 E MPlugin : Unsupported class: com.mediatek.common.telephony.IOnlyOwnerSimSupport 
03-11 19:38:06.107 32233 32233 E MPlugin : Unsupported class: com.mediatek.common.telephony.IOnlyOwnerSimSupport 
03-11 20:06:24.488 32233 369 E MPlugin : Unsupported class: com.mediatek.common.telephony.IOnlyOwnerSimSupport 
03-11 20:09:22.049 945 945 E MPlugin : Unsupported class: com.mediatek.common.telephony.IOnlyOwnerSimSupport 
03-11 20:09:24.018 945 945 E MPlugin : Unsupported class: com.mediatek.common.telephony.IOnlyOwnerSimSupport 
03-11 20:11:02.646 945 1015 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #5 
03-11 20:11:02.646 945 1015 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 945 
03-11 20:11:02.646 945 1015 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground() 
03-11 20:11:02.646 945 1015 E AndroidRuntime: at android.os.AsyncTask$3.done(AsyncTask.java:318) 
03-11 20:11:02.646 945 1015 E AndroidRuntime: at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354) 
03-11 20:11:02.646 945 1015 E AndroidRuntime: at java.util.concurrent.FutureTask.setException(FutureTask.java:223) 
03-11 20:11:02.646 945 1015 E AndroidRuntime: at java.util.concurrent.FutureTask.run(FutureTask.java:242) 
03-11 20:11:02.646 945 1015 E AndroidRuntime: at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
03-11 20:11:02.646 945 1015 E AndroidRuntime: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
03-11 20:11:02.646 945 1015 E AndroidRuntime: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
03-11 20:11:02.646 945 1015 E AndroidRuntime: at java.lang.Thread.run(Thread.java:761) 
03-11 20:11:02.646 945 1015 E AndroidRuntime: Caused by: net.sqlcipher.database.SQLiteException: near "ie": syntax error: INSERT INTO sms VALUES (377,7,'+*********00',1,NULL,1465975641779,1465975641779,0,1,-1,20,NULL,0,NULL,'[censored] NIN\'ie - [censored]',NULL,NULL,-1,0,0,0,0) 
03-11 20:11:02.646 945 1015 E AndroidRuntime: at net.sqlcipher.database.SQLiteDatabase.native_execSQL(Native Method) 
03-11 20:11:02.646 945 1015 E AndroidRuntime: at net.sqlcipher.database.SQLiteDatabase.execSQL(SQLiteDatabase.java:2265) 
03-11 20:11:02.646 945 1015 E AndroidRuntime: at org.thoughtcrime.securesms.backup.FullBackupImporter.processStatement(FullBackupImporter.java:85) 
03-11 20:11:02.646 945 1015 E AndroidRuntime: at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:67) 
03-11 20:11:02.646 945 1015 E AndroidRuntime: at org.thoughtcrime.securesms.RegistrationActivity$2.doInBackground(RegistrationActivity.java:368) 
03-11 20:11:02.646 945 1015 E AndroidRuntime: at org.thoughtcrime.securesms.RegistrationActivity$2.doInBackground(RegistrationActivity.java:360) 
03-11 20:11:02.646 945 1015 E AndroidRuntime: at android.os.AsyncTask$2.call(AsyncTask.java:304) 
03-11 20:11:02.646 945 1015 E AndroidRuntime: at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
03-11 20:11:02.646 945 1015 E AndroidRuntime: ... 4 more 
03-11 20:11:05.067 1023 1023 E MPlugin : Unsupported class: com.mediatek.common.telephony.IOnlyOwnerSimSupport 
03-11 20:11:05.933 1023 1023 E MPlugin : Unsupported class: com.mediatek.common.telephony.IOnlyOwnerSimSupport 
03-11 20:11:49.693 1023 1067 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #4 
03-11 20:11:49.693 1023 1067 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 1023 
03-11 20:11:49.693 1023 1067 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground() 
03-11 20:11:49.693 1023 1067 E AndroidRuntime: at android.os.AsyncTask$3.done(AsyncTask.java:318) 
03-11 20:11:49.693 1023 1067 E AndroidRuntime: at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354) 
03-11 20:11:49.693 1023 1067 E AndroidRuntime: at java.util.concurrent.FutureTask.setException(FutureTask.java:223) 
03-11 20:11:49.693 1023 1067 E AndroidRuntime: at java.util.concurrent.FutureTask.run(FutureTask.java:242) 
03-11 20:11:49.693 1023 1067 E AndroidRuntime: at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
03-11 20:11:49.693 1023 1067 E AndroidRuntime: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
03-11 20:11:49.693 1023 1067 E AndroidRuntime: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
03-11 20:11:49.693 1023 1067 E AndroidRuntime: at java.lang.Thread.run(Thread.java:761) 
03-11 20:11:49.693 1023 1067 E AndroidRuntime: Caused by: net.sqlcipher.database.SQLiteException: near "ie": syntax error: INSERT INTO sms VALUES (377,7,'+*********00',1,NULL,1465975641779,1465975641779,0,1,-1,20,NULL,0,NULL,'[censored] NIN\'ie - [censored]',NULL,NULL,-1,0,0,0,0) 
03-11 20:11:49.693 1023 1067 E AndroidRuntime: at net.sqlcipher.database.SQLiteDatabase.native_execSQL(Native Method) 
03-11 20:11:49.693 1023 1067 E AndroidRuntime: at net.sqlcipher.database.SQLiteDatabase.execSQL(SQLiteDatabase.java:2265) 
03-11 20:11:49.693 1023 1067 E AndroidRuntime: at org.thoughtcrime.securesms.backup.FullBackupImporter.processStatement(FullBackupImporter.java:85) 
03-11 20:11:49.693 1023 1067 E AndroidRuntime: at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:67) 
03-11 20:11:49.693 1023 1067 E AndroidRuntime: at org.thoughtcrime.securesms.RegistrationActivity$2.doInBackground(RegistrationActivity.java:368) 
03-11 20:11:49.693 1023 1067 E AndroidRuntime: at org.thoughtcrime.securesms.RegistrationActivity$2.doInBackground(RegistrationActivity.java:360) 
03-11 20:11:49.693 1023 1067 E AndroidRuntime: at android.os.AsyncTask$2.call(AsyncTask.java:304) 
03-11 20:11:49.693 1023 1067 E AndroidRuntime: at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
03-11 20:11:49.693 1023 1067 E AndroidRuntime: ... 4 more 
03-11 20:12:10.036 1076 1076 E MPlugin : Unsupported class: com.mediatek.common.telephony.IOnlyOwnerSimSupport 
03-11 20:12:10.978 1076 1076 E MPlugin : Unsupported class: com.mediatek.common.telephony.IOnlyOwnerSimSupport 
03-11 20:12:38.402 1076 1076 E MPlugin : Unsupported class: com.mediatek.common.telephony.IOnlyOwnerSimSupport 
03-11 20:13:49.010 1076 1162 E MPlugin : Unsupported class: com.mediatek.common.telephony.IOnlyOwnerSimSupport 
03-11 20:13:51.351 1076 1076 E MPlugin : Unsupported class: com.mediatek.common.telephony.IOnlyOwnerSimSupport 
03-11 20:13:51.379 1076 1287 E MPlugin : Unsupported class: com.mediatek.common.telephony.IOnlyOwnerSimSupport 
03-11 20:13:52.461 1076 1322 E chromium: [ERROR:instance.cc(49)] Unable to locate service manifest for metrics 
03-11 20:13:52.461 1076 1322 E chromium: [ERROR:service_manager.cc(890)] Failed to resolve service name: metrics 
03-11 20:13:58.803 1076 1076 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length 
03-11 20:13:58.803 1076 1076 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length 
03-11 20:13:59.426 1076 1076 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length 
03-11 20:13:59.426 1076 1076 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length 
03-11 20:14:03.484 1076 1076 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length 
03-11 20:14:03.485 1076 1076 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length 
03-11 20:14:06.337 1076 1076 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length 
03-11 20:14:06.337 1076 1076 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length 
03-11 20:14:08.792 1076 1076 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length 
03-11 20:14:08.792 1076 1076 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length 
03-11 20:14:36.272 1076 1076 E MPlugin : Unsupported class: com.mediatek.common.telephony.IOnlyOwnerSimSupport`

**Comment by junitas** [comment] 2018-03-11 19:46
This is duplicate of #7491, it seems that the fix for that in 4.17.0 didn't properly escape single quotes. There's an open PR to address this.

**Comment by itmaciek** [comment] 2018-03-11 19:50
Thought so, but both #7491 and #7488 were opened for 4.17.0 and got closed as resolved, so I thought I will open a new one for 4.17.1. Thank you for confirming this @junitas

**Closed** 2018-03-12 00:08 UTC
