### ISSUE TITLE
TextSecure sub-contacts rolled up into one line when trying to add new message from "+"

### ISSUE THREAD

**Issue by jeremymasters** [signalapp/Signal-Android#2068] opened 2014-11-03 16:17 UTC
1. Have a contact that has two separate phone numbers (Cell #1, Cell#2) and name them such by choosing "Custom" and filling it in.
2. Tap the "+" to create new thread.
3. Under TextSecure users, notice that only one line is available ergo only one number is available to select.  Further, the custom label is not even shown.

SGS4, Verizon, stock 4.4.2

**Comment by riyapenn** [comment] 2015-09-30 23:14
Closed as number is displayed with name for each distinct number.

**Comment by jeremymasters** [comment] 2015-10-01 03:31
But is the custom label's value shown? Just the main part of the name won't fully make distinct which number is which of the custom label isn't expanded to the actual value it contains.

**Comment by FeuRenard** [comment] 2017-02-19 10:27
Duplicate of #1732 ?

**Comment by automated-signal** [comment] 2018-04-02 21:31
GitHub Issue Cleanup:
See #7598 for more information.

**Closed by automated-signal** 2018-04-02 21:31 UTC
Labels: bug
