### ISSUE TITLE
FTBFS using the Dockerfile

### ISSUE THREAD

**Issue by d33tah** [signalapp/Signal-Android#8741] opened 2019-04-05 12:55 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

I failed to build Signal using the Dockerfile attached

### Steps to reproduce
- git checkout the repository,cd into it
- sudo docker build -t signalapp/signal-android .
- sudo docker run  -v `pwd`:`pwd` -ti signalapp/signal-android
- cd to the directory
- ./gradlew  build --stacktrace

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

```
root@90547c9eae54:/home/d33tah/workspace/src/Signal-Android# ./gradlew  build --stacktrace

> Configure project :
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
Verifying com.android.support:design
Verifying com.android.support:preference-v14
Verifying com.android.support:preference-v7
Verifying com.pnikosis:materialish-progress
Verifying pl.tajchert:waitingdots
Verifying com.theartofdev.edmodo:android-image-cropper
Verifying mobi.upod:time-duration-picker
Verifying com.codewaves.stickyheadergrid:stickyheadergrid
Verifying com.android.support:appcompat-v7
Verifying com.melnykov:floatingactionbutton
Verifying com.android.support:recyclerview-v7
Verifying com.android.support:support-v13
Verifying com.android.support:cardview-v7
Verifying com.android.support:gridlayout-v7
Verifying com.android.support:exifinterface
Verifying com.android.support.constraint:constraint-layout
Verifying com.android.support:multidex
Verifying android.arch.work:work-runtime
Verifying android.arch.lifecycle:extensions
Verifying android.arch.lifecycle:common-java8
Verifying com.google.firebase:firebase-messaging
Verifying com.google.android.gms:play-services-places
Verifying com.google.android.gms:play-services-maps
Verifying com.google.android.gms:play-services-auth
Verifying com.google.android.exoplayer:exoplayer-ui
Verifying com.google.android.exoplayer:exoplayer-core
Verifying org.whispersystems:signal-service-android
Verifying org.whispersystems:webrtc-android
Verifying me.leolin:ShortcutBadger
Verifying se.emilsjolander:stickylistheaders
Verifying com.jpardogo.materialtabstrip:library
Verifying org.apache.httpcomponents:httpclient-android
Verifying com.github.chrisbanes:PhotoView
Verifying com.github.bumptech.glide:glide
Verifying com.makeramen:roundedimageview
Verifying org.greenrobot:eventbus
Verifying com.google.zxing:android-integration
Verifying com.squareup.dagger:dagger
Verifying com.amulyakhare:com.amulyakhare.textdrawable
Verifying com.google.zxing:core
Verifying com.davemorrissey.labs:subsampling-scale-image-view
Verifying cn.carbswang.android:NumberPickerView
Verifying com.tomergoldst.android:tooltips
Verifying com.klinkerapps:android-smsmms
Verifying com.annimon:stream
Verifying com.takisoft.fix:colorpicker
Verifying com.github.dmytrodanylyk.circular-progress-button:library
Verifying org.signal:android-database-sqlcipher
Verifying com.googlecode.ez-vcard:ez-vcard
Verifying com.google.firebase:firebase-iid
Verifying com.google.firebase:firebase-common
Verifying com.google.android.gms:play-services-auth-api-phone
Verifying com.google.android.gms:play-services-auth-base
Verifying com.google.firebase:firebase-iid-interop
Verifying com.google.android.gms:play-services-base
Verifying com.google.android.gms:play-services-tasks
Verifying com.google.android.gms:play-services-places-placereport
Verifying com.google.android.gms:play-services-stats
Verifying com.google.android.gms:play-services-basement
Verifying com.android.support:support-v4
Verifying com.android.support:support-fragment
Verifying com.android.support:animated-vector-drawable
Verifying com.android.support:support-core-ui
Verifying android.arch.persistence.room:runtime
Verifying com.android.support:support-core-utils
Verifying com.android.support:support-vector-drawable
Verifying com.android.support:transition
Verifying com.android.support:loader
Verifying com.android.support:viewpager
Verifying com.android.support:coordinatorlayout
Verifying com.android.support:drawerlayout
Verifying com.android.support:slidingpanelayout
Verifying com.android.support:customview
Verifying com.android.support:swiperefreshlayout
Verifying com.android.support:asynclayoutinflater
Verifying com.android.support:support-media-compat
Verifying com.android.support:support-compat
Verifying com.android.support:versionedparcelable
Verifying com.android.support:collections
Verifying com.android.support:cursoradapter
Verifying android.arch.lifecycle:runtime
Verifying android.arch.lifecycle:livedata
Verifying android.arch.lifecycle:livedata-core
Verifying android.arch.core:runtime
Verifying android.arch.core:common
Verifying android.arch.lifecycle:common
Verifying android.arch.lifecycle:viewmodel
Verifying com.github.bumptech.glide:gifdecoder
Verifying com.android.support:documentfile
Verifying com.android.support:localbroadcastmanager
Verifying com.android.support:print
Verifying com.android.support:interpolator
Verifying android.arch.persistence.room:common
Verifying android.arch.persistence:db-framework
Verifying android.arch.persistence:db
Verifying com.android.support:support-annotations
Verifying com.android.support.constraint:constraint-layout-solver
Verifying com.google.guava:listenablefuture
Verifying org.signal:signal-metadata-android
Verifying org.whispersystems:signal-service-java
Verifying com.github.bumptech.glide:disklrucache
Verifying com.github.bumptech.glide:annotations
Verifying com.nineoldandroids:library
Verifying javax.inject:javax.inject
Verifying com.klinkerapps:logger
Verifying com.google.android:flexbox
Verifying org.jsoup:jsoup
Verifying org.whispersystems:signal-protocol-android
Verifying org.signal:signal-metadata-java
Verifying org.whispersystems:signal-protocol-java
Verifying com.google.protobuf:protobuf-java
Verifying com.googlecode.libphonenumber:libphonenumber
Verifying com.fasterxml.jackson.core:jackson-databind
Verifying com.squareup.okhttp3:okhttp
Verifying com.madgag.spongycastle:pkix
Verifying com.madgag.spongycastle:prov
Verifying org.threeten:threetenbp
Verifying org.whispersystems:curve25519-android
Verifying com.fasterxml.jackson.core:jackson-annotations
Verifying com.fasterxml.jackson.core:jackson-core
Verifying com.squareup.okio:okio
Verifying com.madgag.spongycastle:core
Verifying org.whispersystems:curve25519-java

> Task :signProductionPlayRelease FAILED
WARNING: API 'variantOutput.getPackageApplication()' is obsolete and has been replaced with 'variant.getPackageApplicationProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variantOutput.getPackageApplication(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
Running calculateSignature()...

FAILURE: Build failed with an exception.

* Where:
Build file '/home/d33tah/workspace/src/Signal-Android/build.gradle' line: 475

* What went wrong:
Execution failed for task ':signProductionPlayRelease'.
> java.lang.reflect.InvocationTargetException

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':signProductionPlayRelease'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$2.accept(ExecuteActionsTaskExecuter.java:121)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$2.accept(ExecuteActionsTaskExecuter.java:117)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:184)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ResolveIncrementalChangesTaskExecuter.execute(ResolveIncrementalChangesTaskExecuter.java:84)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionStateTaskExecuter.execute(ResolveBeforeExecutionStateTaskExecuter.java:74)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:109)
        at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
        at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:93)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:45)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:94)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:63)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:49)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:46)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.IllegalArgumentException: java.lang.reflect.InvocationTargetException
        at org.signal.signing.ApkSignerUtil.installProvider(ApkSignerUtil.java:84)
        at org.signal.signing.ApkSignerUtil.calculateSignature(ApkSignerUtil.java:52)
        at org.signal.signing.ApkSignerUtil$calculateSignature.call(Unknown Source)
        at build_cberozedifwlq678xpno3n97x$_run_closure6$_closure60.doCall(/home/d33tah/workspace/src/Signal-Android/build.gradle:475)
        at build_cberozedifwlq678xpno3n97x$_run_closure6.doCall(/home/d33tah/workspace/src/Signal-Android/build.gradle:466)
        at build_cberozedifwlq678xpno3n97x$_run_closure7$_closure61.doCall(/home/d33tah/workspace/src/Signal-Android/build.gradle:484)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:648)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:621)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$4.run(ExecuteActionsTaskExecuter.java:338)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:327)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:312)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$200(ExecuteActionsTaskExecuter.java:75)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:158)
        at org.gradle.internal.execution.impl.steps.ExecuteStep.execute(ExecuteStep.java:46)
        at org.gradle.internal.execution.impl.steps.CancelExecutionStep.execute(CancelExecutionStep.java:34)
        at org.gradle.internal.execution.impl.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:69)
        at org.gradle.internal.execution.impl.steps.TimeoutStep.execute(TimeoutStep.java:49)
        at org.gradle.internal.execution.impl.steps.CatchExceptionStep.execute(CatchExceptionStep.java:34)
        at org.gradle.internal.execution.impl.steps.CreateOutputsStep.execute(CreateOutputsStep.java:49)
        at org.gradle.internal.execution.impl.steps.SnapshotOutputStep.execute(SnapshotOutputStep.java:42)
        at org.gradle.internal.execution.impl.steps.SnapshotOutputStep.execute(SnapshotOutputStep.java:28)
        at org.gradle.internal.execution.impl.steps.CacheStep.executeWithoutCache(CacheStep.java:133)
        at org.gradle.internal.execution.impl.steps.CacheStep.lambda$execute$5(CacheStep.java:83)
        at org.gradle.internal.execution.impl.steps.CacheStep.execute(CacheStep.java:82)
        at org.gradle.internal.execution.impl.steps.CacheStep.execute(CacheStep.java:37)
        at org.gradle.internal.execution.impl.steps.PrepareCachingStep.execute(PrepareCachingStep.java:33)
        at org.gradle.internal.execution.impl.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:38)
        at org.gradle.internal.execution.impl.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:23)
        at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:95)
        at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:88)
        at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:52)
        at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:36)
        at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:34)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:109)
        ... 37 more
Caused by: java.lang.reflect.InvocationTargetException
        at org.signal.signing.ApkSignerUtil.installProvider(ApkSignerUtil.java:77)
        ... 77 more
Caused by: java.security.ProviderException: Initialization failed
        ... 78 more
Caused by: java.security.ProviderException: slotListIndex is 0 but token only has 0 slots
        ... 78 more


* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.2.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1s
77 actionable tasks: 1 executed, 76 up-to-date
```

**Comment by greyson-signal** [comment] 2019-04-05 21:22
Closing as dupe of #8574.

**Closed by greyson-signal** 2019-04-05 21:22 UTC
