### ISSUE TITLE
Audio never play on ear speaker

### ISSUE THREAD

**Issue by Edu4rdSHL** [signalapp/Signal-Android#8886] opened 2019-06-22 03:10 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I receive a audio and I try to reproduce it the audio start playing in speaker normally, then when I put my pone close to ear it only increase the volume level on speaker but not start playing in ear speaker. Additionally it have sound still if the media audio is muted (when putting close to ear).

### Steps to reproduce
- Receive an audio message.
- Reproduce the audio.

**Actual result:** The audio never back to ear speaker.
**Expected result:** If the pone is put close to ear it start playing in ear speaker.

### Screenshots

Not needed

### Device info

**Device:** Samsung SM-G610M
**Android version:** 8.01.0
**Signal version:** 4.42.2

### Link to debug log

https://debuglogs.org/be9aa5b946c8ebf4af9af5ebef5e519f15fdb0a3aa16e3596a0146c6fe3c253d

**Comment by greyson-signal** [comment] 2019-07-23 18:11
Likely a dupe of #7576

**Closed by greyson-signal** 2019-07-23 18:11 UTC
