### ISSUE TITLE
Option to revert contact to SMS messages

### ISSUE THREAD

**Issue by ianopolous** [signalapp/Signal-Android#7372] opened 2018-01-30 21:40 UTC
### Bug description
A friend of mine had installed signal and at some point uninstalled it. Now if I send them messages they clearly never get a delivered receipt. I would like an option to downgrade just this friend to unencrypted sms. Otherwise the only options are to uninstall Signal or stop Signal handling smses for all friends. 

### Steps to reproduce
- send a message to a friend who has uninstalled signal

**Actual result:** No way to downgrade to sms per contact to actually send a message successfully

**Expected result:** An option on the user to revert to SMS. 

### Device info
**Device:** OnePlus One
**Android version:** 6.0.1
**Signal version:** 4.14.10

**Comment by FeuRenard** [comment] 2018-01-30 22:17
[This](https://support.signal.org/hc/en-us/articles/212535548-How-do-I-send-an-insecure-SMS-) could help and/or this issue is a duplicate of #2285.

**Comment by ianopolous** [comment] 2018-01-30 22:42
Thanks @FeuRenard That gives me a way out, though #2285 means it is painful. However, I think having such an important option hidden and essentially undiscoverable is not ideal. The logical place would be in the settings menu for that contact/conversation.

**Closed** 2018-02-04 01:28 UTC
