### ISSUE TITLE
Signal can't use Austrian landline numbers

### ISSUE THREAD

**Issue by ElsAr4e** [signalapp/Signal-Android#13062] opened 2023-07-14 12:18 UTC
I am using the newest (non-beta) version of Signal (on Android)

I tried to register an austrian landline number but Signal will always show "no connection to the service possible ..."

I even tried public (landline) numbers and I get the same issue. And I tried Signal on different devices ("real" smartphones and Android emulator).

If I change the prefix from +43 (Austria) to +49 (Germany) now I could receive a verification code (if that number would exist).

My number also has a 0720 prefix (https://en.wikipedia.org/wiki/Telephone_numbers_in_Austria)

**Comment by Sgn-32** [comment] 2023-07-15 18:06
Can you post a debug log?

https://support.signal.org/hc/de/articles/360007318591-Diagnose-und-Absturzprotokolle

You can also test your phone number here:

https://libphonenumber.appspot.com/

Here as example for +4372012345

https://libphonenumber.appspot.com/phonenumberparser?number=%2B4372012345

**Comment by Sgn-32** [comment] 2023-07-15 18:09
Maybe related issue: https://github.com/signalapp/Signal-Android/issues/13027

**Comment by ElsAr4e** [comment] 2023-07-15 19:12
Just tried the number you've mentioned as an example: Same issue;

Does NOT work (even if I do not use the ZERO after +43)

Video:

https://github.com/signalapp/Signal-Android/assets/98536104/4a9445b5-bd21-45b4-afde-f295c674ecee

**Comment by Sgn-32** [comment] 2023-07-21 16:37
Tested it with 6.27.2 (beta) and test number +43 720 123456 and it works.
Only put "720..." in the phone number field, no leading 0 or 43. The country code is already in the first field.


![Screenshot_1689956878](https://github.com/signalapp/Signal-Android/assets/49990901/f8f6f649-4bad-4ea0-ba71-37f349fff418) ![Screenshot_1689956867](https://github.com/signalapp/Signal-Android/assets/49990901/e3cbd49b-c45e-452a-bebd-0c04fc4ab726)

**Comment by ElsAr4e** [comment] 2023-07-21 16:56
I am using the newest beta version (?) of GooglePlay.

It shows 6.26.3. Same issue?

@Sgn-32 If I don't use the number "6" (so just 12345) I get the same issue:
So it's maybe an issue if your number doesn't have enough numbers?

**Comment by Sgn-32** [comment] 2023-07-21 17:14
Signal checks the number with the PhoneNumberUtil library, both on client (Android/iOS) and on server.
Seems that the server can't handle some numbers of +43 720 ....

Please check you real number here:
https://libphonenumber.appspot.com/
Post the anonymized result, important the results of
Result from isPossibleNumber()
Result from isValidNumber()

6.26.3 is the newest stable version on PlayStore. If you have subscribed in the beta program then 6.27.2.
https://support.signal.org/hc/de/articles/360007318471-Signal-Beta

**Comment by ElsAr4e** [comment] 2023-07-21 17:22
Some of the logs:

<pre><code>07-21 19:12:31.255 28534 28534 I EnterPhoneNumberFragmen: Unable to collect necessary data to enter skip flow, returning to normal </code></pre>

<pre><code>07-21 19:12:33.650 28534 28534 I EnterPhoneNumberFragmen: Unknown error during verification code request
07-21 19:12:33.650 28534 28534 I EnterPhoneNumberFragmen: org.whispersystems.signalservice.api.push.exceptions.NonSuccessfulResponseCodeException: [502] Bad response: 502 Bad Gateway
07-21 19:12:33.650 28534 28534 I EnterPhoneNumberFragmen:       at org.whispersystems.signalservice.internal.push.PushServiceSocket.validateServiceResponse(PushServiceSocket.java:1842)
07-21 19:12:33.650 28534 28534 I EnterPhoneNumberFragmen:       at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1786)
07-21 19:12:33.650 28534 28534 I EnterPhoneNumberFragmen:       at org.whispersystems.signalservice.internal.push.PushServiceSocket.requestVerificationCode(PushServiceSocket.java:383)
07-21 19:12:33.650 28534 28534 I EnterPhoneNumberFragmen:       at org.whispersystems.signalservice.api.SignalServiceAccountManager.requestSmsVerificationCode(SignalServiceAccountManager.java:279)
07-21 19:12:33.650 28534 28534 I EnterPhoneNumberFragmen:       at org.thoughtcrime.securesms.registration.VerifyAccountRepository.requestVerificationCode$lambda$4(VerifyAccountRepository.kt:139)
07-21 19:12:33.650 28534 28534 I EnterPhoneNumberFragmen:       at org.thoughtcrime.securesms.registration.VerifyAccountRepository.$r8$lambda$4YuC6roLLQpy3ZfcLaXKaNALQKQ(VerifyAccountRepository.kt:0)
07-21 19:12:33.650 28534 28534 I EnterPhoneNumberFragmen:       at org.thoughtcrime.securesms.registration.VerifyAccountRepository$$ExternalSyntheticLambda4.call(R8$$SyntheticClass:0)
07-21 19:12:33.650 28534 28534 I EnterPhoneNumberFragmen:       at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
07-21 19:12:33.650 28534 28534 I EnterPhoneNumberFragmen:       at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
07-21 19:12:33.650 28534 28534 I EnterPhoneNumberFragmen:       at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
07-21 19:12:33.650 28534 28534 I EnterPhoneNumberFragmen:       at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
07-21 19:12:33.650 28534 28534 I EnterPhoneNumberFragmen:       at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:25)
07-21 19:12:33.650 28534 28534 I EnterPhoneNumberFragmen:       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
07-21 19:12:33.650 28534 28534 I EnterPhoneNumberFragmen:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-21 19:12:33.650 28534 28534 I EnterPhoneNumberFragmen:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-21 19:12:33.650 28534 28534 I EnterPhoneNumberFragmen:       at java.lang.Thread.run(Thread.java:929)
07-21 19:12:33.650 28534 28534 I EnterPhoneNumberFragmen:       at org.signal.core.util.concurrent.SignalExecutors$NumberedThreadFactory$1.run(SignalExecutors.java:109)
07-21 19:12:33.653 28534 28534 I DecorView[]: pkgName:org.thoughtcrime.securesms old windowMode:0 new windoMode:1, isFixedSize:false </code></pre>

**Comment by ElsAr4e** [comment] 2023-07-21 17:32
@Sgn-32 I also tried to use a "real" landline number (NO SIP-account) without 720 - still same issue (I am actually using a SIP-account)

The only way to fix these issues is to change the prefix to Germany - which doesn't make sense because the number does not exist or does not belong to me?

NEXT attempt (Signal 6.26.3.): 
Just used the austrian airport number (https://www.viennaairport.com/passagiere/flughafen/wichtige_telefonnummern). SAME ISSUE!

**Comment by Sgn-32** [comment] 2023-07-21 17:51
Could be problematic that your number is a SIP-number.
Actually, only the Signal team can answer it, (especially the Server team?).
It may be necessary for developers to use the latest version of [libphonenumber 8.13.17](https://github.com/google/libphonenumber/releases)

**Comment by ElsAr4e** [comment] 2023-07-21 18:06
@Sgn-32 I also used a "real" landline number (it has probably NEVER been a SIP-number). It's actually a Plain old telephone service (POTS) and uses a TAE (https://en.wikipedia.org/wiki/TAE_connector).

SAME issue.

Not sure if Austria Airport is SIP or a "real" POTS.

**Comment by ElsAr4e** [comment] 2023-07-21 19:46
Thanks for your answers and help.

But I thought in the past you could use non-mobile numbers?

https://meejah.ca/blog/signal-landline

I just had issues with signal-cl and the newest Java versions.

But anyway - I am looking forward that it will be possible in the near future!

**Comment by nicholas-signal** [comment] 2023-07-21 22:47
> But I thought in the past you could use non-mobile numbers?

That is correct, and this is a regression that we are working to rectify.

**Comment by romanseidl** [comment] 2023-08-13 19:22
It seems austrian mobile numbers don't work anymore either. 

I registered a new mobile number just because of this issue and it did not work. Network is +43677 (bob.at).

**Comment by ElsAr4e** [comment] 2023-09-05 21:01
Using the newest version of Signal you can now choose you want to receive a phone call but after that you get the same error message.

**Comment by nicholas-signal** [comment] 2023-09-06 14:37
Apologies for not pinging the thread, things got lost in the shuffle. This should be live now. If it doesn't work for you on 6.31.2+, please attach a debug log here.

**Comment by ElsAr4e** [comment] 2023-09-14 08:18
Just tried out using Signal 6.32.4:

1) "real" landline phone numbers work (phone uses TAE connector and a TAE wall telephone socket). You'll receive a call.

2) But the SIP-number 0720 still does not work. 

You should be able to reproduce if you try the following number "+43 720 123456". After you select the option "phone call" you get the same error message again.

**Comment by nicholas-signal** [comment] 2023-09-14 19:33
1) This is working and therefore I will close this issue as fixed.
2) SIP numbers are often flagged by our call/SMS providers as being ipso facto fraudulent. We're aware that legitimate users seek to use SIP numbers but the [toll fraud risk](https://www.twilio.com/docs/verify/preventing-toll-fraud) is immense.

**Closed by nicholas-signal** 2023-09-14 19:33 UTC

**Comment by ElsAr4e** [comment] 2023-11-10 20:21
@nicholas-signal I tried an Android emulator (https://www.memuplay.com/) and Signal 6.39.1.

The first times if I select "Call me" option it fails but after I've enabled and disabled the voicemail server option a few times I suddenly received a call and even the SIP 0720 number works.

But maybe just randomly?

Anyway - great that I can now use this number too.
