### ISSUE TITLE
Signal overrides phone's notification settings and 

### ISSUE THREAD

**Issue by skopjanecot** [signalapp/Signal-Android#12353] opened 2022-07-22 07:28 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal does not follow phone's notification settings and overrides them when the phone is in on silent, e.g sends a loud notification sound when, by following the phone's state, it should not. 
The bug appears to be present only when receiving messages, while calls follow phone's notification state as they should.
This has serious implications when in meetings or concerts.

### Steps to reproduce
- set all Signal notification options to default
- set phone on silent
- receive a message

**Actual result:** Besides having Signal set to follow phone's state for notifications, loud notification sound comes trough even when the phone is on silent.
**Expected result:** Signal notifications stay silent when the phone is set to silent.

### Screenshots
![signal-2022-07-22-085854](https://user-images.githubusercontent.com/46635826/180382174-9ffde564-fab7-4027-95ce-eb5f1e8f7088.png)

### Device info
**Device:** Nokia G21
**Android version:** 11 (4.14.199+ Kernel)
**Signal version:** 5.43.7

### Link to debug log
https://debuglogs.org/android/5.43.7/129656cddf0af8bcdc199f6263286081a8f37548ddba02a2ecc2ed0b86d24c25

Needles to say that I have tried reinstalling the app and cleaning the cache and data. 
It seems this problem was introduced when Signal implemented its own notification profiles which somehow messed up simple following of the phone notification settings.
The bug has been here for a while, but at this point it started to be really annoying.

**Comment by cody-signal** [comment] 2022-07-22 15:10
My phone is always on silent, and I receive hundreds of messages a day. I've never heard it make a noise. Your screenshot indicates that the notifications are not silenced. So to confirm:

Make no changes to signal notification configuration in app or in system. Using the system volume controls, mute the device, and then receive a message an hear a sound?

**Comment by skopjanecot** [comment] 2022-07-22 15:53
My screenshot indicates that Signal should follow phone's state. If "Silent" is selected then no notifications will be allowed whatsoever, regardless of phone's settings.

I never made any changes to the app or system after installing Signal on (then) new phone almost 6 months ago. I have also filed a bug report through the app then.

This is probably Device or Kernel specific, but I can assure you that the bug **is present**. Here is a [reddit post](https://www.reddit.com/r/signal/comments/swx2c5/why_does_signal_notify_me_when_do_not_disturb_is/) where other users are claiming the same issue in the same timeframe as I first experienced this. I assume this will be taken with the utmost seriousness, since as you can imagine, receiving notification when in a meeting is a serious issue for something that should be basic functiounality. That's why I have taken the time to file a bug report here. The last thing I honestly want is going back to Whatsapp after pushed all my friends to Signal.

**Comment by cody-signal** [comment] 2022-07-22 18:55
The reddit thread is about Do Not Disturb mode not silenced ringer. Are you using DND or silenced ringer?

**Comment by skopjanecot** [comment] 2022-07-22 19:51
It's all set to default even now, only the notification sound has been changed recently.
As I wrote, the same behaviour is present even after reinstalling the app and having the default preferences that come with fresh install.

Isn't there something in the log that might clarify this issue better? I can make a video as well, just let me know which settings panels are necessary.

**Comment by cody-signal** [comment] 2022-07-25 14:00
I don't think we store anything about do not distrub in our logs. Can you clarify if you are:

1. Using do not disturb mode to silence all sounds/notifications
2. or turning the ring volume all the way down to silence sounds?

While both make notifications "silenced", technically there's a big difference how this works under the hood.

**Comment by skopjanecot** [comment] 2022-07-25 15:35
To answer your question:
1. I am not using "do not disturb mode". I had to search for what this is even.
2. The ring volume is all the way down. This is how I put my phone in silent mode (see screenshots bellow).

**IMPORTANT** I realized that if I lower the "media volume" slider all the way down it silences the Signal notifications as well. But that is not the expected behaviour as far as I know. This should control playback of videos and audio apps.

![signal-2022-07-25-172803_002](https://user-images.githubusercontent.com/46635826/180816941-dbddf37b-e6f8-416c-9ec6-caa30e53f5d8.png)
![signal-2022-07-25-171552_002](https://user-images.githubusercontent.com/46635826/180816259-ef63ce54-c39e-438c-b522-8a0c60c4f9cf.png)

**Comment by skopjanecot** [comment] 2022-07-25 17:52
Found this recent [reddit post ](https://www.reddit.com/r/signal/comments/vl41ma/notifications_use_media_volume/)which deals with the same issue it seems.
I am running Android One on a Nokia G21, so custom ROM cannot be the issue in my case.

**Comment by Genis-Sage** [comment] 2022-07-25 19:28
perhaps related to / duplicate of  #12126

**Comment by cody-signal** [comment] 2022-07-25 20:13
Thank for you for the clarifications, we'll look into it.

**Comment by travisterrell** [comment] 2022-09-22 16:52
My experience has been a slight variation of this. While I personally don't experience notification sounds breaking through, I have found that visual notifications still show up on the screen with high-priority pop-up notifications. I rely on Do Not Disturb to minimize distractions while working, and, man, I REALLY wish it would respect that. (I have a couple of contacts that seriously spam me with messages, and often I'm on my phone while working, where they then cover up 1/4 of the screen, then are sometimes accidentally clicked—marking the received message as _Read._)

I'm a bit surprised this bug isn't more widely reported (or complained about.) I'm guessing most people just use "silent" instead of "do not disturb", but here's another Reddit thread from earlier this year: https://www.reddit.com/r/signal/comments/swx2c5/why_does_signal_notify_me_when_do_not_disturb_is/

**Comment by realwax** [comment] 2022-11-12 14:11
I experience this kind of override on MIUI with my Poco F4. Signal uses the media volume instead of the notification volume....

**Comment by skopjanecot** [comment] 2022-11-12 17:26
At this point I don't think they will ever try to fix this issue. I'm pretty certain that they cannot even locate the bug. They spend thousands of man-hours on implementing new features that nobody needs, like the Stories or the custom notifications profiles, which I think led and created this bug in the first place. Meanwhile, the app struggles with the basic and core functionality. Half of the time people cannot hear me properly in calls, or I get messages every morning that the creation of a backup failed because it cannot find the backup folder (something that every other app somehow can, including Signal before some shitty update).

Now I feel stupid that I dedicated any time to report this bug in the first place.

**Comment by travisterrell** [comment] 2022-11-12 19:21
IIRC, I made a similar rant somewhere earlier in this discussion (and
probably some others over the years.) Very frustrating. If they insist on
adding features, things to bring it closer to feature parity with other
messaging apps should be first--like basic formatting support. Blows my
mind the directions they take this thing. I mean crypto? It'd be hilarious
if not so frustrating.

**Comment by KarowJan** [comment] 2023-01-04 07:58
Maybe a bit late, but I just recently ran into the same issue using a Nokia G21 with Android 11 and later the upgraded version of Android 12. I can confirm that no matter what you do, you will receive an audio notification, even the phone is in vibration state. Only of you put down "media volume" to zero you have the wanted effect.
Having this knowlege I thought it could be a solution to just do two steps in order to have real vibration mode only. But it turns out that you need to unlock the phone to set media volume to zero or back to something useful when you want to see a video or listen to a voice message. So on a regularly basis my complete office gets to know that I received a message, obviously coming from Signal.
But the news is that I have exactly the same issue with Threema. I currently use the 5.03beta3 and as I am based on Threema and Signal, I have lots of incoming messages each day and since I started tests with the G21 I never made it to avoid audio signals for a complete day.

**Comment by cody-signal** [comment] 2023-01-13 16:13
Hi folks, it's really hard to fix a bug you can't reproduce. And we've never been able to reproduce this. I just tried again on stock pixel 7 device, a pixel 2 running lineage, a samsung a51 on android 11, and a oneplus 8t on Android 13.

I see two folks in this thread (@skopjanecot  and @Jan-Coding) have a Nokia G21. Do other folks in this thread have different devices that the problem occurs on?

**Comment by realwax** [comment] 2023-01-13 16:28
@cody-signal I am happy to help out with testing. From my perspective I can only report the issue on Miui latest and before. I am using a Poco F4 and it is reproducible. A new signal message will not use notification volume it uses media volume any time. If doubtet I can make a video as proof.... The issue is really annoying. I using signal, telegram, threema, messenger ... Signal is the only one not capable of doing it right. 
Thank you

**Comment by cody-signal** [comment] 2023-01-24 16:37
@realwax Could you send me an email so I can send you a link to a test app to check various notification channel configurations? cody at signal org

**Comment by realwax** [comment] 2023-01-24 17:07
Done 👍

**Comment by firefoxlover** [comment] 2023-01-24 17:42
This is also true for that damn popup notifications. They are nearly impossible to turn off, not sure how exactly but I managed to do that anyways.

**Comment by cody-signal** [comment] 2023-01-25 19:55
Alright class, with @realwax's help, I think I've found a solution. It'll be in the next beta (6.10.0) and it _should_ be available soon (like today or tomorrow).

Once it's out in your preferred release channel, please see if it fixed it for you. Note, if you have created custom notifications for certain conversations, you'll have to recreate them to get the fix. A pain I know, but was the quickest and safest way to get a fix out. If you only use the main "Messages" channel then you shouldn't have to do anything.

**Comment by realwax** [comment] 2023-01-25 20:10
@cody-signal  Thank you very much for the fix and solution!  As soon as I have it I will test and confirm.
Cheers

**Comment by realwax** [comment] 2023-01-26 13:07
From my perspective using latest Miui on poco f4 I can confirm with todays beta release 6.10. 0 the issue using media volume instead of notification volume is fixed. Thank you @cody-signal

**Comment by ahailes** [comment] 2023-01-27 16:05
Hi there, I don't know if this will help anyone other than me, but I've found a solution to my related problem.  For me, it looks like the problem was some buggy interaction between signal and android conversations.  I had some conversations that would vibrate even when the phone was in do not disturb (and no other app notifications would vibrate).

I went through all the different types of signal notifications and checked them all for the "Override Do Not Disturb" setting, and they were all off.  But signal still showed up in the list of apps that could interrupt DnD in the DnD settings.

I eventually realized that some signal chats (but not all, and I'm not sure why) are marked as "conversations", which can be seen in android settings -> Notifications -> Conversations (but not in Notifications -> App settings -> Signal for some reason).

Given that backstory, here's the fix that worked for me:
1) Find signal conversations in conversations list (in android settings)
2) in the conversation settings, mark them as "Not a conversation"
3) go to the app notification settings, which should now show the non-conversation under "chats" notifications
4) ***in the settings for the new category of chats notifications, switch off "Override Do Not Disturb"***
5) optionally, mark the category as a conversation again

The crux of the issue was that there were conversations that were allowed to override do not disturb, but this setting was not visible anywhere until the conversations were recategorized.

**Comment by nicholas-signal** [comment] 2023-03-29 14:33
Looks like @cody-signal's fix worked for at least @realwax, and @ahailes has offered a guide for similar issues due to Android's categorization of "Conversation" notification types.

I am closing this issue.

If this issue or similar one re-appears, please create a new GitHub issue so we can track that individually!

**Closed by nicholas-signal** 2023-03-29 14:33 UTC
Labels: wontfix
