### ISSUE TITLE
Can't reply a sticker with a sticker

### ISSUE THREAD

**Issue by quiet-programmer** [signalapp/Signal-Android#10719] opened 2021-01-18 10:46 UTC
When I try to reply a sticker with a sticker it does not send as a reply instead it send as a direct message

- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by Leptopoda** [comment] 2021-01-18 11:20
Hi there!
Thanks for the report but this behavior is actually intended and not a bug.
There already is an open feature request in the community forum regarding this.
https://community.signalusers.org/t/send-stickers-as-a-reply-to-a-quoted-message/12919
Please join the discussion over there and close this issue
Also an official statement by the devs when

**Closed** 2021-01-19 09:25 UTC
