### ISSUE TITLE
[Feature Request] Optional Alternative To Using A Number To Add New Contacts

### ISSUE THREAD

**Issue by zero77** [signalapp/Signal-Android#7106] opened 2017-10-17 11:35 UTC
For extra privacy, can you please allow users to use something other than their number.

For example, maybe a randomly generated number or username or, a salted hash of their number similar to wickr and some other private messengers.

Thanks

**Comment by rustybird** [comment] 2017-10-17 13:51
Duplicate of #1085

**Comment by zero77** [comment] 2017-10-17 14:57
@rustybird 
Unless I am mistaken PR #1085 is asking for an alternative way to register other than using a number.

This PR #7106,  is not it’s just asking for a different way to add contacts alongside using a number.

**Comment by grandchild** [comment] 2017-10-17 15:29
> alternative way to register
> different way to add contacts

I would argue that for all practical purposes these are the same. How would the server find the ID that you're trying to add? By looking at the IDs that are _registered_.
You could argue that it's possible to add another field such as an alternative ID but that would add (imo) unnecessary complexity, and your problem would be solved more elegantly by fixing #1085.

**Comment by zero77** [comment] 2017-10-17 17:15
@grandchild
Fundamentally, I am looking for a way to add other users with a bit more privacy for instance, by not giving away personal info like numbers, emails or similar info to users you want to add.

There for, yes I agree #1085 is a good idea and it may achieve this and with more elegance.

Although, I am not after a full remodel of the backend system as, I think it would be a bit over kill for just achieving the above.

I am just after a way to add users without revealing personal info to them so, by just doing something simple like adding an extra field with a more private ID would be a simpler and easer thing to implement.

**Comment by automated-signal** [comment] 2018-04-03 04:33
GitHub Issue Cleanup:
See #7598 for more information.

**Closed by automated-signal** 2018-04-03 04:33 UTC
