### ISSUE TITLE
Number in message gets replaced by three dots

### ISSUE THREAD

**Issue by ronidee** [signalapp/Signal-Android#11908] opened 2022-01-19 00:57 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
A three-digit number got replaced by three dots in a message (german legislative text). Hence the message was useless.

### Steps to reproduce
- Send this message from desktop(including the quotationmarks, replace [4 spaces] with four actual whitespaces):

"(2) Die Bedarfe nach Absatz 1 erhöhen sich für die Unterkunft, wenn der Auszubildende

[4 spaces]bei seinen Eltern wohnt, um monatlich 55 | 56 Euro,

[4 spaces]nicht bei seinen Eltern wohnt, um monatlich 325 Euro."

Aaa aaaaaaa aaa "|" Aaaaaa aaa aaa aaa aa aaaa aaaa aaaaaa aaaa. Aaaa aaaaaaa aa aaaa aaaa aaaaaaa aaa aaaaa aaaaaa aaa" 

(the last line was replaced by "a"s for privacy reason :grin:)

**Actual result:** the "325" was replaced by "..."
**Expected result:** the "325" is not replaced by "..."

### Screenshots
Left side: message viewed on the receiving android client. right side: message viewed on the sending desktop client
![signaltextbug](https://user-images.githubusercontent.com/22625272/150043522-da5cab69-90b9-4f40-b63a-88ebdacd2bd8.jpg)

### Device info

**Device:** Motorola Moto g60s
**Android version:** 11
**Signal version:** TBA

### Link to debug log
The log was taken a 26minutes after the error happened. After the first message I sent multiple variations to test the bug, but the original one was sent at "Wednesday, January 19, 2022 1:28 AM (1642552080531)" if that helps.

https://debuglogs.org/f0e9efa846b370f1da6e078f7a07ec41d84044f91073802959eeac060e14aee4

**Comment by conrad57** [comment] 2022-01-27 10:13
I encountered a similar problem. In some messages, usually lengthy ones, 3 consecutive letters get replaced by "...".

**Comment by Altonss** [comment] 2022-01-29 18:17
This issue is probably a duplicate of https://github.com/signalapp/Signal-Android/issues/11840

**Comment by alex-signal** [comment] 2022-01-31 13:39
Duplicate of #11840

**Closed by alex-signal** 2022-01-31 13:39 UTC
