### ISSUE TITLE
Signal 4.28.0 Chat message colors wrong

### ISSUE THREAD

**Issue by DreamFlasher** [signalapp/Signal-Android#8258] opened 2018-10-06 18:45 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Since the last update to Signal 4.28.0 on Android the color coding of the messages in the chat window is wrong/flipped. 

### Steps to reproduce
- open a conversation with anybody

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

Outgoing messages are in color, right-adjusted. Incoming messages are grey, left-adjusted. 

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

Outgoing messages are in grey, right adjusted, incoming messages are in color, left-adjusted.

### Reasoning
Outgoing messages should be grey because:
1) They are "less important", so should not be highlighted
2) It has been the behavior before, and it "feels" horrible, as if something is wrong
3) The name of the contact (top border) is now of the color of oneself, instead of the other person (inconsistent)
4) The desktop app is the other way around (outgoing messages grey), they should be the same

### Device info

**Device:** Blackberry Priv
**Android version:** 6.0.1
**Signal version:** 4.28.0

**Comment by brs17** [comment] 2018-10-06 18:50
This is a duplicate of https://github.com/signalapp/Signal-Android/issues/8245

The explanation is here: https://support.signal.org/hc/en-us/articles/360016466812-Frequently-Asked-Questions-about-the-recent-changes-to-conversation-colors

**Closed** 2018-10-06 18:50 UTC

**Comment by DreamFlasher** [comment] 2018-10-06 19:00
I searched for this and couldn't find it it open tickets. It's clearly a UI bug, and a couple of other people agree with me in that. UI bugs are bugs too and not off-topic. This should not be closed.

**Comment by greyson-signal** [comment] 2018-10-06 21:03
@DreamFlasher You were kindly linked to a duplicate ticket that covers this topic in detail, as well as a support page made specifically for this situation. This was an intentional change.

**Comment by DreamFlasher** [comment] 2018-10-07 07:10
@greyson-signal That doesn't change anything -- people regularly make intentional mistakes. And this is one. Make it at least customizable. This sucks, and also how you treat your users. You regularly brush off people here who file bug reports. They are the most important users for you, and I have the impression you are not aware of this. I convinced over a hundred people to use Signal. Because I believe it's the best product currently on the market, but yeah hopefully Wire catches up in usability soon, so that I can recommend this.

**Comment by greyson-signal** [comment] 2018-10-07 15:50
@DreamFlasher I think we have a fantastic set of Github users, one that I'm very thankful for, and I do my best to express my gratitude when given the opportunity. I very much appreciate that you're such a strong advocate for Signal, and I hope you continue to be.

But that said, Github isn't great for general discussion, which is why we have a policy of only using it exclusively for bugs and moving all other conversations over to the [forum](https://community.signalusers.org/). There's a couple threads there about this topic already that we're actively watching for feedback, and I encourage you to participate.

**Comment by DreamFlasher** [comment] 2018-10-07 16:27
@greyson-signal Thank you for expressing the appreciation. I added a comment in the forum, I sincerely hope that you take the many people into consideration who consider this change a bug and make it at least customizable.
