### ISSUE TITLE
Wrong Contact in the title

### ISSUE THREAD

**Issue by Bagbar** [signalapp/Signal-Android#4066] opened 2015-09-12 17:57 UTC
First:I use Cyanogenmod on my Galaxy S2. If this has any relevance.
I got a message and I pulled the info tray down then selected the messafe that appeared with the correct sender.
When opened in the title (where the name and the number appears) were the data of another contact.

**Comment by 2-4601** [comment] 2015-09-12 20:32
Does this happen every time with the said contact?
Could you post a debug log right after this happens?
**Settings -> Advanced -> Submit debug log**
And paste the link here.

**Comment by jeremymasters** [comment] 2015-09-16 03:49
I actually had this with a hung mms message.  The notification said it was user A and was downloading an mms and when I tapped it, it took me to the user.  HOWEVER...it was actually a reply from someone with whom I was having a group (non-TS) conversation with.  When I rebooted my phone and the mms came through, the mms was routed to the correct group conversation and did NOT appear in the single user conversation.  @mcginty <3 mms

**Comment by moxie0** [comment] 2015-09-17 01:02
@jeremymasters That's normal.  The MMS "notification" only contains the information of who sent it, where as the information about all the recipients (effectively the group info) is on the part that's retrieved.

**Comment by Bagbar** [comment] 2015-09-18 17:11
@2-4601 I will keep my eye open if this happens again and then post the log.

**Comment by colingourlay** [comment] 2015-09-21 01:07
I've also experienced this consistently for the past few days on my Sony Xperia Z3 Compact running Android 5.1.1. To reproduce:

1. Send a message to "Contact A"
2. Have "Contact B" send you a message while your phone is locked.
3. Tap the message notification to open the app.

The message (and conversation history) from Contact A will open with the header, name, colour, etc. of Contact B.

**Comment by 2-4601** [comment] 2015-09-21 08:44
Unable to reproduce with the above steps on Nexus 4, stock 5.1.1 (LMY48M), TS 2.26.5.

**Comment by Bagbar** [comment] 2015-09-21 11:40
Looked like what @colingourlay  reported.
I don't get many texts but now it was as he described.
After the screen went black and I pushed the "home"button to reactivate it the correct contact was shown.

debug log:
https://gist.github.com/abbeeb785e77f0057cb2

**Comment by riyapenn** [comment] 2015-09-24 18:49
Also related to https://github.com/WhisperSystems/TextSecure/issues/2354

**Comment by Bagbar** [comment] 2015-09-25 09:41
If I understand this correctly, it is different because it is in the wrong conversation.
For me the conversation is right but the title is wrong when using the eventbar to read the message. Afterwards everything is fine

**Comment by unhammer** [comment] 2015-10-11 07:11
When this happens:

    Send a message to "Contact A"
    Have "Contact B" send you a message while your phone is locked.
    Tap the message notification to open the app.

and I click the "fullscreen" button, it shows A in the title for me as well.

**Comment by radiobread** [comment] 2015-11-02 11:51
Me too. 
https://gist.github.com/ffa753d8451049c20d3a

**Comment by mcginty** [comment] 2015-11-02 18:58
This is potentially fixed in Signal 3.1.x (I have a contact who was reproducing this on the regular and hasn't seen it since upgrading to the beta).

**Comment by jeremymasters** [comment] 2015-11-02 19:08
@mcginty Does that mean, as a previous manager would say, the general release of 3.1.x is "imminent"?

**Comment by mcginty** [comment] 2015-11-02 19:29
@jeremymasters https://whispersystems.org/blog/just-signal/ yep

**Comment by riyapenn** [comment] 2015-11-12 19:26
Is this still an issue?

**Comment by automated-signal** [comment] 2018-04-02 21:50
GitHub Issue Cleanup:
See #7598 for more information.

**Closed by automated-signal** 2018-04-02 21:50 UTC
