### ISSUE TITLE
New MMS group created for responses to an existing group.

### ISSUE THREAD

**Issue by cdysthe** [signalapp/Signal-Android#7558] opened 2018-03-23 17:36 UTC
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Replies to an existing MMS group creates a new MMS group with "Me" added.

### Steps to reproduce
- Create a MMS group. Send a message to the group.
- When someone answers the group message a new MMS group is created with 'Me' as a new member. So if the group I created contains members A,B,C the new group containing the answers will have Me,A,B,C as members

**Actual result:** If the group I created contains members A,B,C the new group containing the answers will have Me,A,B,C as members
**Expected result:** The answers to the group will come in the initial group created with members A,B,C

### Screenshots
![img_20180323_132530](https://user-images.githubusercontent.com/1281031/37844413-165a63c0-2e9e-11e8-92a2-c12e07da1263.jpg)

### Device info

**Device:** Moto G5+
**Android version:** 7.0.0
**Signal version:** 4.17.5 (Beta)

### Link to debug log
https://debuglogs.org/2526a8ae758fed3031f850dd6bd698b8ea42c1e79bd08a78bba957c5e800b7be

**Comment by FeuRenard** [comment] 2018-03-23 17:53
Duplicate of #7161

**Closed** 2018-03-24 15:09 UTC
