### ISSUE TITLE
Sharing from Android apps via Signal no longer possible to non-Signal contacts

### ISSUE THREAD

**Issue by caitsith01** [signalapp/Signal-Android#10942] opened 2021-02-09 09:54 UTC
- [ x] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When sharing via the generic Android 'share' functionality used by many apps, Signal appears as a sharing option. However when selected, Signal only offers the ability to share to Signal contacts and not non-Signal contacts via SMS/MMS. 

This occurs despite Signal being set as the default SMS/MMS app and despite it being possible within Signal to create a new message to a non-Signal user and then add an attachment.

### Steps to reproduce
- locate an image in Google Photos
- select the 'share' link
- select Signal as the sharing app
- view the resulting list of contacts

**Actual result:** No non-Signal contacts are shown, not possible to send (for example) an MMS to a non-Signal contact
**Expected result:** All contacts are shown in the share dialogue. Signal sends to Signal contacts natively and non Signal contacts via SMS or MMS as appropriate.

### Device info

**Device:** Google Pixel 3a XL
**Android version:** 11
**Signal version:** 5.3.12

**Comment by birdbrain5381** [comment] 2021-02-10 01:20
Also experiencing this issue and it's really frustrating. Behavior is as described in report.

**Comment by klint** [comment] 2021-02-13 16:56
Same here, same frustration 😊

**Comment by caitsith01** [comment] 2021-02-13 22:15
Seems to me that in their haste to add a feature no one really needs 99% of the time, multi-select, the devs have completely broken the way Signal works as an SMS/MMS app. This integration is one of the biggest selling points of Signal for new users, so breaking it is an incredibly bad idea and will harm uptake.

**Comment by nvllsvm** [comment] 2021-03-03 04:57
@alan-signal Can we have confirmation on whether this is a bug or intended behavior?

**Comment by olimju** [comment] 2021-03-07 16:57
Same issue, with workaround I've confirmed works:
https://github.com/signalapp/Signal-Android/issues/10929#issuecomment-783719234

**Comment by max3163** [comment] 2021-03-07 21:30
Same problem here

**Comment by caitsith01** [comment] 2021-03-09 01:20
So does anyone from Signal actually look at this stuff?  This is still a significant problem and has a major impact on the usability of Signal as an SMS/MMS app.

**Comment by caitsith01** [comment] 2021-04-07 02:17
Just an update to say this is **STILL** a problem and no-one from Signal that I can see anywhere seems to have noticed or cared enough to indicate it will be fixed.  Still unclear whether these bugs actually get seen by anyone?

**Comment by TheLastGimbus** [comment] 2021-04-07 10:27
> no-one from Signal noticed

@greyson-signal... closed #11114... and that's it :expressionless: 

Come on, this is so annoying, and clearly *easy to fix* if workarounds from #10929 make it work (I tried, and they do. I had to teach my mom how to do it :expressionless:)

**Comment by caitsith01** [comment] 2021-04-22 01:52
> 
> 
> > no-one from Signal noticed
> 
> @greyson-signal... closed #11114... and that's it 😑
> 
> Come on, this is so annoying, and clearly _easy to fix_ if workarounds from #10929 make it work (I tried, and they do. I had to teach my mom how to do it 😑)

I don't get what these guys are doing. This shows that they are reading these bugs and yet no-one has had the courtesy to even acknowledge the problem listed here and in multiple related reports, let alone to give any indication of when the (most likely trivial) work will be done to fix this.

**Comment by caitsith01** [comment] 2021-05-10 12:17
This related issue (https://github.com/signalapp/Signal-Android/issues/10929) has been fixed for plain text SMS, but I still have this problem when sharing or forwarding any kind of media.  

@alex-signal is there any way we can get the same fix implemented for MMS, please?

**Comment by greyson-signal** [comment] 2021-05-11 00:17
Should be fixed in 5.11.0 :+1:

**Closed by greyson-signal** 2021-05-11 00:17 UTC

**Comment by caitsith01** [comment] 2021-06-01 09:10
> Apologies, we thought this was fixed, but we see it's not fixed for MMS, and we're looking into it.

This is now fixed for sharing from generic Android apps but not for forwarding media from within signal.
