### ISSUE TITLE
Rejecting call with message does not result in message stored in Signal

### ISSUE THREAD

**Issue by jmayday** [signalapp/Signal-Android#8228] opened 2018-09-28 09:07 UTC
### Bug description
Rejecting call with message (like "I'm busy please call me later") doesn't result in message stored in Signal (while it's default SMS app) but in system Messages app. Also calling side receive message with big delay. 

### Steps to reproduce
- ask someone to call you
- do not answer call but reject with message

**Actual result:** 
- calling end receive message with delay
- check Signal messages - message is not there
- check system Messages app - message is present

**Expected result:**
- message is sent instantly 
- message is stored in Signal app

### Screenshots
some example picture taken from Internet:
![use reject call with message feature in pop up display galaxy s7 edge](https://user-images.githubusercontent.com/10167533/46199160-a5000300-c30e-11e8-982c-24472429a806.jpg)

### Device info

**Device:** Samsung S7 Edge
**Android version:** 8.0.0
**Signal version:** 4.26.2

**Comment by FeuRenard** [comment] 2018-09-28 17:37
Duplicate of #7627

**Comment by greyson-signal** [comment] 2018-09-28 17:57
Yep, thanks @FeuRenard.

**Closed by greyson-signal** 2018-09-28 17:57 UTC
