### ISSUE TITLE
Echoes of the sound in video chat

### ISSUE THREAD

**Issue by reno-a** [signalapp/Signal-Android#7737] opened 2018-04-26 07:14 UTC
Signal 4.18.3 - Motorola Moto G3 - LineageOS 14.1

During video chats, the sound is amplified with a high latency. We hear his voice coming out of the speaker's smartphone of the interlocutor. This echo is unpleasant and prevents the conversation in good conditions.
On others video chat softwares it's not so audible (not even like Wire).

Are there improvements to come, regarding sound, and more importantly this problem echo?

**Comment by FeuRenard** [comment] 2018-04-26 09:44
This issue is a duplicate of #7635.

**Comment by reno-a** [comment] 2018-04-26 12:52
Thank-you @FeuRenard for the link.
Maybe look Wire solution for Audio/Video. Maybe look Wire solution for Audio/Video. The Wire video chat is excellent (https://wire.com/en/ AND https://github.com/wireapp/wire), and without echo problem.

**Closed** 2018-04-26 12:56 UTC
