### ISSUE TITLE
Unable to send SMS today.  Solved.

### ISSUE THREAD

**Issue by jonfen** [signalapp/Signal-Android#10233] opened 2020-11-30 22:01 UTC
Using Google Fi and Pixel 5G no SMS messages were going out today.  They all had spinner icons.  By changing the default app to Messages and then back to Signal the messages were then marked as failed and could be resent.

**Comment by greyson-signal** [comment] 2020-12-01 00:02
Can you please provide a debuglog?

**Comment by n0sign4l-official** [comment] 2020-12-05 22:02
@jonfen if the issue is solved (as written in the title) could you please close the issue? Thanks!

**Closed** 2022-02-03 14:25 UTC
Labels: wontfix
