### ISSUE TITLE
Signal Mesage Reactions are racist

### ISSUE THREAD

**Issue by delondawilliamson** [signalapp/Signal-Android#9776] opened 2020-06-23 02:03 UTC
As a proud Black woman, I go out of my way to set the proper Fitzpatrick Type-6 skin tone whenever I use emojis. The emojis I use are a core part of my identity. Unfortunately when I installed the latest Signal update on my Android, I was disappointed to find that, despite offering litterally thousands of emoji reactions, the hand signs of color have been omitted.

As a side note, all of the testimonials on the front page of signal.org are also from white folks. There are literally more cartoon cats on this page than Black people on that page. At a time when America is coming to grips with its legacy of systemic racism and exclusion this makes me angrier than you can possibly imagine.

Do better.

**Comment by MorgeMoensch** [comment] 2020-06-23 07:00
I don't think those Reaction-Emojis are racist, since they do not offer any human color. If it were the case that one could only select white hands, I would agree. But no (healthy) human has yellow skin - so maybe just see it as a comic-style hand?

**Comment by Rudd-O** [comment] 2020-06-23 09:29
Unbelievable.  This has got to be a s--t test.

It's one thing to suggest "perhaps Signal should support selecting a reaction's skin tone by long-pressing the desired emoji after the emoji reaction list pops up".  This is a valid feature request and it's the polite / decent way to request it.

It's another thing altogether to imply that clearly non-skin-toned emojis are racist.  This is not just outright a lie, but also insulting to the developers and users of the app.

And then to suggest that Signal is racist because the testimonials are "all from white people"?  WTF.

Have you no scruples at all?

**Comment by piratenpanda** [comment] 2020-06-23 09:40
I think it's a fine request, although at the wrong place and maybe not in the right tone. But I am sad to see the typical response of people who most likely never experienced racism. But this goes too far here so I suggest as well moving this to the forum. I also don't see any reason why the reactions can't have the same selector as the normal emojis do.

**Comment by Rudd-O** [comment] 2020-06-23 16:37
To maintainers: the account opening this issue appears to be a troll.  They appear to have opened the account with the express purpose of calling people racist:

![image](https://user-images.githubusercontent.com/346306/85430589-d81d0800-b56f-11ea-9aca-273d1128d2e1.png)

I'd suggest closing the ticket and not feeding the troll any further.

**Comment by delondawilliamson** [comment] 2020-06-23 16:56
The replies to this ticket are a prime example of what WoC face *every single day* when we try to participate in tech discussions. From dismissals of our bias reports, to claiming yellow isn't a legitimate skin color. :rage: 

To the Signal community: do better. Listen and learn. And then act.

**Comment by MorgeMoensch** [comment] 2020-06-23 17:25
@delondawilliamson then tell me, where are the people with yellow skin tone? They dont exist.

And no, it's simply not racist to point out that your point is objectively not true. You may call for black testimonials, but you only weaken your request by putting wrong statements in the same issue.

And what about proposing a new testimonial? This would probably help the most, instead of having a discussion about racism only because Signal uses Comics-Style Emojis for Reactions and writing false statements about tje Signal Website.

**Comment by greyson-signal** [comment] 2020-06-23 18:37
Hi @delondawilliamson, thank you very much for bringing this point up. We agree wholeheartedly that choosing your skin tone for an emoji is very important. The reasons for not including it in the initial release were both technical and UX-based. For instance, on iOS we had to build a custom emoji keyboard from scratch, and still have to spend time to add in skin-tone selection. Also, we were unsure how people would like to see reactions with different skin tones. Would they prefer them to all be considered unique, with their own bubbles? Or would people want to see them clustered in the same bubble, to make it easier to get how many "thumbs ups" there were in total? Would love to hear your thoughts there.

We have work planned to figure these things out, but in the interim, we felt like we could offer this generic “default” selection of emoji so that the functionality is at least there while we continue to iterate on the products. Thank you again for contributing to our community and for underscoring the importance of representation. We hear you and are working to figure out solutions that are both secure and representative of everyone.

**Comment by MorgeMoensch** [comment] 2020-06-23 19:29
> Also, we were unsure how people would like to see reactions with different skin tones. Would they prefer them to all be considered unique, with their own bubbles? Or would people want to see them clustered in the same bubble, to make it easier to get how many "thumbs ups" there were in total? Would love to hear your thoughts there.

I think it's more practical to have these generic emojis. As you said, it makes it easier to make polls, as an example. Also: if you had 4 people with different skin-color giving a thumbs-up, this would clutter the UI while not adding much value (since every thumbs up has the same meaning) and probably hiding other, non-thumbs-up reactions.

**Comment by delondawilliamson** [comment] 2020-06-23 19:45
See this is what I'm talking about. To the Signal developers, inclusion is just an afterthought. Something they'll _maybe_ fix someday if they get called out on it, otherwise nah

**Comment by MorgeMoensch** [comment] 2020-06-23 19:48
> inclusion is just an afterthought

If you want it this way: currently, no one is 'included', so everyone gets treated equally. One may suggesst adding skintones, but treating everyone the same is definitely not racist or excluding.

**Comment by Meteor0id** [comment] 2020-06-23 20:57
"the hand signs of color"
Asif there is somr kind of universal hand Signal. If you and people you know have a have been using some handsignal recently that doesn't mean it should be be adopted in an international mesaging app. Not having done so is not racist.

**Comment by delondawilliamson** [comment] 2020-06-23 21:37
As someone who has struggled against racism all of my life I can't believe I'm getting lectured on whether I should feel excluded by these insensitive decisions made by members of the majority group. It's as rude as it is tone-deaf, especially in the wake of the George Floyd murder.

Please, can the Signal developers weigh in on whether these recent comments reflect their project's values? @greyson-signal I'm looking forward to your response.

**Comment by greyson-signal** [comment] 2020-06-23 23:20
@delondawilliamson We think this is a legitimate request and building a solution for it has always been on the roadmap. The negative responses that you've received are not a reflection of Signal's values. If these types of comments continue, we may be forced to remove responses and/or block accounts.

Signal does the best we can with the resources we have. Our general philosophy is to build things and get them to people quickly so we can get feedback like yours and iterate and improve. So thank you, we're definitely building in the capability to send reactions with different skin tones, and I would love to hear your feedback on some of the questions I asked in my previous comment.

**Comment by Meteor0id** [comment] 2020-06-23 23:29
For my understanding, is OP asking to add some kind if new hand gesture emoji, or is op asking to make all existing hand signs available in a dark skin color (which in my app seems to already be available)

**Comment by kevincianfarini** [comment] 2020-06-23 23:34
Maybe as a catch all feature here....

What if the pre-populated emoji reactions are the top 5 most frequently used emojis for a user? The keyboard for selecting additional emojis already has that information. 

If a user has no emoji reaction history, then pre-populate with the current selections we have.

**Comment by delondawilliamson** [comment] 2020-06-23 23:40
Slack uses the skin tone from the initial reaction, so if a Black person reacts with a thumbs up and then several whites click on the thumbs up too, the Black hand remains.

Or maybe it would be better to select the darkest skin tone from everyone who reacted to the message. Because you can always add more melanin but you can't remove melanin once it's there.

**Comment by Meteor0id** [comment] 2020-06-23 23:48
I think we should avoid giving grouo members any way of influencing which color will resemble the whole group of resoonders, rather randomize it using an algorithm.

**Comment by Meteor0id** [comment] 2020-06-24 10:35
The more I think about this the more it seems like we are debating something which was already solved. Yellow is neutral. We can make it darker yellow if you want, but it's crazy to try to show all variations if skin color for every emoji reaction. It takes up a whole lot of space, and will effectivly give the impression thst skin color is something we need to keep seperated, which is exactly the wrong message. Let's not focus at all on skin tone, and instead pick a neutral color.

This is also not a bug in Signal, so why are we discussing this on GitHub rather than tge community forum?

**Comment by jeroenpraat** [comment] 2020-06-26 16:51
Yellow is not neutral. It resembles white people much more than black people. It's even racist for East-Asian people, cause they are called yellow skinned by some, even if they are not yellow at all. East-Asians skin color ranges from light skinned to medium brown skinned.

I agree with the OP and hope Signal can respect PoC. The Slack solution is great, but a better solution would be if the reaction emoji color that is shown, is the same as the one the user has chosen for themselves.

**Comment by MrWaste** [comment] 2020-06-27 05:54
So what about orange? I don't know. Changing the skin tone is not going to fix this. Its just going to make this worse. Darken the color because there is not much you can do with it. Like what else do you want, its a neutral color!

**Comment by kashizui** [comment] 2020-06-28 07:44
As an East Asian person, the yellow color has always made me rather uncomfortable, given the history of Asian stereotypes and racism in the US (cannot speak for other countries).
I also think yellow is certainly closer to light skin colors visually than dark skin colors.
Trying to pick a "middle ground" (or orange) also seems dangerous.

If we really want a neutral, non-human color, why not blue? 
Or purple, or green?
💙💜💚

**Comment by MorgeMoensch** [comment] 2020-06-28 08:16
> I also think yellow is certainly closer to light skin colors visually than dark skin colors.

I don't understand why one has to make always a connection to actual human skin colours.

> If we really want a neutral, non-human "default" color, why not blue?
> Or purple, or green?

I think using yellow is a good choice, since it matches the 'non-human' emojis like 😀🤗 etc. which leads to a consistent vibe.

**Comment by kashizui** [comment] 2020-06-28 21:02
I understand that for some (or even many) it's easy to compartmentalize and rationally avoid connecting yellow with human skin tones.

Humans are not inherently rational though, nor do we make every mental association consciously.
I think for a product used by the general public, we do have to be aware of the subconscious impact of these design choices.

**Comment by kousu** [comment] 2020-06-28 21:46
> To maintainers: the account opening this issue appears to be a troll. They appear to have opened the account with the express purpose of calling people racist:
> 
> I'd suggest closing the ticket and not feeding the troll any further.

@Rudd-O is right, this person is a troll. This is an attempt to feel powerful by puppetting peoples' emotions, and to spread uncertainty and doubt, much like the ok-hand campaign:

* https://knowyourmeme.com/photos/1249757-ok-symbol-%F0%9F%91%8C
* https://www.adl.org/blog/how-the-ok-symbol-became-a-popular-trolling-gesture
* https://www.independent.co.uk/news/world/americas/ok-sign-white-power-supremacy-alt-right-4chan-trolling-hoax-a9249846.html
* https://mashable.com/article/ok-hand-gesture-hate-symbol-anti-defamation-league-white-sumpremacy/
* https://www.theguardian.com/world/2019/oct/03/ok-sign-gesture-emoji-rightwing-alt-right

The ok-hand campaign succeeded:

* https://www.npr.org/2019/09/26/764728163/the-ok-hand-gesture-is-now-listed-as-a-symbol-of-hate

Please don't let the same happen here.

**Comment by condemnedmeat** [comment] 2020-06-28 22:48
I know now how to get a signal developer to immediately respond to my issue and bend to my will. No matter how implicitly racist and outrageously rude I am.

Sigh.

Responding positively is appeasement. Appeasement will guzzle your resources, things that many sensible, articulate and rational people think are fundamentally important will suffer as a result.

The OP isn't, by modern standards, a troll. Nor are her views representantive

**Comment by jeroenpraat** [comment] 2020-06-29 11:43
@kousu The OK-gesture is from the alt-right. So what the f are you talking about! 

Calling someone who tries to point out (intended or unintended) racism in the tech world a troll, is a lot more racist than the yellow default skin tone.

**Comment by greyson-signal** [comment] 2020-06-30 03:54
We have all the information that we need to work on this, so we are locking the thread for now.

**Comment by greyson-signal** [comment] 2020-07-22 13:04
Android 4.67.x (currently in beta) adds the ability to select skin tone variations of reactions. It adds what we consider to be the bare minimum support, and more changes are planned in the future. Specifically, 4.67:

- Allows long-pressing an emoji to select a skin tone variation
- Skin tone variations of the same 'base emoji' will be grouped together in the badge.
- When picking which variation to show in the reaction bubble, we will always prefer the variation you selected if you are participating in the reaction, and show the most recent if not.

We still have more changes planned, including:
- Saving the skin tone variation you last selected for a specific emoji, so you don't always have to long-press.
- Adding support for long-press in the 'recents' tab.
- A slew of other UI improvements for reactions in general.

Thanks!

**Closed by greyson-signal** 2020-07-22 13:04 UTC
