### ISSUE TITLE
Image thumbnails not loading while sharing images and videos

### ISSUE THREAD

**Issue by vithultnair** [signalapp/Signal-Android#10452] opened 2021-01-10 16:52 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Image thumbnails are not being loaded when images or videos are shared except the first few images.

### Steps to reproduce
- Open any chat
- Attach icon
- Gallery
- Any folder

**Actual result:** 
Thumbnails of images and videos are not loading except the first few ones, others are shown black.

**Expected result:** 
Thumbails of all images should load while selecting images or videos for sending.

### Screenshots
![Screenshot_20210110-222045](https://user-images.githubusercontent.com/64826398/104129410-2837ac80-5392-11eb-892f-cf442622d4b9.png)

### Device info

**Device:** Motorola One Power
**Android version:** 10
**Signal version:** 5.0.8

### Link to debug log
https://debuglogs.org/8ada230710fb73d239a6a20084ba93b71ec3b990c4564eda9882f2c58d997e49

**Comment by Genis-Sage** [comment] 2021-01-10 17:43
hey @vithultnair 

i guess, this is a duplicate of #10394

**Comment by greyson-signal** [comment] 2021-01-11 04:50
Closing as a duplicate of #10394

**Closed by greyson-signal** 2021-01-11 04:50 UTC
