### ISSUE TITLE
Group call feature 

### ISSUE THREAD

**Issue by leonardoporpora** [signalapp/Signal-Android#7414] opened 2018-02-15 09:03 UTC
Add group call feature. But I don’t have to be obliged to have created a group I would like to simply call someone and once I am in the call add other people to this call

**Comment by FeuRenard** [comment] 2018-02-15 09:55
This is a duplicate of #6075.

**Closed** 2018-02-15 19:08 UTC

**Comment by alerque** [comment] 2018-04-13 09:06
The supposed duplicate of this issue got auto-closed and locked. Can we get one issue that's open tracking progress on this feature?

**Comment by haffenloher** [comment] 2018-04-13 11:39
Hey @alerque, feature requests are now being tracked in the forums. The thread for group calls is https://community.signalusers.org/t/conference-calls/870.
