### ISSUE TITLE
Signal is using mobile data for call when connected to WiFi

### ISSUE THREAD

**Issue by rrthomas** [signalapp/Signal-Android#9488] opened 2020-03-20 15:42 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
In the last couple of days I've made some long voice and video calls while connected to reliable WiFi at home. Signal has used large amounts (tens of megabytes) of mobile data. When I switch off mobile data, Signal calls continue to work fine, so it doesn't appear to be a connectivity problem. I also tried disabling "Auto network switch" in case Android was switching over to mobile data, but that didn't help.

### Steps to reproduce
- Make an audio or video call while connected to WiFi
- Observe mobile data usage

**Actual result:** Lots of mobile data used
**Expected result:** No mobile data used

### Device info
**Device:** Sony Xperia XZ1 Compact
**Android version:** 9.0
**Signal version:** 4.57.1

### Link to debug log
https://debuglogs.org/6cf0fa6438c6f67cb3b374bd135bdf7b806543f4adc609df624b61905e1d8072

**Comment by bme13** [comment] 2020-03-21 19:52
Hi, This seems related/duplicate of #8529.

**Comment by rrthomas** [comment] 2020-03-21 19:59
I agree. Not sure why I couldn't find that issue when I searched before filing this one, sorry.

**Comment by greyson-signal** [comment] 2020-03-24 16:52
Closing as duplicate of #8529

**Closed by greyson-signal** 2020-03-24 16:52 UTC
