### ISSUE TITLE
Not able to use app without play services

### ISSUE THREAD

**Issue by indahud** [signalapp/Signal-Android#10368] opened 2021-01-08 06:03 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.
I have installed Signal apk from your official website and also from play store.I am using Android One Phone without any Google dependencies like play services, play store etc. But i am getting Play Services Error toast.I don't know how app is going to run on custom ROM like linageOS, grapheneOS.    

### Steps to reproduce
- Install Signal app from Play store or official website on Android Phone without Google dependencies.
- Open the app
- Enter phone number and click on next button.

**Actual result:** App is displaying play services error toast message.
**Expected result:** App should proceed without play services error.

### Screenshots

![Signal](https://user-images.githubusercontent.com/47686324/103980163-3c539200-5177-11eb-8805-35db43bf9a1c.png)

### Device info

**Device:** Nokia 6.1 Plus
**Android version:** 10
**Signal version:** 5.0.8

**Comment by Genis-Sage** [comment] 2021-01-08 07:55
hey @indahud 

could you describe, how you installed your phone to not have Google Play Services?
Did you install a custom ROM?
or what did you do?

and how do you "Install Signal app from Play store" if you are " using Android One Phone without ... play store"


you issue could be a duplicate of #9043 or #9279


regarding your question about CustomROMs, here's the answer:
https://github.com/signalapp/Signal-Android/issues/9702#issuecomment-652519890

**Comment by indahud** [comment] 2021-01-08 09:06
I used adb to remove all the Google apps using `adb shell pm uninstall -k --user 0 app-name`. I am not using any custom ROM. I am using Aurora Store from Fdroid, alternative to Play store.

**Comment by Genis-Sage** [comment] 2021-01-08 09:28
@indahud 
then this is not an Signal issue

this ADB command is not doing what you think it does

see https://community.signalusers.org/t/why-am-i-being-forced-to-use-google-play-services/10410/21

**Comment by indahud** [comment] 2021-01-08 10:56
The solution was to disable play services after uninstalling for user 0.

**Closed** 2021-01-08 10:56 UTC
