### ISSUE TITLE
SMS Messages sent with Google Assistant do not show up in Signal

### ISSUE THREAD

**Issue by Wigsinator** [signalapp/Signal-Android#7627] opened 2018-04-04 00:06 UTC
- [x] I have searched open and closed issues for duplicates (Issues were closed during cleanup without being solved, Dupe of #5803 )
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When a text is sent through Google Assistant, the text does not appear in the Signal Chatlogs

### Steps to reproduce
- Have Signal installed as default SMS app
- Send a text through Google Assistant
- Text does not appear in Signal conversation

**Actual result:** Sent text appears in Messages App
**Expected result:** Sent text should appear in Signal

### Device info

**Device:** Google Pixel 2
**Android version:** 8.1.0
**Signal version:** 4.17.5

### Link to debug log

https://debuglogs.org/ddce3a178ebe73e6923d478a1264c7e963fa0038cdbfb47628aa7e75092d78b7

**Comment by sampablokuper** [comment] 2018-04-04 00:25
Dupe of #5803?

**Comment by Wigsinator** [comment] 2018-04-04 01:06
Yes, it's a dupe, but you closed that one during the cleanup.  It's still a valid issue, the reproduction steps are up to date, and on a recent version of Signal, and I posted my own debug log. I should have put the number in the original in the main body, I'll do so now.

**Comment by sampablokuper** [comment] 2018-04-04 01:24
@Wigsinator , whoa there. *I* did not close that bug report. That seems to have been done by @jlund-signal as part of the (IMO deeply misguided) #7598.

**Comment by moxie0** [comment] 2018-04-04 11:29
Thanks for the report, but sadly there is no real action that I can take here. As far as I can tell there is:

1. No API that allows Google Assistant to send SMS via Signal.
2. No API that notifies us of a message sent by Google Assistant.

The only option would be to periodically scan the system SMS database for new sent messages, somehow determine whether or not they are duplicate to what we've already seen, and then somehow insert them into our database. This would be extremely unreliable, since that periodic scan might not happen before you next look at your conversation history.

I'd be happy to revisit if Google provides an API that allows for the functionality you want, or if someone can point out an API that I've overlooked.

**Closed by moxie0** 2018-04-04 11:29 UTC
Labels: bug, sms

**Comment by anisse** [comment] 2018-04-04 17:16
@moxie0 A quick search shows you can register a content observer in a service:

https://stackoverflow.com/a/5808648

What am I missing?

**Comment by Wigsinator** [comment] 2018-04-04 21:27
@sampablokuper  sorry, I didn't mean to come across as hostile.  I said you as in "The Signal devs", as I assumed you were a part of that team due to the speed at which the dupe was noticed.  I never meant to imply anything beyond that.

@moxie0 It's a shame that nothing can be done. Thank you for looking into it!

**Comment by moxie0** [comment] 2018-04-05 10:40
@anisse That only works while the service is running. You can do your best to keep it running by making it a foreground service (which will display a persistent notification in the notification bar that can not be dismissed), but even then it's no guarantee the OS won't kill it.

**Comment by anisse** [comment] 2018-04-05 12:08
@moxie0 It's true, I forgot about that. This is indeed challenging, but this is something that could be dealt with ; you don't really need the service to run all the time, if you remember the sms database cursor position in Signal, you could re-launch it when you open the Activity.

And if the messages take a few seconds to appear *after* you launch Signal, it's still a good compromise: by the time you start wondering what your contact is answering to, the message you sent has already appeared in the conversation view.

Not everything is straightforward, and sometimes software needs to be "hacky" and jump though hoops to provide value. Could this be labelled as "help wanted"? If someone is crazy enough to try to make it work would you accept to review a PR of a complex implementation for a "legacy" SMS feature ?

**Comment by moxie0** [comment] 2018-04-05 12:12
Messages would be ordered incorrectly, deletes could only be synchronized in one direction, there could be long delays before messages appear at all, etc. In my view a feature should work well, or it shouldn't exist. I don't want to put in anything that's flaky.

**Comment by anoxi** [comment] 2018-10-02 20:34
Is there any hope to get an API from Google Assistant that these SMS messages get to the Signal app? Otherwise, I understand the only alternative is to switch SMS handling back to the native SMS app.

**Comment by old-square-eyes** [comment] 2021-01-07 03:55
This just happened to me. And I got pretty confused/poor experience etc.

Not withstanding challenges already raised. I have more of a general question... Google allows 3rd party apps handle SMS. Samsung etc, and Google themselves have a couple.

How do they work? Do they not get to view Assistant outbound messages either? It's been said above a feature should work well if at all... but having gaps in messages like this is marrs the whole SMS experience and undermines Assistant which is obviously not properly integrated into the system level SMS ecosystem.

To be clear, I'm just complaining about the Android native / system level SMS implementation more than anything... but I'd prefer If Signal could work around it. Even if the sync wasn't in real time.
