### ISSUE TITLE
Android phone overheating while on Signal voice call

### ISSUE THREAD

**Issue by ohimu** [signalapp/Signal-Android#11294] opened 2021-05-13 05:46 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal voice call is overheating android phone. Please not that, this kind of heating actually occurs while on video call with any other messaging app for obvious reason of video processing and high CPU usage., but not on voice call.
### Steps to reproduce
- Initiate a voice call
- Monitor device temperature

**Actual result:** Phone overheats
**Expected result:** No abnormal heating

### Device info

**Device:** Xiaomi Mi A2
**Android version:** 11 (Lineage OS 18.1)
**Signal version:** 5.7.9

**Comment by Oymate** [comment] 2021-05-13 14:28
Please +1 this issue https://github.com/signalapp/Signal-Android/issues/9687 and close this :)

**Comment by greyson-signal** [comment] 2021-05-13 15:18
Closing as a duplicate of #9687

**Closed by greyson-signal** 2021-05-13 15:18 UTC

**Comment by MrWaste** [comment] 2022-02-27 23:32
Check this post just updated it again. https://github.com/signalapp/Signal-Android/issues/9798

If I am missing any phones in the list please let me know.
