### ISSUE TITLE
Messages not sent using WiFi/Mobile Network

### ISSUE THREAD

**Issue by Edu4rdSHL** [signalapp/Signal-Android#8382] opened 2018-11-18 00:38 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------
Probably related with #8365, if it's the same, feel free to close it and sorry.

### Bug description
Messages stop being sent since the latest Signal releases in random times, messages are seen in the "Sending" state. It's happening non only for me, it's happening also to my friends that are using signal since months ago.

### Steps to reproduce
- I can not describe "how to reproduce" because it happens in random times without specific conditions and not for all users at the same time. When i taked the screenshot I was sending/receiving messages from anothers user.

**Actual result:** Messages keep in the "sending" state anyways if network are available.
**Expected result:** Messages are sent.

### Screenshots

![20181117_193056](https://user-images.githubusercontent.com/32582878/48667260-08511a80-eaa0-11e8-8fa1-dc44b33c409f.jpg)

### Device info

**Device:** Samsung SM-G610M
**Android version:** 8.1.0
**Signal version:** 4.30.6

### Link to debug log

https://debuglogs.org/944ef395438a506e2dd788bb1c38ef479c10111456caa1961a7c765b19baab2d

**Comment by greyson-signal** [comment] 2018-11-18 01:12
This actually looks like a dupe of #8370.

```java
2018-11-17 18:12:12.758 GMT-05:00 I Job: [fb3ead61-9646-41b9-ab13-c2c3e2266bef] PushTextSendJob :: Retrying due to unmet requirements. (Time since submission: 898502 ms, Run attempt: 4, isStopped: false)
```

It looks like the first message took a while to send for whatever reason (log doesn't go back far enough to say why, maybe poor network), and then your screen locked. At this point, messages will fail to send and increase the time between retries to the point where when the app is open, the time between retries was getting pretty long (minutes). To add to that, messages sent in the same conversation need to wait for the previous message to send, so the whole convo gets kinda stuck. 

There's a fix for this in the next beta release that should release early this coming week (I didn't want to put it in this latest release due to the risk of the change). In the short term, you can consider switching to a manual screen lock (basically remove the timeout and lock the screen via the notification after your messages send). And you can get these latest messages to send by leaving the screen lock off until they go through.

Sorry for any frustration -- this should be fixed soon!

**Closed by greyson-signal** 2018-11-18 01:12 UTC
