### ISSUE TITLE
Backup triggered twice a day

### ISSUE THREAD

**Issue by UserX404** [signalapp/Signal-Android#13559] opened 2024-05-11 06:27 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Since the latest update (7.6.x) the backup seems to be triggered twice in a row.
See timestamp names of the uploaded files to my nextcloud.
The issue was reported on the [forum](https://community.signalusers.org/t/double-backup-issue/60663/8) and after check I recognized I'm also affected.

### Steps to reproduce
- enable auto backup

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
Two files were generated each day
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
One backup per day

### Screenshots
Upload dir on my Nextcloud

![grafik](https://github.com/signalapp/Signal-Android/assets/14954521/e4630639-cd19-4a70-8fb4-026dc108308d)

### Device info

**Device:** Sony Xperia XZ2c
**Android version:** 13
**Signal version:** 7.6.2

### Link to debug log

https://debuglogs.org/android/7.6.2/a5f8c2b56ce3e295a87e7e6ec2b4adf96f223df99d5d46cef2c8e131c994b96f

**Comment by RAS915** [comment] 2024-05-12 12:02
I have the same problem. I have auto-backup set to 22:00, but Signal creates two backups, one at 21:55 and the other at 22:05.

**Comment by pippi1otta** [comment] 2024-05-12 13:15
Same here, two backup files created, almost back to back.

**Comment by Lion-box** [comment] 2024-05-18 08:02
Sane exact issue here: backup twice in a row.
Log here:
https://debuglogs.org/android/7.6.2/e67b6ffab9fc9f4dcb294e56682e48e9c7b07c00227261f71f97eef82807debe

**Comment by klausklemens** [comment] 2024-05-19 06:09
Same here. The backup is scheduled for 8am.
The first backup started at like 7:55am and again just after 8am.

**Comment by bjo81** [comment] 2024-05-22 15:51
Also getting this issue, debug log at https://debuglogs.org/android/7.8.1/23988e28401030827f94aae44ce7767ff55e0bdb2ef538921e740827508164db

**Comment by squandita** [comment] 2024-05-24 14:05
![Screenshot_20240524_090420_My Files](https://github.com/signalapp/Signal-Android/assets/170738719/b08171cd-f877-4d23-bd99-58eb9011e1a5)
Same thing here. 

Would like to figure this out.

**Comment by DidierLoiseau** [comment] 2024-05-29 23:17
Same issue here. I don’t know if it’s relevant, but I’m using FolderSync to move the backups to my NAS. So when Signal runs, it always finds an empty folder.

I checked in the logs, and it seems that it reschedules the execution for a few minutes after immediately upon initiating the first backup. In my log I see:
```
[7.6.2] [main ] 2024-05-27 04:25:40.039 GMT+02:00 I PersistentAlarmManagerL: [LocalBackupListener] onReceive(null)
[7.6.2] [main ] 2024-05-27 04:25:40.043 GMT+02:00 I PersistentAlarmManagerL: [LocalBackupListener] onAlarm(): scheduled: 1716776740000 actual: 1716776740043
[7.6.2] [175  ] 2024-05-27 04:25:40.060 GMT+02:00 I Job: [JOB::532120d9-31e9-4738-9cd6-6d2862d7fe83][LocalBackupJobApi29] onSubmit() (Time Since Submission: 14 ms, Lifespan: Immortal, Run Attempt: 1/3, Queue: __LOCAL_BACKUP__)
[7.6.2] [196  ] 2024-05-27 04:25:40.062 GMT+02:00 I JobRunner: [JOB::532120d9-31e9-4738-9cd6-6d2862d7fe83][LocalBackupJobApi29][2] Running job. (Time Since Submission: 4 ms, Lifespan: Immortal, Run Attempt: 1/3, Queue: __LOCAL_BACKUP__)
[7.6.2] [178  ] 2024-05-27 04:25:40.062 GMT+02:00 I JobSchedulerScheduler: JobScheduler enqueue of  (0)
[7.6.2] [main ] 2024-05-27 04:25:40.064 GMT+02:00 I PersistentAlarmManagerL: [LocalBackupListener] scheduling exact alarm for: 1716777196000 hasManagerPermission: true
```
and of course a few minutes later:
```
[7.6.2] [main ] 2024-05-27 04:33:16.040 GMT+02:00 I PersistentAlarmManagerL: [LocalBackupListener] onReceive(null)
[7.6.2] [main ] 2024-05-27 04:33:16.041 GMT+02:00 I PersistentAlarmManagerL: [LocalBackupListener] onAlarm(): scheduled: 1716777196000 actual: 1716777196041
[7.6.2] [175  ] 2024-05-27 04:33:16.046 GMT+02:00 I Job: [JOB::839799d5-2bc1-42b9-a787-5c8ae2d6c84f][LocalBackupJobApi29] onSubmit() (Time Since Submission: 4 ms, Lifespan: Immortal, Run Attempt: 1/3, Queue: __LOCAL_BACKUP__)
[7.6.2] [main ] 2024-05-27 04:33:16.047 GMT+02:00 I PersistentAlarmManagerL: [LocalBackupListener] scheduling exact alarm for: 1716863385000 hasManagerPermission: true
```
`1716863385000` is for the next day, however I notice the log reschedules it several times over the course of the day:
```
[7.6.2] [198  ] 2024-05-27 09:27:47.289 GMT+02:00 I PersistentAlarmManagerL: [LocalBackupListener] scheduling exact alarm for: 1716863385000 hasManagerPermission: true
[7.6.2] [201  ] 2024-05-27 10:02:08.008 GMT+02:00 I PersistentAlarmManagerL: [LocalBackupListener] scheduling exact alarm for: 1716863385000 hasManagerPermission: true
[7.6.2] [198  ] 2024-05-27 12:04:24.151 GMT+02:00 I PersistentAlarmManagerL: [LocalBackupListener] scheduling exact alarm for: 1716863385000 hasManagerPermission: true
[7.6.2] [209  ] 2024-05-27 19:14:23.365 GMT+02:00 I PersistentAlarmManagerL: [LocalBackupListener] scheduling exact alarm for: 1716863385000 hasManagerPermission: true
[7.6.2] [233  ] 2024-05-28 04:16:08.397 GMT+02:00 I PersistentAlarmManagerL: [LocalBackupListener] scheduling exact alarm for: 1716863385000 hasManagerPermission: true
```
and finally the job runs and reschedules it for a few minutes later with timestamp `1716863509000`:
```
[7.6.2] [main ] 2024-05-28 04:29:45.070 GMT+02:00 I PersistentAlarmManagerL: [LocalBackupListener] onReceive(null)
[7.6.2] [main ] 2024-05-28 04:29:45.073 GMT+02:00 I PersistentAlarmManagerL: [LocalBackupListener] onAlaonReceiverm(): scheduled: 1716863385000 actual: 1716863385073
[7.6.2] [260  ] 2024-05-28 04:29:45.083 GMT+02:00 W OkHttpWebSocketConnection: [normal:262120075] onFailure()
java.net.SocketException: Software caused connection abort
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:118)
	at java.net.SocketInputStream.read(SocketInputStream.java:173)
	at java.net.SocketInputStream.read(SocketInputStream.java:143)
	at org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:920)
	at org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:884)
	at org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:799)
	at org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:772)
	at okio.InputStreamSource.read(JvmOkio.kt:94)
	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:125)
	at okio.RealBufferedSource.request(RealBufferedSource.kt:60)
	at okio.RealBufferedSource.require(RealBufferedSource.kt:53)
	at okio.RealBufferedSource.readByte(RealBufferedSource.kt:66)
	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:117)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

[7.6.2] [261  ] 2024-05-28 04:29:45.084 GMT+02:00 W OkHttpWebSocketConnection: [unidentified:19287193] onFailure()
java.net.SocketException: Software caused connection abort
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:118)
	at java.net.SocketInputStream.read(SocketInputStream.java:173)
	at java.net.SocketInputStream.read(SocketInputStream.java:143)
	at org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:920)
	at org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:884)
	at org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:799)
	at org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:772)
	at okio.InputStreamSource.read(JvmOkio.kt:94)
	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:125)
	at okio.RealBufferedSource.request(RealBufferedSource.kt:60)
	at okio.RealBufferedSource.require(RealBufferedSource.kt:53)
	at okio.RealBufferedSource.readByte(RealBufferedSource.kt:66)
	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:117)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

[7.6.2] [261  ] 2024-05-28 04:29:45.085 GMT+02:00 I OkHttpWebSocketConnection: [unidentified:19287193] Client not null when closed
[7.6.2] [260  ] 2024-05-28 04:29:45.085 GMT+02:00 I OkHttpWebSocketConnection: [normal:262120075] Client not null when closed
[7.6.2] [241  ] 2024-05-28 04:29:45.085 GMT+02:00 D IncomingMessageObserver: WebSocket State: FAILED
[7.6.2] [236  ] 2024-05-28 04:29:45.104 GMT+02:00 D IncomingMessageObserver: [Does Not Need Connection] Network: true, Foreground: false, Time Since Last Interaction: 815460 ms (over limit), FCM: true, Stay open requests: [], Registered: true, Proxy: false, Force websocket: false
[7.6.2] [266  ] 2024-05-28 04:29:45.104 GMT+02:00 I OkHttpWebSocketConnection: [normal:241085314] connect()
[7.6.2] [236  ] 2024-05-28 04:29:45.113 GMT+02:00 W IncomingMessageObserver: Shutting down pipe...
[7.6.2] [main ] 2024-05-28 04:29:45.143 GMT+02:00 I PersistentAlarmManagerL: [LocalBackupListener] scheduling exact alarm for: 1716863509000 hasManagerPermission: true
[7.6.2] [235  ] 2024-05-28 04:29:45.154 GMT+02:00 I Job: [JOB::1ee96ce6-2865-4d8d-94fa-69ed20ed0184][LocalBackupJobApi29] onSubmit() (Time Since Submission: 36 ms, Lifespan: Immortal, Run Attempt: 1/3, Queue: __LOCAL_BACKUP__)
[7.6.2] [248  ] 2024-05-28 04:29:45.155 GMT+02:00 I JobRunner: [JOB::1ee96ce6-2865-4d8d-94fa-69ed20ed0184][LocalBackupJobApi29][2] Running job. (Time Since Submission: 15 ms, Lifespan: Immortal, Run Attempt: 1/3, Queue: __LOCAL_BACKUP__)
[7.6.2] [266  ] 2024-05-28 04:29:45.155 GMT+02:00 I OkHttpWebSocketConnection: [normal:241085314] Sending keep alive...
[7.6.2] [233  ] 2024-05-28 04:29:45.157 GMT+02:00 D IncomingMessageObserver: WebSocket State: CONNECTING
[7.6.2] [238  ] 2024-05-28 04:29:45.158 GMT+02:00 I JobSchedulerScheduler: JobScheduler enqueue of  (0)
[7.6.2] [248  ] 2024-05-28 04:29:45.163 GMT+02:00 I LocalBackupJobApi29: Executing backup job...
```
(I assume the stacktrace in the middle is unrelated, but I’m keeping it for completeness)
and then the job runs again and reschedules for the next day:
```
[7.6.2] [main ] 2024-05-28 04:31:49.045 GMT+02:00 I PersistentAlarmManagerL: [LocalBackupListener] onReceive(null)
[7.6.2] [main ] 2024-05-28 04:31:49.047 GMT+02:00 I PersistentAlarmManagerL: [LocalBackupListener] onAlarm(): scheduled: 1716863509000 actual: 1716863509047
[7.6.2] [235  ] 2024-05-28 04:31:49.052 GMT+02:00 I Job: [JOB::4aed4eef-8721-4f91-ad1d-15376a69a7d3][LocalBackupJobApi29] onSubmit() (Time Since Submission: 5 ms, Lifespan: Immortal, Run Attempt: 1/3, Queue: __LOCAL_BACKUP__)
[7.6.2] [241  ] 2024-05-28 04:31:49.052 GMT+02:00 I JobSchedulerScheduler: JobScheduler enqueue of  (0)
[7.6.2] [main ] 2024-05-28 04:31:49.053 GMT+02:00 I PersistentAlarmManagerL: [LocalBackupListener] scheduling exact alarm for: 1716949509000 hasManagerPermission: true
```
again, I see several schedulings over the course of the day:
```
[7.6.2] [242  ] 2024-05-28 08:46:20.795 GMT+02:00 I PersistentAlarmManagerL: [LocalBackupListener] scheduling exact alarm for: 1716949509000 hasManagerPermission: true
[7.6.2] [238  ] 2024-05-28 20:23:27.181 GMT+02:00 I PersistentAlarmManagerL: [LocalBackupListener] scheduling exact alarm for: 1716949509000 hasManagerPermission: true
[7.6.2] [234  ] 2024-05-28 20:37:22.935 GMT+02:00 I PersistentAlarmManagerL: [LocalBackupListener] scheduling exact alarm for: 1716949509000 hasManagerPermission: true
```
but when it ran, this time it was only executed once and properly rescheduled for today:
```
[7.6.2] [main ] 2024-05-29 04:29:45.521 GMT+02:00 I PersistentAlarmManagerL: [LocalBackupListener] onReceive(null)
[7.6.2] [main ] 2024-05-29 04:29:45.557 GMT+02:00 I PersistentAlarmManagerL: [LocalBackupListener] onAlarm(): scheduled: 1716949509000 actual: 1716949785557
[7.6.2] [241  ] 2024-05-29 04:29:45.608 GMT+02:00 D NetworkConnectionListen: ConnectivityManager.NetworkCallback onBlockedStatusChanged()
[7.6.2] [main ] 2024-05-29 04:29:45.742 GMT+02:00 I PersistentAlarmManagerL: [LocalBackupListener] scheduling exact alarm for: 1717036144000 hasManagerPermission: true
```
(next run in a few hours)

I can provide the logs if desired but many people have already done so, so I assume it isn’t necessary.

**Comment by DidierLoiseau** [comment] 2024-05-29 23:29
Oh well, based on the log I just posted, I had a look at `LocalBackupListener`, and [the bug is pretty obvious](https://github.com/signalapp/Signal-Android/blob/eb114de5c8486f6cb3f82a7ce5baed0564b3f6c8/app/src/main/java/org/thoughtcrime/securesms/service/LocalBackupListener.java#L52-L58):
```java
    LocalDateTime next   = now.withHour(hour).withMinute(minute).withSecond(0);

    int jitter = (new Random().nextInt(BACKUP_JITTER_WINDOW_SECONDS)) - (BACKUP_JITTER_WINDOW_SECONDS / 2);
    next = next.plusSeconds(jitter);

    if (now.isAfter(next)) {
      next = next.plusDays(1);
    }
````
Basically, the code adds some jitter to the next schedule time, and only adds one day if the next scheduled time would be in the past. As the jitter is positive half of the time, it reschedules the backup immediately in those case. Theoretically I guess it could run up to 10 times in a row.

This is a regression from recent commit 8a972d9 – the jitter was not actually applied before since `LocalDateTime` is immutable. I guess the proper fix would be to apply the jitter after the following `if`.

**Comment by joergrs** [comment] 2024-06-04 08:41
I am facing the same issue. Every night two 3 GB files are created instead of one. I am on version 7.6.2

![IMG_20240604_104026](https://github.com/signalapp/Signal-Android/assets/8045731/bb199d66-7f39-40de-a8d1-4346bd4eb285)

**Comment by UserX404** [comment] 2024-06-05 21:57
Maybe fixed https://github.com/signalapp/Signal-Android/commit/1565ecdcea298463fbbe0ff6b788004b96ddfa76

**Comment by bjo81** [comment] 2024-06-06 05:52
Installed 7.9.0 via AppTester, let's see if it's fixed.

**Comment by DidierLoiseau** [comment] 2024-06-06 07:21
> Maybe fixed 1565ecdcea298463fbbe0ff6b788004b96ddfa76

@clark-signal and @cody-signal, it’s unfortunate you don’t reference this issue in 1565ecdcea298463fbbe0ff6b788004b96ddfa76.

However, I think **this is not the proper fix**. I thought more about it, and it won’t work if `now` is before the configured backup time, due to the jitter that was computed during the previous run. Moreover, in that case, the jiter may cause `next` to be in the past.

The easiest fix would probably be to just make sure that the jiter is always positive.

Alternatively, the check should make sure that `next` is after the allowed jiter window, something like:

```java
    if (!next.isAfter(now.plusSeconds(BACKUP_JITTER_WINDOW_SECONDS / 2))) {
      next = next.plusDays(1);
    }

    int jitter = (new Random().nextInt(BACKUP_JITTER_WINDOW_SECONDS)) - (BACKUP_JITTER_WINDOW_SECONDS / 2);

    next = next.plusSeconds(jitter);
```
(I wanted to test this but it seems complicated to write a unit tests due to the heavy use of static methods, and actually deploying a build requires to setup a new Signal account with a new number or on the staging environment, apparently…)

**Comment by bjo81** [comment] 2024-06-06 22:19
Still not fixed with 7.9.0:

https://debuglogs.org/android/7.9.0/6a5fc5cf3b21ac6173a255a3cd0af8d5303a568a544aa81b22dbf748559d4cab

**Comment by cody-signal** [comment] 2024-06-07 19:47
Thanks, we're taking another swing at it.

**Comment by DidierLoiseau** [comment] 2024-06-24 21:08
I have joined the beta program for a week now, and as far as I can tell the backups are not triggered twice anymore.

**Comment by bjo81** [comment] 2024-06-25 06:53
Here the are triggered still twice.

**Comment by DidierLoiseau** [comment] 2024-06-25 07:56
@bjo81 it might be good to specify the version you are using 😉 (I’m on 7.9.6)

**Comment by bjo81** [comment] 2024-06-25 08:08
I'm also on 7.9.6, logs: https://debuglogs.org/android/7.9.6/23341a4baba2b11fa8f9a92bd85f9ad2dccd59fd906f4b486fc97a86088b8f10

**Comment by DidierLoiseau** [comment] 2024-06-25 11:44
@bjo81 indeed it seems the bug is still there when you schedule the backup for midnight or just after. Because of the jitter, it is possible that your backup will run before midnight, in which case the backup will run a second time in 100% of the cases (because the default scheduled time without jitter will be midnight on the same day).

[Relevant code here](https://github.com/signalapp/Signal-Android/blob/93ec322bb9be3a17571eb5c9314f23b2a957738c/app/src/main/java/org/thoughtcrime/securesms/service/MessageBackupListener.kt#L44-L54)

As a workaround you could schedule it at any time between 00:05 and 23:59.

**Comment by bjo81** [comment] 2024-06-26 08:36
> As a workaround you could schedule it at any time between 00:05 and 23:59.

Thanks for the hint, set it to 23:45 and it's not triggered twice.

**Comment by Lion-box** [comment] 2024-06-26 08:39
working fine here with backup set at 4:00

**Comment by UserX404** [comment] 2024-06-26 10:09
Thx @Lion-box for the reminder :+1:

**Closed** 2024-06-26 10:08 UTC

**Comment by nicholas-signal** [comment] 2024-06-26 14:07
For those with issues, please try scheduling the backup time to after 00:05. If it still happens twice, feel free to submit a debug log and we'll take another look.

**Comment by DidierLoiseau** [comment] 2024-06-26 14:37
@nicholas-signal do you mean that it is normal that the default schedule of Signal will still trigger the backup twice?

**Comment by nicholas-signal** [comment] 2024-06-26 15:48
> @nicholas-signal do you mean that it is normal that the default schedule of Signal will still trigger the backup twice?

There is some jitterin the current impl, so there is a small chance that the backup will be triggered twice as outlined by @DidierLoiseau. We will fix it in an upcoming version. But I wanted to be explicit about mitigation steps for anyone who finds this github issue in the years to come, and whether they should start a new ticket should this issue (with a different root cause) arise again.

**Comment by DidierLoiseau** [comment] 2024-06-26 17:38
> But I wanted to be explicit about mitigation steps for anyone who finds this github issue in the years to come, and whether they should start a new ticket should this issue (with a different root cause) arise again.

@nicholas-signal it’s not a different root cause, it’s a bug in the fix, which has the same root cause, and it will affect everyone who sets the backup at midnight¹. **It will still run twice in 50% of cases** for them. (as shown in @bjo81’s log above)

Let me explain with an example:

1. Signal is configured to run the backup at midnight
2. the previous jitter causes the backup to run on June 27th at 23:57
3. the _new implementation_ computes `next` to be June **27th** at 00:00
4. the _new implementation_ detects that `next` is in the past, and adds 1 day, so it updates it to June 28th at 00:00 (i.e. 3 minutes later)
5. the _new implementation_ adds some jitter – possibly even generating a date-time in the past!
6. the job runs a second (or third, or fourth…) time in a row

The real root cause, which caused the original bug as well, is that the jitter can be negative, giving it the possibility to run before the scheduled time, which makes everything over-complicated (and also seems like unexpected behavior from a user’s perspective).

p.s. as a side note, `BACKUP_JITTER_WINDOW_SECONDS` is defined twice, and the `maxJitterSeconds` parameter of `getNextDailyBackupTimeFromNowWithJitter()` is [not actually used to compute the jitter](https://github.com/signalapp/Signal-Android/blob/93ec322bb9be3a17571eb5c9314f23b2a957738c/app/src/main/java/org/thoughtcrime/securesms/service/MessageBackupListener.kt#L52).

¹ as opposed to what @bjo81 mentioned, I think [the default is 2:00](https://github.com/signalapp/Signal-Android/blob/93ec322bb9be3a17571eb5c9314f23b2a957738c/app/src/main/java/org/thoughtcrime/securesms/keyvalue/SettingsValues.java#L71-L72).

**Comment by bjo81** [comment] 2024-06-26 22:31
Sorry, seems I was wrong then regarding the default.
