### ISSUE TITLE
camera not working when adding a linked device

### ISSUE THREAD

**Issue by aleksandersumowski** [signalapp/Signal-Android#7397] opened 2018-02-05 23:54 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I'm not able to add a linked devide due to the QR code scanning not working.

### Steps to reproduce
- go to Settings -> Linked Devices
- press plus to add a new linked device
- I've tried force stopping the app and restarting to same result

**Actual result:** The preview quandrant to scan the QR code is blank. No error messages appear.
**Expected result:** I should be able to scan QR code.

### Screenshots
![screenshot_20180205-234512](https://user-images.githubusercontent.com/6926/35834809-46987d80-0acf-11e8-85fa-cd12a33c9db6.jpg)

![screenshot_20180205-235127](https://user-images.githubusercontent.com/6926/35834887-9f18534a-0acf-11e8-8efe-ad70896b6592.jpg)

### Device info
**Device:** OnePlus 5
**Android version:** OxygenOs 5.0.3 - 8.0.0 (108, ONEPLUS A5000_23_180129)
**Signal version:** 4.15.5

app has full set of permissions

### Link to debug log
https://gist.github.com/anonymous/f1a8bd06fdbf8ffbd8b2fefa6d0d33ee

**Comment by FeuRenard** [comment] 2018-02-06 11:45
Duplicate of #4843

**Closed** 2018-02-07 02:22 UTC
