### ISSUE TITLE
V 5.46.6 2022-08-17 update on android 4.4.2 signal stops when opened

### ISSUE THREAD

**Issue by LifeDesign-LD** [signalapp/Signal-Android#12412] opened 2022-08-19 12:11 UTC
signal app stops when opened
sometimes you get a choice for clicking "report" or "ok"... but nothing else shows up...
Android 4.4.2
latest signal Version 5.46.6 installed
smartphone restarted a couple of times to get rid of this...
cache deleted several times
google play services cache deleted...

**Comment by indutny-signal** [comment] 2022-08-22 21:54
I've just transfered this issue to Android. cc @greyson-signal

**Comment by greyson-signal** [comment] 2022-08-23 01:18
Closing as a duplicate of #12407

**Closed by greyson-signal** 2022-08-23 01:18 UTC

**Comment by LifeDesign-LD** [comment] 2022-08-23 02:39
@greyson-signal 
@indutny-signal
thanks for helping...
1. I didn't realize this #12412 is desktop-bug-area...
In case of (win7) desktop, my Version is 5.55.0 and it needs to connect to my mobile-app which is down as described.
So desktop-app, is somehow down also...
2. For Android, I'm changing now to new duplicate #12407
