### ISSUE TITLE
"Missed call" log displays wrong time if offline

### ISSUE THREAD

**Issue by cascheberg** [signalapp/Signal-Android#7647] opened 2018-04-05 18:26 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Timestamp of "Missed call" log entries is always received time instead of sent time.
@2-4601 originally filed this as #4197.

### Steps to reproduce
- Turn on airplane mode on device A
- Device B calls A
- Wait some minutes
- Turn off airplane mode
- A receives missed call message

**Actual result:** Message time is "just now"
**Expected result:** Message time should be "5 min" or so

### Screenshots
![signalmissedcallbug](https://user-images.githubusercontent.com/3845150/38384326-2291edf4-390f-11e8-8e47-a37f179d7109.png)

### Device info
**Signal version:** 4.18.1

### Link to debug log
No debug log required, this bug is always reproducible

**Comment by Xashyar** [comment] 2019-03-07 10:28
Same issue on 4.35.2

possibly related: #7733 #8072 #8302

**Comment by mattimac** [comment] 2019-03-22 00:34
Duplicate of at least #7733  please tidy up this issue

**Closed** 2020-09-23 21:10 UTC
