### ISSUE TITLE
Telco number unreachable after Signal call

### ISSUE THREAD

**Issue by kmm2** [signalapp/Signal-Android#4703] opened 2015-11-24 04:15 UTC
After a Signal call my normal phone number was unreachable from cell/landline phones as if it was turned off. At the same time, strangely, incoming SMS (non-Signal) would go through but with extremely low notification. On top of it I also experienced all the other issues mentioned in https://github.com/WhisperSystems/Signal-Android/issues/4548 and https://github.com/WhisperSystems/Signal-Android/pull/4567 .

While you work on these bugs can you please add to the next version 2 options:
- selectable Signal start with system
- "Exit" menu item for full Signal app shutdown

As Signal may block incoming telco calls I have to either uninstall it completely or get full control of its activities to continue further testing.

I use Signal v3.4.2 on Samsung Galaxy S5 with Android 4.4.2, a friend with Signal v3.4.2 called me on Motorola Moto 2 Android 5.1. He also experienced issues #4548 and #4567 and had to uninstall Signal. At this stage I can not recommend Signal to anyone so I will test it on my own Android devices. I am happy to report that it almost works on tablets already. I installed and registered it on Nexus 7-2013 Android 6 using a landline number voice code. Secure text works both ways, Nexus also accepts incoming calls but is unable to initiate a Signal call due to "missing device capabilities". If you could remove this artificial obstacle in calling from tablets, it would be fantastic.

And thank you for Signal.

**Comment by moxie0** [comment] 2015-11-24 05:05
Sounds like a ROM issue.  There is no way to do that from an app, even if we wanted to.

**Comment by kmm2** [comment] 2015-11-24 08:48
If an app can not block incoming telco call then why do you attempt to **deny incoming PSTN call**...

    Log.d(TAG, "Attempting to deny incoming PSTN call.");
    TelephonyManager tm = (TelephonyManager)context.getSystemService(Context.TELEPHONY_SERVICE);
    try {
      Method getTelephony = tm.getClass().getDeclaredMethod("getITelephony");
      getTelephony.setAccessible(true);
      Object telephonyService = getTelephony.invoke(tm);
      Method endCall = telephonyService.getClass().getDeclaredMethod("endCall");
      endCall.invoke(telephonyService);
      Log.d(TAG, "Denied Incoming Call From: " + intent.getStringExtra(TelephonyManager.EXTRA_INCOMING_NUMBER));

As for the ROM, it is an unrooted original Samsung version with no competing call control nor other voip apps. In fact apart from a few ROM services which I was unable to disable, only Signal was running. I noticed the problems after a barely audible SMS, then I tried repeatedly to call my cell phone from a PSTN phone but all calls were immediately disconnected. It does sound like **"deny incoming PSTN call"** doesn't it? So, as there is no "Exit" option in Signal, I went to app manager and did "Force stop" on Signal, and immediately my next call went through.

Please reopen the issue, this is a serious bug.

**Comment by 2-4601** [comment] 2015-11-24 14:50
Cannot reproduce with Nexus 4, stock 5.1.1, Signal 3.5.1.

However there was a similar sounding issue with RedPhone. If the setting to automatically upgrade regular calls to RedPhone calls was enabled the phone became unreachable through PSTN.

**Comment by kmm2** [comment] 2015-11-26 21:22
Can you confirm that #4703 is in your opinion a ROM issue and it stays closed?

**Comment by 2-4601** [comment] 2015-11-27 01:21
I don't know.

Like I said in my previous comment there was a similar sounding bug with RedPhone. I confirmed it with 4 different devices. Two of which were Nexus 4 with stock ROMs. There were also multiple people reporting the bug on the issue tracker. But RedPhone was already getting less and less love at that point (late 2014) so it was never addressed. 

With that said I cannot reproduce the bug with Signal. Actually when I'm in a Signal call and a PSTN call comes in the PSTN call gets through and happens on top of the Signal call :) Don't know if this is expected. If I recall correctly this did not happen with RedPhone.

Now that I looked at [the file](https://github.com/WhisperSystems/Signal-Android/blob/84fa2d1a34c7d74efc3eab1599e03c036ab50b2f/src/org/thoughtcrime/redphone/pstn/IncomingPstnCallListener.java#L13) you quoted code from it has a comment:
`Listens for incoming PSTN calls and rejects them if a RedPhone call is already in progress.`
So I guess this is not expected behavior.

Perhaps moxie meant in his comment that it's not possible for an app to deny PSTN calls when the app is not using VoIP (or similar) features. But is it possible that Android (or some ROMs) have a bug where the state of rejecting calls gets stuck and is never released? This would explain the RedPhone bug and maybe also your issue.

What do you see in system logs when the bug happens (i.e. PSTN call gets rejected)?

**Comment by kmm2** [comment] 2015-11-28 01:10
*Perhaps moxie meant in his comment that it's not possible for an app to deny PSTN calls when the app is not using VoIP (or similar) features*

I hope to hear from him. I reported that the problem happened after a voip Signal call and the context is crystal clear.

*is it possible that Android (or some ROMs) have a bug where the state of rejecting calls gets stuck and is never released?*

No, because we would have heard about it by now from millions of frustrated users of Android voip apps like Skype, Viber, etc. However all sorts of problems are possible when an unsupported API is used, note

[The com.android.internal.telephony is not part of the Android SDK... Since this is an "unsupported API" it may not work on all devices and it may be changed in a future release of Android](http://stackoverflow.com/questions/24580223/)

And ITelephony, **the unsupported API**, is exactly what Signal relies on. Why don't you have a look at source code of [csipsimple](https://code.google.com/p/csipsimple/source/checkout) which makes Android voip possible without shaky API calls. I used csipsimple for over a year on my old Android phone without any problems.

*What do you see in system logs when the bug happens (i.e. PSTN call gets rejected)?*

The Signal log is gone. My phone is not rooted and I can not access system logs. Since my friend uninstalled Signal I can not test it right now. I will try to install it on another phone.

Again, please include these options:
- optional Signal start with system
- "Exit" menu item for full Signal app shutdown

**Comment by 2-4601** [comment] 2015-11-28 02:43
It is not likely that the options you are suggesting will be included. See: https://github.com/WhisperSystems/Signal-Android/blob/master/contributing.md#development-ideology

To fix your issue it will help tremendously if you can consistently reproduce it with logs. 

AFAIK you don't need root to get system logs. You need the `adb` binary from the Android SDK and then run `adb logcat`. And Signal also can capture logs from **Settings -> Advanced -> Submit debug log** (though if I understood correctly you might already be aware of this... mentioning just in case).

**Comment by kmm2** [comment] 2015-11-28 05:04
*It is not likely that the options you are suggesting will be included. See... development-ideology*

Yes it is a great ideology for a finished product. Signal is not there yet, it is buggy and more options are needed for testing. Add them to the advanced menu.

My logcat holds data for the last 2 days only. The issue happened 4 days ago. No, you can't do "adb shell dmesg" on unrooted phone 
>klogctl: Operation not permitted

**Comment by haffenloher** [comment] 2016-03-29 00:52
This happened to me yesterday on Android 4.2. All incoming calls were being denied automatically (one time the call vibration started for a fraction of a second before the call was denied).
As soon as I stopped Signal's RedPhoneService through Android's "Manage apps" functionality, calls went through again. I forgot to capture a log though :confounded:

**Comment by khers** [comment] 2016-11-03 20:54
This is happening to me on a Nexus 6p with Android 7.0 using a stock image.  I can receive calls from other contacts, but the one with whom I had a Signal call cannot get through on Signal or PSTN.  Next time it happens I will take system logs.

**Comment by bbben123** [comment] 2016-11-19 12:06
It happened to me on a Pixel with 7.1, Signal suggested I share this here.

https://gist.github.com/3407d133f6b41c62ecc6751e5c74f006

**Comment by redbaron-gt** [comment] 2017-01-15 09:46
It happens to me on OnePlus3 with Android 7.0. Sharing log here
https://gist.github.com/anonymous/bdfd8819767b759240efaedb5b9a0697

**Comment by automated-signal** [comment] 2018-04-02 23:04
GitHub Issue Cleanup:
See #7598 for more information.

**Closed** 2018-04-02 23:04 UTC
Labels: redphone, webrtc
