### ISSUE TITLE
Error sharing photo directly to Signal when it's locked

### ISSUE THREAD

**Issue by Edu4rdSHL** [signalapp/Signal-Android#8955] opened 2019-07-26 19:35 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal crashes when you try to share a photo directly from the browser while Signal is locked, when it's unlocked, the app crashes and you back to the browser, then you have to share the photo again and it works.

### Steps to reproduce
- Search a photo in the browser.
- Share it directly pressing in the image and "share with signal" while it's locked.
- Unlock the Signal app.

**Actual result:** Signal crashes and you are send back to the browser screen.
**Expected result:** Signal show you the contacts to choose with who share the photo.

### Screenshots

Not needed.

### Device info

**Device:** Samsung Galaxy A70  SM-A705MN
**Android version:** 9
**Signal version:** 4.44.4

### Link to debug log

https://debuglogs.org/dcb8f566e4612016e08df2820fb3cf011bb7a3ece5cf0056c3f897d820819b11

I found it interesting:

```
07-26 14:19:00.174 19021 23291 W SingleRecipientNotificationBuilder: java.util.concurrent.ExecutionException: com.bumptech.glide.load.engine.GlideException: Failed to load resource
```

**Comment by greyson-signal** [comment] 2020-12-04 15:59
Closing as duplicate of #8528

**Closed** 2020-12-04 16:22 UTC
