### ISSUE TITLE
Proxy UI reports successful connections to non-existent domains

### ISSUE THREAD

**Issue by JusticeRage** [signalapp/Signal-Android#12469] opened 2022-09-23 02:38 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
In normal circumstances, the proxy UI reports being able to connect to non-existent domains.

### Steps to reproduce
- Reboot phone
- Connect to a proxy via a signal.tube link
- Manually change the proxy URL to something random

**Actual result:** The UI reports being able to connect to the domain, even though it doesn't exist. All subsequent attempts to connect to actual proxies fail.
**Expected result:** Not pretending that connection to non-existent domains is possible.

### Screenshots
![](https://pbs.twimg.com/media/FdThGrPWIAEELDI?format=jpg)

### Device info

**Device:** Pixel 4a
**Android version:** 13, September 05 patch.
**Signal version:** latest

EDIT: For the record, I have also encountered cases where the UI reports the connection to the proxy as failed, while messages still manage to go through (in a network where chat.signal.org is blocked). And I am frequently unable to add legitimate and confirmed working proxies manually through the settings, although I'm not sure how to reproduce the issue exactly.

**Comment by derekmorr** [comment] 2022-09-23 12:46
@alphamichael I can't reproduce that. I am on a network where signal.org is not blocked, and my phone uses the proxy when I configure it.

**Comment by JusticeRage** [comment] 2022-09-24 09:28
Several users have reported being unable to connect to functioning proxies. I've experienced the issue myself, especially when switching from a proxy to another.

Considering the PR activity around #IRanASignalProxy, this feels like a high priority issue.

**Comment by derekmorr** [comment] 2022-09-24 14:37
There is a related issue that when you enter a new proxy, the app doesn't switch to it immediately. You have to force quit the app to make it connect. Yesterday there was a commit to fix that - https://github.com/signalapp/Signal-Android/commit/87f206fdc4f6bcbd0087e2a37ffe27f32128e644.

**Comment by Sgn-32** [comment] 2022-10-14 14:04
Fixed in 5.50.4
Ensure websockets are restarted after changing proxy.  https://github.com/signalapp/Signal-Android/commit/87f206fdc4f6bcbd0087e2a37ffe27f32128e644

**Closed** 2022-10-14 14:39 UTC
