### ISSUE TITLE
Blocking Email Crashes Signal

### ISSUE THREAD

**Issue by Amark18** [signalapp/Signal-Android#10857] opened 2021-01-30 03:36 UTC
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I get spam messages from emails and when I try to block these emails, the signal app crashes. 

### Steps to reproduce
- Select sender (which is not a phone number but an email)
- Press the menu and select conversation settings
- Select block (**APP CRASHES**)

**Actual result:** App crashes and is restarted. The sender is not blocked.
**Expected result:** The sender is blocked.

### Device info
**Device:** Oneplus 6T
**Android version:** 10 ___ Oxygen OS 10.3.7
**Signal version:** 5.3.7

**Comment by Genis-Sage** [comment] 2021-01-31 14:33
Hey @Amark18
this is a duplicate of  #9923

**Closed** 2021-01-31 18:13 UTC
