### ISSUE TITLE
Signal wont send any attachment from any mobile!

### ISSUE THREAD

**Issue by mmBesar** [signalapp/Signal-Android#10070] opened 2020-10-09 15:44 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal won't send any attachment from any mobile, from desktop working fine.
I can't send any attachments neither my friend, whom are just using Signal to contact me!

### Steps to reproduce
- send any picture

**Actual result:** keep on loading for ever!
**Expected result:** send the picture

### Device info

**Device:** Motorola G5
**Android version:** 10
**Signal version:** 4.72.5

**Comment by Nisc3d** [comment] 2020-10-09 16:03
Can you please send a debug log?

**Comment by greyson-signal** [comment] 2020-10-15 15:03
Closing as a duplicate of #10061

**Closed by greyson-signal** 2020-10-15 15:03 UTC

**Comment by mmBesar** [comment] 2020-10-21 15:46
[This](https://github.com/signalapp/Signal-Android/issues/10061#issuecomment-713670880) Important
