### ISSUE TITLE
Add Xiaomi Mi A2 to echo cancellation blacklist

### ISSUE THREAD

**Issue by JoaquimCSantos** [signalapp/Signal-Android#10215] opened 2020-11-20 20:44 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
On loudspeaker in the Xiaomi Mi A2 and A3, there is no echo cancellation.

### Steps to reproduce
- Call someone and put it on loudspeaker

**Actual result:** 
- The person on the other side will hear themselves speak, their echo.

**Expected result:**
- The person on the other side of the call should not hear themselves speaking, their echo.

### Device info

**Device:** Xiaomi Mi A2
**Android version: 10 
**Signal version:** 4.77.3

**Comment by leezu** [comment] 2021-01-17 10:19
I have confirmed this issue on calls with Xiaomi A2

**Comment by newuser-web** [comment] 2021-01-18 02:34
This issue is on calls with xiaomi A1 also. Even with headphones voice is echoing.

**Comment by newuser-web** [comment] 2021-01-18 02:52
This issue is on calls with xiaomi A1 also.

**Comment by Hyper-B0T** [comment] 2021-01-29 01:17
Still an issue on Mi a3

**Comment by UserX404** [comment] 2021-01-29 19:04
Seems to be already added (A1 & A2).
https://github.com/signalapp/Signal-Android/blob/29d6d3c041d857bfc5f94b4631f2f7587f599c06/app/src/main/java/org/thoughtcrime/securesms/ApplicationContext.java#L307

Can you check your debug logs what is listed for `Model`.
If it's not misspelled it should be excluded.

[if (HARDWARE_AEC_BLACKLIST.contains(Build.MODEL)) {
    WebRtcAudioUtils.setWebRtcBasedAcousticEchoCanceler(true);
}](https://github.com/signalapp/Signal-Android/blob/29d6d3c041d857bfc5f94b4631f2f7587f599c06/app/src/main/java/org/thoughtcrime/securesms/ApplicationContext.java#L319)

**Comment by newuser-web** [comment] 2021-01-30 02:30
Debug log is attached in issue 10768.

**Comment by newuser-web** [comment] 2021-01-30 02:49
Model: Mi A1
#10768

**Comment by JoaquimCSantos** [comment] 2021-02-03 19:06
Yes, I have checked the code. But the problem still happens.

**Comment by miguelcoelhosantos** [comment] 2021-02-04 09:42
Please note there was no echo before https://github.com/signalapp/Signal-Android/issues/7635 (at least). **It used to work perfectly fine when I first bought my phone.** It worked fine with A1, and A2...then it broke...

After 7635 was solved it was never fixed back.

There have been several issues raised (https://github.com/signalapp/Signal-Android/pull/7956, https://github.com/signalapp/Signal-Android/issues/7635, https://github.com/signalapp/Signal-Android/issues/10215) but in fact this hasn't fixed the problem.

**Comment by jimio-signal** [comment] 2022-01-28 05:08
ahoy there! we made some improvements to the echo-cancellation logic in our android 5.29 release. I’m running through some old AEC issues and resolving them now; please try out the latest release and holler if you have any issues :)

https://github.com/signalapp/Signal-Android/commit/47134e19f18fe7f6e611b7c228520e5d5c0791f5

**Closed by jimio-signal** 2022-01-28 05:08 UTC
Labels: wontfix

**Comment by maymage** [comment] 2022-05-15 07:04
@jimio-signal 

Hi, just to give feedback: echo is back on my Mi A2 - has been for several weeks now. Best
