### ISSUE TITLE
Signal icon in Users & accounts menu section is distorted

### ISSUE THREAD

**Issue by bungabunga** [signalapp/Signal-Android#7908] opened 2018-06-19 06:46 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal icon in Menu / Users & accounts is distorted since version 4.21.0

### Screenshots
![img_eggsif_3831034301093464465xy](https://user-images.githubusercontent.com/2994878/41581426-b18bf508-739e-11e8-9f11-9f2fe7c1acb4.jpg)

### Device info
**Device:** Sony Xperia XZ
**Android version:** 8.0.0
**Signal version:** 4.21.2

**Comment by signal-ogennadi** [comment] 2018-06-20 19:46
I see the same behaviour using the Android Virtual Device

**Device info**
Device: Nexus 5X API 28 (emulated)
Signal version: 4.21.3

![screenshot_1529523715](https://user-images.githubusercontent.com/40372290/41680822-5b5b4a76-7498-11e8-8415-903d7e485398.png)

**Comment by igor2x** [comment] 2018-06-24 07:58
I can confirm this problem on
**Device:** LG Nexus 5x
**Android version:** 8.1.0
**Signal version:** 4.21.6

![signal_icon](https://user-images.githubusercontent.com/10895030/41817117-e1a182cc-7794-11e8-8d1d-1375bc34bd2d.png)

**Comment by billie80** [comment] 2018-06-24 16:47
On Android 6 the icon is replaced with the standard icon.

![icon](https://user-images.githubusercontent.com/9938306/41821295-a0a0d09e-77de-11e8-85a5-d56f10f7f69b.png)

Device: Samsung Galaxy S5 mini
Android version: 6.01
Signal version: 4.21.6

**Comment by cascheberg** [comment] 2018-06-24 19:03
> On Android 6 the icon is replaced with the standard icon.

Same on Android 7.1.1, Moto G5S

**Comment by greyson-signal** [comment] 2018-06-29 21:09
Yeah hmm, I wonder if this is some consequence of switching to an adaptive icon. I don't know why things would change on Android < 8 though. But I see the same stock icon on my Android 5.1 device. I can also confirm that the "Accounts" icon is screwed up on my Android P device. 

I'll look into it. Just weird because obviously the app icon that appears on the launcher is fine :/

**Comment by cascheberg** [comment] 2018-06-29 21:28
@greyson-signal Did you notice that there is an open pull requests that supposedly fixes this issue? I did not test it, but it looks simple and reasonable.

**Comment by greyson-signal** [comment] 2018-06-29 21:34
@cascheberg Ah, thank you for pointing that out! I'll test it and merge it in if it's good :)

**Comment by greyson-signal** [comment] 2018-06-29 21:42
Fixed by #7946 and merged into the 4.23 branch.

**Closed by greyson-signal** 2018-06-29 21:42 UTC
Labels: ux
