### ISSUE TITLE
Screen lock requires Force Stop to function > Settings > Privacy > Screen lock

### ISSUE THREAD

**Issue by jamesjahraus** [signalapp/Signal-Android#9182] opened 2019-11-13 00:46 UTC
----------------------------------------

- [x] I have searched open and closed issues for duplicates
Connected but not duplicate:
https://github.com/signalapp/Signal-Android/issues/8603
https://github.com/signalapp/Signal-Android/issues/7962
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After setting Settings > Privacy > Screen lock to on, I expect that every time I click "square" and "X" the app will close and then the screen will lock for signal. So far to get the screen lock to function I need to reboot my phone, or use force stop. I expect this behaviour from experience with Microsoft Authenticator, and Authy. In both of these apps clicking "square" then "X" will close the app, so next time I open I need to use the screen lock function.

**Note:** I didn't use the "Screen lock inactivity timeout" feature, because it only seems to set to 00:01:00 no mater what I put for time, and I don't "really" understand what the feature means or does, so I have it set to none. I tried 20s as a quick test and the lock still didn't function as I expected, so this bug is under the condition of screen lock: ON, time out: none.
 
### Steps to reproduce
- first install of signal
- sent signal to contacts
- set signal to use SMS
- Settings > Privacy > Screen lock
- Screen lock inactivity timeout: none
- clicked "square" then "X" to close signal app
- opened signal expecting screen lock (similar to authy), but signal just opened
- rebooted phone
- screen lock worked as expected
- clicked "square" then "X" to close signal app
- opened signal expecting screen lock (similar to authy), but signal just opened
- android app setting "Force Stop" on Signal app
- screen lock worked as expected

**Actual result:** 
- clicked "square" then "X" to close signal app
- opened signal expecting screen lock (similar to authy), but signal just opened

**Expected result:**
- click "square" then "X" to close signal app
- open signal, and screen lock is required (similar to authy)

### Device info
**Device:** motorola Moto G (4) (athene)
**Android:** 7.0 (6, NPJS25.93-14.7-8)
**App:** Signal 4.49.18 (5651)

### Link to debug log
I didn't want to use this, because I am not familiar what information is in the logs, and they are very lengthy to read the whole thing to find out.

**Comment by greyson-signal** [comment] 2019-11-15 16:22
This is currently working as intended.

By default, the screenlock is something you have to trigger via the notification. You can also set a timeout to automatically lock the app after a certain time. You closing the app in the recents menu doesn't impact when we lock the screen.

If you'd like to discuss the way the feature works, you can check out [the forum](https://community.signalusers.org/). Thanks!

**Closed by greyson-signal** 2019-11-15 16:22 UTC
