### ISSUE TITLE
Arbitrary string in sent message geo linkifys

### ISSUE THREAD

**Issue by burntcookie90** [signalapp/Signal-Android#7730] opened 2018-04-24 22:07 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

Type "one and find a corner in" on Android and it linkifys to `geo:0,0?q=one+and+find+a+corner+in`

### Steps to reproduce
- type "one and find a corner in"
- it linkifys

**Actual result:** Erroneously linkifys text
**Expected result:** shouldn't linkify

### Screenshots

![image](https://user-images.githubusercontent.com/1452613/39216648-8e8d778c-47ea-11e8-8bd7-e4c2c202c7f5.png)

### Device info
**Device:** Google Pixel 2XL
**Android version:** 8.1.0
**Signal version:** 4.19.1

**Comment by porjo** [comment] 2018-05-01 17:55
I can confirm this. I wrote 'Hi Bob, I've gone for a run The phone is charging in Pete's office.' and it linkified 'one for a run The phone is charging in'

**Comment by greyson-signal** [comment] 2018-05-01 18:03
Yeah, I'm nearly-certain it's because the parser thinks that "in" is an abbreviation for "Indiana". The original bug string "one and find a corner in" also gets mis-identified as an address if you type "one and find a corner pa" and "one and find a corner md". Kinda funny, but also annoying :)

We're using the built-in system address linkifier, so our options are to tweak how we're using it, find a different one, or stop linkifying addresses altogether. I think address links are too valuable to get rid of, so I'm focusing on the first two.

**Comment by burntcookie90** [comment] 2018-05-01 18:14
Is linkifying map addresses super useful when it only works in the US (from the [docs](https://developer.android.com/reference/android/webkit/WebView#findaddress))? 

I think the two options could be amended to:

1. file a bug against framework, have the fix come through in` LinkifyCompat` so that it's backported
1. Disable linkifying, since it only works in the US.

**Comment by RockyTV** [comment] 2018-06-20 23:44
This still happens. My friend was complaining about Signal leaking his location in chat messages, then he sent me a screenshot of it happening. I sent him the same text, which was `anyone can run regardless of party opinion (as it happens in Brazil's`. The geo link that I copied contained the phrase that was mentioned.

**Comment by greyson-signal** [comment] 2018-08-13 19:27
Will be fixed in 4.25 (by way of removal).

**Closed by greyson-signal** 2018-08-13 19:27 UTC

**Comment by greyson-signal** [comment] 2018-08-13 19:29
As a follow-up, it looks like there's an API 28+ approach for linkifying addresses, as hinted at in the docs for [Linkify#MAP_ADDRESSES](https://developer.android.com/reference/android/text/util/Linkify.html#MAP_ADDRESSES). Would probably be a good candidate for a PR if anyone is interested :)

**Comment by RockyTV** [comment] 2018-08-13 20:54
Why not use the approach that other chat apps use, such as WhatsApp? I don't recall having the same issue in it. And a FYI: I got the same issue on Discord app for Android.

**Comment by greyson-signal** [comment] 2018-08-13 21:10
@RockyTV Best I can see, WhatsApp does not automatically linkify addresses that you type out yourself. As I mentioned, there's a platform solution for linkifying addresses more accurately, but it's API 28+.
