### ISSUE TITLE
Gallery not loading images or videos

### ISSUE THREAD

**Issue by BOB74j** [signalapp/Signal-Android#12334] opened 2022-07-06 15:27 UTC
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Most images and videos fail to load in gallery view, instead appearing as empty black images. These items cannot be attached to messages. Other apps display the affected media items correctly. Signal, however, does not.

The affected media items may still be attached as files but not as images or videos. Sometimes removing all EXIF metadata from an image allows previews to be shown, but this should not be considered a permanent fix.

[Example EXIF from an affected 3.21MB photo](https://pastebin.com/ZAGETQhG)

### Steps to reproduce
- Save photo to phone's internal memory via camera, screenshot, or download
- Open any message thread in Signal app
- Click the plus button to attach an item to a new message
- Press gallery button
- Open a folder within gallery view

**Actual result:** Images and videos show up as blank black images in gallery preview. Folder previews may sometimes (seemingly at random) be shown correctly in full gallery view. Upon opening a folder, most thumbnails are again blank and cannot be attached to a message.
**Expected result:** Valid images and videos should show appropriate thumbnail previews in all gallery views regardless of EXIF tags. Additionally, these images should be able to be attached to Signal messages.

### Screenshots
![unnamed](https://user-images.githubusercontent.com/43751378/177589192-baca6e0e-ce23-4931-a282-cc0a6536eac2.jpg)

### Device info
**Device:** Moto G5 Plus
**Android version:** 10
**Signal version:** 5.41.13

### Link to debug log
https://debuglogs.org/android/5.41.13/0f5bfb558b157e06f33302c5266bf7b09a589fce8e160c7a4086ccf0d99ac329

**Comment by greyson-signal** [comment] 2022-07-06 23:31
Closing as a duplicate of #11014

**Closed by greyson-signal** 2022-07-06 23:31 UTC
