### ISSUE TITLE
Closing Signal opens and minimises Phone app

### ISSUE THREAD

**Issue by bobloblawatlaw** [signalapp/Signal-Android#7977] opened 2018-07-10 14:34 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

ISSUE : Upon closing Signal, around 80% of the time this results in Phone app opening then immediately minimising itself.

STEPS : This bug never occurs on first few occasions after device start. After several closures of Signal, Phone app will then consistently open and minimise for rest of day.

ACTUAL : Phone app opening and minimising upon closure of Signal.

EXPECTED : Signal should close without other apps opening.

SCREENSHOTS : N/A

DEVICE : Blackberry Keyone Black BBB100-2
ANDROID : 7.1.1
SIGNAL : 4.23.4

DEBUG : https://debuglogs.org/1b21c29d346ffc81bbe0da27ccaa33cded34ba7e00eb32b2c508a37b29681d9e

**Comment by moxie0** [comment] 2018-07-10 16:50
I'm unable to reproduce this, in part because android has no concept of apps being "closed," "open," or "minimized." This sounds like some kind of Blackberry thing.

I'm going to close this since I don't think there's any action we can take, but please reopen if this behavior isn't a result of the platform.

**Closed by moxie0** 2018-07-10 16:50 UTC

**Comment by bobloblawatlaw** [comment] 2018-07-10 17:48
I've put up with this issue for several months. I asked for help on the Crackberry forums and was treated very dismissively and told it was a "Signal" issue. As none of the other 100+ apps on my phone cause this problem, I tend to agree.
I've come here and followed your guidelines to try and get help but have received similarly condescending non-help from you. Well done on the customer service front. 
I have around a dozen friends who are only using Signal because of me. I'll be sure to tell them of this experience.
