### ISSUE TITLE
Sent picture got stuck at 5% and now I can't write anything after it

### ISSUE THREAD

**Issue by Dyras** [signalapp/Signal-Android#8542] opened 2019-01-19 15:53 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I was at Dollar Store, I found a funny product, I took a picture of it and I tried to send it with a message to a friend. The picture reaches 5% and then it's stuck. I try to send two more messages and they just refuse to send. I start to suspect my phone internet is dead, so I go outside and connect to McDonald's WiFi. Internet works flawlessly. I disconnect from McDonald's and I try my mobile data. Internet works flawlessly.

Now I'm at home on my WiFi and it's still not sending. I'm 99% sure a reboot of the phone will fix the issue, but this is still annoying and IMO it shouldn't happen at all.

### Steps to reproduce
1. Send a picture
2. Have your mobile data temporarily die for a couple of seconds
3. The image gets stuck, no matter how long I wait the image never officially "fails"
4. Nothing can be sent after it

**Actual result:** Images can get stuck indefinitely
**Expected result:** Images automatically fail after a certain amount of time. Or even better, an image failing to send doesn't render the entire app useless until you restart the app/phone.

### Device info
Pixel XL
Latest stock software. January update of 9.0, I believe.
Latest beta

### Link to debug log
https://debuglogs.org/8c9da0457f748e7c201a716b1d74051826282a2a524bcdf2a7dfcbd760db512a
The image in question was sent right after message 1547909922712

**Comment by greyson-signal** [comment] 2019-01-22 00:40
Marking as a duplicate of #8536. You can look there for more background. Thanks!

**Closed by greyson-signal** 2019-01-22 00:40 UTC
