### ISSUE TITLE
HTC bug - "System UI has stopped unexpectedly. Would you like to tell HTC?"

### ISSUE THREAD

**Issue by krasnoj** [signalapp/Signal-Android#2550] opened 2015-03-01 22:08 UTC
Hi!
Cell phone Android 4.0.3, HTC Rhyme
When I start TextSecure the System first crashes with "Default Lock Screen" and then with SystemUI closes unexpectedly (German: "SystemUI wurde unerwarted beendet"). Then the header line including the clock disappears and the SystemUI is started again with the clock. 
This happens every time I start TextSecure. I already tried to reinstall and reflash the cell phone. But the problem still occurs.
If you need any additional information, just tell me what you need.

Cheers.

**Comment by mcginty** [comment] 2015-03-02 19:23
@krasnoj please include a debug log

**Comment by krasnoj** [comment] 2015-03-02 23:18
The build in log functionality is attached to https://gist.github.com/anonymous/024d4c3efd302572cbc8

But there is nothing usefull in this logfile. And yes I posted the whole logfile (using the   and TextSecure was open while the SystemUI crashed.

I posted under <http://debianforum.de/forum/pastebin.php?mode=view&s=38354> a larger logfile made with a third party app. The log file should be complete. Just the entries with "WifiStateMachine" have been filtered by me.

**Comment by moxie0** [comment] 2015-03-03 17:01
looks like a ROM bug

On 03/02/2015 03:18 PM, krasnoj wrote:
> The build in log functionality is attached to
> https://gist.github.com/anonymous/024d4c3efd302572cbc8
> 
> But there is nothing usefull in this logfile. And yes I posted the whole
> logfile (using the and TextSecure was open while the SystemUI crashed.
> 
> I posted under
> http://debianforum.de/forum/pastebin.php?mode=view&s=38354 a larger
> logfile made with a third party app. The log file should be complete.
> Just the entries with "WifiStateMachine" have been filtered by me.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/TextSecure/issues/2550#issuecomment-76848979>.
> 

-- 
http://www.thoughtcrime.org

**Comment by rhodey** [comment] 2015-03-13 18:47
I'm unable to reproduce this and agree that this seems like a ROM bug. If you're running into this issue on a very popular non-stock Android ROM then it might be worth looking into a fix but in general we want to remain focused on compatibility with stock Android.

**Comment by krasnoj** [comment] 2015-03-13 19:01
Hi!

I just want to mention that the Bug occurs with the official upgrade for the HTC Rhyme cell phone. So there is no third party software involved.

Steps I did:
Take HTC Rhyme, upgrade to newest original firmware, activate encryption, install TextSecure.

If TextSecure works on any other HTC with encryption enable I agree with closing the bug. In this case I think HTC broke my firmware, but if the problem occurs on all HTC the situation would be different.

**Comment by rhodey** [comment] 2015-03-14 00:06
thanks for the update @krasnoj, I'll reopen this but still don't have much of an idea how to resolve 0.o

**Comment by beanhr** [comment] 2015-03-14 19:23
I have the exact same problem on HTC EVO3D stock firmware 4.0.3. Also tried reinstalling but same thing happens while everything else works fine.

**Comment by swltr** [comment] 2015-03-29 08:03
Same problem here on a HTC Incredible S, unmodified firmware (Android 4.0.4, HTC Sense 3.6).

I've been using TextSecure for quite a while now, and I definitely did not see this in older versions of TextSecure. Maybe for the last six months. Unfortunately, I cannot remember with which version it started.

**Comment by McLoo** [comment] 2015-03-29 08:36
@swltr could you post a debug log? 
After the crash from the TS lock screen menu or advanced menu, when you don't use  a passphrase

**Comment by swltr** [comment] 2015-03-29 09:16
@McLoo Here's a log: https://gist.github.com/anonymous/5457b6f2a0c8bedef8a1

Until now, I noticed these crashes only occasionally when receiving and/or opening messages. Now I also caused a crash of "System UI" by selecting the debug log item in the advanced settings menu, and it seems like I can reproducibly make it crash when pushing the lock button the notifications list to make TextSecure forget the passphrase.

Please note that TextSecure itself does not crash - it keeps running. It's only "System UI" and sometimes "Default lock screen" that seems to be crashed by some interaction with TextSecure.

**Comment by rhodey** [comment] 2015-04-21 01:17
TestObject has both the HTC Rhyme and Evo 3D, self-assigning this with the intent of at least getting some more debug logs and identifying cause of the error.

**Comment by rhodey** [comment] 2015-04-23 04:29
test run on unmodified debug build of 27a5b7dd5c588abd677b6947c896df410d67a0f2, using an HTC EVO 3D from testobject.com.

![htc evo 3d crash](http://i.imgur.com/TfyIAh1.png)

debug log: https://gist.github.com/rhodey/c5b2d82d768dd5f1bad2

this crash occurred without any user interaction, the app was installed by testobject's processes and then opened automatically, and then the crash occurs immediately. debug log should contain everything from boot to crash and after.

**Comment by rhodey** [comment] 2015-04-23 07:06
@krasnoj, @beanhr a search for [htc evo 3d system ui has stopped unexpectedly](https://www.google.com/search?q=htc+evo+3d+system+ui+has+stopped+unexpectedly) returns a bunch of results, many claiming that uninstalling updates to the Facebook app or "Face Lock" solve the problem. Could you please try this out and let us know if installing TextSecure still results in a crash? I'm unable to test that case through any of these online test suites.

relevant parts of the debug log...
```
2015-04-22 23:20:09.485	ERROR:	AndroidRuntime_2_crash : crash in the same process: Thread-944
2015-04-22 23:20:09.485	ERROR:	AndroidRuntime_2_crash : java.lang.NullPointerException
2015-04-22 23:20:09.485	ERROR:	AndroidRuntime_2_crash : at com.android.systemui.statusbar.phone.UpdateShortcutReceiver$1.run(UpdateShortcutReceiver.java:75)
2015-04-22 23:20:09.485	ERROR:	AndroidRuntime : FATAL EXCEPTION: Thread-943
2015-04-22 23:20:09.485	ERROR:	AndroidRuntime : java.lang.NullPointerException
2015-04-22 23:20:09.485	ERROR:	AndroidRuntime : at com.android.systemui.statusbar.phone.UpdateShortcutReceiver$1.run(UpdateShortcutReceiver.java:75)
2015-04-22 23:20:09.505	ERROR:	EmbeddedLogger : App crashed! Process: com.android.systemui
2015-04-22 23:20:09.505	ERROR:	EmbeddedLogger : App crashed! Package: com.android.systemui v15 (4.0.3-eng..20130207.130217)
```

```
2015-04-22 23:20:11.477	DEBUG:	AndroidRuntime : Shutting down VM
2015-04-22 23:20:11.507	WARN:	dalvikvm : threadid=1: thread exiting with uncaught exception (group=0x40ab6228)
2015-04-22 23:20:11.617	ERROR:	AndroidRuntime : FATAL EXCEPTION: main
2015-04-22 23:20:11.617	ERROR:	AndroidRuntime : java.lang.RuntimeException: Unable to start receiver com.htc.idlescreen.base.setting.UpdateShortcutReceiver: java.lang.NullPointerException
2015-04-22 23:20:11.617	ERROR:	AndroidRuntime : at android.app.ActivityThread.handleReceiver(ActivityThread.java:2408)
2015-04-22 23:20:11.617	ERROR:	AndroidRuntime : at android.app.ActivityThread.access$1500(ActivityThread.java:139)
2015-04-22 23:20:11.617	ERROR:	AndroidRuntime : at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
2015-04-22 23:20:11.617	ERROR:	AndroidRuntime : at android.os.Handler.dispatchMessage(Handler.java:99)
2015-04-22 23:20:11.617	ERROR:	AndroidRuntime : at android.os.Looper.loop(Looper.java:154)
2015-04-22 23:20:11.617	ERROR:	AndroidRuntime : at android.app.ActivityThread.main(ActivityThread.java:4945)
2015-04-22 23:20:11.617	ERROR:	AndroidRuntime : at java.lang.reflect.Method.invokeNative(Native Method)
2015-04-22 23:20:11.617	ERROR:	AndroidRuntime : at java.lang.reflect.Method.invoke(Method.java:511)
2015-04-22 23:20:11.617	ERROR:	AndroidRuntime : at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
2015-04-22 23:20:11.617	ERROR:	AndroidRuntime : at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
2015-04-22 23:20:11.617	ERROR:	AndroidRuntime : at dalvik.system.NativeStart.main(Native Method)
2015-04-22 23:20:11.617	ERROR:	AndroidRuntime : Caused by: java.lang.NullPointerException
2015-04-22 23:20:11.617	ERROR:	AndroidRuntime : at com.htc.idlescreen.base.setting.UpdateShortcutReceiver.onReceive(UpdateShortcutReceiver.java:57)
2015-04-22 23:20:11.617	ERROR:	AndroidRuntime : at android.app.ActivityThread.handleReceiver(ActivityThread.java:2397)
2015-04-22 23:20:11.617	ERROR:	AndroidRuntime : ... 10 more
2015-04-22 23:20:11.808	DEBUG:	dalvikvm : GC_EXPLICIT freed 3458K, 35% free 17404K/26531K, paused 7ms+21ms
2015-04-22 23:20:11.838	ERROR:	EmbeddedLogger : App crashed! Process: com.htc.idlescreen.base
2015-04-22 23:20:11.838	ERROR:	EmbeddedLogger : App crashed! Package: com.htc.idlescreen.base v300381862 (3.0.2215263112.381862)
```

**Comment by rhodey** [comment] 2015-04-24 01:05
at this point I can't think of any way to proceed with this bug except to get our hands on a physical device, root it, and decompile the class `com.htc.idlescreen.base.setting.UpdateShortcutReceiver`. this bug is definitely the fault of HTC but there is likely something we can hack on our end to prevent it from happening.

if anyone has an affected device and is willing to retrieve this class, please consider this on my wishlist :santa:

**Comment by tacMable** [comment] 2015-07-24 12:35
I am affected by this and can't currently use Textsecure. 
How can I help? My HTC Desire S with Android 4.0.4 and HTC Sense 3.6 
used to report the following every time a message was sent or received:
"System UI has stopped unexpectedly. Would you like to tell HTC?"

After todays deinstall/reinstall attempt it now crashes every time i try to install and register:
"Connecting OK, Waiting for SMS verification OK, ...Registering with Server..."
"Unfortunately, TextSecure has stopped. Report/OK" (Seems it wants to report to Google.)

P.S. I'm not sure I understand what "Upgrade to AppCompat v22.1" means, but it seems it's not a thing I can do?

**Comment by moxie0** [comment] 2015-07-24 15:32
@tacMable Are you able to use adb in order to get a debug log of the registration crash?

**Comment by tacMable** [comment] 2015-07-24 16:40
It seems I managed to do that. The output of 'adb bugreport' is about 5MiB in size and it seems there are several credentials in there. Should I use your GPG key from 2007 to encrypt it? Otherwise, I could privately message you an http uri of my dump?


Interactions:
$adb reboot (device reboots, pin entered, wait some time, touch TextSecure icon)
"The default lock screen has stopped unexpectedly, would you like to tell HTC?" / "No"
(connect with TextSecure: enter phone number, Register)
"connecting... waiting..."
"unfortunately, textsecure has stopped"
$adb bugreport > bugreport.txt

**Comment by moxie0** [comment] 2015-07-24 16:43
sure any of those options work for me

**Comment by pascaldragon** [comment] 2016-01-29 21:34
@rhodey , I have successfully extracted the class. What exactly would you need? The *.dex? The *.class? The decompiled code?
I would really love to see a workaround for this problem...

**Comment by swltr** [comment] 2016-02-20 10:47
@pascaldragon  , has there been any answer/further interaction regarding this issue? @rhodey or anyone else trying to fix this would need the decompiled code of at least the class `com.htc.idlescreen.base.setting.UpdateShortcutReceiver`.

**Comment by pascaldragon** [comment] 2016-03-25 10:56
@swltr , no there hasn't been. As I wrote I have the decompiled code of the class, but I'm not feeling well with just uploading it here. So if someone would want to take a look at this we could figure something out.
Alternatively someone could point me to the code in Signal that triggers the notifications and I could try to reproduce this myself with the hope of providing a patch.

**Comment by cascheberg** [comment] 2016-03-28 07:29
I found this: https://github.com/Chairshot215/Harmonia_Evo_V_Decompiled/blob/master/Decompiled_APKs/Rosie/smali/com/htc/launcher/UpdateShortcutReceiver$1.smali

**Comment by automated-signal** [comment] 2018-04-02 21:33
GitHub Issue Cleanup:
See #7598 for more information.

**Closed by automated-signal** 2018-04-02 21:33 UTC
Labels: bug, crash
