### ISSUE TITLE
Feature request: Non contact sms bundling/silencing 

### ISSUE THREAD

**Issue by mrmeku** [signalapp/Signal-Android#10079] opened 2020-10-12 15:11 UTC
Given that signal wants to be a person's primary sms app, one feature that holds me at bay from opting in to doing so is the frequency of spam texts I receive (4-10 per day). Thus I propose a easy to maintain feature signal could add to reduce the noise of such messages:

For all sms messages from non contacts, all the user to bundle such messages into a single thread and turn off notifications for them. While not a perfect solution to the problem, it's better than just the current number blacklist signal supports now

**Comment by Nisc3d** [comment] 2020-10-12 15:25
Feature Request belong in the forum: https://community.signalusers.org/

**Comment by vertigo220** [comment] 2020-11-23 19:40
FWIW, I made an automation flow using Automagic to deal with this issue, where it plays the notification when a message is received from a contact, otherwise it checks for any number of keywords which, if found, it ignores the message and even sends "STOP" if the incoming message has such an option*, otherwise, if none of the keywords are found, it plays the notification sound, in case it actually is a legitimate message from a non-contact. I actually think this is a better solution than just blocking or silencing all texts from non-contacts, though it does take more time to set up and isn't perfect, since I'm constantly getting texts that don't have any of the keywords, but then I add new ones and gradually make it better.

*I did this due to all the political spam messages I was receiving the past couple months, which are unfortunately legal (which is BS) and so nothing more can be done about them. I've recently started receiving non-political spam texts, which I didn't use to, so I'm wondering if it's because I verified my number by sending those stop messages or if it's just coincidence. But this whole mess just brings into light a much bigger problem with Signal: you can't forward the message to report it. You can forward the text, but I think forwarding it to the FTC to report it and have something possibly be done about it would require being able to forward the actual text. It would be nice to have a spam button that would automatically do this.

**Comment by street-grease-coder** [comment] 2021-01-13 16:14
@Nisc3d: this is phrased as a feature request, but really it is an issue, as in, missing functionality to work as intended. Signal allows dangerous spoofed sms through without possibility to filter them (i.e. block all except known numbers). This is especially dangerous in the context of social engineering. This is quite a serious flaw in my opinion and should be fixed immediately

**Comment by codeinabox** [comment] 2021-07-08 13:14
I stumbled upon this issue as in the last month I have been experiencing a lot of SMS spam so would love to see a feature to deal with this.

**Closed** 2022-02-02 09:59 UTC
Labels: wontfix

**Comment by vertigo220** [comment] 2022-03-02 21:06
It will be again in ~4-5 months, but I've quit using Signal because of the numerous issues and missing basic functionality that prevent it from being a realistic default SMS app, so not an issue for me.
