### ISSUE TITLE
No "desktop computer" emoji.

### ISSUE THREAD

**Issue by navid-zamani** [signalapp/Signal-Android#11201] opened 2021-04-13 11:38 UTC
The emoji for "desktop computer" shows a iMac instead. Nobody wants to say  "iMac" instead of a normal desktop computer. Especially since nowadays iMacs aren't even computers anymore at all, but merely locked-down smartphones with more power and a bigger screen that happen to internally use a computer. Like a router or a newer washing machine.

I cannot use that emoji without insulting my peer.

Please do not use Apple-themed emojis anywhere but on Apple's _electronic jewelry_.

**Comment by greyson-signal** [comment] 2021-04-13 13:20
Hi there! For consistency, all Signal clients use the same emoji set. There may be some you don't like, but such is life. Closing this because it's working as intended. Thanks!

**Closed by greyson-signal** 2021-04-13 13:20 UTC
