### ISSUE TITLE
no importing sms messages..??

### ISSUE THREAD

**Issue by Tommy2678** [signalapp/Signal-Android#11543] opened 2021-08-14 05:06 UTC
I tried settings as default messager, but nothing happened, can't use this app without sms and call history, sorry! Hopefully it will come in a later update.

**Comment by UserX404** [comment] 2021-08-15 11:36
Hello
Please don't delete the issue template and search for open and closed issues before opening a new one.
Please close this as dupe of https://github.com/signalapp/Signal-Android/issues/10618

fyi: https://github.com/signalapp/Signal-Android/issues/10618#issuecomment-766310337

**Comment by Kakama** [comment] 2021-08-17 22:52
It is a duplicate of a closed issue, but while this dupe is open I feel it's worth pointing out that this missing feature is, in my experience, the single greatest blocker to getting normal people to use Signal.  Once upon a time they would happily download the app as instructed or hand over their phone, and in a few clicks you could import their old SMS, set it as the default SMS sink, swap their old messenger icon for the Signal icon, and bam, they're a Signal user and happy for it.  It's pretty obvious even to the nontechnical when they are sending an insecure message vs a secure one, given the lock icon on the Send button and the faded text in an empty message entry box.  They don't know the details of how SMS or Signal or default apps works, but they're happy to use the otherwise very use-friendly application as their primary communication app because 'it is encrypted bro'.  

However, without importing the old SMS messages, all of this goes out the window with "but where are my texts" and "I don't want yet-another-messenger application" both of which are completely valid user concerns.  It's honestly enough of a pain for the technically literate setting up for the first time, as referencing your message history with someone is a common use case of all messengers (even ones with self-destruct options).  People who understand the tradeoffs between convenience and privacy may be willing to make that small sacrifice, but it is a barrier to entry for non-technical users that doesn't need to exist.  Normal users have a vague understanding that most of their applications and phone communications are being spied upon by corporations and governments, but will follow the path of least resistance.  Security-minded people are all on Signal already and have spent years evangelizing it to the people who need the most help: the non-technical masses.

Signal is an amazing application primarily _because_ of the seamless integration with existing SMS workflow and overall user-friendliness, but after the import was removed I have found user conversion and retention incredibly difficult.  I understand the old version of this feature is technical debt.  I know it did not work for MMS and group messaging.  I am not asking developers to re-introduce cruft into the codebase.  I am simply trying to communicate the importance of this feature that was so hastily dismissed in #10618 .  It may not seem important in light of various bugfixes in open issues, but I believe this to be the **most sorely needed feature for widespread user onboarding** and urge the developers to consider prioritizing it appropriately when you have the bandwidth to do so.

**Comment by UserX404** [comment] 2021-08-17 23:02
I'm with you and also want back this feature, but it's not a bug - it's a feature. And features should be discussed in the [community forum](https://community.signalusers.org/t/import-standard-sms-database-into-signal/6362).
But i've already pointed you to the latest statements.

**Comment by Kakama** [comment] 2021-08-17 23:18
That's fair, I did not realize feature requests belonged there and only saw links to the previous closed Issue.

**Closed** 2021-08-18 12:21 UTC
