### ISSUE TITLE
On 4.28 update, conversation color switched between myself and the recipient

### ISSUE THREAD

**Issue by brs17** [signalapp/Signal-Android#8254] opened 2018-10-05 04:42 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After updating to the 4.28 release just a few minutes ago, I see that the messages I send are now the color I had picked for the conversation. In previous releases I was always grey/white and the other person was the color.

### Steps to reproduce
- Update to 4.28
- Send a message to a friend

**Actual result:** The messages I send are in green/purple/blue/etc.
**Expected result:** The person I am messaging's messages be in green/purple/blue/etc and my messages be white/grey. I could see an enhancement being the ability to set a color for myself, but I do not think taking away the other person's color is an improvement (but if that is the decision that has been made, changes also need to come out in the desktop program to maintain consistency).

### Screenshots
![signalbug](https://user-images.githubusercontent.com/7460774/46516252-eff5ab00-c825-11e8-9de6-8f80aa5518bc.png)

### Device info

**Device:** Nexus 5x
**Android version:** 8.1.0
**Signal version:** 4.28.0 (BETA channel)

### Link to debug log
No log since this is just a constant issue.

**Comment by Cerberus0** [comment] 2018-10-05 06:55
Duplicate of https://github.com/signalapp/Signal-Android/issues/8245

**Closed** 2018-10-05 14:19 UTC
