### ISSUE TITLE
Long notification sound labels can lead to wrapping

### ISSUE THREAD

**Issue by jancborchardt** [signalapp/Signal-Android#9162] opened 2019-11-05 01:10 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Having the default notification sound for messages with a filename which is slightly longer, this leads to strange wrapping issues of the "Sound" label as you can see below in the screenshots.

### Steps to reproduce
- Have a custom notification sound for messages in the system, and have this sound be a sound file with a slightly longer name
- In Signal, go to Settings
- Go to Notifications
- As "Sound", choose "Default notification sound"

**Actual result:** The "Sound" label is wrapped, 1 letter a row.
**Expected result:** The "Sound" label should stay intact, and instead the long filename should be ellipsized.

### Screenshots
![Screenshot_20181219-013216_Signal](https://user-images.githubusercontent.com/925062/68170730-3fe6fa00-ff71-11e9-9a91-468d36294228.png)

### Device info
**Device:** Fairphone 2
**Android version:** 8.1.0
**Signal version:** 4.47.6

**Comment by alan-signal** [comment] 2019-11-06 23:59
Duplicate of #9078

**Closed by alan-signal** 2019-11-06 23:59 UTC
