### ISSUE TITLE
Importing system SMS

### ISSUE THREAD

**Issue by jaissugam** [signalapp/Signal-Android#10451] opened 2021-01-10 16:51 UTC
- I have searched open and closed issues for duplicates
-  I am submitting a bug report for existing functionality that does not work as intended
-  I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After turning on the SMS enabled option to make signal my default SMS app, it acknowledges that phone's SMS messages were copied to signal database but the inbox does not show any recent SMS messages.

**Actual result:** The inbox does not show SMS messages.
**Expected result:** The inbox should show device SMS messages since signal is the default SMS app.

### Device info

**Device:** Honor Nova 
**Android version:** Android 9
**Signal version:** 5.0.8

**Comment by evrifaessa** [comment] 2021-01-10 16:53
Duplicate of #10377. Same manufacturer.

**Comment by Tursko** [comment] 2021-01-10 18:18
Since it's a duplicate, please close the request.

**Closed** 2021-01-10 18:29 UTC
