### ISSUE TITLE
Signal app freezes on launch

### ISSUE THREAD

**Issue by sverit** [signalapp/Signal-Android#12773] opened 2023-02-04 22:15 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I transfered my apps from my old phone to my new one via Samsung Smart Switch. The Signal app is the only app that does not work on my new phone, it opens to a blank screen or sometimes to a logo screen and that's it. The whole app is unresponsive now.
Clearing the cache is not possible, because there is no data. Clearing the app-data and reinstalling the app does not change anything.

### Steps to reproduce
Launch the app

**Actual result:** App freezes on launch.
**Expected result:** App should open to my contact list.

### Screenshots
https://user-images.githubusercontent.com/31847769/216791522-85def3dc-2219-4478-bed2-ea07d5bacb42.mp4

### Device info

**Device:** Samsung Galaxys23 Ultra / SM-S918B/DS
**Android version:** 13.0.0
**Signal version:** 6.11.0

### Link to debug log
[signal_logcat.txt](https://github.com/signalapp/Signal-Android/files/10609757/signal_logcat.txt) is the output of:
`adb -d logcat | findstr org.thoughtcrime.securesms`

Steps during logging were:
1. force stoping the app
2. deleting the data
3. launching the app
4. tapping wildly on the unresponsive screen
5. switch app forth and back via multitasking

Thank you for your help :)

**Comment by rhyven** [comment] 2023-02-05 08:21
This is happening to me, too! Fresh factory reset on a Motorola G31(w). Thought I was going crazy. 

I found that leaving the Beta programme allowed me to *launch* Signal, however because my backup was from 6.11.0 (and mainline is 6.9.2 IIRC), I couldn't restore my backup... Can't restore backups from newer versions 🙃

Other things I've tried include dropping off WiFi, disconnecting my VPN, deleting the locally-stored backup file, and disabling the a screen reader in Accessibility Services.

**Comment by rhyven** [comment] 2023-02-05 08:31
Aha - not a fix, but a clue:

* uninstall 6.11.0
* leave the beta program
* install 6.9.2
* launch Signal, then close it
* rejoin the beta program
* update back to 6.11.0
* launch Signal

... Signal now loads! However, it still crashes (insta-close) at the end of restoring my backup. Some user data is consumed at this point, but relaunching Signal just prompts me to restore again :(

**Comment by Helium314** [comment] 2023-02-05 20:52
@sverit did you also try it with the backup function of signal? This may work better.
Some backup / migration tools have issues because signal stores some encryption key(s) outside its own data folder, and the tools may not be aware of this.

**Comment by qlx4r** [comment] 2023-02-05 22:13
the same is happening to me:

* Motorola Edge 30 ultra
* Android 12
* Signal 6.11.0 (beta programme)

This is a fresh phone, I installed Signal from play store, it freezes on the startup screen. Tried leaving and joining the beta programme, to no avail.

**Comment by sverit** [comment] 2023-02-06 11:32
@Helium314 I tried transfering the data via the SIgnal app, but transfer from newer versions to older versions is not supported, it says :/

**Comment by sverit** [comment] 2023-02-06 11:34
@qlx4r I hat the same issue at first, I had to uninstall the signal app, leave the beta program and then clear the Google Play app cache, so that it reloads the app info. Then I got the old stable version show up in Google Play and could install it, which works (although I don't have my old data sadly).

**Comment by nicholas-signal** [comment] 2023-02-06 15:24
This is an issue with the 6.11.0 beta pre-release, and will be fixed in the imminent 6.11.1 beta pre-release.

**Comment by sverit** [comment] 2023-02-07 13:53
> This is an issue with the 6.11.0 beta pre-release, and will be fixed in the imminent 6.11.1 beta pre-release.

Thank you, the app starts with version 6.11.1, but I cannot restore my backup from my old device. When I try it from app-to-app it says failed, when I try it via a backup file the app on my new phone crashes/closes suddenly after ~32000 messages :/

See here: https://user-images.githubusercontent.com/31847769/217263907-280e810a-082b-42b7-9b0d-6e954554cc5b.mp4

**Comment by alex-signal** [comment] 2023-02-07 14:01
@sverit Could you please submit a debug log and post the link here?

There are steps here for grabbing one during registration https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports

**Comment by sverit** [comment] 2023-02-07 14:05
@alex-signal I don't think I can, because I cannot access the signal main menu before the import-process to create the debug log. And if I go to signals main screen by skipping the import I cannot start the import again manually, because it is only possible before the first app start :/

**Comment by alex-signal** [comment] 2023-02-07 14:07
@sverit You should be able to tap 8x anywhere on the screen during the registration flow (including the "welcome" screen)

**Comment by AlexMDD** [comment] 2023-02-07 18:03
Ich habe das selbe Problem, in der selben Konstellation.
https://debuglogs.org/android/6.11.1/dc5f984f13a71feecac9e12a1a32ef426cb481b3ef9df20cc2f061e34910ee7f

**Comment by rhyven** [comment] 2023-02-07 19:16
Also occurring here, too - I can launch Signal now, but I can't successfully restore from backup.

@alex-signal once the restore begins, the tapping 8x doesn't work. And at the end of the backup (at 16400 for me), it crashes out immediately without any opportunity for meaningful logs :/

I suspect it happens just as it starts restoring the media - I recall previous restores being very fast until the final couple thousand, and I assume this is because the media takes much longer to restore?  This flies all the way through at a consistent fast speed until the crash.

**Comment by qlx4r** [comment] 2023-02-07 19:22
Signal now starts, but I have the same problem.... transfer fails after ~60%. Here is my debug log:

https://debuglogs.org/android/6.11.1/52f5bd52fe8b6d7fc71b5e9c23d1031f70619e343ba3f97bc08d3ad7e0e0e13f

**Comment by rhyven** [comment] 2023-02-07 19:30
Hey, @qlx4r - how did you get that log? Are you using ADB or something? I'd like to provide mine but haven't figured out how (re my previous comment)

**Comment by qlx4r** [comment] 2023-02-07 20:44
@rhyven the transfer failed but the app did not crash. So I tapped the app eight times (as described above) et voila... the debug log

**Comment by rhyven** [comment] 2023-02-08 01:56
Since Signal was crashing during the import (and the 8-tap thing doesn't work there), I managed to get an adb logcat log (debug mode).  Attached here, filtered by PID.
 
[debug.txt](https://github.com/signalapp/Signal-Android/files/10680910/debug.txt)

**Comment by alex-signal** [comment] 2023-02-08 13:30
Thanks a lot for the logs! I've sent it to the right person. We have put out .2 as of last night, though I don't specifically know if this issue was resolved.

**Comment by qlx4r** [comment] 2023-02-08 19:51
I am sorry to report that even with 6.11.2 on both devices, transfer fails again.

Debug log:

https://debuglogs.org/android/6.11.2/b81329d7c22600a1ad0e892c278eb8b10c8b16129f6a1fe3f1187b956498d369

**Comment by alex-signal** [comment] 2023-02-09 13:35
Thanks for the logs!

**Comment by rhyven** [comment] 2023-02-10 03:49
I'm also having the crash with 6.11.2 (and also with the outright force-close so can't use the built-in debugger)

I've attached a fresh ADB debug log here: [debug 6.11.2.txt](https://github.com/signalapp/Signal-Android/files/10703502/debug.6.11.2.txt)

Thanks for your work on this, team :)

**Comment by alex-signal** [comment] 2023-02-10 14:15
Hi folks! This issue *should hopefully* be resolved in 6.11.4

**Comment by qlx4r** [comment] 2023-02-10 21:54
I am happy to report that with v6.11.4 on both devices, transfer and registration has been successfully completed. 

Thank you very much, signal team, for your support and persistence. It is much appreciated!

**Comment by rhyven** [comment] 2023-02-11 02:44
Confirmed here as well, thanks everyone!

**Closed** 2023-02-13 13:27 UTC
