### ISSUE TITLE
#000000 not available for dark mode

### ISSUE THREAD

**Issue by varunvjha** [signalapp/Signal-Android#10404] opened 2021-01-09 14:13 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Darkest colour available is not dark enough.

**Comment by Genis-Sage** [comment] 2021-01-09 15:35
hey @varunvjha 

this is a duplicate of #8261

apart from that, it's a behaviour change request, which belong onto the community forum:
https://community.signalusers.org/t/restore-black-background-as-dark-theme/4571

**Comment by SriGaneshSharma** [comment] 2021-01-09 15:36
Crezi

**Comment by SriGaneshSharma** [comment] 2021-01-09 15:36
I dont like it

**Comment by Merthan** [comment] 2021-01-09 22:32
> hey @varunvjha
> 
> this is a duplicate of #8261
> 
> apart from that, it's a behaviour change request, which belong onto the community forum:
> https://community.signalusers.org/t/restore-black-background-as-dark-theme/4571

What would be the way to go to add a third option in the settings (light, dark, black/oled). Could I in theory just create a PR or would that be ignored.

**Closed** 2021-01-11 04:56 UTC
