### ISSUE TITLE
no more notification on Samsung

### ISSUE THREAD

**Issue by leonardoporp** [signalapp/Signal-Android#8841] opened 2019-05-30 14:13 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
In the last few days I do not receive anymore signal notifications. I have always received them but from a week let's say I don't get them till I open the app

### Steps to reproduce
I don't know

**Actual result:** I don't receive anymore Signal notifications
**Expected result:** I should receive them

### Device info

**Device:** samsung SM-A320FL (a3y17ltexc)
**Android version:** 8.0.0
**Signal version:** 4.40.4

### Link to debug log

https://debuglogs.org/9d792d6c469aaf2cc496b81ddc9a28f720c0c55a3b85b8ecf8ed0557c7930522

**Comment by ozgurakyazi** [comment] 2019-05-31 07:34
[My post](https://github.com/signalapp/Signal-Android/issues/8604#issuecomment-496313488) on a related issue

**Comment by greyson-signal** [comment] 2019-05-31 15:01
I don't see any logs for `FcmService`, which would imply that the system isn't giving us any FCM messages. Could be due to battery optimizations or some other OS change. Also saw this:

```java
org.whispersystems.signalservice.api.push.exceptions.PushNetworkException: java.net.UnknownHostException: Unable to resolve host "textsecure-service.whispersystems.org": No address associated with hostname
```

Only saw it once, but usually that indicates some VPN issue or weird wifi hotspot issue.

Other than that, I'm going to close this as a dupe of #8692

**Closed by greyson-signal** 2019-05-31 15:01 UTC

**Comment by leonardoporpora** [comment] 2019-05-31 15:32
What should I do? The sender says me that he doesn't even see that the
message is delivered! In fact I receive all messages as soon as I open the
app. Please help signal is the only IM I use I cannot work with this
problem

**Comment by greyson-signal** [comment] 2019-05-31 16:25
It's unclear. If the device chooses not to give us any FCM messages at all, there's not much we can do. I'd double check to make sure there's no battery optimizations enabled (see [here](https://support.signal.org/hc/en-us/articles/360007318711-Troubleshooting-Notifications#android_notifications_troubleshooting_phone)).

One thing I've been thinking about is detecting when notifications are consistently coming in late and trying some other strategies. I'll see what I can come up with.

**Comment by leonardoporpora** [comment] 2019-05-31 19:01
Thanks let me know
