### ISSUE TITLE
SMS sent with external apps do not appear in Signal

### ISSUE THREAD

**Issue by anisse** [signalapp/Signal-Android#7634] opened 2018-04-04 16:11 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When used as an SMS client, Signal won't show SMS that are sent with an external app (Google Assistant, voice commands, wearables, etc.), and directly added to the SMS database. Signal should watch the SMS database for new messages, and import them in real-time.

This is a re-opening of #218 following the new issue template.

### Steps to reproduce
- Trigger a voice command ("ok google…") on your phone or wearable
- Use it to send an sms

**Actual result:** The SMS is sent, but there's no trace of it in Signal.
**Expected result:** The SMS is sent, and it appears in Signal conversation list.

### Device info

**Device:** Huawei Nexus 6P (angler)
**Android version:** 8.1.0 
**Signal version:** 4.18.0

### Link to debug log

https://debuglogs.org/4e3148e51e6fb0560f05102efc37748985bac8da9f10fde16d1bca294fa2d4bd

**Comment by moxie0** [comment] 2018-04-04 16:58
Thanks, but it looks like this is a duplicate of #7627. I'd love to support this, but I don't think it's possible to do consistently or reliably given the current level of integration that Google exposes. If that changes or if I've missed something, I'd be happy to revisit.

**Closed by moxie0** 2018-04-04 16:58 UTC
