### ISSUE TITLE
Bug: no sms-import :  Important usabilty problem with misunderstood by contributors

### ISSUE THREAD

**Issue by jasonswearingen** [signalapp/Signal-Android#11250] opened 2021-05-02 03:46 UTC
As per: https://github.com/signalapp/Signal-Android/issues/10618#issuecomment-766310337

>  please feel free to use Signal as your SMS app moving forward, and if you want to reference your previous messages, just check your old SMS app. 

Critical flaw in this logic.   The Google SMS app does not let you read your old messages if it is not the default SMS client.  So this is a total non-starter for adoption or advocating adoption of Signal.

**Comment by anthonyda** [comment] 2021-05-03 17:28
Same issue for me, this is sad.

**Comment by DvoweredCode** [comment] 2021-05-07 21:49
The number of Android users utilizing the Google Messages app has to be in the millions. Talk about limiting your market share out of the gate...

**Comment by greyson-signal** [comment] 2021-05-08 21:54
Thanks for the extra info, but closing as a duplicate of #10618. Again, may come back to it, just not for the time being.

**Closed by greyson-signal** 2021-05-08 21:54 UTC

**Comment by jasonswearingen** [comment] 2021-05-08 22:12
@greyson-signal #10618 is closed.  you should leave one of these open for tracking.   Closing it implies that Signal is not aware of the issue.  Otherwise people will keep searching (wasting their time) and opening new bugs (wasting your time).
