### ISSUE TITLE
Error while playing a specific voice message

### ISSUE THREAD

**Issue by righy** [signalapp/Signal-Android#8620] opened 2019-02-16 14:51 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
One of my contact sent me a voice message using the in-app recorder, but I cannot play it. When I tap the play icon, it changes into a pause icon for about 3 seconds without playing any audio, and then it switches back to the play icon while the error message "Error playing audio!" appears.

Only this particular voice message doesn't play. All the other voice messages previously sent by this contact, and all my other contacts, play fine.

My contact can play the audio normally from her phone. I can also play the audio by either:
* using Signal desktop
* long-tap the audio message, save the it as a file on my SD card, rename the file extension from .attach to .mp4 and play that file using an audio player
* renaming that file to .mp3 and re-sending it to another contact. That contact can play the audio but after pressing play, it stalls for a few seconds before actually starting to play. See the [debug log](https://debuglogs.org/0e1ae52cf3a90abc643abe6d6eebacfd1c80edd2c49c07d2b7ca84ac6f0692f3) of that contact.

### Steps to reproduce
- Download and unzip this [voice_message.zip](https://github.com/signalapp/Signal-Android/files/2878984/voice_message.zip).
- Rename the file extension `.attach` into `.mp3` (it's actually an MP4 file, but we need a file extension that looks like an audio file).
- Send yourself that file by pressing "+" button -> "Audio". You can also send it from another phone.
- press the play button

**Actual result:** The voice message doesn't play.
**Expected result:** The voice message plays.

### Device info

**Device:** Samsung Galaxy Note 2
**Android version:** 7.1.2
**Signal version:** 4.33.5

### Link to debug log

[Debug log just after failing to play the voice message](https://debuglogs.org/88111ed87f02add1aa8762c175f1e635e4e5757ebf8c3d1593b677e8feeae687).

**Comment by tuxayo** [comment] 2019-02-18 16:07
Do you confirm that it's a duplicate of #7748 ?
(which should be reopened if I understand correctly)

**Comment by greyson-signal** [comment] 2019-02-18 17:17
@tuxayo This is a separate issue. #7748 was a result of specific phones being unable to play any voice note because of manufacturer-specific alterations to core MediaPlayer components. Moving to ExoPlayer solved the core issue.

This issue seems to be around specific voice notes. It's possible there was an anomaly during recording.

**Comment by greyson-signal** [comment] 2019-02-18 17:57
@righy Do you think this is a duplicate of #8440?

**Comment by righy** [comment] 2019-02-19 06:58
> Do you think this is a duplicate of #8440?

If it is, it means I triggered it differently, because my contact was able to record, send me and play the voice message, whereas I am the one having a problem playing it.

**Comment by righy** [comment] 2019-02-19 08:14
I tried to investigate this issue. As you can see in the debug log, the voice message is being downloaded from the AttachmentServer 3 times, with and without dubious range headers. I captured the traffic using tcpdump on the phone during these download attempts, and here is what is happening on a every playing attempt.

1. The client connects to the server and requests the audio without range headers.
2. The server starts sending the file with a length header of 1051990 (this matches the size of the audio file as exported to SD card by Signal).
3. After receiving 17 or 18 data packets, the client resets the connection, resulting in only 556544 or 720384 bytes of the audio being transferred. This data matches the beginning of the audio file.
4. Just after or before the reset, the client makes a new connection to request the audio with range 1011061-.
5. The server starts sending the data with a length header of 40929 and a range header of 1011061-1051989/1051990 (this is logical).
6. After receiving 3 or 4 data packets, the clients send a new GET request with range header of 1516881871- and resets the connection right after that. Despite the length header of 40929, actually 65024 or 97792 bytes are being sent. Despite the range header, the data sent by the server actually matches the range 512- of the audio file.
7. The client makes a new connection and requests the range 1516881871- again.
8. The servers starts sending the data with a length header of -1515829881 and a range header of 1516881871-1051989/1051990 (oops).
9. After receiving 2 packets, the client resets the connection, resulting in only 32256 bytes transferred. This data matches again the range 512- of the audio file.
10. Steps 7 to 9 repeats.
11. Steps 7 to 9 repeats.

[voice_message.zip](https://github.com/signalapp/Signal-Android/files/2878984/voice_message.zip)
[tcpdump_captures.zip](https://github.com/signalapp/Signal-Android/files/2878985/tcpdump_captures.zip)

**Comment by righy** [comment] 2019-02-19 08:58
According to http://mp4parser.com/, the requested range 1011061- matches the moov header of the audio file. However, since the AttachmentServer is not sending the correct data (range 512-), it is no wonder that the player fails and start requesting crazy ranges.

**Comment by righy** [comment] 2019-02-19 09:14
The AttachmentServer is [using the skip() function to get the requested range](https://github.com/signalapp/Signal-Android/blob/f9adb4e4554a44fd65b77320e34bf4bccf7924ce/src/org/thoughtcrime/securesms/attachments/AttachmentServer.java#L219), but [it sometimes doesn't work](https://stackoverflow.com/questions/14057720/robust-skipping-of-data-in-a-java-io-inputstream-and-its-subtypes). Maybe that's the problem.

**Comment by greyson-signal** [comment] 2019-02-19 16:09
@righy  I'll look into the usage of `skip()` when I get a change. Thanks for the detailed analysis of the file read!

**Comment by joao456** [comment] 2019-02-20 18:12
I’m having the same issue, apparently:

Tap the play icon, it changes into a pause icon for about 3 seconds without playing any audio, and then it switches back to the play icon while the error message "Error playing audio!" appears.

My contact can play the audio normally from it phone. I can also play the audio by either:

- Using Signal desktop;

- Long-tap the audio message, save the it as a file on my SD card, rename the file extension from .attach to .mp4 and play that file using an audio player.

The only difference is that I’m having this problem with more than a single message or contact. The issue occurred in three different chats, one been a group chat.

**Device** : motorola Moto E (condor) 
**Android** : 7.1.2 (LineageOS 14.1) 
**Signal version**: 4.33.5
Obs: running without google services

**Comment by erickzr** [comment] 2019-02-21 04:54
Also had this happened error messages from voice recorders sent by my friends 

btw you guys at the github team do listen to feedback, love the new update you guys did with the Note to Self. I brought that up and you guys delivered. Massive props. going to donate again to freedom.press campaign

**Comment by righy** [comment] 2019-02-21 08:51
It's possible to reproduce the bug by re-sending the same audio. I updated the *Steps to reproduce* accordingly in the issue description.

**Comment by righy** [comment] 2019-02-21 09:09
Trying to play the audio on another phone shows a different behaviour: the file plays but it takes a few seconds before it starts to play (see the [debug log](https://debuglogs.org/0e1ae52cf3a90abc643abe6d6eebacfd1c80edd2c49c07d2b7ca84ac6f0692f3)). I updated the issue description accordingly.

**Closed** 2022-02-04 14:14 UTC
Labels: wontfix
