### ISSUE TITLE
Undismissable dialogue: "Member couldn't be re-added to New Group. Do you want to add them now?"

### ISSUE THREAD

**Issue by joehand** [signalapp/Signal-Android#12554] opened 2022-10-26 23:35 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
There is a dialogue message at the top of the group saying:

> Member couldn't be re-added to New Group. Do you want to add them now?

The two options, No Thanks and Add Member, have been clicked by multiple people in the group but they do not dismiss dialogue.

Other info:

* I've tried reinstalling app.
* I've left and rejoined group.
* Other group members on Android also see this message and cannot dismiss. 
* Group members with iPhone or Desktop app do not see this dialogue message. Android only.

### Steps to reproduce

* A new member was added but never joined (? I think)
* Group was updated to a new group version (? I think)
* Member is listed in group members but may not have rejoined.

(Note: the dialogue has been present for awhile and the initial steps that made it happen are a bit hazy)

**Actual result:** Clicking "No Thanks" does nothing. 
**Expected result:** Clicking "No Thanks" should dismiss message.

**Actual result:** Clicking "Add Member" results in error "Cannot add member." Dialog persists.
**Expected result:** Clicking "Add Member" attempts to add member. 

### Screenshots

<img width="380" alt="Screen Shot 2022-10-26 at 4 18 11 PM" src="https://user-images.githubusercontent.com/684965/198156674-c650c47c-4e14-4720-999f-c2ddfd2e5e5e.png">

### Device info

**Device:** Google Pixel 4
**Android version:** 13
**Signal version:** 5.52.5

Another group member with same issue:

**Device:** Google Pixel 5
**Android version:** 13
**Signal version:**  5.52.5

### Link to debug log

Note: debug log captured after failed "Add member" attempted which results in error "Cannot add member"

https://debuglogs.org/android/5.52.5/2758de2d4ce186da5490771933d9578f37a2c5a29cb3f0c45bfaa55710ec5127

**Comment by OddHero** [comment] 2022-10-31 16:29
I have the same Issue in a Group now, so I can confirm its a Bug. Happened on Oktoper 21, the Popup is still open to this day...

![Popup](https://user-images.githubusercontent.com/1459179/199051767-177f8b9f-be6b-4781-9b86-0deb73bebe2e.jpg)

The steps that lead to the Issue are slightly different than in the reporters post
1. The Group was created a long time ago (v1)
2. At some point it got migrated to v2 (also quite some time ago)
3. A member created a new account for a new number (2 weks ago)
4. One of the Admins removed the old account from the group (both accounts where admins, both joined before the migration of the group)(2 weeks ago)
5. The Admin added the new Account to the Group (probably unrelated because everything behaved normal)(2 weeks ago)
6. The message popped up for all users using an Android Device, (for the Admin that removed the old account it only showed up after restarting signal)(Okt.21-today)

Things we tried

- As a blog post mentioned there could be an issue with devices that where connected to the old account and therefore might not be removed by an Admin we tried re-adding the old account and having that account leave the group manually -> Nothing changed

Aditional info:
Pushing the No Thanks "nein Danke" Button seems to results in the following LogMessage:
```
[6.0.4] [main ] 2022-10-31 16:25:09.327 GMT+01:00 I ConversationParentFragm: onModified(RecipientId::156) REGISTERED
[6.0.4] [main ] 2022-10-31 16:25:09.330 GMT+01:00 I ConversationParentFragm: updateDefaultSubscriptionId(null)
[6.0.4] [main ] 2022-10-31 16:25:09.364 GMT+01:00 D ConversationParentFragm: [presentMessageRequestState] No message request necessary.
```
The full log is appended, I clicked the No Thanks multiple times, thats why the log shows it multiple times

Pushing the No Thanks button triggers an exception:
```
[6.0.4] [17973] 2022-10-31 16:25:12.299 GMT+01:00 I ProfileUtil: Updating profile key credential on recipient RecipientId::220, fetching
[6.0.4] [main ] 2022-10-31 16:25:12.397 GMT+01:00 I SimpleProgressDialog: Taking some time. Showing a progress dialog.
[6.0.4] [17973] 2022-10-31 16:25:12.914 GMT+01:00 I ProfileUtil: Got new profile key credential for recipient RecipientId::220
[6.0.4] [17973] 2022-10-31 16:25:13.097 GMT+01:00 W GroupsV1MigrationSugges: Permanent failure! Removing these dropped members from the list.
[6.0.4] [17973] 2022-10-31 16:25:13.097 GMT+01:00 W GroupsV1MigrationSugges: org.thoughtcrime.securesms.groups.GroupChangeFailedException: org.whispersystems.signalservice.internal.push.exceptions.GroupPatchNotAcceptedException: StatusCode: 400
[6.0.4] [17973] 2022-10-31 16:25:13.097 GMT+01:00 W GroupsV1MigrationSugges: 	at org.thoughtcrime.securesms.groups.GroupManagerV2$GroupEditor.commitChangeWithConflictResolution(GroupManagerV2.java:656)
[6.0.4] [17973] 2022-10-31 16:25:13.097 GMT+01:00 W GroupsV1MigrationSugges: 	at org.thoughtcrime.securesms.groups.GroupManagerV2$GroupEditor.commitChangeWithConflictResolution(GroupManagerV2.java:639)
[6.0.4] [17973] 2022-10-31 16:25:13.097 GMT+01:00 W GroupsV1MigrationSugges: 	at org.thoughtcrime.securesms.groups.GroupManagerV2$GroupEditor.commitChangeWithConflictResolution(GroupManagerV2.java:633)
[6.0.4] [17973] 2022-10-31 16:25:13.097 GMT+01:00 W GroupsV1MigrationSugges: 	at org.thoughtcrime.securesms.groups.GroupManagerV2$GroupEditor.addMembers(GroupManagerV2.java:353)
[6.0.4] [17973] 2022-10-31 16:25:13.097 GMT+01:00 W GroupsV1MigrationSugges: 	at org.thoughtcrime.securesms.groups.GroupManager.addMembers(GroupManager.java:409)
[6.0.4] [17973] 2022-10-31 16:25:13.097 GMT+01:00 W GroupsV1MigrationSugges: 	at org.thoughtcrime.securesms.groups.ui.migration.GroupsV1MigrationSuggestionsDialog.lambda$onAddClicked$3(GroupsV1MigrationSuggestionsDialog.java:78)
[6.0.4] [17973] 2022-10-31 16:25:13.097 GMT+01:00 W GroupsV1MigrationSugges: 	at org.thoughtcrime.securesms.groups.ui.migration.GroupsV1MigrationSuggestionsDialog.$r8$lambda$4tOym9D4E_wW36Eowv_ZiuttLsk(Unknown Source:0)
[6.0.4] [17973] 2022-10-31 16:25:13.097 GMT+01:00 W GroupsV1MigrationSugges: 	at org.thoughtcrime.securesms.groups.ui.migration.GroupsV1MigrationSuggestionsDialog$$ExternalSyntheticLambda4.run(Unknown Source:2)
[6.0.4] [17973] 2022-10-31 16:25:13.097 GMT+01:00 W GroupsV1MigrationSugges: 	at org.signal.core.util.concurrent.SimpleTask.lambda$run$3(SimpleTask.java:87)
[6.0.4] [17973] 2022-10-31 16:25:13.097 GMT+01:00 W GroupsV1MigrationSugges: 	at org.signal.core.util.concurrent.SimpleTask.$r8$lambda$jvZ0-8nsHlQ_qvU-Rex9q6uvOXs(Unknown Source:0)
[6.0.4] [17973] 2022-10-31 16:25:13.097 GMT+01:00 W GroupsV1MigrationSugges: 	at org.signal.core.util.concurrent.SimpleTask$$ExternalSyntheticLambda0.run(Unknown Source:4)
[6.0.4] [17973] 2022-10-31 16:25:13.097 GMT+01:00 W GroupsV1MigrationSugges: 	at org.signal.core.util.concurrent.TracingExecutorService.execute$lambda-0(TracingExecutorService.kt:25)
[6.0.4] [17973] 2022-10-31 16:25:13.097 GMT+01:00 W GroupsV1MigrationSugges: 	at org.signal.core.util.concurrent.TracingExecutorService.$r8$lambda$JWXxcO1P3GzWBfvZk9N5USCLsAo(Unknown Source:0)
[6.0.4] [17973] 2022-10-31 16:25:13.097 GMT+01:00 W GroupsV1MigrationSugges: 	at org.signal.core.util.concurrent.TracingExecutorService$$ExternalSyntheticLambda0.run(Unknown Source:4)
[6.0.4] [17973] 2022-10-31 16:25:13.097 GMT+01:00 W GroupsV1MigrationSugges: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[6.0.4] [17973] 2022-10-31 16:25:13.097 GMT+01:00 W GroupsV1MigrationSugges: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[6.0.4] [17973] 2022-10-31 16:25:13.097 GMT+01:00 W GroupsV1MigrationSugges: 	at java.lang.Thread.run(Thread.java:923)
[6.0.4] [17973] 2022-10-31 16:25:13.097 GMT+01:00 W GroupsV1MigrationSugges: Caused by: org.whispersystems.signalservice.internal.push.exceptions.GroupPatchNotAcceptedException: StatusCode: 400
[6.0.4] [17973] 2022-10-31 16:25:13.097 GMT+01:00 W GroupsV1MigrationSugges: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.lambda$static$12(PushServiceSocket.java:2334)
[6.0.4] [17973] 2022-10-31 16:25:13.097 GMT+01:00 W GroupsV1MigrationSugges: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.$r8$lambda$8TP1YqRAKaZu38lRooQqjPTRm-0(Unknown Source:0)
[6.0.4] [17973] 2022-10-31 16:25:13.097 GMT+01:00 W GroupsV1MigrationSugges: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket$$ExternalSyntheticLambda10.handle(Unknown Source:0)
[6.0.4] [17973] 2022-10-31 16:25:13.097 GMT+01:00 W GroupsV1MigrationSugges: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket$ResponseCodeHandler$-CC.$default$handle(PushServiceSocket.java:2298)
[6.0.4] [17973] 2022-10-31 16:25:13.097 GMT+01:00 W GroupsV1MigrationSugges: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket$$ExternalSyntheticLambda10.handle(Unknown Source:0)
[6.0.4] [17973] 2022-10-31 16:25:13.097 GMT+01:00 W GroupsV1MigrationSugges: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeStorageRequest(PushServiceSocket.java:1951)
[6.0.4] [17973] 2022-10-31 16:25:13.097 GMT+01:00 W GroupsV1MigrationSugges: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.patchGroupsV2Group(PushServiceSocket.java:2400)
[6.0.4] [17973] 2022-10-31 16:25:13.097 GMT+01:00 W GroupsV1MigrationSugges: 	at org.whispersystems.signalservice.api.groupsv2.GroupsV2Api.patchGroup(GroupsV2Api.java:168)
[6.0.4] [17973] 2022-10-31 16:25:13.097 GMT+01:00 W GroupsV1MigrationSugges: 	at org.thoughtcrime.securesms.groups.GroupManagerV2$GroupEditor.commitToServer(GroupManagerV2.java:769)
[6.0.4] [17973] 2022-10-31 16:25:13.097 GMT+01:00 W GroupsV1MigrationSugges: 	at org.thoughtcrime.securesms.groups.GroupManagerV2$GroupEditor.commitChange(GroupManagerV2.java:745)
[6.0.4] [17973] 2022-10-31 16:25:13.097 GMT+01:00 W GroupsV1MigrationSugges: 	at org.thoughtcrime.securesms.groups.GroupManagerV2$GroupEditor.commitChangeWithConflictResolution(GroupManagerV2.java:650)
[6.0.4] [17973] 2022-10-31 16:25:13.097 GMT+01:00 W GroupsV1MigrationSugges: 	... 16 more
[6.0.4] [17973] 2022-10-31 16:25:13.097 GMT+01:00 W GroupsV1MigrationSugges: 

```
The Code responsible for the exception is the following:
https://github.com/signalapp/Signal-Android/blob/c4bc2162f23e0fd6bc25941af8fb7454d91a4a35/app/src/main/java/org/thoughtcrime/securesms/groups/ui/migration/GroupsV1MigrationSuggestionsDialog.java#L74-L103
The code does not suggest that the Dialog would stay open afterwards as it should clearly be closed in line 92.
Therfore it seems that the call to ``` SignalDatabase.groups().removeUnmigratedV1Members(...)``` causes the real problem.

As can be seen in the crashlog the call to the signal server seems to return a status 400. which causes a ```GroupPatchNotAcceptedException```.
My investigation ends here as I cannot look at what the server is doing...

Whatever the root cause (server-side) is the dialog should close afterwards... so the call to ``` SignalDatabase.groups().removeUnmigratedV1Members(...)``` probably kills the thread as the exception is not caught. This means the callback NEVER comes back with a result which in turn means line 92 is not able to close off the popup...

Why the No Thanks button wont close the popup on the other hand is still a mystery to me.

**Comment by cody-signal** [comment] 2022-10-31 18:32
Thanks for the legwork on this, hope to have a fix together shortly.

**Closed** 2022-11-02 19:57 UTC
Labels: acknowledged
