### ISSUE TITLE
Backup crashing signal

### ISSUE THREAD

**Issue by piratenpanda** [signalapp/Signal-Android#8665] opened 2019-03-06 18:42 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal crashes when creating the backup and all text entered into the text field is lost

### Steps to reproduce
- Signal automatically creates backups. Didn't find a way to reproduce this yet

**Actual result:** Signal crashes
**Expected result:** Signal should not crash ;)

### Device info
**Device:** Pixel 2 XL
**Android version:** 9.0
**Signal version:** 4.35.2

### Link to debug log
https://debuglogs.org/a243fe7ceb869cc020a2d3fe4f6d1b55e718e7fdd61c777bf6755f7b694954a7

**Comment by greyson-signal** [comment] 2019-03-09 22:25
Unfortunately I don't see a crash in the logs, so I can't act on this. Maybe a dupe of #8666?

**Closed by greyson-signal** 2019-03-09 22:25 UTC

**Comment by piratenpanda** [comment] 2019-03-30 17:16
As this happens while creating not restoring the backup I don't see how they are related. It only happened once again so quite hard to reproduce.
