### ISSUE TITLE
Encrypted backup violates GDPR's right to data portability

### ISSUE THREAD

**Issue by sorsasampo** [signalapp/Signal-Android#7791] opened 2018-05-13 04:01 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

GDPR [article 20 Right to data portability](https://gdpr-info.eu/art-20-gdpr/), emphasis mine:

> The data subject shall have the right to receive the personal data concerning him or her, which he or she has provided to a controller, **in a structured, commonly used and machine-readable format** and have the right to transmit those data to another controller **without hindrance** from the controller to which the personal data have been provided

Recently Signal android app stopped offering `SignalPlainTextBackup.xml`. Currently only an encrypted backup can be done, and there are no clear instructions how to extract the plaintext messages. This is a clear violation of GDPR article 20.

Signal app should provide, or prominently document, a way to extract plaintext messages from the device, to honor the right to data portability.

**Comment by igor2x** [comment] 2018-05-13 05:26
According to [new rules](https://github.com/signalapp/Signal-Android/issues/7598) for bug reporting, this issue is not a bug, because it violates the rule "If you disagree with the way that a feature is working that's not a bug". And another problem is this GDPR is not related to Signal-Android alone, but whole Signal project, so the issue also violates the "If you feel like you are unable to make an idea fit within the _confines of the template_, that might be a sign that you are about to submit something that isn't a bug."

@sorsasampo, I am not saying that your ideas are not good (there actually are), but for this kind of issues it should not be opened a bug report.

May I kindly suggest to close this bug report and continue discussion on [community forum](https://community.signalusers.org/).
- Clear text export is  discussed in topic: [Lets talk about backups](https://community.signalusers.org/t/lets-talk-about-backups/2237/10)
- GDPR is discussed in topic: [Europe implements GDPR in may 2018](https://community.signalusers.org/t/europe-implements-gdpr-in-may-2018/2537/11)
and answer from Signal official in [Is there such a thing as “terms of service”?](https://community.signalusers.org/t/is-there-such-a-thing-as-terms-of-service/2734)

**Closed** 2018-05-13 08:14 UTC
