### ISSUE TITLE
Improve message handling with unreliable data connection

### ISSUE THREAD

**Issue by fungs** [signalapp/Signal-Android#2384] opened 2015-01-25 13:31 UTC
Often, I'm sending messages which stay in transition stage for a short period of time and than turn into a failed message when the data connection is instable. Then, I need to copy the text and send it again as a new message, and repeat this process until I get a good transmission. Upon success, I need to go and manually delete all failed messages. It would be much more convenient, if

a) one could be given the option to simply resent a failed message either by SMS (which is currently implemented) or over the network

b) there would be a smarter heuristic which automatically tries to resend messages that failed to transmit

Using the latest Android client available on Google Play store.

**Comment by manhole11** [comment] 2015-01-25 18:00
a) you can actually touch the "resend message" option

**Comment by fungs** [comment] 2015-01-25 18:25
True, it's possible but you still have to confirm that you don't want to send via SMS every time. I believe the handling of undelivered messages can be improved a lot without touching advanced features such as the encryption or protocol.

**Comment by janvlug** [comment] 2015-01-25 23:29
b) duplicate of #2098?

**Comment by fungs** [comment] 2015-01-26 11:32
@janvlug: no, a missing confirmation can be due to the recipient not being online. That's another level although it could be useful. What I meant was when the application detects that a message could not be passed to the server due to network problem (e.g. if the network connection was interrupted), it should retry if the data connection is up, again. This needs to be integrated with SMS delivery more conveniently.

**Comment by janvlug** [comment] 2015-02-01 22:22
@manhole11 Where can I find the "resend message" option for push messages?

**Comment by prinz-z** [comment] 2015-02-06 08:39
I would like to have the option to automatically resent the message, once a connection is avilable. I don't want to send SMS at all and I don't care if I have to wait until internet is availabe again, but it would be quite good if I could write messages even though I'm offline that will be sent once online :)

**Comment by agrajaghh** [comment] 2015-02-06 09:50
If SMS fallback is disabled, push messages are already send once the internet connection is back.

I think it should be the same if SMS fallback is enabled. We should show "Tap for SMS fallback" but still wait for the internet connection and send it automatically. Once the SMS fallback for that message got used, we should of course remove the push sending job...

**Comment by midi** [comment] 2015-06-05 10:47
This happens quite frequently to me, when I don't have a stable data connection or no network at all. Failing instead of retrying intelligently like other major messengers like Whatsapp or Telegram do, is quite a major issue and makes TextSecure hard to recommend to not so tech-savy friends, who are not familiar on how to manually resend the message.
Please queue the messages and remove the short timeout.

**Comment by fungs** [comment] 2015-08-26 15:17
After the last updates, this works much better now. I've not had a single undelivered message in the last couple of months. Others, please report so we can close this issue ASAP.

**Comment by MartinX3** [comment] 2017-01-23 10:58
Not working, last day, my internet wasn't stable inside of an arena.
#6087 
I was in the need to resent every message with an image.

**Comment by theirix** [comment] 2017-05-26 18:21
I have same problems for several months and it still can be reproduced. Android Marshmallow 6.0.1 (I heard from other similar issues that KitKat had this problem) on Moto X Play, latest Signal from the Play store (about 4.6.0). One of the latest non-delivery situation occurred ten days ago in a store with a very poor reception. Then I sent and received a lot of messages successfully with Signal and other messengers. Failed messages still haven't been delivered.
Should I reproduce it and attach a debug log?

**Comment by donnm** [comment] 2017-09-14 11:22
+1 I have this problem all the time too, often when using an unreliable 3g router, or in areas with bad cellular service. Auto-resend would be a fantastic solution, like how WhatsApp works!

**Comment by deutrino** [comment] 2018-01-05 17:58
I experience this on a Moto X Play running Android 7.1.2. Signal has never been good at handling connectivity changes. I'm commenting here so I can find the issue again later, and will try to reproduce the issue and get some logs.

**Comment by nilsseipel** [comment] 2018-02-04 19:34
+1 

I can't stress it enough: This is very important! I am traveling right now and it really is a pain to communicate with Signal with bad cellular connections. Its not suited for productive use. Please try to fix this, because I would love to have a  working open source & secure messenger.

**Comment by fungs** [comment] 2018-02-05 10:39
I think even the label is wrong, this is really a dysfunctional part of signal, not a user interface thing. However, I reported this two years ago, when I was still using Signal, then my platform become unsupported and alternative clients running on the Signal infrastructure forbidden. Anyway, Wire is much better and has a fully functional desktop web client, too. Good bye!

**Comment by moxie0** [comment] 2018-02-05 20:11
@nilsseipel Please read the contributing guidelines before posting here again, thanks!

**Comment by DreamFlasher** [comment] 2018-03-07 17:09
Why is there a resend/retry option in the UI at all? Shouldn't the expected behaviour be that if the app notices the message wasn't sent, that it continues retrying sending until it has a sufficient internet connection to actually send the message?

**Comment by automated-signal** [comment] 2018-04-02 21:29
GitHub Issue Cleanup:
See #7598 for more information.

**Closed by automated-signal** 2018-04-02 21:29 UTC
Labels: ux
