### ISSUE TITLE
Group chats lost icon and name after migration to new android phone.

### ISSUE THREAD

**Issue by urza** [signalapp/Signal-Android#7144] opened 2017-10-30 23:00 UTC
I was changing phones.

created plaintext backup on old phone.
installed Signal on new phone and imported backup.
All is good except group chats, they dont have icon and name - all are "unnamed group".
What can I do to get my group chats names and icons back?
I use signal on one android and two desktops. This was the first time I changed phones since using Signal, so maybe I am missing something..
Thanks

**Comment by username11236** [comment] 2017-10-31 12:02
Im sorry for bumping this.

There is currently no way to migrate signal to a new phone appart from rooting both phones and using titanium backup. (or similar)
Turn off internet and create full backup of signal. Copy backup dir to new phone. install signal, do not start it. restore signal app data. done!

duplicate of #1619 and others

**Comment by urza** [comment] 2017-10-31 13:01
My old phone is rooted but not the new one (galaxy s8).

Is there at least some way how to add name picture and colour to each group manually on new phone? I can't  find any way to edit this..

**Comment by wizardofid** [comment] 2017-10-31 13:08
I think corresponding groupname and avatar should be updated (in your case: set) as soon as you are receiving a message in a group.

**Comment by tecknicaltom** [comment] 2017-11-01 20:58
Dupe of #6720

**Comment by xyzzyxw** [comment] 2017-11-09 09:11
At least a while ago, as a workaround, someone in the group who still has the group name etc could edit the group details, possible without changing anything. This would update the group and make the name visible again.

As pointed out by others, this is a consequence of the broken/minimalistic backup functionality.

**Comment by kaihsutai** [comment] 2018-01-01 19:42
The backup is not writing out group conversations in my Android client.

**Comment by 2-4601** [comment] 2018-01-27 20:47
Closing as duplicate of the issues mentioned above.

**Closed by 2-4601** 2018-01-27 20:47 UTC
