### ISSUE TITLE
Update available notification does not work

### ISSUE THREAD

**Issue by wheybags** [signalapp/Signal-Android#8433] opened 2018-12-10 15:50 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I am using the standalone apk version from https://signal.org/android/apk/ on a lineageos phone with no google apps/play store.
When I get a notification about a new version of signal, tapping the notification does nothing, and just dumps me back on the previous screen

### Steps to reproduce
- Install signal
- get prompted to update
- tap prompt, nothoing happens

### Screenshots

![ezgif-2-37e1103a2a38](https://user-images.githubusercontent.com/1093274/49743484-2672fa80-fc9b-11e8-8fcf-43b86fcf37d8.gif)

### Device info

**Device:** Oneplus 3T
**Android version:** 8.1.0 / lineageos 15.1-20181111-NIGHTLY-oneplus3
**Signal version:** 4.30.7

### Link to debug log

https://debuglogs.org/44389d47b3c51412b44624c6f4c5af0ce92cc079b2477273d9c210e9d2e56c98

**Comment by greyson-signal** [comment] 2018-12-15 01:17
Duplicate of #7936 (although I very much appreciate the gif!)

**Closed by greyson-signal** 2018-12-15 01:17 UTC
