### ISSUE TITLE
Sending SMS via Google Now voice comand bypasses TextSecure

### ISSUE THREAD

**Issue by tin-can-zz** [signalapp/Signal-Android#218] opened 2013-06-26 18:51 UTC
I like being able to send SMS messages via the Google Now voice option on my Galaxy S3; however, when I do this, the messaging app that came with the S3 is being used to send the messages instead of TextSecure.

At first I thought this was because TextSecure was locked, but after entering the passphrase and leaving TextSecure unlocked, it still does not work with Google Now.

**Comment by rhodey** [comment] 2015-03-25 00:45
`OK Google, send a text message to <contact name>` on my Nexus 5 running stock Android Lollipop 5.1 brings up what appears to be the quick compose dialog of the default `Messenger` app. I wonder if TextSecure will show up when we add support for quick compose?

**Comment by anisse** [comment] 2015-04-29 14:44
Just to add some details: a voice command (android wear/google voice commands/now…) will write a message in the SMS database (readable in hangouts for example), but TextSecure doesn't seem to watch the sms database for new messages, or use it at all (there should be an option to export "unsafe" messages to the SMS database when you switch away from textsecure).

**Comment by maxauvy** [comment] 2015-05-05 06:51
I can confirm this behavior, it was already the case with Android 5.0.2 and Android Wear 5.0.2. If I launch a vocal command to the phone or to the watch, SMS will be sent unencrypted via the default SMS App, even if there's a secured conversation available in TextSecure. Still valid with Android 5.1.1 (CM12.1 in my case).

And yes, TextSecure doesn't "see" this SMS, but you can still import it from the system DB via the import/export submenu!

Also @anisse you can do a "plain text export" with TextSecure and import it to the system database with an app like SMS Backup and Restore, if needed ;)

**Comment by anisse** [comment] 2015-05-05 12:38
@maxauvy : I'm not sure using another app to do the job counts as a feature; it's also awful UX, making it hard to move away from TS; but that's the subject for another bug.

The problem is that you can't use the import submenu to just stay sync: there will just be duplicate messages, as stated in the warning box.
Also, you shouldn't have to keep importing messages just because some other app sent an sms (in this case the Wear/Google app); those messages should automatically appear in the correct conversation so you follow when people answer you.

**Comment by joepetrakovich** [comment] 2015-10-29 17:12
@maxauvy this issue occurs even if TextSecure is the default SMS app.  I can confirm this behavior on a Nexus 6P.

**Comment by vinilox** [comment] 2015-11-21 21:44
Everybody are suggesting that a "android sms DB watcher" is implemented to automatically import new sms send via third party apps like Google now. Right ?
Is this possible to do @mcginty @moxie0 ?
Thanks for your answer. :)

**Comment by castanley** [comment] 2016-01-14 20:10
I too am having this issue. Would love this to be resolved!

**Comment by pjedge** [comment] 2016-02-27 19:19
venturebeat.com/2015/07/28/android-users-can-now-say-ok-google-to-send-messages-via-whatsapp-wechat-nextplus-telegram-and-viber

It appears that apps such as telegram, whatsapp, and more now support sending via Google now. Would it be hard to implement the same -- "okay google, send a signal message to XXXXX?"

**Comment by cascheberg** [comment] 2016-03-04 05:31
@pjedge From reading the article that you linked I understand that the feature requires support by Google for each app. So it cannot be implemented in Signal without Googles support.

**Comment by gooddadmike** [comment] 2017-05-03 07:19
So what does it take to get Googles Support?

**Comment by joeykrim** [comment] 2017-05-04 06:32
The last question seems to be whether it's possible to have voice interactions exposed to an application without Google's explicit support.
On a Google Pixel XL, the voice command "Send a text message" defaults to the Android Messenger application and ignores Signal, even when Signal is marked as the default application. In addition, "Sent a text message with WhatsApp" works, but "Sent a text message with Signal" results in a web search.

Google has listed some voice interactions that are available, but they don't explicitly list sending a text message/SMS, as a possible voice interaction: https://developers.google.com/voice-actions/system/.

After quickly going through their Codelab tutorial (http://io2015codelabs.appspot.com/codelabs/voice-interaction#1), I don't see how to bind to the initial and specific voice command "Send a text message". The codelab example does show how to handle the intent(responding via voice and confirming action completed) after Google passes the intent to the application from the voice command.

**Comment by jszaszvari** [comment] 2017-05-17 10:28
With the newly released google assistant SDK this should be possible now. Something like " send a signal to bob saying I'll be home in 5 mins"

**Comment by automated-signal** [comment] 2018-04-02 21:18
GitHub Issue Cleanup:
See #7598 for more information.

**Closed as completed by automated-signal** 2018-04-02 21:18 UTC
