### ISSUE TITLE
4.20.4 is destroying my battery

### ISSUE THREAD

**Issue by kpuljek** [signalapp/Signal-Android#7839] opened 2018-05-24 13:26 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

Since the update to 4.20.4, signal is constantly active in the background and is using a lot of battery. Never before have I seen such a huge usage, it's first on the list with 20% right now.

### Steps to reproduce
- updated to 4.20.4
- i made a short call in the morning, messaged as usual
- 3 hours later my battery is at 35% down from a full charge, signal in the first place, it's usually not even on the list

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

Battery quickly drained with signals "usage in the background" being the same as the time since i unplugged the charger

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

Battery usage like before

### Device info

**Device:** OnePlus 3T
**Android version:** 8.0
**Signal version:** 4.20.4

**Comment by kpuljek** [comment] 2018-05-24 15:33
Finally made it to the charger, upon plugging in the phone started heating and continued to do so until I force closed the Signal process. When I restart it, it starts heating again. I'd love to submit more/any useful info, just let me know. I skipped sending logs because this looks like something that wouldn't end up in there.

**Comment by cascheberg** [comment] 2018-05-24 16:38
I am currently experiencing a major performance regression in the current beta release 4.20.4 (Moto G5S, Android 7.1.1). It gets worse while the app is open. When the app is open for just some seconds, even typing a message is lagging.
Could this be related?

**Comment by kpuljek** [comment] 2018-05-24 17:32
@cascheberg could be related, my phone also stutters a bit more so Signal's probably doing something in the background that's using cpu cycles and draining the battery.

**Comment by dineshdevarapally** [comment] 2018-05-24 19:41
This is because the app is allowing all the CPUs to run the programs in the back end.

**Comment by Slomo17** [comment] 2018-05-25 08:10
Same issue here

**Comment by 0xnor0** [comment] 2018-05-25 09:01
same issue here, the app is extremely jerky, normal typing is almost impossible

**Comment by kpuljek** [comment] 2018-05-25 09:04
@0xnor0 @cascheberg then maybe it's not related, while I do feel some overall performance losses, I can use the application and type just fine, it's just using ridiculous amounts of battery and overheating my phone. It's doing something in the background, but I wouldn't say it's that degrading to performance. I noticed the stutters once I noticed the battery usage and heating, I don't think I would pay too much attention or notice them otherwise.

**Comment by 0xnor0** [comment] 2018-05-25 09:08
@kpuljek my OP5 isn't heating, but the overall performance is very bad, closing or opening other apps is very very slow. A restart didn't help, only the hard close of the app brings the performance of the phone back.

**Comment by kpuljek** [comment] 2018-05-25 09:12
@0xnor0 no battery drain? if not, that sounds like a separate issue. Yesterday it ended up using 24% by idling in the background. I actively used pocket casts for 5 hours and streamed the podcasts using LTE and that only used 10%
 
![screenshot_20180524-173429](https://user-images.githubusercontent.com/9851336/40536419-57a42920-600c-11e8-92a0-3009ddf8495c.jpg)

**Comment by 0xnor0** [comment] 2018-05-25 09:16
@kpuljek yes there's battery drain too. but i would say there's no temp change in normal use.

**Comment by kpuljek** [comment] 2018-05-25 09:20
@0xnor0 my phone gets hot as hell, especially if i'm charging it while signal's doing its thing. if i force close it, the phone cools down to the usual temperatures. maybe OP5 handles the load a bit better so it heats less than my op3t, who knows.

**Comment by bme13** [comment] 2018-05-25 09:30
Hi, Also running 4.20.4 however I don't have this issue but it reminds me of an old performance issue (7016) where I was instructed to provide a system trace. I'm not sure if it's useful for this situation and I guess the device needs to be rooted for that however it might give the developers something to work with. [Here's](https://github.com/signalapp/Signal-Android/issues/7016#issuecomment-334915227) how I've created the requested info back then.

**Comment by cascheberg** [comment] 2018-05-25 11:06
My performance issue was gone after I enabled system emoji. I wonder if that also reduces battery usage back to normal? Otherwise we should treat these as separate issues.

**Comment by 0xnor0** [comment] 2018-05-25 11:41
Enabling system emoji stops the stutter on my phone, i will observe the battery life now

**Comment by 0xnor0** [comment] 2018-05-26 07:42
@kpuljek @cascheberg for now signal is nearly unusable on my OP5. If i force to close the app and reopen it again, all works fine until i type and send a message. after that, the app stutters, the view of the message window ist very very slow and it looks like the app does some work in the background.

**Comment by CaptainBalou** [comment] 2018-05-26 14:33
Working with Signal 4.20.4 on a Samsung S7 and see the fast battery draining as well. I had 36% two hours before and now my phone switched off because battery was empty. Samsung's battery status states that Signal is using 48% of all together.

I now read that some had better performance with using system emoji. I switched some minutes ago and will observe if somethin changes.

**Comment by 0xnor0** [comment] 2018-05-26 18:02
With activated energy saving mode the problem is gone, everything is smooth again. 
While the display used 11% of my battery, Singnal took 16%...

**Comment by rachanon2116** [comment] 2018-05-26 18:04
เมื่อ 27 พ.ค. 2018 01:02 น. "0xnor0" <notifications@github.com> เขียนว่า

With activated energy saving mode the problem is gone, everything is smooth
again.
While the display used 11% of my battery, Singnal took 16%...

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/signalapp/Signal-Android/issues/7839#issuecomment-392277891>,
or mute the thread

**Comment by london52** [comment] 2018-05-26 18:29
I keep losing Wi-Fi

**Comment by london52** [comment] 2018-05-26 18:30
I keep losing Wi-Fi

**Comment by CaptainBalou** [comment] 2018-05-26 19:59
Energy saving mode didn't solved it for me. Using system emojis improved the most.
Nevertheless, while 'Android System' used 38%, Signal used 61% even I didn't wrote more then 3 lines today. So I think it's still a strange behavior.

**Comment by bme13** [comment] 2018-05-27 08:51
Also running Signal version 4.20.4 and had the situation where Signal became very slow. Switching to system emoji immediately resolved it. I don't know if needed, but before I switched to the system emoji I've first created a logfile and a trace. After switching to system emoji I also created a logfile and a trace. 
Here's the data.
**Logfile when Signal was lagging:**  https://debuglogs.org/4dfa150ee51493998a13168859b13fff44e1d60db544675f00fd7a0fac34a1fa
**Logfile after switching to system emoji and Signal became normal again:** https://debuglogs.org/395f34b7d3b03b25a720d5091e9ced426140fd61d33cc3ca921b0d3cadf54f15
**Tracefile where the first trace was made when Signal was lagging (09:27:26) and the second trace was made after switching to system emoji and Signal was behaving normal again. (09:38:06)**: 
[traces_signal_20180527.txt](https://github.com/signalapp/Signal-Android/files/2042382/traces_signal_20180527.txt)

**Comment by a9e78rauijasdf** [comment] 2018-05-27 13:36
I have the same kinds of problems on my OP5. Typing lags A LOT - started happening yesterday i believe. Restarts has been tried.

Im not sure if its related - but i also see that messages dont arrive until i actively open Signal - i have no battery optimization apps installed, and system battery optimizer is disabled for Signal - hoping that it would solve issues.

Im on VPN as well - im disabling the VPN for now to see if it helps.

Signal app is using ~660MB. how about you guys - might it be a size thing?

From the debug logI can see some TLS errors with your amazon server - maybe its squishy?

I've tried to message myself the link to the debuglog, but the message doesnt show up in the desktop app. Another issue? :(

**Comment by jeffbl** [comment] 2018-05-27 15:04
Seeing massive (45%) battery use as well on 4.20.4. Essential PH-1 running Android 8.1.0.

**Comment by kpuljek** [comment] 2018-05-28 12:11
I kept Signal force closed for the last few days, but now I need it again so I tried disabling system emoji and so far it didn't come up on the battery usage screen. I'll try reenabling them when I get near to a power source

**Comment by PiCob** [comment] 2018-05-28 20:54
I have Signal v4.20.4 running since it came out on the beta channel, but a few minutes ago I experienced that above mentioned laggy behavior for the first time (on my Moto G4 Plus, stock Android 7.0). To give an impression of the impact (never seen something like that in any other app):

![signal-2018-05-28-224346](https://user-images.githubusercontent.com/23237468/40629230-15420a64-62ca-11e8-96e2-cde0bb8e9339.jpg)


FWIW, here's a debug log:
https://debuglogs.org/47be128235ea379ec872135d07cbd6c8b325353cd8a88c1e64d317916e2ba922

**Comment by greyson-signal** [comment] 2018-05-28 21:39
Hello everyone, thank you all for detailing your experiences and providing information! I've been able to reproduce the emoji performance issues present in 4.20.4, and I can confirm that ceafb0d130910a9742ba510defa1afe2be095f8c fixes it. This will be released in 4.20.5.

While it's odd to me that this performance issue could have such a large impact on battery drain, anecdotally these two do seem to be linked. For that reason, I'm going to close this issue for now. If anyone is experiencing battery issues afterwards, please open a separate ticket and we'll dive into it.

Thank you!

**Closed by greyson-signal** 2018-05-28 21:39 UTC
Labels: performance

**Comment by PiCob** [comment] 2018-05-29 05:01
Thanks! May I suggest to rename the issue in order to reflect the performance issue (lagging) a bit more? That would help reducing duplicates (for example, #7857 sounds related to this one as well)
