### ISSUE TITLE
Signal always resets to main screen after leaving the app

### ISSUE THREAD

**Issue by Tursko** [signalapp/Signal-Android#9261] opened 2019-12-08 22:58 UTC
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal doesn't respect your last location inside the app. 

### Steps to reproduce
- open a thread
- leave the app (go to home screen, go to a different app etc).
- reopen signal using icon

**Actual result:** It always brings you back to the main screen where are the threads are located
**Expected result:** It should remember the exact thread you were inside. (the iOS app does this).

### Device info

**Device:** Google Pixel 4
**Android version:** 10
**Signal version:** 4.50.6

### Link to debug log
https://debuglogs.org/d475f0c10986a32332d241154577b229dac0673c8d9f96d7a4b3843ace46568b

**Comment by alternativesurfer** [comment] 2019-12-09 20:37
Other observed behavior.

If I go to desktop, open another app, go to desktop again, then re-open Signal from the app icon I am brought to the main screen in Signal.

If I then navigate back to desktop, then switch back to Signal using the app switcher, I am brought to the original thread within the app that I was in.

@Tursko Can you get back to the original thread using the app switcher, instead of relaunching Signal from the app icon?

(I confirmed this behaviour on a Pixel 1 and Pixel 4).

**Comment by Tursko** [comment] 2019-12-10 02:01
> If I then navigate back to desktop, then switch back to Signal using the app switcher, I am brought to the original thread within the app that I was in.

Good catch. If I go back using the app switcher then it holds my thread. If I click on the app icon it always goes back to the main Signal screen.

**Comment by Meteor0id** [comment] 2019-12-13 22:16
I thought this was by design, and I actually love that Signal goes back to the main screen instead of 'remembering' the last thread I had open. I want to be able to open Signal without wondering what will appear prominently on my screen when I do so, because others around me might also see that. Furthermore it saves me thr time of leaving a conversation to see if there had been activity in other conversations. I also oike that i do not get confronted (distracted) with a conversation which was not currently on my mind. And finally, it prevents me from unintentionally marking messages as reaf and thus aknowledge to someone that I had time to open Signal.

I like the cutrent behavior, and don't think 'remembering' the thread I was in is worth not having those benefits.

I don't think this is a bug in existing functionality, but rather a feature request for a featire which I personally rather not see in Signal. Feature requests belong on the community forum where they can be discussed, not on GitHub. https://community.signalusers.org/

**Comment by Tursko** [comment] 2019-12-14 18:36
> I thought this was by design, and I actually love that Signal goes back to the main screen instead of 'remembering' the last thread I had open. I want to be able to open Signal without wondering what will appear prominently on my screen when I do so, because others around me might also see that. Furthermore it saves me thr time of leaving a conversation to see if there had been activity in other conversations. I also oike that i do not get confronted (distracted) with a conversation which was not currently on my mind. And finally, it prevents me from unintentionally marking messages as reaf and thus aknowledge to someone that I had time to open Signal.
> 
> I like the cutrent behavior, and don't think 'remembering' the thread I was in is worth not having those benefits.
> 
> I don't think this is a bug in existing functionality, but rather a feature request for a featire which I personally rather not see in Signal. Feature requests belong on the community forum where they can be discussed, not on GitHub. https://community.signalusers.org/

The iOS app does not do this and if you use the app switcher it does hold your position.

**Comment by Meteor0id** [comment] 2019-12-14 21:55
That is inconsistent and I agree the iOS and Android app should be consistent in whether or not the previous state is preserved.

But since both preserving and not preserving have their value and this decicion impacts privacy of the app user, maybe this one warrents a switch in preferences.

I also use WhatsApp, and I thought myself to always exit any conversation before closing the app. I am glad I don't need to mind that in Signal.

**Comment by Tursko** [comment] 2021-01-13 20:29
This was solved in 5.1.x.

Thanks!

**Closed** 2021-01-13 20:41 UTC

**Comment by Meteor0id** [comment] 2021-01-13 21:07
This is sad, it was a useful privacy feature to open on the main screen rather than within a conversation. This should have been a user preference.
