### ISSUE TITLE
No push notifications when closed

### ISSUE THREAD

**Issue by deremuTVCode** [signalapp/Signal-Android#9806] opened 2020-06-29 17:30 UTC
When signal is closed i dont get push notifications.

**Comment by Nisc3d** [comment] 2020-06-29 20:55
Please check all the steps in this guide: https://support.signal.org/hc/en-us/articles/360007318711-Troubleshooting-Notifications

**Comment by greyson-signal** [comment] 2020-06-30 04:09
Closing as a duplicate of #8692

**Closed by greyson-signal** 2020-06-30 04:09 UTC
