### ISSUE TITLE
Calls don't ring - show up as missed calls

### ISSUE THREAD

**Issue by Maximus778** [signalapp/Signal-Android#8302] opened 2018-10-24 20:20 UTC
- [x ] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I have been using Signal since it came out and find it to be very useful with great voice quality. However in the last few months, when I call another signal user, they don't hear the call ring and only get a missed call notification

1) This is happening with users in the US, where there was no issue previously. Since it is in the US, it is not a firewall issue
2) On both ends, the app has permissions to mic and camera
3) There is a super-strong wifi connection on both ends and whatsapp, Skype and wire calls ring and connect effortlessly

This is now happening with 100% of calls being placed with signal, effectively making signal useless to make voice calls. Can you please look into this and fix it urgently

Thanks

### Steps to reproduce
Am able to reproduce this 100% of the times now. Earlier would happen 50% of the time

- This is not related to clock syncing. Both devices have the exact same time and all other calling apps such as Wire, WhatsApp and Skype work perfectly

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Pixel 2
**Android version:** 9
**Signal version:** 4.29.5

**Comment by greyson-signal** [comment] 2018-10-25 19:58
This is something where I very much need debug logs from both devices, as I'm unable to repro on any of my devices.

**Comment by omd10** [comment] 2018-10-30 08:55
I can confirm the issue. Even when it is working it takes longer time to connect than other messengers. Cannot reproduce the issue on 100%. On one of the devices the situation was improved by manually adjusting the clock and reinstalling Signal on the other. Before that I was observing notification without ring and no ringing with screen off. Log before that adjustment: 
https://debuglogs.org/caa881e9e1789d0beb42acdb1b4383001f007ab2fe555d9b2341f9565124c773
And after:
https://debuglogs.org/5c1c590d60fc3054a2a38f5440f2867c0382822951e5d48d3a1b6f289954cbf0

The other device before:
https://debuglogs.org/a07b722b2e98e547e966855ccca0cbb261ccbdd5bd635944bfddf4a6e4c48bc9
And after:
https://debuglogs.org/81c4e423cb4c612eccb31338a6ae3a3a91946a1296bb0228e917eabb0e34608d

**Comment by omd10** [comment] 2018-10-30 09:03
If you need other tests let me know.

**Comment by Maximus778** [comment] 2018-10-31 06:41
This is an issue which a number of tickets on Github have mentioned for 12 months now. Here's a thread with debug logs
https://github.com/signalapp/Signal-Android/issues/8302#issuecomment-434219763
Would appreciate your help with fixing this
Thanks

    On Thursday, October 25, 2018, 3:58:28 PM EDT, Greyson Parrelli <notifications@github.com> wrote:  
 
 
This is something where I very much need debug logs from both devices, as I'm unable to repro on any of my devices.

**Comment by omd10** [comment] 2018-10-31 08:21
This maybe related or a separate issue, but when DND is activated and then deactivated calls stop ringing or vibrating. Witelisting the app to notify during DND does not help for call notifications, killing the app and clearing cache too. Sound and vibrations work start working after a reboot. Messaging notifications are not afected.

**Comment by mattimac** [comment] 2018-11-02 21:15
@omd10 @Maximus778 
are you calling from LTE or other ipv6 network or not? Is is proven to give similar issues as you describe.

**Comment by omd10** [comment] 2018-11-03 08:32
@mattimac 
The issue is observed on wifi too. The strange think is that if I lift the phone ambient display ia showing phone with lock icon, nothing happens if i dont wake up the screen no free signal on the other side just trying to connect. If i wake up the screen then i see the incomming call comming and sometimes it rings sometimes not. The application is excluded from all battery optimisations. Easiest way to reproduce is by not using the app for long time although it happens randomly. Only call notifications are affected. Fresh log, last call is with the issue:
https://debuglogs.org/320847d8ed044e5b7c93c6b0feacb0164c4d6a0f30ef88758da4bed1eafdddde
The other phone:
https://debuglogs.org/a3bb83ada69ff158d02377120e5806c573207e1636f0f0e4fb95818fa6d1fbac

**Comment by omd10** [comment] 2018-11-03 08:36
This is the only real issue I see with the app, although message delivery is slow compared to others. Still keeping telegram just because of that.

**Comment by ghosted17** [comment] 2018-11-04 07:32
This is happening me and a friends phone too. It was working fine. Now calls just show up. I see connecting in notification bar when trying to receive a call. Wifi calling is off on both phones

**Comment by ozgurakyazi** [comment] 2018-11-04 22:13
Since I have the same problem, I am willing to contribute. Please let me know if a test needed.

**Comment by jl91569** [comment] 2018-11-06 04:49
I'm also having the same issue, but I noticed that the incoming call screen appears if the recipient attempts to call the sender at the same time, although it still gets stuck attempting to connect if the recipient tries to answer the call.

**Comment by ghosted17** [comment] 2018-11-06 07:01
Disabling through signal servers doesn't work for us. Voice calls totally don't work atm and i think messages are also buggy laggy. Is there an alternative to use for calls now? I tried latest and I'm on latest beta

**Comment by todoesUno** [comment] 2018-11-06 21:20
I think this is the same issue: https://github.com/signalapp/Signal-Android/issues/7733

**Comment by Maximus778** [comment] 2018-11-08 22:20
It's clear that this is a common and long-standing issue with Signal. On top of that, this is a core functionality and not a tertiary refinement. I end up using WhatsApp for voicecalls though I would strongly prefer Signal specifically due to this issue.

What can we do to fix this?

Thanks

**Comment by ghosted17** [comment] 2018-11-09 02:10
I ended up using wire and have to say I'm liking it as much as signal

**Comment by mattimac** [comment] 2018-11-09 09:41
> What can we do to fix this?
> 
> Thanks
@Maximus778 @ghosted17 
If you have some time and access to two devices, best would be with LTE that you can switch between ipv6 and ipv4. I think best we can do is perform several tests and submit the logs according to the
https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports

**Comment by dorakas** [comment] 2018-11-11 21:13
same here. calls don't get established. it pings on the one phone and show notification on the other but never rings. if you click the notification it shows call screen but the call doesn't make it.

**Comment by greyson-signal** [comment] 2018-11-12 05:18
@Maximus778 Just wanted to chime in to clarify why this is difficult, so you don't feel like I'm ignoring this. First, I don't want you to think that calling is broken for all users or anything -- these appear to be exceptional cases we're looking at that seem to arise from specific device configurations. I have 10 Android devices on my desk right now, and sadly I'm unable to reproduce this issue on any of them.

Across a couple tickets, possible explanations vary from VPNs, IPv4 vs IPv6, mismatched device clocks, and notification issues.

What would be great to have from you, since your calls fail 100% of the time, is a debug log. Specifically, just make a single call from your device, and after it fails, capture a debug log and save the URL. Then, request a debug log from the person you called. Then, post both of those links here and label which was the sender and which was the receiver. That'd help a lot with debugging your specific problem.

**Comment by mattimac** [comment] 2018-11-12 09:30
@greyson-signal what i would try to test with would be:
- make sure the call receiving device has the screen off, app is not whitelisted in the battery optimization etc
- make sure you run signal 4.29.7 on android
- try with the receiving device on LTE/ calling device on LTE / both LTE/ both Wifi (best would be different ISPs and public adresses) 
- experiment with ipv4 only, ipv6 only and dual stack if possible)
- experiment with "always relay calls" - for me it seems that enabling this increased the possibility of failing the call, but the issue is there when this is disabled as well

**Comment by greyson-signal** [comment] 2018-11-12 21:54
@torlarse 
> Is there any risk in posting an unedited log?

Generally no, but it depends on your information-sharing threshold. Things like phone numbers are automatically stripped from the logs, and we never log anything like message contents. Basically the log tells us what _types_ of things were happening. For example, the log will say that a message was sent, but it won't say what who it was sent to or what it said. Hope that helps.

**Comment by Booteille** [comment] 2018-11-15 13:30
I have this issue too with at least two of my contacts. I'll try to grab some logs ASAP.

**Comment by mnns** [comment] 2018-11-15 17:09
Me and my friends get this exact same bug, it is almost a constant now. Suddenly, no rings, no notifications, on separate phones, different everything. We are out of US so it is not a matter of firewall. All other apps work just fine.

**Comment by Xashyar** [comment] 2018-12-04 11:43
@greyson-signal 
Received 5 Missed Calls from an iOS Device with no Ringing:

Android **4.32.3** (Call Receiver):
https://debuglogs.org/2693bf057f25f4e3edd3b64a8e78d8d1696897c3c464560d486fb933460aa53d

iOS **2.32.0.19** (Caller):
https://debuglogs.org/4286b413429be3039817ef1ebccd6ebee175f84945508e91c55e1b9e9547062f.zip

Calls are received normally when you try vice versa (Calling from Android)

**Comment by Maximus778** [comment] 2018-12-04 20:50
I have found that if I send a text message first to the person I want to call, wait for the text message to be delivered, the call rings always through.
This clearly shows some manner of server time out by Signal. 

Sending the text message forces the Signal app to reestablish connection with the server. I hope that the Signal developers can use this workaround hack to fix the issue
Thanks

    On Tuesday, December 4, 2018, 6:44:01 AM EST, Xashyar <notifications@github.com> wrote:  
 
 
@greyson-signal
Received 5 Missed Calls from an iOS Device with no Ringing:

Android 4.32.3 (Call Receiver):
https://debuglogs.org/2693bf057f25f4e3edd3b64a8e78d8d1696897c3c464560d486fb933460aa53d

iOS 2.32.0.19 (Caller):
https://debuglogs.org/4286b413429be3039817ef1ebccd6ebee175f84945508e91c55e1b9e9547062f.zip

Calls are received normally when you try vice versa (Calling from Android)

**Comment by szotsaki** [comment] 2018-12-30 09:07
This ticket is a duplicate of #7733.

Please, close this bug and comment on the other one to have all the necessary information in one place. Thank you!

**Comment by usergoodvery** [comment] 2019-07-09 14:05
Signal folks this issue and #7733 are most likely related to some logical bug in how you set  IceTransportsType.RELAY for PeerConnection configuration as in https://github.com/signalapp/Signal-Android/blob/e603162ee767d56fa16f56701cd29010f22ed22d/src/org/thoughtcrime/securesms/webrtc/PeerConnectionWrapper.java#L72

Since you are automatically forcing non system contacts on the TURN path (perhaps being bit over protective?) as per https://github.com/signalapp/Signal-Android/blob/84fd1a9140e15a3f02bec6a2803d26223acc44a3/src/org/thoughtcrime/securesms/service/WebRtcCallService.java#L389 (suspect very few users turn this option on by default) your TURN servers are properly overloaded and users are getting random success rate with their webrtc connections, because system-contact vs non-system-contact is random and highly localised to each user.

The remote peer won't be trickling ICE candidates back, and onIceConnectionChange won't evolve out of the CHECKING state forcing a timeout and users seeing missed call note.

**Comment by AdelKS** [comment] 2020-01-14 15:31
Hello,

I am experiencing the same problem, receiving missed calls without the phone having rung (around 70% of the time). And maybe it's related: long wait before the phone of the person I am calling starts ringing, if it rings. I can join debug logs if needed.

Thank you and good luck!

**Comment by Nnidyu** [comment] 2020-02-25 09:45
I have an identical problem on 4.55.8. Calls do not ring and I only see a "Missed call" notification.

**Comment by deBugger-** [comment] 2020-04-03 17:19
Same on Samsung S4 Telekom  "Missed call" only msg.

**Comment by magician11** [comment] 2020-04-14 01:31
I, and 2 friends that have the same issue. It's tricky to debug, because the issue is intermittent. Sometimes it'll ring, and sometimes it won't and we'll just see a missed call. Sometimes a notification will pop up saying a new Signal call is coming in, but it won't ring.

These issue seems to occur independently of the functionality of battery saver mode, or "do not disturb" mode.

**Comment by szotsaki** [comment] 2020-05-18 05:42
This is most likely a duplicate of https://github.com/signalapp/Signal-Android/issues/7733 or https://github.com/signalapp/Signal-Android/issues/9633. Could you please close this one in favour of them? Thank you.

**Comment by samuelowino** [comment] 2020-05-18 19:49
@greyson-signal have you or other collaborators had any luck with this issue, or could it be a webrtc bug

**Comment by capitolfrills** [comment] 2020-11-04 19:48
@greyson-signal I have been experiencing a similar issue for at least half a year. Incoming Signal calls used to work fine for me, but now when I am receiving incoming calls, I can hear the call ringing, but no notification box and the phone screen does not change to enable me to answer the call. If I open Signal, open a message and select the call icon only then does the incoming call screen appear and allow me to answer the call. This issue is reproduceable for me and happens with every incoming call, whether on wifi or network. 

**Device info**

Device: OnePlus 7
OS: Oxygen OS 10.3.4.GM21AA
Signal version: 4.75.4

**Comment by szotsaki** [comment] 2020-11-05 10:07
Please, append your bug report and log into either #7733 or #9633 depending on the type of the issue.

@Maximus778: could you please be so kind and close this ticket as a duplicate?

**Comment by attila-lendvai** [comment] 2022-01-27 16:53
yes, it is.

it's part of my regular habit to send a chat or two to my peers (to wake up their phone?), see when it gets delivered, and only when it gets delivered do i start ringing them. otherwise the call gets through much less reliably, and it takes from seconds to minutes until it actually starts ringing, if at all.

eliminating the auditory clue that the other side is not ringing yet was a mayor drop of UX for me, and frankly, i still can't understand why it was removed.

**Comment by dsvk** [comment] 2022-02-01 00:10
Duplicate of https://github.com/signalapp/Signal-Android/issues/7733 (that one has the most traction) + https://github.com/signalapp/signal-android/issues/8780 + https://github.com/signalapp/Signal-Android/issues/9813.

**Comment by jknockaert** [comment] 2022-02-01 09:17
I think Signal is not properly using a call API and as a result Android cannot know a call is coming in; see #11512.

**Comment by cody-signal** [comment] 2022-03-08 20:08
Try on 5.33 where we've integrated with the Android telecom system, and made some changes to how we ring. Please post an updated debuglog if you try with that version and still encounter problems.

**Closed** 2022-05-15 07:36 UTC
Labels: calling, wontfix
