### ISSUE TITLE
Downloading an image that has been sent makes the photo's date some time in the year 52000

### ISSUE THREAD

**Issue by josphh** [signalapp/Signal-Android#10386] opened 2021-01-08 23:16 UTC
![Screenshot_20210108-231635_Gallery.jpg](https://user-images.githubusercontent.com/28985840/104074273-9439d980-5207-11eb-928b-822a7a6dd296.jpg)

**Comment by Nisc3d** [comment] 2021-01-09 01:02
I think this is a duplicate of #10142.

**Closed** 2021-01-09 15:24 UTC
