### ISSUE TITLE
Microphone doesn't work on video calls and audio calls with speaker

### ISSUE THREAD

**Issue by michelesr** [signalapp/Signal-Android#13423] opened 2024-02-14 08:47 UTC
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Since last week, when making a video call or a call with the speaker, the other part can't hear my voice. The microphone permission is granted and the Android icon that notifies microphone activity is displayed.

### Steps to reproduce
- make a video call OR make a phone call and activate speaker
- try to talk or make some sound

**Actual result:** The other part doesn't hear the produced sound
**Expected result:** The other part hears the sound

### Device info

**Device:** OnePlus 6T 
**Android version:** 13 (Lineage OS 20-20240213-NIGHTLY-fajita)
**Signal version:** 6.46.7

### Link to debug log
[Link](https://debuglogs.org/android/6.46.7/d1a85ce462e4dfc0a03cdd5784e7e80cbfc5e6cb4d11758ac4d65b52cd7bdbbf)

**Comment by Captain-Sandwich** [comment] 2024-03-11 14:42
I have the same problem on OnePlus 6 (enchilada)
Android version: 14 (LineageOS 21-20240306-NIGHTLY-enchilada)
Signal version: 7.0.2

I am working on generating a debug log, but also had the problem on lineage 20 and only upgraded to 21 because of the issue.

**Comment by HyknuF** [comment] 2024-03-25 08:03
Same problem:  OnePlus 6
Android version: 14 (LineageOS 21-20240313-NIGHTLY-enchilada)
Molly / Molly UP 7.1.3-1  (both Versions same issue)

I also had the problem on lineage 20

**Comment by lightweight** [comment] 2024-04-02 00:39
I've got the same issue with Lineage 20 on fajita (OnePlus 6T)...

**Comment by rymiel** [comment] 2024-04-15 01:13
I have the same issue on a Pixel 6 with Android 14. Just seems weird that everyone else with this issue seems to have a different phone than me

**Comment by T-Mike** [comment] 2024-04-16 20:43
I experience the same problem with a OnePlus 6 (A6003) with Lineage 20.
This bug also happens when plugging headphones.

**Comment by Niyphelah** [comment] 2024-04-17 19:45
Same issue on a Moto G7 Plus with LinegageOS 21 + MicroG. I am able to record voice notes & play them back without issue. I do also have the same issue with Telegram -- so I think this issue is related to LineageOS and not Signal itself.

**Comment by Captain-Sandwich** [comment] 2024-04-21 05:45
I reported the issue for OnePlus 6 as well on the lineage issue tracker and we already have a fix merged: https://review.lineageos.org/c/LineageOS/android_device_oneplus_sdm845-common/+/390109

It should be in the next build on April 24. I am going to report back if it fixes the issue.

**Comment by michelesr** [comment] 2024-04-21 22:12
I've tried the proposed fix by manually editing `build.prop` in my OnePlus 6T and it works fine.

**Comment by Captain-Sandwich** [comment] 2024-05-01 06:36
The new lineage build fixed the issue on enchilada/OnePlus 6.
I guess this can be closed

**Closed** 2024-05-01 07:49 UTC

**Comment by Forage** [comment] 2024-05-06 12:25
I can confirm that the 5 may build of lineageos4microg, which includes the mentioned fix, works as well. My OnePlus 6 can be used on speaker again.
