### ISSUE TITLE
Push notifications / Play Services detection with microG broken since face blur update

### ISSUE THREAD

**Issue by quirk46** [signalapp/Signal-Android#9702] opened 2020-06-06 00:11 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Push notifications when using microG in place of Google's Play Services, which was working perfectly previously, is now broken since the face blur update. I believe this is due to the addition and/or update of relevant Google Firebase libraries, for example https://github.com/signalapp/Signal-Android/commit/c8dd4e5254c0771b2a1925df408ed9d360c68f84#diff-39e7d8c00954e920b98e7636f0ac30b2R287. It's possible that the upgrade or addition of the ML libraries changed the higher level detection of Play Services to return an error, or a "needs update" status or similar, breaking push notification functionality where it was previously known to work well.

I realise microG isn't an official development target of yours at all, however given that Signal likely attracts a disproportionate number of microG users relative to other projects, if it turns out to be relatively low lift to roll-back or otherwise rework the capability detection, perhaps a fix for this can be considered.

### Steps to reproduce
- Set up a phone with a working install of microG, showing as connected in the Google Cloud Messaging menu.
- Install the latest Signal release.

**Actual result:** Play Services detection fails and the app falls back to the much less efficient polling service.
**Expected result:** Perhaps a warning about lack of face blurring capability (if this is the case), but functioning push notifications.

**Comment by quirk46** [comment] 2020-06-06 00:16
After a quick test, face blurring functionality actually appears to work fine, so it appears it's just push notifications affected here.

**Comment by tom3220** [comment] 2020-06-11 09:23
Can reproduce on v4.62.4.6522. Not exactly sure on the last working version but as OP says it was before face blur update.

**Comment by ybea** [comment] 2020-06-19 22:02
Works on 4.60.9.6401. Doesn't work on 4.61.6.6471.

**Comment by GuillaumeLeGoc** [comment] 2020-06-22 12:01
I have the same problem with a fresh install of a custom ROM with no Google Apps. microG is installed and working for every other apps, except Signal and Telegram X. Both were working when registered in GCM through microG before my reinstallation, so I'm not sure from which version Google Play Services detection got broken.

**Comment by jbleonesio** [comment] 2020-06-25 21:13
Doesn't work for me neither on a freshly installed custom ROM (Lineage OS 17.1 on a Samsung Galaxy S10e) while 9 other apps successfully registered within microg GCM.

**Comment by prg318** [comment] 2020-06-30 21:48
Ran into this issue today on a LineageOS/MicroG install.  This is clearly an issue with signal since every other GCM application I've tried has worked fine.  As @ybea pointed out, this works totally fine in signal 4.60.9.x

**Comment by ybea** [comment] 2020-07-01 14:08
There was nothing wrong with Signal after all. PR linked by @jbleonesio explains it. Provided solution works with the latest version (4.65.2). Let's hope it will be merged soon. [For the time being](https://github.com/microg/android_packages_apps_GmsCore/wiki/Building).

I think the issue can be closed.

**Comment by greyson-signal** [comment] 2020-07-01 16:25
Yeah, and as a rule: Signal supports devices that *do not have* Play Services. We fallback to a persistent websocket in that case. If you choose to *fake* Play Services, you're on your own. There's just no world where we can build Signal to use Play Services, but in a way where we cater to the various quirks of replacement implementations. If your Play Services replacement isn't working, please file the issue with them :)

**Closed by greyson-signal** 2020-07-01 16:25 UTC

**Comment by vollzeitaffe** [comment] 2020-07-03 12:29
Can somebody please offer an microg apk upgrade including the fix?

**Comment by jbleonesio** [comment] 2020-07-08 14:02
I can confirm that the PR is indeed fixing the problem but you may have to reinstall your apps to make them registering to push notifications.
Here is the documentation to build microg : https://github.com/microg/android_packages_apps_GmsCore/wiki/Building

**Comment by mmBesar** [comment] 2020-08-13 18:10
We should have the APP working without play services or even microG! [this mine](https://github.com/signalapp/Signal-Android/issues/9638)

**Comment by breversa** [comment] 2020-08-20 11:14
microG 2.11 fixes this issue : https://github.com/microg/android_packages_apps_GmsCore/releases/tag/v0.2.11.202414
