### ISSUE TITLE
Echo cancellation when using speaker

### ISSUE THREAD

**Issue by owiuefiweytgt** [signalapp/Signal-Android#8554] opened 2019-01-22 18:05 UTC
Other side reports loud echo when using the speaker function during a call. I'm on an Android device.
Bug Description

Echo is heard only when on speaker mode
Steps to Reproduce

    Start call
    Select speaker

Actual Result:

Echo on calls

Expected Result:

No echo
Screenshots

audio issue
Platform Info

Signal Version:

4.31.8

Operating System:

Android 7.1.2 (5250158c4b, NJH47F release-keys)

**Comment by 2-4601** [comment] 2019-02-14 17:24
Looks like a duplicate of #7635.
What was the device the other party was using during the call? Please add the device model name as a comment to #7635.

**Closed by 2-4601** 2019-02-14 17:24 UTC
