### ISSUE TITLE
Website APK doesn't auto update on Pixel 3xl 

### ISSUE THREAD

**Issue by nutts0** [signalapp/Signal-Android#8998] opened 2019-08-26 10:11 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Website APK doesn't update automatically

### Device info

**Device:** Pixel 3 XL
**Android version:** 9
**Signal version:** 4.44.7

### Link to debug log

https://debuglogs.org/c85924f2ee06c64280e77fd76ec42bd0074dac486ef990c7733be4a96856b5f4

**Comment by u32i64** [comment] 2019-08-26 14:54
Duplicate of #8936.

Note https://github.com/signalapp/Signal-Android/issues/8936#issuecomment-524438720.

**Closed** 2019-08-26 21:22 UTC
