### ISSUE TITLE
Camera won't work.

### ISSUE THREAD

**Issue by EchersMedia** [signalapp/Signal-Android#9184] opened 2019-11-13 08:33 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After a recent update, I cannot launch the camera within Signal anymore.
It seems like Signal is 'locking' the camera for about 30 seconds. 
The issue affects other apps for the same about 30 seconds.

Is issue only occurs when opening the camera in Signal app and thus locking the camera for up to 30 seconds in all other apps as well afterwards.

### Steps to reproduce
- Open Signal app
- Open a conversation
- Click the camera to take a picture / capture a video.

**Actual result:** 
Camera is now just black and the camera is now "locked" for up to 30 seconds for all other apps as well.
I can still see the following icons:
- Flash icon
- Switch camera icon
- See pictures (buttom left corner)
- Take picture botton

**Expected result:** 
I expect to be able to take a picture ;-)

### Device info

**Device:** Huawei Mate 10 Pro (BLA-L29)
**Android version:** 9.1.0.306
**Signal version:** 4.49.18

### Link to debug log

https://debuglogs.org/8fcb16c1a48aa40b9d7fb13e57627c7ab76aeb6bbd5958d8eb427e4e20416ca2

**Comment by wine3603** [comment] 2019-11-13 08:43
Ｍｙ　ｃａｒｍｅ doesn't work in my signal either.

**Comment by EchersMedia** [comment] 2019-11-13 08:52
> Ｍｙ　ｃａｒｍｅ doesn't work in my signal either.

I'm glad to know I'm not the only one who has this issue - I hope they are able to do something about it.

**Comment by Cerberus0** [comment] 2019-11-13 12:03
Duplicate of https://github.com/signalapp/Signal-Android/issues/9150

**Comment by EchersMedia** [comment] 2019-11-13 14:36
> Duplicate of #9150

I apologize.
I've searched both here and on Google but nothing came up.
But yes, this is the exact same issue.

To add to this issue, I've tested on colleague's Mate 10 Pro, which has the exact same issue.
Either it's an issue of Signal who messed up something during the recent update, or it's Huawei who has done something to break the Signal app on their EMUI system.

Either way, I hope for a fix soon! :)

**Comment by Cerberus0** [comment] 2019-11-13 14:49
Please close this issue and follow https://github.com/signalapp/Signal-Android/issues/9150 for updates. Thanks!

**Closed** 2019-11-13 15:05 UTC

**Comment by Bjornerikm** [comment] 2021-02-22 23:41
Same her on P40 lite, I downgraded to v10.1.0.136 and then it stopped working. But I don't want to upgrade since then I can't use Google services. Just after I try camera in signal and go to regular camera it says it can't connect to the camera there either..

Any fix?
