### ISSUE TITLE
Crash on opening the gallery

### ISSUE THREAD

**Issue by pr0gg3r** [signalapp/Signal-Android#10624] opened 2021-01-14 13:07 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Crash on opening the gallery (I already reinstalled Signal, this did not solve the problem).

### Steps to reproduce
- Tap button to open gallery. It does not matter from where (camera, profile editor, group editor, attach photo to message)

**Actual result:** I see the gallery for a second, than it crashs and is closed.
**Expected result:** Gallery opens and stays open so I can select a photo.

### Screenshots
<img width="450" alt="A6p3wZn3ev" src="https://user-images.githubusercontent.com/7628104/104594083-f0ba5000-5670-11eb-84a9-4fdbc8fa83fc.png">
<img width="449" alt="crc0jF1gw6" src="https://user-images.githubusercontent.com/7628104/104594088-f152e680-5670-11eb-9882-91e279610c5c.png">
<img width="449" alt="O5CXBvOGol" src="https://user-images.githubusercontent.com/7628104/104594090-f1eb7d00-5670-11eb-9190-9fc1fd1fdd1b.png">
<img width="450" alt="ZvvzQ75a1x" src="https://user-images.githubusercontent.com/7628104/104594091-f2841380-5670-11eb-93ae-f4f150897d02.png">

### Device info

**Device:** HUAWEI P30 Pro (VOG-L29)
**Android version:** 10.1.0
**Signal version:** 5.1.8

### Link to debug log
via profile photo selection
https://debuglogs.org/d2c47b458026560637732ce1e61fe6e38034c6899edc4334f0f756545df1796f

via group photo selection
https://debuglogs.org/e86b1008a06620a98492254cddfe7291992a380f121668a749f5d669344fa26c

via attach photo to message
https://debuglogs.org/f693bdfbba6a4f88a4bef23c01721042060280a9c9fb0a755e359e0b412e6c77

via camera screen
https://debuglogs.org/535a9063eaf40743082a8db9e6994f50261d614cb82220adc3996620e900997f

**Comment by pr0gg3r** [comment] 2021-01-14 16:31
After several hours of investigation I found a workaround for this bug. I started with cleaning up my device. I deleted a huge amount of different folders with old images. I even have uninstalled Google Photos. Nothing helped. Then I tried to take a screenshot of the gallery to see after which thumbnail the crash happens. And indeed, I could identify an folder without a thumbnail. I found this folder with the Solid Explorer App. There was just a single file in this folder. It was a short video I have creates with a free video editor. I don't remember the name of that editor. Furthermore the video file was not broken, I could play it without any problem. However, as a last act of desperation I have deleted this file and... the gallery does not crash anymore.
I'm glad I found a workaround, but please fix this bug. I had to sacrifice several gigabytes of photos and videos to find this solution.

![3fd](https://user-images.githubusercontent.com/7628104/104619612-5d901300-568e-11eb-8daf-607d70850bda.jpg)

**Comment by platypusgit** [comment] 2021-01-14 17:34
Could you provide more information about the file an how you located it by taking a screenshot?
Thank you for your sacrifices!

**Comment by pr0gg3r** [comment] 2021-01-14 18:41
Video was 1440p, 31sec long - that is sure, because I uploaded it to YouTube and have checked that now. But I am not 100% about the original file type, I think it was mp4.

Locating it was a little tricky. The gallery activity opens and is visible for a fraction of a second. I took many dozens of screenshots and then I realized that every folder preview image is loaded one after the other. So, I tried to find out which preview/thumbnail is not present. Of course, I could not scroll because of the short time so I had to delete the folders which worked well (existing preview) to see the next bunch of folders.

Here is an example of a screenshot taken to early:
<img width="430" alt="sNEBzUvFR0" src="https://user-images.githubusercontent.com/7628104/104633503-88369780-569f-11eb-8602-564ea2641a85.png">

Here one just in time before its crash:
<img width="431" alt="3XxGTrrMeW" src="https://user-images.githubusercontent.com/7628104/104633551-997fa400-569f-11eb-8519-75efbdd55667.png">

Folder 1 and 2 have no preview. I searched for folder 1 in Solid Explorer, found it, deleted the content, restarted Signal and it did not crash.

**Comment by platypusgit** [comment] 2021-01-15 07:41
Thank you so much! I'll try your workaround in the next few days.

**Comment by JekRock** [comment] 2021-01-15 19:12
Experience the same issue. Here is my [debug log](https://debuglogs.org/1708efe3c138f6dfc4d87babc7d6a56e1b85216820ff0d9cff189b298f7d3545)

**Comment by g42d** [comment] 2021-01-17 10:52
I have the same problem. I will try the workaround

**Comment by g42d** [comment] 2021-01-17 11:01
I found the culprit. In my case, there was a folder without the thumbnail called ADM. It was generated by the app Advanced Download Manager. I deleted both the folder and the app and now it works

**Comment by JekRock** [comment] 2021-01-17 16:53
I think I've found the source of the issue.
Here is what happens in the log when the gallery preview from the camera is being closed:
```
2021-01-17 18:07:22.304 18429-18429/org.thoughtcrime.securesms I/ViewRootImpl: jank_removeInvalidNode all the node in jank list is out of time
2021-01-17 18:07:22.314 18429-18429/org.thoughtcrime.securesms D/StreamStateObserver: Update Preview stream state to IDLE
2021-01-17 18:07:22.614 18429-18519/org.thoughtcrime.securesms D/skia: --- Failed to create image decoder with message 'unimplemented'
2021-01-17 18:07:22.616 18429-18519/org.thoughtcrime.securesms D/skia: --- Failed to create image decoder with message 'unimplemented'
2021-01-17 18:07:22.617 18429-18519/org.thoughtcrime.securesms I/chatty: uid=10253(org.thoughtcrime.securesms) glide-source-th identical 1 line
2021-01-17 18:07:22.619 18429-18519/org.thoughtcrime.securesms D/skia: --- Failed to create image decoder with message 'unimplemented'
2021-01-17 18:07:22.626 18429-18650/org.thoughtcrime.securesms W/ExifInterface: Skip the tag entry since tag number is not defined: 2
2021-01-17 18:07:22.626 18429-18650/org.thoughtcrime.securesms W/ExifInterface: Stop reading file since a wrong offset may cause an infinite loop: 0
2021-01-17 18:07:22.626 18429-18650/org.thoughtcrime.securesms W/ExifInterface: Stop reading file since a wrong offset may cause an infinite loop: 0
2021-01-17 18:07:22.627 18429-18650/org.thoughtcrime.securesms W/ExifInterface: Skip the tag entry since data format (URATIONAL) is unexpected for tag: GPSAltitudeRef
2021-01-17 18:07:22.628 18429-18650/org.thoughtcrime.securesms W/ExifInterface: Stop reading file since a wrong offset may cause an infinite loop: 0
2021-01-17 18:07:22.629 18429-18650/org.thoughtcrime.securesms W/ExifInterface: Stop reading file since a wrong offset may cause an infinite loop: 0
2021-01-17 18:07:22.640 18429-18519/org.thoughtcrime.securesms V/BitmapFactoryEx: nativeDecodeFileDescriptorEx
2021-01-17 18:07:22.641 18429-18519/org.thoughtcrime.securesms A/libc: FORTIFY: read: count 18446744072793573601 > SSIZE_MAX
2021-01-17 18:07:22.641 18429-18519/org.thoughtcrime.securesms A/libc: Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 18519 (glide-source-th), pid 18429 (crime.securesms)
2021-01-17 18:07:22.659 18429-18429/org.thoughtcrime.securesms W/glide-source-th: type=1400 audit(0.0:4372634): avc: granted { read } for path="/mnt/media_rw/C0EA-72C2/DCIM/Camera/IMG_20210113_1234.jpg" dev="mmcblk1p1" ino=16264767 scontext=u:r:untrusted_app:s0:c253,c256,c512,c768 tcontext=u:object_r:exfat:s0 tclass=file
2021-01-17 18:07:22.671 18429-18442/org.thoughtcrime.securesms I/CameraDevice-JV-1: Camera now idle
2021-01-17 18:07:22.674 18429-18595/org.thoughtcrime.securesms D/CaptureSession: CameraCaptureSession.onClosed()
2021-01-17 18:07:22.677 18429-18595/org.thoughtcrime.securesms D/DeferrableSurface: use count-1,  useCount=0 closed=true androidx.camera.core.impl.ImmediateSurface@4511002
2021-01-17 18:07:22.677 18429-18595/org.thoughtcrime.securesms D/DeferrableSurface: Surface no longer in use[total_surfaces=3, used_surfaces=2](androidx.camera.core.impl.ImmediateSurface@4511002}
2021-01-17 18:07:22.678 18429-18595/org.thoughtcrime.securesms D/DeferrableSurface: Surface terminated[total_surfaces=2, used_surfaces=2](androidx.camera.core.impl.ImmediateSurface@4511002}
2021-01-17 18:07:22.678 18429-18595/org.thoughtcrime.securesms D/DeferrableSurface: use count-1,  useCount=0 closed=true androidx.camera.core.impl.ImmediateSurface@8ff7077
2021-01-17 18:07:22.679 18429-18595/org.thoughtcrime.securesms D/DeferrableSurface: Surface no longer in use[total_surfaces=2, used_surfaces=1](androidx.camera.core.impl.ImmediateSurface@8ff7077}
2021-01-17 18:07:22.679 18429-18595/org.thoughtcrime.securesms D/DeferrableSurface: Surface terminated[total_surfaces=1, used_surfaces=1](androidx.camera.core.impl.ImmediateSurface@8ff7077}
2021-01-17 18:07:22.679 18429-18595/org.thoughtcrime.securesms D/DeferrableSurface: use count-1,  useCount=0 closed=true androidx.camera.core.SurfaceRequest$2@2c42a4e
2021-01-17 18:07:22.680 18429-18595/org.thoughtcrime.securesms D/DeferrableSurface: Surface no longer in use[total_surfaces=1, used_surfaces=0](androidx.camera.core.SurfaceRequest$2@2c42a4e}
2021-01-17 18:07:22.680 18429-18595/org.thoughtcrime.securesms D/DeferrableSurface: Surface terminated[total_surfaces=0, used_surfaces=0](androidx.camera.core.SurfaceRequest$2@2c42a4e}
2021-01-17 18:07:22.681 18429-18595/org.thoughtcrime.securesms I/CameraDevice-JV-1: close camera: 1, package name: org.thoughtcrime.securesms
2021-01-17 18:07:22.681 18429-18595/org.thoughtcrime.securesms I/BackgroundPermManager: pkgName: org.thoughtcrime.securesms,pid: 18429 ,uidOf3RdApk: 10253 ,permType: 0 ,permCfg: 0
2021-01-17 18:07:22.684 18429-18595/org.thoughtcrime.securesms I/HwCameraUtil: notifySurfaceFlingerCameraStatus : isFront = true , isOpend = false
2021-01-17 18:07:22.686 18429-18595/org.thoughtcrime.securesms I/HwCameraUtil: notifySurfaceFlingerFrontCameraStatus 8012 transact success!
2021-01-17 18:07:22.695 18429-18429/org.thoughtcrime.securesms D/SurfaceViewImpl: Safe to release surface.
2021-01-17 18:07:22.699 18429-18429/org.thoughtcrime.securesms W/glide-source-th: type=1400 audit(0.0:4372643): avc: granted { read } for path="/mnt/media_rw/C0EA-72C2/DCIM/Camera/IMG_123.jpg" dev="mmcblk1p1" ino=16264767 scontext=u:r:untrusted_app:s0:c253,c256,c512,c768 tcontext=u:object_r:exfat:s0 tclass=file
2021-01-17 18:07:22.794 18429-18595/org.thoughtcrime.securesms D/CaptureSession: CameraCaptureSession.onReady() RELEASED
2021-01-17 18:07:22.796 18429-18595/org.thoughtcrime.securesms D/Camera2CameraImpl: {Camera@69c9d60[id=1]} CameraDevice.onClosed()
2021-01-17 18:07:22.798 18429-18595/org.thoughtcrime.securesms D/Camera2CameraImpl: {Camera@69c9d60[id=1]} Transitioning camera internal state: CLOSING --> INITIALIZED
2021-01-17 18:07:22.804 18429-18595/org.thoughtcrime.securesms D/CameraStateRegistry: Recalculating open cameras:
    Camera                                       State                 
    -------------------------------------------------------------------
    Camera@c8dca65[id=0]                         UNKNOWN               
    Camera@69c9d60[id=1]                         CLOSED                
    -------------------------------------------------------------------
    Open count: 0 (Max allowed: 1)
```

The most interesting part of the log is:
```
2021-01-17 18:07:22.641 18429-18519/org.thoughtcrime.securesms A/libc: FORTIFY: read: count 18446744072793573601 > SSIZE_MAX
2021-01-17 18:07:22.641 18429-18519/org.thoughtcrime.securesms A/libc: Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 18519 (glide-source-th), pid 18429 (crime.securesms)
```

Fast googling gave me that [issue](https://github.com/bumptech/glide/issues/4165) from the [Glide](https://github.com/bumptech/glide) library that is used in the Signal app for loading images including camera gallery previews.
According to the discussion in that issue, the error appears in the Glide v4.11on Huawei devices while v4.10 doesn't have this problem.
The Signal app is using Glide v4.11([link](https://github.com/signalapp/Signal-Android/blob/7e64d57ba8fc8ac295c7c35279fba2bf6400655b/app/build.gradle#L354)).
So, the solution might be a fallback to the Glide v4.10

**Comment by JekRock** [comment] 2021-01-17 16:56
@pr0gg3r @g42d do you have a Huawei device?
I have a Huawei device, but I don't have another one to check whether the issue appears on non-Huawei devices

**Comment by g42d** [comment] 2021-01-17 17:01
> @pr0gg3r @g42d do you have a Huawei device?
> I have a Huawei device, but I don't have another one to check whether the issue appears on non-Huawei devices

In my case, it's a Huawei P30 Pro
Device info: HUAWEI VOG-L29 (VOG-L29EEA)
Android version: 10 (10.1.0.150C431, VOG-L29 10.1.0.150(C431E19R2P5))
Signal version: 5.1.9
Signal package: org.thoughtcrime.securesms 
Registration lock: false
Locale: en_DE

**Comment by JekRock** [comment] 2021-01-17 17:37
I've just checked the current Signal version with the previous Glide version that had been used before (v4.9.0) and the gallery preview works without any errors.
@greyson-signal I've seen that you updated the Glide version at d05a71c8fe. Is it possible to fall back to Glide v4.9.0 to resolve the gallery issue until it's fixed in Glide?

**Comment by richardddd98** [comment] 2021-01-18 03:32
I think I have this problem too. If I have at least one long screen recording (more than 3 GiB), when I scroll the gallery and Signal attempts to show its thumbnail it crashes and asks me again to unlock it with my fingerprint. My device is Huawei P40 Lite 5G

**Comment by DarkoVeberic** [comment] 2021-07-06 20:18
Duplicate of #10394

**Comment by JekRock** [comment] 2022-01-26 09:54
I'll try to reproduce it again on the same phone.
I don't see `glide` in dependencies anymore, though.

**Closed** 2022-04-10 19:15 UTC
Labels: wontfix
