### ISSUE TITLE
Attachments Sent Cannot Be Accessed on Android Side

### ISSUE THREAD

**Issue by GuardianMajor** [signalapp/Signal-Android#7257] opened 2017-12-08 22:22 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When sending an attachment of any file extension (tested with TXT, MP4, PDF, ZIP) will be sent to the recipient (be it via Desktop client ~~or within Android~~) they are delivered but you cannot do anything like open them, or save them, on Android conversation with that recipient and often show Unknown File as the name. They also do not show up under the documents tab of the media library for that conversation.

### Steps to reproduce
- Send a file to someone, using desktop client
- Attempt to open or save them on Android client
- The files are unknown and inaccessible
- Check all media and the documents tab and they will not be there either

Issue originally opened here: https://github.com/WhisperSystems/Signal-Desktop/issues/1853 (worked with Scott to figure out what is going on, he was able to reproduce the issue and found it to be an Android client issue, could not reproduce on iOS client and was suggested I open this issue here)

Issue similar to https://github.com/WhisperSystems/Signal-Android/issues/6791 (except not just for PDF but for ANY file type - list of tested types so far mentioned above) and the system contains viewers for all these file types and they work normally outside of the client, the issue is not opening them but rather that you can't open or save them at all, they basically show up as an entry with unknown as the file name and nothing more can be done with them.

**Actual result:** The files are not accessible and marked as unknown under the Android side for anything sent either via Desktop client to someone.
**Expected result:** Files should be properly listed with their names and be accessible to open or save and appear under the documents tab of the all media library.

### Screenshots
Screenshots available at the referenced original issue above but do not reveal anything special beyond what is described.

### Device info
**Device:** Motorola Nexus 6 (shamu)
**Android version:** Nougat 7.1.1 (stock N6F27M)
**Signal version:** 4.14.3 (beta)

### Logs
https://gist.github.com/anonymous/f06a523736972102de8f296e85c224fc

I would be happy to provide anything else you need and as with Scott, we worked directly with each other to send stuff so we can see the behavior, if anyone needs me to use the special debug build and do the same, be happy to do it, just give me a way to contact you privately like with Scott. Thanks.

**Comment by moxie0** [comment] 2017-12-08 23:06
I don't understand your issue. Can you try posting an ordered list of steps to reproduce from a clean install?

**Comment by jeremymasters** [comment] 2017-12-08 23:08
I've sent PDF's from desktop and android to another android user with no issue.

**Comment by GuardianMajor** [comment] 2017-12-08 23:39
I have listed the steps above, I don't know what else you want me to include. It was replicated by Scott, so I am sure there is an issue there and he had no more information than what I have provided.

I would have liked to include a log too but the log only contains this and nothing more:

> Device  : motorola Nexus 6 (shamu)
> Android : 7.1.1 (4299435, N6F27M)
> Memory  : 42M (10.79% free, 512M max)
> Memclass: 256
> OS Host : wprh2.hot.corp.google.com
> App     : Signal 4.14.3

So not exactly helpful. The steps are quite simple, as already stated:

1. Send a document of any extension like TXT, ZIP, PDF, MP4 to someone (use either the Desktop client or the Android client makes no difference other than the file name when sent from Desktop will show correctly and otherwise shows Unknown file)
2. Try to open it from the conversation where you sent it
3. I can't open it, or save it and it will not show up under the documents tab of all media

That's it. They receive it fine on their end and it shows up on the desktop client fine but only on the Android client they are inaccessible (meaning, can't be opened, can't be saved, can't be forwarded, no action can be taken on them other than delete). Let me know if anything else.

@jeremymasters please read the issue, the sending is not an issue, I can send them just fine, it is accessing them from the conversation on the Android client that is the issue.

**Comment by scottnonnenberg** [comment] 2017-12-08 23:55
Here are my steps:
- Open Signal Desktop `v1.1.0-beta.4` send an attachment to a contact
- Open Signal Android `4.14.2` and view the conversation with that contact
- See the message there, listing the attachment I just sent
- Tap on that attachment, and nothing happens

I'm able to access the file if I send the attachment from Android, or if I receive an attachment from the contact. I have problems only if I send from desktop, then attempt to open my sent attachment in Android.

As mentioned above, I tested this build of Signal Desktop against iOS, and I was able to access my sent attachment there. So it does seem to be an Android-specific issue.

**Comment by GuardianMajor** [comment] 2017-12-09 00:04
Ok, here is some more information. As Scott said, I had the same contact send ME something and I was able to download and open it just fine, it came from them on Android. I asked them to send it from their desktop and I was able to get it and open it as well. However, THEY could not open the same file on their end. As described above, same for me when I send them something on desktop, I cannot access them on the Android client. 

In fact, an indicative indicator is that when you can "access" them, you will see a down icon before you click and get it and then switches to the "file" icon. But on those that we cannot access, there is no down icon, just shows the file icon and if you try to force save it by long press, it will give a toast saying, cannot access, unfortunately the exact wording escapes me as it doesn't last long enough to catch.

I was finally able to generate a log that had something useful more than what I posted earlier, so I am going to put the link here and update the original issue above to have the link as well. I hope there is something useful in it for you, I didn't have a chance to parse through it much.

https://gist.github.com/anonymous/f06a523736972102de

**Comment by jeremymasters** [comment] 2017-12-09 00:38
@GuardianMajor I was of course following your steps and my receiver was able to open them

**Comment by GuardianMajor** [comment] 2017-12-09 21:49
@jeremymasters as noted already, and again, it is not the receiver that has issue opening, it is the sender on their own device. If you followed the steps, you would see it, so if you are not, then you didn't.

**Comment by Trolldemorted** [comment] 2017-12-09 22:11
Isn't this a duplicate of https://github.com/WhisperSystems/Signal-Android/issues/6791?

**Comment by GuardianMajor** [comment] 2017-12-09 23:06
@Trolldemorted As I already referenced in my bug report above, I saw this but it involves specifically a PDF document and the discussion seemed to surround the availability of a PDF viewer, so while tenuously related as mentioned, it was not directly the same and I was asked to open this issue by a member of the dev team. Unless substantial amount of each bug is related to the same issue, calling it a duplicate is not helpful. If they do feel it is, then they are welcome to merge it, as I have also mentioned in my report.

**Comment by Trolldemorted** [comment] 2017-12-09 23:25
#6791 is not about pdfs, but about all attachments - the pdf is just an example, as everyone most likely has a pdf file around to test it.

You can verify by sending a pdf from Signal-Desktop to yourself - you will be able to open the pdf in the direct message, but not the one in the sync message.

I guess it's just a wrong view spawned for attachments in sync messages.

**Comment by GuardianMajor** [comment] 2017-12-10 23:20
@Trolldemorted Last I read it, which is when I opened the issue and referenced it, it was revolving pretty exclusively around not being able to open/view the PDF document despite having "viewers" on the device, if the context or further developments pointed elsewhere, I did not have a reason to check or follow up on it. Regardless, the lack of feedback on the issue and bickering over whether it is a duplicate or not seems a bit disheartening.

**Comment by automated-signal** [comment] 2018-04-03 04:48
GitHub Issue Cleanup:
See #7598 for more information.

**Closed by automated-signal** 2018-04-03 04:48 UTC
