### ISSUE TITLE
Video redirect removes file ending

### ISSUE THREAD

**Issue by MartinX3** [signalapp/Signal-Android#8015] opened 2018-07-20 16:35 UTC
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Redirected media files lost their file ending.
Contact B can't play the video.
I can't see the preview in the dekstop app anymore, instead I see an "unamed file" text.

Android doesn't has this trouble, because it looks into the file header instead of the file name.

### Steps to reproduce
- In my android APP I share a video to contact A (iPhone user).
- In my android APP I redirect it to contact B (iPhone user).

**Actual result:** My Desktop APP tells me, that this is an unnamed file.
Contact B can't open the video, because her iPhone doesn't know the file ending.

**Expected result:** Contact B can play the video like contact A.
The Desktop app should show me the preview.

### Screenshots

![grafik](https://user-images.githubusercontent.com/4518092/43014193-aec90d04-8c4b-11e8-9736-ff19f136baee.png)

![grafik](https://user-images.githubusercontent.com/4518092/43014178-a2939b12-8c4b-11e8-99d9-9c8def4dccde.png)

### Device info

**Device:** Sony Xperia XZ2 H8296 Revision 2
**Android version:** 8.0.0
**Signal version:** 4.23.4

### Link to debug log

https://debuglogs.org/3e709472c4686268d346bacbba3075806eef8761984c0aa1783bfa70d0985efc

**Comment by greyson-signal** [comment] 2018-07-20 23:07
Dupe of #7783. Thanks!

**Closed by greyson-signal** 2018-07-20 23:07 UTC
