### ISSUE TITLE
Notification persists after a reply in Android P

### ISSUE THREAD

**Issue by nkm8** [signalapp/Signal-Android#8194] opened 2018-09-10 12:58 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Bug report is observed on the final release of Android 9.0; a continuation of: https://whispersystems.discoursehosting.net/t/signal-notification-behavior-in-android-9-0-dp5/3630
When I receive a Signal notification and reply using the 'reply' feature of the notification, the notification and reply both persist in the system notification tray.  This is a bug because 'Mark as read' quick action still exists, but doesn't actually do anything.  The message is already marked as read if you manually open the Signal app, but the notification isn't being automatically dismissed.

### Steps to reproduce
- Receive a Signal message
- Reply to the Signal message via the system notification

**Actual result:** Both the original message and your reply are both shown in the system notification, along with the 'Mark as Read' quick action
**Expected result:** After the reply is sent, the original message should be marked as read in Signal and the notification should be automatically dismissed.

### Device info

**Device:** Google Pixel 2
**Android version:** 9.0
**Signal version:** 4.25.10

**Comment by 211217613** [comment] 2018-09-18 04:15
My :+1:  is to confirm the same behaviour.

**Comment by Orion116** [comment] 2018-10-25 15:11
The reply issue is not a issues with Signal. It is an actual feature of Android Pie. Most messaging as do that. As for the marked as read that is probably a bug. https://www.androidcentral.com/android-p-features-youll-love-improved-notifications

**Comment by nkm8** [comment] 2018-10-26 12:47
@Orion116 That article isn't relevant to this issue.  Smart replies only work on Android Messages, not third-party messaging apps (yet).  Actionable notifications were introduced back in Android L.

**Comment by Orion116** [comment] 2018-10-26 13:46
I am referring to the other features like saving drafts and in like media. Those are things that are new.

**Comment by elliptic1** [comment] 2018-10-29 16:54
I'm having this problem too and I'm interested in finding a solution for it. Is the expected behavior that the notification dismisses after the reply is sent or that it persists until the Mark as Read button is clicked? I imagine it would persist since the user is interested in continuing that conversation, as demonstrated by the action of replying to the message.

**Comment by nkm8** [comment] 2018-10-29 19:03
This is where things get a bit fuzzy.  The behavior that @elliptic1 describes is how Android Messages behaves, which I hate.  I would prefer the opposite behavior - when I reply to the message, the notification should be dismissed.

The only argument I have heard for leaving the notification in place is for 'continuing a conversation', but I never really understood this perspective.  For me, notifications are items that I need to perform an action on.  I go through my notifications and either perform an action or dismiss the notification.  For chats/conversations, my reply is my action and the notification should be dismissed.

Currently, my work-around is to swipe-to-dismiss the notification after I use the inline reply.  However, I would argue that this is an unnecessary extra step.

**Comment by elliptic1** [comment] 2018-10-30 03:50
The most important thing is to make it behave the way the Signal community wants it. I was looking over the Android best practices for messaging apps and they talk about using a notification's direct reply: 

> After a user replies with the inline reply action ... do not retract or cancel the notification. Not cancelling the notification allows a user to send multiple replies from the notification.

[Best practices for messaging apps](https://developer.android.com/training/notify-user/build-notification#messaging-best-practices)

**Comment by Orion116** [comment] 2018-10-30 14:17
@elliptic1 exactly what I was trying to say this is a normal behavior.

**Comment by nkm8** [comment] 2018-10-30 16:08
@elliptic1 I assumed this had to be a best practice from Google since Android Messages follows the same behavior.  However, I would still argue that the best practice is wrong/incorrect.  After I reply to a message, why would I want an ongoing notification clogging my entire notification pane?  This behavior never made any sense to me.  I am curious if I am crazy or if others feel the same way.  Related discussions:
https://forums.androidcentral.com/android-apps/772490-google-messages-mark-text-read-when-i-reply-status-bar.html
https://forums.androidcentral.com/google-pixel-2-pixel-2-xl/865730-sms-staying-notification-after-replying.html
https://www.reddit.com/r/GooglePixel/comments/7maq20/should_using_quick_reply_clear_the_text/
https://www.reddit.com/r/GalaxyS8/comments/7zkymk/android_messages_app_notification_still_in_status/
https://productforums.google.com/forum/#!topic/play/C-D1Hwu-Cw8
https://talk.sonymobile.com/t5/Xperia-XZ/Notifications-don-t-dissapear-if-using-quick-reply/td-p/1196304

If the point is to continue ongoing conversations from the notification panel, what is the point of the app?  I don't think it makes any sense to jamb an entire application's behavior into a single notification.

At a minimum, I think the Signal behavior is incorrect because the 'Mark as read' quick action still exists on the notification.  By replying to a message, I must have read the notification, so persisting a 'Mark as read' action is incorrect.  This is where I see a direct contradiction to the best practices (ironically, Android Messages also behaves incorrectly).

Is it possible to include a setting/toggle to control this behavior in Signal?  I am clearly not the only person who doesn't like the current behavior, so making it configurable would satisfy both viewpoints.

**Comment by Enzo40Dog** [comment] 2018-11-08 18:54
I have the same issue. Both within the notification menu and in quick reply.  Running Android Pie on OG Google Pixel XL

**Comment by Enzo40Dog** [comment] 2018-11-08 18:57
@nkm8 @orion116 is actually correct it's an Android Pie feature that the messages are left in the notification menu after a reply. But the mark Read button should work to dismiss it

**Comment by nkm8** [comment] 2018-11-08 19:06
@Enzo40Dog calling it a feature isn't accurate. Android provides support for persisting the notification, but the behavior is ultimately controlled by the app. As I explained previously, neither the current behavior nor the mark as read button make sense to me. 

I accept that others may agree with the current behavior, which is why I suggested a setting to control. I also provided ample evidence that I'm not the only person who disagrees with the current behavior and Google's guidelines.

**Comment by greyson-signal** [comment] 2018-11-08 19:15
I think it's safest for us to follow Android-standard behavior. System-provided actions, like replying in a notification, should work the same across different messaging apps, and that includes us. I believe Android's rationale for keeping the notification is that you should be able to reply multiple times. 

Also, I just checked, and other messaging apps will not dismiss the notification after "mark as read" is clicked *if* you've already used the same notification to reply. I'm assuming it's because you've started a new chain of actions with the reply, and "mark as read" no longer becomes a dismissable action.

It's worth noting that Signal (and other apps) *do* dismiss the notification if you click "mark as read" and *haven't* used the same notification for a reply.

Changing this behavior would go against user expectation of how notifications work in other places, so I'm closing this as a feature request. Feel free to continue this in the forum. Thanks!

**Closed by greyson-signal** 2018-11-08 19:15 UTC
