### ISSUE TITLE
The photos previews are not rendered well

### ISSUE THREAD

**Issue by giupardeb** [signalapp/Signal-Android#11551] opened 2021-08-19 14:18 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The photos previews are not rendered well. In the Screenshots section, you can see the properties of the photos.

### Steps to reproduce
I took a pictures with Open Camera v1.48.3, then I sent them in a chat.

**Actual result:** the photos previews are not rendered well
**Expected result:** a well rendered previews

### Screenshots
![photo_2021-08-19_16-03-03](https://user-images.githubusercontent.com/4471950/130083759-07987d3b-a35b-4c12-8a68-d2649a084417.jpg)
![photo_2021-08-19_16-18-10](https://user-images.githubusercontent.com/4471950/130084877-c9530e7e-62af-4ebc-a4b0-e029a6307db0.jpg)

### Device info

**Device:** Redmi Note 8T
**Android version:** 10 (LineageOS 17.1)
**Signal version:** 5.20.4

### Link to debug log
https://debuglogs.org/842f921d09446204b5364d952138a3b5b23fde8f9027e870d572a4db890d19fd

**Comment by greyson-signal** [comment] 2021-08-19 16:30
Closing as duplicate of #9082

**Closed by greyson-signal** 2021-08-19 16:30 UTC
