### ISSUE TITLE
I cannot send GIF in unsecure way to contacts having signal

### ISSUE THREAD

**Issue by Paradoxeuh** [signalapp/Signal-Android#8610] opened 2019-02-13 09:47 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I cannot send GIF in unsecure way to contacts having signal. Secure gif to contacts having signal and unsecure gif to contacts not having signal are working.

### Steps to reproduce
- Select the unsecure send button
- Select a gif
- Try to send it

**Actual result:** It behaves like if I had no network.
**Expected result:** It should just send the gif.

### Device info

**Device:** Huawei Nova 2
**Android version:** 7.0.0
**Signal version:** 4.32.8

### Link to debug log
https://debuglogs.org/7768cf0bd593fda04b52b39a319d2d5a70daf2e14a38bbde36fe44faea7966f3

**Comment by greyson-signal** [comment] 2019-02-14 15:49
This is a dupe of #8573, which will be fixed in 4.34. Thanks!

**Closed by greyson-signal** 2019-02-14 15:49 UTC
