### ISSUE TITLE
QR scanner not working as intended for connecting to Signal Desktop client.

### ISSUE THREAD

**Issue by QwertyIsCoding** [signalapp/Signal-Android#12184] opened 2022-04-20 12:46 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The QR code scanner in the Android app freezes. By that, I mean that every time I try to scan teh QR code on the desktop client, the camera pauses and does not scan the QR code and because of this, I cannot use Signal dekstop.

### Steps to reproduce
- Open the Signal app
- Click on the three dots on the top right of the app UI
- Click on the settings option
- Click on Linked devices
- Click on the + button

**Actual result:** The camera pauses and freezes. And hence, does not scan the QR code.
**Expected result:** The camera should scan the QR code and should sync messages between the desktop client and the Android app.

### Device info

**Device:** Redmi Note 11
**Android version:** 11 running MIUI 13.0.9
**Signal version:** 5.34.10

### Link to debug log

https://debuglogs.org/android/5.34.10/671c0b04c5e6588d8d4f624897a0ce730b503dd3f5f81906e21524e000ed5f82

**Comment by cody-signal** [comment] 2022-04-20 15:37
Duplicate of 12009

**Closed by cody-signal** 2022-04-20 15:37 UTC

**Comment by QwertyIsCoding** [comment] 2022-04-23 03:25
Oh, I'm sorry...
