### ISSUE TITLE
Friend no longer shows up in the secure contacts list

### ISSUE THREAD

**Issue by nullray** [signalapp/Signal-Android#7563] opened 2018-03-24 18:42 UTC
I have:
- [x ] searched open and closed issues for duplicates
- [x ] read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Friend no longer shows up in the secure contacts list.

### Steps to reproduce
- talk to someone
- ???

**Actual result:** The app stopped recognizing him in the middle of a conversation which resulted in sending unsecure messages. The app still doesn't recognize him. I asked if he changed anything and he claims he didn't. While talking with him over unsecure messages about the issue the app briefly recognized him and I started receiving secure messages but that didn't last long.

**Expected result:** The app should properly recognize people using the app and display a warning if problems occur during a conversation.

### Device info

**Device:** Galaxy S6
**Android version:** 7.0
**Signal version:** 4.16.9

**Comment by haffenloher** [comment] 2018-03-24 18:43
Please make sure to always include a debug log when filing a bug report.

**Comment by nullray** [comment] 2018-03-24 18:46
When I try to submit a debug log I get "Network failure. Please try again.". Internet works fine... I can send messages on a group chat.

**Comment by nullray** [comment] 2018-03-24 18:54
I should add that my friend is also in the group chat and he receives the messages there.

**Comment by PiCob** [comment] 2018-03-25 06:39
Just tried myself and I'm facing the "network failure" as well despite being online for sure. Seems to be an issue with the Gist API, resulting in an exception:

```
03-25 08:34:08.785 22465 27782 W ImageActivity: 
03-25 08:34:08.785 22465 27782 W ImageActivity: java.io.IOException: Gist's response was malformed
03-25 08:34:08.785 22465 27782 W ImageActivity: 	at org.whispersystems.libpastelog.SubmitLogFragment$SubmitToPastebinAsyncTask.doInBackground(SubmitLogFragment.java:383)
03-25 08:34:08.785 22465 27782 W ImageActivity: 	at org.whispersystems.libpastelog.SubmitLogFragment$SubmitToPastebinAsyncTask.doInBackground(SubmitLogFragment.java:336)
03-25 08:34:08.785 22465 27782 W ImageActivity: 	at android.os.AsyncTask$2.call(AsyncTask.java:304)
03-25 08:34:08.785 22465 27782 W ImageActivity: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-25 08:34:08.785 22465 27782 W ImageActivity: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
03-25 08:34:08.785 22465 27782 W ImageActivity: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
03-25 08:34:08.785 22465 27782 W ImageActivity: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
03-25 08:34:08.785 22465 27782 W ImageActivity: 	at java.lang.Thread.run(Thread.java:761)
03-25 08:34:08.835 22465 22465 W SubmitLogFragment: Response was null from Gist API.
```

However, you can just copy the original log manually (instead of hitting the submit button) and upload it on hastening/hastening/wherever.

**Comment by FeuRenard** [comment] 2018-03-25 11:25
The debug log issue is tracked in #7451.

**Comment by 2-4601** [comment] 2018-03-25 13:06
I think this is a duplicate of #7016? There have been other reports older than that but can't find them.

**Comment by moxie0** [comment] 2018-04-03 10:00
I'm unable to take any action without a debug log. Please reopen once a debug log is available, thanks!

**Closed by moxie0** 2018-04-03 10:00 UTC
Labels: bug
