### ISSUE TITLE
In-app camera preview does not auto-rotate if system auto-rotation is disabled

### ISSUE THREAD

**Issue by subraizada3** [signalapp/Signal-Android#8515] opened 2019-01-08 03:19 UTC
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The in-app camera view used to quickly add a photo to a conversation will not auto-rotate the captured photo (or the 'swap cameras' button) unless the system auto-rotation setting is enabled.

This is when using the Camera button inside the normal text input box, toward the right side - which opens a Signal built-in camera. Clicking the blue '+' button on the right of the text box (outside it) and then selecting 'Camera' opens the system camera app, which always auto-rotates.

### Steps to reproduce
- In a Signal conversation view, click the Camera button in the right side of the text input box
- Rotate the phone physically, with or without the system auto-rotation setting enabled

**Actual result:** Camera should always auto-rotate
**Expected result:** Camera only auto-rotates when system-wide auto-rotation is enabled

### Device info
**Device:** Samsung Galaxy S9
**Android version:** 8.0.0
**Signal version:** 4.31.6

### Link to debug log
https://debuglogs.org/9cf5fc892fd29d65fc215a11f85b951c645d1517203cbc933574e5ef84a46861

**Comment by righy** [comment] 2019-02-06 09:16
I'm having the exact same problem on Android 7.1.2 and Signal 4.32.8.

**Comment by greyson-signal** [comment] 2019-03-19 18:07
Closing as a dupe of #8611, which I think describes the problem more succinctly.

**Closed by greyson-signal** 2019-03-19 18:07 UTC
