### ISSUE TITLE
Saving some media files to storage fails with crash

### ISSUE THREAD

**Issue by DirkPitt1** [signalapp/Signal-Android#10249] opened 2020-12-04 15:58 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Every time I try to save video attachments to storage I get 'Error while saving attachment to storage!' and these exceptions in debug logs:

> [4.79.3] 2020-12-04 13:00:34.401 CET W SaveAttachmentTask: java.io.FileNotFoundException: No such file or directory
> [4.79.3] 2020-12-04 13:00:34.401 CET W SaveAttachmentTask: 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:144)
> [4.79.3] 2020-12-04 13:00:34.401 CET W SaveAttachmentTask: 	at android.content.ContentProviderProxy.openAssetFile(ContentProviderNative.java:621)
> [4.79.3] 2020-12-04 13:00:34.401 CET W SaveAttachmentTask: 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:980)
> [4.79.3] 2020-12-04 13:00:34.401 CET W SaveAttachmentTask: 	at android.content.ContentResolver.openOutputStream(ContentResolver.java:722)
> [4.79.3] 2020-12-04 13:00:34.401 CET W SaveAttachmentTask: 	at org.thoughtcrime.securesms.util.SaveAttachmentTask.saveAttachment(SaveAttachmentTask.java:113)
> [4.79.3] 2020-12-04 13:00:34.401 CET W SaveAttachmentTask: 	at org.thoughtcrime.securesms.util.SaveAttachmentTask.doInBackground(SaveAttachmentTask.java:77)
> [4.79.3] 2020-12-04 13:00:34.401 CET W SaveAttachmentTask: 	at org.thoughtcrime.securesms.util.SaveAttachmentTask.doInBackground(SaveAttachmentTask.java:34)
> [4.79.3] 2020-12-04 13:00:34.401 CET W SaveAttachmentTask: 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
> [4.79.3] 2020-12-04 13:00:34.401 CET W SaveAttachmentTask: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
> [4.79.3] 2020-12-04 13:00:34.401 CET W SaveAttachmentTask: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
> [4.79.3] 2020-12-04 13:00:34.401 CET W SaveAttachmentTask: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
> [4.79.3] 2020-12-04 13:00:34.401 CET W SaveAttachmentTask: 	at java.lang.Thread.run(Thread.java:818)

When I try to save mp3 file the app crashes and I get this exception in logs:

> 12-04 12:42:48.548  8714  8714 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x80e381ed10 in tid 8714 (crime.securesms)
> 12-04 16:33:11.506 12248 12350 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #5
> 12-04 16:33:11.506 12248 12350 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 12248
> 12-04 16:33:11.506 12248 12350 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
> 12-04 16:33:11.506 12248 12350 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:309)
> 12-04 16:33:11.506 12248 12350 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
> 12-04 16:33:11.506 12248 12350 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
> 12-04 16:33:11.506 12248 12350 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
> 12-04 16:33:11.506 12248 12350 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
> 12-04 16:33:11.506 12248 12350 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
> 12-04 16:33:11.506 12248 12350 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
> 12-04 16:33:11.506 12248 12350 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.lastIndexOf(int)' on a null object reference

Documents (txt, docx, pdf) and images get saved correctly and I have enough free space on my phone.

### Steps to reproduce
- try to save video or audio attachment to phone storage

**Actual result:** Error while saving videos and crash while saving audio files.
**Expected result:** An attachment is saved correctly.

### Device info

**Device:** LG G4
**Android version:** 6.0
**Signal version:** 4.79.3

### Link to debug log

https://debuglogs.org/36f3853d2da4261591bb63ea043fa73aba09f6fc28c1913c7f187e2aaa3c8736

**Comment by sivaraam** [comment] 2020-12-06 16:19
I observed this too when saving video files. Debug log: https://debuglogs.org/fcdcb6a0c13ae9ca8d1d862e12d4cd37f6b20f26ad556eecaf86519e8abfbf54

**Comment by greyson-signal** [comment] 2020-12-07 15:36
Looks to be a duplicate of #10159

**Closed by greyson-signal** 2020-12-07 15:36 UTC
