### ISSUE TITLE
Creation of backup not possible

### ISSUE THREAD

**Issue by SignalUser2022** [signalapp/Signal-Android#12062] opened 2022-03-13 17:23 UTC
Let's begin with a checklist: Replace the empty checkboxes [ ] below with checked ones [x] accordingly. -->

- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I try to create a backup on Signal v 5.32.15 the app tells me that this feature is deactivated. When I click on the "activate" button a folder of my internal storgae is opened with the question if Signal is allowed to access the sotrage. When I click on it, it just jumps back to the backup menu and aks me if I want to activate backups. Therefore I cannot create any backup at this moment.
- I tried to create a backup on internal and externeal storage, 
- I ejected the SD card and tried to create a backup on internal storage
- I checked the permissions of Signal in the Android settings, and the permissions are all set.
- I tried to force close the built-in android file manager and deleted the cache.
- I force closed Signal and deleted the cache
-> No effect on the problem.

### Steps to reproduce
- Start Signal
- Go to Signal settings
- Go to backup menu of Signal
- Click on "Activate"
- File manager pops up to choose the backup location (Where to save it)
- Question on the lower half of the screen to allow access to the storage
- Click on it and get kicked back to backup menu

**Actual result:** Impossible to create backup in any storage
**Expected result:** Create a backup after choosing the storage location

### Device info

**Device:** BQ Aquaris X
**Android version:** 10
**Signal version:** 5.32.15

### Link to debug log
I don't know why but the debug log is huge and contains many days logged. Can I shrink it to at least the latest 15 minutes?

**Comment by alex-signal** [comment] 2022-03-14 12:27
We'll likely need a debug log. You can always submit a debug log privately via the forum, or you can submit it, send yourself the link, and then send over the relevant parts. Debug logs are not indexed and do not contain PII

**Comment by SignalUser2022** [comment] 2022-03-14 14:01
Dear Alex, 
do you mean the Signal community forum to upload the debug log?
If I can priavtely upload it there, I would prefer that.
The log is huge with approximately 10000 rows, it's way too much to go through for me at the moment with my limited knowledge, of what is important for solving the problem and what is not.
Thank you very much :-)

**Comment by cody-signal** [comment] 2022-03-14 20:02
Nothing jumps out in your logs as a problem. I fired up a Android 10 emulator to try and reproduce and couldn't. Where on the device are you trying to store the backups? I went for base internal storage and made a new folder? Could you try that?

**Comment by SignalUser2022** [comment] 2022-03-15 12:00
Dear Cody,
Thanks for looking into the logs.

I tried to store the backups either in internal storage or in external storage. I also tried to disable the external storage and save it in internal storage. Nothing works.
I also tried to create a new folder in internal storage and start creating a backup, but the same happens: It just jumps back to the backup menu within Signal.

**Comment by SignalUser2022** [comment] 2022-03-15 12:08
Furthermore, when I create a folder in the process this folder appears in the built-in data manager of my phone. When i open it and check for mistakes it says (besides other information): 
Supports create: True
Suppurts delete: True
Supports move: True
Supports write: False

Could that be the problem?
When I set up the phone I changed the settings of the phone to use the SD card as external storage and the internal storage as main storage for apps etc... if that helps anything.

**Comment by cody-signal** [comment] 2022-03-15 13:58
Interesting, yeah, if we don't have write permission there's nothing we can do. It's odd that is the case. Are you able to use the phone's manager to give write access (if that's even possible)?

**Comment by SignalUser2022** [comment] 2022-03-15 14:02
I checked the permissions in the settings of the phone, but I cannot change any permissions of this app since it's a built-in app. Since Signal doesn't allow me to choose a file manager to perform this task, I can only work with the default data/folder manager of my phone and this one doesn't have write access, as it seems :((

**Comment by SignalUser2022** [comment] 2022-03-16 01:30
Ok, this is now really weird:
I checked the permissions of Signal and the file manager with an app that can also see the permissions that cannot be changed without root access.
Both Signal and the file manager got all the necessary permissions, I mean they got all they requested, not one is denied.
Cody, can you maybe explain to me the process that follows after Signal sending a request for the file manager to the Android system so I can check on the next steps? Maybe the problem is somewhere hidden there.

Thank you very much for your efforts.

**Comment by Aushilfsarnie** [comment] 2022-04-20 11:25
Hello, is there any solution? Got the same problems and can't switch backups on...

**Comment by alex-signal** [comment] 2022-04-20 12:26
When presented with the dialog to select a backups location are you trying to use the home folder or are you creating a Signal subfolder? If not the latter, could you try that? It's possible that the home folder is "special" like that.

**Comment by Aushilfsarnie** [comment] 2022-04-20 12:36
Hello, thank you for the feedback. Unfortunately, this dialog does not open at all. The file manager always crashes. Maybe it's because Signal only has access to media files?

**Comment by SignalUser2022** [comment] 2022-04-20 20:05
@Aushilfsarnie @alex-signal The problem was not solved by me, I tried removing all permissions from signal and giving them back, deleting the cache, removing sd card, ....
Nothing helped. So far the issue is unsolved.

**Comment by SignalUser2022** [comment] 2022-04-20 20:09
@alex-signal For me it's possible to choose a folder where to save the backup. I tried to choose the default folder in internal memory and creating a new folder. Both methods don't work. 
When I click on "Allow access to internal memory", either in the default folder or on a newly created one, the file manager crashes.

**Comment by Aushilfsarnie** [comment] 2022-04-21 07:33
Hey, Thanks for the reply. My problem is solved. My problem is solved. Another app was interfering and crashing the app files

**Comment by alex-signal** [comment] 2022-04-21 12:32
@SignalUser2022 If you're seeing a crash, please link a debug log :)

https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports

**Comment by alex-signal** [comment] 2022-04-22 12:09
No, that should be fine!

**Comment by Chris56** [comment] 2022-07-05 06:29
LineageOS for microG 17.1, Android 10, current version 5.41.13 (problem was the same with previous versions):
Trying to switch on creating Backups:
Signal calls the file manager and
I can choose (or even create) a directory to store the backup.
Returning to signal offers to switch on creating Backup: bang, endless loop.
I can even choose a directory like /sdcard/pictures, where my signal messenger does successfully save images to (thus having write privilege): still not accepted.
The debuglog (and also logcat) says:
[5.41.13] [main ] 2022-07-05 07:39:14.557 GMT+02:00 I BackupUtil: Backup directory is not set. Returning an empty list.
So, returning from the file manager, signal messenger thinks, there is no directory.
The complete debuglog: https://debuglogs.org/android/5.41.13/e2f0efed5e61f80da4c6bda2e2270e850f0a04301b911111921d8752b1750c97
I am fairly desperate, because I don't have a backup with years of history.
Also I need to move to a new android very soon and I would loose years of history.
I cannot transfer the history from linked devices (at least I don't know how).Therefore, I don't know how to continue.
I want to point out, that also other applications can write to /sdcard (and even signal can when saving images...)
It seems the interfacing between signal and the file manager stub, which chooses the directory (and should return the Backup directory).
Is the any way to use a different file manager, which may resolve the problem?
Chris
P.S.: Any more information needed? I have root access and can login with a shell to the system.

**Comment by SignalUser2022** [comment] 2022-08-22 09:37
Hello again, since there's no solution for this problem yet, I tried to use another phone to transfer the signal data to this new phone.
This also doesn't work. The two phones don't find each other and I get an error report even though I'm using the same Wifi, Bluetooth and Location services are activated and the Signal app has all needed permissions. 
Can I send the error report to someone?

**Comment by Chris56** [comment] 2022-11-01 10:19
The bug still exists!!
I've installed every signal update:every time I hoped, this would change the situation. However: no  change.
When enabling, I can choose (or even create one) a directory (definitely with write access by singal, as proven by saving attachments to it).
However, signal does not accept the return from the file picker stub (Log entry: [5.41.13] [main ] 2022-07-05 07:39:14.557 GMT+02:00 I BackupUtil: Backup directory is not set. Returning an empty list.).
I am fairly desperate, I will loose yous of conversations.
a) Is there a way (some settings, I have root access) to make signal think, such a directory exists?
b) Is there a way exchange the file picker? Maybe a different file picker will work?
c) Is there any other way to create a backup? Eventually I will have to either change the OS or change the device.

In desperate need of help
Chris

**Comment by Chris56** [comment] 2022-11-01 13:06
To be honest: I have no idea, how to replay the standard file picker with a different one. See my point b) from above.
So if you could point me to an alternative file picker and how to get it running: great.
However: with microG (see above): the normal google stack has been replaced by a free, open alternative.
However, this should not be a problem, as I have other phones running with microG an no problems with the file picker.

**Comment by cody-signal** [comment] 2022-11-01 14:06
Are they all running the same version of lineage?

**Comment by Chris56** [comment] 2022-11-01 14:49
Yes (at least they did before upgrade). I never had this problem on any lineageos system.
Is there a way to cheat, meaning make signal think, it already did a backup, thus not calling the file picker, but simply perform the backup (similar to saving an attachment (which works fine)?

**Comment by cody-signal** [comment] 2022-11-01 17:55
Not without a special build.

Can you send me an updated debug log?

**Comment by SignalUser2022** [comment] 2022-11-01 18:00
Same with me. I didn't change my LineageOS version within the last year and also after installing the latest Signal updates the backup still doesn't work.

**Comment by Chris56** [comment] 2022-11-01 18:20
The debug log is here:
https://debuglogs.org/android/5.52.5/63c927c156459c44cc50bba267857d075ee84434e94989f9012d655e68bf6df5
It still shows the line:
11-01 19:04:39.744  1727  1727 I BackupUtil: Backup directory is not set. Returning an empty list.

**Comment by Chris56** [comment] 2022-11-03 09:44
It gets even worse ...
I dirty flashed to LineageOS 18.1 , Android 11 with microG and still the same, even though the file picker has been updated.
(needless to say, that the file ficker works with other applications ...)
Debuglog is the same:
11-02 17:24:42.020  2244  2244 I BackupUtil: Backup directory is not set. Returning an empty list.
https://debuglogs.org/android/5.52.5/9fc53a801a465e6bb28ab8ad0970b9f33dc76d60add501f93b2f02c42dcec4ee

**Comment by cody-signal** [comment] 2022-11-04 00:56
I'll charge up my test lineage os device and give it a check, but at this point I'm at a loss as to what it could be. 

Can you try to sideload Files app from Google? I'm assuming you don't have play store but I'm sure with some googling you could find a site that mirrors apks for direct download. Here's the play store page: https://play.google.com/store/apps/details?id=com.google.android.apps.nbu.files&hl=en_US&gl=US

**Comment by Chris56** [comment] 2022-11-04 09:28
I'm using the microG version of lineage: https://lineage.microg.org/ (it was 10 now it is 11).
It might be an effect of microG.
On the other hand, using https://e.foundation/ which is based on lineage with microG also already incorporated works without any problem ...

**Comment by SignalUser2022** [comment] 2022-11-04 14:01
@cody-signal I tried to create the backup with several open source file pickers, it didn't work.
I'm also using Lineage OS without MicroG and it was never a problem to create a backup of Signal before. I created the last backup 1,5 years ago with the same phone I am using today and it worked flawlessly.

**Comment by Chris56** [comment] 2022-11-04 14:05
@SignalUser2022 Just to make sure:
It is not trivial to replace the file picker. Installing other file managers will not replace the picker. Did signal actually call a different file picker when trying to enable the backup?

**Comment by SignalUser2022** [comment] 2022-11-05 13:00
@Chris56 My description should have been more precise, sorry. I installed several other file managers and tried to create folders where Signal could create the backup. Changing the default file picker wasn't possible in the settings, also resetting all changes in the main settings of the OS to default didn't help.
Signal always called the file picker com.android.documentsui

**Comment by Chris56** [comment] 2022-11-05 16:59
@SignalUser2022 This is what I meant.
As soon as I find the time, I will try cody-signal's suggestion and try to install google file. In case I succeed installing google's file app, I will see whether that installation will also replace the file picker.

**Comment by Chris56** [comment] 2022-11-07 07:33
@cody-signal I have installed the goole files app.
However - as with all the other file managers I tried - it does not replace the file picker.
Thus, if I uninstall com.android.documentsui then signal cannot call a file picker at all (with google files installed) or if com.android.documentsui is not uninstalled, then I have the standard situation.
Because loosing all data of years of conversations was by far too risky or me, I have now transferred signal to an intermediate phone, then installed eOS (lineage plus microg), Android 11 and transferred signal back. Now I do have a backup (and unfortunately cannot do any bug tracking anymore).
Thanks for the support!

**Closed** 2023-01-13 19:10 UTC
Labels: wontfix

**Comment by viddha** [comment] 2023-05-14 06:43
I recently shifted to a Google Pixel 6 phone and started facing the same issue. Earlier, I used a Oppo F9 phone, and the backups worked absolutely fine. However, now every time I try to select the folder to backup the chats, I get reverted back to the previous screen, backup menu, where the button still reads 'Turn On' (Chat Backups). I went through this issue thread, and I would like to point out that Google Pixel phones have Files by Google as the default file manager app. Furthermore, I was able to save a copy of the debug log onto my phone, which means that there is no issue in supporting the writing of data.

My debug log - https://debuglogs.org/android/6.19.9/83fb2daa96529e5b5b5e32f94c274ef3d4b043b62278881bceaeb3bcb55d671b

Please help. Backing up signal is absolutely important for me.

**Comment by cody-signal** [comment] 2023-05-15 14:09
@viddha do you happen to have the developer option "Don't Keep Activities" enabled?

**Comment by viddha** [comment] 2023-05-16 14:02
Omg brother!! It worked 🥳. I don't know how to Thank You!! I just selected the folder and created a backup successfully.

Thanks again for being responsive and solving the issue! Signal is amazing! 🏅

**Comment by SignalUser2022** [comment] 2023-06-07 21:45
Thank you @cody-signal @Chris56 @alex-signal 
It worked.
Your guys are awesome :-)
