### ISSUE TITLE
Editing image Performance issue

### ISSUE THREAD

**Issue by bezoui-software** [signalapp/Signal-Android#10740] opened 2021-01-19 21:00 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
  Editing image is so slow,  the editing tool doesn't respond in real-time (big latency) when drawing or cropping image after using the blur pen and

### Steps to reproduce
- use blur in an image 
- try to crop the image or draw something

**Actual result:** Slow responding from the app and some difficult when editing image
**Expected result:** Editing image without any latency

### Device info

**Device:** OPPO F3
**Android version:** 6.0.0
**Signal version:** 5.1.9

### Link to debug log
https://debuglogs.org/ceb2f7a0caa54fb8faa58140c3a3d9be1f4302133b93e1adf76e5615154f17fb

**Comment by Xrasure** [comment] 2021-01-20 08:00
I can't reproduce this on my oneplus 6t with Signal beta, so i think that it will be fixed in the regular version soon

**Comment by bezoui-software** [comment] 2021-01-20 19:46
Oh yeah it's fixed in beta version, I tried and it worked successfully.

**Closed** 2021-01-20 19:47 UTC
