### ISSUE TITLE
"Signal has stopped" during backup restore

### ISSUE THREAD

**Issue by masgnl** [signalapp/Signal-Android#8441] opened 2018-12-11 20:50 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal has stopped working while restoring backup

### Steps to reproduce
- Fresh Signal install
- Copy backup file onto phone
- Start restoring process
-Backups starts slowing down around 19k messages 
-Signal crashes 

### Device info

**Device:** Moto G3
**Android version:** 7.1.2/LOS 14.1
**Signal version:** 4.31.5

### Link to debug log

https://debuglogs.org/fc07f1817faa8bfb9ecdca47d1b9563d6f48c6aee72122639b827153d79a8adf

**Comment by leafcutterant** [comment] 2018-12-15 21:19
If I'm not mistaken, this is a duplicate of #8355.

**Comment by greyson-signal** [comment] 2019-03-03 09:43
I think this is a dupe of #7975

**Closed by greyson-signal** 2019-03-03 09:43 UTC
