### ISSUE TITLE
Oppo - no notification if app is not opened

### ISSUE THREAD

**Issue by D4nte** [signalapp/Signal-Android#8517] opened 2019-01-08 23:57 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
#8400 is similar but not exactly hence opening this issue.

On Oppo phone, with battery optimisation settings sorted:
- do not optimize battery for Signal
- do not kill signal in background or if issue is encountered
- max notification priority in both signal and android settings

Notifications are not received except of the signal app is opened.
Sometimes notification are received if the signal app is in the background however, it is not great as if the signal app get closed then notifications stopped being received.

Please note I have unregistered and re-registered. This help as now I can receive notifications if the app has been opened and is still opened in the background (before I had to open the app in the foreground to receive notifications). However, if the app is closed (from the swith app menu, I am **not** talking about a force stop) then notifications stop.

### Steps to reproduce
1. start the phone
2. someone sends you a signal message (**not** SMS)
3. actual: no notification, expected: notification

1. start signal app, see all notification
2. close signal app (using the app switch menu)
3. someone sends you a signal message (**not** SMS)
4. actual: no notification, expected: notification

### Screenshots
Let me know if you need those

### Device info
Let me come back to you on this one (wife's phone)
**Device:** Oppo CPH1715
**Android version:** 6.0 (ColorOS V3.0.0i)
**Signal version:** 4.31.6

### Link to debug log
https://debuglogs.org/2403397b841eb983cc424600326d341eb2ff5c042a1296033d3a6d02e912a7da

**Comment by greyson-signal** [comment] 2019-01-09 00:01
Looking at the logs, we never received any GCM pushes. Oppo seems to be doing something fishy.

**Comment by D4nte** [comment] 2019-01-09 00:13
Happy to capture more logs if needed just to be sure.

**Comment by bme13** [comment] 2019-01-09 08:20
Hi. Don't know if you tried it already or if it's even possible with your phone, but based on this https://www.forbes.com/sites/bensin/2017/07/28/how-to-fix-push-notifications-on-oppo-phones/ you can try locking the app in the 'recent apps overview' see step 4 in the link.

**Comment by drale2k** [comment] 2019-01-10 10:39
I can confirm we have the same issue. No message or notification is received if the app is not active.

**Comment by AqwelF** [comment] 2019-03-08 08:15
Same issue on Oneplus 6T. I have to lock the app in the switch app menu to keep recieving notifications.
If the app is closed. i receive nothing until a launch the app manually.

What's new about this prob ?

**Comment by ramast** [comment] 2019-03-25 16:22
Same problem here, using LineageOS without Google Play Service.

**Comment by armeclemes** [comment] 2019-05-11 05:41
Same problem on Wiko.
But not on Oneplus 6.

**Comment by greyson-signal** [comment] 2019-05-31 14:31
Doing some cleanup. Closing as dupe of #8692.

**Closed by greyson-signal** 2019-05-31 14:31 UTC
