### ISSUE TITLE
A very quiet earpiece during voice calls [Poco X3 NFC]

### ISSUE THREAD

**Issue by Zipos** [signalapp/Signal-Android#11931] opened 2022-01-28 12:21 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

During calls, the top speaker is at least two times more quiet than it is during regular phone calls.
I'm running pixel experience ROM based on Android 12 but it is persistent on stock MIUI and multiple other ROMs as well.

### Steps to reproduce
- Open Signal
- Call somebody
- Notice that you can't hear much

**Actual result:** During voice calls, the earpiece speaker is horribly quiet, even on the highest volume. In the city center or even anywhere outdoor it makes talking absolutely not possible. Audio also appears to be really low quality but maybe that's just me.
**Expected result:** The volume of it should be the same as on regular phone calls.

### Device info

**Device:** Poco X3 NFC
**Android version:** 12 (Pixel Experience)
**Signal version:** 5.30.2 beta

### Link to debug log

https://debuglogs.org/fbdc1a88c0154e1acdfd0df34b0967d0e1f6fb4afef1fd5889ee834a076eca5e

**Comment by jim-signal** [comment] 2022-02-03 16:36
Hi @Zipos, this is probably a duplicate of #11943. The same setting referenced in that issue was also active for the beta. Please try calling again and let us know the result.

**Closed** 2022-04-11 20:02 UTC
Labels: wontfix
