### ISSUE TITLE
Wrong Picture Orientation when screen orientation is locked

### ISSUE THREAD

**Issue by newhinton** [signalapp/Signal-Android#12185] opened 2022-04-20 13:36 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When taking a picture while the screen is locked, the resulting image is often in the wrong rotation because pictures are usually taken in landscape. 

### Steps to reproduce
- Lock screen in portrait mode
- Rotate the device to take a landscape picture

**Actual result:** 
- image is still portrait, ignoring the 'usually correct' orientation

**Expected result:** 

while the screen content has to/should obey the screen orientation lock, the imagecontent should not. Signal should query the physical orientation of the device and show the picture according to the picture-content.

This is how camera apps handle it usually aswell as most messengers

### Device info

**Device:** Samsung S9
**Android version:** 11
**Signal version:** 5.34.10

**Comment by Tursko** [comment] 2022-04-20 20:31
I'm not sure if this is actually considered a bug, but I created FR for this in the forums a while back.

**Comment by newhinton** [comment] 2022-04-20 20:46
It is borderline, and depending on the viewpoint its either a bug or a feature request.

My reasoning is that since the image sent is rotated from the real-world-object-orientation, it is not working properly as it is rarely intended to sent rotated images

**Comment by VadimMuhtarov** [comment] 2022-04-21 10:15
I can confirm this on Galaxy A70, Android 11, Signal 5.35.3.
Also may be related to a wrong heic photos orientation selected from gallery and mentioned in 10493 bug

**Comment by Genis-Sage** [comment] 2022-04-21 19:05
@Tursko 
I assume, Signal devs count the behaviour as a bug, as there is already an open report about it

so this here is a duplicate of #8611

**Comment by alex-signal** [comment] 2022-04-22 12:07
Closing as a duplicate.

**Closed by alex-signal** 2022-04-22 12:07 UTC
