### ISSUE TITLE
Reply font does not follow the Signal setting for text size

### ISSUE THREAD

**Issue by l3jyeo** [signalapp/Signal-Android#8645] opened 2019-02-28 05:37 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Replies to messages do not follow the different in-app font sizes. It looks like the font size for replies stays at the default setting.

### Steps to reproduce
- Go into Settings, Chats and media, Message font size, set it to something other than normal
- Go into a chat and reply to a chat message

**Actual result:** The font size of the reply is different than the set font size in the settings
**Expected result:** The font size of the reply is the same as the font size in the setting

### Signal version
4.34.8

**Comment by greyson-signal** [comment] 2019-03-03 08:48
Duplicate of #8512

**Closed by greyson-signal** 2019-03-03 08:48 UTC
