### ISSUE TITLE
Ring call bug

### ISSUE THREAD

**Issue by DenisBeliant** [signalapp/Signal-Android#9813] opened 2020-07-01 19:37 UTC
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When we receive a call, the mobile doesn't ring or vibrate. It only vibrate when call request it's finish.

### Steps to reproduce
1. Make a call with two Signal's users.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Xiaomi Mi 9 Lite (CC9)
**Android version:** 9PKQ1.181121.001
**Signal version:** 4.65.2

### Link to debug log

https://debuglogs.org/24c4af929e25fb2b2dae5342304584da95ab14153b89ae5d7fec307df8aff62a

**Comment by johnmhm** [comment] 2020-09-17 14:09
Experiencing the same on Android 10.

**Comment by dsvk** [comment] 2022-01-31 23:38
Sounds like a duplicate of https://github.com/signalapp/Signal-Android/issues/8780?

I also experienced this while doing DND tests in https://github.com/signalapp/Signal-Android/issues/11055#issuecomment-1026275640 - **only** with DND active though (no missing call screen if DND is off) and only on one of my devices (Android 9), not on the other (Android 12). [Mentioned it](https://github.com/signalapp/Signal-Android/issues/8780#issuecomment-1026316726) on #8780 already.

**Comment by jknockaert** [comment] 2022-02-01 09:16
I think Signal is not properly using a call API and as a result Android cannot know a call is coming in; see #11512.

**Closed** 2022-04-09 15:59 UTC
Labels: wontfix
