### ISSUE TITLE
Feature-request : When no cellular data available, send text message to another signal user in non-secure way (sms)

### ISSUE THREAD

**Issue by chioubaca** [signalapp/Signal-Android#7447] opened 2018-02-28 17:01 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Question
Don't know if it's a bug or if this is by design : when I'm sending text message to another signal-user but my cellular-data aren't available, I would like to be able to send the message using a non-secure way (SMS).
I can clearly understand that this can mislead some user, maybe a good way to handle that would be to change the color of the "non-secure sending" button (put it orange for example ?)

It's more a feature request than an issue, so please vote and let me know if you think like me or if you'd rather keep the current design.

### Steps to reproduce
- disconnect cellular data on your phone
- open signal and send text message to another signal-user

**Actual result:** Message is not sent and a link proposing "try again" is displayed after a long timeout
**Expected result:** Message is sent using a non-secure method (SMS)

**Comment by haffenloher** [comment] 2018-02-28 18:11
> when I'm sending text message to another signal-user but my cellular-data aren't available, I would like to be able to send the message using a non-secure way (SMS)

Long-press the send button to temporarily switch to SMS.

If what you want is an automatic fallback, that's a duplicate of e.g. #6377.

**Closed** 2018-02-28 19:11 UTC
