### ISSUE TITLE
Backups are deleted when app is uninstalled (or reinstalled) when using SD card

### ISSUE THREAD

**Issue by xeals** [signalapp/Signal-Android#7942] opened 2018-06-26 09:06 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Backups may be being produced, but are functionally useless if a user is required to restore from one.

With an SD card inserted, the [backup location](https://github.com/signalapp/Signal-Android/blob/70c2a863cca7984fec072913148fb4651e9644e4/src/org/thoughtcrime/securesms/util/StorageUtil.java#L17) defaults to the `Android/data/org.thoughtcrime.securesms` folder on the external SD. This is completely unsuitable for a backup location as **[the folder is cleared when the parent app is removed](https://developer.android.com/reference/android/content/Context.html#getExternalFilesDirs(java.lang.String))**. #7912 confirms this issue, but not the implications of it.

The internal storage path (`/sdcard/Signal/Backups`) won't be searched unless the SD card is completely removed from the device (not just unmounted).

### Steps to reproduce
- insert SD card
- set up Signal and backups
- remove and reinstall Signal (or just clear data)
- attempt to restore from backup

**Actual result:** First-time wizard is run
**Expected result:** Backup should be found and restored from

### Device info
**Device:** Motorola G5 Plus (XT1685)
**Android version:** 8.1.0
**Signal version:** 4.21.6

### Link to debug log
Unable to link debug log as I can't restore from a backup I don't have.

**Comment by greyson-signal** [comment] 2018-06-28 23:42
Dupe of #7845. Thanks!

**Closed by greyson-signal** 2018-06-28 23:42 UTC
