### ISSUE TITLE
Sending Images does not work

### ISSUE THREAD

**Issue by theBoatman** [signalapp/Signal-Android#13708] opened 2024-09-24 09:11 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
We have problems sending pictures from one phone to two other devices. The pictures seem properly sent on the sending device, but do not download on the receiving ones.

### Steps to reproduce
It is probably not reproducible easily because nothing special was done, but this was happening:

- phone1 received several photos from a third person. (multiple photos in 3 messages) 
- phone1 forwards all of them to phone2  (most probably around timestamp 2024-09-23 20:14:16)
- on phone2 some photos are visible, but some do not download. There is a retry-button, which seems to restart the download, but fails to do so.
- phone2 tries to forward the messages to phone3, which was not possible (error message unknown)
- later phone1 forwards the photos to phone3. 
- on phone3 none of the photos are downloadable (around timestamp 2024-09-23 21:40:18)
- phone3 has a linked desktop version, which also doesn't show the photos

Hint: phone1 is always in airplane mode when not in use. It might have happened that it went offline during the first sending process and left the attachments in an unrecoverable state.

### Device info phone1
**Device:** Xiaomi Redmi 4X
**Android version:** 14, API 34 (4e0569a71a, lineage_Mi8937-userdebug 14 AP2A.240705.005 4e0569a71a)
**Signal version:** Signal 7.17.5 (1462, 146200) (e81fc2900da9)

### Device info phone2 and phone3 (identical)
**Device:** Google Pixel 5
**Android version:** 13, API 33 (38682b0ab6, lineage_redfin-userdebug 13 TQ3A.230901.001 38682b0ab6)
**Signal version:** Signal 7.17.5 (1462, 146200) (e81fc2900da9)

### Link to debug log
phone1: https://debuglogs.org/android/7.17.5/8a3499bb69db669b959c1f90dbb78fb72b38abe7119ff8aa524bf281d704f16c
phone3: https://debuglogs.org/android/7.17.5/775e902e22e1949d8b5d1e2bc7abae477188fa9d128b2ffe9e1ce7a042432d24

**Comment by greyson-signal** [comment] 2024-09-24 18:24
This is addressed in 7.17.6, which is currently rolling out to production. Note that the issue is the sender, not the receiver. Unfortunately we can't fix any currently-undownloadable attachments, but once the sender upgrades, future attachment sends should work.

**Closed by greyson-signal** 2024-09-24 18:24 UTC
