### ISSUE TITLE
Call's elapsed time is not shown

### ISSUE THREAD

**Issue by MarcinOrlowski** [signalapp/Signal-Android#8200] opened 2018-09-11 20:53 UTC
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The Call Screen's elapsedTime widget is not being used therefore there's no call duration
shown to the user.

### Steps to reproduce
- do the call
- once connected, the call elapsed time should be shown

**Actual result:** nothing is being shown
**Expected result:** call elapsed time should be visible during the whole call

**Comment by MarcinOrlowski** [comment] 2018-09-11 20:53
I am going to submit PR addressing this though.

**Comment by greyson-signal** [comment] 2018-09-13 14:43
This is a feature request, not a bug. But I understand that you may be making this so you can link something in your PR. But don't worry, you can make a PR without an attached bug :) Closing this.

**Closed by greyson-signal** 2018-09-13 14:43 UTC
