### ISSUE TITLE
photo get zoomed

### ISSUE THREAD

**Issue by leonardoporp** [signalapp/Signal-Android#8451] opened 2018-12-15 10:49 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I take a photo from Signal the photo get zoomed by itself
### Steps to reproduce
- take a photo in Signal

**Actual result:** photo get automatically zoomed
**Expected result:** photo shouldn't be zoomed 

### Screenshots
Not necessary

### Device info

**Device:** Samsung Galaxy s8 plus
**Android version:** 8.0.0
**Signal version:** 4.31.6

### Link to debug log

https://debuglogs.org/09a98e0b1d87c423d8b3c9b933edd46a78c3b99411267707c455a2509e179df9

**Comment by leonardoporpora** [comment] 2018-12-15 12:37
I have pixel 2 XL but I don't have this problem

**Comment by sirlada** [comment] 2018-12-15 14:07
this is a dupe of #8310

**Closed** 2022-02-04 16:17 UTC
Labels: wontfix
