### ISSUE TITLE
[Usability] On unmodified fresh installation, app is red, the icon to start the app is blue

### ISSUE THREAD

**Issue by suhrawardi** [signalapp/Signal-Android#10986] opened 2021-02-17 17:44 UTC
- [X] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I recently installed the Android Signal app on a Sonim XP8800  with Android 8.1.0.
It's a fresh install with the default settings. 
The app appearance when I use it is bright red. When I want to open it via a shortcut on my home screen, I thus look for a red app icon. But the icon is bright blue. This confuses me.
I think the usability would be increased if the app theme and the icon use a similar color.

### Steps to reproduce
- Be a Signal n00b
- Install Signal on Android
- Do not configure anything
- Use the app
- Close it
- Try to find the app again

**Actual result:** As I identified Signal with the bright red color of the App, I cannot find my Signal application.
**Expected result:** I can easily find Signal cause the app icon relates to the look and feel of the App itself.

### Device info
**Device:** Sonim XP8800
**Android version:** Android 8.1.0
**Signal version:** 5.3.12

**Comment by alan-signal** [comment] 2021-02-17 17:50
> Install Signal on Android

Where did you install it from?

**Comment by suhrawardi** [comment] 2021-02-17 17:53
I installed it from the Google Play Store.

**Comment by alan-signal** [comment] 2021-02-17 17:53
> The app appearance when I use it is bright red.

This is not normal. Please provide screen shots and a debug log.

**Comment by suhrawardi** [comment] 2021-02-17 17:56
Ah, I see it's only red for the person I'm chatting with. If I try to send messages to some-one else it's a different color. But still, even on the blank home screen, it does not make a connection for me to the icon itself... :-)

**Comment by suhrawardi** [comment] 2021-02-17 18:06
![Screenshot_20210217-185841](https://user-images.githubusercontent.com/32413/108247667-3cba5200-7153-11eb-8cd9-7fc7b5887a2e.png)

**Comment by alan-signal** [comment] 2021-02-17 20:11
OK cool, closing as not a bug, but please use the community forum if you want to make suggestions https://community.signalusers.org/

**Closed by alan-signal** 2021-02-17 20:11 UTC

**Comment by suhrawardi** [comment] 2021-02-17 20:13
I think it _is_ a bug in the usability of the Signal app though. It might be a small thingie, but it might improve the Signal experience a lot for many people.
