### ISSUE TITLE
Image sharing when Signal is locked not working as expected

### ISSUE THREAD

**Issue by dinosmm** [signalapp/Signal-Android#8354] opened 2018-11-10 09:10 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When sharing an image from another app, if Signal is locked it will present the fingerprint unlock screen, and as soon as I unlock it the phone will go back to the image-containing app, instead of continuing to Signal to let me choose a contact. If I want to share the image, I have to 'share' it again. Since Signal is unlocked this time, it works fine.

### Steps to reproduce
- Open an app where there is an image to share (I've tried it with Google Photos and with Telegram)
- click on the Share button
- Choose Signal
- Signal lock screen appears; touch fingerprint sensor to unlock Signal

**Actual result:** The phone exits Signal, and the original app with the image I want to share is shown.

**Expected result:** See Signal's contact selection screen

### Device info

**Device:** Samsung Galaxy S7 Edge SM-G935F
**Android version:** 8.0.0
**Signal version:** 4.30.2

### Link to debug log
https://debuglogs.org/dd85aca7d7993dceb30458f819e579ca245d569cf2166ae684e49e2517c37b6a

**Comment by johanw666** [comment] 2019-03-22 08:39
The same happens with sharing links, I was about to open a new issue when I found this. After unlocking Signal I have to share it again.

**Comment by Ndr6** [comment] 2020-05-01 09:06
This also does this for me when sharing an image or a video, but not links or text, from the "Sync for Reddit" app.
Moreover, the result is more random for me. After unlocking, sometimes I'm sent back to the app I shared the image with, sometimes I'm sent back to the app launcher, and sometimes I'm sent to the Signal conversations list.
I can provide debug logs if needed.

**Comment by wnhre2ur8cxx8** [comment] 2020-12-04 10:52
There are multiple issues already, and the issue exists since a few years actually.

Current duplicates: #8955 #8528 

See comment here about history of the issue: https://github.com/signalapp/Signal-Android/issues/8528#issuecomment-463667384

**Comment by greyson-signal** [comment] 2020-12-04 16:00
Closing as duplicate of #8528

**Closed by greyson-signal** 2020-12-04 16:00 UTC
