### ISSUE TITLE
Not all chat bubbles follow colour change without re-entering chat

### ISSUE THREAD

**Issue by spagy** [signalapp/Signal-Android#13212] opened 2023-10-09 21:44 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When changing the chat colour, (directly or indirectly, by changing the wallpaper colour, with the chat colour set to 'Auto'), some chat bubbles don't change colour until after exiting the chat and re-entering.

### Steps to reproduce
- Open a chat
- Go to 'Chat settings'
- Go to 'Chat color & wallpaper'
- Go to 'Chat color'
- Select a different colour (the chat bubble colour will change in the preview)
- Hit back three times to get back to the chat
- See that the old colour is still present for 'simple' chat bubbles. However the following bubbles do change colour: messages that include a link preview, messages that are either a reply to a specific message, or have been replied to. This applies to previous messages too, if you scroll back.
-  Hit back again to exit the chat
- Re-enter the chat and see that all chat bubbles now have the new colour.

**Actual result:** Only some chat bubbles change colour when a new chat colour is selected.
**Expected result:** All chat bubbles change colour when a new chat colour is selected

### Screenshots
Before changing the colour: all chat bubbles original colour
<img src="https://github.com/signalapp/Signal-Android/assets/5479401/0375cfb3-8eb6-4603-ac4e-54a4f034ea1a" width="200" />

After changing the colour, but not leaving the chat: replies, and messages that are replied to change colour
<img src="https://github.com/signalapp/Signal-Android/assets/5479401/7ad226a8-cf83-4f02-b2f6-6d578aaf749b" width="200" />

After leaving the chat and re-entering: all chat bubbles have changed colour
<img src="https://github.com/signalapp/Signal-Android/assets/5479401/0537002f-eec3-4ecb-8c6b-10c0bfaa711b" width="200" />

### Device info
**Device:** Fairphone 3
**Android version:** 13
**Signal version:** 6.34.5

### Link to debug log
https://debuglogs.org/android/6.34.5/8b731a554b9f5fc10651f839f9556f4788c646a08e247aa1abf4f66b3533dac5

**Comment by gouenji-shuuya** [comment] 2023-10-12 13:44
Also, setting a custom wallpaper, while looking fine during the process of setting it, is actually stretched in the actual chat.

I think this is a related issue, caused by some underlying bug.

**Comment by alex-signal** [comment] 2023-10-13 12:21
@gouenji-shuuya Not the related issue. The colors aren't changing because the mask is cached in memory and not cleared when changed. The stretched wallpaper feels like a cropping issue for the wallpaper background, which we'll also look into.

**Comment by gouenji-shuuya** [comment] 2023-10-13 13:31
@alex-signal I found out force closing and opening corrects the wallpaper. So definitely some issue in memory.

**Comment by alex-signal** [comment] 2023-10-16 12:28
@gouenji-shuuya This is fixed in a later version of Signal. (https://github.com/signalapp/Signal-Android/commit/5cc85cc860d8c9158f4540f925e3b7d6d989503f)

**Comment by spagy** [comment] 2023-11-20 01:39
Although I originally noticed this while changing the chat colour settings, I'm also getting this issue quite a bit when I switch between a chat in [a chat bubble](https://developer.android.com/develop/ui/views/notifications/bubbles), and in the main app.

For example,
1. Open a conversation in the Signal app. The chat displays with the right colours.
2. Open a chat bubble (from notifications) for a chat with different colours. This chat also displays with the right colours.
3. Close the chat bubble (but don't dismiss it)
4. The original chat in the app now renders with the wrong colours.
5. In the app, exit the chat and re-enter it. This chat now displays the right colours again.
6. Tap on the bubble chat again to re-open it. Now _it_ will display the wrong colours.

**Comment by cody-signal** [comment] 2024-01-19 15:25
This has been fixed and will be out in 6.45

**Closed** 2024-03-20 07:51 UTC
Labels: wontfix
