### ISSUE TITLE
Messages and Stickers

### ISSUE THREAD

**Issue by ElDiosX** [signalapp/Signal-Android#11785] opened 2021-11-23 12:40 UTC
When you reply with a sticker, it doesn't show the answered message, pls try to fix it for Signal > WhatsApp

**Comment by greyson-signal** [comment] 2021-11-23 14:27
I also want this, but given that it's currently working as intended, I'm going to consider this a feature request and close the issue per our guidelines. Thanks!

**Closed by greyson-signal** 2021-11-23 14:27 UTC
