### ISSUE TITLE
Signal Forcing Users to Allow Remote Storage

### ISSUE THREAD

**Issue by jbaker6953** [signalapp/Signal-Android#9625] opened 2020-05-15 01:01 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal is forcing users to submit to having their information stored remotely ... God knows where. They pinky promise it's encrypted, but users just have to trust that it is.

### Steps to reproduce
- Open Signal. Be prompted to create a PIN to "secure" remote data storage. Impossible to decline or disable.

**Actual result:**
Signal doesn't respect user's choice about whether to trust unidentified third party storage.

**Expected result:** 
Signal respects a user's decision whether to entrust their data to a third party.

### Device info

**Device:** Google Pixel XL
**Android version:** 8.1.0
**Signal version:** 4.59.9

**Comment by igor2x** [comment] 2020-05-15 06:52
This report violates Signal/Android bug reporting rule: "If feature works and you don't like how it works, it is not a bug."

In this case, this is not official bug, but feature request. Signal uses forum for feature request. Please join us, Signal communitiy, on Signal forum: https://community.signalusers.org/
where is very vibrant and welcome community. Please open new forum thread and set "Feature request" as question option.

Please also, be so kind and close this bug report in github, because it does not belongs here.

**Closed** 2020-05-15 16:46 UTC
