### ISSUE TITLE
No callback for registration attempt of landline phone number

### ISSUE THREAD

**Issue by MatejKovacic** [signalapp/Signal-Android#8342] opened 2018-11-06 19:58 UTC
I am trying to register Slovenian land line number (+386xxxxxxx) on Android.

This has been working in the past, but not anymore.

What I am trying to do? For a phone number, I enter land line. Which, of course, does not accept SMS messages.

So I wait a little and then click in an Signal application to call me tell me verification code.

However, I never get the call. It is simple not working.

Any idea what is the issue? Foes Signal servers does not support land lines at all?

**Comment by igor2x** [comment] 2018-11-07 18:41
@MatejKovacic, Signal/Android project uses GitHub **exclusively** for bug reporting. May I invite you to the [Signal Community forum](https://community.signalusers.org/) where is very vibrant community and you can get all kind of advices. You can also use [official Signal support](https://support.signal.org/hc/en-us/requests/new) if you prefer, but it may take a while, because they are swamped. I suggest to use forum.

Also each message on this bug report triggers hundreds of mails for bug mail subscribers, so please avoid posting non-bug requests.

This non-bug report is going to be closed down shortly by project maintainer.

**Comment by MatejKovacic** [comment] 2018-11-07 19:12
Sorry, but it seems to me this is a bug. Verification calls are terribly delayed. I consider this a bug.

**Comment by igor2x** [comment] 2018-11-07 21:07
@MatejKovacic, there are several sub-projects in signalapp one of them is Signal-Android. When Signal on Android is installed, app sends some random number to server. Server sends message to phone-SMS-or-call system and that system has to send SMS or establish call with Signal-Android. Because SMS or call never gets to Signal-Android, this is not Signal-Android problem or bug. Maybe it is a bug in one of the server components, one of the server sending SMS/calls, maybe even your phone-system ISP or maybe even you not typing in correct number. I don't know which of the components do not work as expected, but I am pretty sure this is not "Signal-Android sub-project" problem or bug.

Like I have suggested, use official Signal support site. There are Signal administrators that can check which of the server components did not do the job in your case of sending SMS or making call. I am also pretty sure if you used forum up till now, you would already got few of the suggestions. For example [guy from India](https://community.signalusers.org/t/registering-in-india-airtel/4684/11) did not get call and there are tons of answers and possible solutions on that thread alone.

I still thing this is not Signal-Android subproject problem or bug and so maintainers are probably going to close this bug report down.

P.S. We are making too much noise. Bug mail subscribers are not going to be happy.

**Comment by five-c-d** [comment] 2018-11-08 01:28
@MatejKovacic, this **is** definitely a bug, thank you for the bug-report.   It is possibly going to be considered a duplicate of bug #7980 -- it depends on whether Greyson and the other OWS folks want to track a huge generic issue for "delayed&lost registration conf-codes" -- or would prefer to rename 7980 for India-specific delays only, and keep this 8342 for Slovenia-specific delays.  It is mostly a bureaucracy-question methinks, but if I had to make a recommendation it would be to track each country separately, but also keep one meta-issue (rather than reopen #6027 put it into a wiki subpage on github preferably) which gives a table of all known country-and-carrier combinations that have troubles.  

Signal-Android *is* the correct repo to report this bug, because the SMS-and-robocall troubleshooting steps differ depending on the enduser's platform, android and ios are not the same codebase when it comes to capturing debuglogs during the registration-phase (or with respect to offering restore of encrypted backups during the registration phase).  One could argue that Signal-Server is the correct repo to report Twilio-backend-related bugs... but that is a moot point, there ***is*** no issues-area for that repo.  @Igor2x if you would like to discuss where to track registration-bugs please open a forum-thread  :-)   and I will be happy to participate there.  But in the meantime, SMS-and-robocall failure is generally a bug, which needs to be github-visible, since if there is a misconfiguration on the signal-server backend or on the twilio-backend-dependency, only signal-server devs at OpenWhisper can fix those. 

More usually it is a carrier-specific problem, and those are tough to pin down, which is why it is SOMETIMES preferable to shift over to a forum-conversation for the detailed troubleshooting portion.  Talking back and forth in github about many different close-but-not-quite-identical failures with registration is painful.  For that matter, troubleshooting registration is also painful, because there are a lot of moving parts: 

*  properly-configured smartphone OS (are you still running CyanogenMod/LineageOS on your devices nowadays @MatejKovacic ?  usually should make no difference since in this case you are associating the device with a landline number... so 99% ruled out, but to be positive there are no exceptions happening during the registration steps, there is a new signal4android feature where tapping eight times on the floating phone-icon during registration will permit capturing a debuglog, can you grab one please just to positively rule out the OS or the signalapp innards being at fault somehow here?  this would also rule out inadvertent rate-limiting and the HTTP 413 error) 
*  internet access (**ruled out** in this case)
*  signal4smartphone (**ruled out** in this case)
*  properly formatted E.164 telephone number (**ruled out** in this case since a call came in, and the debuglog shows correct +386xyyyzz30 type of eleven-digit <a href="https://en.wikipedia.org/wiki/Telephone_numbers_in_Slovenia">Slovenian landline format</a> as opposed to twelve-digit-mobile-number format)
*  signal-server and the twilio sms api process (possible but unlikely ... 99% **ruled out** here since this is a landline, though signal-server *does* need to handle the error-message and continue on... "SMS cannot be sent to landline... Twilio REST API will throw a 400 response <a href="https://www.twilio.com/sms/guidelines/si">with error code 21614</a>, the message will not appear in the [twilio-backend] logs" ... similarly the same page says that although Slovenia operators support inbound longcode SMS, that the twilio servers require provisioning&using an alphanumeric SMS-identifier instead?) 
*  signal-server and the twilio robocall api process, including <a href="https://github.com/signalapp/Signal-Server/blob/master/config/sample.yml#L11">the callback to signal-server</a> (very possible... either could be causing the bottleneck, twilio <a href="https://twilioinc.wpengine.com/2017/11/chaos-engineering-ratequeue-ha.html">has server-side queues</a> on a per-twilio-number basis, and signal-server is <a href="https://github.com/signalapp/Signal-Server/blob/master/src/main/java/org/whispersystems/textsecuregcm/sms/TwilioSmsSender.java#L45">also directly involved</a> in the completion of robocalls) 
*  country-specific telco regulations applied to inbound traffic (possible e.g. in Slovenia and other EU countries since ~2016 there is <a href="https://support.twilio.com/hc/en-us/articles/223183188-Origin-Based-Pricing-for-European-destinations ">taxation on inbound calls from the USA</a> which may need to be routed differently by the carrier) 
*  country-specific or carrier-specific behaviors/subcontractors/glitches  (possible... cf issue 8148 for example) 
*  carrier specific gateway misconfigurations (very possible usually in these cases, but less likely on landlines methinks... still, if you do not mind saying, what landline-carrier aka landline-operator are you using? internet suggests Telekom Slovenije is the main corporation but that maybe Amis Telekom and T-2 are also providing services nowadays... are you paying your fees to any subsidiary corporation rather than direct to the landline-network-operator?) 
*  cellular connection with sufficient bars (or in this case landline ... thus **ruled out**) 
*  device-specific configuration related to incoming international texts&calls (is the landline number on any sort of do-not-call registry, or does it have incoming international numbers blocked as part of the carrier-provided feature-set in your telco plan, or anything like that?  since you did receive the call once, this is also 99% **ruled out** in your specific case, but worth mentioning for future readership)  

Since relatively few of those moving parts are controlled by signalapp OR by signal-server, compared to most github bugs, it is usually hard to pin down where the blame belongs even when debuglogs *are* available.  I've added a forum-thread for Slovenia, and contacted somebody there who I believe lives in the country.  Here is the link, please answer questions over there, or ask new ones, as applicable (you can login to the signalUsers forum with your github username if you like).  https://community.signalusers.org/t/robocall-to-register-seriously-delayed-slovenia-landline-among-others/4745

**Comment by MatejKovacic** [comment] 2018-11-08 10:49
Hi,
thank you for your reply.

Yes, I am using LineageOS (device is Nexus 5). I also tried Redmi 5 Plus 3 (with original Android), and there was the same issue. I have working Internet connection and I also entered properly formatted E.164 telephone number.

Anyway, it seems it is not just a Slovenian or Indian specific problem. Here  is the report from some German guy (using German land line with +49 prefix), experiencing the same problem: https://github.com/AsamK/signal-cli/issues/160

I will check Signalusers community site.

**Comment by five-c-d** [comment] 2018-11-09 15:03
@MatejKovacic, per my replies in signalUsers it looks like you are either experiencing a weird situation-specific glitch on the Telekom Slovenije backend (tried two landlines at least... but bungabunga reports success with other landlines from that same carrier in that same country recently), or you are having a weird situation on the twilio-backend where the twilio-number-queues you are assigned to are backlogged (whereas bungabunga's friends did not have the same thing happen).  

@greyson-signal, or somebody else with such access, can you look into the twilio logfiles and/or signal-server logfiles for these registration-attempts please == https://community.signalusers.org/t/robocall-to-register-seriously-delayed-slovenia-landline-among-others/4745/11  

In addition to <a href="https://debuglogs.org/b1dcc66af39a10f0c7e3dbd69901e7b8d388a1032de9ae02ed9645e692e0174f">the debuglog there for LineageOS</a> custom ROM on nexus trying to register +386xxxxyy60 landline, there was also testing done on a stock APK on a stock ROM on another device (Redmi), as well as testing on a second +386xxxxyy30 landline number.  Some exceptions in the debug-log, "Authorization Failed" after PushNotificationReceiveJob :: doWork, but those seem to be unrelated to registration-via-landline-woes (to my eyes at least).  Not carrier-specific, not country-specific, not device-specific, not even landline-number-specific... either a weird glitch on signal-server and twilio-dependency, or a weird glitch locally.  

Matej:  can you please call tech support of Telekom Slovenije and see if they are willing to work with you and/or with OpenWhisper&Twilio to look into this.  And if you have any other exact-debuglog-timestamps, e.g. from your Redmi, those would be worth uploading here to github methinks.  Are the xxx30 and xxx60 numbers both at the same physical location, i.e. have the same upstream telco substation/router/whatnot?  Sorry things are not working properly, but with persistence and a bit of luck mayhap we will get it solved  :-)

**Comment by MatejKovacic** [comment] 2018-11-10 08:55
Well, I can try contacting Telekom Slovenije, but I guess they will not be very happy and willing to cooperate, since a few years ago I was a member of the team which "hacked" their mobile network... :)

**Comment by five-c-d** [comment] 2018-11-16 04:07
From forum-comments it looks like MatejKovacic was successfully able to register (unknown what changed but presumably a temporary server-side bottleneck at carrier-or-twilio-or-signal-server "fixed itself" or was fixed without notice).  

@wizardofid , are you in a position where you can test the speed of robocalls again please?  Are you also in Slovenia now, by the way, or another country-code, where you are seeing the many-hour-delayed robocalls?  An older github comment of yours suggests Germany, there is a forum-thread about that country here, https://community.signalusers.org/t/call-verification-takes-forever/4479 , with one +49 number having maybe-still-unsolved problems 4 weeks ago, plus a more recent problem this past week that (like Matej in Slovenia) seemed to "fix itself" without really being resolved.

**Comment by MatejKovacic** [comment] 2019-12-05 12:30
Hi, just tried it, and the problem appears again.

**Comment by MatejKovacic** [comment] 2019-12-07 10:21
Is anyone working on Signal issues or not?

**Closed** 2022-02-04 07:38 UTC
Labels: wontfix

**Comment by aventura-ms** [comment] 2025-01-21 16:45
can you find out how to register a landline phone today with signal api?

I have been trying all day and it keeps telling me that I have to receive a sms first. It doesn't make sense. My landline phone can't receive sms.

```
signal-api@61ad1d46ac9e:/$ signal-cli --config /home/.local/share/signal-cli -u +4930xxxxxxx register --voice
Failed to register: Invalid verification method: Before requesting voice verification you need to request SMS verification and wait a minute.
signal-api@61ad1d46ac9e:/$ 
```
