### ISSUE TITLE
Failure to be added to group chat

### ISSUE THREAD

**Issue by lindasdoyle** [signalapp/Signal-Android#8640] opened 2019-02-26 08:15 UTC
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I couldn't send messages in a group chat (I could to individuals), I could type but the messages were forever trying to send. 
I have seen that in previous issues that group chat messages were not sending due to server issues. That is not the case here because I could messages individuals in the group chat separately, and they could all message each other in the group chat. 

### Steps to reproduce
- I left the group chat
- I asked my friend to re-add me
-  He couldn't because it says I am still a member
- I uninstalled and reinstalled Signal

**Actual result:** He still cannot add me back to the group chat
**Expected result:** To be added to the group chat and to be able to send messages

### Device info

**Device:** Sony Xperia
**Android version:** 8.0.0
**Signal version:** 4.34.8

### Link to debug log
 Signal does not report what is happening as a bug.

**Comment by 2-4601** [comment] 2019-02-26 10:41
>- I asked my friend to re-add me
>- He couldn't because it says I am still a member

He can still add you even though Signal shows you are still a member. Please ask your friend again to add you even though it seems counter-intuitive.

>### Link to debug log
>Signal does not report what is happening as a bug.

Signal is most likely reporting about the bug but it's only visible in the debug log :) Please try to capture one next time when you can't send a message in a group.

**Comment by greyson-signal** [comment] 2019-03-03 09:15
Almost certainly a dupe of #8602. Messages are stuck in that thread, so the rest of the group can't receive your 'group leave' message either.

**Closed by greyson-signal** 2019-03-03 09:15 UTC
