### ISSUE TITLE
Photo preview mostly black

### ISSUE THREAD

**Issue by narayaana** [signalapp/Signal-Android#11212] opened 2021-04-15 15:03 UTC
Let's begin with a checklist: Replace the empty checkboxes [ ] below with checked ones [x] accordingly. -->

- [x ] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

When trying to change profile photo or share photos, preview show most photos in black. Picking any of these black photos will take seconds if not minutes to send.
This problem does not occur the first time one opens the photo selection after installation.

### Steps to reproduce
- click open photo selection on Huawei p30 pro
- most photos are just black
- when selecting any of these photos, it takes more than 30 seconds to send or add to profile

**Actual result:** same as steps to reproduce.

**Expected result:** 
I want to see my photos to choose them !
Better performance for posting would be good.

### Screenshots

![Screenshot_20210415_224956_org.thoughtcrime.securesms.jpg](https://user-images.githubusercontent.com/52987462/114889889-1bb56b00-9e3d-11eb-8d50-6764c03a5d65.jpg)

### Device info

**Device:** Huawei p30 pro, vog l29
**Android version:** android 10, kernel 4.14.116
**Signal version:** 5.7.6 (but this has been going for a few versions already)

### Link to debug log
N/A

**Comment by Dhanurjan** [comment] 2021-04-20 22:07
yes for me too.
Nokia 2.2
android 10

**Comment by strnad** [comment] 2021-04-27 17:04
I have same problem on Huawei P30 pro with android 10. it is really annoying issue that makes me think about replacing signal with something else :-/

**Comment by varac** [comment] 2021-04-30 19:48
Similar issue:  #11014

Possible workaround: Reducing the picture size for new pictures taken with the camera app down to 2.1 megapixel "fixed" it for me (although this is just a temporary stop-gap measure until this gets fixed properly).

**Comment by aPollO2k** [comment] 2021-05-05 05:46
I have the same issue with Huawei P30 Pro / Android 10 / EMUI 11 / C431E8R2P3

**Comment by cody-signal** [comment] 2021-06-08 23:39
Can y'all provide updated debug logs after encountering the issue? I've been trying to reproduce on multiple devices and haven't been able to. Where is the media coming from that's having problems? Are they photos? Downloads? From other apps?

**Comment by aPollO2k** [comment] 2021-06-09 09:53
Here is my debug log: https://debuglogs.org/ae4a41c69c0ab1b39a73211636c9fe947f9126791488b12c1e6e51af5b7b9e75

Around 2021-06-09 11:41 i have tried to send a picture.

Steps i have done:

1.  Opened Signal
2. Opened a conversation
3. Used the + to open the attachment menu
4. Go on "Gallery" to slect a photo
5. Got a "black" gallery with no previews
![grafik](https://user-images.githubusercontent.com/5796295/121333492-25c58880-c919-11eb-83fc-1e1dd3ac5a94.png)
6. Send a black photo (that took a long time)

**Comment by cody-signal** [comment] 2021-06-09 15:17
@aPollO2k thanks! and these are all photos/videos taken with the default camera app? Is it all media that shows up this way, or just from the camera?

**Comment by aPollO2k** [comment] 2021-06-09 16:37
> @aPollO2k thanks! and these are all photos/videos taken with the default camera app? Is it all media that shows up this way, or just from the camera?

The media you can see at the screenshot are photos and videos taken with the default camera app.
But not only the media taken by the camera app is affected. Other photos/videos is also sometimes black. For example screenshots, screencasts or media received via signal, whatsapp or downloaded from web.
As far as I could see there is no difference.

I can remember I had the same issue with whatsapp a long time ago. When I bought the Huawei P20 Pro. but it was fixed very soon. I can not say if it was fixed from whatsapp team or from Huawei. but it was exactly the same behavior. Black preview.

**Comment by DarkoVeberic** [comment] 2021-07-06 20:16
Duplicate of #10394

**Closed** 2022-02-02 08:59 UTC
Labels: wontfix
