### ISSUE TITLE
Video sending error -> MediaMetadataRetriever setDatasource failed

### ISSUE THREAD

**Issue by NightDeveloper-wq** [signalapp/Signal-Android#10342] opened 2020-12-28 14:12 UTC
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I keep getting this error when I want to send videos over 5 minutes. Some videos are posted, some progressbar just keeps turning and notification has shown. When it does not give an error, the compress process takes a long, long time and it never ends.

### Steps to reproduce
- I pressed the bottom + menu
- Selected gallery menu
- Selected 7 videos in Camera folder
- Trim videos and click send button

**Actual result:** All videos are sending
**Expected result:** Sometimes videos aren't sending

### Device info

**Device:** Huawei P30 Pro
**Android version:** 10.0.0
**Signal version:** 4.78.5

### Link to debug log

```2020-09-14 14:36:55.787 3646-4017/?  E/media-converter: error converting
        IllegalArgumentException from the setDataSource() call.
      2020-09-14 14:36:55.787 3646-4017/? java.lang.IllegalArgumentException
      2020-09-14 14:36:55.787 3646-4017/? android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:68)
        at .InMemoryTranscoder.transcode(InMemoryTranscoder.java:207)
```

**Comment by Genis-Sage** [comment] 2020-12-29 14:14
Hey @NightDeveloper-wq
could this error be similar to or a duplicate of #10135

Since the debuglos are already gone, I don't know, if it's the same exception

**Closed** 2022-02-03 13:25 UTC
Labels: wontfix
