### ISSUE TITLE
Signal using a shitcoin for payments

### ISSUE THREAD

**Issue by k3tan172** [signalapp/Signal-Android#11177] opened 2021-04-07 13:00 UTC
### Bug description
There is a shitcoin being used to send payments over signal.

### Steps to reproduce
- Open app
- Send payment to friend

**Actual result:** Signal sends payment with mobilecoin shitcoin
**Expected result:** Signal should send payment with lightning network bitcoin

**Comment by DagAgren** [comment] 2021-04-07 13:03
Bitcoin is planet-destroying garbage and Lightning doesn't work.

Just don't join the cryptocurrency scam. Don't burn all your trust like this.

**Comment by Nisc3d** [comment] 2021-04-07 13:06
This is the wrong place for this. Join the discussion in a polite way here: https://community.signalusers.org/t/signal-blog-help-us-test-payments-in-signal/30817/

And please close this, because this is not a bug report.

**Comment by benthecarman** [comment] 2021-04-07 13:15
I am seeing the same bug, this is a critical issue as it could cause users to think somehting like mobilecoin is worth more than dogshit.

**Comment by dannyjmac** [comment] 2021-04-07 13:20
@DagAgren you're greatly misinformed, please do some research around Bitcoin and Energy.

I am seeing this bug too.

**Comment by Bitcoin-Only-Fun-Stuff** [comment] 2021-04-07 13:33
Verified. Bug present. Should be Bitcoin, not shitcoin.

**Comment by MohamedKiouaz** [comment] 2021-04-07 13:56
I am also seeing this bug.

I would say that Lightning should not be used either because it's not a working product.

I think that Signal should be improving other parts of the software and not bringing useless complexity.

**Comment by kaschmirrr** [comment] 2021-04-07 13:57
Yes, cant use signal anymore with this built in scam. The integration of lightning otherwise would be a very helpful feature.

**Comment by benbabics** [comment] 2021-04-07 13:58
This bug is a blocker for me. Please fix ASAP.

**Comment by bitcoinheiro** [comment] 2021-04-07 13:59
This is very unfortunate indeed. I believe this project should focus on private messaging, improving usability, and leave money protocols for other apps to handle. A private communication protocol is all we need, user can decide what money to use without the need for the messaging app to push for one. It will generate way more backlash and problems to Signal than actual benefits.

**Comment by drrossum** [comment] 2021-04-07 14:01
Signal lost me here.  This bug is a showstopper.

Sphinx.chat does decentralized private messaging and payments without shitcoinery.

**Comment by kaschmirrr** [comment] 2021-04-07 14:02
@bitcoinheiro Integrated payment can be very useful for millions who only have access to hyperinflationary currencies or no bank accounts at all. With lightning in signal every signal user could privately send hard money between continents without setting up an extra wallet.

**Closed** 2021-04-07 14:04 UTC
