### ISSUE TITLE
if a link has an ñ it does not recognize it as a link

### ISSUE THREAD

**Issue by nadermx** [signalapp/Signal-Android#11676] opened 2021-10-10 16:15 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
if a link has an ñ it does not recognize it as a link

### Steps to reproduce
For example, when I type [diccionarioespañol.com](https://diccionarioespañol.com), or even [https://diccionarioespañol.com](https://diccionarioespañol.com) it does not recognize it as a link.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
It does not show it as a link, simply text.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
Like any other text I append .com to, it turns into a link.

### Screenshots
not available atm the moment.

### Device info

**Device:**galaxy note 10
**Android version:** R(Android 11)
**Signal version:** 5.24.14

### Link to debug log

https://debuglogs.org/dcb2535acb3695d46c83161fe58077ce0e6470a361ad60458a65f5c9acfe3f06

**Comment by Genis-Sage** [comment] 2021-10-10 18:27
hey @nadermx 
that's most probaly a duplicate of #11636

as stated there, that's currently intended behaviour to protect against [homograph attacks](https://en.wikipedia.org/wiki/IDN_homograph_attack)

**Closed as completed** 2021-10-11 13:55 UTC

**Comment by nadermx** [comment] 2021-10-11 16:02
@greyson-signal  Perhaps a script that checks the alexa top million and writes all variations of IDN, to prevent that, with perhaps a redirect, or a notification of double url, if it contains a IDN letting them know it contains an IDN?
