### ISSUE TITLE
Groups should appear in the NewConversationActivity

### ISSUE THREAD

**Issue by smichel17** [signalapp/Signal-Android#6053] opened 2017-01-15 17:01 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------
### Steps to reproduce
- From the home screen, tap the FAB
- type the name of a group you are in

**Actual result:** No results are shown.
**Expected result:** The group you searched for is shown.

### Rationale

When I want to send a new message to a person or group, my first thought is, "Did I message them recently?" If so, I'll scroll to find the conversation. If not, I'll hit the FAB, so I can search for them. Except that groups don't show up in that view.

In fact, the only time I ever use the search function is when I'm trying to find a group that I haven't messaged recently. If I could find groups in the new conversation activity, I wouldn't mind it at all if search were removed.

### I'm happy to take a crack at this

To avoid wasting my time, I'll only do this if OWS would be interested in merging (also, since I'd be a first time contributor, I'd probably fix a small bug or two first as the readme suggests).

**Comment by moxie0** [comment] 2017-01-16 21:52
I agree that groups should show up in that view. I have a feeling that might not be the simplest change though, so maybe take a crack at a few smaller PRs first.

**Comment by smichel17** [comment] 2017-02-02 13:27
Note: I probably won't have time to do this for a couple months, so if someone else comes across this and wants to take a stab at it before I have a chance, feel free. I'll comment again when I start.

**Comment by FeuRenard** [comment] 2017-02-19 20:27
This is a duplicate of #5039.

**Comment by 2-4601** [comment] 2017-02-19 22:01
This one has clearer description and is focused only on one issue so I closed the other one.

**Comment by automated-signal** [comment] 2018-04-03 00:58
GitHub Issue Cleanup:
See #7598 for more information.

**Closed by automated-signal** 2018-04-03 00:58 UTC
Labels: bug
