### ISSUE TITLE
Signal doesn't respect "SMS-App" setting on Lineage 17/Android 10

### ISSUE THREAD

**Issue by nerdoc** [signalapp/Signal-Android#9549] opened 2020-04-20 07:16 UTC
- [ x] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Since upgrade frome LineageOS 16 to 17 (Android 10) on my Oneplus 3, Signal doesn't send SMS any more. Contacts without Signal aren't listet in my Signal app, can't change that.
I don't use Hangouts/Project Fi, no other (besides the Android default SMS App) that can read/write SMS are installed.

Doesn't seem to be related to https://github.com/signalapp/Signal-Android/issues/5044

### Steps to reproduce
* Upgrade to Lineageos 17 (Android 10) with installed Signal App.
* Go to Signal settings, see that Signal is NOT the default SMS App.
* Go to Android Permission settings - Signal is the default App there.

**Actual result:** 
Signal dosen't send SMS any more, and can't be made the default SMS app on Android 10.

**Expected result:** It should do as before: send SMS to non-Signal contacts. It should be able to recognize that it IS the default SMS app.

### Screenshots
In Android settings Signal is the default SMS app:

![Screenshot_20200420-090328_Berechtigungssteuerung](https://user-images.githubusercontent.com/2955584/79723434-09662700-82e6-11ea-98a5-acc5e44e1ce1.png)

But in Signal settings, this is not respected. 

![Screenshot_20200420-085939_Signal](https://user-images.githubusercontent.com/2955584/79723179-9ceb2800-82e5-11ea-9cf2-e4990981e13e.png)

### Device info

**Device:** Oneplus 3
**Android version:** 10 (lineage_oneplus3-userdebug 10 QQ2A, 200405.005 a3bfd141c1
**Signal version:** 4.58.5

### Link to debug log
https://debuglogs.org/ec86d32ae068fac52cf3e52ce02cd0081ca8ad980dab7a2ac6b6787cafbeec08

Excerpt:
* android.permission.WRITE_SMS: YES
* org.thoughtcrime.securesms.ACCESS_SECRETS: YES

**Comment by nerdoc** [comment] 2020-04-20 10:45
added logcat when clicking on "activate signal for SMS" within a conversation:

```
04-20 12:42:04.722   943 11213 I ActivityTaskManager: START u0 {act=android.provider.Telephony.ACTION_CHANGE_DEFAULT cmp=com.android.permissioncontroller/com.android.packageinstaller.role.ui.RequestRoleActivity (has extras)} from uid 10088
04-20 12:42:04.730  5228  5228 D PassphraseRequiredActionBarActivity: [ConversationActivity] onPause()
04-20 12:42:04.740  6857  6857 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@6e61407
04-20 12:42:04.746  6857  6857 W RequestRoleActivity: Telephony.Sms.Intents.ACTION_CHANGE_DEFAULT is deprecated; please use RoleManager.createRequestRoleIntent() and Activity.startActivityForResult() instead
04-20 12:42:04.749  6857  6857 I RequestRoleActivity: Application is already a role holder, role: android.app.role.SMS, package: org.thoughtcrime.securesms
04-20 12:42:04.750  6857  6857 V RequestRoleFragment: Role request result requestingUid=10088 requestingPackageName=org.thoughtcrime.securesms roleName=android.app.role.SMS qualifyingCount=-1 currentUid=-1 currentPackageName=null grantedAnotherUid=-1 grantedAnotherPackageName=null result=2
04-20 12:42:04.759  5228  5407 V Cursor  : Filling cursor window with start position:0 required position:0
04-20 12:42:04.759  5228  5300 V Cursor  : Filling cursor window with start position:0 required position:0
04-20 12:42:04.763  5228  5299 V Cursor  : Filling cursor window with start position:0 required position:0
04-20 12:42:04.764  5228  5407 V Cursor  : Filling cursor window with start position:0 required position:0
04-20 12:42:04.769  5228  5228 I ConversationActivity: onActivityResult called: 11, -1 , null
04-20 12:42:04.770  5228  5228 I ConversationActivity: handleSecurityChange(false, false)
04-20 12:42:04.772  5228  5300 V Cursor  : Filling cursor window with start position:0 required position:0
04-20 12:42:04.779  5228  5300 I chatty  : uid=10088(org.thoughtcrime.securesms) signal-bounded- identical 1 line
04-20 12:42:04.781  5228  5300 V Cursor  : Filling cursor window with start position:0 required position:0
04-20 12:42:04.783  5228  5228 D ConversationActivity: Setting link preview: false
04-20 12:42:04.784  5228  5300 V Cursor  : Filling cursor window with start position:0 required position:0
04-20 12:42:04.785  5228  5777 D SearchRepository: Total time: 30 ms
04-20 12:42:04.789  5228  5228 D ConversationActivity: Setting link preview: false
04-20 12:42:04.793  5228  7035 I ConversationActivity: Resolving registered state...
04-20 12:42:04.794  5228  7035 I ConversationActivity: Checking through resolved recipient
04-20 12:42:04.794  5228  7035 I ConversationActivity: Resolved registered state: NOT_REGISTERED
04-20 12:42:04.794  5228  7035 I ConversationActivity: Returning registered state...
04-20 12:42:04.799  5228  5228 D PassphraseRequiredActionBarActivity: [ConversationActivity] onResume()
04-20 12:42:04.803  5228  7058 I ConversationActivity: Loading identity for: RecipientId::322
04-20 12:42:04.809  5228  7058 V Cursor  : Filling cursor window with start position:0 required position:0
04-20 12:42:04.841  5228  7058 I chatty  : uid=10088(org.thoughtcrime.securesms) AsyncTask #126 identical 3 lines
04-20 12:42:04.842  5228  7058 V Cursor  : Filling cursor window with start position:0 required position:0
04-20 12:42:04.864  5228  5228 I ConversationActivity: Got identity records: false
04-20 12:42:04.864  5228  5228 I ConversationActivity: onSecurityUpdated()
04-20 12:42:04.864  5228  5228 I ConversationActivity: updateDefaultSubscriptionId(1)
04-20 12:42:04.870  5228  5228 D ConversationActivity: Setting link preview: false
04-20 12:42:04.874  5228  5299 V Cursor  : Filling cursor window with start position:0 required position:0
04-20 12:42:04.880  5228  5299 V Cursor  : Filling cursor window with start position:0 required position:0
04-20 12:42:04.881  5228  5407 V Cursor  : Filling cursor window with start position:0 required position:0
04-20 12:42:04.882  5228  5300 V Cursor  : Filling cursor window with start position:0 required position:0
04-20 12:42:04.889  5228  5407 V Cursor  : Filling cursor window with start position:0 required position:0
04-20 12:42:04.894  5228  5407 I chatty  : uid=10088(org.thoughtcrime.securesms) signal-bounded- identical 2 lines
04-20 12:42:04.896  5228  5407 V Cursor  : Filling cursor window with start position:0 required position:0
04-20 12:42:04.898  5228  5777 D SearchRepository: Total time: 25 ms

```

**Comment by nerdoc** [comment] 2020-04-23 11:34
Can I do anything else to help this sort out? I'm currently completely without ability to send SMS to non-Signal contacts.

**Comment by UserX404** [comment] 2020-04-23 17:15
Maybe you can check within the system settings.
Settings - apps- standard apps

Can you choose Signal for Sms standard app?

**Comment by nerdoc** [comment] 2020-04-23 19:53
Hrllo @UserX404 - Please read my issue above. In the first Screenshot you can see the setting: Signal IS the SMS app.

**Comment by UserX404** [comment] 2020-04-23 21:38
Sorry. My fault.

**Comment by micressor** [comment] 2020-04-25 14:57
Confirm this problem.
I just upgraded to LinageOS 17.1.

**Comment by nerdoc** [comment] 2020-04-25 15:12
Switching back to Android's standard SMS app works (including SMS sending/receiving), switching to Signal again breaks it again.

**Comment by micressor** [comment] 2020-04-25 15:24
For me only the sending of SMS is affected. If Signal is the default app, receiving SMS works, but not sending.

**Signal version:** 4.58.5

**Comment by nerdoc** [comment] 2020-04-25 20:13
That's right, receiving works here too. Sending does not - but you have to switch to Android's SMS app anyway, because just receiving is only half of the story, and if you have Signal as default SMS app, you can't send with Android's SMS app

**Comment by 32u-nd** [comment] 2020-05-23 11:09
> Confirm this problem.
> I just upgraded to LinageOS 17.1.

Confirmed, too. In addition, I don't receive SMS incoming notifications, if Signal is not opened in front screen (e.g. SMS bank TAN). I need to actively open Signal in front screen to see incoming SMS.

**Comment by nerdoc** [comment] 2020-05-23 16:55
This seems to be another bug, don't have thus problem here. Yust no SMS sending. It's annoying. Did Google change an API?

**Comment by tsopanid** [comment] 2020-06-03 17:36
Same issue (or both of them) for me on Essential PH1 with LineageOS 17.1. 
Some days ago it still worked, i think after a signal update notifications stopped showing, 
don't know since when i can't send sms, realized it later.
i'm using the apk downloaded from signal.org some weeks ago, cant find it today on the website.
Did a Signal update afterwards, also LOS update, both didn't help.

**Comment by melohr** [comment] 2020-06-29 06:51
I experienced the very same bug (LOS upgrade 16 to 17.1, latest Signal version). I tried (having up before!) deleting Signal's use data and restoring but didn't change. A complete de-/reinstallation and account restore finally did it. I was able to successfully set Signal as standard app, Signal confirms it in its settings, and I was able to send an SMS.

**Comment by nerdoc** [comment] 2020-07-13 06:24
Can confirm. Workaround is making a backup (+remembering the code) uninstalling Signal, reinstalling it and recovering data Form backup.

**Comment by Gryf1972** [comment] 2020-10-17 11:06
> A complete de-/reinstallation and account restore finally did it.

Confirmed here as well - thanks for the tip. Would be interesting to know whether this is an issue affecting only upgrades from LineageOS 16 to 17, or from "official" Android 9 to 10 as well ...

**Comment by melohr** [comment] 2020-10-17 16:06
Funnily, the recent LOS upgrade from 16 to 17.1 last week on the BQ XPro (bardockpro) did work perfectly. No need to touch Signal, it just worked as expected. (My former post covered the upgrade of a Poco F1 (beryllium).)

**Comment by denics** [comment] 2020-10-25 20:09
Dear all, I am on Lineage MicroG 17.1 and I have this problem on a Sony Xperia XZ2. Unfortunately uninstalling and reinstalling restoring from a backup did not work for me.

**Comment by dbkblk** [comment] 2020-12-15 10:39
> 
> 
> I experienced the very same bug (LOS upgrade 16 to 17.1, latest Signal version). I tried (having backed it up before!) deleting Signal's user data and restoring it but didn't change. A complete de-/reinstallation and account restore finally did it. I was able to successfully set Signal as standard app, Signal confirms it in its settings, and I was able to send an SMS.

I have the same problem (after a LOS 16 -> 17.1 updgrade on OnePlus5T / dumpling). What do you mean by "complete reinstallation", signal or LineageOS?

**Comment by dbkblk** [comment] 2020-12-15 10:51
> 
> 
> Dear all, I am on Lineage MicroG 17.1 and I have this problem on a Sony Xperia XZ2. Unfortunately uninstalling and reinstalling restoring from a backup did not work for me.

It worked for me on LineageOS 17.1 microg. Make sure you do that in this order:
- Backup Signal (make sure you have the restore code).
- Close Signal
- Empty Signal app cache
- Remove Signal app data
- Uninstall Signal
- Reinstall Signal
- Restore Backup
- Set as default SMS app

**Comment by sseide** [comment] 2020-12-21 20:51
Same problem for me - updated a Fairphone2 from LineageOS 16 to 17.1 (20201218) and Signal did not realized its the default SMS app afterwards, therefor unable to send sms. Did not tested receiving one.

Following steps from @dbkblk fixed the problem so far...

**Comment by taivlam** [comment] 2021-04-07 17:10
As a side note, this issue disappears after upgrading from LineageOS 17.1 to 18.1.  Afterwards, setting Signal as the default SMS app will then properly function as the SMS app.  So, in a way, upgrading to LOS 18.1 "fixes" the issue.

I had the issue of never being able to send and compose new SMS messages, though I could always receive SMS messages.  However, I never got around to trying the whole "back up, uninstall, reinstall, and restore" method on Signal worked, so I can't say whether or not the ad-hoc solution ever worked for me. 

This was done on two OnePlus 3T devices, both running the unofficial fork of LineageOS 18.1 for microG (based on Android 11), with all microG services turned off.  (I suspect that this will also work on official LineageOS, though your mileage may vary.)

**Comment by sseide** [comment] 2022-01-26 15:53
for me working again since some time, can send/receive sms.
started to work again under LOS 17.1 (but cannot remember when/wh<) and now with LOS 18.1 works too.

**Comment by 32u-nd** [comment] 2022-01-26 16:29
I am meanwhile running LineageOS 18.1. The symptom does not exist anymore, hence you may close the issue.

**Closed** 2022-04-08 12:16 UTC
Labels: wontfix
