### ISSUE TITLE
Thumbnails of images once in a while have incorrect fit

### ISSUE THREAD

**Issue by guimspace** [signalapp/Signal-Android#9082] opened 2019-10-08 14:36 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The thumbnail of a cropped picture is not properly fit/positioned in the frame.

### Steps to reproduce
1. Select a picture for attachment
2. Selection the "crop" tool
3. Crop ("resize") the image AND move the picture
4. Send the picture

**Actual result:** The picture in the thumbnail can be out of frame if it is moved to the edges during edition.
**Expected result:** Thumbnail centred in the thumbnail frame.

### Screenshots
![Screenshot_20191008-090713](https://user-images.githubusercontent.com/43423701/66404270-7f481800-e9be-11e9-9b82-ad872e6b9a97.jpg)

### Device info
**Device:** ASUS ZE520KL
**Android version:** 8.0.0
**Signal version:** 4.48.14

**Comment by aleb2000** [comment] 2019-10-28 18:21
Reproducible on Samsung S7, Android 8.0, Signal 4.49.10
The thumbnail appears partially black (with dark theme), only upper part of the thumbnail is rendered.
See also https://github.com/signalapp/Signal-Android/issues/9109#issuecomment-544897603
https://debuglogs.org/fe537a60049b354d96a1a80d5d8dc380760cc247fd2bd999a01bcb3b23b9177f
https://debuglogs.org/7ea740710838a34b34cd4e3c9cb0635090754e006962601a34a4cd69a8c6c63f

**Comment by greyson-signal** [comment] 2019-11-09 00:11
This is some weird Glide issue, I think. Happens very rarely and randomly to me. Unfortunately it makes this bad thumbnail and caches it, so it'll look like that for a long team, even if the image is fine when you tap it. In the meantime, if you go to your system settings for Signal and clear the cache (*not*  storage, just the cache), it'll regenerate the thumbnail.

**Comment by Tursko** [comment] 2019-11-25 23:31
Also happens to me on 4.50.5.

**Comment by n-o-o-b** [comment] 2020-05-27 13:13
Presumably this issue is related to #9294, since that has been closed? I am getting something similar to that.

Version 4.59.11, LG G6, Android 9. Sometimes sent images display with a portion of them blacked out in the thumbnail, but usually they fix themselves after some time.

https://debuglogs.org/1d7c94414cbf92e90d95c7f3253a2aef1940894e4c2ea9477fc1b03e0e982ab7

![Screenshot_20200527-134155_1](https://user-images.githubusercontent.com/19697175/83022651-bb9ab800-a023-11ea-93f9-efe667bdda90.png)

**Comment by theirix** [comment] 2020-06-01 13:44
Same for me. Happened ever without transforming the photo, just send an original photo.

Force stopping and starting does not help. Clearing the cache helps.

4.60.9 (6402)
Android 10, Pixel 3a

https://support.signal.org/hc/en-us/articles/360007318591#android_debug

**Comment by Nisc3d** [comment] 2020-10-24 11:18
This also happens to Link Previews.
In this example the whole preview image was black not just a half.
Unfortunately I couldn't capture a debug log.
The device is a Nokia 6 with Android 9 and Signal 4.74.3.
The issue went away after clearing the cache.

![signal-2020-10-24-130130](https://user-images.githubusercontent.com/7361310/97080344-eac94b80-15fa-11eb-86d3-53af4a5488a5.png)

**Comment by Tursko** [comment] 2021-02-26 14:46
Signal is currently using Glide 4.11. 

4.12 was released around a month ago: https://github.com/bumptech/glide/releases/tag/v4.12.0

**Comment by guimspace** [comment] 2021-02-26 21:52
> Signal is currently using Glide 4.11:
> 
> https://github.com/signalapp/Signal-Android/blob/f707c1d02cd30ab927b9671f12e871e2b381ebe3/app/build.gradle#L350
> 
> 4.12 was released around a month ago: https://github.com/bumptech/glide/releases/tag/v4.12.0

**Comment by guimspace** [comment] 2021-02-26 21:54
Closed by accident.

**Comment by Herohtar** [comment] 2021-04-28 00:59
This happens a *lot* for me on my Pixel 5, definitely much more than "rarely". The image only renders partially with a black background, but if I leave the conversation and go back in, the background is now the blurhash. Clearing Signal's cache fixes it.
Screenshots:
![signal-2021-04-27-195251_001](https://user-images.githubusercontent.com/10427164/116330381-04f30a80-a793-11eb-9155-38f9b2f7ee1f.png)
![signal-2021-04-27-195251_002](https://user-images.githubusercontent.com/10427164/116330395-091f2800-a793-11eb-9b55-5c1c851ca94a.png)

Debug log:
https://debuglogs.org/9c8d8f7b9f6fafbfb1b33b5e93f8080057714b36475a15cf571d009eff6fbd01

**Comment by l3ender** [comment] 2021-06-20 19:06
I'm still periodically experiencing this issue on my OnePlus 7T on Android 11. I've seen quite a few issues link to this one so I am adding some screenshots and a recent log grab.

Clearing cache worked to regenerate the thumbnails correctly, but it seems the core issue is still present.

![Screenshot_20210620-133727](https://user-images.githubusercontent.com/2243641/122685362-774efc80-d1d0-11eb-9c1a-05c355425151.jpg)

![Screenshot_20210620-133840](https://user-images.githubusercontent.com/2243641/122685370-859d1880-d1d0-11eb-9721-60dc4313ae66.jpg)

![Screenshot_20210620-133930](https://user-images.githubusercontent.com/2243641/122685372-8afa6300-d1d0-11eb-8e29-837a84ee7197.jpg)

https://debuglogs.org/623aefe7ab86f15539b12e9312ca3446e267db32e7053f4c2895c31567c52b97

**Comment by DarkoVeberic** [comment] 2021-07-06 20:17
Duplicate of #10394

**Comment by Tursko** [comment] 2021-07-06 20:30
> Duplicate of #10394

Not true, this is the original issue. Check the dates.

**Comment by DarkoVeberic** [comment] 2021-07-07 09:20
true, i just wanted join all these separate issues under one roof. #10394 seems to have most comments by now and we can increase the pressure to fix this increasing annoyance by posting comments in one place only. it so f** annoying i paid the app price for some friends to switch to threema instead.

**Comment by oittaa** [comment] 2021-10-04 00:44
I haven't noticed this issue in a while. Maybe commit https://github.com/signalapp/Signal-Android/commit/fe82c4e487fca9f208d7389610450fc9b41d7c35 fixed this one for me?

**Comment by Tursko** [comment] 2021-10-04 03:50
> I haven't noticed this issue in a while. Maybe commit https://github.com/signalapp/Signal-Android/commit/fe82c4e487fca9f208d7389610450fc9b41d7c35 fixed this one for me?

That commit fixed an unrelated issue. The glide bug (this issue) is still present.

**Comment by oittaa** [comment] 2021-10-04 08:58
> That commit fixed an unrelated issue. The glide bug (this issue) is still present.

What's the unrelated issue? Is there a bug number? The commit doesn't reference anything, but the message "Fix image partially shown after message sent." more or less describes the issues people have in this one.

**Comment by Herohtar** [comment] 2022-01-28 17:44
I don't think I have seen this happen in a while, but I also haven't been sending a whole lot of pictures, so not sure whether it is fixed or not.

**Comment by Tursko** [comment] 2022-01-28 17:46
> I don't think I have seen this happen in a while, but I also haven't been sending a whole lot of pictures, so not sure whether it is fixed or not.

Agreed. Haven't seen it in months.

**Closed** 2022-01-31 14:05 UTC
