### ISSUE TITLE
Endless SMS send loop after initially failed message

### ISSUE THREAD

**Issue by cebone** [signalapp/Signal-Android#8390] opened 2018-11-22 11:39 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Resend of initially failed SMS message after loss of mobile connectivity caused a loop (the recipient received almost 300 duplicate SMSs before I killed the App) of SMS resends that the App thought were failed but were actually being sent. 

The only way to stop it was to uninstall Signal.

### Steps to reproduce
- SMS received from non Signal user
- Reply to SMS
- Send message (loose mobile connectivity just after)
- Message fails
- Press resend (still no mobile connectivity)
- On reestablishment of good mobile connectivity the loop began.

**Actual result:** Multiple uncontrollable resend loop
**Expected result:** Single send of message.

### Screenshots
No images, I had to kill the App and uninstall to stop the loop.

### Device info

**Device:** Samsung S7 SM-G935F
**Android version:** 8.0.0
**Signal version:** 4.30.7

### Link to debug log

No log. I had to kill the App and uninstall to stop the loop.

**Comment by greyson-signal** [comment] 2018-11-24 03:53
@cebone Yeah, if you could get a log that'd be super helpful, otherwise I don't have much to go off of. Logs in Signal persist by size, not date, so you likely still have relevant logs from the incident. If you're concerned about Signal sending too many SMS while you submit a debug log, you can set another app as your default SMS first (like the built-in Messages app). Thanks!

**Comment by cebone** [comment] 2018-11-26 16:19
I have reinstalled signal. On the off chance that logs are persisted across installs, I have submitted my log.
https://debuglogs.org/f3d89eb2b728ca36878b129f973c7dde9a50364ebc74bb7be25a962bfb1f9d0d

**Comment by cebone** [comment] 2018-11-26 18:01
Ok, so they haven't persisted. I uninstalled and then reinstalled again including then setting Signal as my default SMS app again. I guess there's not a lot more that can be done now.

**Comment by biolypl** [comment] 2019-12-24 13:12
The issue is still there, I didn't notice the another issue is closed so my comment there for reference: https://github.com/signalapp/Signal-Android/issues/8268#issuecomment-568745604

**Comment by twistypigeon** [comment] 2020-02-21 20:56
Just received this issue
https://debuglogs.org/5380189bdf15c89bf882f5bc94becd0c3814fa2619ad42a39aa6f4ab042eadc3

Attempted to send an SMS in a poor signal area and didn't check if it sent.
When reopening my phone I received multiple failed message notifications that kept appearing.
My recipient then informed my that I'd sent the same message over 200 times.
Force closed the app and still receivedore notifications.
I hadn't pressed resend or anything.

**Comment by zebastiane** [comment] 2020-07-28 17:59
@biolypl for me #8268 is still not fixed, or the cause is different (see https://github.com/signalapp/Signal-Android/issues/8268#issuecomment-665181365)

**Comment by giunz** [comment] 2020-08-04 16:05
On 27/7/2020 16:47 (GMT +3) I sent an SMS while being in an area without signal. While the first attempt failed, after enabling  "WiFi calling"  it seemed to have successfully been sent. 
After 2 hours I was informed by the recipient that he received over 500 times, the same message. 
I recently retrieved the [logs](https://debuglogs.org/03b8095b31e86b45698c10ffebe14bf3abab89b86280559e699295c5a43d39aa)

**Comment by m2nis** [comment] 2020-08-26 20:35
Hello,

I experience exactly the same issue, with current version and beta version. At a place at home, with our without wifi, nearly always the same. The recipient receive hundreds of sms. Also experienced outside in other bad conditions. If I delete the message, it's seems to stop the endless loop. 

So inconfortable that I'm thinking of changing my sms default application... 

Debug link :
https://debuglogs.org/32c48a6de3ac7c24500c50014619eb90b7487233c7c0ab794033a2f9887d2c82

**Comment by lgvld** [comment] 2020-12-05 18:47
Same thing happens to me one in a while.

I also use a Samsung S7 (Edge) SM-G395F.

**Comment by nigiord** [comment] 2021-06-08 07:52
Exactly the same issue as described on a Samsung A3 2016. Unfortunately no log because I panic-shutdowned my phone to stop it (and apparently this clean the log). It's the second time something like this happens. I guess it's when you lose connectivity at just the wrong time... hence why it's hard to reproduce. But once the app is stuck like this, the only thing that stop it is to force kill Signal or delete the message.

To be honest it's hard to troubleshoot because you risk problems with your service provider (and extra billing). Is there a way to make some test without risking sending thousands of SMS?

**Comment by sirlada** [comment] 2021-08-22 20:16
Hi, just experienced the same issue. Was not aware of signal sending hundreds of sms. The receiver made me aware of it and had to block me. After deleting the message signal crashed and kept on crashing when trying to reopen the app shortly after startup.
Was able to delete whole conversation and make a debug log after going to airplane mode.
Hope this helps resolving the issue!

https://debuglogs.org/0c8ce2debf17d7dbb2f8e27ffbaae7513a7e83bd65bb8835bad37912a38f5f24

**Comment by greyson-signal** [comment] 2021-08-23 02:58
Hi there, there is a fix in 5.21.x, which is currently rolling out to production. Thanks! f4d6de466

**Closed by greyson-signal** 2021-08-23 02:58 UTC
