### ISSUE TITLE
Cannot send photos taken from built in camera in portrait orientation

### ISSUE THREAD

**Issue by ryancdotorg** [signalapp/Signal-Android#8350] opened 2018-11-07 22:48 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
There is no option to send a photo after taking it using the built in camera while phone is in portrait orientation.

### Steps to reproduce
- tap camera icon from a chat
- hold phone in portrait orientation 
- take photo

**Actual result:** Some options to edit the photo appear, but option to send is only visible in landscape
**Expected result:** An option to send should be visible

### Screenshots

![screenshot_20181107-155313](https://user-images.githubusercontent.com/656699/48166328-7aa64b80-e2a5-11e8-82df-b875751f59e3.png)

### Device info

**Device:** Essential PH-1
**Android version:** 8.1.0
**Signal version:** 4.29.7

**Comment by greyson-signal** [comment] 2018-11-08 01:00
Hmmm... the only thing I can think of is that the navigation bar is somehow covering up the compose box and send button. There's also a weird black bar at the top -- is that because the notch of the Essential Phone leaves a blank space up there? Maybe it's pushing the entire screen content somehow?

**Comment by ryancdotorg** [comment] 2018-11-13 23:31
I have no idea. Is there any more information I can provide to help get this fixed?

**Comment by ryancdotorg** [comment] 2018-12-20 02:30
Is there anything I can do to help you folks figure out what's going on?

**Comment by greyson-signal** [comment] 2019-02-14 05:19
I actually got a hold of an Essential Phone, and this problem seems to be resolved in their Android P update. At least, I can't reproduce this issue on an Essential Phone running Android P.

**Closed by greyson-signal** 2019-02-14 05:19 UTC

**Comment by ryancdotorg** [comment] 2019-11-29 03:46
I can confirm this was fixed in Android P, thanks.
