### ISSUE TITLE
Call function not working

### ISSUE THREAD

**Issue by SlightlyTiltedBookshelf** [signalapp/Signal-Android#10680] opened 2021-01-16 19:39 UTC
- [ X] I have searched open and closed issues for duplicates
- [X ] I am submitting a bug report for existing functionality that does not work as intended
- [ X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Calling or video calling doesn't actually ring and only leaves a miss call after hanging up.

### Steps to reproduce
- open the app
-click on a chat
-click on call icon

**Actual result:** The calls do not actually get through and only end up as miss calls.
**Expected result:** The calls should ring and the call must go through on the other phone or on mine and I should get a call popup on my screen.

### Device info

**Device:** Manufacturer samsung
**Android version:** 11
**Signal version:** 5.1.9

### Link to debug log
https://debuglogs.org/e21246d579025fba74eeae4310bb0e2bf538994d0e36590b114dda4aadeaf6d8

**Comment by Tursko** [comment] 2021-01-16 19:48
This is the result of the servers being down right now.

https://status.signal.org/

**Comment by lokesh-krishna** [comment] 2021-01-18 04:20
I've had this issue for a while. Going back at least a few months. I do not get notified of calls but my contacts do receive calls I make. 

Is there any thing I can provide to help figure out what's going on?

**Comment by szotsaki** [comment] 2021-04-03 08:13
This is most probably a duplicate of https://github.com/signalapp/Signal-Android/issues/7733. May I ask to close this issue (to avoid having duplicates) and continue the conversation in the linked ticket?

**Closed** 2022-02-02 16:36 UTC
Labels: wontfix
