### ISSUE TITLE
search function does not include conversation content or archived conversations

### ISSUE THREAD

**Issue by thbsp** [signalapp/Signal-Android#7418] opened 2018-02-16 03:54 UTC
### Feature request
I find it remarkably difficult to find old contacts conversations in Signal, for three reasons:
* the global search function doesn't search archived messages, for either the name of the conversation (e.g. the contact's name) or the conversation content
* the global search function doesn't search current conversation content
* there is no search function within a conversation's options menu
* the contact search function only searches the address book, ignoring phone numbers for current or archived conversations

I use Signal to handle regular text messages. I have many (100+) contacts with whom I will only send or receive a 2-3 messages. It's not worth my time to add all of them to my contact list. Perhaps my use case is different from what the developers envisioned, but I don't think it's that uncommon.

**Actual result:**
- I go to send a message to a particular phone number. I'm not sure if I've previously sent a message to that number or not.
- I start typing in a phone number, and no autocomplete option appears. I am led to believe that I have not messaged that number before.
- After typing in the full number, I start a conversation, and my previous messages to that phone number appear.
- Aside from scrolling down a list of hundreds of conversations and manually reading the associated phone numbers, what I described above is the only way for me to see previous messages to/from that phone number.

Desired behaviour:
- Ability to search all current and archived conversations based on contact name, contact phone number or conversation content.
- Existing conversations to appear in new conversation search window based on phone number

**Comment by FeuRenard** [comment] 2018-02-16 08:24
Search in message content is a duplicate of #1232.

**Comment by haffenloher** [comment] 2018-02-16 20:17
For me, the search function does return conversations from both the inbox and the archive. (Android 4.2, Signal 4.16)

**Comment by moxie0** [comment] 2018-02-17 04:56
@thbsp Please try not to delete the issue template. Searching message content is a duplicate, there is an open issue for that, and we've made some recent progress to make it possible in the future. Contact names should be returned from the archive, if that's really broken for you then please open an issue specifically for that with the template information. Thanks!

**Closed by moxie0** 2018-02-17 04:56 UTC
