### ISSUE TITLE
NewConversationActivity and ConversationListActivity search behavior is dependent on device model

### ISSUE THREAD

**Issue by McLoo** [signalapp/Signal-Android#2378] opened 2015-01-22 13:37 UTC
Occurs in Latest HEAD, works in 2.4.2

Searching for conversation a with recipient "Test" 
- fails if you search "est"
- work if you search "Tes"

**Comment by agrajaghh** [comment] 2015-05-01 10:03
I just built 2.4.2 but it isn't working there for me (Nexus 4, Android 5.1). I guess @rhodey is right and its device dependent ...

But its still weird why it worked for you with 2.4.2 but not with HEAD from Jan 22... I suppose you used the same device?

**Comment by McLoo** [comment] 2015-05-01 11:07
I used different devices. Android x86, some CM versions... 
Tested a view days ago. It's the search in contacts DB via URI. Couldn't figure out how to force a fuzzy *-text-* search 😢

**Comment by rhodey** [comment] 2015-05-04 18:30
this issue was first reported to affect the search feature in `ConversationListActivity` exclusively. recently I discovered that:

1) "starts with" search also happens in `NewConversationActivity`
2) "starts with" search only happens on some devices, others do full text search as intended

so updating the label on this to **bug** because the search feature in two of our UIs has been shown to behave differently on different devices.

**Comment by rhodey** [comment] 2015-06-09 20:40
some context:

the method at fault here is [ContactsDatabase.queryAndroidDb()](https://github.com/WhisperSystems/TextSecure/blob/master/src/org/thoughtcrime/securesms/contacts/ContactsDatabase.java#L123), this issue is that the behavior of `ContactsContract.CommonDataKinds.Phone.CONTENT_FILTER_URI` has been shown to be device specific.

we can get around this device specific behavior by ditching the special filter URI and using the base URI of `ContactsContract.CommonDataKinds.Phone.CONTENT_URI` with a fuzzy filter selection just as we do in [ContactsDatabase.queryLocalDb()](https://github.com/WhisperSystems/TextSecure/blob/master/src/org/thoughtcrime/securesms/contacts/ContactsDatabase.java#L135). this approach gets us close but doesn't collate "raw contacts" into "contacts" (aka de-duplication) in the way that `CONTENT_FILTER_URI` does seemingly magically by default.

looking into the android contact provider source code you will see that an SQL `GROUP BY` clause is added when using `CONTENT_FILTER_URI`, this de-duplicates contacts that exist in multiple accounts by grouping on `RawContacts.CONTACT_ID`. before Android ICS, it was possible to hack a `GROUP BY` clause into a ContactsProvider query but this is no longer possible. the only way to do a `GROUP BY` now is programmatically like in [this example](http://stackoverflow.com/questions/8654904/group-by-in-contentresolver-in-ice-cream-sandwich).

If we switched to using the `ContactsContract.Contacts` URIs, tables, and columns we would have contact de-duplication by default and could simply add a fuzzy filter selection, unfortunately without a serious database migration we're stuck using the `ContactsContract.CommonDataKinds.Phone` URIs, tables, and columns. so, to close this issue we need to either:

1) stop using the special filter URI, add a fuzzy filter selection, and group by on `RawContacts.CONTACT_ID` programmatically.
2) migrate our local contacts database to use the `ContactsContract.Contacts` URIs, tables, and columns, and update the filter query to use these too.

I don't expect the first of these two to be too complicated, gonna start a PR.

**Comment by RiseT** [comment] 2016-12-14 11:11
@2-4601 I guess that's fixed with the PR mentioned.

**Comment by 2-4601** [comment] 2016-12-15 12:52
@RiseT Hmm... I don't understand? The commit in the PR wasn't merged?
I can reproduce this bug for non-group conversation. For group conversations the search works ("est" and "Tes" both find "Test")

**Comment by RiseT** [comment] 2016-12-15 13:00
@2-4601 Uh - I've missed that it wasn't merged. I'm sorry.

**Comment by automated-signal** [comment] 2018-04-02 21:29
GitHub Issue Cleanup:
See #7598 for more information.

**Closed by automated-signal** 2018-04-02 21:29 UTC
Labels: bug
