### ISSUE TITLE
Can't unregister without play services!

### ISSUE THREAD

**Issue by user12332** [signalapp/Signal-Android#6581] opened 2017-04-25 22:38 UTC
Can't unregister my number without play services. Isn't this app supposed to work now without google play services?

**Comment by nrizzio** [comment] 2017-04-25 23:39
Can you please fill out the issue template so we have enough information to help you?

**Comment by p4nci** [comment] 2017-04-26 06:54
probably dupe of https://github.com/WhisperSystems/Signal-Android/issues/6381

**Comment by p4nci** [comment] 2017-04-27 08:49
@user12332 if you have root, please check this workaround (thanks @moxie0):
https://whispersystems.discoursehosting.net/t/continual-nagging-to-get-google-play-services/990/6

**Comment by automated-signal** [comment] 2018-04-03 02:31
GitHub Issue Cleanup:
See #7598 for more information.

**Closed by automated-signal** 2018-04-03 02:31 UTC
