### ISSUE TITLE
Bug in Danish Translation

### ISSUE THREAD

**Issue by iamjustmeithink** [signalapp/Signal-Android#13763] opened 2024-11-01 19:17 UTC
### Guidelines

- [X] I have searched searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

### Bug description

The "Remove Person" has a `<br/ >` at the end, wich should not be there.

It is only present in the Danish translation.

I have added screenshot of the English and Danish translation.

### Screenshots

Danish dialog (where the bug is present):
![Screenshot_Danish Translation](https://github.com/user-attachments/assets/efe1738c-aa74-4d64-808c-fdfa32bd829a)

English dialog (without the bug):
![Screenshot_English Translationl](https://github.com/user-attachments/assets/653a1633-90aa-4c38-a97e-a0ccaff0ab7c)

**Comment by ismaildasci** [comment] 2024-11-01 19:23
Here’s a concise response acknowledging the issue and suggesting a quick solution:

Hey! 👋

Thanks for catching this! It looks like the extra <br /> in the Danish translation might have been added by mistake. A quick fix would be to update the translation file to remove this line break.

If you’re open to it, feel free to submit a PR with the fix! Otherwise, I’m sure the team can address this in the next update.

Thanks for your attention to detail! 😊

**Comment by mosbat** [comment] 2024-11-02 14:40
Here is the fix

https://github.com/signalapp/Signal-Android/pull/13764

**Comment by mosbat** [comment] 2024-11-02 14:48
Let me know if anything else is needed

**Comment by iamjustmeithink** [comment] 2024-11-02 15:34
@ismaildasci 
I don't know how to make a PR, but thank you for your sugestion!


@mosbat 
Wouw! You are fast in changing the tranlsation! I have not catched other mistakes in the translation, but if I do, I will let you know :)

Thank you :)

**Comment by mosbat** [comment] 2024-11-04 14:03
@ismaildasci Seems like Signal forgot to mention that we don't handle translations for the mobile app here; so my fix was rejected since they prefer to have it done with a translation service. However, @greyson-signal who is working with Signal has confirmed that the issue will be fixed externally since they are pulling those translations from a third party.

**Comment by iamjustmeithink** [comment] 2024-11-04 15:02
Hi @mosbat ,

Ohh okay, thank you so much :)

Do you know where the translation service is? Just so I know where to add this in the future?

Thank you so much for taking your time to make the PR, even tho they dont accept translations there.

Even tho it feels like wasted time, you should know that I am very gratefull that you did it!

Have a great day :)

**Comment by mosbat** [comment] 2024-11-04 15:20
> Hi @mosbat ,
> 
> Ohh okay, thank you so much :)
> 
> Do you know where the translation service is? Just so I know where to add this in the future?
> 
> Thank you so much for taking your time to make the PR, even tho they dont accept translations there.
> 
> Even tho it feels like wasted time, you should know that I am very gratefull that you did it!
> 
> Have a great day :)

No worries, I'm new here and learning.

Based on what @greyson-signal said here (https://github.com/signalapp/Signal-Android/pull/13764#issuecomment-2454724025), he didn't indicate which service that is. However, I did suggest that such information regarding translations should be added to CONTRIBUTING.md (same as on the Desktop client of Signal repo).

I'm looking forward to contributing to Signal :)

**Comment by iamjustmeithink** [comment] 2024-11-04 15:40
Ohh oki :)

I think you are on the right track! Just keep doing it and learn along the road :)

Best of luck in the future :)

**Closed as completed** 2024-12-05 07:24 UTC
