### ISSUE TITLE
Emoji reaction gets assigned to wrong chat

### ISSUE THREAD

**Issue by chiraag-nataraj** [signalapp/Signal-Android#11327] opened 2021-05-21 23:59 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
An emoji reaction in one chat (as identified by the name in the notification and the name in the reaction menu) has been assigned to a different chat.

### Steps to reproduce
I honestly don't know. I was using the app as normal and forwarded a message to a bunch of people. One person reacted to the message (and was correctly attributed on `signal-desktop`), and the reaction is being shown in a different chat (same message --- the one I had forwarded to a bunch of people). Both chats are one-on-one chats.

**Actual result:**

The emoji reaction isn't available in the right chat.

**Expected result:** 

The emoji reaction should be in the right chat.

### Device info

**Device:** Samsung Galaxy S7
**Android version:** 8.0.0
**Signal version:** 5.11.5

### Link to debug log
https://debuglogs.org/b9138fa5b3eb2cabcf159f88a2ac0adcf646e6903b053dacec8ad4433fdecf6e

(apologies, I only thought to capture it a while after it happened)

**Comment by dstj** [comment] 2022-01-17 02:55
I got the same issue since yesterday. 

Several emoji reactions are automatically assigned (i.e. not by anyone) as soon as a message is sent, and today, one was assigned to someone that is not even in the conversation!

My friend does not see the reaction on her side and on the desktop client, no reaction is visible for that message on my end as well.

This is, to say the least, disconcerting.

Image 01
![01](https://user-images.githubusercontent.com/467692/149700371-be93548c-73cc-4e51-a4ba-130529e13cc5.jpg)

Image 02 (reaction details)
![02](https://user-images.githubusercontent.com/467692/149700372-87a00166-a54d-4621-8d7b-cbbd795921ff.jpg)

Logs: https://debuglogs.org/2fb5eaa9dc9bdc88a33c6f42278877c31563f8719269d9a5854694fdb5ee32d9

**Comment by greyson-signal** [comment] 2022-01-18 16:02
@dstj Can you please share the 'sent message timestamp' of the message that incorrectly got assigned the reaction? To get this, long press the message, click the 'i' button to go to message details, and then long-press the sent time. This will copy the timestamp to your clipboard. Should be a long number like 1642521730188.

**Comment by dstj** [comment] 2022-01-18 16:07
@greyson-signal can do.

Sent: 1642385458435
Received: 1642385458534

**Comment by dstj** [comment] 2022-01-18 16:58
@greyson-signal 

> Are the bad reactions appearing on the message as soon as they're sent/received? Or sometime later?

Instantaneously. Like freakingly fast! Sometimes, it says it's me that reacted, sometimes it shows my friend with whom I'm chatting, and sometimes someone from another conversation. But always so fast that it feel like it's as soon as I touch the send button.

> Are the bad reactions always on the same messages, even after closing the app or sending/receiving new messages?

Yes, once they are there, they remain there and survive app restart, force stop, phone restart, etc. Only there on **MY** Android app, not on my Desktop.

> How often is this happening?

Started 2-3 days ago, happens on ~20% of the messages I would say within that one conversation. But I don't use Signal with many people yet, so that number may not be representative.

**Comment by greyson-signal** [comment] 2022-01-18 17:58
@dstj Thank you so much for being so responsive. Another question: your log says that your latest install in ~12 days old (at the time you created the log). Is that accurate, and did you restore from a backup at that time, or did you do a fresh install?

**Comment by dstj** [comment] 2022-01-18 18:08
@greyson-signal 
Yes, just got a new phone.

I transferred from my old phone using the account transfer, then relinked my Desktop app.

I also deleted all my conversations to basically avoid having super old messages since I had set a 4 weeks expiration on the messages some months after the initial conversation was started.

**Comment by greyson-signal** [comment] 2022-01-18 19:20
Ahh thank you so much for including that and the details about the expiring messages. We believe we understand what's happening now.

When you create a backup (or do a device transfer), we skip messages with expiration timers. However, we still (unintentionally) include the reactions for those messages in the backup.

These 'abandoned' reactions were being associated with newly-sent messages because the new messages had the same ID's as the expiring messages we skipped in the backup.

It's worth noting that in order to hit this bug, you have to:
- Have messages that are expiring, but have not expired yet
- Those messages have to have reactions
- Those message have to be *the most recent* messages in your message table

If you do a backup-restore in this scenario, then you could have this problem.

I'm putting a fix together now that should (1) prevent this from happening in future backup/restores and (2) clean up any of these 'abandoned' reactions so that newly-sent/received messages will not have these 'bad' reactions attached.

Unfortunately, it's not possible for me to remove any 'bad' reactions you've *already seen*, as there's not reliable way to tell the difference. Apologies.

And thank you again for being so responsive and helpful!

**Comment by dstj** [comment] 2022-01-18 19:52
@greyson-signal 
Wow, that was a hard one to find and reproduce. Good job to have figured it out so quickly!
Glad I could help!

**Closed** 2022-01-18 22:28 UTC
