### ISSUE TITLE
Others default to Signal, not SMS, after uninstall

### ISSUE THREAD

**Issue by drbeco** [signalapp/Signal-Android#11164] opened 2021-04-04 13:50 UTC
Checklist: 
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

When you install Signal and set it as SMS client, all your contacts that also have signal app will not send default SMS again.
They will default to Signal msg.

If someone uninstall Signal after that, you still have the option to send Signal messages, that are now default.

That is very confusing, as people without so much tech knowledge will feel like they cannot send message to a contact anymore.

### Steps to reproduce
- A friend install Signal
- Your Signal app now detects it and change the default from SMS to Signal
- That friend uninstall Signal
- Your Signal app still sends Signal msgs, not going back to default SMS

**Actual result:** You end up sending a Signal message to a contact that does not have Signal anymore, and the message is never received. Your app still thinks the contact have Signal.
**Expected result:**  Your app should go back to default that specific contact to SMS, not Signal. When you try to send a Signal msg to a contact that does not have Signal installed, Signal app should detect that and change your message to SMS.  Lost of data is the worst kind of error, and in this case, lost of communication (that may be urgent), until the sender realizes what is happening.

### Screenshots
No screenshots needed for this explanation.

### Device info
No device info needed for this bug.

**Device:** two devices
**Android version:** multiple
**Signal version:** last for Android from play store (5.5.5) 

### Link to debug log
No link debug log generated

**Comment by Sgn-32** [comment] 2021-04-04 14:32
Signal detects inactive users and unregister them automatically.

https://community.signalusers.org/t/how-long-does-it-take-until-signal-auto-detects-a-user-uninstalled-signal-without-unregistering/25171

**Comment by UserX404** [comment] 2021-04-04 14:58
It's not a bug and you should close this issue.

Your friend has not deleted his account and so the account is active for some time. Sgn-32 has pointed the corresponding forum thread. You are able so see the 2 check marks when a message is delivered. If only one check mark is displayed for a longer time try to contact the person on an other channel and ask whats going on. If he uninstall tell him he need to [unregister](https://support.signal.org/hc/en-us/articles/360007061192-Unregister-or-Delete-Account) the account.

It's the same if you send an email and the address has been changed.

**Comment by EmberHeartshine** [comment] 2021-04-07 09:58
I would consider this a UX bug. Uninstallation should unregister a client, or if that isn't possible, Signal should display a message stating that the message couldn't be delivered over Signal instead of forcing users to depend on tiny checkmarks most non-techies ignore completely.

**Comment by drbeco** [comment] 2021-04-13 01:37
My friend is a 74 y.o. lady, who I should not expect to understand such intrincases. It should be as easy as "uninstall and you are gold again".

**Comment by grandchild** [comment] 2021-04-13 08:58
It's an Android thing. An app has no way to know it is being uninstalled. The app just get's killed and removed. This is a security feature, so apps you want removed cannot execute a single line of code anymore. In consequence, the server has no way of knowing whether the device is just on a long jungle trek or the app got uninstalled. There is really little Signal can do here.

Other people's Signal should default back to SMS after some time (see the forum thread above for the exact times, which can vary).

**Comment by EmberHeartshine** [comment] 2021-04-13 09:12
> In consequence, the server has no way of knowing whether the device is just on a long jungle trek or the app got uninstalled.
To the end user, there is no difference.
> Other people's Signal should default back to SMS after some time (see the forum thread above for the exact times, which can vary).
Per the thread above, that process can take up to *a year*. That's unacceptable. Signal should detect when messages aren't getting delivered and notify the end user, and if the end user has the recipient's phone number in their contacts Signal should ask whether they want to fall back to SMS.

**Comment by greyson-signal** [comment] 2021-04-13 13:36
> My friend is a 74 y.o. lady, who I should not expect to understand such intrincases. It should be as easy as "uninstall and you are gold again".

Hi there, as others have helpfully noted, the issue is that your friend is still technically registered. FCM does have an event that tells us when a user uninstalls, but it's incredibly unreliable and often only happens after a massive delay. Unfortunately it just isn't technically possible with the information we're provided by the system :/

> Per the thread above, that process can take up to a year. 

We're currently looking into adjusting some of these times, but they're still going to be long (i.e. measured in months). 

> Signal should detect when messages aren't getting delivered and notify the end user

We've thought about this in the past, but it's always turned into something not-incredibly-useful. The timer would have to be at least a day or something, and being told that a message you sent yesterday wasn't delivered is probably unhelpful or redundant at that point (i.e. most people would have already realized that something was up by then), and also runs the risk of annoying people with false positives (i.e. in very large groups where there's probably at least one or two inactive users, or for messages where you *already knew* someone was on a hiking trip and now you're getting bothered with notifications).

And we'll never suggest people send an SMS to someone who may still registered. We're an encrypted messaging app. 

Still, there may be something here, provided we get the timing and UX right. But the original bug is not directly fixable, and GH isn't a forum, so I'm gonna close this. Thanks, everyone!

**Closed by greyson-signal** 2021-04-13 13:36 UTC

**Comment by UserX404** [comment] 2021-04-13 16:42
> 
> 
> I would consider this a UX bug. Uninstallation should unregister a client, or if that isn't possible, Signal should display a message stating that the message couldn't be delivered over Signal instead of forcing users to depend on tiny checkmarks most non-techies ignore completely.

Just for personal interest... How does other Messenger handle this? What happens if you uninstall WA and an other person message you?

**Comment by EmberHeartshine** [comment] 2021-04-13 16:44
> Just for personal interest... How does other Messenger handle this? What happens if you uninstall WA and an other person message you?

I don't know about WA, since I've never used it, but other messaging clients have a much more visible difference between sent, delivered, and read messages.

**Comment by drbeco** [comment] 2021-07-11 00:19
> 
> Just for personal interest... How does other Messenger handle this? What happens if you uninstall WA and an other person message you?

WA does not substitute SMS. If you send a WA, it goes only to the WA messenger or fail.

**Comment by karlkeefer** [comment] 2022-02-07 22:33
+1 for @zacharycohn 's suggestions. Because of being burned by this before, I now hesitate to use signal with anyone unless I'm _sure_ they are currently active users from out of band communication with them. In practice, that means I'm not bringing others into my network of signal contacts, even if they show up as having an account in the app.

**Comment by jeremywiens** [comment] 2022-08-02 05:15
I just missed out on placing an offer on a house because of this issue. I guess my lender had signal at some point but poor ole me just thought he was too busy to respond to me...

As far as I know there are 4 states:
1. Sending - spinner
2. Sent - one checkmark
3. Delivered - two check marks
4. Seen - check marks filled in

A single checkmark does not make it obvious that the person has definitely not seen my message unless I really stop to think about it.

Why not use a second spinner for while the message is delivering? 

I am also heavily in favor of a notification after 5 minutes of either of those what should be spinner states (sending or delivering)
