### ISSUE TITLE
can't retrieve MMS

### ISSUE THREAD

**Issue by skierpage** [signalapp/Signal-Android#4878] opened 2015-12-14 00:20 UTC
Someone sent me an MMS, probably from iPhone. It shows up as

  _Multimedia Message_
  MMS download failed!
  Message size: 967 KB
  Expires: Dec 16
with an exclamation in a circle.
I tried turning off Wi-Fi and clicking the  exclamation, it displays Connecting to MMS server... then redisplays "MMS download failed!".  I have SMS and MMS On, I don't know about "Push", I haven't changed any settings.

The log gist is https://gist.github.com/anonymous/86a162b00ea8545a45a7 , in that e.g.

```
E/PduParser(  516): Corrupt Part headers
W/IncomingLegacyMmsConnection(  516): Couldn't parse PDU, byte response: [-116, -124, -115, -110, -123, 4, 86, 110, 9, 126, -112, -127, -118, -128, -113, -127, -122, -127, -103, -30, -102, 77, 101, 115, 115, 97, 103, 101, 32, 110, 111, 116, 32, 102, 111, 117, 110, 100, 0, -124, -125, 77, 101, 115, 115, 97, 103, 101, 32, 110, 111, 116, 32, 102, 111, 117, 110, 100]
W/IncomingLegacyMmsConnection(  516): Couldn't parse PDU, ASCII:         �����Vn ~����������Message not found���Message not found
```

I tried turning WiFi off and clicking, same result.
Thanks!

**Comment by vay-ix** [comment] 2016-02-20 02:15
I'm also experiencing this problem. I am unable to receive MMS but am able to send it, whether is be group texts, or media like pictures and sounds.
This basically happened overnight... 3 or 4 days ago, I had  no problems with sending and receiving group texts

Here's the latest debug log, go nuts, it's all Greek to me: https://gist.github.com/2d62692c744614c8ce77
I am connected to my mobile network (Ting (CDMA: Sprint and GSM http://ting.com/coverage)) and nothing else!

**Comment by moxie0** [comment] 2016-02-20 07:17
@vay-ix There's nothing in this log. You would have to capture the debug log immediately after the failure you're experiencing.

**Comment by effigies** [comment] 2016-02-23 21:28
Here's a debug log from very shortly after the failure to retrieve two or three (I don't remember how many I'd received when I captured the log). Afterwards, I was able to download (in a browser on the same phone) one of the messages by following a URL in the gist. I am still unable to download any of the messages from within Signal.

----

I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

### Bug description
Cannot receive MMS messages, and MMS settings seem to be missing.

### Steps to reproduce
- Fail to retrieve MMS
- Try to check MMS settings

### Screenshots
![signal_mms_failure](https://cloud.githubusercontent.com/assets/83442/13266665/20ac1664-da47-11e5-8c45-e84896afdc62.png) ![signal_no_mms_settings](https://cloud.githubusercontent.com/assets/83442/13266664/20abd3d4-da47-11e5-9174-beecb63b0042.png)

### Device info
 **Model:** Samsung Galaxy S5
 **Android version:** 5.1.1 (CyanogenMod 12.1-20160129-NIGHTLY-kltespr)
 **Signal version:** 3.11.1

### Link to debug log
https://gist.github.com/effigies/148bf707f27f190bdf8a

**Comment by BierCrow** [comment] 2016-03-15 17:03
MMS is complicated. Even if the app is perfect, some phones just won't work with anything other than the stock messaging app. I know for instance Republic Wireless MMS only works with the stock app and Google Messenger. Getting MMS to work with other apps on my Moto X seems to be hit or miss (mostly miss). You might try other 3rd party messaging apps to see if MMS works with those. If it doesn't, then it's not a Signal problem.

**Comment by gene1wood** [comment] 2016-03-16 19:58
As a Republic Wireless user (also with a Moto X like @BierCrow ) of Signal, is there a workaround to the MMS issue? I ask not because I need to send MMS messages (pictures, multi-recipient texts), but because when someone sends me an MMS message and I have signal set as my messaging app, the MMS message is lost. The cost to me to reply to all received MMS texts saying "Hey, I didn't get your MMS message because I can't receive them with my messaging app, can you either email me your photo or text me directly without including other recipients" is too great to be worth the benefit of defaulting to using signal for texting.

If there was some way (even if it was complicated) to recover/retrieve a received MMS message by signal that fails in this way, that would be a suitable workaround.

Any ideas?

**Comment by gene1wood** [comment] 2016-03-16 20:27
It sounds like the [Google Messenger app and the Google Hangouts app both work using SMS with Republic Wireless](https://community.republicwireless.com/docs/DOC-1861#jive_content_id_Unable_to_Receive_Picture_Messages_MMS).

And it sounds like the way they accomplish this (and some other third party messaging apps) is [by using the stock messaging app as the interface to sending and receiving messages](https://community.republicwireless.com/thread/52806#comment-441725) instead of sending and receiving the messages directly.

Would it be possible to implement in Signal the same kind of option and the same kind of behavior, such that instead of signal doing the MMS receipt and sending on it's own (if this option were checked) it would handoff responsibility to actually transport the messages to the built in messaging app.

The app they give as an example that successfully does this is called is called [GroupText](https://play.google.com/store/apps/details?id=com.smallbouldering.grouptext). Maybe that can be used as a guide for how to implement this.

**Comment by riyapenn** [comment] 2016-03-18 01:35
Contact support@whispersystems.org to test/troubleshoot to get this working.

**Comment by effigies** [comment] 2016-03-24 21:19
I think this may have been resolved by dd986dbc4bbf8cefc6fc8dba6ad4b715cc160c73... Signal has resumed downloading MMS normally. @skierpage did 3.14.2 fix this for you?

**Comment by gene1wood** [comment] 2016-04-22 18:37
So I had 2 friends test with me, one a T-Mobile user and one an AT&T user. I had them send a multi-recipient MMS message to me and I received it with my stock messaging app and it worked as expected.

I then switched to Signal as my default app and had them send another message in the MMS multi recipient thread. To my surprise both of the messages arrived in Signal as expected.

So this implies that either the issue is carrier specific and the problems with receiving MMS before were constrained to carriers other than AT&T and T-Mobile

or the problem has been globally resolved since that point either on my phone or from a Signal update.

**Comment by jodosh** [comment] 2016-05-24 14:46
Both me and my wife have the nexus 6 on Tmobile. With signal we have many problems with MMS intermittently failing to download and sending. Tmobile engineering support has done some trouble shooting and their logs indicate that our phones disconnect from the MMSC before the MMS is fully downloaded. This doesn't appear to happen with other messaging apps.

**Comment by jmcclelland** [comment] 2016-05-25 01:29
I'm using cyanogenmod with Sprint  - I couldn't send or receive MMS messages. Sending reported that there was an error (but no further information). Receiving provided me with a download link, but clicking on the link caused a brief period where it seemed to be doing something, followed by nothing.

I checked the Signal logs and found "No matching APNs found."

I did the following to fix the problem:

I checked my APN settings: Settings -> Mobile Network -> Access Point Names -> Sprint LTE internet (the selected one). I noticed that MMSC was set to: http:/mms.sprintpcs.com.

Then, I opened Signal. Settings -> SMS and MMS -> Manual MMS Settings -> MMSC URL: I set it to http:/mms.sprintpcs.com.

Now both sending and receiving work.

**Comment by remram44** [comment] 2017-02-11 01:30
Can't download MMS today on T-Mobile. The "Manual MMS Settings" doesn't seem to be there, either. I am forced to stop using Signal as my SMS/MMS app because of this, and still the MMS conversation is lost.

Android 7 on stock Google Pixel, Signal 3.28.4 from market.

**Comment by databaseindays** [comment] 2017-03-12 17:17
this is affecting me as well on my Samsung galaxy 5 when on a group text and sent MMS. "says error downloading MMS message, tap to retry" with Signal as the default text app.

**Comment by remram44** [comment] 2017-03-12 17:23
Is there a workaround, at least allowing me to see those MMS messages from another app? Or is there no hope because Signal was the texting app when I got them?

**Comment by bradleytaftsmith** [comment] 2017-04-30 16:08
Also seeing an issue downloading MMS messages on a Samsung Galaxy S7, Android 6.0.1 on Credo Mobile. It seems to be multi-recipient messages, but it may be pictures.

Debug log is [here](https://gist.github.com/ef04dbfaa7b3029113941ceedde08384).

**Comment by beruken** [comment] 2017-05-03 11:22
Same issue here. Only works with data turned on. 
Are you using Tmobile? YES
Is MMS only working on mobile data?  Then enable "WiFi calling" on your phone AND through Signal's Settings > SMS and MMS > enable WiFi calling compatibility mode. Still does not work.

**Comment by Powwers** [comment] 2017-05-13 05:07
I'm not a phone guy, first off. My Kata C2 has never been able to send or receive MMS unless it's via Signal software. My understanding is that Signal is entirely Internet based. Another of my understandings is that MMS is structured like an email with different headers.

Is my Signal just not operating correctly? I have done weefee and disabled it, MMS works fine between users of Signal, whether I'm on weefee or not. I cannot get or send shit to/from anyone who doesn't use Signal.

Rather not stray from Signal. I know my answer is there, spelled out but why would I have to stray from Signal for this to work? I've had phones that were completely fine until now

Kata C2 - Duracell 32GB chip implant

P.S. Memes are life and this has to be fixed

**Comment by Powwers** [comment] 2017-05-13 05:24
Privacy is key. You guys are phenomenal and keep up the good work for the good fight. If there's any more testing or info that you require, don't hesitate to hit me up. You can do this. Or maybe my phone is just garbage but I brought hell fire to my provider and they couldn't do anything, not that they're too technically inclined at 16 working a phone sales kiosk. Not saying I'm gawd of phones either! Willing to help what I can if possible

**Comment by timhowes** [comment] 2017-05-15 15:59
@Powwers  Messages between Signal users are not SMS or MMS; they use the Signal protocol. If you can't get MMS inside Signal or outside Signal, then you have a more general problem with your phone or service provider. This thread is about MMS messages that appear in Signal but fail to download.

**Comment by QuibblingAsh42** [comment] 2017-05-15 17:12
Greetings, adding my own logs to the fray.  Been using Signal for a few months now, and have had similar issues downloading MMS attachments consistently.  Sometimes having the sender resend works fine, other times it doesn't.  Sometimes it works if I reboot, most times it doesn't.  Debug log [here](https://gist.github.com/1400ffb8e87b9e0d066a2ad79009c4fe).

**Comment by karlockhart** [comment] 2017-05-22 17:03
I am also having this issue, I tested with both stock SMS and Signal, Signal fails to receive from a non-signal SMS/MMS user.

**Comment by apotek** [comment] 2017-05-24 19:05
I have the same issue as described in this thread. MMS messages (group chats, or media files) won't download. There will be a display saying it failed to download and when I re-attempt, it fails again.

The only way I can them to work is to go someplace where there is wifi, turn the wifi on, and attempt to download the mms again. If the mms is recent enough (within the last 24 hours) it will most of the time finally work. 

However, it won't work if I try *exclusively* over wifi. I need to have both my native provider network as well as wifi turned on to get the MMS message. 

The upshot is that I can't get MMS messages via signal (other messaging apps work fine), unless I quickly get to a wifi network and try to download them again.

Moto E (otus).
t-mobile

**Comment by timhowes** [comment] 2017-05-24 20:28
Users experiencing MMS issues may want to refer to this troubleshooting page:
https://support.whispersystems.org/hc/en-us/articles/214785937-I-have-MMS-issues-What-can-I-do-

If you need to fix your APN settings on T-mobile, check this page:
https://support.t-mobile.com/docs/DOC-2090

**Comment by remram44** [comment] 2017-05-24 21:03
I don't think any of us here have problems receiving MMS outside of Signal. Never had a problem before, never had a problem since I stopped using Signal for SMS & MMS. There is a bug in Signal.

**Comment by QuibblingAsh42** [comment] 2017-05-25 14:39
I decided to work through the troubleshooting page, and resetting my APNs to default seems to have worked for now.  (Settings, Cellular Network Settings, Access Point Names).  

In there, I had two entries, Cricket (my provider) and Internet.  The Cricket entry looked more or less correct when I reviewed, but when I did Reset to Default, the Internet entry went away, and the Cricket entry's parameters changed dramatically.  

For example, items were pointing at Cricket domains (proxy.cricketwirelss.com) prior to the reset, but AIO ones (proxy.aiowireless.com) after.  AIO was the ATT MVNO from ATT that was merged with Cricket when ATT bought Cricket, so not sure where those settings originally came from, but it's working now.  

I'll be interested to see how long this lasts, though.  I've had ups and downs with Signal's MMS implementation where it's worked, then not, then did.  This really needs to be figured out to gain mass adoption.  I've been telling people "Signal's so easy, I have my mom using it!", but I'm not moving anyone else to the platform until that statement is true again.

**Comment by remram44** [comment] 2017-05-25 14:42
@QuibblingAsh42
> I decided to work through the troubleshooting page, and resetting my APNs to default seems to have worked for now. (Settings, Cellular Network Settings, Access Point Names).

It seems to me that your MMS settings were broken at the phone level and wouldn't have worked outside of Signal anyway? This is not the issue the rest of us are experiencing.

**Comment by QuibblingAsh42** [comment] 2017-05-25 14:55
No, I removed Signal as my default messenger a couple of weeks back to test and had no issues. The issue only returned when I used Signal.  I never touched APN settings prior to today.  I'm not sure why Signal can't work with the same settings that worked for other apps.

**Comment by remram44** [comment] 2017-05-25 14:58
Interesting! Maybe there are specific APN configurations that Signal chokes on but other apps can handle. Or maybe the fact there are multiple entries?

**Comment by QuibblingAsh42** [comment] 2017-05-25 15:05
That's what I was leaving toward.   Don't know where that Internet one came from, or even if was there since I put my current ROM in my phone.  Hmm... I should try laying down a fresh install and see.  I wish I'd taken a screenshot of the settings within to review, too, but I hadn't had coffee yet... :)

**Comment by evantd** [comment] 2017-06-22 01:15
[Significant MMS changes](https://github.com/WhisperSystems/Signal-Android/commits/master/src/org/thoughtcrime/securesms/mms/CompatMmsConnection.java) were made in May 2017 that may have resolved this issue. Is it still a problem for you?

**Comment by QuibblingAsh42** [comment] 2017-06-26 17:51
Since I modified the APN settings on mine, I haven't had any issues with MMS.  All of those changes seem to have occurred prior to my making those changes, and I'd confirmed there was no update to the app prior to working through the issues on the 25th.

**Comment by Glassweaver** [comment] 2017-08-02 04:57
This exact same issue skierpage reported has also been happening to me for years. MMS messages almost never send, and are almost never received. Most recently, a friend of mine **who also uses Signal** will attempt sending me a picture...on her end, the picture claims sent, with one checkmark. On my end, I never receive it. 

Other messaging applications (such as Google Messenger, or the stock messaging app) work just fine, so in my case, it's isolated to Signal. 

Has anyone figured this one out yet? If it helps, here's a debug log from my phone about 5 - 10 seconds after attempting to send an MMS to another signal user and having it fail. https://gist.github.com/anonymous/0f05120bb6aca37f960dd9aed26ae993

**Comment by thephw** [comment] 2018-01-15 17:40
@evantd 
FWIW, I am having this issue with Signal (4.14.10) and Cricket Wireless presently, but not with the default messaging app. The proxy settings for Cricket on Android devices are wrong by default, but mine have been updated and verified to work in other SMS/MMS apps. If there is anything else that I can provide that may assist in debugging please let me know and I'll provide it.

Debug Log 1/15/2018:
https://gist.github.com/thephw/21cc94d1ac75457948f65e69af28c975

**Comment by evantd** [comment] 2018-01-16 17:16
Hi @thephw. Sorry, I don't know. The only reason I was active on this is that I was having my own MMS issues, which were resolved with a previous update.

**Comment by automated-signal** [comment] 2018-04-02 23:12
GitHub Issue Cleanup:
See #7598 for more information.

**Closed** 2018-04-02 23:12 UTC
Labels: mms
