### ISSUE TITLE
Cannot receive calls on Android anymore

### ISSUE THREAD

**Issue by petcap** [signalapp/Signal-Android#10787] opened 2021-01-24 09:23 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Since the downtime last week, I am unable to reliably receive calls on my Android phone. When someone calls me, I instantly get the "missed call" notification on my phone, even while Signal-desktop is still ringing. This problem does not seem to be restricted to Android, as I have friends and family who are on iPhone and are experiencing the same issue.

Things I've tried:
- Reset the secure session, both ways
- Turn on and off call relaying via the Signal servers
- Different network combinations, both WiFi and LTE
- Having Signal open on the called phone, with the screen on when placing a test call

### Screenshots
![Screenshot_20210124-101345](https://user-images.githubusercontent.com/8736529/105626073-eac12d80-5e2d-11eb-9252-685e56335f98.png)

### Link to debug log
This debug log is from the phone that is being called.

https://debuglogs.org/ccef93ca0b3dbfe8dc6f2e4cb5e182c58ef193631d54e405df2f85bff58f5d5a

**Comment by leonidax** [comment] 2021-01-24 14:04
This is a duplicated ticket:

https://github.com/signalapp/Signal-Android/issues/7733

**Comment by valldrac** [comment] 2021-01-26 17:59
t could be the old known issue that the app failed to retrieve the turn servers list, but this time has gotten worse.

Seems that in v5.2.2 a new feature flag was introduced to prevent okhttp from retrying network requests. This affects negatively the call service when it retrieves the TURN servers from Signal. It happens because there is no retry policy, like tasks run via JobManager.

If the websocket connection to the Signal server is stale and it has not yet restarted, the function "retrieveTurnServers" will instantly fail with "java.io.IOException: unexpected end of stream" raised by "getServiceConnection" and the call will show the network-failed popup.

**Comment by afmbsr** [comment] 2021-01-27 13:46
Isn't there a great developer fixing this problem?! Since installing the application a week ago and until now, I have not been able to receive any calls at all

**Comment by AsamK** [comment] 2021-01-31 15:34
The `retrieveTurnServers` method doesn't use the websocket connection, but just sends an HTTP request.
It seems the issue is the okhttp connection pool. Which by default keeps inactive connections around for 5 minutes, but the signal server closes inactive connections already after 60 seconds.

So after closing the app, if an incoming call is received
- within 60 seconds the call to retrieve the turn servers will succeed by reusing an existing connection.
- after 1 minute and before 5 minutes, the call will fail because it reuses an already closed connection
- after 5 minutes the call will succeed again because the stale connections have been removed from the okhttp connection pool.

**Comment by szotsaki** [comment] 2021-04-03 08:12
This is most probably a duplicate of https://github.com/signalapp/Signal-Android/issues/7733. May I ask to close this issue (to avoid having duplicates) and continue the conversation in the linked ticket?

**Closed** 2021-04-03 08:16 UTC
