### ISSUE TITLE
Wishlist: Possibility to delete images in gallery mode (and when opened)

### ISSUE THREAD

**Issue by mawed** [signalapp/Signal-Android#6111] opened 2017-01-27 09:29 UTC
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Feature description
When opening "Image gallery" (or lateron media gallery due to #5941) I would like to be able to multiselect images/media and delete them.
And when opening an image/media, I would like to have the possibility to delete it in this opened view.

Maybe putting this option behind a settings menu as the action bar already contains forward, save, All Images. (In Gallery mode only save).
IMO there should be a dialog, if you really want to delete this (all the selected images).

---
~One point to think about is the corresponding messaged (text).
At the moment, it's only possible to delete the whole messagte (text + image/media) by selecting it right in the conversation.
When deleting in the gallery mode or when opened, the corresponding text is not visible to the user, so maybe it should be contained (with a hint to the deleted image/media)?~[Edit: Duplicate of #4242]

**Comment by FeuRenard** [comment] 2017-01-27 10:13
Duplicate of #4242

**Comment by mawed** [comment] 2017-01-27 10:22
@FeuRenard You're right, the possibility to delete images/media unrelated to the corresponding text is a duplicate.
I addressed this by editing the description of the issue.

IMO the possibility to delete the image/media out of gallery mode (or when open) is not a duplicate, even if it would solve #4242.
If #4242 is implemented only in conversation view, my feature request would differ.

**Comment by Natanji** [comment] 2017-05-05 10:28
I'm glad @haffenloher implemented this feature, I hope it gets merged soon.

This is especially important for people who have been using Signal for a long time and have a large database (I know people for which the Signal app is using easily over 1 GB of data by now!). Right now it is impossible to export then delete all media from the database, and the workaround of making a plain-text backup, deleting Signal data, then re-importing it also isn't feasible due to #3024. So #6165 really really improves this situation a lot.

**Comment by FeuRenard** [comment] 2017-05-22 14:01
> Possibility to delete images (...) when opened

is a duplicate of #2798

**Comment by automated-signal** [comment] 2018-04-03 01:10
GitHub Issue Cleanup:
See #7598 for more information.

**Closed by automated-signal** 2018-04-03 01:10 UTC
Labels: feature
