### ISSUE TITLE
Can only receive 1st picture on mms with multiple pictures attached 

### ISSUE THREAD

**Issue by jkanethird** [signalapp/Signal-Android#1300] opened 2014-04-05 18:13 UTC
When I receive an mms from an iPhone with multiple pictures attached, I only get the first one. I'm on AT&T, using an Android 4.4 phone.

**Comment by ryannathans** [comment] 2016-07-15 12:32
NOT a duplicate of #736 or #1132

### Bug description
When receiving MMS containing multiple images from non-signal contact, only first image is shown. 

### Steps to reproduce
- Make new MMS on another phone containing multiple images
- Send to signal phone


**Actual result:** Signal only shows image 1
**Expected result:** Signal shows all images in MMS message

### Device info

**Device:** Samsung Note 3
**Android version:** 5.0.0
**Signal version:** 3.16.0

### Link to debug log
https://gist.github.com/anonymous/a8814012a48c9031cc736bf3e4d44e8d

**Comment by ryannathans** [comment] 2016-07-15 12:48
Can also confirm on Samsung Note 4/5.1.1/3.16.0

**Comment by riyapenn** [comment] 2016-12-11 20:31
Recent log from Signal v3.24.1: https://gist.github.com/7d15856066dfd944264e25e134915eb9

**Comment by castanley** [comment] 2017-06-18 15:05
Please fix! I didn't realize I was missing so many pictures until a friend told me. Come on, this is 6 months old! I am willing to donate money for this to be resolved. Can we have a bug bounty setup?

**Comment by rthomas6** [comment] 2017-06-20 15:58
Just chiming in that this is real and a big deal. My mom likes to send me pictures of my son when she's babysitting him. When Signal is my default messaging app (and I want it to be), I get the first image out of who knows how many. I never get the rest. This bug is a dealbreaker for people I personally know. It's costing Signal users. The fix requirements are pretty straightforward, too: duplicate the functionality of literally any other MMS messaging app.

**Comment by moxie0** [comment] 2017-06-20 16:11
Thanks everyone, but please do not "bump" issues unless you have new information to add: https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#dont-bump-issues

If you want to express your support for something, you can use the built-in "reaction" emojis.

I am the only full time developer working on this client, so while I wish I could make everyone happy, I unfortunately can't do everything at once. If something seems easy and a priority for you, feel free to take a stab at it with a PR.

**Comment by forevermatt** [comment] 2017-06-20 21:16
@rthomas6 If it's any consolation, it is actually possible to see the rest of the images in Signal. When you tap on the one image shown in the conversation, then tap the icon in the top-right corner that looks like two photos stacked on top of each other ("All media"), you can see the rest of the images. There was simply no indicator in the conversation that more than one image was received.

@moxie0 Thank you for all the work that you have put into Signal and its related technologies. Serious kudos.

**Comment by rthomas6** [comment] 2017-06-20 21:35
Oh wow. Thank you, I did not know about this. That info downgrades this issue in my mind from "major bug" to "potential UI improvement".

Is this issue even valid if we're not actually missing images from MMS messages? We _are_ receiving all of them, they just don't display without navigating to another place.

**Comment by ddomains** [comment] 2017-06-27 18:13
This continues to happen, and now when someone sends text with multiple images, the text is all that displays.  When signal only displays one image, yes, the work around of clicking the icon works, but when it shows none, it makes it hard

**Comment by mftruso** [comment] 2017-10-20 18:17
I agree with @rthomas6 that a great UI improvement would be to add some visual cue that there are multiple images that came in an MMS. Also the ability to swipe left or right when viewing an image to navigate through media shared from that thread.

**Closed as completed** 2018-04-02 21:22 UTC
