### ISSUE TITLE
Text entered into quick reply toast is lost when another message comes in

### ISSUE THREAD

**Issue by deutrino** [signalapp/Signal-Android#6693] opened 2017-05-31 18:50 UTC
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

### Bug description
When a message comes in and a toast pops up with the ability to mark read or quickly reply, if I've entered some text and another message comes in, the next message's toast obliterates the one I was typing. No draft is saved.

### Steps to reproduce
- Be using an app that's not Signal
- Receive a message
- Start typing a reply in the toast box
- Receive another message (in my case from the same sender, I'm not positive a different sender will cause this)

**Actual result:** The 2nd message's toast pops up over the first one, and the message being entered into the first toast disappears.
**Expected result:** Preferably the 2nd message would be queued (or perhaps extend the toast vertically, if that's an option?), or at least a draft would be saved. Either of these options are not the greatest UX though.

### Device info

**Device:** I don't like sharing this info publically
**Android version:** 7.1.2 (LineageOS 14.1)
**Signal version:** 4.6.1

### Link to debug log
I don't currently have one - time crunch this morning - and not sure it will be useful, but if so, I will set up with a friend to induce this bug later today or tomorrow.

**Comment by p4nci** [comment] 2017-05-31 19:18
probably duplicate of  https://github.com/WhisperSystems/Signal-Android/issues/4729

**Comment by Dyras** [comment] 2017-05-31 19:41
@p4nci I don't think so, the issue you link mentions the text eventually comes back. In this issue however, it never does.

**Comment by FeuRenard** [comment] 2017-06-01 08:44
Just to make it clear for everybody: you aren't talking about Signal's own implementation of a quick reply window (first screenshot) but about the quick reply function introduced with Nougat (second screenshot).

### Screenshots
quick reply < Android 7
![signal-2017-06-01-103120](https://cloud.githubusercontent.com/assets/16167751/26671702/c6673462-46b6-11e7-8b61-b871812eef0f.png)

quick reply >= Android 7
![bildschirmfoto von 2017-06-01 10-38-00](https://cloud.githubusercontent.com/assets/16167751/26671709/ccf97c0e-46b6-11e7-9717-c47f46872f72.png)

**Comment by gordon-morehouse** [comment] 2017-06-01 08:54
I am referring to the Android 7 one, yes.

**Comment by FeuRenard** [comment] 2017-06-02 10:20
It sounds like this issue is related to #6050 and would be improved by implementing the requested feature.

**Comment by dcherian** [comment] 2017-07-07 16:47
Dupe of #6042 ? and both will be fixed if #6050 is addressed?

**Comment by deutrino** [comment] 2017-09-17 20:55
I think this is a dupe of #6042, although more discussion has accrued in this issue now.

**Comment by deutrino** [comment] 2017-10-09 18:16
I wanted to clarify when the text is completely lost.

* Receive message from a contact and hit reply in the toast notification
* Start typing into the text box within the toast
* Receive message from a *different* contact which pops over the toast
* Typed text is now irretrievably lost

If you receive a message from the *same* contact, it pops over the toast but the text can be salvaged by hitting 'reply' and loading the full app's reply UI.

It occurs to me that this bug could perhaps be avoided quite simply by never having a toast pop over one that already exists, or that the user is currently interacting with.

**Comment by automated-signal** [comment] 2018-04-03 02:37
GitHub Issue Cleanup:
See #7598 for more information.

**Closed by automated-signal** 2018-04-03 02:37 UTC
