### ISSUE TITLE
Signal Not At All Working Since 2-3 days !!

### ISSUE THREAD

**Issue by BUAWF** [signalapp/Signal-Android#8743] opened 2019-04-05 21:15 UTC
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I've No Idea, Why Signal's Network has Stopped working for Me, but with My Uncle's Device I've tried sending a Message, a tick mark is shown properly.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Samsung Galaxy A3 (SM-A300F)
**Android version:** 7.1.2
**Signal version:** 4.36.2

### Link to debug log

https://debuglogs.org/6f3298a5ac02fe61563ebb481297b97b4f71fc907a7dc3a60d7f64da42899090

**Comment by greyson-signal** [comment] 2019-04-05 21:20
Closing as dupe of #8736. The version with the fix is still rolling out, but if you want it faster, you can [join the beta](https://play.google.com/apps/testing/org.thoughtcrime.securesms).

**Closed by greyson-signal** 2019-04-05 21:20 UTC

**Comment by BUAWF** [comment] 2019-04-06 20:42
Greyson, I reside in India, as of v4.37.2 universal website release (I use only this, as I Never Install GApps at all while in Custom Roms!) it's Perfect without any isuues.
Thank You Mate.
God Bless You Dear.
I Pray to God that, You get Success in Every Step of Your Life.
Amen.
