### ISSUE TITLE
SMS Delivery Reports Not working for several months 

### ISSUE THREAD

**Issue by cleanerspam** [signalapp/Signal-Android#12056] opened 2022-03-12 05:24 UTC
- [ ✖️] I have searched open and closed issues for duplicates
- [ ✔️] I am submitting a bug report for existing functionality that does not work as intended
- [✔️ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ✔️] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Delivery Reports for Messages sent as SMS is not working at all 

### Steps to reproduce
- Send a sms to any number with Delivery Reports Enabled
- Even after SMS is received by recipient 
- Signal does not show that SMS is received 

This feature was working somewhere in 2021, it is not working for quite some time, I thought it wouod be fixed in some weeks but many months have passed with no removal of this bug 

### Device info

**Device:** realme 
**Android version:** 11
**Signal version:** 5.32.15

### Link to debug log
https://debuglogs.org/android/5.32.15/613c3453ca87ff58d20d11bc1a941ab01c52819dc5b181006ae2b50d342a48c9

**Comment by alex-signal** [comment] 2022-03-14 12:25
Duplicate of #11444

**Closed by alex-signal** 2022-03-14 12:25 UTC
