### ISSUE TITLE
Error importing sms during initial setup on Huawei device

### ISSUE THREAD

**Issue by waldenconsulting** [signalapp/Signal-Android#10377] opened 2021-01-08 13:51 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
During initial setup of Signal, import of System messages does not import anything. It doesn't give an error, but nothing is imported. I have found many mentions of this on various forums (it looks like any Huawei device, see e.g. closed but unresolved issue: https://github.com/signalapp/Signal-Android/issues/6198).

### Steps to reproduce
- Download and install signal app.
- after setting up, set signal to default and app, and when promoted, click "import system messages".

**Actual result:** 
Nothing happens, and no old messages are available in signal app.

**Expected result:** 
Old (system) messages should be imported.

### Screenshots

N/A

### Device info

**Device:** Huawei P30 Pro
**Android version:** 10 (EMUI v10.1.0)
**Signal version:** 5.0.8

### Link to debug log

https://debuglogs.org/3d5848fc9637b88cc6afcd929c60334a99da2f8f608e143ec9bd91332514cf0a

**Comment by AlexyPulivelil** [comment] 2021-01-08 16:41
For the login I got the code and the app itself copy the code but after that nothing happens. And there is no button to go to next screen.

**Comment by evrifaessa** [comment] 2021-01-10 15:11
Can reproduce in POT-LX1 with Android 10. Nothing seems to be imported.

**Comment by frontrunnersoftware** [comment] 2021-01-19 01:27
This SMS import mechanism worked fine on my own Oneplus 7T Pro.  However, my friends Honor View 10 phone wouldn't import SMS messages on initial install or using the menu option.   After clicking on the import banner, the app just moved on, but does not show any historical SMS messages.  I can send and receive them no problem.  I tried uninstall-reinstall, making Signal the default SMS app before import and allowing all permissions manually, but still no luck.

**Comment by go2null** [comment] 2021-01-20 12:22
Duplicate of #10618

**Comment by Aephir** [comment] 2021-01-21 11:21
@go2null not to be pedantic, but since this issue was opened before #10618, wouldn't #10618 be a duplicate of this instead? 

In any case, this issue is old (had problems months ago when trying, but since it was not urgent at the time, I just quit using Signal), and all reports on various forums said that it was specific for Huawei devices. That doesn't seem to be the case for #10618 (error). That is a new error (between v5.0.8 and 5.1.8). So I don't even think  #10618 is a duplicate of this issue.

**Closed** 2022-02-03 05:47 UTC
Labels: wontfix
