### ISSUE TITLE
Answered messages text size not affected by font size setting

### ISSUE THREAD

**Issue by Kwasow** [signalapp/Signal-Android#11187] opened 2021-04-09 07:16 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Changing the _Chats > Message font size_ setting doesn't change the size of text on answered message previews.

### Steps to reproduce
- Set the _Message font size_ to something else than _Normal_
- Answer a message in a conversation

**Actual result:** The font size was not changes on the answered message preview.
**Expected result:** The font size should change.

### Screenshots
![IMG_20210409_090650](https://user-images.githubusercontent.com/10947344/114142902-c4cb0580-9913-11eb-971a-ee8c7fe36c2c.jpg)
![IMG_20210409_091130](https://user-images.githubusercontent.com/10947344/114142909-c694c900-9913-11eb-9dbd-75d4bfecb5d5.jpg)

### Device info
**Device:** Redmi Note 9 Pro
**Android version:** 10.0
**Signal version:** 5.7.2

### Link to debug log
Probably not needed

**Comment by platinops** [comment] 2021-05-22 06:36
I have the same issue with Signal 5.10.8 on a Google Pixel 4a with Android 11.

**Comment by cody-signal** [comment] 2021-06-07 21:28
Duplicate of #10188, closing.

Fix from PR will be in 5.14.1 coming to beta soon.

**Closed by cody-signal** 2021-06-07 21:28 UTC
