### ISSUE TITLE
Please add external storage option

### ISSUE THREAD

**Issue by ThemGo** [signalapp/Signal-Android#9126] opened 2019-10-24 09:54 UTC
Please add the option to store data on external sd card instead of internal memory. The size of my data in folder /data/user/0/org.thoughtcrime.securesms/ is 3 GB now and it keeps on growing. I think I am not the only one, and I think this is a big issue, since most of the mainstream phones still only consist of 16 GB internal memory. 
And, I need all the data, i.e. I cannot delete chats or part of them because they contain conversations which are important for me.

**Comment by Cerberus0** [comment] 2019-10-24 14:24
Hi @ThemGo,

This is not the right place for feature requests. As stated in the [bug report template](https://raw.githubusercontent.com/signalapp/Signal-Android/master/.github/ISSUE_TEMPLATE.md) that you appear to have deleted, as well as the project's [CONTRIBUTING.md](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md), this issue tracker is only meant for bug reports. Bug reports should only be submitted for existing functionality that does not work as intended. You are welcome to submit and discuss ideas for non-existing functionality on the community forum. Please close this issue and continue the discussion there:

* https://community.signalusers.org

You can easily sign up/login on the forums with your existing GitHub account.

**Closed** 2019-10-24 15:25 UTC
