### ISSUE TITLE
Signal storage reporting missmatch

### ISSUE THREAD

**Issue by qubecub** [signalapp/Signal-Android#9946] opened 2020-08-21 10:25 UTC
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal app on Android reports storage in the way that does not align with Android system storage reporting - by the factor of 2 / two. 
Also backup file created by Signal app is much bigger thank Signal reported storage by about a 1/3. 

### Steps to reproduce
Open Signal app on Android, then:
Go to Settings->Storage
The screen displays storage used by the app, e.g. 3.1GB

Now to the phone/Android Settings -> Storage -> Other apps -> Signal 
Now the screen displays Signal app storage as seen by Android, e.g. 6.8GB

The third options is to create backup file in Signal App: 
Settings -> Chats and media -> Backups
Enable 'Chat backups' and create a backup file. The size of the backup file is: 4.1GB. 

These storage numbers are confusing, especially the first two. 

Why is Signal reported storage 3.1GB and Android storage for Signal 6.8GB? 
Why is Signal backup file so much bigger than Signal reported storage? 

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

Expected results - both Signal used storage and Android storage for Signal reporting should be aligned - if not identical then almost identical. The difference by the factor of 2 is misleading. 

### Device info

**Device:** Samsung S9
**Android version:** 10
**Signal version:** 4.69.4

**Comment by greyson-signal** [comment] 2020-10-08 00:26
Closing as duplicate of #9634 (which I believe is resolved)

**Closed by greyson-signal** 2020-10-08 00:26 UTC
