### ISSUE TITLE
Signal crashes after apparently completing db import on new install

### ISSUE THREAD

**Issue by deepskydiver** [signalapp/Signal-Android#9178] opened 2019-11-12 00:50 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I've upgraded from a Pixel 2XL to a 4XL both fully up-to-date OS.

I tried to copy and restore my messages from the old phone. The database is about 128mb.

It crashes once it finishes running through the complete message count.

I have tried a few times with the same version and earlier versions of signal. On first attempt the version on my new phone was 4.49.18 and the old phone 4.49.17. I then tried with 18 on both. The result is the same.

I tried earlier versions on the new phone but the message was that the passphrase was incorrect.

### Steps to reproduce
- save database on old phone, copying passphrase
- replace file in signal backup directory
- install signal accepting permissions
- choose option to import
- paste in passphrase

**Actual result:**
- watch counter tick to similar total seen on export
- signal vanishes
- on re-use app is at the import database step

**Expected result:** 
Successful import and completion of installation

### Device info
**Device:** Pixel 4XL
**Android version:** 10
**Signal version:** 4.49.18

### Link to debug log

https://debuglogs.org/3ed9f06d71208b1c433154e25de1fbe9c94ef6c4795c2b0db4be32cfc868470f

**Comment by Flupkees** [comment] 2019-11-12 16:20
Exactly the same happens to me, but I have 88000 messages and the backup database is 5GB, which I thought could have something to do with it, but reading your report, this may not be the case.

Both phones run 4.49.18
Old phone: OnePlus 6
New phone: OnePlus 7 Pro

**Comment by greyson-signal** [comment] 2019-11-12 19:28
Closing as a duplicate of #9154

**Closed by greyson-signal** 2019-11-12 19:28 UTC
