### ISSUE TITLE
Updates are not checked via mobile data (only via Wi-Fi) for the APK-installed app.

### ISSUE THREAD

**Issue by greenerk** [signalapp/Signal-Android#12711] opened 2023-01-05 08:32 UTC
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Updates are not being checked unless the device is on a Wi-Fi network.

### Steps to reproduce
- Install app via Android APK on Signal website.
- Disable Wi-Fi for a few weeks, leaving mobile data enabled.
- Enable Wi-Fi again.
- Notice than an update notification is presented after a few days, for a version that was published whilst Wi-Fi was off.

**Actual result:** No updates are presented when on mobile data.
**Expected result:** Updates should be checked, regardless of network type.

### Screenshots
None as there is nothing to show.

### Device info

**Device:** Google Pixel 4a
**Android version:** 13
**Signal version:** 6.6.3

### Link to debug log
No debug log - updates are just not being checked.

I first noticed this bug when away travelling for a while - I have unlimited mobile data so never connect to a Wi-Fi network.  Signal informed me that my current version was too out of date.  Having to find and connect to a Wi-Fi network, just to auto-update a secure messaging app seem like an oversight.
I've since purchased a mobile hotspot for the sole purpose of connecting to its Wi-Fi to "trick" Signal into auto-updating.

**Comment by nicholas-signal** [comment] 2023-01-05 14:25
Thanks for reporting this bug.

Please submit a debuglog, as it is actually relevant here: we would like to see if the "check for update" job is running at all. It is possible that the check is being performed but the request fails due to issues with your mobile provider.

Thanks!

**Comment by greenerk** [comment] 2023-01-05 15:26
Ah, right enough, I'd not thought of that.
The debug log looks pretty anonymised - I'm assuming it's OK to upload the .zip file here, but the instructions for logging an issue state to "paste a link".
Is there a preferred service to upload the file to, or will I just drop it in here?

**Comment by nicholas-signal** [comment] 2023-01-05 15:49
> Ah, right enough, I'd not thought of that. The debug log looks pretty anonymised - I'm assuming it's OK to upload the .zip file here, but the instructions for logging an issue state to "paste a link". Is there a preferred service to upload the file to, or will I just drop it in here?

You're welcome to paste a .zip here, but the preferred way is to use the "Submit" button in the app which will upload it to our https://debuglogs.org host. And as with everything we do, our debuglogs are completely anonymized.

**Comment by greenerk** [comment] 2023-01-05 15:56
Blimey, that could not have been any simpler!  I wish all apps had a submit option like this.
https://debuglogs.org/android/6.6.3/1c9769f7a6e6936f30e5aed13e672fefc96295d3b88503a9bf120e5d3c4b0951

It's worth noting that my wife has the same issue, and is on a different mobile network. Same phone, OS and version though.

**Comment by nicholas-signal** [comment] 2023-01-05 19:41
> Blimey, that could not have been any simpler! I wish all apps had a submit option like this. https://debuglogs.org/android/6.6.3/1c9769f7a6e6936f30e5aed13e672fefc96295d3b88503a9bf120e5d3c4b0951
> 
> It's worth noting that my wife has the same issue, and is on a different mobile network. Same phone, OS and version though.

Thanks for the log! I see in there that the UpdateApkJob is running every ~6 hours, as expected. I also see that our server was responding that 6.5.6 was the latest and greatest version up until this morning, and I've confirmed with the team that it's possible that we forgot to update our website's APK until today. We're planning to release 6.7 in the near future and I will ensure that it gets uploaded to our upgrade server. Since it sounds like you're not on WiFi very often, let us know if you successfully receive an update notification for 6.7 when it is released in the coming week.

**Comment by greenerk** [comment] 2023-01-06 10:40
Thanks, Nicholas.  I'll keep an eye on the releases and let you know what happens with the app updates either way.

**Comment by greenerk** [comment] 2023-01-15 11:11
Hi, Nicholas.
I can see version 6.7.6 is now up on the APK download page.

My phone is currently still on 6.6.3, and my Wife's on 6.5.6.  Still no notification that there is an update waiting.

Links to the debug logs;
https://debuglogs.org/android/6.6.3/467024fc4ca23fbd537db4ae4a1342f124276b60a81b9c904e231a7ab008180d
https://debuglogs.org/android/6.5.6/88d961df8930bc4c1806cafbc23c5103fee16327c14d55f3e6ec1b5de43a214d

Just to confirm, Signal **is** meant to still check and notify of updates when just on mobile data, right?

**Comment by greenerk** [comment] 2023-01-22 19:47
Hi, @nicholas-signal 

I decided to flip on the Wi-Fi to grab the latest version.  Before I did, though, I grabbed some fresh logs (while still on mobile data).  I then grab logs right after the update was installed when on Wi-Fi.

Hopefully the before-and-after might help shed more light onto the problem.  These are from both mine and my wife's phones.

Mister Mobile Data: https://debuglogs.org/android/6.6.3/00e22c4377c89cee378b3d6bcd3aa3616bf9403ebae8df519a7eb67a3088ba7d
Misses Mobile Data: https://debuglogs.org/android/6.5.6/55d1058b12400ce8443f58f74d0ce0f3108f01a1961afb942718301d4ff70d4f

Mister Wi-Fi: https://debuglogs.org/android/6.8.3/97274061328432ea9ff7a6f8cbf1a82cfa2be46b610b74c34ac51075ed4edb86
Missus Wi-Fi: https://debuglogs.org/android/6.8.3/dd8c836e797903a3f374e407b0aae60af0efab88f38daa9c6709053fb6d1c004


Cheers.

**Comment by nicholas-signal** [comment] 2023-01-23 22:05
hello @greenerk.

I've dug into this further with the team, and I've discovered that [this behavior is intentional](https://github.com/signalapp/Signal-Android/blame/7fafa4d5e6c1e8d0aea78413d59fa6d535b650b0/app/src/main/java/org/thoughtcrime/securesms/jobs/UpdateApkJob.java#L163).

Signal is used across the world, including in nations where mobile data is punitively expensive, so we do our best to minimize the amount of unmetered data that we use.

I will raise the idea to Product of forcing the update over a metered connection.

**Closed by nicholas-signal** 2023-01-23 22:05 UTC

**Comment by greenerk** [comment] 2023-01-23 22:20
Thanks for looking into this for me, @nicholas-signal . And it's actually interesting to see where it's hard-coded to only work over Wi-Fi.

However, I do find the news very sad - surely a toggle in the settings to allow update checks (and downloads) over mobile data would make sense here, to allow the users to decide (defaulted to Wi-Fi only) for themselves.  These toggles are already present in the app for media auto-downloads.

Cheers for taking the time.

**Comment by nicholas-signal** [comment] 2023-01-24 15:42
> Thanks for looking into this for me, @nicholas-signal . And it's actually interesting to see where it's hard-coded to only work over Wi-Fi.
> 
> However, I do find the news very sad - surely a toggle in the settings to allow update checks (and downloads) over mobile data would make sense here, to allow the users to decide (defaulted to Wi-Fi only) for themselves. These toggles are already present in the app for media auto-downloads.
> 
> Cheers for taking the time.

[As of Android 7.0, even though it specifies "WiFi" this line is actually equivalent to allowing on all unmetered networks](https://developer.android.com/reference/android/app/DownloadManager.Request#setAllowedNetworkTypes(int)) (this includes ethernet, for example).

**Comment by greenerk** [comment] 2023-01-25 08:34
How funny.  You'd think they'd update that to reflect the wording.
For the record, I still think having an option to check for, and download, updates via mobile data should be added.  Especially with that already there for media downloads.
Manually checking the apk page and installing that way requires allowing the browser to install apps, which just makes the process more convoluted.
