### ISSUE TITLE
+1 prepended when outside usa 

### ISSUE THREAD

**Issue by jcolson** [signalapp/Signal-Android#9439] opened 2020-03-02 21:06 UTC
- [ ✔] I have searched open and closed issues for duplicates
- [ ✔] I am submitting a bug report for existing functionality that does not work as intended
- [ ✔] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ✔] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I have a USA phone number based account.  I spend a _lot_ of time in Europe.  When I get a local text +1 is prepended to the local phone number when there is no country code.  This means the text doesn't get matched with the address book entry assigned to the contact.

### Steps to reproduce
- have a usa account
- put your vodafone Ireland sim in
- go to Dublin, Ireland
- get a text from a user on Vodafone Ireland

- note that +1 is prepended to the local phonenumber and the contact now isn't matched to your address book entry for that contact
- address book entry should match to the person who texted you

### Screenshots
no need

### Device info

**Device:** OnePlus 7Pro
**Android version:** 10 - jan 1 2020 security patch
**Signal version:** 4.55.8

### Link to debug log
https://debuglogs.org/93d7467a334ba84ee4f5f0506cc932658e50d775636bfcad9937d5a4267105b9

**Comment by mum6ojum6o** [comment] 2020-03-04 04:59
I would volunteer to research on this subject.

**Comment by Genis-Sage** [comment] 2020-03-20 09:20
hey @jcolson 

when i understand it correctly, this is somehow an intented behaviour, also by libphonenumber from google

i guess the simple workaround is, that you save every phone number in the contacts with the country code instead of a leading 0

libphonenumber has to exchange the leading 0 to a country code
and because signal sees you as US user, because you registered with an US number
a leading 0 will be replaced with +1 as country code for USA

signal does not know, that you are now in Ireland and use an Irish sim card

**Comment by mum6ojum6o** [comment] 2020-03-20 17:06
I agree. This seems more like Working as Designed

**Comment by robin-thoni** [comment] 2020-04-23 22:34
I also have this issue:
Signal phone number is US (+1), I have French (+33) and UK (+44) dual SIM cards. When I get a text it sometimes, but not always (not sure how/who/when/where) gets prefixed by +1, but without even removing the first 0: if number is 0612345678, then intl format should be +33612345678, but is instead +10612345678.

> This seems more like Working as Designed

I don't think so. If the sender numbwr doesn't have a country code, the default should be the one from the SIM receiving the text, not the one from Signal's registered number. I'm not sure, however, if that info is available, as not all SIM cards have phone numbers available into them.

**Comment by robin-thoni** [comment] 2020-04-23 22:43
Maybe related to #8838?

**Comment by AlexandreBonneau** [comment] 2021-01-29 06:45
Indeed, this is a duplicate of #8838.
This bug is really annoying

**Comment by AlexandreBonneau** [comment] 2021-01-29 06:48
> hey @jcolson
> 
> when i understand it correctly, this is somehow an intented behaviour, also by libphonenumber from google
> 
> i guess the simple workaround is, that you save every phone number in the contacts with the country code instead of a leading 0
> 
> libphonenumber has to exchange the leading 0 to a country code
> and because signal sees you as US user, because you registered with an US number
> a leading 0 will be replaced with +1 as country code for USA
> 
> signal does not know, that you are now in Ireland and use an Irish sim card

For information, ALL my numbers are stored with the country code (since I do have a use for using both sim card everyday), and the bug still applies.
I'm pretty sure what happens is that the network only send the basic `99 99 99 99` numbers, and then Signal by default check the country code used by the account (mine is `+33`), then add it to that numbers giving the wrong `+33 99 99 99 99`, instead of `+689 99 99 99 99`.
Do note that even if you have the `+689 99 99 99 99` number in your phone book, the bug still happens (but not for every phone numbers, weirdly).

**Comment by AlexandreBonneau** [comment] 2021-03-09 07:24
One workaround could be for Signal to:
- First check when receiving `99 99 99 99` without a country code if a known signal account already exist finishing with those numbers
- If it does not match, check the phone address book for those numbers.
- Lastly, find a way to know in which country the user currently is in, in order to add the country code automatically

**Comment by robin-thoni** [comment] 2021-03-09 13:00
> First check when receiving 99 99 99 99 without a country code if a known signal account already exist finishing with those numbers

If you're receiving a plain old standard SMS/MMS from that person, isn't there more chance this person doesn't have a Signal account?

> check the phone address book for those numbers.

That should probably be the first things to check if no other reliable methods are available (as described below), as it does not involve any remote resources.

> Lastly, find a way to know in which country the user currently is in, in order to add the country code automatically

It is possible to access MCC/MNC for both the SIM card and the current carrier (useful when roaming):
![signal-2021-03-09-134745](https://user-images.githubusercontent.com/9640353/110472853-2d894d00-80de-11eb-833d-884e05cd6f13.jpeg)

From this, you can get the country code. However, I'm not note sure if any or which country code is appended in the following situations (probably carrier and country dependent):
- When roaming, you receive a text from your home country (in my case, a text from France while roaming in Germany)
- When roaming, you receive a text from the local country (in my case, a text from Germany while roaming in Germany)

**Comment by greyson-signal** [comment] 2021-03-09 15:50
Unfortunately, yeah, this isn't a problem that is easily automatically solveable. If you have local contacts with no country code specified, the only logical thing we can do is assume that they have the same country code as your own number. In your case, that will cause non-US numbers without specified country codes to not match. As others have noted, the solution is to specify the country code in your system contacts.

If for whatever reason the inbound SMS does not have a valid e164 address (i.e. it's dropping the country code), then the same problem applies.

Changing how we link numbers based on what secondary SIM you're popping in and out causes other sets of issues, namely that a contact links up today because you had your Ireland SIM in, but then it doesn't match tomorrow because you took it out.

**Closed by greyson-signal** 2021-03-09 15:50 UTC
