### ISSUE TITLE
Roaming through non-data mobile service regions stops incoming messages

### ISSUE THREAD

**Issue by tomjennings** [signalapp/Signal-Android#9947] opened 2020-08-22 02:01 UTC
This is a sadly vague report, because it is inherently difficult to repeat, but the result is very frustrating.

Phone: Pixel 3a, Android 10, 5 aug 2020
Service: Google Fi

The problem below happens about every other time I travel to rural areas of the U.S. So far I have been able to unregister and reregister, but not this time.

I travel extensively through very rural parts of the U.S. south-west, Navajo Nation, etc where vast swaths have no service at all, and much of it is mixed voice-only, voice+SMS, non-data, etc. Roaming is unreliable and spotty. I eventually return to Los Angeles (full service).

About three days into a trip all incoming SMS and incoming Signal messages just stopped (discovered only when others told me out of band). I am able to send.

My goal is to get to baseline -- no Signal, receive SMS via google's Messages app, then start over.

On return home in Signal app, in settings I turned off messages and calls ("unregister"), within seconds I got a flood of SMS/MMS, picked up by the default Android Messages app. Dozens. However I was/am still unable to receive new texts.

I then uninstalled Signal, and went to the Signal.org URL to unregister: https://signal.org/signal/unregister/

Unregister fails.

When I enter phone number and country and click CALL or SMS the error "Failed to connect to the server" appears on the screen. See attached. All combinations of prefix, no prefix (+1, 01, etc), page refresh, no change. WHen I click the buttons grey out, floating circle-slash, then a second or two the error message.

Another Signal.org page re: unregistering talks about "shortcode blacklist", to call my provider to clear it. Google Fi support claims no knowledge nor access. No reason to believe this is pointful other than the signal help page mentions it.

Phone powered off, etc of course. Backed out Messages updates, reinstalled. 

I'm stumped. How can I force an unregister?
<img width="1361" alt="Screen Shot 2020-08-21 at 6 41 12 PM" src="https://user-images.githubusercontent.com/10536133/90946318-9201ea80-e3e0-11ea-93de-ff1a8e4da443.png">

**Comment by pmiossec** [comment] 2021-01-07 12:36
FYI, roaming problem seems a duplicate of #9864

**Closed** 2022-02-03 13:26 UTC
Labels: wontfix
