### ISSUE TITLE
Message delivery delay

### ISSUE THREAD

**Issue by IanSpam** [signalapp/Signal-Android#9355] opened 2020-01-21 02:48 UTC
This is a new problem on my Signal. There used to be no delay in receiving notification on my phone of new Signal message arriving. Now there is, and often no notification until I open the app. Then it goes off as each notification alert sounds sequentially. This is new behaviour so may be bug in newer version. To my knowledge nothing else has changed.
Family members used to mention this to me on their devices but I thought it was probably a notification setting. I have checked every setting I can think of. All seem correct, still no timely notifications.
Phone: HTC Desire 530
Android: 6.0.1
Signal: 4.53.7

- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by d43m0nhLInt3r** [comment] 2020-01-21 14:46
same here on 2 different devices.

**Comment by greyson-signal** [comment] 2020-01-21 17:53
Closing as dupe of #8692

**Closed by greyson-signal** 2020-01-21 17:53 UTC

**Comment by IanSpam** [comment] 2020-01-22 01:43
Quick to close slow to fix.............While I used to appreciate Signal a lot. You devs were awesome. This one thing is a real problem.
