### ISSUE TITLE
safety bug, wrong logic or setting problem !!!!

### ISSUE THREAD

**Issue by liufeijin** [signalapp/Signal-Android#9955] opened 2020-08-24 11:34 UTC
I have set all message will disappear in signal on my iphone6s(ios14 beta5)
,but when i install the signal soft wear on laptop , all disappear message are present again!
All message are not disappeared at all, they just disappeared on my iphone!, All message are stored at somewhere.
Who is keeping all message always.

It is danger, you think your all message already gone but it still at here.  
Somebody(or GOV) just sing in signal on other platform (sometime you must give them password), will get all evidence.

I don't find any setting for this. so is it a safety bug, wrong logic or setting problem?

???

**Comment by strugee** [comment] 2020-08-25 07:08
This is the incorrect issue tracker for this. I also suspect this is not a bug, but merely an (understandable) misunderstanding on your part as to how disappearing messages work. I would suggest posting to the forums: https://community.signalusers.org/

**Comment by bme13** [comment] 2020-08-25 07:26
Hi. Strugee is correct about the location of the issue tracker. Please note this is the issue tracker for the Android client. Seems you have a IOS/desktop issue. Now I don't have any experience with the desktop or IOS but I think your expectation about the disappearing messages is correct. See e.g. https://community.signalusers.org/t/disappearing-messages-synchronization-off/4023. This seems to be either a IOS or desktop issue so it should be reported there. Just did a quick search and this seems related to https://github.com/signalapp/Signal-Desktop/issues/3941

**Comment by alex-signal** [comment] 2020-08-25 12:12
Closing this as it is not an android client issue.

**Closed by alex-signal** 2020-08-25 12:12 UTC
