### ISSUE TITLE
Outgoing messages get stuck on pending after bot captcha did not pop out.

### ISSUE THREAD

**Issue by Sangresignal** [signalapp/Signal-Android#12307] opened 2022-06-23 16:55 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

I recently installed a new phone with a new number and sync all my old contacts. Whenever i tried sending a new message to a contract i was required to confirm that i am not a bot (captcha). After going through the procedure and confirming the checklist and captcha, the message would be sent and all would work great. But i had to do it with every single contact.
So now comes the bug...
I just tried to write a message to a new contact, but the verification pop up did not come out and the message is stuck on pending. Also when i try to send a message to any new contact the messages are stuck on pending. Old contacts work fine and messaging is flawless. 
I tried deleting the original (first message that was stuck on pending) but it def doesn't help and any attempt to send a message to a new contact is impossible.
I don't use VPN, i cleared cache and did all the normal instructions that u suggest on the troubleshooting on the signal webpage.  I even tried uninstalling the signal app and it did not help. Nothing works. I tried wifi, gsm etc. internet is working just fine other apps are doing great.
Any ideas if i can reset the verification process or do it manually?  Why is it asking for verification in the first place it has never asked it before.

### Device info

**Device:** Google Pixel 5A
**Android version:** 12
**Signal version:** 5.40.4.1
****Operating system- grapheneos

### Link to debug log

https://debuglogs.org/android/5.40.4/d332e3505e060537a5ae1f8f7820d1e47b602cfb9583432804f1365df985096a

**Comment by greyson-signal** [comment] 2022-06-24 12:46
Closing as a duplicate of #12289

**Closed by greyson-signal** 2022-06-24 12:46 UTC
