### ISSUE TITLE
Automatic search for new contacts

### ISSUE THREAD

**Issue by Elep331** [signalapp/Signal-Android#12749] opened 2023-01-25 11:40 UTC
Dear Support,

In several last versions does not flawlessly work automatically search for new contact (phone numbers with Signal registration).

When someone from my phone contacts signs up for the Signal app I do not know about it often for a very long time. This behaviour confirms a lot of my colleagues and friends.

I can not say it is the case for all my new contacts. Often it does not work but from time to time it works.

Manual update through New message -> Settings -> Refresh works perfectly.

I tried to reinstall the app but without success.

Best Regards
Thanks

**Comment by greyson-signal** [comment] 2023-01-25 15:02
Hi there, unlike other messaging apps, Signal does not know who your contacts are. That means that if one of your friends signs up, we can't make it so that your app instantly knows about it. Instead, we periodically check if any of your contacts are registered every couple of days, or whenever you add contacts to your system contacts (but that can also be delayed based on the device).

I don't consider this a bug, since it's technically working as intended, so I'm going to close this, but I am going to think about some ways we could improve this in the future.

**Closed by greyson-signal** 2023-01-25 15:02 UTC

**Comment by Elep331** [comment] 2023-01-25 17:58
I understand the principle that Signal service does not have a database with my contacts and this mechanism is controlled by the Signal app on the phone.

You described two principles:
1) New contact is saved into my phone.
2) Periodically checking if any of my contacts are registered every couple of days.

Ad1) This works predictably
Ad2) Check every "couple of days" is very confusing for users. Users usually think that the service is not working. When my friend signs up for Signal, and tells me about it, and I still do not see it, we typically both say that Signal probably is not working as it should. This is a situation I and my colleagues have experienced several times.

Maybe shortening the period significantly would help.

For example, competitor Telegram will notify others of the registration of a known number almost immediately.

**Comment by Elep331** [comment] 2023-01-25 17:59
> Hi there, unlike other messaging apps, Signal does not know who your contacts are. That means that if one of your friends signs up, we can't make it so that your app instantly knows about it. Instead, we periodically check if any of your contacts are registered every couple of days, or whenever you add contacts to your system contacts (but that can also be delayed based on the device).
> 
> I don't consider this a bug, since it's technically working as intended, so I'm going to close this, but I am going to think about some ways we could improve this in the future.

I understand the principle that Signal service does not have a database with my contacts and this mechanism is controlled by the Signal app on the phone.

You described two principles:
1) New contact is saved into my phone.
2) Periodically checking if any of my contacts are registered every couple of days.

Ad1) This works predictably
Ad2) Check every "couple of days" is very confusing for users. Users usually think that the service is not working. When my friend signs up for Signal, tells me about it, and I still do not see it, we typically both say that Signal probably is not working as it should. This is a situation I and my colleagues have experienced several times.

Maybe shortening the period significantly would help.

For example, competitor Telegram will notify others of the registration of a known number almost immediately.

**Comment by greyson-signal** [comment] 2023-01-25 22:25
> For example, competitor Telegram will notify others of the registration of a known number almost immediately.

This is because Telegram stores all of it's users' phone contacts in plaintext on their server. When one of your contacts is discovered to be registered, it notifies you immediately. Signal can't do that because we don't store your contacts.

I have some ideas that can help, but there will always be some form of compromise.
