### ISSUE TITLE
Crash on open

### ISSUE THREAD

**Issue by jntx** [signalapp/Signal-Android#10035] opened 2020-09-23 13:04 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal crashes on open

### Steps to reproduce
- Tap on signal icon

**Actual result:** White empty screen which disappear immediatly
**Expected result:** Opening the app

### Device info
**Device:** Motorola G7 Power
**Android version:** 9.0.0
**Signal version:** 4.71.5

### Link to debug log
adb logcat follows:
```
    --------- beginning of crash
2020-09-22 15:19:54.795 16524-16706/? E/AndroidRuntime: FATAL EXCEPTION: signal-serial-0
    Process: org.thoughtcrime.securesms, PID: 16524
    org.thoughtcrime.securesms.database.RecipientDatabase$MissingRecipientException: Failed to find recipient with ID: null
        at org.thoughtcrime.securesms.recipients.LiveRecipientCache.getSelf(LiveRecipientCache.java:132)
        at org.thoughtcrime.securesms.recipients.Recipient.self(Recipient.java:278)
        at org.thoughtcrime.securesms.megaphone.Megaphones.shouldShowMessageRequestsMegaphone(Megaphones.java:217)
        at org.thoughtcrime.securesms.megaphone.Megaphones.access$100(Megaphones.java:46)
        at org.thoughtcrime.securesms.megaphone.Megaphones$1.<init>(Megaphones.java:87)
        at org.thoughtcrime.securesms.megaphone.Megaphones.buildDisplayOrder(Megaphones.java:83)
        at org.thoughtcrime.securesms.megaphone.Megaphones.getNextMegaphone(Megaphones.java:58)
        at org.thoughtcrime.securesms.megaphone.MegaphoneRepository.lambda$getNextMegaphone$2$MegaphoneRepository(MegaphoneRepository.java:71)
        at org.thoughtcrime.securesms.megaphone.-$$Lambda$MegaphoneRepository$q9Ph2NWga4K9VBzFhswMpm7EJ5M.run(Unknown Source:4)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
2020-09-22 15:19:54.793 16524-16706/? V/Cursor: Filling cursor window with start position:0 required position:0
2020-09-22 15:19:54.795 16524-16706/? E/SignalUncaughtExceptionHandler: org.thoughtcrime.securesms.database.RecipientDatabase$MissingRecipientException: Failed to find recipient with ID: null
        at org.thoughtcrime.securesms.recipients.LiveRecipientCache.getSelf(LiveRecipientCache.java:132)
        at org.thoughtcrime.securesms.recipients.Recipient.self(Recipient.java:278)
        at org.thoughtcrime.securesms.megaphone.Megaphones.shouldShowMessageRequestsMegaphone(Megaphones.java:217)
        at org.thoughtcrime.securesms.megaphone.Megaphones.access$100(Megaphones.java:46)
        at org.thoughtcrime.securesms.megaphone.Megaphones$1.<init>(Megaphones.java:87)
        at org.thoughtcrime.securesms.megaphone.Megaphones.buildDisplayOrder(Megaphones.java:83)
        at org.thoughtcrime.securesms.megaphone.Megaphones.getNextMegaphone(Megaphones.java:58)
        at org.thoughtcrime.securesms.megaphone.MegaphoneRepository.lambda$getNextMegaphone$2$MegaphoneRepository(MegaphoneRepository.java:71)
        at org.thoughtcrime.securesms.megaphone.-$$Lambda$MegaphoneRepository$q9Ph2NWga4K9VBzFhswMpm7EJ5M.run(Unknown Source:4)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
2020-09-22 15:19:54.797 16524-16561/? V/Cursor: Filling cursor window with start position:0 required position:0
2020-09-22 15:19:54.798 16524-16561/? V/Cursor: Filling cursor window with start position:0 required position:0
2020-09-22 15:19:54.799 16524-16706/? I/JobManager: Successfully flushed.
2020-09-22 15:19:54.799 16524-16561/? E/SignalUncaughtExceptionHandler: org.thoughtcrime.securesms.database.RecipientDatabase$MissingRecipientException: Failed to find recipient with ID: null
        at org.thoughtcrime.securesms.recipients.LiveRecipientCache.getSelf(LiveRecipientCache.java:132)
        at org.thoughtcrime.securesms.recipients.Recipient.self(Recipient.java:278)
        at org.thoughtcrime.securesms.conversationlist.-$$Lambda$4R-k00CnaOfHk3PXlQVrsbtQQhM.run(Unknown Source:0)
        at org.thoughtcrime.securesms.util.concurrent.SimpleTask.lambda$run$1(SimpleTask.java:26)
        at org.thoughtcrime.securesms.util.concurrent.-$$Lambda$SimpleTask$W3hwqgjBrQ_4y_Y0MHEF08-is-w.run(Unknown Source:6)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
2020-09-22 15:19:54.802 16524-16561/? I/JobManager: Successfully flushed.
2020-09-22 15:19:54.802 16524-16561/? I/Process: Sending signal. PID: 16524 SIG: 9
2020-09-22 15:19:54.804 2037-9902/? W/ActivityManager:   Force finishing activity org.thoughtcrime.securesms/.RoutingActivity
2020-09-22 15:19:54.806 2037-9902/? D/ActivityManager: found next focusableStack ActivityStack{e6d7d4d stackId=0 type=home mode=fullscreen visible=true translucent=true, 1 tasks} with top ActivityRecord{10b4b50 u0 com.motorola.launcher3/com.android.launcher3.CustomizationPanelLauncher t2} as current stack ActivityStack{e787481 stackId=121 type=standard mode=fullscreen visible=true translucent=true, 1 tasks}
2020-09-22 15:19:54.811 2037-2100/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
2020-09-22 15:19:54.811 2037-2100/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
2020-09-22 15:19:54.877 2037-9902/? I/ActivityManager: Process org.thoughtcrime.securesms (pid 16524) has died: vis  +99TOP 
2020-09-22 15:19:54.877 2037-2103/? W/libprocessgroup: kill(-16524, 9) failed: No such process
2020-09-22 15:19:54.877 1068-1068/? I/Zygote: Process 16524 exited due to signal (9)
2020-09-22 15:19:54.881 1216-2440/? W/SurfaceFlinger: Attempting to set client state on removed layer: Splash Screen org.thoughtcrime.securesms#0
2020-09-22 15:19:54.881 1216-2440/? W/SurfaceFlinger: Attempting to destroy on removed layer: Splash Screen org.thoughtcrime.securesms#0
2020-09-22 15:19:54.883 2037-2298/? W/WindowManager: Failed looking up window callers=com.android.server.wm.WindowManagerService.windowForClientLocked:5626 com.android.server.wm.WindowManagerService.removeWindow:1684 com.android.server.wm.Session.remove:226 
2020-09-22 15:19:54.889 2037-2103/? W/libprocessgroup: kill(-16524, 9) failed: No such process
2020-09-22 15:19:54.889 2037-2103/? I/libprocessgroup: Successfully killed process cgroup uid 10175 pid 16524 in 12ms
```

**Comment by jntx** [comment] 2020-09-24 15:06
Forget to say that it is not a new install, it's an 14 month old install with many messages and media. The crash appeared without any reason. Tryed to clean-up Signal cache. I didn't reinstalled the app (I don't know if I will lost the archive).

**Comment by TheLastGimbus** [comment] 2020-11-13 12:24
Seems to be a duplicate of #9332

**Closed** 2022-02-03 16:52 UTC
Labels: wontfix
