### ISSUE TITLE
Permanent fallback to SMS when a contact uninstalls signal

### ISSUE THREAD

**Issue by praxiq** [signalapp/Signal-Android#8110] opened 2018-08-15 17:02 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I have a contact that previously used signal, but has uninstalled it. Every time I send them a message, Signal defaults to trying to send it as a Signal message, then fails and asks me if I want to fallback to SMS.

### Steps to reproduce
- Select a conversation with a contact who has recently uninstalled Signal.
- Send a Signal message. 
- Get "the recipient is no longer a Signal user" warning.
- Choose to send unsecured SMS.
- Later, send another message to the same contact.

**Actual result:** "Send" button continues to default to "Signal" instead of "SMS" every time.

**Expected result:** After the first time that Signal notices the user has uninstalled, and warns me of this, it should default to SMS for that contact - just like with any other contact who does not have Signal.

### Device info

**Device:** OnePlus 3T
**Android version:** 8.0.0 (OxygenOS 5.0.4)
**Signal version:** 4.24.8

**Comment by moxie0** [comment] 2018-08-15 21:34
I think this is somewhat different, since it sounds like we "know" that the destination user has uninstalled. A debug log would be very helpful.

**Comment by GuardianMajor** [comment] 2018-08-15 22:00
@moxie0 Quick question, when we say "uninstall" does that mean off their phone or actually "deleted/unregistered" signal? They are two different things. I know a few who are not as tech savvy and never unregistered or deleted their signal account but they got a new phone and never installed it again and since it was never officially uninstalled either, the messages sent to them always go to Signal and they never get the regular text, I have at least 3 contacts in this boat, so how do we deal with that?

Specifically a condition where the person didn't unregister, delete, or uninstall the app but no longer has it or able to check it, but on my end I can't send them a regular text message anymore since Signal is my default SMS. Can we get a way to "exclude" sending a message to the person on Signal on our end please? Where at least on our end we can designate them as "regular" and "not signal" so the message gets routed accordingly? In the least to alleviate situations like this and make sure they are still getting your text?

PS. Apologies for posting here I didn't intend to "hijack" the discussion, just that I was going to post something very similar, as described above and felt this might reduce the clutter. If I am wrong, I can repost as a separate issue. TIA.

**Comment by igor2x** [comment] 2018-08-16 14:00
@GuardianMajor, github is for bugs only. Any discussion, feature request, ideas etc should be discussed on [official Signal forum.](https://community.signalusers.org/) Ideas you have written have already been discussed on forum in [Simplify change of secure/insecure communication](https://community.signalusers.org/t/idea-simplify-change-of-secure-insecure-communication/1781) and many other topics. Please join the forum and discuss with us.

**Comment by GuardianMajor** [comment] 2018-08-16 19:44
I understand that but consider the context. I do thank you for linking to the topic on the forum though but I have no interest in creating yet another account or linking yet another place to existing accounts. If it is being discussed, then great, and hopefully it will be implemented. I did read something that in the short term might prove useful but I'll have to test to see if it actually exists already and work or not, in which case it might suffice for my short term needs. So at the very least, thanks for that.

**Comment by mryellow** [comment] 2018-10-26 08:13
I'm sorry but the responses I read to the numerous threads on this issue by the Signal core team are unacceptable.

If a Alice is no longer contactable via Signal and they have informed Bob of such, then Bob should have the option to no longer be ATTEMPTING to send encrypted messages to Alice. Bob should NOT have to hold down send on each message to this contact for the rest of their lifetime.

This is a blocker level UX failure and the only way past it is to uninstall Signal. Instead of spending time locking threads an arguing with people demanding they provide solutions to X/Y problems like Google not sending uninstall events, it should be fixed with priority. 

Instead we are stuck in a UX hole thanks to this UI **BUG**. 

It really would be a pity to uninstall this software, I only want to be able to message my family member without holding down send every time. That is not any kind of solution.

**Comment by mryellow** [comment] 2018-10-26 08:49
> For example, the iOS version does not offer any SMS and alleviates all of these concerns.

Well then it seems that not setting Signal as a default SMS app on Android is the best way forward. 

Seems there is some confusion around the importance of this UX bug in the devteam.

Perhaps you guys should just become an encrypted chat app, drop the clunky "hold down the button" UX which is very unintuitive and remove any mention of defaulting as an SMS app. 

Either that or simply allow people to default to either SMS or encryption on a per-user basis, that's not hard either.

**Comment by Bujiraso** [comment] 2018-11-25 17:05
@mryellow is right here. The current UI is defective, the UX is absolute non-sense. As someone who works full-time as a software developer it took me literally ages to find this option on my own. How much harder will it be for the masses that Signal tries to reach?

There needs to be a per-contact setting that is stored, as I am also encouraging people not to use Signal now since I cannot trust it to reliably connect two people -- which, we should be careful to recall, is the entire purpose of the whole app.

**Comment by mryellow** [comment] 2018-11-25 21:50
@Bujiraso https://riot.im/ seems like a decent alternative which takes a *"lets make this thing actually work"* approach to UX rather than *"lets keep everything ultra tight and hope that in a few decades people have all moved over and gone dark, hopefully by then our database isn't all orphan hashes of past uninstalls"*

Let me know if you find anything else with a more usable design.

*I believe there is no progress to be made here on Signal as the issue is ideological and relates to a purity rather than a usability.*

Currently my state in the Signal system is that any user will be sending messages to a black hole assuming I get them. I, like everyone else in the world really can't bothered reengaging with this system only to remove myself. I've already removed myself on my end and that's find by me. The orphan record that exists for my number can keep on existing, I'll simply assume that Signal will never gain any ground and that that hash being wrong won't ever cause me to miss a message.

**Comment by moxie0** [comment] 2018-11-26 22:10
I'm going to close this, since it looks like we never got a debug log for the original issue (we "know" a user has uninstalled, but keep trying to send them Signal messages).

For everyone who has contributed thoughts regarding a separate issue (we don't know a user has uninstalled) in this thread, please remember that we don't use GH issues for discussion or feature requests. If folks have good ideas about how to handle that case, I'd love to hear more, but please post in the discussion forum instead. Thanks!

**Closed by moxie0** 2018-11-26 22:10 UTC
