### ISSUE TITLE
Signal is not updating individual profile avatars once they got lost

### ISSUE THREAD

**Issue by motatuc** [signalapp/Signal-Android#7544] opened 2018-03-20 12:22 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Some of my contacts use profile avatars. After I did a backup and restored that, I lost these avatars. With the latest fix ([https://github.com/signalapp/Signal-Android/commit/d6610f0dd073aa406eb5f03d44a9574995ab3f19](https://github.com/signalapp/Signal-Android/commit/d6610f0dd073aa406eb5f03d44a9574995ab3f19)) they are replaced by standard avatars. But how to get the individual avatars back? Signal does not seem to update them.

### Steps to reproduce
- Have contacts with individual profile avatars
- Restore a backup where the avatars have gone missing
-> No way to get the avatars back

**Actual result:** The avatars are lost
**Expected result:** Signal is taking care that avatars are in sync.

**Comment by johanw666** [comment] 2018-03-20 13:10
Duplicate of https://github.com/signalapp/Signal-Android/issues/7540, fixed in https://github.com/signalapp/Signal-Android/commit/d6610f0dd073aa406eb5f03d44a9574995ab3f19

**Comment by motatuc** [comment] 2018-03-20 13:47
@johanw666 I appreciate your participation but please read my posts carefully before you reply to them. It's not a duplicate and it's not fixed.

**Comment by johanw666** [comment] 2018-03-20 18:54
Sorry, I didn't read your post carefull enough.

**Comment by AlfonsoMuskedunder** [comment] 2018-03-23 18:36
I have noticed that when I enter the conversation list, the circle-cum-initial flickers for a split second for all my contacts who have actually set a profile picture. See for example [this clip](https://imgur.com/a/3TlTj).

**Comment by moxie0** [comment] 2018-04-03 09:58
This is a condition specific to this one sequence of events in a beta release. The problem is that the profiles aren't "lost," only some part of them. So the app doesn't think there's anything to re-download. You can manually fix it up by removing the profile data from the recipent_preferences table.

**Closed by moxie0** 2018-04-03 09:58 UTC
Labels: bug
