### ISSUE TITLE
playback of audio attachments behaves like active phone call

### ISSUE THREAD

**Issue by thbsp** [signalapp/Signal-Android#7419] opened 2018-02-16 04:19 UTC
### Problematic functionality
When playing an audio attachment within Signal, if the proximity sensor is triggered then the screen shuts off and audio is played from the earpiece.
If the screen is turned off during playback, playback stops.
If this is intended functionality, I don't understand why this would be desired. I know of no other applications that behave in this way, save for with active phone calls.

This is related to this issue, but goes further:
https://github.com/signalapp/Signal-Android/issues/6993

Example scenario 1:
- A user starts playback of an audio attachment.
- Said user continues to read messages in that conversation while the audio plays.
- While scrolling, one of their fingers (or any other random object) happens to briefly move near the proximity sensor.
- The screen turns off and then immediately back on, and playback has stopped.
- For a user who isn't expecting this behaviour or doesn't know enough about proximity sensors to predict how they will function, they try to play the audio again, only to have the above scenario play out again. This repeats 3-4 times, after which they swear loudly, give up in frustration, and start harassing me for encouraging them to use Signal in the first place instead of a "real" app that "works for normal people".

Example scenario 2:
- My phone's speaker is on the back of the device.
- The audio attachment is long, and I don't want to be holding my phone or have the screen on (to conserve battery) that whole time.
- I want to turn off the screen, put my phone down on a table (screen facing down, speaker facing up) and do something else while I listen to the message. This is currently impossible unless I download the audio file and play it using a different app.
- Even if I leave the phone facing upward, the screen will automatically shut off after 30 seconds, stopping the playback.

### Device info
Many devices (all?), but my particular device information is:
**Device:** Samsung Galaxy S4 (SHV-E330S)
**Android version:** 5.0.1
**Signal version:** 4.15.5

**Comment by FeuRenard** [comment] 2018-02-16 08:39
> If the screen is turned off during playback, playback stops.

This issue (your example 2) is a duplicate of #4424. I agree that the desired behaviour would be that the audio file keeps playing.

What's your expected behaviour for example 1? It's intentional that the audio playback is switched to the earpiece when the phone is placed near to your ear which should be detected by the proximity sensor. This allows listening to voice notes in public without revealing the message content to others or disturbing them with the playback. Pausing the playback when the phone is moved away from your ear is also intentional behaviour so that you can safely put down your phone without fearing a loud noise from your phone (the continuing playback).

**Closed** 2018-02-17 04:57 UTC
