### ISSUE TITLE
Unable to scan QR Code

### ISSUE THREAD

**Issue by egrath** [signalapp/Signal-Android#11414] opened 2021-06-28 17:57 UTC
### Bug description
Unable to scan the QR code provided in the Desktop App. The QR code is clearly visibly inside the Signal App by the camera but isn't recognized. Playing around with the distance between the Monitor and the Phone seems to resolve the issue in some cases (Had success with it on one Desktop App, a other one still refuses to Link)

### Steps to reproduce
- Hard to reproduce as it does not occur with all devices. But there are some users with this issue as is reported in the corresponding reddit thread (https://www.reddit.com/r/signal/comments/o9hqlb/qr_code_not_recognized_when_linking/)

**Device:** Samsung Galaxy Tab Active3
**Android version:** 10
**Signal version:** 5.14.5

**Comment by Sgn-32** [comment] 2021-06-29 16:17
Please post a debug log directly after scanning the QR code.

**Comment by egrath** [comment] 2021-06-29 16:47
You're welcome:
https://debuglogs.org/acb780a851e705b3c11f983b241f2489280d618ca99d0811fede7acac48951f7

I'm seeing a lot of 
```
[5.14.5] [9469 ] 2021-06-28 19:48:46.719 GMT+02:00 W ScanningThread: com.google.zxing.FormatException
[5.14.5] [9469 ] 2021-06-28 19:48:46.796 GMT+02:00 W ScanningThread: null
```
As mentioned in https://github.com/signalapp/Signal-Android/issues/10756 i also scanned to provided QR code with another application and got a good result. Unsure if i can/should post the result here.

**Comment by Sgn-32** [comment] 2021-06-29 16:59
You can check the result with `tsdevice:/?uuid=xxxxxxxxxxxxxxxxxxxxxxxxx&pub_key=xxxxxxxxxxxxxxxxxxxxxxxxx` (see the linked issue)
Also try the workaround with taking a screenshot of the QR code and printing it very large.

**Comment by egrath** [comment] 2021-07-01 18:09
A interesting find maybe: Scanning the provided QR Code with another application (which gets me the mentioned tsdevice:/ string) and regenerating exactly this string with another QR Code generator online leads to immediate acceptance by the Android Signal App when scanned directly on the display. 

Used https://www.the-qrcode-generator.com/ as the generator. The generated QR code also looks different to the one in the Signal Desktop App but contains the same decoded data.

**Comment by Sgn-32** [comment] 2021-07-06 20:10
I'm not sure whether this can also be an issue of Signal Desktop when creating a faulty QR code?

**Comment by bristow** [comment] 2021-08-23 07:39
I had the same problem. 

I had to re-link my PC (I don't know why it lost the link), I couldn't figure out how to scan... Then I went to the debug log, found the same messages and when I came back, I scanned in landscape mode, and oh magic, the scan could be done \o/

So try turning the phone...

**Comment by egrath** [comment] 2022-01-26 06:54
Yes, Problem still persists to this day.

**Comment by rubikscraft** [comment] 2022-01-26 18:51
had the same problem, turning on light mode on signal desktop solved it somehow

**Comment by Vaulbelz** [comment] 2022-02-05 13:19
I had the same Problem.
Steps to reproduce:
- install signal desktop and watch the phone not scanning the QR code. Nothing. no qr code scanner would scan the desktop app
- every other app works just fine. WA, Discord, online banking login... you name it
- cuss loudly

Measures taken:
- Have the desktop client on a FreeSync monitor -> nope
- IPS panel monitor -> nope
- MVA panel -> nope
- cuss even louder
- re-install the android app -> nope

Solution:
Read this guys issue https://github.com/signalapp/Signal-Android/issues/10756
screenshot the QR code (win + shift + s)
scan the QR code -> nope
`**print the QR code as PDF and scan the PDF**`
\o/ yeay!

by no I don't know if the android app is at fault becaus of the way it connects to the cam API
or the desktop app is generating slightly broken QR codes that get fixed by printing

Desktop App:
here's the logs from the desktop app. Nothing to see here.
https://debuglogs.org/7e79c4cb9332f2810e3ba99838e7974d9273dc5293abe3afae0cd2ee9afa6e9d.gz

I had it with 5.29 / 5.29.2 / 5.30

Phone:
OnePlus 6 with stock ROM
Signal app from the PlayStore

**Comment by gammison** [comment] 2022-02-16 22:21
> had the same problem, turning on light mode on signal desktop solved it somehow

This also happened to me. The dark theme of the desktop app somehow confused the mobile app's QR code scanner. I had to turn the desktop app to light mode before the mobile app would scan correctly. This is probably an issue with the QR code scanning library. A temporary fix would probably just be to disable the dark theme/switch it when opening the QR page, or making the white frame around the code much larger.

**Comment by greyson-signal** [comment] 2022-02-17 15:35
Hi there, we've updated our QR scanning library in 5.32 which (at least in my experience on a Pixel 5) fixed the issue of not being able to scan a dark themed QR code on desktop. I believe Desktop is also looking into changing the background around the QR code. If you're having problems in 5.32+, please let us know. Thanks!

**Closed by greyson-signal** 2022-02-17 15:35 UTC

**Comment by kszwaba** [comment] 2023-03-16 22:20
Still not work for me. App for Android v. 6.13.7, Linux desktop 6.10.1
Phone Samsung Galaxy S III GT-i930, Lineage OS 18.1

**Comment by cody-signal** [comment] 2023-03-16 23:55
@kszwaba can you share a debuglog?

**Comment by cody-signal** [comment] 2023-03-17 14:15
Thanks. It looks like everything spins up properly but it never "sees" a QR code to process. Unfortunately not much we can do here :( I can provide you with a test app to try and see if that gets us any more info but it's likely a combination of our use of camerax and a much older phone with the S3.
