### ISSUE TITLE
Signal crashes while loading from backup

### ISSUE THREAD

**Issue by derptables** [signalapp/Signal-Android#7987] opened 2018-07-14 06:37 UTC
- [x ] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Backup was created on LG G5 running android 7.0 with signal 4.23.4
Backup was transferred to Moto Z2 Force via mtp file transfer.
This was attempted with multiple backups.

partway through loading backup, exactly at the 10001 message mark, signal crashes.

### Steps to reproduce
open signal
choose to restore from backup
put in backup password
wait for loaded message count to hit something like 10k

**Actual result:** 
signal exits immediately upon hittin 10001messages
"Signal has stopped" popup window appears 

**Expected result:** 
I expect signal to finish loading my messages and populate the normal startup gui with my messaging history

### Device info

Motorola Z2 Force AT&T version
**Android version:** 7.1.1
**Signal version:** 4.23.4

Previous device: LG G5, Android 7.0.0, Signal 4.23.4

### Link to debug log
ADB Output:

```
07-13 23:25:48.910  2209  2229 I art     : Background sticky concurrent mark sweep GC freed 204462(7MB) AllocSpace objects, 0(0B) LOS objects, 37% free, 12MB/19MB, paused 6.505ms total 27.185ms
07-13 23:25:49.293  1678  2334 W qti_sensors_hal: processReportInd: lux: 16, ch0: 51, ch1: 327, pData: 17, pOffset: 14
07-13 23:25:52.004  2209  2335 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #4
07-13 23:25:52.004  2209  2335 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 2209
07-13 23:25:52.004  2209  2335 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
07-13 23:25:52.004  2209  2335 E AndroidRuntime:        at android.os.AsyncTask$3.done(AsyncTask.java:325)
07-13 23:25:52.004  2209  2335 E AndroidRuntime:        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
07-13 23:25:52.004  2209  2335 E AndroidRuntime:        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
07-13 23:25:52.004  2209  2335 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
07-13 23:25:52.004  2209  2335 E AndroidRuntime:        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
07-13 23:25:52.004  2209  2335 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
07-13 23:25:52.004  2209  2335 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
07-13 23:25:52.004  2209  2335 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:761)
07-13 23:25:52.004  2209  2335 E AndroidRuntime: Caused by: java.lang.NegativeArraySizeException: -190479444
07-13 23:25:52.004  2209  2335 E AndroidRuntime:        at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readFrame(FullBackupImporter.java:303)
07-13 23:25:52.004  2209  2335 E AndroidRuntime:        at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readFrame(FullBackupImporter.java:245)
07-13 23:25:52.004  2209  2335 E AndroidRuntime:        at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:79)
07-13 23:25:52.004  2209  2335 E AndroidRuntime:        at org.thoughtcrime.securesms.RegistrationActivity$2.doInBackground(RegistrationActivity.java:376)
07-13 23:25:52.004  2209  2335 E AndroidRuntime:        at org.thoughtcrime.securesms.RegistrationActivity$2.doInBackground(RegistrationActivity.java:368)
07-13 23:25:52.004  2209  2335 E AndroidRuntime:        at android.os.AsyncTask$2.call(AsyncTask.java:305)
07-13 23:25:52.004  2209  2335 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-13 23:25:52.004  2209  2335 E AndroidRuntime:        ... 4 more
07-13 23:25:52.013  1678  2729 W ActivityManager:   Force finishing activity org.thoughtcrime.securesms/.RegistrationActivity
07-13 23:25:52.025  2671  6547 D ProcSpeedReader: Failed to read freq stats from null
07-13 23:25:52.045   933   933 I SFPerfTracer:      triggers: (rate: 172:13838) (compose: 0:0) (post: 0:44) (render: 0:80) (249:392589 frames) (250:434063)
07-13 23:25:52.046   933   933 D SFPerfTracer:        layers: (3:7) (StatusBar (0x7a12b84000): 3:102560) (com.android.systemui.ImageWallpaper (0x7a12eb1c00): 3:81583)* (DimLayerController/Stack=0 (0x7a0d904000): 1:1952)* (Sprite (0x7a0d909400): 0:302)* (animation background stackId=1 (0x7a0d9b2400): 0:235)* (NavigationBar (0x7a12f7d800): 3:1070) (org.thoughtcrime.securesms/org.thoughtcrime.securesms.RegistrationActivity (0x7a0d954800): 250:374) 
07-13 23:25:52.116  1678  3537 I ActivityManager: moveHomeStack, setupComplete:true
07-13 23:25:52.116  2671  6547 D ProcSpeedReader: Failed to read freq stats from null
07-13 23:25:52.182  1678  6957 I OpenGLRenderer: Initialized EGL, version 1.4
07-13 23:25:52.182  1678  6957 D OpenGLRenderer: Swap behavior 1
07-13 23:25:52.226  1678  1688 I art     : Background partial concurrent mark sweep GC freed 2931
```

**Comment by greyson-signal** [comment] 2018-07-14 16:00
Dupe of #7975. Thank you!

**Closed by greyson-signal** 2018-07-14 16:00 UTC
