### ISSUE TITLE
Constant crash of signal on Nexus 6p, since  first Nougat update.

### ISSUE THREAD

**Issue by neurotensin** [signalapp/Signal-Android#5923] opened 2016-12-04 22:18 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal continual shows "Signal stopped" and then restarts. Messaging appears to work normally, but of course , battery life may be affected.

### Steps to reproduce
Happens constantly.

### Device info

**Device:** Manufacturer Model Nexus 6P
**Android version:** 7.0 Build NBD91K
**Signal version:** 3.23.0

### Link to debug log

https://gist.github.com/anonymous/2c4e04d9583b6f8f1721c2adf93d7c24

**Comment by Trolldemorted** [comment] 2016-12-05 15:00
can you still use Signal, or does it crash immediately on startup?

Could it be you have a contact without a number in your contacts?

**Comment by neurotensin** [comment] 2016-12-07 01:47
It doesn't seem to stop signal working, but the error keeps reappearing. I've not found a correlation other than having the phone lock screen off!!

Occasionally it crashes completely (closing mid-message), but restarting seems to carry on ok.

A bit of a mystery, but i can't see any strange contacts (I saw the log and thought the same)...

**Comment by jkdf2** [comment] 2017-01-02 04:18
Hi @neurotensin 

I believe this may be a duplicate of #5639 when the libsignal service does not flag a null number as an `InvalidNumberException`. @moxie0 merged my fix for this an hour ago. I am not sure when the fix will go live but hopefully this should fix you up 😺

**Comment by neurotensin** [comment] 2017-01-02 11:48
Well it seems to have lessened since the 7.1.1 update, though still happens occasionally. I'll make a note when it gets updated, upload a new trace if it continues.

**Comment by automated-signal** [comment] 2018-04-03 00:53
GitHub Issue Cleanup:
See #7598 for more information.

**Closed by automated-signal** 2018-04-03 00:53 UTC
Labels: bug, crash
