### ISSUE TITLE
Archived chats keep getting back unarchived after a few hours or days.

### ISSUE THREAD

**Issue by omargoda** [signalapp/Signal-Android#11587] opened 2021-09-02 01:20 UTC
Let's begin with a checklist: Replace the empty checkboxes [ ] below with checked ones [x] accordingly. -->

- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Archived chats keep getting back unarchived after a few hours or days.

### Steps to reproduce
- Open Signal
- Select some chats and press the archive button at the top bar.
- It is better that you enable signal locking using the fingerprint.
- Open Signal the next day.
- Chats appear again unarchived

**Actual result:** Archived chats get back unarchived after a few hours or days.
**Expected result:** Normally archived chats should stay archived till the user unarchive them manually.
### Device info

**Device:** Huawei Nova 7i
**Android version:** 10.1.0
**Signal version:** 5.21.6

**Comment by cody-signal** [comment] 2021-09-02 14:27
Are the archived chats getting new messages? New messages cause chats to become unarchive by design. It was modeled after the old Google Inbox app. If they aren't getting new messages, and they are unarchiving that's a bug. Do you have a linked device?

**Comment by omargoda** [comment] 2021-09-02 14:55
@cody-signal I guess you are right, but yet I think making them archived till users manually unarchive them is a better feature as when archiving a chat, usually you do not want it to appear in the main chats view or push notifications.

**Comment by cody-signal** [comment] 2021-09-02 15:07
Yup, this confused me too when I started using Signal, but it's the way it's designed. You can hop over to the community forum and start/find a feature request to change the behavior, but I don't think product/design is looking to change it.

I'm going to close this ticket. Cheers.

**Closed by cody-signal** 2021-09-02 15:07 UTC
