### ISSUE TITLE
Can't send Location with de-googled Android like /e/ OS

### ISSUE THREAD

**Issue by huuhaa** [signalapp/Signal-Android#10944] opened 2021-02-09 17:50 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Location cannot be sent.

### Steps to reproduce
- Install Signal to de-googled Android device
- Start conversation with friend
- try to send your location

**Actual result:** When trying to send location location picker opens up, it does find my location, but after confirming that Signal just shows preview image of apparently mapbox address to the location, but that cannot be sent. Previous version of Signal crashed at this point and restarted automatically.
**Expected result:** When confirming location that location should be sent to recipient

### Screenshots

![location](https://user-images.githubusercontent.com/469355/107403048-8f18c480-6afc-11eb-832b-3691105278e4.jpg)

### Device info

**Device:** Redmi Note 8T
**Android version:**10.0.0 / /e/ OS 0.14q
**Signal version:** 5.3.7.1

### Link to debug log

https://debuglogs.org/4806321a68961f910d25cf140f2ff177ad01c4d582864626684c34c711c4d625

**Additional note:** I know you don't exactly support de googled android devices, but on the other hand since you prefer to offer your own build also to users who doesn't use Google Play Store, I think it is valid to report bug also in this case.

**Comment by Cerberus0** [comment] 2021-02-09 18:34
Duplicate of https://github.com/signalapp/Signal-Android/issues/7835

**Closed** 2022-02-02 21:27 UTC
Labels: wontfix
