### ISSUE TITLE
Previews link save thumbnail in media

### ISSUE THREAD

**Issue by primarto** [signalapp/Signal-Android#10866] opened 2021-01-31 00:16 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When the Generate link previews option is turned on and you receive any link, the thumbnail generated with the link is saved in Media as the received image.
### Steps to reproduce
- Enable Generate link previews
- Receive any link
- Open All Media

**Actual result:** Thumbnail generated with the link is saved in Media
**Expected result:** Thumbnail generated from the link not to be saved in the media, I see no reason why it would be necessary to save the thumbnail, only if we could see the received links through All media

### Device info

**Device:** Xiaomi redmi note 7
**Android version:** 10
**Signal version:** 5.3.7.1

**Comment by happychameleon** [comment] 2021-01-31 01:37
This is intended behavior and not a bug, join the forum to add your voice to the relevant feature request:

https://community.signalusers.org/t/dont-save-link-preview-as-image/16462/6

Please close this bug report.

**Closed** 2022-02-03 02:21 UTC
Labels: wontfix
