### ISSUE TITLE
After creating a new group the back button should not bring you back to the group creation screen

### ISSUE THREAD

**Issue by Meteor0id** [signalapp/Signal-Android#12199] opened 2022-04-24 12:07 UTC
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- make a new group
- press the back arrow to left

**Actual result:** you can again name the group and press create
**Expected result:** you should be send back to the chats overview

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 10.0.0
**Signal version:** 5.36.3

**Comment by cody-signal** [comment] 2022-05-02 17:55
Hey there @Meteor0id , I can't reproduce this. Both the up arrow (toolbar button) and the back button both return me to the conversation list.

**Comment by cody-signal** [comment] 2022-05-02 19:40
Hrm. Well I'm going to close this, comment and let me know if you can repro it and we can reopen.

**Closed by cody-signal** 2022-05-02 19:40 UTC
Labels: acknowledged
