### ISSUE TITLE
Answer/Deny Call button not present

### ISSUE THREAD

**Issue by RiseT** [signalapp/Signal-Android#8225] opened 2018-09-26 20:06 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Today (for the first & only time so far), I've had the strange experience of an incoming Signal call which I neither could answer nor deny since there was no corresponding button anymore. I've tried swiping at the location where that button should get displayed, but to no avail.

Regarding the linked log, this incoming call must have happened either on 2018-09-26 14:50 or 15:35 (not sure anymore)

### Steps to reproduce
n/a

**Actual result:** Answer/Deny Call button not present
**Expected result:** Answer/Deny Call button present
### Screenshots
Sorry, didn't think of making one at that moment. Just think of the usual incoming call screen without that button.

### Device info

**Device:** Nexus 5X
**Android version:** 8.1.0
**Signal version:** 4.26.2

### Link to debug log

https://debuglogs.org/34ec10219cdda463d97d86dcd1af3dca4ef57acc54ea4392a3092943969773d8

**Comment by minnmann** [comment] 2018-09-26 20:43
Like this? https://github.com/signalapp/Signal-Android/issues/8141#issuecomment-423670734

**Comment by greyson-signal** [comment] 2018-09-26 23:17
Yeah, this almost certainly appears to be a dupe of #8141. Thanks for the additional report and log! Please reopen this if you think your issue is distinct.

**Closed by greyson-signal** 2018-09-26 23:17 UTC

**Comment by RiseT** [comment] 2018-09-27 11:38
Right. Sorry, I've look at that issue prior to posting mine, but somehow managed to not realize the dupe.

@greyson-signal Regarding my log: I've had several call disconnects that day while speaking with that contact via Signal. You might might want to find out the reason. That contact is currently residing in China, so it is a possiblity that this is somehow related to the "Great Firewall". I'm currently not sure if the contact used a VPN during the call and will add that info as soon as I know.
