### ISSUE TITLE
Video-call screenfreeze after 8 minutes

### ISSUE THREAD

**Issue by 1stchiller** [signalapp/Signal-Android#8755] opened 2019-04-11 07:35 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
when in videocall the screen freezes. 

### Steps to reproduce
- open signal
- open chat
- video call someone

**Actual result:** 
the video call works like it should until around 7-10 minutes. My screen freezes and i end the call to call again. Only to start the circle again. The picture of my partner is just one picture but i hear her talk but can't see her lips moving or the camera.
**Expected result:** 
video call should show me what is going on on the other end.

### Device info

**Device:** OnePlus 6T
**Android version:** 9
**Signal version:** 4.37.2

### Link to debug log

https://debuglogs.org/fbfceb42b0cbd6fc3202ce95b4ff6080528c7df6558a7f19cd928478e3a03560

P.S
I apologize in advance, its my first bugreport ever, and english is not my mother tounge

**Comment by greyson-signal** [comment] 2019-04-12 19:22
Closing as dupe of ##8685

**Closed by greyson-signal** 2019-04-12 19:22 UTC
