### ISSUE TITLE
Signal crashes when trying to copy debug log

### ISSUE THREAD

**Issue by mueller-ma** [signalapp/Signal-Android#8082] opened 2018-08-07 14:56 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal crashes when trying to copy debug log.

It is possible to change the logger buffer size in the Android dev options. I have set it to 4 M.

### Steps to reproduce
- Open debug log
- Click and hold on the log and select "Select all" when it appears
- Click on "Copy"

**Actual result:** App crashes
**Expected result:** Debug log should be copied to clipboard

### Device info

**Device:** Oneplus X
**Android version:** 7.1.2, LineageOS 14.1
**Signal version:** 4.23.4

### Link to debug log
````
08-07 16:50:54.992 19966-19966/org.thoughtcrime.securesms E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.thoughtcrime.securesms, PID: 19966
    java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1622972 bytes
        at android.content.ClipboardManager.setPrimaryClip(ClipboardManager.java:125)
        at android.widget.TextView.setPrimaryClip(TextView.java:9692)
        at android.widget.TextView.onTextContextMenuItem(TextView.java:9386)
        at android.widget.Editor$TextActionModeCallback.onActionItemClicked(Editor.java:3793)
        at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onActionItemClicked(DecorView.java:2303)
        at com.android.internal.view.FloatingActionMode$3.onMenuItemSelected(FloatingActionMode.java:88)
        at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:761)
        at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
        at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:904)
        at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:894)
        at com.android.internal.view.FloatingActionMode$4.onMenuItemClick(FloatingActionMode.java:114)
        at com.android.internal.widget.FloatingToolbar$FloatingToolbarPopup$3.onClick(FloatingToolbar.java:394)
        at android.view.View.performClick(View.java:5637)
        at android.view.View$PerformClick.run(View.java:22433)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6186)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
     Caused by: android.os.TransactionTooLargeException: data parcel size 1622972 bytes
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:615)
        at android.content.IClipboard$Stub$Proxy.setPrimaryClip(IClipboard.java:170)
        at android.content.ClipboardManager.setPrimaryClip(ClipboardManager.java:123)
        at android.widget.TextView.setPrimaryClip(TextView.java:9692) 
        at android.widget.TextView.onTextContextMenuItem(TextView.java:9386) 
        at android.widget.Editor$TextActionModeCallback.onActionItemClicked(Editor.java:3793) 
        at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onActionItemClicked(DecorView.java:2303) 
        at com.android.internal.view.FloatingActionMode$3.onMenuItemSelected(FloatingActionMode.java:88) 
        at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:761) 
        at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152) 
        at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:904) 
        at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:894) 
        at com.android.internal.view.FloatingActionMode$4.onMenuItemClick(FloatingActionMode.java:114) 
        at com.android.internal.widget.FloatingToolbar$FloatingToolbarPopup$3.onClick(FloatingToolbar.java:394) 
        at android.view.View.performClick(View.java:5637) 
        at android.view.View$PerformClick.run(View.java:22433) 
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6186) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779) 
````

**Comment by jeremymasters** [comment] 2018-08-07 18:42
Might be a dupe of #7976

**Comment by greyson-signal** [comment] 2018-08-08 15:05
@jeremymasters In your ticket, you describe the crash as happening immediately after you go to the debug log screen. In this ticket, it only happens after a select-all > copy. Am I understanding your issue properly, or is it more similar to this one?

**Comment by greyson-signal** [comment] 2018-08-08 15:11
In general, this ticket is interesting. I don't know if there's a good way for us to get a maximum copy size or anything. I tested copying large amounts of text in other apps (like Firefox) and got similar crashes. This is all kind of core Android stuff.

**Comment by jeremymasters** [comment] 2018-08-08 15:43
@greyson-signal prior, I had the same issue where it would crash on copy

**Comment by greyson-signal** [comment] 2018-09-17 04:36
I think we may have to leave the copy issue as an Android platform issue.

**Closed by greyson-signal** 2018-09-17 04:36 UTC
