### ISSUE TITLE
Camera viewfinder turns black on rotation.

### ISSUE THREAD

**Issue by herrfisk** [signalapp/Signal-Android#7815] opened 2018-05-19 15:17 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The camera turns black on rotation but when the device is turned back again the image returns. When the viewfinder is black you can get an image again in the current state by switching back and forth between the front and back camera.

### Steps to reproduce
- Compose a message and click the camera button
- Tilt the phone, camera goes black.
- Tilt phone back again and the image is back

**Actual result:** The camera turns black instead of going into the right rotation (landscape/portrait)
**Expected result:** The camera should rotate

### Device info
**Device:** LG Nexus 5x
**Android version:** 8.1.0
**Signal version:** 4.19.3

### Link to debug log
https://debuglogs.org/2a5f1d1e0e413b56869fecd0512373be3114943f3efb3536422c8b28cf0b89c3

**Comment by igor2x** [comment] 2018-05-19 15:52
This is a duplicate of #5855 and #4843 and #7442 with possible fix #7449.

I know this was a problem once on my device, but I tried to reproduce right now and I am unable to reproduce a problem. It works fine in my case. I am having exactly the same device as @herrfisk and exactly the same versions of Android and Signal.

**Comment by herrfisk** [comment] 2018-05-19 19:14
Very strange with same setup but different results. I'll have to try clearing cache and data and/or reinstall

**Comment by erik55** [comment] 2018-06-16 15:10
On my Samsung Galaxy S7 it happened a minute ago. 

Android 8.0.0
Signal 4.21.0

I does not happen always. I tried it a few times. 

Click photo, 
port authority mode works, 
turn 90 degrees: black in landscape mode. 
Turn back to portrait mode: works. 

Did it several times with several contacts. 

Suddenly for one contact after a second of waiting in landscape mode it began to work. Then I turned it back to portrait mode: now black!

Weird.

**Comment by mathsen** [comment] 2018-08-13 06:05
Happens also on my Huawei P20 Lite, Android 8

**Comment by brs17** [comment] 2018-09-25 04:36
Looks like there is a PR open here with a potential fix: https://github.com/signalapp/Signal-Android/pull/7449

**Comment by greyson-signal** [comment] 2018-09-25 15:32
There's a new photo capture flow being introduced in #8215 that does not have this problem.

**Closed by greyson-signal** 2018-09-25 15:32 UTC
Labels: device-specific
