### ISSUE TITLE
Signal forcing PIN creation

### ISSUE THREAD

**Issue by bulgyharriet** [signalapp/Signal-Android#9819] opened 2020-07-03 01:01 UTC
Title.

**Comment by grandchild** [comment] 2020-07-03 08:41
Duplicate of #9812.

**Comment by bsteindl** [comment] 2020-07-03 10:24
But it's not fixed yet

**Comment by cpmcgrath** [comment] 2020-07-04 22:03
I'm not sure if the developers are still looking at 9812, but there's been a lot of constructive comments since it was closed. Please read and reconsider.

**Comment by najtin** [comment] 2020-07-06 19:27
this is a total deal breaker for me. I use signal because i do not want a cloud backup of anything. I will migrate to https://github.com/matrix-org where i means my entire family and me.

**Comment by greyson-signal** [comment] 2020-07-06 20:22
Closing as duplicate of #9812

**Closed by greyson-signal** 2020-07-06 20:22 UTC
