### ISSUE TITLE
Feature Request - Ability to swap to back facing camera during video call

### ISSUE THREAD

**Issue by usmarine2141** [signalapp/Signal-Android#7443] opened 2018-02-26 22:01 UTC
Could yall in the very near future add the ability to swap to back facing camera during video call

**Comment by p4nci** [comment] 2018-02-27 06:19
@usmarine2141 please use the template for new issues (see also [Submitting useful bug reports](https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports)).

BTW: this issue is duplicate of #6279

**Comment by jlund** [comment] 2018-02-28 03:52
Closing in favor of #6279.

**Closed by jlund** 2018-02-28 03:52 UTC
