### ISSUE TITLE
Crashed on opening the application in Android 8.0.0, Api 26

### ISSUE THREAD

**Issue by alhasanmridha** [signalapp/Signal-Android#8183] opened 2018-09-07 06:30 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
App is crashing after installation in Android 8.0.0, Api 26 from android studio 3.1.4. Same code works fine in android 6.

### Steps to reproduce
- just build from android studio

### Device info

**Device:** Samsung  SM-J720F
**Android version:**8.0.0

### debug log
`09-07 12:10:20.523 31289-31289/org.thoughtcrime.securesms E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.thoughtcrime.securesms, PID: 31289
    java.lang.RuntimeException: Unable to get provider com.klinker.android.send_message.MmsFileProvider: java.lang.ClassNotFoundException: Didn't find class "com.klinker.android.send_message.MmsFileProvider" on path: DexPathList[[zip file "/data/app/org.thoughtcrime.securesms-VTacP0Lp13dOaf2_IjWz7g==/base.apk", zip file "/data/app/org.thoughtcrime.securesms-VTacP0Lp13dOaf2_IjWz7g==/split_lib_directories_apk.apk", zip file "/data/app/org.thoughtcrime.securesms-VTacP0Lp13dOaf2_IjWz7g==/split_lib_resources_apk.apk"],nativeLibraryDirectories=[/data/app/org.thoughtcrime.securesms-VTacP0Lp13dOaf2_IjWz7g==/lib/arm, /data/app/org.thoughtcrime.securesms-VTacP0Lp13dOaf2_IjWz7g==/base.apk!/lib/armeabi-v7a, /data/app/org.thoughtcrime.securesms-VTacP0Lp13dOaf2_IjWz7g==/split_lib_directories_apk.apk!/lib/armeabi-v7a, /data/app/org.thoughtcrime.securesms-VTacP0Lp13dOaf2_IjWz7g==/split_lib_resources_apk.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:6577)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6129)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6039)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6940)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.klinker.android.send_message.MmsFileProvider" on path: DexPathList[[zip file "/data/app/org.thoughtcrime.securesms-VTacP0Lp13dOaf2_IjWz7g==/base.apk", zip file "/data/app/org.thoughtcrime.securesms-VTacP0Lp13dOaf2_IjWz7g==/split_lib_directories_apk.apk", zip file "/data/app/org.thoughtcrime.securesms-VTacP0Lp13dOaf2_IjWz7g==/split_lib_resources_apk.apk"],nativeLibraryDirectories=[/data/app/org.thoughtcrime.securesms-VTacP0Lp13dOaf2_IjWz7g==/lib/arm, /data/app/org.thoughtcrime.securesms-VTacP0Lp13dOaf2_IjWz7g==/base.apk!/lib/armeabi-v7a, /data/app/org.thoughtcrime.securesms-VTacP0Lp13dOaf2_IjWz7g==/split_lib_directories_apk.apk!/lib/armeabi-v7a, /data/app/org.thoughtcrime.securesms-VTacP0Lp13dOaf2_IjWz7g==/split_lib_resources_apk.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6562)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6129) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6039) 
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6940) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
    	Suppressed: java.io.IOException: No original dex files found for dex location (arm) /data/app/org.thoughtcrime.securesms-VTacP0Lp13dOaf2_IjWz7g==/split_lib_resources_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:353)
        at dalvik.system.DexFile.<init>(DexFile.java:100)
        at dalvik.system.DexFile.<init>(DexFile.java:74)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
        at dalvik.system.DexPathList.<init>(DexPathList.java:157)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.PathClassLoaderFactory.createClassLoader(PathClassLoaderFactory.java:43)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:36)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:678)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:711)
        at android.app.LoadedApk.getResources(LoadedApk.java:944)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2303)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5939)
        		... 8 more`

**Comment by greyson-signal** [comment] 2018-09-08 15:51
Looks like you're having some sort of proguard issue. Building an unmodified Android master shouldn't cause any problems. I don't know what changes you've made. You can determine if it has something to do with your build environment by using the Docker images we've made to compile Signal. Check out how to do that in our [reproducible builds guide](https://github.com/signalapp/Signal-Android/wiki/Reproducible-Builds).

That said, we reserve github for bugs in the app, so I'm going to close this. Feel free to reach out for additional support on [the forum](https://community.signalusers.org/). Thanks!

**Closed by greyson-signal** 2018-09-08 15:51 UTC

**Comment by dthree** [comment] 2018-09-11 05:50
@alhasanmridha If you add these exceptions to `proguard.cfg`, It'll let you build the app. Just dont commit them on your branch if you're trying to do a PR.

```
-keep class com.klinker.android.*.* { *; }
-keep class android.arch.lifecycle.** { *; }
```

**Comment by tokenray** [comment] 2018-10-03 17:27
> @alhasanmridha If you add these exceptions to `proguard.cfg`, It'll let you build the app. Just dont commit them on your branch if you're trying to do a PR.
> 
> ```
> -keep class com.klinker.android.*.* { *; }
> -keep class android.arch.lifecycle.** { *; }
> ```

What does the PR stands for?

**Comment by dthree** [comment] 2018-10-04 17:31
@tokenray Pull Request.

**Comment by Hkarimi561** [comment] 2018-12-30 13:15
Same Issue Here

**Comment by Hkarimi561** [comment] 2018-12-30 13:18
#7652

**Comment by Hkarimi561** [comment] 2018-12-30 13:18
#reopen #8183

**Comment by Hkarimi561** [comment] 2018-12-30 13:19
reopen #8183

**Comment by greyson-signal** [comment] 2019-01-18 23:20
Signal builds are reproducible. Please see the wiki.
https://github.com/signalapp/Signal-Android/wiki/Reproducible-Builds

If you're not able to build a tagged release, it's almost certainly an issue with your build environment. You can direct those questions to the forum. Thanks!
