### ISSUE TITLE
Makes alert noise even when phone on silent (Android) 

### ISSUE THREAD

**Issue by tomchiverton** [signalapp/Signal-Android#5663] opened 2016-09-03 21:43 UTC
## I have:

[x ] searched open and closed issues for duplicates
- [ x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

(delayed delivery) Signal messages play alert when phone is on silent 
### Steps to reproduce
- put phone on silent 
- disable data
- get sent a Signal message 
- enable data 
- alert noise sounds 

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
Sound 
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
No sound 
### Screenshots

n/a
### Device info

**Device:** Sony z3c 
**Android version:** 5.1.1
**Signal version:** latest from Play Store 
### Link to debug log

https://gist.github.com/5a31d82fc1cdaabe748990f87e5b257f

**Comment by FeuRenard** [comment] 2016-09-03 22:25
Do you mean the sound is played while you are still inside the conversation? If this is the case, this issue would be a duplicate of #3337 and will be solved in the next release (probably 3.18.1).

**Comment by automated-signal** [comment] 2018-04-03 00:37
GitHub Issue Cleanup:
See #7598 for more information.

**Closed by automated-signal** 2018-04-03 00:37 UTC
Labels: pending information
