### ISSUE TITLE
suggest : add a feature to use front and back camera on video calling

### ISSUE THREAD

**Issue by ara11** [signalapp/Signal-Android#7364] opened 2018-01-26 15:14 UTC
suggest : add a feature to use front and back camera on video calling
i can use front camera at this time only, you should support front and back camera together

**Comment by p4nci** [comment] 2018-01-26 16:20
@ara11 please use the template for new issues.

BTW: this issue is duplicate of https://github.com/signalapp/Signal-Android/issues/6279 and please use reaction emojis to support an issue, future, comment, ...

**Closed** 2018-01-27 02:55 UTC
