### ISSUE TITLE
Can not add contact to groups after he re-registered his account

### ISSUE THREAD

**Issue by daharn** [signalapp/Signal-Android#11467] opened 2021-07-14 07:32 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
One of my contacts deleted his account and opened a new account using the same phone number. While we can continue our private chat without issue,  he can not receive or send messages in the groups he is in, being informed that he is no longer a member. As a group admin, if I try to re-add him to the group,  I am instead always adding his "old ID ". However,  this ID seems just to be an artifact local to my device that can not receive any more messages. This also applies to newly created groups!

I have first opened this as a community question [here](https://community.signalusers.org/t/re-registered-with-same-number-can-not-use-groups-any-more/34929) as well, but since it just seems like there are some remnants of the old ID that are not properly updated locally, this appears like a bug to me, especially since everything else is working. Thus, I hope the double post is justified in this case.

### Steps to reproduce
- contact deletes his account
- contact re-registers account using the same phone number and PIN
- trying to re-add contact to existing or new groups

**Actual result:** Instead of properly re-adding the contact to the group, some dysfunctional remnants of his old account is added.
**Expected result:** Adding the contact to the group should replace the old ID with the new, as it works in private chats.

### Device info

**Android version:** 7.1.1
**Signal version:** 5.15.6

### Link to debug log
[debug log](https://debuglogs.org/32f457308a5e3cb1aadebc715a0b4cb670023acac52809b801726d1cef69d42e)

The important part is probably "local recipient doesn't match."

**Comment by unoxxis** [comment] 2021-09-17 17:49
I had the same issue with someone who had to re-register his ID, where there was even intermittently a second conversation open.

Another piece of evidence which I have noticed is that if there is the described behavior (supposedly a mismatch between the "new ID" valid in a direct 1-to-1 conversation and the "old ID" falsely remembered in groups), that the groups of the contact are no longer shown as "shared groups" in the contact card.

----

I also found a workaround (which might not work for everyone) to make conversations in groups working again by forcing a contact re-sync while the offending contact and me are no longer in the same group:

1. Remove the offending contact from (possibly all?) of the groups that have the problem, i.e. messages are not received / group is not shown in the shared groups list in the contact details.
2. Close signal completely ("force close" in Android app settings)
3. Go to the Android Account settings and delete the "Signal Account" there. You can ignore the warning, by Signal's nature it keeps its data separate so nothing is deleted and all your chats will still be there.
4. Start up Signal again, go to the contact list (pen icon in list view) and force a contact refresh by swiping down the top of the list. Wait for the sync to happen.
5. Re-add the offending account to the group(s). For me the contact is now registered correctly using his "new ID" and I can receive his messages and also see the groups as shared groups in the card.

What I have not tested (and cannot, since the issue is now fixed for me):
- I don't know if you need to remove the "duplicate" contact from _all_ groups or if it works _partially_ only for a subset of groups or new groups.
- It might be that the opposite way also works, i.e. leaving the group(s) yourself, then force re-syncing contacts as described above in steps 2-4, and then re-joining the group(s). But it might well be!

**Comment by unoxxis** [comment] 2021-09-19 16:17
Now another contact of mine has the same problem (with the same group...). Additionally, we found out that if you have Signal coupled with a Desktop App, the messages are received there correctly - just not on the Android phone.

**Comment by unoxxis** [comment] 2021-09-19 16:54
I tried my workaround from above with said contact except that we tried the opposite way - i.e. he left all shared groups, then force re-synced contacts, and then joined them again. That fixed the problem as well.

**Closed** 2022-02-02 01:05 UTC
Labels: wontfix
