### ISSUE TITLE
OOM during prekey migration

### ISSUE THREAD

**Issue by tux2sa** [signalapp/Signal-Android#7866] opened 2018-05-30 19:34 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The device Crash after i upgrade the Signal App to a newer version than 4.16.9. I have read the Issue #7572 and try the 4.20.4 but it does not work.
Restore with OandBackup to the 4.16.9 version with the App data work fine but Signal cannot use.
Open the Signal app after Update with the old user data and the App imideatly crash and close.

I Allrady tryed to remove all Messages in the chat an then update but no success.

### Steps to reproduce
Signal with user Data (Version 4.16.9) Update to 4.18.3 or 4.20.4 after Update open Signal and it crash immediatly.

**Actual result:** Signal App crashes
**Expected result:** After update to a newer Signal version the App works fine and not Crash

### Device info

**Device:** Manufacturer Model LG G4 with LineageOs 14.1.20180530
**Android version:** 7.1.2
**Signal version:** 4.16.9

### Link to debug log
https://gist.github.com/tux2sa/c343566b26c4bf4a1cc25a15a6ce6a9f

**Comment by greyson-signal** [comment] 2018-05-31 00:19
Duplicate of #7863

**Comment by greyson-signal** [comment] 2018-06-08 00:18
Looks like this is a separate issue from the one I linked. There's on OOM error when opening a backup from 4.16.9 in 4.20.6.

```java
6-07 16:40:23.573 19839 19839 W service : Broadcasting new secret...
06-07 16:40:23.574  2326  2366 W BroadcastQueue: Skipping deliver [background] BroadcastRecord{f0e4bbd u0 org.thoughtcrime.securesms.service.action.NEW_KEY_EVENT} to ReceiverList{5d4a4ee 19839 org.thoughtcrime.securesms/10146/u0 remote:c13269}: process crashing
06-07 16:40:23.575 19839 19839 W KeyCachingService: onStartCommand, null
06-07 16:40:23.575 19839 19839 W PassphraseRequiredActionBarActivity: onPause()
06-07 16:40:23.581  2326  2364 I WindowManager: Failed to capture screenshot of Token{5f8b143 ActivityRecord{5b916f2 u0 org.thoughtcrime.securesms/.RoutingActivity t3468 f}} appWin=Window{7cc9ad8 u0 Starting org.thoughtcrime.securesms} drawState=4
06-07 16:40:23.586 19839 19882 W MmsSmsDatabase: Executing query: SELECT _id, unique_row_id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, read_receipt_count, mismatched_identities, network_failures, subscription_id, expires_in, expire_started, notified, transport_type, attachment_json, quote_id, quote_author, quote_body, quote_attachment, shared_contacts FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, 'SMS::' || _id || '::' || date_sent AS unique_row_id, NULL AS attachment_json, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, read_receipt_count, mismatched_identities, subscription_id, expires_in, expire_started, notified, NULL AS network_failures, 'sms' AS transport_type, NULL AS quote_id, NULL AS quote_author, NULL AS quote_body, NULL AS quote_attachment, NULL AS shared_contacts FROM sms WHERE (read = 0 AND notified = 0) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, mms._id AS _id, 'MMS::' || mms._id || '::' || date AS unique_row_id, json_group_array(json_object('_id', part._id, 'unique_id', part.unique_id, 'mid', part.mid,'data_size', part.data_size, 'file_name', part.file_name, '_data', part._data, 'thumbnail', part.thumbnail, 'ct', part.ct, 'cl', part.cl, 'fast_preflight_id', part.fast_preflight_id, 'voice_note', part.voice_note, 'width', part.width, 'height', part.height, 'quote', part.quote, 'cd', part.cd, 'name', part.name, 'pending_push', part.pending_push)) AS attachment_json, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, read_receipt_count, mismatched_identities, subscription_id, expires_in, expire_started, notified, network_failures, 'mms' AS transport_type, quote_id, quote_author, quote_body, quote_attachment, shared_contacts FROM mms LEFT OUTER JOIN part ON part.mid = mms._id WHERE (read = 0 AND notified = 0) GROUP BY mms._id ORDER BY date_received ASC)
06-07 16:40:23.593 19839 19839 W KeyCachingService: onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_START_EVENT
06-07 16:40:23.593 19839 19839 W KeyCachingService: Incrementing activity count...
06-07 16:40:23.613 19839 19886 I art     : Alloc concurrent mark sweep GC freed 1388(123KB) AllocSpace objects, 0(0B) LOS objects, 40% free, 9MB/16MB, paused 972us total 48.805ms
06-07 16:40:23.613 19839 19886 I art     : Forcing collection of SoftReferences for 778MB allocation
06-07 16:40:23.614 19839 19886 I art     : Starting a blocking GC Alloc
06-07 16:40:23.658 19839 19886 I art     : Alloc concurrent mark sweep GC freed 2486(101KB) AllocSpace objects, 0(0B) LOS objects, 40% free, 9MB/16MB, paused 571us total 44.143ms
06-07 16:40:23.658 19839 19886 W art     : Throwing OutOfMemoryError "Failed to allocate a 815909458 byte allocation with 6922064 free bytes and 502MB until OOM"
06-07 16:40:23.658 19839 19886 I art     : Starting a blocking GC Alloc
06-07 16:40:23.658 19839 19886 I art     : Starting a blocking GC Alloc
06-07 16:40:23.665 19839 19886 I art     : Alloc sticky concurrent mark sweep GC freed 1349(44KB) AllocSpace objects, 0(0B) LOS objects, 40% free, 9MB/16MB, paused 578us total 6.432ms
06-07 16:40:23.666 19839 19886 I art     : Starting a blocking GC Alloc
06-07 16:40:23.666  2326  2366 W BroadcastQueue: Skipping deliver [background] BroadcastRecord{30025f u-1 android.net.conn.CONNECTIVITY_CHANGE} to ReceiverList{a58e6b9 19839 org.thoughtcrime.securesms/10146/u0 remote:7078080}: process crashing
06-07 16:40:23.670 19839 19893 W MessageRetrievalService: Waiting for websocket state change....
06-07 16:40:23.672 19839 19893 W MessageRetrievalService: Network requirement: false, active activities: 0, push pending: 0, gcm disabled: true
06-07 16:40:23.680 19839 19839 W MessageRetrievalService: Active Count: 1
06-07 16:40:23.681 19839 19893 W MessageRetrievalService: Network requirement: false, active activities: 1, push pending: 0, gcm disabled: true
06-07 16:40:23.712 19839 19886 I art     : Alloc partial concurrent mark sweep GC freed 742(39KB) AllocSpace objects, 0(0B) LOS objects, 39% free, 9MB/16MB, paused 3.479ms total 45.405ms
06-07 16:40:23.712 19839 19886 I art     : Starting a blocking GC Alloc
06-07 16:40:23.734 19839 19839 W KeyCachingService: onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_STOP_EVENT
06-07 16:40:23.734 19839 19839 W KeyCachingService: Decrementing activity count...
06-07 16:40:23.735 19839 19839 W MessageRetrievalService: Active Count: 0
06-07 16:40:23.738 19839 19893 W MessageRetrievalService: Network requirement: false, active activities: 0, push pending: 0, gcm disabled: true
06-07 16:40:23.765 19839 19886 I art     : Alloc concurrent mark sweep GC freed 389(25KB) AllocSpace objects, 0(0B) LOS objects, 39% free, 9MB/16MB, paused 5.916ms total 51.494ms
06-07 16:40:23.765 19839 19886 I art     : Forcing collection of SoftReferences for 778MB allocation
06-07 16:40:23.765 19839 19886 I art     : Starting a blocking GC Alloc
06-07 16:40:23.810 19839 19886 I art     : Alloc concurrent mark sweep GC freed 98(6KB) AllocSpace objects, 0(0B) LOS objects, 40% free, 9MB/16MB, paused 442us total 44.365ms
06-07 16:40:23.810 19839 19886 W art     : Throwing OutOfMemoryError "Failed to allocate a 815909458 byte allocation with 6911450 free bytes and 502MB until OOM"
06-07 16:40:23.814 19839 19886 I Process : Sending signal. PID: 19839 SIG: 9
06-07 16:40:23.836  2326  3683 I ActivityManager: Process org.thoughtcrime.securesms (pid 19839) has died
06-07 16:40:23.836  2326  3704 D GraphicsStats: Buffer count: 9
06-07 16:40:23.836  2326  3683 D ActivityManager: cleanUpApplicationRecord -- 19839
06-07 16:40:23.837  2326  3683 W ActivityManager: Scheduling restart of crashed service org.thoughtcrime.securesms/.service.MessageRetrievalService in 1000ms
06-07 16:40:23.837  2326  3683 W ActivityManager: Scheduling restart of crashed service org.thoughtcrime.securesms/.service.KeyCachingService in 11000ms
06-07 16:40:23.840  2326  2580 W InputDispatcher: channel 'e370714 org.thoughtcrime.securesms/org.thoughtcrime.securesms.RoutingActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
06-07 16:40:23.840  2326  2580 E InputDispatcher: channel 'e370714 org.thoughtcrime.securesms/org.thoughtcrime.securesms.RoutingActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
06-07 16:40:23.843  2326  3158 I WindowManager: WIN DEATH: Window{e370714 u0 org.thoughtcrime.securesms/org.thoughtcrime.securesms.RoutingActivity}
06-07 16:40:23.843  2326  3158 W InputDispatcher: Attempted to unregister already unregistered input channel 'e370714 org.thoughtcrime.securesms/org.thoughtcrime.securesms.RoutingActivity (server)'
06-07 16:40:23.860  2326 10446 W ActivityManager: Ignoring remove of inactive process: ProcessRecord{43c08f3 0:org.thoughtcrime.securesms/u0a146}
06-07 16:40:24.018  2326  2373 W AppOps  : Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0
06-07 16:40:24.470   281   476 E ThermalEngine: [GPU_MON] 11 percent. Current Sampling Time is 1 sec
06-07 16:40:24.849  2326  2366 I ActivityManager: Start proc 19899:org.thoughtcrime.securesms/u0a146 for service org.thoughtcrime.securesms/.service.MessageRetrievalService
06-07 16:40:24.935 19899 19899 I MultiDex: VM with version 2.1.0 has multidex support
06-07 16:40:24.935 19899 19899 I MultiDex: Installing application
06-07 16:40:24.936 19899 19899 I MultiDex: VM has multidex support, MultiDex support library is disabled.
06-07 16:40:24.959 19899 19899 W PartProvider: onCreate()
06-07 16:40:25.147 19899 19899 W PersistentAlarmManagerListener: class org.thoughtcrime.securesms.service.RotateSignedPreKeyListener scheduling for: 1528579752983
06-07 16:40:25.150 19899 19899 W PersistentAlarmManagerListener: class org.thoughtcrime.securesms.service.DirectoryRefreshListener scheduling for: 1528450152986
06-07 16:40:25.163 19899 19899 I org.webrtc.Logging: NativeLibrary: Loading native library.
06-07 16:40:25.163 19899 19899 I org.webrtc.Logging: NativeLibrary: Loading library: jingle_peerconnection_so
06-07 16:40:25.171 19899 19923 W SQLCipherOpenHelper: Upgrading database: 1, 9
06-07 16:40:25.177 19899 19899 D JVM     : JVM::Initialize@[tid=19899]
06-07 16:40:25.178 19899 19899 D JVM     : JVM::JVM@[tid=19899]
06-07 16:40:25.178 19899 19899 D JVM     : LoadClasses
06-07 16:40:25.178 19899 19899 D JVM     : name: org/webrtc/voiceengine/BuildInfo
06-07 16:40:25.178 19899 19899 D JVM     : name: org/webrtc/voiceengine/WebRtcAudioManager
06-07 16:40:25.178 19899 19899 D JVM     : name: org/webrtc/voiceengine/WebRtcAudioRecord
06-07 16:40:25.178 19899 19899 D JVM     : name: org/webrtc/voiceengine/WebRtcAudioTrack
06-07 16:40:25.187 19899 19923 W PreKeyMigrationHelper: Migrated one-time prekey: 2363189
06-07 16:40:25.190 19899 19923 W PreKeyMigrationHelper: Migrated one-time prekey: 2363191
06-07 16:40:25.191 19899 19923 W PreKeyMigrationHelper: Migrated one-time prekey: 2363193
06-07 16:40:25.192 19899 19923 W PreKeyMigrationHelper: Migrated one-time prekey: 2363194
06-07 16:40:25.195 19899 19923 W PreKeyMigrationHelper: Migrated one-time prekey: 2363196
06-07 16:40:25.196 19899 19923 W PreKeyMigrationHelper: Migrated one-time prekey: 2363198
06-07 16:40:25.197 19899 19923 W PreKeyMigrationHelper: Migrated one-time prekey: 2363200
06-07 16:40:25.198 19899 19923 W PreKeyMigrationHelper: Migrated one-time prekey: 2363201
06-07 16:40:25.204 19899 19923 W PreKeyMigrationHelper: Migrated one-time prekey: 2363202
06-07 16:40:25.205 19899 19923 W PreKeyMigrationHelper: Migrated one-time prekey: 2363203
06-07 16:40:25.206 19899 19923 W PreKeyMigrationHelper: Migrated one-time prekey: 2363204
06-07 16:40:25.206 19899 19923 I art     : Starting a blocking GC Alloc
06-07 16:40:25.206 19899 19923 I art     : Starting a blocking GC Alloc
06-07 16:40:25.242 19899 19923 I art     : Starting a blocking GC Alloc
06-07 16:40:25.268 19899 19923 I art     : Starting a blocking GC Alloc
06-07 16:40:25.295 19899 19923 I art     : Forcing collection of SoftReferences for 778MB allocation
06-07 16:40:25.295 19899 19923 I art     : Starting a blocking GC Alloc
06-07 16:40:25.317 19899 19923 W art     : Throwing OutOfMemoryError "Failed to allocate a 815909458 byte allocation with 2554394 free bytes and 504MB until OOM"
06-07 16:40:25.319 19899 19923 I art     : Starting a blocking GC Alloc
06-07 16:40:25.319 19899 19923 I art     : Starting a blocking GC Alloc
06-07 16:40:25.325 19899 19923 I art     : Starting a blocking GC Alloc
06-07 16:40:25.342 19899 19923 I art     : Starting a blocking GC Alloc
06-07 16:40:25.371 19899 19923 I art     : Forcing collection of SoftReferences for 778MB allocation
06-07 16:40:25.371 19899 19923 I art     : Starting a blocking GC Alloc
06-07 16:40:25.396 19899 19923 I art     : Starting a blocking GC HomogeneousSpaceCompact
06-07 16:40:25.429 19899 19923 W art     : Throwing OutOfMemoryError "Failed to allocate a 815909458 byte allocation with 2559629 free bytes and 504MB until OOM"
06-07 16:40:25.436 19899 19923 E AndroidRuntime: FATAL EXCEPTION: pool-3-thread-1
06-07 16:40:25.436 19899 19923 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 19899
06-07 16:40:25.436 19899 19923 E AndroidRuntime: java.lang.OutOfMemoryError: Failed to allocate a 815909458 byte allocation with 2559629 free bytes and 504MB until OOM
06-07 16:40:25.436 19899 19923 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.helpers.PreKeyMigrationHelper.readBlob(PreKeyMigrationHelper.java:190)
06-07 16:40:25.436 19899 19923 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.helpers.PreKeyMigrationHelper.loadSerializedRecord(PreKeyMigrationHelper.java:158)
06-07 16:40:25.436 19899 19923 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.helpers.PreKeyMigrationHelper.migratePreKeys(PreKeyMigrationHelper.java:46)
06-07 16:40:25.436 19899 19923 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.helpers.SQLCipherOpenHelper.onUpgrade(SQLCipherOpenHelper.java:141)
06-07 16:40:25.436 19899 19923 E AndroidRuntime: 	at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:173)
06-07 16:40:25.436 19899 19923 E AndroidRuntime: 	at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:227)
06-07 16:40:25.436 19899 19923 E AndroidRuntime: 	at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:214)
06-07 16:40:25.436 19899 19923 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.helpers.SQLCipherOpenHelper.getReadableDatabase(SQLCipherOpenHelper.java:224)
06-07 16:40:25.436 19899 19923 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.SmsDatabase.getExpirationStartedMessages(SmsDatabase.java:668)
06-07 16:40:25.436 19899 19923 E AndroidRuntime: 	at org.thoughtcrime.securesms.service.ExpiringMessageManager$LoadTask.run(ExpiringMessageManager.java:57)
06-07 16:40:25.436 19899 19923 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
06-07 16:40:25.436 19899 19923 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
06-07 16:40:25.436 19899 19923 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
06-07 16:40:25.448  2326  2366 W BroadcastQueue: Skipping deliver [background] BroadcastRecord{ff914e3 u-1 android.net.conn.CONNECTIVITY_CHANGE} to ReceiverList{3406c9d 19899 org.thoughtcrime.securesms/10146/u0 remote:c0b9f74}: process crashing
06-07 16:40:25.449 19899 19930 W MessageRetrievalService: Waiting for websocket state change....
06-07 16:40:25.453 19899 19930 W MessageRetrievalService: Network requirement: false, active activities: 0, push pending: 0, gcm disabled: true`

**Comment by greyson-signal** [comment] 2018-06-08 00:49
Because this was previously associated with a backup-restore ticket, I just wanted to clarify that this issue is actually not related to backup-restore. This looks like a pre-4.20.x issue with the prekey migration.

Specifically, it looks like this is failing [here](https://github.com/signalapp/Signal-Android/blob/master/src/org/thoughtcrime/securesms/database/helpers/PreKeyMigrationHelper.java#L190), which means you either have a legitimately large (~815MB) prekey file, or, more likely, the file is malformed/mis-parsed, and we're misreading the file length.

**Comment by tux2sa** [comment] 2018-06-08 01:31
I may have said the restore wrong.
My database is 200 MB large of Signal and if I go back to the old version (4.14.8 or 4.16.9) it works or opens.

I can upgrade from version 4.14.8 to 4.16.9 but the newer versions lead to this crash.
How can I save the malformed/mis-parsed formatted file to avoid losing my chats and groups?

I'm missing here in Signal a function that completely backed up everything to me not in plain text as it is offered.

Thanks

**Comment by greyson-signal** [comment] 2018-06-08 04:47
@tux2sa Unfortunately I think that you just have a corrupted/malformed file, and that's going to prevent you from upgrading to >= 4.17. There isn't much to be done.

If you're phone is rooted, and you don't mind getting your hands dirty (and given that you're running LineageOS, I'm guessing you are? :wink:), the following steps may help:

1) Force stop Signal.
2) Delete the offending prekey file, which should be in `/data/data/org.thoughtcrime.securesms/prekeys`
3) Perform the app upgrade
4) Go to Settings > "Chats and media" and perform a backup
5) Uninstall and reinstall Signal
6) Restore from your backup

But honestly, I haven't fully tested these steps, and they're just a suggestion. We can't really support this. The only guaranteed path forward is to do a plain 'ol fresh install, but then you'll of course lose your messages.

**Closed by greyson-signal** 2018-06-08 04:47 UTC
