### ISSUE TITLE
Unable to connect to service on Samsung Phones with +94 numbers

### ISSUE THREAD

**Issue by Sebijk** [signalapp/Signal-Android#12927] opened 2023-04-30 13:53 UTC
On Samsung Phones Registration with +94 (Sri Lanka) numbers will not work. It will show the error message: Unable to connect to service. Please check network connection and try again. If i use a german number with +49, registration works.

Debug Log: https://debuglogs.org/android/6.18.4/5a90cb02dc1c01a3e6b968fedd5a446b8b9c2a28abcc2bef792eccbc296183be

**Comment by nicholas-signal** [comment] 2023-05-01 14:57
The 502 represents a failure with the external third party service that actually sends the SMS codes. This can be due to a number of factors, and may be temporary or permanent. In the next release, I'll include clearer messaging so people understand what's going on, as well as more verbose logging.

Once that release is available, may I ask you to try again with the improved logging?

**Comment by Sebijk** [comment] 2023-05-01 17:30
It's a permanent error. I tested this since 20. April with various Samsung Phones with Samsung Stock ROM. Same error. I will provide an improved debug log if new release comes.

**Comment by nicholas-signal** [comment] 2023-05-01 19:19
> It's a permanent error. I tested this since 20. April with various Samsung Phones with Samsung Stock ROM. Same error. I will provide an improved debug log if new release comes.

When I say "permanent", I mean from the sender's side. There could be any number of interruptions to their service that could last for any length of time, and usually they'll tell us if their issues are going to be fixed (temporary) or cannot be fixed (permanent).

**Comment by Sebijk** [comment] 2023-05-09 04:37
Same issue also with 6.19.8 version with 502 error. I wait for the 6.20 with improved logging.

**Comment by Sebijk** [comment] 2023-05-11 11:43
with 6.20.0: https://debuglogs.org/android/6.20.0/9cab632c0f7be9cef865c7f4019571d0c960468904849f3f92a0ff81ea9be098

**Comment by nicholas-signal** [comment] 2023-05-18 15:45
Hello @Sebijk,

Thank you for the logs! It confirms what we suspected: our partner is choosing not to create an SMS for you. We are following up with this local SMS operator in Sri Lanka to try to understand better why SMS sending is often blocked.

**Comment by nicholas-signal** [comment] 2023-07-18 21:08
Hello @Sebijk,

Our provider has informed us that their heuristics have changed recently. Please give it a another try at your convenience.

I am closing this issue here on GitHub, as the problem is at the local operator's level, not the code of the Android app. As always, we welcome discussion and feedback in our community forum: https://community.signalusers.org/

**Closed by nicholas-signal** 2023-07-18 21:08 UTC
Labels: wontfix
