### ISSUE TITLE
Save all media to filesystem

### ISSUE THREAD

**Issue by Argafal** [signalapp/Signal-Android#7939] opened 2018-06-25 17:56 UTC
- [x ] I have searched open and closed issues for duplicates ( #3975 shows the successful implementation)
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The "save all media" button disappeared on my device. My device's screen just broke half-way and I need to switch to a new device. I do not have space on the new device to move 3 gb (sic!) of signal data. I want to save all media from my existing conversations and move them from my (old) phone to my computer. This used to work fine and disappeared in a recent update. I relied on features not suddenly disappearing.

I am a little scared, do I really now need to do this manually for >10000 pictures and videos? Is there a way to default the answer "yes" to the "if you say yes the file will be stored unencrypted" question, instead of answering it 10000 times individually? Why did this feature suddenly and without a heads-up disappear, was something wrong with it (not answered in #5874)? Is there a way to downgrade the app to get it back? How I can I solve this without sitting a whole day and doing the same finger motion thousands and thousands of times?

### Steps to reproduce
- Open a conversation, select the three dots, choose all media
- Expectation: There used to be a double disk icon that saves all media to the file system
- Actual: It's not there anymore and I am desperate to get it back (or to find another workaround).

**Signal version:** 4.19.3

**Comment by greyson-signal** [comment] 2018-09-17 04:41
Closing since this is a feature request. But #7996 exists, so I'm gonna take a look at it when I get a chance.

**Closed by greyson-signal** 2018-09-17 04:41 UTC

**Comment by PiCob** [comment] 2018-09-17 14:34
Don't want to start a discussion here, but like the OP already mentioned that this "used to work fine and disappeared in a recent update". So unless I have a distorted understanding of feature requests, this isn't really a feature request, but a regression introduced by https://github.com/signalapp/Signal-Android/commit/020e5b22ebff279c40773b2bd64b570030c9c81f#diff-978497c8da0623480ac14da5b105d5fbL124.

**Comment by Argafal** [comment] 2018-09-17 15:01
PiCob, yes indeed, regression as per your reference. Glad to see there is patch to restore the functionality, super! Can't wait to get this back and finally migrate my device from Android 4.4.4 (sic) to 8.0. :)
