### ISSUE TITLE
Unable to share images from gallery to Signal

### ISSUE THREAD

**Issue by vincentvikram** [signalapp/Signal-Android#9270] opened 2019-12-11 12:38 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Unable to share images from gallery to Signal

### Steps to reproduce
- select an image or object within phone gallery
- select the share icon
- select the Signal app
- select a user or 'note to self' from the 'share with' menu
- either type or don't type message
- select blue send button

**Actual result:** no action. the share screen repeats itself without posting the selected image to the destination. The 'back' button does not allow me to exit the screen. I need to manually close the Signal app and restart.
**Expected result:** The image should be sent to the destination account along with a confirmation
### Device info

**Device:** OnePlus GM1901
**Android version:** 10.0.0
**Signal version:** 4.51.6

### Link to debug log

https://debuglogs.org/328f77695a7d18466904a26aad8b5e0fd7da14bcf08ac46218d33e4ec3447413

**Comment by Rushi98** [comment] 2020-01-15 07:55
This happens only when Signal is locked and not when it is unlocked. I have observed following behaviour.
# Locked Signal
1. Share with Signal (from G Photos)
2. Signal Unlock screen appears
3. Unlock Signal
4. Signal closes. G Photos is displayed again.

# Unlocked Signal
1. Share with Signal (from G Photos)
2. Signal opens asking to choose contacts and message
3. Signal conversation screen appears showing send progress
4. The picture is sent successfully as expected

**Comment by Rushi98** [comment] 2020-01-15 09:48
This is probably duplicate of #3990

**Comment by digital-idiot** [comment] 2021-01-02 10:52
I have also encountered this bug.

**Comment by fduraibi** [comment] 2022-01-03 07:18
I also have this issue, not sure if the app is crashing as in #3990 since it remains unlocked. I assume if the app crashed and restarted it will become locked again.

Oneplus 7 Pro
Android 11

**Closed** 2022-03-11 09:03 UTC
Labels: wontfix

**Comment by noClaps** [comment] 2023-03-05 11:40
> This happens only when Signal is locked and not when it is unlocked. I have observed following behaviour.
> 
> # Locked Signal
> 1. Share with Signal (from G Photos)
> 2. Signal Unlock screen appears
> 3. Unlock Signal
> 4. Signal closes. G Photos is displayed again.
> 
> # Unlocked Signal
> 1. Share with Signal (from G Photos)
> 2. Signal opens asking to choose contacts and message
> 3. Signal conversation screen appears showing send progress
> 4. The picture is sent successfully as expected
> 
> # Device Info
> Device: Moto G5S Plus Android version: 8.1.0 Signal version: 4.52.4

I see this in Signal 6.13.6 too.
