### ISSUE TITLE
Disappeared images appending to other chat

### ISSUE THREAD

**Issue by Hour-Boss1310** [signalapp/Signal-Android#11037] opened 2021-02-26 10:57 UTC
- [x ] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

this has happened a number of times, in the same group chat (3 people)
( most recently immediately prior to the above logs)

- (A) sends an image
- My received message from (A) shows 2 pictures - the one sent by (A) and another
- the other image was previously received by me in a now-disappeared message from another sender.
- I send a text only
- all chat participants see an image attached to the text ( including me)
- the other image was previously received in a now-disappeared message from another sender
- I send a text only
- all chat participants see an image attached to the text ( including me)
- the other image was previously received in a now-disappeared message from another sender

the second time it happened - same chat group

- I send a picture
- (A)'s received message shows 2 pictures - the one sent and another
- the other image was previously received by (A) in a now-disappeared message from another sender.
- Both (A) and I have Huawei phones, person (B) has an Apple

### Screenshots
https://imgur.com/a/aX8Zeb8

### Device info

**Device:** Huawei ANE-LX1
**Android version:** 9.1.0.374
**Signal version:** 5.4.7

### Link to debug log
sender : message ID 1614331991684 - one image sent https://debuglogs.org/ac171358ebe41b7470bb30770b0383d3630e19d6853808a25331cc15e79f4af5

recipient : message ID 1614331991684 - two images 'received'
https://debuglogs.org/635cfbfd47631037a99c22f68b5cedb6a2896d18e0be81e7da1750b14fb00b0e

**Comment by andrewazores** [comment] 2021-05-08 22:25
I have what seems to be the same problem, although I think I have only observed it within one chat. However that's also the one contact that the majority of my Signal messages go to/come from. It only happens when I'm using my Android phone (Galaxy S10e) and not when I use any of my linked desktop clients.

@Hour-Boss1310 did you have a link to a bug report or other discussion on ex. the Signal user forums, since there has been no feedback here?

**Comment by Hour-Boss1310** [comment] 2021-05-09 10:42
apologies - I was just about to post the link.

To be honest I have had zero acknowledgment of what is a massive flaw, and if you are observing the same problem it only confirms the issue.

The images that were supposed to have 'disappeared' obviously still exist - and for them to be sent to random contacts is dangerous and could have massive consequences.

I have posted screenshots of the issue being replicated and submitted debug logs.

I have stopped using Signal - I cant trust it and the fact that I have had no response only makes me more suspicious.

**Comment by Hour-Boss1310** [comment] 2021-06-16 07:59
reopened issue - as maybe helpful to anyone else experiencing the problem to know of its existence.

**Comment by eater** [comment] 2021-07-14 17:06
This happened for me yesterday. My colleagues and I are immediately ceasing our use of Signal as a result.

**Comment by Hour-Boss1310** [comment] 2021-07-15 05:43
> This happened for me yesterday. My colleagues and I are immediately ceasing our use of Signal as a result.

what make / model of handset did you experience the issue on?

**Comment by eater** [comment] 2021-07-15 13:46
It's a Motorola Moto E. I created a debug log as soon as I learned that it was possible to create a debug log, but it looks like the log only shows the day after the incident (which happened 2021-07-13 22:08 EDT). Still maybe there's some useful info : 
https://debuglogs.org/7481a680b0b2e177a97ce476e622618fa708ad4d543fd5532db0d13096adbe3e

**Comment by greyson-signal** [comment] 2021-07-15 14:25
We've been trying to figure out what could have happened, but unfortunately with so few cases of this being reported and us being unable to reproduce the issue, it took a while. But we think we finally have an idea as to the types of corner cases that could result in this happening, and have fixes that will go out in 5.17.

**Comment by Hour-Boss1310** [comment] 2021-07-15 14:56
I was able to consistently replicate the issue and was happy to share logs and screenshots.
I posted here, on the Signal Community and on Reddit.

Unfortunately as  nobody acknowledged there was a problem I ditched the handset and have stopped using Signal as I don't trust it.

Hopefully the fix works !

good luck.

**Comment by greyson-signal** [comment] 2021-07-25 18:53
Hi, this should be fixed in 5.17

**Closed by greyson-signal** 2021-07-25 18:53 UTC
