### ISSUE TITLE
Crash while forwarding video

### ISSUE THREAD

**Issue by dcherian** [signalapp/Signal-Android#8043] opened 2018-07-27 17:50 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

Not sure if this is a duplicate of https://github.com/signalapp/Signal-Android/issues/8042
### Bug description
Signal crashes while forwarding video from MMS group to Signal group.

### Steps to reproduce
- Select video,
- Hit forward button
- Search for group and tap

(This happens every time)

### Device info

**Device:** Nokia 6.1
**Android version:** 8.1.0
**Signal version:** 4.24.4

### Link to debug log
https://debuglogs.org/0bffec469f538b2c3fdd7be6b8dcf4e9e3cb4401672a3a07612bcae4a13b8d69

**Comment by greyson-signal** [comment] 2018-07-27 20:08
Yeah, this is a dupe of #8042. Apologies! It'll be fixed in the next release.

**Closed by greyson-signal** 2018-07-27 20:08 UTC
