### ISSUE TITLE
Screen lock inactivity timeout

### ISSUE THREAD

**Issue by akshayd002** [signalapp/Signal-Android#10425] opened 2021-01-10 05:19 UTC
Yes this one is good. But please give immediately option also. Every time only user should give the lock signal.
So do update this one

**Comment by AliabbasMerchant** [comment] 2021-01-11 07:35
Duplicate of #10424 (We should close this and shift to that, as much more discussions have taken place there)

**Closed** 2022-02-03 11:25 UTC
Labels: wontfix
