### ISSUE TITLE
Signal trims first second of video sent

### ISSUE THREAD

**Issue by diogodh** [signalapp/Signal-Android#9359] opened 2020-01-22 16:49 UTC
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I send a video in signal for android, it trims / cuts the firts +-500ms of the video.

### Steps to reproduce
Send any video from a file in the smartphone. 

**Actual result:** After sent, watch it and it will miss the first miliseconds (+-500ms)

**Expected result:** After sent, watch it and it would show the entire lenght of the video

### Device info
**Device:** OnePlus 6
**Android version:** 10
**Signal version:** 4.53.7

**Comment by frankvollebregt** [comment] 2020-03-11 12:19
I am unable to reproduce this on my own smartphone

## Device info
**Device:** Xiaomi Mi A2
**Android version:** 10
**Signal version**: 4.57.0

So unless it was fixed in an in-between update, the issue may be device specific.

**Comment by frankvollebregt** [comment] 2020-03-11 12:22
Tested it on another device, where I cannot reproduce it either

### Device info
**Device:** Oneplus 7T Pro
**Android version: ** 10
**Signal version:** 4.56.4

**Closed** 2022-02-04 02:04 UTC
Labels: wontfix
