### ISSUE TITLE
No active call info

### ISSUE THREAD

**Issue by Trojgarb** [signalapp/Signal-Android#9516] opened 2020-04-02 12:25 UTC
### Bug description

If a caller switches to another app while having active Signal voice/video connection there is no info on the status bar that the call is still active. The only way to disconnect is to switch back to Signal, choose the contact's thread and then click on phone call icon. That restores active connection screen with red button to disconnet. If someone forgets about having audio conversation, the connection is still active in the background, so be careful!

### Steps to reproduce

Make an audio/video call

**Expected result:** 

There should be notification in status bar showing active call, possibly with info about caller and buttons to mute and disconnect the call.

### Device info
**Device:** Motorola X Force
**Android version:** 7.0
**Signal version:** 4.58.5

**Comment by Mat3oo** [comment] 2020-04-05 18:04
Duplicate of #9414

**Comment by ozgurakyazi** [comment] 2020-04-05 18:49
@Trojgarb you can see the version number in Settings>Advanced.

**Comment by Trojgarb** [comment] 2020-04-06 06:03
@ozgurakyazi Thank you. I have complemented the version number.

**Closed** 2020-05-14 14:31 UTC
