### ISSUE TITLE
Issues with mms and project fi

### ISSUE THREAD

**Issue by GadgetTech** [signalapp/Signal-Android#3644] opened 2015-07-13 16:52 UTC
Hello, I am a long time users of text secure and recently got my invite to project fi from Google.  When using it on a nexus 6 I can send mms to certain people and others it simply won't work.  Non of them are using the encrypted client and I've tried on WiFi and cellular without a different resault...  I've included the URL to the debug file.  Thank you in advance.https://gist.github.com/26cb4701cef131177d4e

**Comment by rm-you** [comment] 2015-10-18 22:36
I believe I have the same issue. I can't send Pictures in messages, though the most pain is lack of group message support (either Conversation mode, or Broadcast), since it uses MMS. Toggling Wifi Calling support in settings doesn't seem to matter. Google Fi hides all APN settings as well, so I don't know that I can try any solutions that involve APN tweaks. Very frustrating. :(

**Comment by GadgetTech** [comment] 2015-10-19 00:46
Interesting, that's probably the reason, if they cant get the APN settings from them its hard to make everything work.  It is because I'm back to using hangouts...  I hope we can get some traction on this at some point.

**Comment by rm-you** [comment] 2015-10-19 06:11
Might be a duplicate of: https://github.com/WhisperSystems/TextSecure/issues/4131

Try switching manually to T-Mobile (can use Fi Spy or find the dialer code online somewhere). I am able to send on TMO but not Sprint, per that issue.

**Comment by rm-you** [comment] 2015-10-19 06:13
Looking at your log it seems this is the same issue -- getting the Authentication Required response from the MMS server with Sprint. Try when you are forced onto T-Mobile and I bet it will work.

**Comment by Tweakyth13f** [comment] 2015-11-06 20:29
Having this exact issue. When one Sprint LTE, I cannot send a photo via even the update Signal (even with the wifi compatibility toggled). Using Fi Spy to force myself to Tmobile, it worked without issue. I'm on a 16GB Nexus 5X.

**Comment by peteyblueeyes** [comment] 2015-12-17 17:57
I did some digging in my debug logs. Like most of you, I determined that the problem arises when I'm on Sprint's network but that I can send MMS just fine when on T-Mobile's network.

I spent a little while on email and on the phone with Project Fi and Google support. The answer I got was that the app is "not supported" on Sprint's network. It's impossible for me to tell if that means that Signal needs to be tested more extensively on Sprint's network or if Sprint is failing to support the protocol properly (which could be worked around) or if Sprint is actively suppressing traffic from some applications.

**Comment by matthewdavis** [comment] 2015-12-18 15:45
Issue 4131 is related to this and seems to have more relevant info.

https://github.com/WhisperSystems/Signal-Android/issues/4131

**Comment by evantd** [comment] 2017-06-22 01:08
#4131 has been resolved **and** [more changes](https://github.com/WhisperSystems/Signal-Android/commits/master/src/org/thoughtcrime/securesms/mms/CompatMmsConnection.java) were made in May 2017 that may have resolved this issue. Is it still a problem for you?

**Comment by peteyblueeyes** [comment] 2017-06-22 15:48
I lurked on #4131 for a while and a fix came through the Play Store not long after it wrapped up that fixed things. The problem was always intermittent, so it's hard to say; I haven't sent many insecure MMS since the latest changes to <a href="https://github.com/WhisperSystems/Signal-Android/commits/master/src/org/thoughtcrime/securesms/mms/CompatMmsConnection.java">CompatMmsConnection.java</a> (May 24 2017) but I have sent a few and they've all worked. So although one can never be certain about the absence of an intermittent problem, I'd say we're good to go.

**Comment by automated-signal** [comment] 2018-04-02 21:41
GitHub Issue Cleanup:
See #7598 for more information.

**Closed by automated-signal** 2018-04-02 21:41 UTC
Labels: mms
