### ISSUE TITLE
No message counter on Galaxy Note 9

### ISSUE THREAD

**Issue by mrHJS** [signalapp/Signal-Android#8216] opened 2018-09-21 15:02 UTC
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
On my Note 9 Signal in its latest version does not show the message counter of new messages on the icon although this function is explicitly enabled in the Note 9's functions. Other apps show the badge counter normally such like Whatsapp, E-Mail, Messages etc.

### Steps to reproduce
- Install Signal on Note 9
- Receive a message
- Notification is shown in status bar but no message counter appears

### Device info
**Device:** Samsung Galaxy Note 9
**Android version:** 8.1.0
**Signal version:** 4.25.10

**Comment by greyson-signal** [comment] 2018-09-21 15:48
Dupe of #7580. Thanks!

**Closed by greyson-signal** 2018-09-21 15:48 UTC
