### ISSUE TITLE
Not Receiving any message on signal Now , Only able to Send Messages 

### ISSUE THREAD

**Issue by abhinand2608** [signalapp/Signal-Android#12988] opened 2023-06-08 19:06 UTC
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by clark-signal** [comment] 2023-06-09 15:34
Hi, it would help to know your version number, but a similar issue has been fixed in 6.22.7 and 6.23.1

**Comment by Meteor0id** [comment] 2023-06-09 16:03
Likely duplicate of https://github.com/signalapp/Signal-Android/issues/12984

**Comment by fr1sty** [comment] 2023-06-09 18:27
Started for me today also. Running version 6.22.5. Signal desktop was still functioning. Then I found a 6.23.0 version installed that one, problem on Android didn't change. Only thing is that my desktop version is only able to send messages when I restart the client after sending a message. 
Cannot find version 6.23.1 mentioned above.

**Comment by cody-signal** [comment] 2023-06-09 19:50
6.23.1 will be out soon

**Comment by fr1sty** [comment] 2023-06-10 06:42
Thanks installing 6.23.1 fixed it for me indeed!

**Closed** 2023-09-23 14:50 UTC
Labels: wontfix
