### ISSUE TITLE
SQLiteConstraintException when restoring backup

### ISSUE THREAD

**Issue by bjacquin** [signalapp/Signal-Android#12051] opened 2022-03-09 22:21 UTC
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------
### Bug description
I am unable to restore a backup created using Signal 5.33.1. The following error can be observed using `adb logcat`:

### Steps to reproduce
- create a backup with Signal 5.33.1
- transfer backup file between phones using adb pull and adb push
- restore backup file to Signal 5.33.1
- enter backup passphrase

**Actual result:** Signal closes abruptly without completing the backup restoration
**Expected result:** Signal should be completing the restoration successfully.

### Screenshots
N/A

### Device info
**Device:** OnePlus 9 Pro
**Android version:** 11
**Signal version:** 5.33.1

### Link to debug log
```
03-09 22:14:31.894 15928 21268 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
03-09 22:14:31.894 15928 21268 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 15928
03-09 22:14:31.894 15928 21268 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
03-09 22:14:31.894 15928 21268 E AndroidRuntime: 	at android.os.AsyncTask$4.done(AsyncTask.java:415)
03-09 22:14:31.894 15928 21268 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
03-09 22:14:31.894 15928 21268 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
03-09 22:14:31.894 15928 21268 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
03-09 22:14:31.894 15928 21268 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
03-09 22:14:31.894 15928 21268 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
03-09 22:14:31.894 15928 21268 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
03-09 22:14:31.894 15928 21268 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:923)
03-09 22:14:31.894 15928 21268 E AndroidRuntime: Caused by: net.zetetic.database.sqlcipher.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787)
03-09 22:14:31.894 15928 21268 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
03-09 22:14:31.894 15928 21268 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:767)
03-09 22:14:31.894 15928 21268 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:758)
03-09 22:14:31.894 15928 21268 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:70)
03-09 22:14:31.894 15928 21268 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteDatabase.executeSql(SQLiteDatabase.java:1994)
03-09 22:14:31.894 15928 21268 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteDatabase.execSQL(SQLiteDatabase.java:1901)
03-09 22:14:31.894 15928 21268 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.dropAllTables(FullBackupImporter.java:281)
03-09 22:14:31.894 15928 21268 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:94)
03-09 22:14:31.894 15928 21268 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:77)
03-09 22:14:31.894 15928 21268 E AndroidRuntime: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:291)
03-09 22:14:31.894 15928 21268 E AndroidRuntime: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:282)
03-09 22:14:31.894 15928 21268 E AndroidRuntime: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
03-09 22:14:31.894 15928 21268 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
03-09 22:14:31.894 15928 21268 E AndroidRuntime: 	... 4 more
```

**Comment by elitistphoenix** [comment] 2022-03-09 23:42
I have the same issue and believe is related to issue #12048 too

**Comment by TheLastGimbus** [comment] 2022-03-10 01:46
Can you guys fix this??? I wasted 4 hours trying to fix it ;_;

**Comment by TheLastGimbus** [comment] 2022-03-10 13:22
@greyson-signal could you please take a look :pray: :sob:

**Comment by alex-signal** [comment] 2022-03-10 13:38
Duplicate of #12048

**Closed by alex-signal** 2022-03-10 13:38 UTC
