### ISSUE TITLE
Does not warn if SMS permission gets disabled when it's default SMS app

### ISSUE THREAD

**Issue by Fregf** [signalapp/Signal-Android#8503] opened 2019-01-03 18:01 UTC
### Bug description
I upgraded LineageOS 15.1 to a newer build, and because of that, all permissions of apps where lost. Signal was set as default app for receiving SMS. However, at no time it asked me access again access to SMS. It looks like all SMS sent during this period, got lost. I had to enable it manually again, then I started receiving messages again.

### Steps to reproduce
- Set Signal as default SMS app via its Settings - SMS and MMS 
- go to Android Settings - Apps - Signal - Permissions
- disable SMS permission

**Actual result:** Signal does not give you any warning that the SMS permission is missing. SMS do not arrive at all any more.
**Expected result:** Signal warns you (at least when you open it) that it's missing the permission while it's set as default SMS app.

**Comment by djcass44** [comment] 2019-01-04 09:57
I was going to have a go at fixing this, however the only method I could find to check the default SMS app requires API19 ([getDefaultSmsPackage](https://developer.android.com/reference/android/provider/Telephony.Sms.html#getDefaultSmsPackage(android.content.Context))). 
Considering Signal's minimum API is 14, are we able to implement this? Would implementing this only for devices which support API >= 19 be acceptable?

**Comment by five-c-d** [comment] 2019-01-07 14:41
@djcass44 , you are on the right track methinks, and there is already a utility-function implemented in the code which calls the method you are talking about == https://github.com/signalapp/Signal-Android/blob/f9d7cf0e1900d4f32c92eebf0f6828b4c376ce70/src/org/thoughtcrime/securesms/util/Util.java#L344 , it was added back in the Android 4.4 aka api 19 era == https://github.com/signalapp/Signal-Android/pull/425 

It looks like you would want to add a call to that isDefaultSmsProvider(context) method over in the onSend() method for SMS here, https://github.com/signalapp/Signal-Android/blob/be215b3b1e7e5751d1a2317cf6d77c5ae79fb9ac/src/org/thoughtcrime/securesms/jobs/SmsSendJob.java#L79 , plus presumably(?) also in the slightly-different onSend() method for MMS here, https://github.com/signalapp/Signal-Android/blob/1f9a65e389e5e356d8c6217e7db74832ff3adb2e/src/org/thoughtcrime/securesms/jobs/MmsSendJob.java#L90 

Doing that check ought to prevent any SMS/MMS from 'trying' to be sent, if permission has been revoked or signal4android has otherwise been removed as the default-sms-integration app for whatever reason.  I'm not sure what UX is desired here, when the failure is detected:  if the user tries to send an SMS/MMS when the permission is off, presumably we want to dynamically prompt them to enable it, on android versions that permit that (6.0+ methinks).  However, what if the enduser has purposely given another app the default-sms role, and wants to leave it thataway... is there any way for signalapp to "send a draft message over to the default sms app" via the system clipboard or whatever?  Or perhaps that is overly complex  :-) 

As for the suggestion that signal4android ought to **always** popup a banner (at app-launch) reminding the enduser 'signal is no longer the default sms provider would you like to enable sms integration again please please please?'  ...that seems like overkill to me  ;-)   When you first install signal4android, it asks you if you want to enable sms integration, but if you say no, it does not bother you about it again... until and unless you attempt to send a signal message which fails to go through and attempt to perform a fallback to unencrypted sms... at which point you are dynamically prompted to enable sms-integration.  Or similarly, if you punch in the digits of a contact who is not registered with signal-server, you can either enable sms-integration to invite-them-to-signalapp, or switch modalities and call them via unencrypted telco (or email them or speak to them face-to-face or whatever).  Point being, I think it makes more sense to just prompt the enduser when they attempt to utilize SMS-integration.  

But the downside here, is that if the enduser enabled SMS-integration, and then a bug in their device-update-and-upgrade process (unwanted permissions-reset) causes signalapp to *lose* SMS-integration and **no** other app to gain it, incoming SMS will be lost to that big bitbucket in the sky... if I'm understanding correctly, at least.  Or maybe the permissions-reset will re-enable the stock SMS app to receive those correctly?  Adding the just-in-case check when trying to send an outgoing SMS is a good belt-n-suspenders idea, methinks:  it prevents the enduser from thinking they sent something, which in reality never went out.  But as for alerting them that signalapp has 'lost' the SMS-integration permission... so that they will be able to receive incoming SMS/MMS properly... that is a bit harder for me to see what the 'correct' UX behavior ought to be.  

There is a forum-thread already about somebody running LineageOS on a Samsung GT-I9505, https://community.signalusers.org/t/sms-are-not-being-sent/5495/7 , that I suspect (but have not confirmed) ran into this same 8503 bug due to a LineageOS update/upgrade.  So, because LineageOS is 'officially unsupported' here in github, maybe we ought to move the discussion of how to write a pull-request that fixes signal4android when SMS-integration permissions suddenly disappear, over there?  

But I would argue for keeping this bug-report open here on github, because in addition to LineageOS having problems with android-permission-resets, there are also certain stock android ROMs from the 2016/2017 timeframe which had similar kinds of difficulties (either permissions-reset when the phone is turned off or when an over-the-air upgrade is received or both).  For example, motorola droid turbo 2, htc m8, motorola g4, <a href="https://forums.androidcentral.com/android-6-0-marshmallow/690856-how-do-i-fix-app-permissions-resetting-after-phone-restart.html">maybe others</a> turned up in a quick googling.  Those were stock android 6.x ROMs, so although it is fairly rare in the wild, there are definitely 'officially supported' android devices that would manifest this same kind of SMS/MMS unreliability -- fixing the lack of isDefaultSmsProvider during the onSend code, would be helpful to those specific stock devices, as well as to LineageOS endusers.

**Comment by Fregf** [comment] 2019-01-07 15:47
[quote]As for the suggestion that signal4android ought to always popup a banner (at app-launch) reminding the enduser 'signal is no longer the default sms provider would you like to enable sms integration again please?[/quote]

No, this is not the suggestion. There are two different things here: Signal being set as default SMS app, and Signal not having SMS access permissions. Only when both conditions are valid, there should be a message. Always, because this is a completely broken configuration and will lead to SMS messages sent to you, not arriving at all and getting lost. if Signal is default SMS app, it always needs to have SMS permissions. Also note that this situation is not necessarily the result of an OS bug: the user can easily by accident trigger this situation by retracting the SMS permission while Signal is default SMS app.

**Comment by djcass44** [comment] 2019-01-07 20:13
Just to reinforce what @Fregf said... 

* Signal as default SMS provider + no SMS permissions = user will be unable to send/receive SMSs

* The popup should show as often as possible to inform the user that they MUST provide the permission or remove Signal as the SMS app otherwise they will be unable to send/receive SMSs

I would like to take this issue, I'm not sure if I need to be assigned or if I just submit my PR when ready... But I figured I would mention it just so no one else does duplicate work by accident.

**Comment by five-c-d** [comment] 2019-01-07 23:58
@Fregf thanks for helping correct my misconception... I assumed that being the default SMS provider was tied to having those permissions, but see now that I was wrong!  Note the 2019+ policy below in the postscript, however, seems like google is forcibly trying to make me "correct" retroactively, by removing non-compliant apps from playStore.  

@djcass44 there is no restriction on writing and submitting PR work, low bureaucracy level here, but there **is** a fairly low success-rate:  people spend hours or months working on code which is then rejected.  So it depends on your gumption-level, basically  ;-)   If you are okay with doing a "ton" of work, by some measure of tonnage, and risking it NOT being merged, then please go for it.  

Worst that can happen is you solve it for your own signal-android APK, and it is not merged upstream 'at this time'.  Or that you never quite solve it, but maybe your attempt helps somebody down the line.  You should follow the coding-styleguide, and be ready to sign the CLA which assigns copyright for dual-licensing purposes, and all the other stuff == https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md#pull-requests 

To improve the chances of being merged, though, I strongly suggest opening a forum-thread over at community.signalUsers.com with our feature-upgrade-slash-bugfix suggestion.  You can login there using your github credentials, if you like.  There are plenty of folks at signalUsers that will have design-ideas for how to best handle all the situations that may arise:  

*  android 4.4+, is default sms provider, has sms perms == normal
*  android 4.4+, not default sms provider, no sms perms == "iosMode" (non-default)
*  android 4.4+, is default sms provider, no sms perms == BAD
*  android 4.x, default sms provider unknown, no sms perms == BAD-or-iosMode 
*  android 4.4+, not default sms provider, has sms perms == notSure?
*  android 4.x, default sms provider unknown, has sms perms == normal-or-notSure? 

Maybe there are some undocumented API calls on 4.0 / 4.1 / 4.2 / 4.3 versions of android, that will permit us to determine what the default sms provider is?  Hints that such might exist were sprinkled here == https://android-developers.googleblog.com/2013/10/getting-your-sms-apps-ready-for-kitkat.html   Also, at a more granular level, what should happen if the user disables only some of the SMS-related perms, such as leaving signalapp as the default SMS provider, but turning off permissions for (just) RECEIVE_WAP_PUSH and RECEIVE_MMS, but leaving the others on?  

Once you have made some initial posts to SignalUsers explaining your design and your strategy for handling each of the sub-cases and sub-sub-cases in terms of UI/UX, we can ping Greyson who is the tip of the spear for android-commits nowadays, and do an informal design-review.  If everything looks peachy, you can then put together a proper PR and do a full-blown code review when it is baked.  

p.s.  Still not 100% positive whether these are corner-cases which are 'ignored by design' or count as actual bugs that need fixing (as opposed to feature-requests that would improve things despite not being classified as Bugs per se).  The idea that android endusers on certain kinds of stock systems could mess with permissions "for privacy" and end up making their SMS/MMS fail, is probably worthy of buggy-ness methinks.  And there are stock systems which apparently have buggy vendor-provided-stock-android-ROMs, also, which is not really signalapp's fault of course, but seems to be something we CAN help endusers out with. 

p.p.s.  Seems related to this effort == https://www.xda-developers.com/google-play-developer-policy-call-log-sms/ and the corresponding https://support.google.com/googleplay/android-developer/answer/9047303#intended&exceptions&invalid&alternatives& helpdoc.  Up until 2019, android did NOT demand that apps which were NOT the default sms provider, give up the associate SMS-and-MMS permissions... but henceforth they will be, if I'm reading correctly.  Furthermore, it looks like google will be retroactively removing apps from the playstore which fail to follow the 2019+ policy, which ought to simplify our corner-cases: 

*  android 4.4+, is default sms provider, has sms perms == normal
*  android 4.4+, not default sms provider, no sms perms == "iosMode" (non-default)
*  <s>android 4.4+, is default sms provider, no sms perms == BAD</s>
*  <ins>android 4.x</ins>(??), default sms provider unknown, no sms perms == BAD-or-iosMode 
*  <s>android 4.4+, not default sms provider, has sms perms == notSure?</s>
*  <ins>android 4.x</ins>(??), default sms provider unknown, has sms perms == normal-or-notSure? 

Does signal4android actually try to even *become* the "default SMS provider" on android version prior to 4.4 when the isDefaultSmsProvider stuff was finalized?

**Comment by mryellow** [comment] 2019-01-13 19:49
The SMS replacement integration on Android causes many UX issues.

https://github.com/signalapp/Signal-Android/issues/274
https://github.com/signalapp/Signal-Android/issues/845
https://github.com/signalapp/Signal-Android/issues/2285
https://github.com/signalapp/Signal-Android/issues/4932
https://github.com/signalapp/Signal-Android/issues/5293
https://github.com/signalapp/Signal-Android/issues/5386
https://github.com/signalapp/Signal-Android/issues/5481
https://github.com/signalapp/Signal-Android/issues/5563
https://github.com/signalapp/Signal-Android/issues/5565
https://github.com/signalapp/Signal-Android/issues/5719
https://github.com/signalapp/Signal-Android/issues/5858
https://github.com/signalapp/Signal-Android/issues/6771
https://github.com/signalapp/Signal-Android/issues/6718
https://github.com/signalapp/Signal-Android/issues/6912
https://github.com/signalapp/Signal-Android/issues/7116

**Comment by labanskoller** [comment] 2019-08-13 00:51
A few days ago my husband said he didn't receive text messages anymore. He noticed because he didn't get a message which was sent to multiple recipients. He asked me for help and I found out that Signal was the default SMS handling app but didn't have the SMS permission anymore. He doesn't remember changing that recently but he's not 100% sure so I don't know if he did a permission cleanup or if some upgrade caused it. He's using the stock Android from Samsung.

I really think this is a bug. I agree it shouldn't be possible to route all incoming text messages to "/dev/null" by mistake (or deliberately for that matter). Signal shall warn (at least at start-up) if it's the default app for SMS but lack the SMS permission(s).

**Comment by mryellow** [comment] 2022-01-28 22:52
Bump.

**Closed** 2022-04-06 04:20 UTC
Labels: wontfix
