### ISSUE TITLE
I suggest  hide phone number or register with email

### ISSUE THREAD

**Issue by weweyes** [signalapp/Signal-Android#10350] opened 2021-01-03 12:49 UTC
I suggest  hide phone number or register with email

**Comment by Cerberus0** [comment] 2021-01-04 02:09
Hi @weweyes,

Please note that this issue tracker is [only meant for bug reports](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md#issues). Bug reports should only be submitted for existing functionality that does not work as intended. This is not the right place for questions, comments, or feature requests, as stated in the project's [CONTRIBUTING.md](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md) and [issue template](https://raw.githubusercontent.com/signalapp/Signal-Android/master/.github/ISSUE_TEMPLATE.md). I suggest moving this discussion over to the [community forum](https://community.signalusers.org/). Thanks!

**Closed** 2021-01-04 17:38 UTC
