### ISSUE TITLE
Export all media from all conversations

### ISSUE THREAD

**Issue by dschrempf** [signalapp/Signal-Android#6539] opened 2017-04-17 19:16 UTC
Hello,

it would be nice to be able to export all media from all conversations.

This is especially useful, when moving media from the phone to a computer or when Signal has to be reinstalled for whatever reason.  At the moment I have to go through all my conversations one by one.  I do not need an encrypted backup nor do I want to reimport the exported media.

**Comment by nrizzio** [comment] 2017-04-17 19:21
I think this is a duplicate of #1619. You can add a "thumbs up" to that issue to show support for its implementation.

**Comment by dschrempf** [comment] 2017-04-17 19:30
Hm thanks for the reference, you may be right.  However, I was not thinking about an XML backup.  For me it is more than enough (and actually even better) to have a normal export so that all images are saved into one folder and all movies into another.  In case this is really a duplicate, please feel free to close this issue.

**Comment by ChimeraCoder** [comment] 2017-12-31 01:57
To add some context to this, it's *incredibly* useful when getting a new phone - there really isn't any other way to preserve the media on the old phone, except to go through every conversation manually, which isn't really an option for people who use Signal frequently.

**Comment by santa-klaus** [comment] 2018-01-24 15:33
I is also a absolutely key feature for people who have old/cheap phones with little memory, because all media is saved together with the app on the internal memory. This fills up the memory really fast, so it would be cool to export various/all media to be able to clear the space.

**Comment by automated-signal** [comment] 2018-04-03 02:33
GitHub Issue Cleanup:
See #7598 for more information.

**Closed by automated-signal** 2018-04-03 02:33 UTC
