### ISSUE TITLE
Can't listen to new voice message after listening to a few others

### ISSUE THREAD

**Issue by lk251** [signalapp/Signal-Android#9974] opened 2020-08-29 16:37 UTC
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Can't listen to new voice message after listening to a few others previously.

### Steps to reproduce
- To a few (a couple or more) incoming voice messages
- Listen to a new one
**Actual result:** 
- Error message ""Fehler bei der Audiowiedergabe", and can't listen to the audio.

**Expected result:**
- Can listen to any and all voice messages

### Screenshots
NA

### Device info
**Device:** Sony Xperia Modell F3311
**Android version:** Android Version 6.0
**Signal version:** Signal 4.69.4

### Link to debug log

Will post ASAP

**Comment by alan-signal** [comment] 2020-08-31 13:51
Logs would really help track this down.

Instructions for how to capture logs for us can be found here: https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports

**Comment by davidak** [comment] 2020-11-07 21:57
duplicate of https://github.com/signalapp/Signal-Android/issues/8487

**Closed** 2022-02-03 16:52 UTC
Labels: wontfix
