### ISSUE TITLE
Sent image previews not fully showing

### ISSUE THREAD

**Issue by sybercorp** [signalapp/Signal-Android#9889] opened 2020-07-30 20:16 UTC
When I send pictures through Signal, some of the previews that show in the conversation don't show fully (see the included screenshot of what it looks like).  Tapping on the image opens it up properly, and the recipient has no issues viewing the picture.  This has been happening for quite a long time but I keep holding out hope it'll be patched. Since it hasn't been, I'm making sure it's at least mentioned.

![Screenshot_20200730-161225.jpg](https://user-images.githubusercontent.com/17321398/88970174-f3221c80-d27f-11ea-897c-5f3f53185596.jpg)

[Debug Logs](https://debuglogs.org/8c92b420697281f18c8255bc2161b0d976b2d4da937ee08e4566bc4441f1d1e6)

**Comment by Nisc3d** [comment] 2020-07-31 01:50
This is a duplicate of #9082.

**Comment by sybercorp** [comment] 2020-07-31 01:54
They may be very similar but I don't feel this is a duplicate since I get the same result without editing the photos.  I don't touch the crop tool, specifically, and just attach the picture as it exists in my photo library.

**Comment by Nisc3d** [comment] 2020-07-31 01:57
Alright, I don't know how the devs handle it. I opened the same issue a while back and it got closed, because it was a duplicate. But at least these issues are now linked.

**Comment by sybercorp** [comment] 2020-07-31 01:59
@Nisc3d That's fair. Hopefully one day they actually fix it since it's existed for a while.

**Comment by greyson-signal** [comment] 2020-07-31 14:08
Closing as a duplicate of #9082

**Closed by greyson-signal** 2020-07-31 14:08 UTC

**Comment by sybercorp** [comment] 2020-07-31 14:11
@greyson-signal So, even though I still disagree that this is a duplicate of the other ticket, the other ticket has been open for nearly a year with seemingly no progress in fixing it, while new versions of the app to add emojis and other absolutely useless things have been released.  Why are bugs not being prioritized over new functionality?

**Comment by greyson-signal** [comment] 2020-07-31 14:27
I know the bug, and I know it's a duplicate, don't worry :) Sometimes bugs like this one are very rare and near-impossible to reproduce, and that makes them difficult to fix. I'd very much like to fix it. If you have steps that makes it more likely, or have a device that it happens a lot on, that'd be very useful information to share on #9082. Thanks!

**Comment by sybercorp** [comment] 2020-07-31 14:55
> I know the bug, and I know it's a duplicate, don't worry :) Sometimes bugs like this one are very rare and near-impossible to reproduce, and that makes them difficult to fix. I'd very much like to fix it. If you have steps that makes it more likely, or have a device that it happens a lot on, that'd be very useful information to share on #9082. Thanks!

I guess that's fair.

No, I can't think of anything to recreate it 100% of the time or even more frequently.

It happened on my Samsung Note 9 as well as my current phone (OnePlus 8 Pro) so it doesn't seem device-specific.
