### ISSUE TITLE
Signal removes EXIF data

### ISSUE THREAD

**Issue by circledot** [signalapp/Signal-Android#7862] opened 2018-05-29 18:22 UTC
Recent versions of Signal are stripping pics of their EXIF data. Perhaps fine as a default but please put an option in Settings to not modify pics at all. Thanks.

**Comment by circledot** [comment] 2018-05-29 18:46
I dunno, it never used to remove EXIF data so it might of been a bug. Was it removed intentionally?

**Comment by igor2x** [comment] 2018-05-30 08:10
@circledot, all sort of info can be stored into EXIF metatada like image creation date and time, geolocation, unique device number of camera taking picture and more which are privacy problematic and Signal is privacy application after all. Stripping EXIF metadata was intentional feature not a bug. Code change is at https://github.com/signalapp/Signal-Android/commit/7e1e666172e0c8d0582d28a817affae91a02a598.

IMHO this bug report should be closed down and feature request discussed on forum.

**Comment by circledot** [comment] 2018-05-30 10:35
I have joined to a conversation on the forum so you can close this down. But for the record here, I'm not very happy that an app is modifying my binary files (in this case pics) without my permission. I understand EXIF data may hold geolocation etc - and perhaps you can warn the user of that - but why impose it? Perhaps it should auto-blur text and faces? How far should we take it?

**Comment by scienmind** [comment] 2018-05-30 10:38
@circledot if you want to send a picture unmodified, send it as a "file"

**Comment by circledot** [comment] 2018-05-30 10:43
@scienmind It's still modified.

**Comment by scienmind** [comment] 2018-05-30 11:05
> It's still modified.
Than this is a (separate) bug. If I understand correctly OWS's intention, stuff sent via "File" menu should be always delivered "as is" without modification.

**Comment by scienmind** [comment] 2018-05-30 11:32
@circledot Please submit it as a separate issue (images being altered while sent as "files"), filling in the issue template as required, with log taken after sending the attachment. Thanks

**Comment by jlund-signal** [comment] 2018-05-30 17:46
Closing in favor of the [discussion on the community forum](https://community.signalusers.org/t/add-option-to-keep-or-strip-meta-data/3005).

**Closed by jlund-signal** 2018-05-30 17:46 UTC
