### ISSUE TITLE
SMS rate limit pops up in flight mode

### ISSUE THREAD

**Issue by jandechent** [signalapp/Signal-Android#4449] opened 2015-11-08 12:40 UTC
1. Activate flight mode
2. Activate wlan
3. try to send a SMS
4. get the popup "app is trying to send a lot SMS"

The expectation is a a hint that the device is in flight mode. alternatively replace the send icon with the airplane icon. Sending Signal messages works fine though .

Android 6.0 M8974A
Signal 3.3.1

**Comment by moxie0** [comment] 2015-11-08 18:10
can't do anything without a debug log

**Comment by jandechent** [comment] 2015-11-08 21:13
You're right... PS awesome APP. 

https://gist.github.com/be46bbe306f7b7551181

**Comment by moxie0** [comment] 2015-11-09 05:44
Looks like your device is reporting that you have network service.  Are you running a custom ROM or anything weird?

**Comment by TimmyCarbone** [comment] 2015-11-12 03:13
Having a really similar problem but not sure the cause is the same.
Having the same "Signal is sending a large number of SMS ..." when I try sending an unsecured SMS. 

... But I'm not in flight mode !
Problem is the same if I'm connected or not connected to the network (wifi).

https://gist.github.com/anonymous/aef41db7ff1f48712c33

Not sure if I should open a new issue or not. LMK.

**Comment by jandechent** [comment] 2015-11-12 21:40
Im using a rooted device this might cause the problem.
TimmyCarbone <notifications@github.com> schrieb am Mi., 11. Nov. 2015 um
19:13:

**Comment by TheNain38** [comment] 2015-11-13 08:06
Mine is rooted and flashed with cm11 and not having any issue

**Comment by juanito003** [comment] 2015-11-13 11:54
@TheNain38 Hi, I also have a SGSIII and would like to get your Signal apk could you share it?
I tried te build but it failed (ressource missing from WhisperSystems).

**Comment by TheNain38** [comment] 2015-11-13 12:41
@juanito003 I got Signal from the Google PlayStore

**Comment by vanous** [comment] 2016-02-24 05:12
Some issues here. Not rooted Nexus 5, flight mode enabled but connected to wifi, when sending unsecured SMS to a non signal recepitient. Installed via Google play store.

**Comment by dghouse** [comment] 2016-06-17 11:37
I encountered into this problem when trying to send a message longer than 160 characters. I'm guessing Signal breaks up long messages for transmission and puts them back together later. I think Hang Outs does the same, but the OS won't complain about it. Not cool Google.

Oddly enough, I get the same error while on Wifi with a very short message. I'm guessing the app retries sending the message, triggering this warning. 

Oh, I'm on a Moto G with Lollipop if it helps. Installed Signal from the App Store.

**Comment by chainspell** [comment] 2016-08-31 02:59
I get this error a few times per week. I experience this issue WITHOUT having flight mode on. I am running stock Nexus 5X; I have experienced this on both Marshmallow and Nougat. I also experienced this on Nexus 5 with Marshmallow. Force closing/clearing cache of the Signal app does not resolve the problem.

The only way I can resume sending SMS is if I restart my phone. Here are a couple debug logs when this occurred (generated after repeatedly pressing accept to warning prompt, then pressing deny once to continue, before phone was restarted): 

[https://gist.github.com/65e6a19065a772059fd4f5fc3730300a](https://gist.github.com/65e6a19065a772059fd4f5fc3730300a)

[https://gist.github.com/92d2293b30b4b8f960610cc540d3dc1d](https://gist.github.com/92d2293b30b4b8f960610cc540d3dc1d)

[https://gist.github.com/anonymous/c4c962bb0c4831dc007adf8bff7b464e](https://gist.github.com/anonymous/c4c962bb0c4831dc007adf8bff7b464e)

**Comment by vanous** [comment] 2016-08-31 03:28
I have uninstalled signal long ago and moved to matrix/vector. The developers are responsive and helpful there.

**Comment by mxtm** [comment] 2016-10-11 22:53
I am also having the exact same problem when in flight mode, except I have WiFi enabled for T-Mobile WiFi texting (and have the WiFi texting option in Signal settings on). Nexus 6P with Nougat

**Comment by TopHatProductions115** [comment] 2017-01-01 05:49
I'm having this issue on Android 5 as well, on Doogee X6 Pro. It happens at least once a week with me, and my messages tend to be extremely short (under 20 chars). No Airplane/Flight mode either - just random...

**Comment by TopHatProductions115** [comment] 2017-01-01 07:11
My debug log:
https://gist.github.com/c1215f097d5b2f523cb89ef8d00efb07

**Comment by automated-signal** [comment] 2018-04-02 22:55
GitHub Issue Cleanup:
See #7598 for more information.

**Closed** 2018-04-02 22:56 UTC
