### ISSUE TITLE
Video call own camera

### ISSUE THREAD

**Issue by rissilver** [signalapp/Signal-Android#9004] opened 2019-08-31 11:48 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
In video call own camera is cube and is not real form how other person sees it.

### Device info

**Device:** Manufacturer :** Xiaomi redmi note 4
**Android version:** 8.1.0
**Signal version:** 4.46.2

**Comment by alan-signal** [comment] 2019-08-31 13:56
cube?

**Comment by pabl0** [comment] 2019-09-01 19:45
Square. So the framing/aspect ratio  you see on your local device is different the other party sees on his/her screen.

**Comment by rissilver** [comment] 2019-09-01 20:16
Better said, thanks

**Comment by rainerzufall** [comment] 2019-09-02 12:21
duplicate of: https://github.com/signalapp/Signal-Android/issues/8615

**Comment by greyson-signal** [comment] 2019-09-03 22:26
Closing as dupe

**Closed by greyson-signal** 2019-09-03 22:26 UTC
