### ISSUE TITLE
Portrait images are displayed in landscape when viewed in full screen mode

### ISSUE THREAD

**Issue by yan-** [signalapp/Signal-Android#8025] opened 2018-07-22 20:53 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

When I receive images in Signal messages that are in portrait format and then tap on them to see them in full screen, they are displayed in landscape mode, i.e. turned 90 degrees. That does not apply to all portrait images, but to many. It seems to me that it happens on a per-user base, that means, if one image from a contact is displayed wrong, all portrait images from that user are incorrect.

### Steps to reproduce
- Receive a portrait image
- tap on it

**Actual result:** Image is displayed in landscape mode.
**Expected result:** Image is displayed in portrait mode.

### Screenshots
nope

### Device info
**Device:** Oneplus X
**Android version:** 6.0.1 (OxygenOS 3.1.4)
**Signal version:** 4.24.2
(Same problem happens with my partner's Samsung Galaxy A3)

### Link to debug log
https://debuglogs.org/22589a5dc191a287d4719640352d3ca58c9a4daac220ded946c455b5be50a497

**Comment by greyson-signal** [comment] 2018-07-23 15:02
Hmm, this is likely a lingering issue with EXIF rotation data not being acknowledged. It's probably happening on a per-contact basis because that person's phone does something interesting with the EXIF data. I'll close this as a dupe of #7671.

Thank you!

**Closed by greyson-signal** 2018-07-23 15:02 UTC
