### ISSUE TITLE
error playing audio

### ISSUE THREAD

**Issue by leonardoporp** [signalapp/Signal-Android#8856] opened 2019-06-05 19:34 UTC
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I encoure into a error while playing some audios that I receive from signal. I think, but I'm not sure about that they are forwarded from whatsapp

### Steps to reproduce
- play the audio

**Actual result:** I get an error while playing the audio
**Expected result:** I should be able to listen to it

### Device info

**Device:** pixel 2 xl
**Android version:** 9
**Signal version:** latest

### Link to debug log

Sent to you through Signal

**Comment by walkertraylor** [comment] 2019-06-16 19:25
I have the same issue on a Pixel 2 XL.  Sometimes audio message will play, and sometimes they do not.  

I can play them on Signal Desktop Client.

**Comment by dusscloud** [comment] 2019-06-23 16:12
Same issue : I sent an audio file (AAC 48khz m4a), which also cannot be played within Signal.
The only option is to download the attachment and open it with VLC app for instance.
In my case I am on a Motorola Moto G6 with Android 9.

**Comment by five-c-d** [comment] 2019-06-23 16:21
@dusscloud can you please submit debuglogs from the sender-device, and from the recipient-device?  home > signal > threeDotMenu > advanced > debuglog > submit > longpress to copy URL to clipboard > click edit on your comment above > paste URL here into github.  

Are you able to send (handset A to B and also B to A) voiceNotes from within signalapp, by holding down the little microphone-icon next to the quick-camera-icon, successfully?  Whereas when you record audio in an external app, and try to do that, you are unsuccessful unless the recipient downloads the audiofile and plays it in VLC, it seems?

**Comment by dusscloud** [comment] 2019-06-23 17:11
> @dusscloud can you please submit debuglogs from the sender-device, and from the recipient-device? home > signal > threeDotMenu > advanced > debuglog > submit > longpress to copy URL to clipboard > click edit on your comment above > paste URL here into github

Here  a debug log from the sender.
https://debuglogs.org/2767404c865eda70fda330498cffe0f1390cee9ede701ba777edc3ddb10d3867
No need to do the same from the receiver, I cannot even playback the file on the sender side after having sent the file.

 
> Are you able to send (handset A to B and also B to A) voiceNotes from within signalapp, by holding down the little microphone-icon next to the quick-camera-icon, successfully? 

Yes that works.

> Whereas when you record audio in an external app, and try to do that, you are unsuccessful unless the recipient downloads the audiofile and plays it in VLC, it seems?

Exactly

**Comment by greyson-signal** [comment] 2019-07-23 18:10
This seems to be a device-specific or format-specifc problem. In these cases, the best thing I could get is a sample file that is known to not play on a device, and a debuglog from the device taken just after it failed to play.

**Comment by leonardoporp** [comment] 2019-07-25 10:20
Done. Look your signal number

**Comment by leonardoporpora** [comment] 2019-07-29 17:20
Greyson I see that you haven't received the message yet and it seems that
your number is no more registered on Signal. Tell me if you need that I
send you the audio and the logs again.

**Comment by davidak** [comment] 2020-11-07 21:59
duplicate of https://github.com/signalapp/Signal-Android/issues/8487 (?)

**Closed** 2022-02-03 16:52 UTC
Labels: wontfix
