### ISSUE TITLE
Circumvent Signal censoring in Cuba

### ISSUE THREAD

**Issue by jromero2k** [signalapp/Signal-Android#8712] opened 2019-03-27 02:44 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Thanks to ETECSA --the telecommunications monopoly in Cuba-- blocking Signal confirmation messages or calls, it's impossible to install Signal on a new phone, or restore normal use when replacing an old phone

### Steps to reproduce
- Install Signal
- Fill in the +53 xxxxx phone number
- The screen is replaced by "Enter the code we sent to +53 xxxx"
- The code never arrives
- "CALL ME INSTEAD" action becomes available after a while
- Nothing else happens, the app can't be used at all

**Actual result:** App can't be used

**Expected result:** An alternative method should be available to register Signal. Maybe sending the activation code from a non-blacklisted origin, or reading the active number from the SIM and providing additional steps.

### Device info

**Device:** N/A
**Android version:** N/A
**Signal version:** N/A

**Comment by riyapenn-signal** [comment] 2019-07-12 06:55
You can register in Cuba now with the verification code arriving from **SignalApp** 
For reference, this is a duplicate of https://github.com/signalapp/Signal-Android/issues/8450

**Closed by riyapenn-signal** 2019-07-12 06:55 UTC
