### ISSUE TITLE
Messages within a specific thread are stuck sending.

### ISSUE THREAD

**Issue by Xashyar** [signalapp/Signal-Android#8602] opened 2019-02-09 13:51 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Messages don't get sent to a Specific contact (+*********62) from mobile but are sent successfully from Desktop.
+: Messages to other contacts are sent and delivered with no problem.

*Edit: I've also tried attachments after sending the log, and they also get stuck.

### Screenshots

![signal-attachment-2019-02-09-171010](https://user-images.githubusercontent.com/34171942/52521626-21c4c580-2c8f-11e9-86e4-d363575f1a86.png)

### Device info

**Device:** Nexus 5
**Android version:** 6.0.1
**Signal version:** 4.33.5
### Link to debug log

https://debuglogs.org/cbcee7965976ea069cb7f4b4f3e5726bd5fabbaf33c4d1b9ec8d489f4d232d47

**Comment by greyson-signal** [comment] 2019-02-11 18:02
Looks like this job failed and was never retried, blocking the queue. This is a WorkManager bug.

```java
2019-02-09 11:16:34.503 GMT+03:30 I Job: [7f76d76f-93ef-44a6-8e60-d569f9d74ac0] PushTextSendJob :: Retrying after a retryable exception. (Time since submission: 228 ms, Run attempt: 0, isStopped: false)
2019-02-09 11:16:34.503 GMT+03:30 I Job: org.thoughtcrime.securesms.transport.RetryLaterException: org.whispersystems.signalservice.api.push.exceptions.PushNetworkException: java.net.UnknownHostException: Unable to resolve host "textsecure-service.whispersystems.org": No address associated with hostname
2019-02-09 11:16:34.503 GMT+03:30 I Job: 	at org.thoughtcrime.securesms.jobs.PushTextSendJob.deliver(PushTextSendJob.java:175)
2019-02-09 11:16:34.503 GMT+03:30 I Job: 	at org.thoughtcrime.securesms.jobs.PushTextSendJob.onPushSend(PushTextSendJob.java:92)
2019-02-09 11:16:34.503 GMT+03:30 I Job: 	at org.thoughtcrime.securesms.jobs.PushSendJob.onSend(PushSendJob.java:86)
2019-02-09 11:16:34.503 GMT+03:30 I Job: 	at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:56)
2019-02-09 11:16:34.503 GMT+03:30 I Job: 	at org.thoughtcrime.securesms.jobmanager.Job.doWorkInternal(Job.java:111)
2019-02-09 11:16:34.503 GMT+03:30 I Job: 	at org.thoughtcrime.securesms.jobmanager.Job.doWork(Job.java:64)
2019-02-09 11:16:34.503 GMT+03:30 I Job: 	at androidx.work.Worker$1.run(Worker.java:84)
2019-02-09 11:16:34.503 GMT+03:30 I Job: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
2019-02-09 11:16:34.503 GMT+03:30 I Job: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
2019-02-09 11:16:34.503 GMT+03:30 I Job: 	at java.lang.Thread.run(Thread.java:818)
2019-02-09 11:16:34.503 GMT+03:30 I Job: Caused by: org.whispersystems.signalservice.api.push.exceptions.PushNetworkException: java.net.UnknownHostException: Unable to resolve host "textsecure-service.whispersystems.org": No address associated with hostname
2019-02-09 11:16:34.503 GMT+03:30 I Job: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.getServiceConnection(PushServiceSocket.java:917)
2019-02-09 11:16:34.503 GMT+03:30 I Job: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:778)
2019-02-09 11:16:34.503 GMT+03:30 I Job: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.sendMessage(PushServiceSocket.java:222)
2019-02-09 11:16:34.503 GMT+03:30 I Job: 	at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:851)
2019-02-09 11:16:34.503 GMT+03:30 I Job: 	at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:218)
2019-02-09 11:16:34.503 GMT+03:30 I Job: 	at org.thoughtcrime.securesms.jobs.PushTextSendJob.deliver(PushTextSendJob.java:169)
2019-02-09 11:16:34.503 GMT+03:30 I Job: 	... 9 more
2019-02-09 11:16:34.503 GMT+03:30 I Job: Caused by: java.net.UnknownHostException: Unable to resolve host "textsecure-service.whispersystems.org": No address associated with hostname
2019-02-09 11:16:34.503 GMT+03:30 I Job: 	at java.net.InetAddress.lookupHostByName(InetAddress.java:440)
2019-02-09 11:16:34.503 GMT+03:30 I Job: 	at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
2019-02-09 11:16:34.503 GMT+03:30 I Job: 	at java.net.InetAddress.getAllByName(InetAddress.java:215)
2019-02-09 11:16:34.503 GMT+03:30 I Job: 	at okhttp3.Dns$1.lookup(Dns.java:39)
2019-02-09 11:16:34.503 GMT+03:30 I Job: 	at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:185)
2019-02-09 11:16:34.503 GMT+03:30 I Job: 	at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:149)
2019-02-09 11:16:34.503 GMT+03:30 I Job: 	at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84)
2019-02-09 11:16:34.503 GMT+03:30 I Job: 	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:213)
2019-02-09 11:16:34.503 GMT+03:30 I Job: 	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:134)
2019-02-09 11:16:34.503 GMT+03:30 I Job: 	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:113)
2019-02-09 11:16:34.503 GMT+03:30 I Job: 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
2019-02-09 11:16:34.503 GMT+03:30 I Job: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-02-09 11:16:34.503 GMT+03:30 I Job: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2019-02-09 11:16:34.503 GMT+03:30 I Job: 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
2019-02-09 11:16:34.503 GMT+03:30 I Job: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-02-09 11:16:34.503 GMT+03:30 I Job: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2019-02-09 11:16:34.503 GMT+03:30 I Job: 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
2019-02-09 11:16:34.503 GMT+03:30 I Job: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-02-09 11:16:34.503 GMT+03:30 I Job: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
2019-02-09 11:16:34.503 GMT+03:30 I Job: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-02-09 11:16:34.503 GMT+03:30 I Job: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2019-02-09 11:16:34.503 GMT+03:30 I Job: 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
2019-02-09 11:16:34.503 GMT+03:30 I Job: 	at okhttp3.RealCall.execute(RealCall.java:77)
2019-02-09 11:16:34.503 GMT+03:30 I Job: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.getServiceConnection(PushServiceSocket.java:910)
2019-02-09 11:16:34.503 GMT+03:30 I Job: 	... 14 more
```

Can you try restarting your device? This is a bug I'm still trying to workaround, but for those that run into it, restarting (or just force-stopping) tends to help.

**Comment by omniuwo** [comment] 2019-02-13 20:43
I have experienced this problem for a couple of weeks.

When a message get stuck to a certain contact, I cannot send anything to that contact again. I now have fewer and fewer contacts that I can communicate with.

I've tried restarting the app, the phone, removing the stuck message as well as the whole conversation.

**Comment by greyson-signal** [comment] 2019-02-13 20:55
@omniuwo Can you submit a debug log?

**Comment by brinerustle** [comment] 2019-02-16 10:04
Workaround: Erase all of the messages back to before the first failed message and reboot.

This also started happening on my partner's device, on the 12th February. It received my chats, I received confirmation that it received them, and we could call each other, but it could not chat me back. Resetting secure sessions did not work, nor did erasing the conversation on my end. We created a group, then we were able to chat, then I tried the above workaround. I don't have access to the device to send a debug log.

**Comment by menaceone** [comment] 2019-02-19 18:20
Same behaviour here.
Willing to help, need an additional debug log or something?

**Comment by greyson-signal** [comment] 2019-02-19 18:41
@menaceone Unfortunately I can guess what your log will look like. I think the solution here is to ditch WorkManager and write our own thing, which is a pretty huge task. Looking more and more like I'm just gonna have to do it though.

**Comment by Rappel87** [comment] 2019-02-20 18:44
I am having the same issues but not sure if it is the same problem.

I created the issue in the wrong repo but it has a description and debug log attached. 
https://github.com/signalapp/Signal-Desktop/issues/3155

We tried the workaround with the groupchat but only 2 messages were delivered successfully after it stopped working. 
The person with the problem can still text other signal contacts.

**Comment by JamesHarrison** [comment] 2019-02-22 21:26
I've just seen the same issue - unfortunately didn't get a log entry out but it was contact-specific behaviour. SMS (in Signal) to the same contact worked, so was just Signal messages that failed. Other user working just fine and able to reply to my SMS messages via Signal. Only seen this recently, after (but not coinciding with - was working fine for some days) latest Android update on a Galaxy S9+.

**Comment by watcg** [comment] 2019-02-22 22:30
Same here. Good workaround is to make a new group that is just you and the other person. In my experience they can then receive messages again. Annoying tho!

**Comment by watcg** [comment] 2019-02-23 14:37
Good news-- for one of my recipients where this happened, eventually (5-6 days later, approximately), the stuck messages eventually seemed to give up on sending and just said failed to send.  And so i can send again!

**Comment by Pratiwir** [comment] 2019-03-05 10:52
I had a similar issue today. UsingGT-I9082 Android 4.1.2
https://debuglogs.org/21214f2af973ab336a73eba10f4cb6d89fc34e06f9a46203c821b41952981402
The messages going out were marked sent to server but not delivered. They were in fact delivered.
Incoming messages didn't arrive at all.
Rebooting the device fixed the problem.
I recently upgeaded to Signal 4.34.8 and was previously having problems with messages not playing which needed reboot. So I removed firefox to clear space. I think there is some space or paging issue because reboot always fixes the problems. 
My main suggestion is if play gives an error then more complete information should be given. The previous version wouldn;t save error logs at all, this seems ok now.
Also there could be better diagnostics on the server connection to see if there are errors getting or displaying data. I suspect some memory problem or low swap space maybe the root issue.

**Comment by greyson-signal** [comment] 2019-04-16 20:36
I've removed WorkManager in the [current beta](https://play.google.com/apps/testing/org.thoughtcrime.securesms) (4.38.x) and replaced it with our own system. Check it out and let me know if messages are still getting stuck. Thanks!

**Comment by akutuzov** [comment] 2019-04-16 22:10
In fact, for me the problem was fixed after I upgraded to 4.35.3.

**Comment by Nostrocean** [comment] 2019-09-18 10:34
I am having the same issue (Signal 4.47.6)
	
Only happens with one certain contact, where my outgoing messages get stuck (spinning wheel icon).
	
I tried to solve restarting Signal, rebooting the device, deleting stuck messages, reseating session key, and deleting the chat, but nothing worked; my sent messages with this contact kept being stuck after each one of those tries.
	
Latter I deleted stuck messages, did backup, uninstalled Signal and installed it again, what at first apparently solved the problem due I was able to send two messages until my outgoing messages began to get stuck again with this certain contact.

This is the log after reinstall Signal:
	
- Around 20:08 sent message, OK.
- Around 20:14 sent message, OK.
- Around 01:01 received message, OK.
- Since 01:01 the next 2 outgoing messages get stuck (spinning wheel icon). 
- I erase those stuck messages, restart Signal, latter I turn off the device.
- At 02:29 turn on the device, new outgoing message get stuck.
	
https://debuglogs.org/e912427f937d1d443b468c85088fca8cf7afbb6fb602423cccc057f8e530965a

**Comment by greyson-signal** [comment] 2019-09-18 14:17
I believe the original bug here was fixed some time ago.

**Comment by greyson-signal** [comment] 2019-09-18 14:17
@Nostrocean you're experiencing a different issue. Specifically, you have an SMS you're trying to send earlier in your thread, and for whatever reason it isn't send, and therefore is blocking all future messages. It's likely the case that for whatever reason, we're not detecting 'cellular service' on your device. Regardless, you are experiencing a dupe of #9030.

**Closed by greyson-signal** 2019-09-18 14:17 UTC

**Comment by robertsmd** [comment] 2023-04-14 18:38
To give a little more detail: the Queue `Queue: RecipientId::10` is stopped up, but the Queue `Queue: RecipientId::10::MEDIA` works fine, so I actually get a pending message, then a sent media message after it.

Furthermore, messages are able to be received, but received receipts and read receipts are not sent, because they are sent to the `Queue: RecipientId::10` queue

**Comment by greyson-signal** [comment] 2023-04-14 20:40
Hi @robertsmd I would need a log. Feel free to open a new issue too :+1:
