### ISSUE TITLE
Backup restore fails

### ISSUE THREAD

**Issue by pgerber** [signalapp/Signal-Android#9177] opened 2019-11-11 23:43 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Backup fails to restore. Restore starts, progress shows that hundreds of messages have been restored already and then aborts telling me the passphrase was incorrect.

### Steps to reproduce
- create backup on device A
- restore  backup on device B

**Actual result:** Restore aborts
**Expected result:** Restore succeeds

### Device info (device A, backup source)

**Device:** Samsung Galaxy
**Android version:** 9 (LineageOS 16)
**Signal version:** 4.49.18

### Device info (device B, backup target)

**Device:** Nokia 4.2
**Android version:** 9
**Signal version:** 4.19.18

### Link to debug log

[Device A](https://debuglogs.org/f7c091e46af94724d3234d1c77c6b817063c62317028227df25ac19df1f44e9e)
[Device B](https://debuglogs.org/654ecae6b54c9836d22b145e6015233de0391bb640de426d24ec51e77aa9ebba)

**Comment by pgerber** [comment] 2019-11-12 13:28
Based on the error, [this here](https://stackoverflow.com/questions/52024752/android-9-keystore-exception-android-os-servicespecificexception/52295484#52295484) might be the solution.

**Comment by greyson-signal** [comment] 2019-11-12 19:31
```java
11-12 00:26:11.945 11285 11409 W RestoreBackupFragment: java.io.IOException: File ended early!
11-12 00:26:11.945 11285 11409 W RestoreBackupFragment: 	at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readAttachmentTo(FullBackupImporter.java:283)
11-12 00:26:11.945 11285 11409 W RestoreBackupFragment: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.processAttachment(FullBackupImporter.java:140)
11-12 00:26:11.945 11285 11409 W RestoreBackupFragment: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:85)
11-12 00:26:11.945 11285 11409 W RestoreBackupFragment: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:198)
11-12 00:26:11.945 11285 11409 W RestoreBackupFragment: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:190)
11-12 00:26:11.945 11285 11409 W RestoreBackupFragment: 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
11-12 00:26:11.945 11285 11409 W RestoreBackupFragment: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
11-12 00:26:11.945 11285 11409 W RestoreBackupFragment: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
11-12 00:26:11.945 11285 11409 W RestoreBackupFragment: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
11-12 00:26:11.945 11285 11409 W RestoreBackupFragment: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
11-12 00:26:11.945 11285 11409 W RestoreBackupFragment: 	at java.lang.Thread.run(Thread.java:764)
```

Closing as dupe of #9154. See this comment for why it's the same:
https://github.com/signalapp/Signal-Android/issues/9136#issuecomment-552916561

**Closed by greyson-signal** 2019-11-12 19:31 UTC
