### ISSUE TITLE
The login/signup UX flow is insanely confusing

### ISSUE THREAD

**Issue by otherstew** [signalapp/Signal-Android#13432] opened 2024-02-17 23:08 UTC
1. Get a new phone, keep your existing number & have it fully set up for everything including 2FA (which you sometimes have to wait for).
2. Install signal (no other apps installed, reliable/fast 4G data connection or WiFi, no proxies/VPNs or any other shenanigans).
3. Launch the app, grant the requested android permissions.
4. Enter phone number.
5. Get a prompt asking 'Is the phone number below correct?' (see screenshot below). Click yes.
6. Get a captcha, solve the captcha like a good little mechanical turk.
7. After a brief pause **I get the exact same screen from step 5 screen, with no indication of success or failure or anything.**
8. Inspect number carefully, add/remove leading zeroes, type it in again to make sure there's no invisible unicode trickery, switch to wifi, switch back to data, change *something* and click 'OK' again like a good little user.
9. Repeat setps 6, 7, and 8 ad nausium until I get blocked by a login cooldown for too many attempts.

I was accidentally able to log in to my secondary account by putting my phone down at step 7, and avoiding interacting with the dialog for long enough that the app got to the next stage of the login sequence. So it seems that my original attempt was probably fine, but because of the mind boggling UX flow I repeatedly cancelled my attempt and started a new one until I got put in the naughty corner.

So why the hell do I get shown a screen which indicates (or at least strongly suggests) that something went wrong and I need to do something to try again when doing anything will cancel my current login attempt and start a new one (even though there's nothing wrong)? Why don't I get a 'captcha sucess/failure', or a 'please wait' screen, or just a loading spinner? Nearly *anything* would be better than the current flow.

This is the problematic prompt:
![Screenshot_20240218-111703](https://github.com/signalapp/Signal-Android/assets/135083158/d5062e2f-da3a-43a1-91b1-cf74d5cb8df0)

### Device info
**Device:** Sony Xperia 1 IV
**Android version:** 14
**Signal version:** 6.46.7

### Link to debug log
I can't do this yet, because I'm blocked from signing in again.

**Comment by cody-signal** [comment] 2024-02-19 19:50
If you tap any title 8 times in the registration flow it'll prompt about a debuglog. That would be very helpful for figuring out what you are stuck in a loop.

**Comment by otherstew** [comment] 2024-02-26 22:25
Turns out it's a different issue to the one where I had to wait, since waiting doesn't seem to work even after the lockout.

[Here's the log.txt](https://github.com/signalapp/Signal-Android/files/14411984/log.txt)

**Comment by HensonHorkson** [comment] 2024-02-27 18:08
The same happened here today while reinstalling after resetting my phone. Took sometimes about 15 minutes between the dialogs. First I was tuck in a loop, where I was asked a second time my phone number, then they send me the code via SMS but there was no field to enter the code.
Then I reentered the number a few times without getting a box to enter the first or the second code. 
Then I put the phone away and only as I unlocked it some time later the field to enter the code had loaded. 

Could it be some man in the middle attack or something? This huge lag between the SMS and the field worries me.

**Comment by otherstew** [comment] 2024-03-03 23:47
Okay so this is actually two issues:

1. The login flow is still insane and the absence of any useful error messages is frustrating and pointless as far as I can tell.
2. After using 'Change phone number' I am unable to access my account from any device using the new phone number. Probably a general signal bug(?)

For the second one: I signed up ages ago with my original phone number, and used signal for a while. Recently I moved to a new phone number and used 'Change phone number' to switch my account to that number, but I kept the same phone and didn't have to log in again. Now, I am unable to log in on any device using the new number which is a problem because I now have a new phone. I can, however log in using my original number and repeat the 'Change phone number' process to switch to switch to the new number again which gives me access to signal via the new number but seems to be creating a new identity? I'm not sure. Again, needlessly confusing.

**Comment by JRosanowski** [comment] 2024-04-25 22:04
Same problem here. Also got to the point where I've tried to register too many times and have to wait 4 hours to try again...

**Comment by cody-signal** [comment] 2024-04-26 15:29
@JRosanowski can you provide a debuglog? Tap any title in the registration flow 8 times, get the links, post the link here or send it us directly?

**Comment by JRosanowski** [comment] 2024-04-26 19:56
Here's the debug log. I actually created this yesterday when I was having problems. After I created the debug log I used the back button to return to Signal and it suddenly allowed me to progress| through the sign up process. So I no longer have a problem.

[7aa88c2f261cbc6a653caf7103fd185af920dd7d19a4c061ebecfa0f9395a1eb.txt](https://github.com/signalapp/Signal-Android/files/15134802/7aa88c2f261cbc6a653caf7103fd185af920dd7d19a4c061ebecfa0f9395a1eb.txt)

**Comment by sjmduncan** [comment] 2024-06-26 20:04
Hi, I'm not sure. I have no idea if the issue has been addressed because my secondary problem (the "I can't sign in with a 'changed' phone number" from my previous comment) appears to have been resolved and I can't force that failure mode to see if the issue is fixed.

It *looks* like it hasn't changed, but I can't demonstrate failure to login (or maybe to verify the phone number?) would do anything other than unceremoniously dump you back on the 'Phone Number' page without any indication that something failed.

**Comment by otherstew** [comment] 2024-06-26 20:06
Hi. I'm not sure. The "Can't sign in with a changed phone number" problem seems to be resolved, and I don't have a way to trigger that error (or a similar one) to see if the login process has changed, or whether it would still just unceremoniously dump you back on the 'Phone Number' screen.

**Comment by nicholas-signal** [comment] 2024-06-26 20:51
Glad to hear at least the one problem is resolved! I'll close this issue; feel free to re-open it if it happens again.

**Closed by nicholas-signal** 2024-06-26 20:51 UTC
