### ISSUE TITLE
Notifications on Phone not Clearing When Messages are Read on the Desktop App

### ISSUE THREAD

**Issue by 492wnw5ja** [signalapp/Signal-Android#11950] opened 2022-02-02 13:58 UTC
Bug description

Post-upgrade to Android 12 on my Pixel 4a, banner notifications and notification bubbles on my phone no longer disappear after the messages/reactions are read on my Signal Desktop app (Windows 11). When read on my phone, the notification number on the desktop app's taskbar icon disappears, and the message/reaction shows as read in the desktop app which is normal behavior.

Steps to reproduce

- Receive notification from Signal.
- Read message on Signal Desktop. (Application can be open or closed before receiving message/reaction.)
- Notification remains populated on phone or populates on the phone if the conversation was open on the desktop app when the message/reaction arrives and was automatically marked as read when received on the desktop.
- Opening the Android app to the messages list shows that the message has been read but still does not clear the banner notification. You must actually open the message, either from selecting the banner notification or the conversation list, to clear the banner notification.
- The desktop app has been removed and re-linked several times and both devices have been rebooted several times over the past 6 days since this started.

Actual result: Signal message notifications on Android 12 persist even when they have been read on the desktop app until you open the conversation in the Android app.

Expected result: When a message is opened on either device, the notification on the other device should clear.

Device info

Device: Pixel 4a

Android version: Android 12, CalyxOS 3.1.0

Signal version: 5.28.10

App state

Signal messages and calls registered, SMS enabled, recovery passphrase enabled, synced with one desktop app, no Google Play Services, installed via APK.

Link to debug log

https://debuglogs.org/5e1922573723bfe74076d2de4559e58767251dad0bec04ac483c0656c16c0f6b (from device while message was read but notification was still active)

**Comment by cody-signal** [comment] 2022-02-02 14:57
Looking at the log, we are getting the read syncs and telling the system to dismiss all notifications. Android 12 has incredibly busted notifications and using a custom rom on top of that may be the reason why it's not working.

If the message has been marked read in the conversation list, then we are definitely trying to dismiss the notification. Entering any conversation will force another attempt to clear notifications which for some reason is working the second time. Does this always happen even with the app in the foreground and the device unlocked?

**Comment by 492wnw5ja** [comment] 2022-02-02 23:43
@cody-signal, the issue seems to have been resolved after installing the latest Signal Desktop update just two hours ago. 

(－‸ლ)

For reference to your question, yes, the issue occurred even when the app was open to any conversation other than the one receiving updates or to the app list in the foreground with the device unlocked. 

I've now been able to open conversations on my desktop app, and the notification on my phone clears even when the app is cleared from the open app list and my device is locked.

Thank you VERY much for such a quick turnaround investigating this issue, and I'm glad it's now resolved!

**Comment by 492wnw5ja** [comment] 2022-02-03 12:20
@cody-signal , after closing the Signal desktop app last night and reopening this morning, the previous behavior has been restored.

With the further information about the behavior, the temporary fix, and clarification that you provided about the dual attempts of the app to clear the notifications, what are the next steps to investigating this issue? Or are we going to just say it's A12's fault?

**Comment by cody-signal** [comment] 2022-02-03 14:23
Based on the logs, we are doing everything we should be doing for clearing notifications. I was search around on CalyxOS and notification issues to see if others have problems with notifications.

**Comment by 492wnw5ja** [comment] 2022-02-03 14:57
Thanks! I couldn't find anything, so I submitted one linking this issue.

Thank you again! Since the app is working properly, I'll go ahead and close this issue again.

**Comment by dagdrommer** [comment] 2022-02-07 15:59
I do observe the same on my Pixel 4a G for quite a while now. As @492wnw5ja stated, the app works well otherwise... However, I wouldn't close this issue, as it still is a bug and more and more Android devices will get Android 12 (or one day even higher) in future, where de bug will likely persist.

**Comment by cody-signal** [comment] 2022-02-08 13:48
@dagdrommer are you running stock Android 12 or a custom ROM?

**Comment by dagdrommer** [comment] 2022-02-08 13:52
Stock Android 12

Btw, thank you @cody-signal for your work at signal and it's community.

**Comment by dagdrommer** [comment] 2022-02-08 13:58
Here my log:  https://debuglogs.org/16830346acb5d2c10b975249b353292ca695f3d80e2fb20269c4af6039426dc2

When I receive a message, i get a notification on my Phone and Desktop. If I read the message on the desktop, the message gets 'read' on my desktop and my SignalApp on the phone. However, the notification sustains in Android, until I manually open the chat or remove it inside my system.

**Comment by cody-signal** [comment] 2022-02-08 14:14
@dagdrommer nothing immediately jumps out from your logs. Is the notification a full message notification or a summary one (like x convos with x messages type text, or latest from x).

**Comment by dagdrommer** [comment] 2022-02-08 14:18
full message notification

**Comment by Kit-p** [comment] 2022-03-09 14:10
I am observing the same behavior on my Mi 9T running Android 11 and MIUI Global 12.1.4, the full message notification persists even after I have replied in the desktop client.

**Device Info**
**Device:** Xiaomi Mi 9T (aka Redmi K20)
**Android version:** Android 11 RKQ1.200826.002
**ROM:** MIUI Global 12.1.4.0 (RFJMIXM)
**Signal version:** 5.32.15

Link to debug log, hope that helps.
https://debuglogs.org/android/5.32.15/d9cd1fbb23f4ff02d339c10c3da17201ffc5897c1720ff4df4c81b4411d6c5b9

**Comment by 492wnw5ja** [comment] 2022-04-05 15:19
The original issue has also returned for me.

**Comment by janvlug** [comment] 2022-04-05 15:19
Here is a [debug log](https://debuglogs.org/android/5.34.5/403f3bf3f4bc54d640b703b8a095cf3a82f606df97fdff0985cb76091e4f2083).

**Comment by janvlug** [comment] 2022-04-07 11:22
Some additional info: It is only the notification in the top of the Android screen that stays. The batch with the number of unread messages does disappear in Signal Android after reading the messages in Signal Desktop.

**Comment by cody-signal** [comment] 2022-04-07 14:44
@janvlug could you provide a screenshot? You can blur out names/message content. And you can email it to me directly if you want. My email is my name at signal dot org.

**Comment by janvlug** [comment] 2022-04-08 09:08
Unfortunately, I just "solved" the issue, by going into the Android Settings | Apps | Notifications. There, the contact for which the above appeared was shown as a conversation for which bubbles were allowed. I removed the contact from there, and made sure bubbles for Signal were fully disabled. Now the notifications for this contact are cleared again when I read the messages at Signal Desktop. So my conclusion is that the issue in my case was certainly related to Android bubbles.
I will try if I can reproduce it. If I manage to do this, I will provide the requested screenshot. But basically what you saw on the screen was a little blue dot (indicating that there is a notification) on the Signal icon on the Android "Desktop", and the small Signal logo in the top bar indicating that there is an unread message.

**Comment by 492wnw5ja** [comment] 2022-04-08 10:37
Quick note: bubbles are disabled entirely on my device, so @janvlug's fix isn't always applicable.

**Comment by Andysk13** [comment] 2022-05-03 07:28
Hello, I'm having this same problem and it's specific to signal. It's not happening to me with whatsapp or regular messages

**Comment by jvankoll** [comment] 2022-05-03 15:34
I am having this issue as well. I'm using a Google Pixel 5 running stock Android 12.

**Comment by cody-signal** [comment] 2022-05-06 20:15
Can y'all try on the latest beta and see if the issue is resolved? If not, an updated debug log with the timestamps of the messages that won't go away would be helpful (long press message -> info -> long press sent timestamp -> copies a timestamp to your clipboard -> send that here with the debuglog.

**Closed** 2022-07-12 21:52 UTC
Labels: wontfix
