### ISSUE TITLE
Reproducible Signal crash when entering conversation

### ISSUE THREAD

**Issue by SamLS98** [signalapp/Signal-Android#10738] opened 2021-01-19 16:31 UTC
- [X] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic
- 
### Steps to reproduce
- Open the app
- Select the search icon
- Put the phone in landscape mode
- While on it, go into one of the chats

### Link to debug log
https://debuglogs.org/7bc1a34ed0e9ad9cf969e43a2025ab52545b747a139180dbc7b4fe3bba560772

I made a video
https://cloud.disroot.org/s/iCWeLbzfQZoxtXw
I'm currently using 5.2.3

**Comment by Xrasure** [comment] 2021-01-19 21:29
I could not reproduce the issue in the signal beta for Android, so I assume it will be fixed in the next public release

**Comment by SamLS98** [comment] 2021-01-20 07:49
> I could not reproduce the issue in the signal beta for Android, so I assume it will be fixed in the next public release

I installed the beta and the bug persist

**Comment by Xrasure** [comment] 2021-01-20 08:02
> > I could not reproduce the issue in the signal beta for Android, so I assume it will be fixed in the next public release
> 
> I installed the beta and the bug persist


Which device are you using? I'm using a oneplus 6t and there is no issue

**Comment by Alecerf** [comment] 2021-01-20 08:09
I can't reproduce in the last version (5.2.3)
Device: Pixel 3XL Android 11

**Comment by Natanel-Ziv** [comment] 2021-01-20 08:11
I can't reproduce on latest version (5.2.3)
Device: OnePlus 8

**Comment by SamLS98** [comment] 2021-01-20 08:15
> > > I could not reproduce the issue in the signal beta for Android, so I assume it will be fixed in the next public release
> > 
> > 
> > I installed the beta and the bug persist
> 
> Which device are you using? I'm using a oneplus 6t and there is no issue
It's in the debug log
Device: LG-M400
Is there a way to record the screen?

**Comment by Xrasure** [comment] 2021-01-20 08:17
> > > > I could not reproduce the issue in the signal beta for Android, so I assume it will be fixed in the next public release
> > > 
> > > 
> > > I installed the beta and the bug persist
> > 
> > Which device are you using? I'm using a oneplus 6t and there is no issue
> 
> It's in the debug log
> Device: LG-M400
> Is there a way to record the screen?

You could download a free screen recording program and upload the video to youtube and send the link

**Comment by SamLS98** [comment] 2021-01-20 08:37
I made a video
https://cloud.disroot.org/s/iCWeLbzfQZoxtXw

**Comment by Xrasure** [comment] 2021-01-20 08:40
> I made a video
> https://cloud.disroot.org/s/iCWeLbzfQZoxtXw
> I'm currently using 5.2.3

This is probably an issue with your device model

**Comment by Leptopoda** [comment] 2021-01-20 10:50
> This is probably an issue with your device model

I disagree. Your debuglog indeed shows a crash caused by signal
```
01-16 09:05:30.796 14942 15493 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x345ad84c in tid 15493 (Thread-5)
01-17 22:17:41.225  9449  9739 E AndroidRuntime: FATAL EXCEPTION: pool-24-thread-1
01-17 22:17:41.225  9449  9739 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 9449
01-17 22:17:41.225  9449  9739 E AndroidRuntime: java.lang.IllegalStateException: value is absent
01-17 22:17:41.225  9449  9739 E AndroidRuntime: 	at org.whispersystems.libsignal.util.guava.Absent.get(Absent.java:39)
01-17 22:17:41.225  9449  9739 E AndroidRuntime: 	at org.thoughtcrime.securesms.service.WebRtcCallService.lambda$requestMembershipProof$10(WebRtcCallService.java:1088)
01-17 22:17:41.225  9449  9739 E AndroidRuntime: 	at org.thoughtcrime.securesms.service.WebRtcCallService.lambda$requestMembershipProof$10$WebRtcCallService(WebRtcCallService.java)
01-17 22:17:41.225  9449  9739 E AndroidRuntime: 	at org.thoughtcrime.securesms.service.-$$Lambda$WebRtcCallService$irzB9CmQl6bl_zS7x_Z_hOgXUG0.run(lambda)
01-17 22:17:41.225  9449  9739 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
01-17 22:17:41.225  9449  9739 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
01-17 22:17:41.225  9449  9739 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
01-19 17:14:47.223 14174 14205 E AndroidRuntime: FATAL EXCEPTION: signal-bounded-2
01-19 17:14:47.223 14174 14205 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 14174
01-19 17:14:47.223 14174 14205 E AndroidRuntime: java.lang.IndexOutOfBoundsException
01-19 17:14:47.223 14174 14205 E AndroidRuntime: 	at android.content.res.StringBlock.nativeGetString(Native Method)
01-19 17:14:47.223 14174 14205 E AndroidRuntime: 	at android.content.res.StringBlock.get(StringBlock.java:82)
01-19 17:14:47.223 14174 14205 E AndroidRuntime: 	at android.content.res.AssetManager.getThemeValue(AssetManager.java:269)
01-19 17:14:47.223 14174 14205 E AndroidRuntime: 	at android.content.res.ResourcesImpl$ThemeImpl.resolveAttribute(ResourcesImpl.java:1295)
01-19 17:14:47.223 14174 14205 E AndroidRuntime: 	at android.content.res.Resources$Theme.resolveAttribute(Resources.java:1538)
01-19 17:14:47.223 14174 14205 E AndroidRuntime: 	at org.thoughtcrime.securesms.util.ThemeUtil.getAttribute(ThemeUtil.java:93)
01-19 17:14:47.223 14174 14205 E AndroidRuntime: 	at org.thoughtcrime.securesms.util.ThemeUtil.isDarkTheme(ThemeUtil.java:28)
01-19 17:14:47.223 14174 14205 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.model.LiveUpdateMessage.toSpannable(LiveUpdateMessage.java:59)
01-19 17:14:47.223 14174 14205 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.model.LiveUpdateMessage.lambda$fromMessageDescription$1(LiveUpdateMessage.java:46)
01-19 17:14:47.223 14174 14205 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.model.-$$Lambda$LiveUpdateMessage$hlON42KJEOkK2x2yEx7XsQrASRM.apply(lambda)
01-19 17:14:47.223 14174 14205 E AndroidRuntime: 	at org.thoughtcrime.securesms.util.livedata.LiveDataUtil.lambda$null$2(LiveDataUtil.java:72)
01-19 17:14:47.223 14174 14205 E AndroidRuntime: 	at org.thoughtcrime.securesms.util.livedata.-$$Lambda$LiveDataUtil$TQJl5AtGFsXm1hslYBPQHKXESxE.run(lambda)
01-19 17:14:47.223 14174 14205 E AndroidRuntime: 	at org.thoughtcrime.securesms.util.concurrent.SerialMonoLifoExecutor.lambda$enqueue$0(SerialMonoLifoExecutor.java:44)
01-19 17:14:47.223 14174 14205 E AndroidRuntime: 	at org.thoughtcrime.securesms.util.concurrent.SerialMonoLifoExecutor.lambda$enqueue$0$SerialMonoLifoExecutor(SerialMonoLifoExecutor.java)
01-19 17:14:47.223 14174 14205 E AndroidRuntime: 	at org.thoughtcrime.securesms.util.concurrent.-$$Lambda$SerialMonoLifoExecutor$zGI5_MD8odfHaH2-Q_X27ikdsnk.run(lambda)
01-19 17:14:47.223 14174 14205 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
01-19 17:14:47.223 14174 14205 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
01-19 17:14:47.223 14174 14205 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
```
Also would you please Update your post (the first one) and check the missing box? As you indeed have found a bug.

**Comment by ascendingSun** [comment] 2021-01-21 02:21
@SamLS98 Does this happen with:
-A conversation other than 'Note to Self'
-Any empty conversation
-A populated conversation(a conversation where you have chat history with someone)

I tried on latest master branch and have not been able to reproduce this so far.

**Comment by Caerbannog** [comment] 2021-01-21 22:55
I could not reproduce the issue either.
Is your phone configured for "dark mode" ("battery saving" on my phone)?
Since the stacktrace contains `isDarkTheme()`, could you try reproducing the crash after switching the "dark mode" setting?

**Comment by ascendingSun** [comment] 2021-01-21 23:32
@Caerbannog @SamLS98 I tried with dark mode on and off during my test. I still could not reproduce this issue.

**Comment by SamLS98** [comment] 2021-01-22 06:34
@Caerbannog my phone doesn't have dark mode, I disabled reader mode, battery saver etc, and still happened.
@ascendingSun  yes in all those cases

**Closed** 2022-02-03 05:47 UTC
Labels: wontfix
