### ISSUE TITLE
Photos are not correctly displayed in chats

### ISSUE THREAD

**Issue by HiperFall** [signalapp/Signal-Android#10196] opened 2020-11-14 15:54 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I send or view old photos, they are half-displayed. It doesn't happen every time, but often. It can be fixed only if I clear app's cache. 

### Steps to reproduce
- Send a photo.
- View old photos.

**Actual result:** Sometimes photos in the chat are not properly displayed. 
**Expected result:** Photos have to be properly displayed.

### Screenshots
![2020-11-14 15 52 05](https://user-images.githubusercontent.com/11684093/99151206-5f8b2500-2691-11eb-8bf1-0ce2775d6545.jpg)

### Device info
**Device:** Redmi Note 9S.
**Android version:** 10.
**Signal version:** 4.76.3.

### Link to debug log
Is it neccessary?

**Comment by Nisc3d** [comment] 2020-11-14 22:56
Thanks for reporting this bug, but I think this is a duplicate of #9608.
If you want to help more you can post your debug logs there and if you have other comments on this issue you can also comment there.

**Comment by HiperFall** [comment] 2020-11-15 11:59
> Thanks for reporting this bug, but I think this is a duplicate of #9082.
> If you want to help more you can post your debug logs there and if you have other comments on this issue you can also comment there.

It's almost the same, but I haven't used the crop tool. I have only sent full-sized photos and just viewed some old photos.

**Comment by Nisc3d** [comment] 2020-11-15 22:28
The crop tool has nothing to do with it. It happens to people also without using the crop tool, but I leave this to the devs how they want to organize this.

**Closed** 2022-02-03 17:52 UTC
Labels: wontfix
