### ISSUE TITLE
Support for broadcast lists

### ISSUE THREAD

**Issue by Norbert80** [signalapp/Signal-Android#3301] opened 2015-06-01 20:58 UTC
Please support broadcast lists like Telegram or WhatsApp. Broadcast lists are sending messages to a defined list of recipients.

It shall be possible to include TextSecure PUSH and SMS/MMS contacts into one common broadcast list.

**Comment by benedetto** [comment] 2015-06-02 14:39
I first thought you were talking about simple groups, but then I looked it up. For those others who don't know what the OP is talking about: It is explained [here](https://www.whatsapp.com/faq/en/iphone/23782313).

Basically it's a fixed list of people to send a message to. However, it's not a group, as every recipient receives the message as if it was a message especially for them and if they reply, the reply goes only to the initial sender.

**Comment by agrajaghh** [comment] 2015-06-30 07:52
related to #413 (broadcast list for SMS)

**Comment by uiken** [comment] 2015-07-31 02:04
It would also be great if when composing a message we can select multiple recipients.

**Comment by Norbert80** [comment] 2015-08-11 07:13
It shall be possible to include TextSecure PUSH and SMS contacts within one broadcast list.

**Comment by riyapenn** [comment] 2015-11-19 03:00
Indirectly available through B listed on support page: http://support.whispersystems.org/hc/en-us/articles/213190647-Group-SMS

**Comment by agrajaghh** [comment] 2015-11-19 08:13
@riyapenn I don't think the invite feature fixes this. Its just an ugly workaround noby will use :grin:

**Comment by Norbert80** [comment] 2015-11-19 10:42
@riyapenn please reopen! You don't understand broadcast lists. They are for convenient frequently sending messages to defined list of receivers. This feature is to AVOID circumstances like the "workaround" you describe.

@moxie0 please reopen.

**Comment by generalmanager** [comment] 2015-11-19 11:09
@riyapenn Are you seriously suggesting to abuse the invite system with custom messages instead of enabling this actually useful feature by allowing to address messages (not just SMS as you seem to think) to multiple recipients?!

**Comment by heyimgay** [comment] 2015-12-02 00:36
@generalmanager please keep comments that add nothing to yourself.

**Comment by generalmanager** [comment] 2015-12-02 12:47
@heyimgay Did you really just send a notification to all contributers, two weeks after I wrote something which apparently offended you, even though it was neither directed at you, nor are you the TO?

My comment might not have been the most polite I ever wrote, which was caused by the frustration I felt when an important FR was closed by someone who apparently didn't understand the implications of it. The fact that it was reopened supports that line of thought.

But I'm most certainly going to let you tell me to shut my mouth. People who think they are entitled to such behaviour are the reason I'm supporting tools like Signal.
So either ignore me or go for some constructive criticism. But acting like your are in a playground and someone took your shovel away isn't gonna get you anywhere.

**Comment by gerdneuman** [comment] 2016-01-08 01:20
I am not a fan of broadcast UX. I have them in Threema but quickly stopped using because recipients cannot answer to all, and even do not know that's a message to more.

What I would like to have is an easy quick way to send a message to a small "instant" group, mostly just 2 people. E-mail has the perfect UX for this: Just press a :heavy_plus_sign: button and add another recipient. Recipient can then reply to all and see who has been informed.

In Signal we have single messages (resembles single mails) and group messages (resembles mailing lists). 

But there is no easy way sent a "Hi, we meet at five" to 2 people spontaneously without setting a up a static group before – and also allowing one of the 2 recipients to answer "No, let's meet at six" and all get the message and all know about it. I do not see how broadcast list could fulfill this user story.

**Comment by Blackbam1337** [comment] 2016-09-30 18:18
Really missing this feature just as it is implemented in Whatsapp. 

**I have a use case for this:** In my country there are secret parties which are being held at secret locations which the police and unwanted persons shall not know. Therefore location, date and time are sent within secret messages. If you have information about such an event you broadcast it to a certain group of your contacts (which may be about 30 persons or more, which you all trust). 

You sometimes edit this list but usually its almost the same persons. However you do not want to create a group as it shall not be traceable for others which persons you invited or you have contacted. Any answers to those invitations shall be only sent to you as a standard private message.

**Comment by saurik** [comment] 2017-08-15 12:15
If this feature were implemented, would you be able to send messages to hundreds or thousands of users? I have been attempting to find documentation of how the various mentioned rate limits work (as to find out what kinds of operations are inherently rate limited), and have so far not been able to find anything terribly useful :(. (I was asked a while ago to build a service to help undocumented people receive updates on immigration raids, and we all agreed that Signal would be an interesting platform for this, but I couldn't figure out if it was actually possible to send bulk. I figure I should finally just ask ;P.)

**Comment by Recte** [comment] 2018-01-02 19:30
I'd love to see this feature introduced to Signal. It's a big miss in relation to WhatsApp and very useful in situations where you'd like to invite multiple people for a party or just wish them a happy new year, for example.

By using a broadcast, people do not see the recipients phone numbers and are not able to reply to the "group". An often used feature back in my WhatsApp time(s).

**Comment by automated-signal** [comment] 2018-04-02 21:43
GitHub Issue Cleanup:
See #7598 for more information.

**Closed by automated-signal** 2018-04-02 21:43 UTC
Labels: feature
