### ISSUE TITLE
Import from plaintext backup fails.

### ISSUE THREAD

**Issue by pstratem** [signalapp/Signal-Android#7430] opened 2018-02-22 07:07 UTC
Import from plaintext backup fails.

Android 8.1.0
Signal 4.16.5
`
02-22 17:31:00.560  5238  5243 I zygote  : Do full code cache collection, code=124KB, data=95KB
02-22 17:31:00.560  5238  5243 I zygote  : After code cache collection, code=112KB, data=73KB
02-22 17:31:00.570  5238  5270 W PlaintextBackupImporter: importPlaintext()
02-22 17:31:00.825  5238  5243 I zygote  : Do partial code cache collection, code=124KB, data=97KB
02-22 17:31:00.825  5238  5243 I zygote  : After code cache collection, code=124KB, data=97KB
02-22 17:31:00.825  5238  5243 I zygote  : Increasing code cache capacity to 512KB
02-22 17:31:00.890  5238  5270 I zygote  : Deoptimizing void net.sqlcipher.database.SQLiteClosable.releaseReference() due to JIT inline cache
02-22 17:31:01.682  5290  5306 I zygote64: Waiting for a blocking GC ProfileSaver
02-22 17:31:01.709  5290  5306 I zygote64: WaitForGcToComplete blocked ProfileSaver on HeapTrim for 26.826ms
02-22 17:31:06.455  5238  5246 W SQLiteCompiledSql: Releasing statement in a finalizer. Please ensure that you explicitly call close() on your cursor: INSERT INTO sms (address, person, date_sent, date, protocol, read, status, type, reply_path_present,
02-22 17:31:06.455  5238  5246 W SQLiteCompiledSql: net.sqlcipher.database.DatabaseObjectNotClosedException: Application did not close the cursor or database object that was opened here
02-22 17:31:06.455  5238  5246 W SQLiteCompiledSql: 	at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:62)
02-22 17:31:06.455  5238  5246 W SQLiteCompiledSql: 	at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:109)
02-22 17:31:06.455  5238  5246 W SQLiteCompiledSql: 	at net.sqlcipher.database.SQLiteStatement.<init>(SQLiteStatement.java:39)
02-22 17:31:06.455  5238  5246 W SQLiteCompiledSql: 	at net.sqlcipher.database.SQLiteDatabase.compileStatement(SQLiteDatabase.java:1589)
02-22 17:31:06.455  5238  5246 W SQLiteCompiledSql: 	at org.thoughtcrime.securesms.database.SmsDatabase.createInsertStatement(SmsDatabase.java:760)
02-22 17:31:06.455  5238  5246 W SQLiteCompiledSql: 	at org.thoughtcrime.securesms.database.PlaintextBackupImporter.importPlaintextFromSd(PlaintextBackupImporter.java:36)
02-22 17:31:06.455  5238  5246 W SQLiteCompiledSql: 	at org.thoughtcrime.securesms.ImportExportFragment$ImportPlaintextBackupTask.doInBackground(ImportExportFragment.java:184)
02-22 17:31:06.455  5238  5246 W SQLiteCompiledSql: 	at org.thoughtcrime.securesms.ImportExportFragment$ImportPlaintextBackupTask.doInBackground(ImportExportFragment.java:142)
02-22 17:31:06.455  5238  5246 W SQLiteCompiledSql: 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
02-22 17:31:06.455  5238  5246 W SQLiteCompiledSql: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
02-22 17:31:06.455  5238  5246 W SQLiteCompiledSql: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
02-22 17:31:06.455  5238  5246 W SQLiteCompiledSql: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
02-22 17:31:06.455  5238  5246 W SQLiteCompiledSql: 	at java.lang.Thread.run(Thread.java:764)
02-22 17:31:10.864 25060 25090 I CastDatabase: Saving the database
02-22 17:31:10.877 25060 25090 I SQLiteCastStore: [CastNetworkInfo] saved: 0, skipped: 0, [CastDeviceInfo]: saved 0, skipped 0, Paired Guest Mode DeviceInfo] saved: 0, skipped: 0.
`

**Comment by junitas** [comment] 2018-02-22 16:33
Can you list the steps you took to cause this bug to happen and how someone could reproduce it? What was the expected behavior vs the observed behavior?

**Comment by joshproehl** [comment] 2018-02-22 16:52
I just discovered this github issue after uncovering this problem myself last night.

I'm not 100% sure if the issue I was having was caused by this bug, however the "Application did not close the cursor" was the only error I got in the debug log.
I was attempting to import a 12MB signal backup file, and was finally able to succeed by breaking it apart into 15 smaller files. I appeared to be able to import anything under ~4k lines reliably, 4-6k lines unreliably, and could not succeed in importing any file over 6k messages.

Once again, not sure that this bug was the cause, but that may give you a method to reliably reproduce the issue.

**Comment by pstratem** [comment] 2018-02-22 22:59
this issue is triggered by using the import plaintext backup function, nothing more

there's a one line pull request that fixes this

**Comment by Ilnahro** [comment] 2018-02-23 11:35
The issue is still present in 4.16.6.

**Comment by DarthSpock** [comment] 2018-03-01 14:10
I have this issue where it tries to import and Signal crashes asking if I want to restart the app. Really bad timing since my phone wiped itself yesterday. Never had issues importing backups before.

**Comment by Ilnahro** [comment] 2018-03-01 14:13
Yeah, I am in a similar situation. The bug persists in 4.16.9

**Comment by DarthSpock** [comment] 2018-03-01 14:17
I signed up for the beta, hopefully that gets the fix to me a bit faster. I trust there's an easy way to remove the "tester" status once this issue is resolved.

**Comment by risole** [comment] 2018-03-06 19:34
I seem to be suffering from this bug too. I have a 1.7MB SignalPlaintextBackup.xml file that consistently causes Signal to crash in Android 8.1.0. I have not tried breaking the file up into smaller pieces and importing the pieces separately. How can I make use of the fix mentioned by @pstratem ? Specifically, "this issue is triggered by using the import plaintext backup function, nothing more [same is true for me]
there's a one line pull request that fixes this [I'd like to be able to use this one line pull request too; does that mean side loading an app or using a non-released (via the Play Store or the apk from Signal.org)? If so, can someone post a link and/or instructions?"

**Comment by DarthSpock** [comment] 2018-03-06 19:45
Signing up for beta didn't update the app at all, still shows the same version, I'm guessing new code hasn't been committed yet. If there is a one-liner that acts as a workaround to get xml backups imported into Signal, I would like to see it pushed to beta unless this will require a terminal app that doesn't require root privileges in order for the code to run.

**Comment by DarthSpock** [comment] 2018-03-08 23:28
My phone just updated to 4.17 and still have the issue: https://debuglogs.org/8cadeece49c9427e11c74e02da26ef48c9f2c2d758f39e5adbb64511168d75d6

**Comment by nwbt** [comment] 2018-03-10 20:08
I see this is fixed. You guys are super quick! Out of curiosity, when will this get rolled out to the Google Play Store?

**Comment by DarthSpock** [comment] 2018-03-10 23:14
@nwbt  It's only fixed for backups created with 4.17.1 

@moxie0  are you working on getting backups created with older versions working? I'd hate to find out everything I had backed up is gone forever unless I revert the version first. I like to upgrade not downgrade. Here's a new debug log in 7.17.1 in case it makes any difference. https://debuglogs.org/872b722d8fe60e535d6c9a4f38bf886a25044d9e07c3873de83179f0c4aec252

**Comment by DarthSpock** [comment] 2018-03-13 12:42
I was able to successfully import my plain-text backup after upgrading to 4.17.2. if another person can also repro success, this issue can be closed.

**Comment by risole** [comment] 2018-03-15 20:23
Thanks for posting this update, @DarthSpock.

How do I upgrade to 4.17.2? The .apk at https://signal.org/android/apk/ is still 4.15.5. There's no new update listed in the Play Store. My F-Droid app is reporting "Error getting index file" right now (so I can't see if there is an update in the F-Droid repo) which I'm sure is unrelated to this problem in Signal.

I know how to sideload (with "adb install -r Signal-4.17.2.apk"), but where is the 4.17.2 version of Signal.apk?

Is 4.17.2 not yet production-ready? I'm willing to try updating to 4.17.2 to fix this problem, but if it is not yet production-ready, then I'm nonetheless a bit concerned about creating additional problems for myself in updating. Anything I can do to mitigate those concerns? Make frequent SignalPlaintextBackup.xml backups I suppose?

**Comment by DarthSpock** [comment] 2018-03-16 01:27
I'm using the Google Play version and am now on 4.17.3. The signal.org apk
is out of date.

**Comment by risole** [comment] 2018-03-16 17:33
As of this minute (1332 EDT), when I look at https://play.google.com/store/apps/details?id=org.thoughtcrime.securesms&hl=en I see the following details:

Updated
March 5, 2018

Current Version
4.16.9

I wonder what's different between your view of the Play Store and mine...

How do I use the Signal app in Android to check the version number? I tried Settings and Help, but don't see anything about version.

**Comment by Ilnahro** [comment] 2018-03-16 17:35
He is signed up as a beta tester.
Current stable is 4.16.9
Current beta is 4.17.3

**Comment by DarthSpock** [comment] 2018-03-16 18:03
That is correct. I did say I signed up up above in case it made a difference in resolving the issue. Doing so has indeed resolved the issue and I haven't discovered any other issues yet for communicating with others via Signal and the people I do communicate with use the stable version. I'm sure there are bugs but I'm not hitting them fortunately.

**Comment by nikksno** [comment] 2018-03-18 22:55
I'm having the same issue here. Exported / imported this same dataset in the past over 4 different phones and now on the same phone as before but freshly wiped it's failing.

I've removed all log entries I was sure weren't relevant, you'll find some that most likely still aren't but I left in just to be sure:

```
03-18 17:48:43.201 21028 21053 W PlaintextBackupImporter: importPlaintext()
03-18 17:48:43.401   554  1179 E SurfaceFlinger: Failed to find layer (org.thoughtcrime.securesms/org.thoughtcrime.securesms.ImportExportActivity#1) in layer parent (no-parent).
03-18 17:48:43.421  3274  3373 I QCNEJ/CndHalConnector: -> SND notifyWifiStatusChanged(RatInfo{type=1, subType=101, state=CONNECTED, v4=IfaceAddrPair{iface=wlan0, addr=xxx.xxx.xxx.xxx}, v6=IfaceAddrPair{iface=, addr=}, timestamp=2018-03-18 17:48:43.421, isAndroidValidated=true, netHandle=xxxxxxxx, slotIdx=0} WifiInfo{freq=FIVE_GHz, state=3, ssid=yyyyyyyy, bssid=zzzzzzzz, dns=[8.8.8.8, 8.8.4.4, 0.0.0.0, 0.0.0.0, ]})
03-18 17:48:45.280   541   541 E lowmemorykiller: Error opening /dev/memcg/apps/uid_99017/pid_13928/memory.soft_limit_in_bytes; errno=2
03-18 17:48:45.308  4154 21112 I Authzen : [DeviceStateSyncManager] The server is in sync with current state. Nothing to do
03-18 17:48:46.316   473 15267 D hardware_info: hw_info_append_hw_type : device_name = speaker
03-18 17:48:46.316   473 15267 D msm8974_platform: platform_split_snd_device: snd_device(2) num devices(0) new_snd_devices(0)
03-18 17:48:47.037   541   541 E lowmemorykiller: Error opening /dev/memcg/apps/uid_99017/pid_13928/memory.soft_limit_in_bytes; errno=2
03-18 17:48:47.040 21028 21038 I zygote  : Background concurrent copying GC freed 236859(9MB) AllocSpace objects, 10(2MB) LOS objects, 57% free, 8MB/20MB, paused 119us total 179.426ms
03-18 17:48:47.122 21028 21036 W SQLiteCompiledSql: Releasing statement in a finalizer. Please ensure that you explicitly call close() on your cursor: INSERT INTO sms (address, person, date_sent, date, protocol, read, status, type, reply_path_present,
03-18 17:48:47.122 21028 21036 W SQLiteCompiledSql: net.sqlcipher.database.DatabaseObjectNotClosedException: Application did not close the cursor or database object that was opened here
03-18 17:48:47.122 21028 21036 W SQLiteCompiledSql: 	at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:62)
03-18 17:48:47.122 21028 21036 W SQLiteCompiledSql: 	at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:109)
03-18 17:48:47.122 21028 21036 W SQLiteCompiledSql: 	at net.sqlcipher.database.SQLiteStatement.<init>(SQLiteStatement.java:39)
03-18 17:48:47.122 21028 21036 W SQLiteCompiledSql: 	at net.sqlcipher.database.SQLiteDatabase.compileStatement(SQLiteDatabase.java:1589)
03-18 17:48:47.122 21028 21036 W SQLiteCompiledSql: 	at org.thoughtcrime.securesms.database.SmsDatabase.createInsertStatement(SmsDatabase.java:764)
03-18 17:48:47.122 21028 21036 W SQLiteCompiledSql: 	at org.thoughtcrime.securesms.database.PlaintextBackupImporter.importPlaintextFromSd(PlaintextBackupImporter.java:36)
03-18 17:48:47.122 21028 21036 W SQLiteCompiledSql: 	at org.thoughtcrime.securesms.ImportExportFragment$ImportPlaintextBackupTask.doInBackground(ImportExportFragment.java:184)
03-18 17:48:47.122 21028 21036 W SQLiteCompiledSql: 	at org.thoughtcrime.securesms.ImportExportFragment$ImportPlaintextBackupTask.doInBackground(ImportExportFragment.java:142)
03-18 17:48:47.122 21028 21036 W SQLiteCompiledSql: 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
03-18 17:48:47.122 21028 21036 W SQLiteCompiledSql: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
03-18 17:48:47.122 21028 21036 W SQLiteCompiledSql: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
03-18 17:48:47.122 21028 21036 W SQLiteCompiledSql: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
03-18 17:48:47.122 21028 21036 W SQLiteCompiledSql: 	at java.lang.Thread.run(Thread.java:764)
03-18 17:48:50.053  2220  3390 I LOWI-8.5.0.1: [LOWI-Scan] lowi_close_record:Scan completed in 176386600ms and Recieved 37 APs scan results
03-18 17:48:52.317   541   541 E lowmemorykiller: Error opening /dev/memcg/apps/uid_99017/pid_13928/memory.soft_limit_in_bytes; errno=2
03-18 17:48:52.490 31776 31798 I PlayCommon: [603] com.google.android.play.b.h.e(263): Preparing logs for uploading
03-18 17:48:52.490 31776 31798 I PlayCommon: [603] com.google.android.play.b.h.e(267): No file ready to send
03-18 17:48:55.120 21028 21038 I zygote  : Background concurrent copying GC freed 232025(9MB) AllocSpace objects, 0(0B) LOS objects, 51% free, 11MB/23MB, paused 150us total 217.132ms
03-18 17:49:03.780 21028 21038 I zygote  : Background concurrent copying GC freed 246364(9MB) AllocSpace objects, 0(0B) LOS objects, 49% free, 14MB/28MB, paused 127us total 229.976ms
03-18 17:49:03.949 21028 21034 I zygote  : Thread[3,tid=21034,WaitingInMainSignalCatcherLoop,Thread*=0xe6ff2a00,peer=0xa5280218,"Signal Catcher"]: reacting to signal 3
03-18 17:49:03.949 21028 21034 I zygote  : 
03-18 17:49:04.035  2143  4271 I LocSvc_libulp: ulp_msg_process_system_update: systemEvent:5 
03-18 17:49:04.035  2143  4271 I LocSvc_libulp: ulp_msg_process_start_req, at ulp state = 1
03-18 17:49:04.036  2143  3258 I LocSvc_api_v02: ---> locClientSendReq line 2102 QMI_LOC_GET_BEST_AVAILABLE_POSITION_REQ_V02
03-18 17:49:04.044  2143  3266 I LocSvc_ApiV02: <--- globalRespCb line 141 QMI_LOC_GET_BEST_AVAILABLE_POSITION_REQ_V02
03-18 17:49:04.044  2143  4271 I LocSvc_libulp: ulp_brain_process_zpp_position_report, report ZPP position to providers,report_position = 1
03-18 17:49:04.044  2143  3258 V LocSvc_HIDL_IzatProvider: [onLocationChanged][67] [HS] =>>>> [HC]
03-18 17:49:04.045  2299  3457 V LocSvc_HIDL_IzatProvider_jni: [onLocationChanged][136] [HC] <<= [HS]
03-18 17:49:04.096  2171  2171 I /system/bin/tombstoned: received crash request for pid 21028
03-18 17:49:04.096  2171  2171 W tombstoned: type=1400 audit(0.0:20411): avc: granted { append } for path="/data/anr/trace_01" dev="dm-0" ino=85819 scontext=u:r:tombstoned:s0 tcontext=u:object_r:anr_data_file:s0 tclass=file
03-18 17:49:04.100 21028 21034 I zygote  : Wrote stack traces to '[tombstoned]'
03-18 17:49:04.101  2171  2171 E /system/bin/tombstoned: Traces for pid 21028 written to: /data/anr/trace_01
03-18 17:49:08.958  2299 26839 W ActivityManager:   Force finishing activity org.thoughtcrime.securesms/.ImportExportActivity
03-18 17:49:08.969 21028 21028 W PassphraseRequiredActionBarActivity: onPause()
03-18 17:49:08.984  2299  2383 I ActivityManager: Showing crash dialog for package org.thoughtcrime.securesms u0
03-18 17:49:08.987   541   541 E lowmemorykiller: Error opening /dev/memcg/apps/uid_99017/pid_13928/memory.soft_limit_in_bytes; errno=2
03-18 17:49:09.011 21028 21028 W KeyCachingService: onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_STOP_EVENT
03-18 17:49:09.012 21028 21028 W KeyCachingService: Decrementing activity count...
03-18 17:49:09.012 21028 21028 W MessageRetrievalService: Active Count: 0
03-18 17:49:09.020 21028 21028 W PassphraseRequiredActionBarActivity: onResume()
03-18 17:49:09.020  2299  2381 W BroadcastQueue: Skipping deliver [background] BroadcastRecord{ccc627c u-1 android.net.conn.CONNECTIVITY_CHANGE} to ReceiverList{713404e 21028 org.thoughtcrime.securesms/10169/u0 remote:f759f49}: process gone or crashing
03-18 17:49:09.039   541   541 E lowmemorykiller: Error opening /dev/memcg/apps/uid_99017/pid_13928/memory.soft_limit_in_bytes; errno=2
03-18 17:49:09.090  2299  8622 I OpenGLRenderer: Initialized EGL, version 1.4
03-18 17:49:09.091  2299  8622 D OpenGLRenderer: Swap behavior 2
03-18 17:49:09.094 21028 21028 W KeyCachingService: onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_START_EVENT
03-18 17:49:09.094 21028 21028 W KeyCachingService: Incrementing activity count...
03-18 17:49:09.095 21028 21028 W MessageRetrievalService: Active Count: 1
03-18 17:49:09.415 21028 21028 W PassphraseRequiredActionBarActivity: onDestroy()
```

Tried this 20 times across several days and reboots. Signal always consistently crashes about 20 seconds in. Thank you.

**Comment by AVerm** [comment] 2018-03-21 04:16
I am still having this error with importing plaintext backup AND importing an identical device sms log. Both claim success but do not change the messages Signal shows. Note: the backup file is a whopping 13 MB, which is mostly due to a one-on-one conversation totaling 29,345 messages.
Device: Huwei Mate 10 (BLA-A09)
Android: 8.0.0
Ram: 6.0 GB
Signal Version: 4.17.4

**Comment by jaylinski** [comment] 2018-03-25 18:03
Same issue for me with the latest beta (4.17.5).

I got the import working by splitting my 2MB backup into three chunks.

**Comment by nikksno** [comment] 2018-03-29 17:43
Same here, split everything into 4200-message files and it worked. Also, why is it that signal can only *import* encrypted archives but not *produce* them?

**Comment by randlet** [comment] 2018-04-01 00:54
Same issue for me.  I had around ~16k messages but trying to import it to Signal caused a crash every time.  Splitting it into 4 files allowed them all to import successfully although Signal still crashed after every import.

**Comment by automated-signal** [comment] 2018-04-03 05:03
GitHub Issue Cleanup:
See #7598 for more information.

**Closed by automated-signal** 2018-04-03 05:03 UTC
Labels: bug
