### ISSUE TITLE
Add server status on homepage

### ISSUE THREAD

**Issue by natrius** [signalapp/Signal-Android#7461] opened 2018-03-05 08:42 UTC
Please add the server status on the homepage somehow visible. If you have just one server because you don't want a federated network, fine, but manage it.

This is the exact reason why people are arguing for the federated network and not for a centralized server.

And no information anywhere from "official" is also really, really bad.

**Comment by ruicruzpt** [comment] 2018-03-05 08:45
I agree with you, however this is not the right place to ask for it. 

But, still, I agree with you. ;)

**Comment by natrius** [comment] 2018-03-05 08:52
As there is no github for the homepage itself, i wrote it here. Signal-server maybe?

**Comment by Cerberus0** [comment] 2018-03-05 10:02
This is a duplicate of https://github.com/signalapp/Signal-Android/issues/3835

**Comment by moxie0** [comment] 2018-03-05 20:10
Please do not use GH issues for discussion, and please do not delete the issue template.

**Closed by moxie0** 2018-03-05 20:10 UTC
