### ISSUE TITLE
Can't answer the call, when Signal Desktop app is running in the same time

### ISSUE THREAD

**Issue by f1sz** [signalapp/Signal-Android#11091] opened 2021-03-12 06:18 UTC
Hello,
I cannot answer the call on my Android phone, when Signal Desktop (Windows) app is running in the same time. I can see the incomming call notification, but when I click on the answer call button - nothing happens.

When Windows Signal is not running - everything is fine.

Signal Android version: 5.4.12 
Signal Windows version: 1.40.1

**Comment by hiqua** [comment] 2021-03-12 09:40
Debug log?
Duplicate of https://github.com/signalapp/Signal-Android/issues/10623 ?

**Comment by f1sz** [comment] 2021-03-12 10:55
Debug log attached: https://debuglogs.org/90eb13f2c79eebc0eec90ae7aee3ec84dd1bee02f79b7b81d96a7db886b73856
Sorry - I've searched through issues, but didn't found it. Yup, seem to be same issue as #10623

**Comment by greyson-signal** [comment] 2021-03-12 16:41
Closing as duplicate of #10623

**Closed by greyson-signal** 2021-03-12 16:41 UTC
