### ISSUE TITLE
Backup timestamp only displays in locale.us not default language

### ISSUE THREAD

**Issue by Sgn-32** [signalapp/Signal-Android#8986] opened 2019-08-16 15:02 UTC
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The backup time is displayed under "Settings -> Chats and Media -> Backups" in English in every other language setting.

### Steps to reproduce
- set a language different from english
- go to "Settings -> Chats and Media -> Backups"
- look at the displayed time of "Last backup"

**Actual result:** the "Last backup" time is displayed in english even if an other language is set in Signal
**Expected result:** the "Last backup" time is displayed in the default language of Signal

### Screenshots
![Screenshot_20190814-152657](https://user-images.githubusercontent.com/49990901/63176032-75044000-c045-11e9-8bcb-e44ef031ee76.png)
![Screenshot_20190816-070524](https://user-images.githubusercontent.com/49990901/63176034-75044000-c045-11e9-9a37-bf6dedcf5d88.png)

### Device info
**Signal version:** 4.45.2

should be this source code:

Signal-Android/src/org/thoughtcrime/securesms/preferences/ChatsPreferenceFragment.java

private void setBackupSummary() {
    findPreference(TextSecurePreferences.BACKUP_NOW)
        .setSummary(String.format(getString(R.string.ChatsPreferenceFragment_last_backup_s), BackupUtil.getLastBackupTime(getContext(), Locale.US)));
  }

**Comment by Meteor0id** [comment] 2020-05-06 11:04
This issue is a duplicate of #8842

**Closed** 2020-05-14 14:31 UTC
