### ISSUE TITLE
In "All Media" of group chats, images sent by other people do not load when tapped directly (but show when swiped to them)

### ISSUE THREAD

**Issue by Natanji** [signalapp/Signal-Android#7643] opened 2018-04-05 13:38 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I have a bunch of group chats in which many images (100+) have accumulated over time. I noticed that only some of them are viewable when tapping on them in the "all media" view, while others bring up only a completely black screen with the heading "Medieninhalte..." on which both the share and save buttons do not function, and pressing "delete" in the three dot menu does not in fact delete the image. (I can still delete it by the new longpress method from the All Media overview).

Other images DO show up however when I tap on them, and once I selected such an image, I can access the other images by swiping left and right. To clarify, let's say that in All Media, there are the images A B C D E in that order, and A through D do not display when tapped but E does; then I can keep swiping to the right to display D, C, B and A.

Now the thing I consistently noticed about the images for which this works and for which it doesn't is: the images that don't show while tapping are from messages from other people. The images that I posted to the group chat load consistently (showing "You" in the headline). Indeed, this is 100% reproducible for me, see below - but only in group chats. 1-to-1 chats are not affected.

I have confirmed with a friend's phone which is still on 4.17.5 that this problem does not exist in their phone, so perhaps this is a regression introduced by pull #7527 since this changed the All Media stuff.

### Steps to reproduce
- Open a new group chat (even with only a single other person)
- Have them send you an image
- Open "All Media" for the conversation
- Tapping the image thumbnail results in the media activity opening but not displaying the image (everything is black and the sender's name is not in the headline)
- Now send an own image to the other person
- The image you sent is possible to access via "All Media", and by the swiping workaround you can also access the image the other party sent; but directly accessing their image still doesn't work.

**Actual result:** When tapping an image thumbnail in "all media" that was sent by another person, it is not shown.
**Expected result:** The image is shown, just like media from messages that I sent myself.

### Device info
**Device:** Oneplus 3
**Android version:** 8.0.0
**Signal version:** 4.18.1

### Link to debug log
https://debuglogs.org/a8604af1dcbc4a81f2a860aa1bde352e286fdca3887cc19a974ea2e586607c9d

**Comment by FeuRenard** [comment] 2018-04-05 14:30
This issue is a duplicate of #7609 and is fixed by #7387 in Signal version 4.19.

**Closed** 2018-04-05 14:31 UTC

**Comment by Natanji** [comment] 2018-04-05 14:49
Thank you, from the title of the other bug I didn't know this was the same issue.
