### ISSUE TITLE
Bad people sorting for non-English country

### ISSUE THREAD

**Issue by SanoKriss** [signalapp/Signal-Android#10635] opened 2021-01-14 18:10 UTC
Hi,
I'm from Slovakia where we have diacritics at character and specific sorting for example:
Cica
Číslo
Cudný

you should use something like this in sort (Kotlin fragment)
`    override fun compareTo(other: world): Int {
        var result: Int
        val collator = Collator.getInstance(Locale.getDefault())
        collator.strength = Collator.SECONDARY

        result = collator.compare(this.displayMeno.toString(), other.displayMeno.toString())

....
`

**Comment by ChewTeaYeah** [comment] 2021-01-14 20:28
This issue seems to be a duplicate of #10409

**Comment by SanoKriss** [comment] 2022-01-30 11:00
This is still relevant and not fixed.

**Comment by alex-signal** [comment] 2022-01-31 16:04
We're looking into our options here. Sorting in-memory isn't realistic because we don't want to load contacts into memory unnecessarily (imagine someone sync'd an active directory and has 20k contacts) so we want to do this at the database ORDER BY level. Unfortunately, while Android supports COLLATE LOCALIZED, SQLCipher does not, so we need to take a look at the best way to either reintroduce the LOCALIZED Collation or create a normalized database column to sort via.

**Comment by SanoKriss** [comment] 2022-02-07 17:00
It's really problem load 20K contacts? We are talking about Nokia 3210 or modern phones with gigabytes memory :) ?
Or you can use loadable extension as is mentioned here [https://discuss.zetetic.net/t/workaround-for-using-androids-localized-collator-after-3-5-0-update/1515/13](url)
It is really awkward for non-english world...
thanks

**Comment by alex-signal** [comment] 2022-02-08 13:30
Yes, it is. Many people utilize devices with very low (1GB or less) RAM, and much of that RAM is in use by either the operating system or other applications. The fix here will likely be storing some kind of normalized value in a separate column.

**Comment by SanoKriss** [comment] 2022-02-09 08:15
Separate column is also good idea, not perfect but usable. Just for sure, you mean use something like:
`import java.text.Normalizer;

public static String stripAccents(String s) 
{
    s = Normalizer.normalize(s, Normalizer.Form.NFD);
    s = s.replaceAll("[\\p{InCombiningDiacriticalMarks}]", "");
    return s;
}`
I'm using that in several projects and work fine, especially for full text searching

**Closed** 2022-04-21 08:29 UTC
Labels: wontfix
