### ISSUE TITLE
Cannot receive MMS messages from non-signal users (Android, T-Mobile)

### ISSUE THREAD

**Issue by IrkenEngineer** [signalapp/Signal-Android#9272] opened 2019-12-12 20:20 UTC
- [x] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I cannot download MMS messages from non-signal users. This remains true after at least one app update, uninstalling/reinstalling, rebooting my phone, enabling WiFi calling, confirming my configuration with my carrier, and even changing ROMs on my phone.

### Steps to reproduce
- Receive media message (image or group text) from Signal user, successful result
- Receive media message (image or group text) from non-Signal user, unsuccessful result
- "Tap to retry", result remains unsuccessful

**Actual result:** Unable to receive any kind of MMS message from non-Signal users.
**Expected result:** Ability to receive MMS messages as normal from all users.

### Screenshots
![Screenshot_20191212-105047_Signal](https://user-images.githubusercontent.com/29724031/70740725-a1b42580-1cce-11ea-8a0d-3dd5df7a2036.png)

### Device info
**Device:** Motorola Moto G5 Plus (Potter)
**Android version:** 9.0
**Signal version:** 4.50.5
**ROM:** Ressurection Remix v7.0.2-20190918

### Link to debug log
https://debuglogs.org/6330909a439146a00bc99a968b2c34c21bab0349e9b15428aa4269e9734b9f88

**Comment by Tursko** [comment] 2019-12-12 20:54
This is a duplicate of https://github.com/signalapp/Signal-Android/issues/9173

@greyson-signal recently created a test build to fix this issue. Close this issue and submit your debug log there ^

**Comment by IrkenEngineer** [comment] 2019-12-13 00:26
Apologies, I did see that, but figured it might be a network-specific issue.

**Closed** 2019-12-13 00:26 UTC
