### ISSUE TITLE
recent versions of ts lag terribly

### ISSUE THREAD

**Issue by ghost** [signalapp/Signal-Android#3651] opened 2015-07-13 19:46 UTC
I don't know if it's thw colors or something else, but ts has become way less responsive than it used to be. Whenever i type a message it takes a fraction of a second for the letters to appear, it's a pain.
This is the log after sending some messages, hopefully it helps https://gist.github.com/3af07e4dc4b3678eb97c

**Comment by oaim** [comment] 2015-07-22 18:29
Some more information.
1. Open a conversation, start typing. Everything works smoothly
2. Hit sent, and start typing a new message while the previous message is being sent. This is when I experience a huge lag

It looks like the problem is that there is something really slow with sending messages. I'd already noticed that ts is slower than other apps at sending messages, and found a partial answer here (https://github.com/WhisperSystems/TextSecure/issues/981). Maybe it's also a UI issue, but it's your app so you tell me.
Thanks!

**Comment by oaim** [comment] 2015-07-25 08:33
I happen to have some free time, can I help find the cause for this with some magical tool?

**Comment by oaim** [comment] 2015-07-28 06:52
I found the culprit!
I have trim activated after 5000 messages.( Most of my conversation have 5000 messages)
Deactivating the trim and deleting/recreating a thread basically fixes the problem. Sending several messages onr after the other is now WAY faster. There is still a lag while a message is being sent, but it isn't that bad because it lasts for a fraction of a second (the message gets sent pretty fast, as I said). The speed of sending has dramatically improved.
Maybe textsecure shouldn't load all the messages of a conversation on opening, but only the 100 most recent? Or maybe it's a problem with the trim feature... hope this comment helps

**Comment by Dyras** [comment] 2015-08-05 11:05
I can confirm that sending messages is really slow for me lately. I'm gonna check out if disabling trim helps.

**Comment by oaim** [comment] 2015-08-05 11:39
Can you try deleting and recreating the conversation? That fixed the problem for me (until the conversation got big again)

**Comment by McLoo** [comment] 2015-08-05 11:49
I'd wait with deleting until the performance changes @mcginty is working on are merged - unless you don't need your conversation data...

**Comment by oaim** [comment] 2015-08-06 20:40
Not solved for me in 2.25

**Comment by oaim** [comment] 2015-08-17 20:16
Surprisingly (are you surprised?) the Samsung default keyboard may have been part of the problem. Using SwiftKey doesn't make the keyboard lag *at all*. Don't know why...

**Comment by automated-signal** [comment] 2018-04-02 21:48
GitHub Issue Cleanup:
See #7598 for more information.

**Closed by automated-signal** 2018-04-02 21:48 UTC
Labels: performance
