### ISSUE TITLE
No sound notification message / call issue

### ISSUE THREAD

**Issue by eglyn** [signalapp/Signal-Android#11036] opened 2021-02-26 08:49 UTC
Hi everybody; 

I have 2 issues with notifications: 
first one, when I receive a message, there is no sound notification. Only visual popup on the lock screen. The notification is already setup in signal app (and mode dnd disable of course). The notification works on every other app :/

And the second issue is when someone call me, my phone ring, but only ring... there is no notification on the screen, I have to open signal app (when I found that was signal) and I see the call once in the app.

My wife has same both issues on her phone, we have a Xiaomi redmi note 7 and redmi note 8 on MIUI 12

Is there a way to resolve this issues ? 

Thx :)

**Comment by Kwasow** [comment] 2021-02-26 08:59
I'm also experiencing the issue - my screen will only light up when someone is calling and only when I unlock the phone and go into Signal can I answer the call

**Comment by oxygi** [comment] 2021-02-26 10:03
Same here.

**Comment by Kwasow** [comment] 2021-02-26 10:07
I've checked Facebook Messenger for calls and the behavior is that when someone calls you, you get a fullscreen call interface - just as if they were calling you with your phone number over a GSM network

**Comment by Kwasow** [comment] 2021-02-26 10:12
# Bug description
_For the sake of order here is the bug description following the template:_

- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Answering a Signal call requires unlocking the device

### Steps to reproduce
- Lock your phone
- Have someone call you on Signal

**Actual result:** The screen ligths up, but there is no way to answer the call without unlocking the phone.
**Expected result:** A fullscreen UI appears to answer the call

### Device info
**Device:** Redmi Note 9 Pro (and others)
**Android version:** 10.0
**Signal version:** 5.4.9

@eglyn Could you please update the post to be only about the calling issue and open a separate issue with notifications?

**Comment by Kwasow** [comment] 2021-02-26 10:14
Also, have you checked under Settings > Apps > Manage Apps > Signal > Notifications > Default, that everything is setup correctly? My notifications stopped working after some update, because these settings turned off for some reason (also using MIUI 12)

**Comment by Kwasow** [comment] 2021-02-26 10:19
Oh, sorry guys - I got a little excited here with solving an issue that doesn't exist. 
***The steps to resolve the issues on MIUI are:***
1. Go into: Settings > Apps > Manage Apps > Signal > Notifications.
2. Under "Default" check if notification sounds are on and that they are set to show on lock screen
3. Do the same for the "Calls" category.

The issue appeared after a MIUI update in my case, because somehow they got reset or reverted to an older state. Checking and fixing these settings fixed it for me. Hope that helps

**Comment by eglyn** [comment] 2021-02-26 10:47
> Oh, sorry guys - I got a little excited here with solving an issue that doesn't exist.
> _**The steps to resolve the issues on MIUI are:**_
> 
> 1. Go into: Settings > Apps > Manage Apps > Signal > Notifications.
> 2. Under "Default" check if notification sounds are on and that they are set to show on lock screen
> 3. Do the same for the "Calls" category.
> 
> The issue appeared after a MIUI update in my case, because somehow they got reset or reverted to an older state. Checking and fixing these settings fixed it for me. Hope that helps

That's it ! Sound was unchecked...

**Comment by Kwasow** [comment] 2021-02-26 10:50
> 
> That's it ! Sound was unchecked...
> 
> Thx ! :)

Please close the issue if it's resolved

**Closed** 2021-02-26 10:50 UTC
