### ISSUE TITLE
Can't establish (send/receive) any calls

### ISSUE THREAD

**Issue by iox86** [signalapp/Signal-Android#7895] opened 2018-06-12 20:17 UTC
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal calls always get stuck "connecting" and do not get established on a Samsung Galaxy S9. This does not happen on an iPhone 7 under similar network conditions. 

Issue is very similar to issue 7375. It happens on many different networks.

Signal text messages remain unaffected, even when a call cannot be established between the devices, messages go through and lost call notifications arrive too. But no calls can be established in either direction.

### Steps to reproduce
Make a Signal call to or from a Galaxy S9+.

**Actual result:** 
Call is not established.

**Expected result:** 
Call should be established.

### Screenshots
Visually very similar to issue 7375.

### Device info
**Device:** Samsung Galaxy S9+
**Android version:** 8.0.0
**Signal version:** 4.19.3

### Link to debug log
https://debuglogs.org/b88cec4323b9ef59a9773f5e2bcda0ac3ce1b04e2157d7c72a67baefe295c537

**Comment by cegg1** [comment] 2018-06-15 19:40
Initially I thought that #7375 was related to the Pixel 2 but I have since realized that the culprit seems to be the EE UK mobile network, not the Pixel 2.

When I use a different mobile network instead of EE UK, Signal calls work flawlessly. 

Have you tried using a different ISP and/or asking your contact to use a different ISP? 

What mobile network are you using when you experience this problem?

**Comment by sibrahi5** [comment] 2018-06-23 01:06
I am having the same issue. I have a LG Stylo 3 Plus running Android 7.0. Signal calls used to work, but now no longer do. It's been a few versions since it has stopped working now. I am using T-Mobile, and have been using it. I have tried different ISPs, using a VPN, etc, with no luck. I can submit my additional debug logs as well, if necessary.

**Comment by szotsaki** [comment] 2018-07-07 11:48
Perhaps a duplicate of #7733.

**Comment by greyson-signal** [comment] 2018-12-15 00:37
> Perhaps a duplicate of #7733.

**Closed by greyson-signal** 2018-12-15 00:37 UTC
Labels: calling
