### ISSUE TITLE
Images taken in Signal without tilting the phone are mirrored

### ISSUE THREAD

**Issue by Dyras** [signalapp/Signal-Android#7590] opened 2018-03-31 15:07 UTC
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If you open a chat and take a picture directly in the app (edit: with the selfie camera) and you keep your phone upright while doing so, the image is for some reason mirrored. If you tilt the phone 90º to make the image "widescreen" then it's not actually mirrored.

### Steps to reproduce
1. Open a chat with your local hot babe (or with your mom)
2. Press the camera to the right of the message box
3. Now, without tilting the phone (keep it upright) take a picture
4. Notice how it's mirrored when you preview it.
5. Try sending it, it's still mirrored.

6. Back out of the app and follow steps 1-2 again
7. Tilt the phone 90º to the left and take a picture
8. Now all of a sudden, it's not mirrored

**Actual result:** Images taken directly in Signal (edit: with the selfie camera) are mirrored, unless you tilt the phone
**Expected result:** Images should never be mirrored

### Screenshots
Image taken while the phone was upright:
![signal-2018-03-31-170002](https://user-images.githubusercontent.com/12563436/38164453-6022c0c0-3505-11e8-873b-45460bcf788f.jpeg)

Image taken while the phone was tilted:
![signal-2018-03-31-170016](https://user-images.githubusercontent.com/12563436/38164455-690ece9a-3505-11e8-9487-81371d26e97e.jpeg)

(The shirt is from an anime called One Punch Man, judge me all you want)

### Device info
**Device:** Moto G4
**Android version:** 7.0
**Signal version:** 4.17.5

Also confirmed to happen on a Nexus 6P with Oreo

### Link to debug log
https://debuglogs.org/b368fffc1683c9c94487e9ee015dae773db2f5add619889a7205bca9ea49dfa3

**Comment by 2-4601** [comment] 2018-03-31 16:08
Looks like a duplicate of #7122 unless it's a separate bug that it's not mirrored on landscape. I'm assuming the mirroring is the expected feature since Signal iOS does the same.

**Comment by moxie0** [comment] 2018-04-05 13:10
While it is indeed strange, this is the intended functionality. Most devices will display a "mirrored" image in the preview (since that's what looks "normal"), and then unmirror when the actual photo is taken. In our case, we're never taking the "actual" photo, since it's designed to be a fast screen-grab. We could "unmirror" in the preview, but then that might look strange to people who are used to looking in the mirror.

I think the real solution is to eventually get rid of our built-in "quick capture" photo thing and just use the intent to take a real photo.

**Closed by moxie0** 2018-04-05 13:10 UTC
