### ISSUE TITLE
Creating backup not working

### ISSUE THREAD

**Issue by oXvTV** [signalapp/Signal-Android#9548] opened 2020-04-17 19:15 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

Unable to create backup on Sony Xperia Z5 Compact despite chat backups being enabled

I have recently obtained a new phone and I would like to transfer my messages from Signal on my old phone to my new phone. Obviously, in order to do this, the first thing I need to do is create a backup on Signal on my old phone. Unfortunately, for some unknown reason, I am unable to create a backup on my Sony Xperia Z5 Compact running Android version 7.1.1 - when I press ‘Create backup’ nothing happens. This is despite the fact that I have enabled ‘Chat backups’, ensured the necessary permissions for Signal are enabled, ensured there is enough space to create a backup on the device, and I do not have an SD card in my device. Of course this is very frustrating as I would like to transfer my messages to my new phone so I can begin to use it. I have contacted the official email support but have not had a response yet. I would be very grateful for your help.

### Steps to reproduce
- open Signal and settings
- enable chat backups
- try to create backup by pressing 'Create backup'

**Actual result:**  

Nothing happens after running the steps above except that a Signal notification symbol very briefly appears in the notification panel at the top of the screen for a few milliseconds or so and then disappears.

**Expected result:** 

I'm not exactly sure what the expected behaviour should be but I imagine a backup should be created somehow.

### Device info

**Device:** Sony Xperia Z5 Compact E5823
**Android version:** 7.1.1
**Signal version:** 4.58.5

### Link to debug log

https://debuglogs.org/8b7508e70c8df7f703b29c25a536003c6f4f06d8f65045ff4b38558d4a983fa0

**Comment by haffenloher** [comment] 2020-04-22 15:52
Sorry to hear about that, sounds really frustrating :( This is a dupe of your own issue #9083 though, as well as of a couple of older ones. Here are some workarounds that others with the same `NoExternalStorageException` came up with:

https://github.com/signalapp/Signal-Android/issues/8054#issuecomment-409286620

> Somehow a hidden privacy feature in my lineage install didn't allow Signal to read the external storage even when the permission was granted. I've found it while trying to export an image from the app. When I tried this a message was shown, that Signal has no rights to write/read external storage.

I assume you aren't using LineageOS, though?

This might be more relevant: https://github.com/signalapp/Signal-Android/issues/8159#issue-356028406

> **User solution:** Force closing Signal messenger > go to Android app settings > Signal > Permissions > Disable storage > Exit and re-open settings > Re-enable Signal storage permission > Re-open Signal messenger > Run backup > Success

**Comment by oXvTV** [comment] 2020-04-22 16:14
Thanks so much for getting back to me and for the information.

I actually managed to get it working. Because my phone screen was broken and I couldn't use the touch screen to operate the phone I was having to operate it connecting the phone to a computer using a USB cable and Vysor software. Whenever I tried to backup through the app using Vysor, it didn't worked (this is the method I was trying for months). I then thought that having my phone connected to my computer via USB somehow was preventing backup. So I then tried the same thing using TeamViewer and, amazingly, this method worked. I'm not sure what difference this would have made but it seemed to work in any case. I was pretty relieved and happy when it eventually worked :-) I don't know why I forgot to mention this detail about my phone screen not working and having to operate it through other means. Perhaps someone would have realised what the problem was sooner if I had.

**Comment by haffenloher** [comment] 2020-04-22 19:45
Oh. Maybe Signal wasn't allowed to write to storage because the storage was simultaneously connected to your computer via USB? Really strange. Glad to hear you figured it out though! Could you please close your two bug reports then?

**Comment by oXvTV** [comment] 2020-04-22 20:28
I thought it could be something to do with that. Yes, will do now! Thanks in any case!

**Comment by BetaMaxHeadroom** [comment] 2021-04-14 01:10
I have the same issue. Any chance this can be reopened?

**Comment by greyson-signal** [comment] 2021-04-14 18:35
@BetaMaxHeadroom please post a log taken after experiencing the issue, thanks!

**Comment by BetaMaxHeadroom** [comment] 2021-04-14 19:06
Well, this is embarrassing. I removed my SD card, and I was able to create a backup in my phone's internal storage. I switched to a new phone recently. 

From
Device: Huawei Honor 8
Android Version: 7.0

To
Device: Samsung S20 5G
Android Version: 11

Maybe backups do not work well on older android versions. I love the app, and use it a daily. Thank you for the help. Please close this issue.

**Closed** 2021-04-14 19:43 UTC
