### ISSUE TITLE
Can't send Images 

### ISSUE THREAD

**Issue by LukasKnuth** [signalapp/Signal-Android#9210] opened 2019-11-20 18:05 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The "Send Picture"-Activity shows, but when hitting the "send"-button, nothing happens.

### Steps to reproduce

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

- Select an Image to send, either by using Androids Share function (from gallery), taking a picture with signal or using the "+"-button which becomes the send button
- The Activity for selecting one ore multiple images and Text is shown as expected.
- Hit send 
- The activity closes, showing the chat again. No picture is sent, no error is given. The App does NOT crash.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

- Select an Image to send, either by using Androids Share function (from gallery), taking a picture with signal or using the "+"-button which becomes the send button
- The Activity for selecting one ore multiple images and Text is shown as expected.
- Hit send 
- The selected images are sent and appear in the conversation.

### Device info

**Device:** Samsung S4 Mini (GT-I9195)
**Android version:** 4.4.2 (Rooted)
**Signal version:** 4.49.18

### Link to debug log

https://debuglogs.org/ad04a29eafc36857ad430d07b418efd284d9c9c6c0ca08b759e7bc18851b0897

Aside from this Log, I get the following via LogCat when reproducing the Error:

```
11-20 18:47:24.267 850-6689/? E/DatabaseUtils: Writing exception to parcel
    java.lang.SecurityException: Permission Denial: get/set setting for user asks to run as user -2 but is calling from user 0; this requires android.permission.INTERACT_ACROSS_USERS_FULL
        at com.android.server.am.ActivityManagerService.handleIncomingUser(ActivityManagerService.java:15197)
        at android.app.ActivityManager.handleIncomingUser(ActivityManager.java:2492)
        at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:688)
        at android.content.ContentProvider$Transport.call(ContentProvider.java:325)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:275)
        at android.os.Binder.execTransact(Binder.java:404)
        at dalvik.system.NativeStart.run(Native Method)
11-20 18:47:24.267 850-5233/? E/Parcel: Class not found when unmarshalling: org.thoughtcrime.securesms.mediasend.Media
    java.lang.ClassNotFoundException: org.thoughtcrime.securesms.mediasend.Media
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:251)
        at java.lang.Class.forName(Class.java:216)
        at android.os.Parcel.readParcelableCreator(Parcel.java:2133)
        at android.os.Parcel.readParcelable(Parcel.java:2097)
        at android.os.Parcel.readValue(Parcel.java:2013)
        at android.os.Parcel.readListInternal(Parcel.java:2343)
        at android.os.Parcel.readArrayList(Parcel.java:1703)
        at android.os.Parcel.readValue(Parcel.java:2034)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:2314)
        at android.os.Bundle.unparcel(Bundle.java:249)
        at android.os.Bundle.getString(Bundle.java:1118)
        at android.content.Intent.getStringExtra(Intent.java:5151)
        at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:1467)
        at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:1063)
        at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:4138)
        at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:4036)
        at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:159)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2712)
        at android.os.Binder.execTransact(Binder.java:404)
        at dalvik.system.NativeStart.run(Native Method)
     Caused by: java.lang.NoClassDefFoundError: org/thoughtcrime/securesms/mediasend/Media
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:251) 
        at java.lang.Class.forName(Class.java:216) 
        at android.os.Parcel.readParcelableCreator(Parcel.java:2133) 
        at android.os.Parcel.readParcelable(Parcel.java:2097) 
        at android.os.Parcel.readValue(Parcel.java:2013) 
        at android.os.Parcel.readListInternal(Parcel.java:2343) 
        at android.os.Parcel.readArrayList(Parcel.java:1703) 
        at android.os.Parcel.readValue(Parcel.java:2034) 
        at android.os.Parcel.readArrayMapInternal(Parcel.java:2314) 
        at android.os.Bundle.unparcel(Bundle.java:249) 
        at android.os.Bundle.getString(Bundle.java:1118) 
        at android.content.Intent.getStringExtra(Intent.java:5151) 
        at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:1467) 
        at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:1063) 
        at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:4138) 
        at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:4036) 
        at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:159) 
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2712) 
        at android.os.Binder.execTransact(Binder.java:404) 
        at dalvik.system.NativeStart.run(Native Method) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.thoughtcrime.securesms.mediasend.Media" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:67)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:251) 
        at java.lang.Class.forName(Class.java:216) 
        at android.os.Parcel.readParcelableCreator(Parcel.java:2133) 
        at android.os.Parcel.readParcelable(Parcel.java:2097) 
        at android.os.Parcel.readValue(Parcel.java:2013) 
        at android.os.Parcel.readListInternal(Parcel.java:2343) 
        at android.os.Parcel.readArrayList(Parcel.java:1703) 
        at android.os.Parcel.readValue(Parcel.java:2034) 
        at android.os.Parcel.readArrayMapInternal(Parcel.java:2314) 
        at android.os.Bundle.unparcel(Bundle.java:249) 
        at android.os.Bundle.getString(Bundle.java:1118) 
        at android.content.Intent.getStringExtra(Intent.java:5151) 
        at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:1467) 
        at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:1063) 
        at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:4138) 
        at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:4036) 
        at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:159) 
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2712) 
        at android.os.Binder.execTransact(Binder.java:404) 
        at dalvik.system.NativeStart.run(Native Method) 
```

**Comment by bme13** [comment] 2019-11-20 19:25
Hi. This seems a duplicate of https://github.com/signalapp/Signal-Android/issues/9149 and it was fixed in the beta version. Based on the latest comment in that issue it starts to roll out in the playstore so you should receive the fix soon.

**Closed** 2019-11-20 21:57 UTC

**Comment by LukasKnuth** [comment] 2019-11-23 18:41
Yes, the new Update fixes the issue. Thanks!
