### ISSUE TITLE
The other person cannot hear me

### ISSUE THREAD

**Issue by RasheedAZ** [signalapp/Signal-Android#12100] opened 2022-03-27 08:53 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I use Signal voice call to call others or they call me, they can't hear my voice whether I'm using the phone's normal mic, have turned on speaker, or am using a (wired) headset. I can hear them.

- Signal has permissions to Contacts, Microphone and Phone, unrestricted access to data and unrestricted battery usage.
- I'm on a strong Wi-Fi connection. This was working perfectly fine until last week.
- Regular calls via the cellphone network work fine so the microphone isn't damaged.

### Steps to reproduce
- Open Signal
- Initiate voice call with contact
- Alternatively, have contact initiate the call.

**Actual result:** Recipient unable to hear my voice although I can hear them.
**Expected result:** Recipient be able to hear my voice.

### Device info
**Device:** Google Pixel 5
**Android version:** 12, Security Update 5 March 2022
**Signal version:** 5.34.4

### Link to debug log
https://debuglogs.org/android/5.34.4/feb52531be4c632f5aea86f046fe4170ec761c1273e6d8b5678fd27938efe2a6

### Update
I just got the 5.34.5 update and the issue appears to be fixed for me :) Recipient's Signal was also updated when I tested.

**Comment by lavaux** [comment] 2022-03-27 09:02
I have the same issue on a Galaxy A8 2018 after a recent update. It was still working one week ago.

**Comment by Cobalt0s** [comment] 2022-03-27 15:07
I am seeing the same problem on one of the phones. I have the latest singal version on Samsung Galaxy S8 and got this problem. Same account but using tab s5e and people can hear me. Tried all the possible permissions and settings on the phone and microphone itself works but not with Signal.

Would be grateful if this can be resolved!

**Comment by aminekechaou** [comment] 2022-03-27 21:20
I'm experiencing the exact same issue since March 18th. I have a Samsung Galaxy S8+. I tried to backup, uninstall, reinstall and recover my account but the issue still persists.

**Comment by st-sbs** [comment] 2022-03-28 07:13
Same exact issue on Galaxy note 8 after an update to 5.34.4.

**Comment by Surfrat** [comment] 2022-03-28 07:16
Same problem. Phone is a Nokia 8 on Android 9. Latest update 5.34.4 broke microphone for voice and video calls. Have re installed with same problem..

**Comment by twanek** [comment] 2022-03-28 12:51
hello!
i have the same problem since 5.34.4, before it worked good. galaxy s8, latest updates.

thanks!

**Comment by RasheedAZ** [comment] 2022-03-29 01:03
> Hi there, if you're having the issue, please include a debuglog.

I just got the 5.34.5 update and the issue appears to be fixed for me :) Recipient's Signal was also updated when I tested. Thanks.

**Comment by Bust3D** [comment] 2022-03-29 08:42
Same issue with Samsung Galaxy Note 8.

**Comment by st-sbs** [comment] 2022-03-29 08:54
5.34.5 fixed it on Galaxy Note 8. Thanks

**Comment by Surfrat** [comment] 2022-03-29 09:50
Confirmed fixed in 5.34.5.

**Comment by Cobalt0s** [comment] 2022-03-29 11:26
Galaxy S8 is fixed after 5.34.5
Thank you for quick fix!

**Closed** 2022-03-29 14:10 UTC
