### ISSUE TITLE
Android / Verizon / Group messages

### ISSUE THREAD

**Issue by ChrisPGitbass** [signalapp/Signal-Android#9975] opened 2020-08-29 16:51 UTC
I am a total newb but someone said to post here....
I have sent the report to support@signal.org - no response.  

I am on Verizon Android LG v30 and family is on iOS.  this may happen with others but I don't know because I don't text a ton of people

Starting a couple weeks ago, my family group chat gets broken up.  If iOS replies to the group, I see the group.  If Android replies to the group each iOS sees the text as if I texted only them.

XI have searched open and closed issues for duplicates
X I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
X This isn't a feature request or a discussion topic

https://debuglogs.org/a2d88bd5bbfb7bab37496f3361dd4c6565b5db6cf7ef9ed1738d37286752fa97

**Comment by alan-signal** [comment] 2020-08-31 13:49
Is this an SMS/MMS group chat? Or a Signal group chat?

**Comment by ChrisPGitbass** [comment] 2020-08-31 16:52
out of the 4 of us i am the only one on signal.

________________________________

**Comment by ChrisPGitbass** [comment] 2020-09-01 17:52
I wiped my phone and reinstalled.  seems to be working again.  unfortuneately i can't find my 30 character passcode for my ONE GIG signal backup

________________________________

**Comment by alex-signal** [comment] 2020-09-14 13:19
Closing this as it sounds as though the issue resolved itself, or the issue is carrier-specific and your device got into a bad state.

**Closed by alex-signal** 2020-09-14 13:19 UTC
