### ISSUE TITLE
Some emoji not going jumbo

### ISSUE THREAD

**Issue by jeremymasters** [signalapp/Signal-Android#7213] opened 2017-11-21 01:46 UTC
I have:
- [ x] searched open and closed issues for duplicates
- [ x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Some emoji are not going jumbo when I receive them. There are more than in my screen shot, but this was a good example. I can produce a bigger list if needed.  These are from an iOS user. 

**Actual result:** some emoji just refuse to grow up. 
**Expected result:** All emoji go jumbo according to the same rules

### Screenshots
![20171120_183736](https://user-images.githubusercontent.com/4967949/33050420-1a17fc34-ce22-11e7-916e-13c8ef87cd0e.png)

### Device info
**Device:** Samsung s8
**Android version:** 7.0 stock
**Signal version:** 4.13.3

### Debug Log

https://gist.github.com/47a7f0c2545f20f6753b0f618cd4c92d

**Comment by moxie0** [comment] 2017-11-21 02:20
Is this a regression or a duplicate of #6758?

**Comment by jeremymasters** [comment] 2017-11-21 02:58
They are new emoji but if you feel it's a dupe it's cool.

**Comment by automated-signal** [comment] 2018-04-03 04:50
GitHub Issue Cleanup:
See #7598 for more information.

**Closed by automated-signal** 2018-04-03 04:50 UTC
Labels: bug, emoji
