### ISSUE TITLE
The Signal icon doesn't work as an adaptive icon.

### ISSUE THREAD

**Issue by cdysthe** [signalapp/Signal-Android#7625] opened 2018-04-03 18:59 UTC
- [x ] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The signal icon doesn't work as an adaptive icon in launchers that supports these. I know this is a cosmetic issue, but important for an app that is used as much as Signal.

### Steps to reproduce
- Install Smart Launcher 5 (or other launchers that supports adaptive icons). 
- Use the adaptive icons in Smart Launcher.
**Actual result:** The icon will appear as a mostly white icon without any resemblance to the Signal icon.
**Expected result:** The icon should appear as an adapted Signal icon clearly identifiable. The problem is confirmed by the Smart Launcher developers. All other app icons I use adapts well. Signal is the only one that doesn't work well in this regard.

### Screenshots
![img_20180331_225114](https://user-images.githubusercontent.com/1281031/38269601-fb384a30-374e-11e8-8dea-31db9db4b9c1.jpg)

### Device info

**Device:** Moto G5+
**Android version:** 7.0.0
**Signal version:** 4.18.0

**Comment by FeuRenard** [comment] 2018-04-03 20:57
Related to #7607 ?

**Comment by 2-4601** [comment] 2018-04-04 07:55
Closing as duplicate of #7607.

**Closed by 2-4601** 2018-04-04 07:55 UTC
