### ISSUE TITLE
Preceding characters are included in the phone number link

### ISSUE THREAD

**Issue by mueller-ma** [signalapp/Signal-Android#8084] opened 2018-08-07 15:38 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Preceding characters are included in the phone number link. When clicking on the link, the dialer opens with the number 123 dialed.

### Screenshots
![screenshot_20180807-173459](https://user-images.githubusercontent.com/22525368/43786245-7b4b5e02-9a68-11e8-9768-fd1229803ff5.png)

### Device info

**Device:** Oneplus X
**Android version:** 7.1.2, LineageOS 14.1
**Signal version:** 4.23.4

**Device:** Samsung S8
**Android version:** 8.0.0
**Signal version:** 4.24.8

**Comment by ru-signal** [comment] 2018-10-11 23:34
i tried to repro this on current master https://github.com/signalapp/Signal-Android/commit/50eb8f23227bad52b88432e97806c632e35ea503 and it did not show up for me when chatting 1-1 with test accounts on Android Galaxy S6 . seems like maybe time to close this issue.

![phone-working](https://user-images.githubusercontent.com/44073336/46839592-79036980-cd73-11e8-9052-68ea91d66be5.png)

**Comment by mueller-ma** [comment] 2018-10-12 14:51
I tested it with 4.26.2 and the issue still exists for me.
You can see in your screenshots, that the opening bracket is marked as phone number.

**Comment by ru-signal** [comment] 2018-10-12 18:58
Thanks for pointing that out @mueller-ma I wasn't sure about that part and it looked like it could be a bug. It is definitely anomalous looking to link the `(` and not the `)`. 
I see in the code it looks like it's near here where the fix would go: https://github.com/signalapp/Signal-Android/blob/0d48f10806aabe9bbf9c87109d6cc14373658e5c/src/org/thoughtcrime/securesms/ConversationItem.java#L575  i will wait for another dev to confirm the fix should and could go in there before proceeding. the current code while visually buggy seems safe and (the good part) simple in that area.

one fix would involve detecting phone number versus url/email which i think is very doable but slightly more complex. e.g. count '@'. if >0, consider as email. if not, count dots and colons and slashes. if any >0 consider as URL. if none of the above, count numbers, hyphens, parens and pluses (phone chars). versus "everything else". if phone chars number more consider item a phone number otherwise fall back to earlier URL assumption behavior. open to other ideas.

**Comment by mueller-ma** [comment] 2018-10-18 17:56
@greyson-signal Can you reopen this issue as it isn't fixed for me?

**Comment by mueller-ma** [comment] 2022-01-28 15:54
Still an issue

**Comment by pierceshih** [comment] 2022-02-01 08:16
This seems to be caused by how [Linkify](https://android.googlesource.com/platform/frameworks/base/+/5d123b67756dffcfdebdb936ab2de2b29c799321/core/java/android/text/util/Linkify.java#671) uses [libphonenumber](https://github.com/google/libphonenumber/blob/3285ff2a4031c681aac1307b4760a82838df36c1/cpp/src/phonenumbers/phonenumbermatcher.cc#L277) to identify possible phone numbers. Specifically, leading and trailing parentheses - which frequently denotes regional codes in parts of the world - are characters that the libphonenumber parser can handle.

The problem of "preceding characters are included" is a subset of the Linkify behavior:
 
![phone](https://user-images.githubusercontent.com/6747499/151931316-dc1a5c19-00f0-4fae-bc7e-efec3b38d3bb.png)

**Closed** 2022-04-09 09:44 UTC
Labels: wontfix
