### ISSUE TITLE
Signal reads messages automaticaly after a call

### ISSUE THREAD

**Issue by ruicruzpt** [signalapp/Signal-Android#7641] opened 2018-04-05 10:15 UTC
Let's begin with a checklist: Replace the empty checkboxes [ ] below with checked ones [x] accordingly. -->

- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If you're calling someone who does not yet read your message, after the call hangs up (no anwser) the messages appear as read. 
You need, of course, tohave the option Read reeipts under Settings > Privacy enabled on both phones.

### Steps to reproduce
Phone 1:
- Read reeipts is enabled
- You're on another window, not Signal
- or you've your phone blocked 

Phone 2
- call Phone 1
- hang up before Phone 1 anwsers (but it needs to ring first)

**Actual result:** Unread messages become read after 3 seconds
**Expected result:** Messages are indeed NOT read (by "human standarts") and cannot be marked as read

### Device info

**Device:** Samsung s6, both phones
**Android version:** 7.x
**Signal version:** last beta

**Comment by moxie0** [comment] 2018-04-05 11:32
I'm unable to reproduce this. I tried:

1. Alice sends message to Bob. It is unread.
2. Alice calls Bob.
3. Bob's phone rings.
4. Alice hangs up.
5. The message to Bob remains unread on both Alice and Bob's phone.

Please let me know if there are other steps I should try, and I'll reopen. Thanks!

**Comment by Hooloovoo** [comment] 2018-06-15 08:21
From the duplicate Issue #7896 
If I have unread messages in a conversation and that person calls me, all unread messages are marked as read (blue check marks). This actually caused us a real issue, as the person was calling me to check I had seen the message and then stopped trying once the messages were marked as read.
Steps to reproduce    

- Send messages from phone A to phone B (phone B has screen off and is untouched through process). These messages are shown as unread.
- Signal Call phone B from phone A.
- Do not touch phone B or answer the call. Stop calling from phone A.
- The messages are now shown as read (blue check marks).

Actual result: Messages are marked read.
Expected result: Messages should not be marked read until the conversation is opened on phone B.
Device info

Device: OnePlus 3T
Android version: 8.0.0
Signal version: 4.20.7

Also tested in both directions with another OnePlus 3T and a Samsung S8.
Link to debug log

https://debuglogs.org/72ae8fa7a3a4f71014ee02bbee433ce10d038c21c676f9c68f788a4970659532

**Comment by Hooloovoo** [comment] 2018-06-22 11:31
@2-4601 I have just retested this. 

The issue appears to be that the incoming Signal call is bringing Signal to the foreground in whatever state the app was last open. Where Signal was in the conversation with that person, the missed Signal call is bringing that conversation to the foreground (even behind the locked/turned-off screen) and that is "reading" the unread messages.

There are five relevant scenarios:
1. Phone B has no apps open (actually closed, not just in the background). Works correctly whether screen is on or off.
1. Phone B was in Signal but in initial conversation list instead of the specific conversation with Person A. Phone B back to the home screen, leaving Signal in the background. The missed call reopens Signal to where it last was, so not in the relevant conversation, and the messages are not marked as read.
1. Phone B was in Signal but in initial conversation list instead of the specific conversation with Person A. Phone B back to the home screen, leaving Signal in the background. Phone B screen is turned off. A missed incoming call from Phone A to Phone B. When Phone B is next turned on, the conversation list is left in the foreground on Phone B. The messages are not marked as read.
1. Phone B was in conversation with person A and Phone B switched to home screen (Signal in background in relevant conversation). The missed call reopens Signal on the conversation and messages are marked as read. After the incoming call stops on Phone B, the conversation is left in the foreground on Phone B.
1. Phone B was in conversation with person A and Phone B switched to home screen (Signal in background in relevant conversation) and turns off the phone. The missed call reopens Signal on the conversation and messages are marked as read. After the incoming call stops on Phone B, the conversation is left in the foreground on Phone B.
1. Phone B was in the conversation with person A and Phone B and Signal is running (including in the background) and has screen turned off. The missed call reopens Signal on the conversation (behind the turned off screen) and messages are marked as read. When turning the screen back on on Phone B, the conversation is in the foreground.

**Comment by 2-4601** [comment] 2018-06-22 14:44
Thanks @Hooloovoo for testing all the scenarios.

So the gist of the issue is that the call can turn the device on and open the conversation thus marking all messages read.

This behavior seems to be very reproducible.

**Comment by ruicruzpt** [comment] 2018-06-25 07:02
Thank you everyone for re-testing this. :)

**Comment by theafn** [comment] 2019-05-10 09:42
What's the status of this? This issue can cause a lot of trouble especially among those who are not aware of the bug and should be prioritized in my opinion.

**Comment by chaoscommander** [comment] 2019-11-02 15:04
This is still not fixed, I came to report it believing it was a new bug and just saw that it is a really old one... @moxie0 please consider looking into it. This problem has prompted relationship drama on more than one occasion that I know of.

**Comment by LordPicard** [comment] 2019-11-02 15:52
I tested with my backup/old phone and indeed is not fixed. 

I did not insist on this because my main phone became an iOS and i did not notice this in the new operating system. 

But talking with my second number (on Android) from my primary number (on iOS) the issue still exists.

**Comment by smichel17** [comment] 2020-07-09 12:46
Adding keywords to aid searching: messages seen call receipt reciept (:sweat_smile:) read

**Comment by theGeekyLad** [comment] 2021-08-18 14:19
Is anyone else facing this in 2021?

**Comment by chaoscommander** [comment] 2021-08-19 15:54
I have just tried to reproduce this and the marking as read did not occur. I didn't, however, try every possible scenario. I tried manually sending Signal to the background, then turning off the screen, then sending messages from another phone and calling afterwards. I also tried the above without backgrounding, just turning off the screen from the relevant conversation. In both cases the message stayed unread after the missed call.

**Comment by greyson-signal** [comment] 2021-08-20 15:26
We've changed a lot of mark-read logic in the past couple years. I can't repo either, so closing. If someone can repro, please provide detailed steps. Thanks!

**Comment by theadventurebite** [comment] 2023-02-26 07:09
I believe that this was experienced today. My partner got an awful earful about ignoring me and I had a pretty solid panic. His phone was on the charger. I will attempt to reproduce it but this was very distressing.

**Comment by cody-signal** [comment] 2023-02-27 04:00
So sorry this happened. I'll look into it and try to reproduce.

**Comment by cody-signal** [comment] 2023-03-01 19:22
Does your partner have a lock screen on their phone or no?

Only way I could reproduce this was to have left the callee phone open to the chat of the caller but have the screen turned off. Then the act of calling would wake up the device and since there was no lock screen would fall back to the conversation screen and mark the messages read. If the callee has a lock screen it wouldn't drop back to the convo screen but instead drop back to lock.

**Closed** 2023-05-08 20:45 UTC
Labels: wontfix
