### ISSUE TITLE
Can't send messages to contact after "Safety Number Changes"

### ISSUE THREAD

**Issue by alpipego** [signalapp/Signal-Android#10256] opened 2020-12-06 09:56 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After the safety number for a contact changed, i.e. they set up a new phone, I can't send them messages. The "send anyway" button does not send it, neither does verifying the new safety number.
Resetting the secure session also does not fix the problem.

### Steps to reproduce
* Get a contact to set up a new phone 
* Get them to send you a message
* Reply to that message

**Actual result:** The messages can't be sent
**Expected result:** The messages should be sent after either verifying the new safety number or via "send anyway"

### Device info

**Device:** OnePlus A6013
**Android version:** Oxygen OS 10.3.6
**Signal version:** 4.79.3

### Link to debug log
https://debuglogs.org/7078798e2e758100c45bbfb6d687413242208edc61bfa3cda97e95b59927300c

**Comment by cody-signal** [comment] 2020-12-09 15:13
@alpipego thanks for the report. I'm trying to reproduce and I'm unable to. Could you elaborate more. Could you clarify:

1. Does the Safety Number change dialog show each time your try to send?
1. Does the "Send Anyway" button cause the dialog to disappear and then immediately reappear? Or not go away at all? Or go away and not reappear until trying to send again?
1. Is there anything else you think would be helpful in reproducing this?

**Comment by alpipego** [comment] 2020-12-09 16:11
Thanks for getting back to me @cody-signal:

1. There's a red exclamation mark and it says "not sent, tap for details", if I tap I get the Safety Number dialog.
1. Yes, the pop up goes away and the exclamation mark immediately reappears (there's a very short "trying to send"-spinner visible, < 1s)
1. It has only happened with one contact so far, and I know they've gotten a new phone. So I can't think of anything else, sorry.

**Comment by ahaverty** [comment] 2021-01-30 12:23
I am also seeing the same issue with just one contact for both groups and direct messages. They can send me a message, but no mater what I do, I can't send them a message (Android).
I've verified multiple times, and tried 'Reset secure session', but continue to get the red exclamation mark.

**Comment by ahaverty** [comment] 2021-01-30 12:26
I've been able to verify on my mac signal app, and send messages from there to this contact, but still get errors on my android signal.

**Comment by ahaverty** [comment] 2021-01-30 14:29
Here's what I'm seeing from android, with a bit of annotation to explain what's going on:
![Screenshot_20210130-142306__01.jpg](https://user-images.githubusercontent.com/2920947/106359004-6ed05500-6307-11eb-8fdb-dd7b525e326a.jpg)

**Comment by ahaverty** [comment] 2021-01-30 14:40
I can see logs for mismatched keys around 12:25 today for this conversation: https://debuglogs.org/f67fb073ccab88b61d8bdd46a5fd38f614f87b28ca08b49748be4cf5db3de803

**Comment by Leptopoda** [comment] 2021-03-18 16:51
Hi just can from #10950 
I had both a linked device and an iPad wich where unaffected by this. 
Could it be related to libsignal-client (as it is 0.2 on android and 0.3 on the other platforms) ?

**Comment by vs49688** [comment] 2021-04-05 11:23
Just hit this when registering a new phone. Different safety number on each device, almost like it missed the "safety number changed" message. Same behaviour, desktop clients work fine.

**Comment by cody-signal** [comment] 2021-04-14 21:24
Hey Folks, sorry y'all are running into this. Are you being presented with a safety number change dialog at all? Or does it just fail and tapping the error icon doesn't show anything?

**Comment by Leptopoda** [comment] 2021-04-14 21:38
Scrolling back i had the error icon and tapping on it showed the safety Humber changed dialogue

I texted the person now and it doesn't happen anymore🤷‍♀️ (waiting for a response)

Keep in mind I did a few backup and restore in the mean time (testing the device transfer)

![signal-2021-04-14-233506](https://user-images.githubusercontent.com/25266387/114783689-6326f300-9d7a-11eb-8d99-c663252a12d0.jpg)
![signal-2021-04-14-233448](https://user-images.githubusercontent.com/25266387/114783703-67eba700-9d7a-11eb-8c08-88eb6f8b1564.jpg)

**Comment by Leptopoda** [comment] 2021-04-15 06:10
Ok small update 
Seems to be fixed for ne already 🙃
Sorry for the confusion

**Comment by ahaverty** [comment] 2021-04-15 07:25
Just to chime in here, similarly to @Leptopoda, this eventually worked itself out for me too. I'm not sure how many days it took, but I've since not had an issue with that particular contact or seen this happen with any other of my contacts.

**Comment by cody-signal** [comment] 2021-04-15 13:46
Well, I'm glad it resolved itself. If it happens again, let us know.

**Comment by alpipego** [comment] 2021-04-16 08:44
I have initially opened this ticket and the issue is not resolved for me. It's still the same contact, same phone etc. I can only send them messages on iOS for the moment. Everything from my first comment is still the case.

> Hey Folks, sorry y'all are running into this. Are you being presented with a safety number change dialog at all? Or does it just fail and tapping the error icon doesn't show anything?

The dialog is there, "Send anyway" does not work. I have exchanged security numbers and reset my signal app multiple times. 

I am now on Signal 5.8.5. 

Unfortunately, I can't do it myself, but please reopen this issue. @greyson-signal.

**Comment by cody-signal** [comment] 2021-04-16 12:47
@alpipego can you provide a new debuglog?

**Comment by alpipego** [comment] 2021-04-16 19:28
Sure thing: https://debuglogs.org/0a73bf800428c9c3540d46a832ccd9bc5ca0a3881ca53d1d80aa91de035f55f4

**Comment by hiqua** [comment] 2021-05-19 13:48
@cody-signal new debug log:
https://debuglogs.org/5c1ff29d5722721a725371fa9f2d547f783e50adfb2f4ea5492aa3f1fe71f908

There are some `UntrustedIdentityException: Untrusted on send`.

My problem is in the "Breaking Signal for Science" group, with one specific group member. This person was never in my contacts.

Sending a message to the group always results in `partial sent, tap for details`. `Send anyway` fails, so I don't think the person is receiving my messages.
I've tried:
* to mark the number as verified
* to add the number to my local contacts
but this doesn't change anything.

I've also tried to send messages directly to this account, but it fails with "Not sent, tap for details" (basically same error as in the group).

Other people in the group told me they had no such warnings. So at least there's some consistency problem: I was thinking that maybe the account does not exist anymore and my Signal is not aware of that yet, but then other clients should also have the same "view" of the group.

Note that I'm on beta, but it was already happening with the previous version.

**Comment by brs17** [comment] 2021-05-20 02:21
I ran into this issue this morning.

I went to message a contact with whom I had disappearing messages enabled. Since the last time either of us had messaged the other, all previous messaged had disappeared and the contact had gotten a new phone (so the safety number changed).

Upon sending the first message, I got the red error that the message: "Not sent, tap for details". 

Upon taping for details, the "safety Number Changes" pop-up appeared. I went ahead and clicked "View" and toggled the "Verified" toggle.

![safetynumberchanges](https://user-images.githubusercontent.com/7460774/118907456-c6a5c280-b8dc-11eb-9e6f-2b9f2f4c896a.jpeg)

I then attempted to resend the message with no success. 

I went ahead and tried to send the same message a couple more times (thinking that maybe a new message would work). This also did not work. Not wanting the recipient to eventually receive 3 of the same message I went ahead and tried to delete the message and discovered I could delete it for both me and the recipient (even though it had never successfully sent).

![1](https://user-images.githubusercontent.com/7460774/118907531-e937db80-b8dc-11eb-83ed-6bd318efeea5.jpeg)

A bit later I went ahead and tried resetting the secure connection wondering if that would fix the issue. I then believe I attempted to send the first message again, but definitely copied and tried to send a new message again with no success.

Since this failed, I went ahead and just about immediately sent an insecure SMS to the recipient which successfully sent. A few hours later, I received a response from the contact. The contact confirmed they were not experiencing any issues with Signal. I requested the contact send me a Signal message, and the contact had no issues doing so. We were able to then have a conversation with encrypted messages.

![2](https://user-images.githubusercontent.com/7460774/118907632-1be1d400-b8dd-11eb-8b53-0fd2d6ae6e11.jpeg)

Below are the debug logs from today through the times shown in the screenshots.

### Debug logs
[signal_debug_log_2021-05-19.log](https://github.com/signalapp/Signal-Android/files/6512396/signal_debug_log_2021-05-19.log)

### Device info

Device: Nexus 5X
Android version: Android 8.1.0
Signal version: 5.11.4


Please let me know if there is more information that would be valuable to provide.

**Comment by Lukas-J** [comment] 2021-06-20 15:05
Interesting thing: I've got exactly the same issue on my Android Phone (Huawei P10, Andriod-Version 9.1.0, Signal Version 5.13.8), but everything works fine on my Signal Desktop (Operating System: Windows 10 Pro 20H2 19042.1052, Signal Version: 5.5.0). There I can still send messages to the affected contact.

**Comment by cody-signal** [comment] 2021-06-21 13:16
Can you try with 5.14.4+ (still coming to production) or 5.15 (beta) build and let us know after that?

**Comment by Lukas-J** [comment] 2021-06-22 07:55
I'm on 5.15 now and it seems to be fixed. Thanks.

**Comment by alpipego** [comment] 2021-06-23 07:42
5.15.0 also solves this for me.

**Comment by adambriny** [comment] 2021-07-08 14:05
https://github.com/signalapp/Signal-Android/issues/10256#issuecomment-844632346

I've just run into the exact same issue described by @brs17 today.

Signal version: 5.15.6
Mobile: Samsung A50
Android version: 11

**Comment by cody-signal** [comment] 2021-07-08 14:13
@adambriny can you provide a debuglog please?

**Comment by adambriny** [comment] 2021-07-08 20:07
@cody-signal sure thing!

https://debuglogs.org/7dd45043a00c35f13b2d3f5d66e10418c19af1615f96b3989591f052282316a5

**Comment by benedetto** [comment] 2021-07-18 15:12
Same over here.
Signal 5.16.3
Fairphone 3
Android 10

https://debuglogs.org/6e2ca2070d7a1cd90d95b8a61ce6da53899e0b3694a67f9053db1659328ebcd8

**Comment by notobasa** [comment] 2021-08-01 12:45
Same issue here since 25th of may this year with exactly 1 conversation.
Signal 5.18.5
Samsung Galaxy S9
Android 10

[https://debuglogs.org/9762d032436049f9252f0f54c142a4dbfdd7bb6c1d815879b57987507177b681](url)

**Comment by cody-signal** [comment] 2021-08-02 13:35
@notobasa could you encounter the issue, attempt to resolve via the dialog with "Send anyway" and submit the logs afterwards? The logs you provided don't seem to include that operation which is what should fix this.

**Comment by notobasa** [comment] 2021-08-09 20:29
> @notobasa could you encounter the issue, attempt to resolve via the dialog with "Send anyway" and submit the logs afterwards? The logs you provided don't seem to include that operation which is what should fix this.

Hey, I just saw your message now, sorry^^ Thanks for your reply. The update/new version (5.19.4) fixed the issue for me, which is great. Thank you very much!

**Comment by cody-signal** [comment] 2021-08-09 21:36
Thanks. I'm going to close this now, but we can reopen if someone encounters it again.

**Closed by cody-signal** 2021-08-09 21:36 UTC

**Comment by nicholas-signal** [comment] 2023-04-25 15:03
> I just ecountered it once again. 2y ago my friend changed phone, his security number changed and since that time I'm unable to contact him via signal. After 2y the problem persist.
> 
> Today my wife changed phone, transfered all the data to a new android using usb cable, but she missed all the history. I got info that her security number changed and I cannot contact her anymore. When I try, my android says "signal keeps crashing". I scanned her QR code with my phone and it says it's ok, I cannot show my qr to her, because it says: "exchange some messages with the contact first".
> 
> I removed cache, nothing helps.

Are you able to submit a debuglog? Instructions: https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports#capture-a-debug-log
