### ISSUE TITLE
Not creating backup

### ISSUE THREAD

**Issue by Hellmark** [signalapp/Signal-Android#7770] opened 2018-05-07 19:05 UTC
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Backup function fails silently. No files created on SD card, just shows "Last Backup: Never" in app.

### Steps to reproduce
-Enable external backups on Android app
-attempt to create backup

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
Goes through what appears to be the backup process, parsing through all messages, but nothing is created on the SD card.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
A backup file created on the SD card.

### Device info
**Device:** LG V20
**Android version:** 7.0.0
**Signal version:** 4.19.3

### Link to debug log
https://debuglogs.org/a37020132215e3e35c5f7661a76b89cfbb2e442c2a3ea2aaa800ed5ea1f4cc36

**Comment by Cerberus0** [comment] 2018-05-07 19:42
Sounds like a dupe of https://github.com/signalapp/Signal-Android/issues/7692

@moxie0 has said that the issue should be fixed in 4.20

**Closed** 2018-05-07 20:02 UTC

**Comment by Hellmark** [comment] 2018-05-07 21:37
I wasn't sure if it was a dupe, because no error on my end, unlike the one for #7692 

Still, hopefully 4.20 is out soon.
