### ISSUE TITLE
MMS will not download

### ISSUE THREAD

**Issue by cmherna7** [signalapp/Signal-Android#2690] opened 2015-03-14 23:47 UTC
When I try to download a picture someone sends me it just fails and returns to the original download button

**Comment by agrajaghh** [comment] 2015-03-15 08:15
Please post a debug log

**Comment by billie80** [comment] 2015-03-15 09:48
Same problem here:
https://gist.github.com/billie80/d0ad24b6d725c18d3149

**Comment by agrajaghh** [comment] 2015-03-15 12:17
relevant part from @billie80:
````
W/ConversationItem( 2009): Content location: http://mmsaut.at/8-qf3881.7217.x657.75@2/43xxx
W/MmsDownloadJob( 2009): MmsDownloadJob:onRun()
W/MmsDownloadJob( 2009): About to parse URL...
W/MmsDownloadJob( 2009): Downloading mms at mmsaut.at
W/MmsDownloadJob( 2009): Changing radio to MMS mode..
W/MmsRadio( 2009): startUsingNetworkFeature status: 2
W/MmsRadio( 2009): Got connectivity change...
W/MmsRadio( 2009): Connected: NetworkInfo: type: mobile_mms[UMTS], state: UNKNOWN/IDLE, reason: (unspecified), extra: (none), roaming: true, failover: false, isAvailable: false
W/MmsRadio( 2009): Connected: NetworkInfo: type: mobile_mms[UMTS], state: UNKNOWN/IDLE, reason: (unspecified), extra: (none), roaming: true, failover: false, isAvailable: false
W/MmsRadio( 2009): Notifying not connected...
W/MmsRadio( 2009): Connected: NetworkInfo: type: mobile_mms[UMTS], state: UNKNOWN/IDLE, reason: (unspecified), extra: (none), roaming: true, failover: false, isAvailable: false
W/MmsRadio( 2009): Got back from connectivity wait, and not connected...
W/MmsRadio( 2009): MMS Radio Disconnect Called...
W/MmsRadio( 2009): Reference count: 0
W/MmsRadio( 2009): Turning off MMS radio...
W/MmsRadio( 2009): Unregistering receiver...
W/MmsDownloadJob( 2009): org.thoughtcrime.securesms.mms.MmsRadioException: Unable to successfully enable MMS radio.
W/MmsDownloadJob( 2009): at org.thoughtcrime.securesms.mms.MmsRadio.connect(MmsRadio.java:94)
W/MmsDownloadJob( 2009): at org.thoughtcrime.securesms.jobs.MmsDownloadJob.onRun(MmsDownloadJob.java:111)
W/MmsDownloadJob( 2009): at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
W/MmsDownloadJob( 2009): at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:72)
W/MmsDownloadJob( 2009): at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46) 
````

**Comment by justin-** [comment] 2015-03-18 06:34
Duplicate of #1937? tele.ring uses T-Mobile's network

**Comment by zaazi** [comment] 2015-04-08 11:26
Same issue here, bug report here https://gist.github.com/anonymous/0d975e5012e81207ae79

**Comment by mcginty** [comment] 2015-04-08 23:22
@zaazi that log doesn't have any MMS-related debug info in it, unfortunately

**Comment by zaazi** [comment] 2015-04-09 04:36
Sorry about that, this one seems to contain the information you want. 

https://gist.github.com/5130fa3f804f4849abae

On April 9, 2015 1:23:01 AM GMT+02:00, Jake McGinty <notifications@github.com> wrote:
>@zaazi that log doesn't have any MMS-related debug info in it,
>unfortunately
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/WhisperSystems/TextSecure/issues/2690#issuecomment-91065580

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by automated-signal** [comment] 2018-04-02 21:33
GitHub Issue Cleanup:
See #7598 for more information.

**Closed by automated-signal** 2018-04-02 21:33 UTC
Labels: bug, mms
