### ISSUE TITLE
Signal not optimised for Samsung's Ultra power saving mode

### ISSUE THREAD

**Issue by RobertTEG** [signalapp/Signal-Android#7529] opened 2018-03-16 13:24 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I think this could be considered as an update, not like a bug or so. I saw that Signal cannot be used while a Samsung phone is in Ultra power saving mode.
### Steps to reproduce
- Set the phone on Ultra power saving mode

**Actual result:** Signal isn't listed in "available apps" list to use in saving mode.

### Device info
**Device:** Samsung Galaxy S7
**Android version:** 7.0
**Signal version:** 4.16.9

### Link to debug log
It isn't necessary at all...

I know there was a closed issue 2 years ago and nothing was done since then.

###Screenshots
![screenshot_20180316-152933](https://user-images.githubusercontent.com/36175353/37523342-4c003fdc-292f-11e8-91c6-cfeb88b632ad.png)
![screenshot_20180316-152945](https://user-images.githubusercontent.com/36175353/37523348-54190aaa-292f-11e8-86ef-93b1070ee19d.png)

**Comment by FeuRenard** [comment] 2018-03-16 17:36
This is a duplicate of #4945.

Quote from https://github.com/signalapp/Signal-Android/issues/4945#issuecomment-272627451 :
> Does Samsung provide some API to circumvent the restrictions in the ultra power-saving mode? If it does, could you redirect to the documentation?

As long as we don't have a positive answer to the questions above, how should Signal attempt to get on this list? Is this power saving mode in principal open for all apps?

**Closed** 2018-03-18 13:06 UTC
