### ISSUE TITLE
TS Contacts show phone number instead of name

### ISSUE THREAD

**Issue by sweah** [signalapp/Signal-Android#3810] opened 2015-07-27 08:35 UTC
After installing TS 2.23.2 on a Galaxy S3 Mini, all TS Contacts are listed with their phone number instead of the contact name. All other contacts are listed correct.

**Comment by 2-4601** [comment] 2015-07-27 11:14
I can confirm this on a friend's phone (exact same device). I didn't make an issue before because it isn't my device and I could not debug at will but here's a log: https://gist.github.com/anonymous/a15638f5c6f318aaaee4

If you search with a name TS will find the right contact though.
But otherwise all contacts show as phone numbers all the time everywhere. And if you try to edit the contacts by tapping the avatar they cannot be edited.

**Comment by agrajaghh** [comment] 2015-07-27 11:23
maybe similar to #3715 which is fixed by https://github.com/WhisperSystems/TextSecure/commit/156a86013f4ca8c5102110ccc71daa4d3887fa4c in 2.23.3

**Comment by sweah** [comment] 2015-07-27 11:34
TS 2.23.3 is installed, but I only see the Phone numbers...

**Comment by oaim** [comment] 2015-07-27 14:47
I mentioned it here too https://github.com/WhisperSystems/TextSecure/issues/3711 (I have a samsung galaxy s3 mini as well)
As 2-4601 says, I can't edit the textsecure-synced contacts:
https://cloud.githubusercontent.com/assets/12774519/8806855/05aa2b76-2fd9-11e5-9f20-59b5af83673b.png

**Comment by moxie0** [comment] 2015-07-27 15:21
@sweah What version of android? Also please always include a debug log.

**Comment by sweah** [comment] 2015-07-27 15:30
Android 4.1.2 and the debug log after restarting TS and opening contact list: https://gist.github.com/anonymous/e5cb3ba461e8af0130c0

**Comment by oaim** [comment] 2015-07-27 15:30
@moxie0 Since we have the same phone and same problem on the same version, I think he's running Android 4.1.2 like me.

**Comment by moxie0** [comment] 2015-07-27 17:15
Does the default SMS app render those numbers correctly? Sounds like your contacts provider is failing to aggregate them.

**Comment by sweah** [comment] 2015-07-27 17:33
The default SMS app renders those numbers correctly. The correct names are shown there.

**Comment by 2-4601** [comment] 2015-07-27 17:40
I can also confirm that the default Samsung SMS app shows names.
WhatsApp displays names too.

**Comment by sweah** [comment] 2015-07-28 12:47
I found a workaround for my problem. I had all my contacts on the SIM-Card. After importing them to the phone, the names of the TS contacts were shown correct. All other contacts existed twice (although the SIM-contacts were excluded in the contacts-app of the phone). After deleting the contacts from the SIM-card, everything works as expected. But in my opinion it should not be necessary to delete all SIM-contacts. What do you think?

**Comment by oaim** [comment] 2015-07-28 12:57
The problem is that ts still isn't syncing the name of the contacts... they are displayed correctly because the app fetches the names from the phone, but ts isn't syncing the names

**Comment by 2-4601** [comment] 2015-07-30 15:32
@sweah Did you say that this issue came with 2.23.2 and you saw names before? If so then this a regression. (I can't tell since 2.23.2 was my friend's first TextSecure install.)

**Comment by sweah** [comment] 2015-07-31 05:27
@2-4601: I don't really know if it came with TS 2.23.2... It was the first TS installation on the Android 4.1.2  phone.

**Comment by 2-4601** [comment] 2015-07-31 12:46
RedPhone (1.0.3) displays names on said device.

**Comment by Wikinaut** [comment] 2015-08-08 00:44
@oaim https://github.com/WhisperSystems/TextSecure/issues/3810#issuecomment-125595109 I think your are right.

I noticed the problem while installing TS on a Tablet-PC; imported all contacts via a VCF file from my smart phone - not using the Google sync-of-contacts (I do not use Google for contacts).

The vcf file has some ten or twenty number entries at the *beginning* of the list where names are missing, but these are marked as sync-ed with TextSecure, the numbers appear later in the list on contacts where names are attached, but these second entries (number+name) do not have an information that they are synced with TextSecure (which is in my view the underlying problem of the present issue).


#### Alleged problem

So what I think is that TextSecure has a problem when a number is listed at the begin of contacts list without a name, but when later the same number appears in the list with the contact name. It strictly uses the first occurence, but this may not be the best choice.

#### Proposed solution

Unify the list of contacts before using in TextSecure. i.e. combine all available "doublure" entries into one record based on the phone number. In other words: TS has to ignore all entries where a TextSecureNumber is given but names are missing, instead it should use the corresponding entry where both a number is given and also the contact name.

Or simply process the table from the end.

**Comment by WalterFaber** [comment] 2015-08-20 21:02
Hi All,

this is not a TS issue. However here comes the solution.

The affected contacts are stored on your SIM card.
In this case, the phone can't merge the "TS contact" and the "SIM card contact" (1*).

To fix this, just ...
1. copy your "SIM card contact" to the "phone storage". 

2. The merge process starts automatically in the background.

3. After that I strongly recommend to restart your phone and to refresh your contact list in textsecure, otherwise some contacts might not be merged completely.

4. Finally, I recommend to delete the contacts on your SIM card -> now you manage all contacts in the phone storage, you don't need them any more and you won't see any difference.

Please read the manual of your phone if you don't know how to perform the single steps. Each phone is different.

I hope that helps :)

Best Regards
Matthias


(1*) in one of the recent TS versions, the app started to create its own "Contact Account" where TS stores its contacts. Other apps do this as well. Dublicate contacts in different accounts can be merged to one account. That's a common procedure in Android.
The advantage is: if you open a merged contact in your address book, you can directly use features provided by the "source apps". In this case, TS adds an option within the contact details, to send a TS message to the contact.

**Comment by Wikinaut** [comment] 2015-08-20 21:42
@WalterFaber your explanation looks to be fine, but: my tablet (onto which I copied manually the list of my contacts) does not have SIM card, so I have a single linear list of i) numbers only and ii) numbers with names. So I really think that TS should provide a mechanism to "unify" double entries (if exist) into one.

**Comment by sweah** [comment] 2015-08-21 05:39
@WalterFaber that's exactly what I did, but I have still some problems. Some TS contacts aren't listed as TS contacts. They only appear in the complete list. It's possible to send encrypted messages, but they are not listed the right way. By the way, I like to have my contacts on my SIM and I never had problems with it before.

**Comment by sweah** [comment] 2015-09-07 11:13
I still have the problem, that some of my TS contacts are listed as normal contacts. The Issue has been  removed from the 2.26.0 milestone, but not added to the 2.27.0 milestone. Is there any news, or do I simply have to live with the incorrect contact list? 
I use TS 2.26.1 on my galaxy s3 mini.

**Comment by 2-4601** [comment] 2015-09-12 15:31
I can confirm on Galaxy S3 Mini that if you save the contact info to the phone then the name is displayed correctly in TS.
However if you save it to SIM then only the number is displayed.
So the solution is to not save your contacts to the SIM card.

**Comment by oaim** [comment] 2015-09-12 15:33
When you're forcing something on your users, you're not giving them a solution, but a workaround.

**Comment by jnachtigall** [comment] 2015-12-19 20:08
I can confirm this bug, very annoying for newcomers: Contacts stored on the *SIM card* show as numbers not names. Moving the contacts to another storage with the [Copy contacts App](https://play.google.com/store/apps/details?id=com.alefsoft.copycontacts&hl=de) fixes the problem.

I just had this bug on two different phones (Vanilla 2.3.3 Android on Samsung Galaxy Ace and Android 4.4 Cyanmodgen on Samsung S II). So Signal seems to have a problem retrieving the name of SIM card stored contacts.

**Comment by agrajaghh** [comment] 2015-12-20 17:57
I can't reproduce it on my Nexus4. Contacts on the SIM card are normally displayed in Signal

**Comment by jnachtigall** [comment] 2015-12-20 18:35
Maybe it is a country/provider issue. According to http://stackoverflow.com/a/6797278/1129950 it is not possible to always retrieve the phone number from SIM (related to #4929). I am in Germany, might be interesting where @2-4601, @sweah  and @WalterFaber are from.

**Comment by agrajaghh** [comment] 2015-12-20 20:41
oh, not true, I can confirm the bug! The name is still shown in the existing conversation but I cant select this SIM contact in the newConversationActivity

**Comment by jnachtigall** [comment] 2015-12-21 08:56
@agrajaghh Maybe you could take care of this then? The bug is still assigned to moxie0. 

If you need any debug / log information or a tester, then let me know :heart:

**Comment by h1618** [comment] 2016-02-05 12:39
I see this happen on two Samsung Galaxy S3 mini with Signal 3.9.1 and 3.10.0 and Android 4.2.2 (up to date) stock firmware. Copying contacts from SIM to phone did NOT help. If I reset the contacts' and contact.provider's cache and data, the threads show the real name. But as soon as I refresh the Signal's contact list, they are again replaced with numbers. Though SMS/MMS uses the stock android app, also past SMS threads (only those of signal contacts) have names replaced with numbers. Seems, the contacts provider is severely broken with this phone model (and no hope Samsung would provide any update).

**Comment by sh0nuff** [comment] 2016-03-01 04:13
This is also happening to me and I have zero contacts on my SIM. 

However, I was having an issue with my Contacts Google App,  not being able to choose which address book to save to,  so I removed all my Google accounts from the phone to try and troubleshoot.  After adding them back in,  none of the contacts that use Signal show up as their contact name. 

I've also tried deleting their # from their contact card,  hoping to save them into my address book from within Signal,  as well as deleting the message history with that contact. Nothing helps..

*However* if I search their name from within Signal their number shows up as if it were connected to their name in some fashion.

**Comment by tom-albrecht** [comment] 2016-03-07 14:11
I found the solution to at least @sh0nuff 's problem, which I also had.

Apparently, in the time that my Google account was removed from the phone, some app or the Android system created new contacts with name "#" and just the phone number as info for some of the numbers I recently used. 
So when I reactivated the account, those contacts were used in Signal and not my previous ones with names. Deleting all "#" contacts at the end of the contact list solved the problem.

**Comment by mbaughn** [comment] 2016-06-05 06:00
I ran into this issue on Signal 3.16.0 on a stock Nexus 5 running 6.0.1 Build MOB30H. In my case it was Google's fault, not Signal.

I changed my Google account password from my computer, which booted my phone off of my account temporarily until I could figure out a 2FA bug on the phone login page (Hint: you can't switch apps to the Google Auth app to read a code anymore during the Google sign-in, you need to write the code down before you attempt to sign in with the new password and enter it when prompted without switching apps).

My Google Contacts were all dumped from my phone in the interregnum between passwords, and Signal created its own nameless contact entry for all of my Signal-using contacts (I.E. all the cool people), probably to prevent things from breaking.

To fix this, once your Google contacts are re-synched open Signal and tap on the circle where a contact photo would normally be (or the first number or letter of a name, absent a photo). When the contact card pops up from the bottom of the screen, hit the "edit" pencil icon. The contact card will then move to occupy the whole screen. Click on the "..." at the top, and select "Link". It will suggest the Google Contact with the corresponding Signal number. Click the contact to link the two, and you're set.

**Comment by tom-albrecht** [comment] 2016-06-06 06:53
But then you need to do this manually for every contact.

 

If you go to the contacts app, you can delete all those new “Signal contacts” at once. 

Signal will automatically find the correct “google contacts” again.

**Comment by lgro** [comment] 2016-07-26 23:51
mbaughn's how-to that @tom-albrecht reported works but in Andrid 6.0.1 deleting Signal contacts is not possible since it is a read-only account (reproduce: contacts app -> mark all faulty contacts -> delete)
Re-installing Signal is of course a workaround, though not a favorable one.

Maybe it is possible to integrate a feature into Signal that allows the user to regenerate all Signal contacts from scratch / to discard the existing ones for this Account.

**Comment by Wikinaut** [comment] 2016-07-27 00:24
Same problem here after recent upgrade to Android 6 (Huawei P8 Lite).

**Comment by zoff99** [comment] 2016-07-27 08:02
+1 : regenerate all Signal contacts
this sounds like a needed feature. maybe run it automatically on sync?

**Comment by lgro** [comment] 2016-09-22 20:05
**Android 7 workaround**
1. Open the contacts app
2. Display only Signal contacts
3. Bulk remove all contacts (Android says they are only "hidden", though)
4. Sync contacts in Signal mobile and Desktop to discover correct contact names instead of phone numbers

**Comment by mimf** [comment] 2016-10-14 18:57
I also have this issue and several people to whom I recommended signal also had this issue (they stopped using it since then, because of this).

I'm using 5.0.2

**Comment by codemac** [comment] 2016-10-22 20:18
Happened for me and my friend who just both got new phones. Really embarrassing, and a tedious fix if you have lots of signal contacts.

**Comment by codemac** [comment] 2016-10-22 21:21
I deleted my signal contacts in my contacts app, and that did nothing. So then I followed the [instructions from the support page](http://support.whispersystems.org/hc/en-us/articles/216595418-How-can-I-see-the-names-of-my-contacts-in-my-contact-list-I-am-only-seeing-numbers-) (which I could not find via searching google for quite a while)

So the steps to fix this should be:
- Delete all your signal contacts by going into the contacts app, going to settings, and defining a custom view that only shows your signal contacts. Then mark them all as deleted (it'll tell you they're actually just hidden)

Then follow the Resync your contacts workflow:

Resync your contacts

- Go to Android Settings
- Choose Accounts
- Choose Signal
- Tap on the Menu
- Choose Remove Account (the alert of clearing data is incorrect, your messages will not be deleted)
- Open Signal
- Tap on the pencil icon in the blue circle
- Choose the Menu
- Tap Refresh

Masha Kolenkina - July 27, 2016 15:08

    Facebook

**Comment by Wikinaut** [comment] 2016-10-22 23:03
Warning:

On my Android, your step 1 - where you wrote "just hidden" - would **delete** the marked contact. I tried that carefully - the contact was deleted in all accounts.

**Comment by codemac** [comment] 2016-10-23 00:04
@Wikinaut You have to create the custom view that only shows contacts from Signal. Remember to unfold each and every named app in the custom view panel and deselect the others.

I'm really sorry if anything I said caused you any trouble, just trying to help others. Any more clarity on what you did that caused the contact to actually be deleted would be helpful to add.

**Comment by donjan** [comment] 2016-10-29 09:45
@Wikinaut @codemac 
No need to delete anything. Just go to the Contacts app, hit the three-dot-button -> Filter and make sure that the "All Contacts" option under Signal is ticked on. This marks the sources you wish to consider for linking. I'd recommend activating all the entries while you're at it.
After this, again the three dots in the Contacts app and "Find link candidates", which will now offer a list with every contact that can be linked between Signal and the phone contacts.

**Comment by ekkis** [comment] 2017-01-19 21:32
I have this problem on the Desktop version (OS X).  any thoughts as to how to fix? I can't even tell the version I have installed as the app doesn't have an About box

**Comment by automated-signal** [comment] 2018-04-02 21:47
GitHub Issue Cleanup:
See #7598 for more information.

**Closed by automated-signal** 2018-04-02 21:47 UTC
