### ISSUE TITLE
signal silently closing during restore

### ISSUE THREAD

**Issue by contractor1970** [signalapp/Signal-Android#8256] opened 2018-10-06 10:41 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Restore of a backup silently closes before completion. Both phones are same model, android version, signal version - it's an RMA swap. According to the backup I think there are about 35K messages.  File size is 1.6GB

### Steps to reproduce
1. create backup from within Signal App
2. transfer backup fiel to new device via usb (iinto Signal/Backup dir)
3.confirm intefgrity of file via hash comparison
4.restore using standard process - click "Restore Backup"
5.Enter passphrase (as recorded earlier during step 1
6.Restore starts quickly through to about 19000 messages and then slows.
7.Silently exits at around 20300 messages

**Actual result:** 

Silently exits at around 20301 messages

**Expected result:** 

Successful restore message

### Device info

**Device:** Google Pixel XL
**Android version:** 9 + Oct 5 patch
**Signal version:** 4.26.2

### Link to debug log

https://debuglogs.org/fc8eaf42547312fecc0a4337449cd6cb9463c746855b7a5d43d2e81746d9bef1

**Comment by greyson-signal** [comment] 2018-10-07 16:02
Glad it got resolved! Looking at the log, it seems to be a dupe of #7975. This should give us some more data points on that -- thanks!

**Closed by greyson-signal** 2018-10-07 16:02 UTC
