### ISSUE TITLE
Signal doesn't store incoming SMS messages to Android's message store

### ISSUE THREAD

**Issue by izacus** [signalapp/Signal-Android#5729] opened 2016-09-29 08:28 UTC
When Signal is the default messaging handler for SMS apps, it doesn't add received SMS (not Signal!) messages into the global SMS store. This means that if the user wants to switch back to the default / other SMS app, all the messages received while Signal was the default handler will be missing.
This also breaks SMS backup software like SMS Backup and Restore and SMS Backup (because they don't see the messages) or software like AirDroid that allows reading and sending SMS messages on the computer. 

To resolve this, Signal should correcly insert received SMS messages into global Android SMS store.

The issue was seen on Sony Xperia Z5 compact running Android 6.0.1 and Signal 3.19.1.

**Comment by nrizzio** [comment] 2016-09-29 09:41
This would break the encrypted storage that Signal provides.

**Comment by izacus** [comment] 2016-09-29 12:41
Instead it now breaks SMS functionality on the (already encrypted) phone and prevents users from backing up their SMS messages. Encrypted storage for Signal messages is fine. Breaking SMS functionality just to add another encrypted layer over FDE is not.

**Comment by 2-4601** [comment] 2016-09-29 13:02
Signal supports devices all the way to Gingerbread. Older devices don't have good enough FDE.

**Comment by johanw666** [comment] 2016-09-29 13:55
Besides, the plain sms massages can be backud up in Signal in SMS backup and Restore format and then inserted in the system sms database by SMS backup and Restore if one would want that.

**Comment by izacus** [comment] 2016-11-17 10:39
This still does not address:

* Using triggers to automatically backup the SMS messages and data store.
* Breaking tools like AirDroid, PushBullet and other SMS senders and receivers.
* Automatically backing up SMS to a secure storage (which Signal still does not support).

**Comment by sparr** [comment] 2016-12-02 00:26
This should definitely be an option exposed to the user. I use SMS Backup And Restore to backup my SMSes on a schedule. That functionality is lost to me while using Signal to receive SMSes.

**Comment by icantremember** [comment] 2016-12-07 18:22
I have to agree here. I wanted to use Signal for all my messaging but I can't/won't because it hijacks the phone's regular SMS functionality. Prior to my finally figuring it out, I assumed that Signal would allow for regular SMS/MMS (read: system database) and also encrypted private messaging. I did not initially understand (nor is it clear) that the goal is an encrypted store of SMS/MMS which can no longer be accessed by the system or other apps. I wanted to use the encrypted messaging for some contacts and regular SMS for others. I understand that I can do that with separate apps but the (assumed) promise of Signal was that it would do it all-in-one.

That said, I'm sure this feature/issue has long been pondered by @moxie0 and I don't think we're going to change his mind any time soon.

**Comment by ibigfire** [comment] 2017-12-03 03:53
Doubling down on this as a potential option that would be nice.  Personally I like Signal as just a really solid good messaging app, but am not as concerned about security, and it not having this function breaks too many features for me to keep it.

I am forced to uninstall Signal until this becomes an option, sadly.

**Comment by johanw666** [comment] 2017-12-03 20:43
@ibigfire noone forces you to use Signal for sms messages. You can use Signal for secure messages over the internet and something else for sms.

**Comment by demokritos** [comment] 2017-12-04 01:29
Enabling this option can popularize Signal. If Signal can function as a normal SMS app, I would recommend it to people. People do not want to install a messenger not used by many of their friends, but they will install a multifunctional good SMS app.

**Comment by IanTangney** [comment] 2017-12-04 20:15
This would make it much easier for me to continue to use signal. Right now I like to be able to write SMS from my computer(via AirDroid), and that's not possible if I use Signal to handle SMS. 
If the signal desktop client could send SMS via my phone, this would be less of an issue.

**Comment by deutrino** [comment] 2018-01-05 18:07
Duplicate of #5491

**Comment by automated-signal** [comment] 2018-04-03 00:34
GitHub Issue Cleanup:
See #7598 for more information.

**Closed by automated-signal** 2018-04-03 00:34 UTC
