### ISSUE TITLE
old chat from android device are not synced in desktop version on linux

### ISSUE THREAD

**Issue by awg01** [signalapp/Signal-Android#10598] opened 2021-01-13 16:50 UTC
I was chatting on android device on signal but when I opened signal on my linux pc previous chats aren't synced in pc.

**Comment by Sgn-32** [comment] 2021-01-13 16:56
Please post a debug log from both devices.

**Comment by Ashvith** [comment] 2021-01-13 17:13
> I was chatting on android device on signal but when I opened signal on my linux pc previous chats aren't synced in pc.

You "opened" means what exactly? Were you already connected to the Signal desktop app, or did you just connect it?
Right now, signal desktop won't take any older chats that sent before connecting the desktop client.

**Comment by manuel-91** [comment] 2021-01-13 20:43
I just installed [signal desktop](https://security.archlinux.org/package/signal-desktop) on my linux and also have no old chats. But on the desktop app the very first message tells that for security reasons the history is not synced, so the behaviour seems intended. @akashgudadhe1 please check if you see this hint.

**Comment by ypshukla55** [comment] 2021-01-14 17:04
> I was chatting on android device on signal but when I opened signal on my linux pc previous chats aren't synced in pc.

Also not in Windows

**Comment by Ashvith** [comment] 2021-01-14 17:46
Can someone close this thread? I think that this isn't an issue, but a feature request.

**Comment by ypshukla55** [comment] 2021-01-14 18:02
I think it's an issue.  I created a group on Android phone and later I removed my friend & deleted the conversation.
But it was still displayed on Desktop whereas already deleted on mobile. I closed and reopened Signal on desktop but still I was able to see the deleted group. So finally I deleted it manually.

So there's definitely a sync issue.

**Comment by SkoZombie** [comment] 2021-01-14 23:28
I think this is from behaviour that is unexpected by the user where the history won't sync and users will see "For your security, conversation history isn't transferred to new linked devices.". It's intended behaviour by the developers but it seems to be due to a relatively recent change in the desktop app that is frustrating people, myself included as there is no way to override it.

So it's arguably a feature request to turn off a new change to the app, or make it configurable/ prompt for confirmation etc. Not sure if you consider changes that impact UX an issue or a feature request.

**Comment by stingray21** [comment] 2021-06-24 20:39
I agree, even if this is the intended default behavior, there should be an option import or sync your history. Every time I use a new PC, I lose all my conversations. This is a deal breaker for me, since I usually prefer using my laptop over my phone for messaging.

**Comment by greyson-signal** [comment] 2021-06-28 16:20
We have never had a mechanism to sync old messages to a newly-linked device. 

> Every time I use a new PC, I lose all my conversations.

If you're switching PC's though, you should be able to copy your data directory to the new computer and keep all of your message history.

> I created a group on Android phone and later I removed my friend & deleted the conversation.
But it was still displayed on Desktop whereas already deleted on mobile

In general, we do not sync data deletions across linked devices. It may be something we do in the future, but we have no immediate plans.

**Closed by greyson-signal** 2021-06-28 16:20 UTC
