### ISSUE TITLE
Cannot Send GIFs from Gboard, Signal to Signal, exceeded the size limit

### ISSUE THREAD

**Issue by the4ndy** [signalapp/Signal-Android#8775] opened 2019-04-20 00:20 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I cannot send a gif image obtained using the gboard keyboard app. I was able to on my previous device, Google Nexus 5x on Android 8.1.0 on Signal 4.38.2 but now cannot on my brand new Pixel 3 XL on Android 9, signal version 4.38.2 (also tried on non beta, 4.37.2). I get the error message, "an item was removed because it exceeded the size limit" in a toast at the bottom of the screen. I am on Google Fi as my carrier, this was the same carrier and plan on both the old and my new current phone.

### Steps to reproduce
- Install Signal 4.38.2 from Play Store
- use Gboard as default keyboard
- open and choose any GIF within the keyboard

**Actual result:**  I get the error message, "an item was removed because it exceeded the size limit" in a toast at the bottom of the screen.

**Expected result:** The GIF image adds to the message and can be sent to the Signal user.

### Screenshots
Same as screenshot as in this issue (just newer looking) 
https://github.com/signalapp/Signal-Android/issues/6187#issue-206098978

### Device info

**Device:** Google Pixel 3 XL
**Android version:** 9
**Signal version:** 4.38.2 (or 4.37.2)

### Link to debug log
https://debuglogs.org/41c243145551573443e9e1355141e9491e7bdf2ac0948214272f61851f348710

**Comment by greyson-signal** [comment] 2019-04-20 00:48
Dupe of #8626. I can confirm that you can send a gif from Gboard as a Signal message. When sending via SMS, it's a mixed bag. We're updating the MMS configs in 4.39.x, maybe that will fix it.

**Closed by greyson-signal** 2019-04-20 00:48 UTC
