### ISSUE TITLE
Can't link devices / scan QR

### ISSUE THREAD

**Issue by bartz1** [signalapp/Signal-Android#4637] opened 2015-11-20 20:30 UTC
I am stuck at the step saying "scan the qr code displayed...". I can see the qr code in the camera, but it won't do anything. I'm assuming there should be a moment when the phone goes like "okay I saw that's a qr code", but nothing happens. I think the problem may be that the camera is a bit out of focus.
Samsung galaxy s3, signal 3.5

**Comment by bartz1** [comment] 2015-11-20 20:36
I can confirm the problem is that the camera not being in focus. I have the same problem when using the quick direct capture (can't click to focus).
I came to this conclusion after taking a screenshot and zooming -- it linked the device

**Comment by 2-4601** [comment] 2015-11-21 00:00
You might already be aware of this pr #3767 but marking it here as related.

**Comment by bartz1** [comment] 2015-11-21 09:32
I don't know if the code that the quick camera uses is the same as the one used by the qr scanner (I haven't looked at the code to be honest) but it seems to be the case.

**Comment by ndevln** [comment] 2015-12-04 16:32
As in #4804 autofocus is not working when QR Code scanning. I have the same setup:
Signal version: 3.6.1
Android version: 5.1.1 (Cyanogenmod 12.1) snapshot
Device: Samsung Galaxy S2 ("i9100")

**Comment by ndevln** [comment] 2015-12-04 19:16
Saving the QR-Code png and zoomind doesn't work for me. Even when the QR Code is sharp on the screen, it is not recognized. Also when using Signal 3.7.0, I can scan the Code via an external App and it opens Signal, but in Signal I have to rescan.

**Comment by moxie0** [comment] 2015-12-04 20:07
@ndevln does it make a difference if you try rotating the device to portrait or landscape?

**Comment by HansHerbert** [comment] 2015-12-04 21:25
No difference for me

Signal version: 3.6.1
Android version: 5.1.1 (Cyanogenmod 12.1)
Device: Samsung Galaxy S2 ("i9100")

**Comment by ndevln** [comment] 2015-12-05 00:15
No makes no difference. Also moving the QR Code in from all sides makes no difference (in portrait and landscape mode). Also I can't take pictures with my back camera in the messaging view (but i can see the preview). My front camera works in the quick camera mode (autofocus and capturing pictures). I think using the front camera for the qr code scan would work, but it's still only a workaround.

**Comment by lolonaut** [comment] 2015-12-05 13:49
Same situation here, Signal doesn't focus and the QR code won't get recognized (zoomed screenshot or switching between landscape/portrait doesn't help).

Signal version: 3.6.1
Android: 5.1.1 (Cyanogenmod 12.1)
Device: Galaxy S2 (i9100)

**Comment by JStyle21** [comment] 2015-12-05 20:13
+1 to this issue it's the same as described by me in 4661.

**Comment by lolonaut** [comment] 2015-12-05 22:48
Apart from the camera issue, what speaks against manual device linking (e.g. via typing of a code)? 
Would be a workaround for this case and the only option for people with broken cameras (or even smartphones without a camera)...

**Comment by JStyle21** [comment] 2015-12-06 01:05
lolonaut couldn't agree more!

**Comment by ndevln** [comment] 2015-12-06 16:00
I think it's not quite as simple as that, since this function allows you to get a full take an the devices communication over Signal. For example the verification of the fingerprint of your contacts is done by an external app (f-droid barcode scanner in my case).  But for this scan they use an internal approach, which I think is a deliberate choice.

Secure design is hard to get right and I think @moxie0 has put some thought into it.

**Comment by lolonaut** [comment] 2015-12-06 17:46
I'm not sure if I understand you right...my suggestion would be to show the QR-code data (i.e. the uuid and the ub_key) underneath the QR-code-field in the chrome app and to add a manual linking option into the smartphone app, where one could type the uuid and the ub_key by hand.
Would this really be less secure?

**Comment by HansHerbert** [comment] 2015-12-06 17:48
I don't see why this should be less secure. The form of the data shouldn't have any impact on the security.

**Comment by abcdev** [comment] 2015-12-14 22:23
There seems to be a very strange bug within the auto focus behavior of the Samsung Galaxy S2 (other devices may be affected too).

The CameraView class checks the supported focusModes (on the S2 both  FOCUS_MODE_CONTINUOUS_PICTURE and  FOCUS_MODE_CONTINUOUS_VIDEO are reported back as supported by camera.getParameters()) and sets them if available. This alone should trigger continuous auto focus but it doesn't on this device. 

So AFAIK the only solution is invoking camera.autoFocus() reasonably often enough between startPreview() and before stopPreview().

Signal version: 3.6.1
Android: 5.1.1 (Cyanogenmod 12.1)
Device: Galaxy S2 (i9100)

**Comment by nerdoc** [comment] 2015-12-22 04:44
I also can confirm this issue on my S2.

What I want to add is that the QR scanner from the (open source) "Barcode scanner" `com.google.zxing.client.android` does work perfectly, while signal's implementation does not.

Signal version: 3.7.2
Android version: 5.1.1 (Cyanogenmod 12.1) snapshot
Device: Samsung Galaxy S2 ("i9100")

**Comment by JStyle21** [comment] 2015-12-22 19:32
This is exactly what happens and the reason i've opened my issue(referenced above).
I've also tried several QR scanners and all of them worked as well but since the link process stopped using a URL and switched to an internal scanner it stopped working for me.
Please address this problem with some priority as it related to basic functionality (even tho it's still in beta).

**Comment by lukeIam** [comment] 2015-12-22 20:01
The preview image looks sharp, but it es not recognized :disappointed:

**Comment by raubv0gel** [comment] 2015-12-26 13:20
Same issue here.

**Comment by cjuner** [comment] 2015-12-26 21:30
:+1: (S2, i9100)

**Comment by 2-4601** [comment] 2015-12-26 22:03
Unfortunately bumping or :+1:s don't help fixing this issue (they just create extra email notifications). Please only post if you have new information that will help to solve the issue. Thanks

**Comment by MonsterCode8000** [comment] 2016-01-27 13:05
Same issue here, with the XCover2 (GT-S7710) Android- Version 4.1.2.

**Comment by ngulden** [comment] 2016-01-27 15:28
Same issue with Galaxy S2 and CM 12.1.

**Comment by neurotensin** [comment] 2016-02-09 18:39
Hi, I posted in desktop https://github.com/WhisperSystems/Signal-Desktop/issues/665 issues too, so this is probably belongs here:
 https://gist.github.com/anonymous/299d4e71409a231f5396

**Comment by SeIek** [comment] 2016-02-20 17:30
I have the same problem with the Galaxy S2 and CM 13.0. For what it's worth, the Whatsapp QR device linking worked without any problems.

I just got invited to the Signal Desktop Beta and can't use it because of this bug, is there a workaround for the time being?

**Comment by turion** [comment] 2016-03-21 19:18
Having the same problem. I'm using a ShiftPhone 5.1 with Android 5.1 and Signal 3.13.1. The image of the QR-Code is absolutely in focus, this is not the problem.

**Comment by 2-4601** [comment] 2016-03-21 19:30
@turion is the ROM in your device Cyanogenmod based?

**Comment by turion** [comment] 2016-03-21 19:47
@2-4601, not that I know of.

**Comment by cguentherTUChemnitz** [comment] 2016-03-23 15:00
I have the same problem. I am using a Samsung Galaxy S2 with Cyanogenmod 13 (cm-13.0-20160322-NIGHTLY-i9100). It seem to be handled strange by the signal app. In contrast the barcode scanner app recognizes correctly the qr-code and gives a link. When i follow the link the signal app is opened but nothing happens. The signal app itself does not recognize the qr-code. It does not even try to focus my screen, showing the qr-code.

**Comment by Y0Mamma** [comment] 2016-03-31 04:34
I was having the same problem as everybody else. On a whim, I changed my default messaging app from Hangouts to Signal. The barcode scanning for linking devices worked after I did this.

**Comment by turion** [comment] 2016-03-31 07:29
I had changed my default messaging app before, and it didn't make a difference. But it also worked for me after many, many tries. So I can only recommend trying often and moving the camera back and forth in order to hit the focus point better.

**Comment by lukeIam** [comment] 2016-04-02 09:14
No success - neither with changing the default app nor 10min trying to hit the perfect focus point :disappointed: 

Is it much work to add the possibility to change to the front camera to the qr scanner?
If this problem is caused by malformed image (https://github.com/WhisperSystems/Signal-Android/issues/4899) that might be a workaround.
(S2's front camera has no autofocus but with QR Droid it is easy to scan a qr code with it)

**Comment by chepec** [comment] 2016-04-06 19:23
Same issue. The QR code is visible in Signal's "viewfinder", but nothing happens. I would expect the app to "lock onto" the QR code and give some sort of feedback.
I just updated to Signal 3.15.2, but this issue remains. Here's my [Signal debug log](https://gist.github.com/5c73d15f1e02ff4157ceef92e6423f97) at the time.

**Comment by GuidoGa** [comment] 2016-04-26 20:51
Same issue here.

The camera works well, and the QR can be read without trouble from the Barcode Sanner app. But when triying to do it from within signal the camera doesn't focus. I've solved it by enlarging the QR.

Samsung Galaxy J1 Ace
Android 5.1.1
Signal Private Messenger 3.15.2

**Comment by chrysh** [comment] 2016-05-03 09:37
I stupid workaround: Take a screenshot of the QR code on your computer, then zoom in with your favorite graphics program, scan that with the signal app.

Worked for me (Samsung Galaxy Note I)

**Comment by Catscratch** [comment] 2016-05-03 09:46
At least, this workaround isn't working for me. No matter which scale level I choose.

**Comment by lukeIam** [comment] 2016-05-03 11:00
> A stupid workaround: Take a screenshot of the QR code on your computer, then zoom in with your favorite graphics program, scan that with the signal app.

Also not working for me (S2): Tried multiple sizes ans monitors.

 Anyone found the time to test the [`flipCamera` idea](https://github.com/WhisperSystems/Signal-Android/issues/4637#issuecomment-204678987)?

**Comment by chepec** [comment] 2016-05-03 12:01
Yeah, taking a screenshot and magnifying did not work for me either (Galaxy S2 with latest CyanogenMod).

I would like to take a step back, and note that from a UX perspective, the app should not assume that every user has a working camera, or has access to the camera during registration. Maybe they have disabled the camera for privacy-purposes, or whatever. 
Why can't the "Add device" screen in the Android app be gifted with an option to input the `uuid` and `pub_key` manually? Since it would only be done once, the extra typing work would probably be acceptable for such users.

The Chrome app actually displays the necessary information on mouse-over:
![ ](https://luxor.chepec.se/owncloud/index.php/s/aYEeyuvRXuBoA9p/download)

I haven't been able to even test the Signal desktop app because of this issue, so I would be happy with any solution.

**Comment by Catscratch** [comment] 2016-05-31 06:57
Is this fix already in latest cm build? And if so, does anyone tested it?

**Comment by SeIek** [comment] 2016-06-11 17:13
On my SGS 2 with CM 13.0-20160611-NIGHTLY-i9100 and Signal 3.16.0 it still doesn't work, sadly.

**Comment by fliegentoeter** [comment] 2016-06-17 12:49
It still is not working -.-
Running latest CM13 on a Xperia M

**Comment by borowitz** [comment] 2016-07-04 13:19
Same issue here signal 3.16.0. It did work when I took a screenshot and zoomed in on it.

**Comment by SeIek** [comment] 2016-07-29 13:33
I switched to SlimSaber 4.4.4 on my SGS 2 and it works. So it most likely has to do with how Cyanogenmod handles it.

**Comment by lukeIam** [comment] 2016-08-20 14:42
I tired cm-13.0-20160818-NIGHTLY on my S2 and it is working! :+1: 
The code is recognized in under a second.

Looks like https://github.com/CyanogenMod/android_device_samsung_galaxys2-common/commit/b7fa70df69e8d54b8ec72750989e7a9eda67f573 did the trick.

**Comment by nerdoc** [comment] 2016-08-22 04:50
I cant confirm that any more, as I don't use GApps any more, therefore Signal is not working on my device and I had to remove it. Sorry about that, but unless #127 is not fixed, I'm not able to use Signal...

**Comment by JacobHenner** [comment] 2016-10-14 15:50
Experiencing this on CM 13, neither the QR scanning nor the in-chat camera feature starts the camera. All other apps using camera (e.g. facebook messenger) seem to work.

**Comment by Integral** [comment] 2016-11-07 11:40
Worked for me couple months ago after making screenshot, zooming in and rotating. But now it's not working anymore (during last month). Lenovo s856, debug log: https://gist.github.com/anonymous/3c24d13861f97632cce7b2f08c50b53c

**Comment by spacekookie** [comment] 2016-11-16 13:26
Personally I've not had issues with it. BUT two of my friends are experiencing this issue. It seems to be that the camera isn't focusing properly.

Happening with a Samsung GT-S7580.

Anything that might help fix this? (haven't read the entire thread)

**Comment by lpirl** [comment] 2016-11-16 13:45
@spacekookie please do read the thread and save everyone's time (try phone in landscape or moving it from real close to far away slowly in the hope the QR is in focus at some point).

**Comment by merkste** [comment] 2016-12-01 17:49
I have troubles scanning QR codes as well. It seems to be a general focusing problem of the in-app camera, as described in #5276. None of the workarounds mentioned above help. If a QR code is successfully scanned, it seem to happen by chance.

**Comment by tschernobyl** [comment] 2017-01-11 08:35
I too have the problem which I suspect is due to the back camera of my Nexus 5X being a bit broken. It can't focus and so I can't pair new devices. Same goes for Whatsapp (which uses the same underlying protocol).

**Comment by riyapenn** [comment] 2017-01-12 18:05
One user has had success taking a screenshot of the QR code, zooming in, and using the phone camera to scan.

Again, I'm suggesting you 
1. Take a screen shot on your computer of Signal Desktop with the QR code
2. Open the screen shot image in an image viewer i.e. MS Paint
3. Zoom in on the image
4. Take your phone and scan the "zoomed-in QR code"

**Comment by tschernobyl** [comment] 2017-01-13 10:24
@riyapenn it worked!

**Comment by bengoldstein** [comment] 2017-01-17 20:40
Uh, I had this problem. Tried various things, including printing the QR code and it still didn't work. I futzed with camera settings because no matter what I did it was blurry. Then I looked at the lens and noticed schmutz on it. I cleaned that off and presto, no problem. Duh.

**Comment by timbury** [comment] 2017-02-05 21:17
I have this same issue on my Sprint HTC One m7 (camera sucks but is functioning). If I use a generic barcode scanning app, it scans it immediately but that is no help authenticating in Signal. It does show, however, there is no problem with the camera's focus, functionality or cleanliness. Any idea of the scope of this issue? Is this affecting most users? Some? Few? Seems to me it is a critical bug if the scope is broad enough.

**Comment by spacebast** [comment] 2017-02-06 19:11
Same with Galaxy Xcover 2 (GT-S7710, quite similiar to S2), Vanir AOSP Android 4.4.4:
No image if i want to read the QR-code, seems like no access to the cam. Otherwise no problem with taking photos from the chat directly or using the camera with other apps.
Log:
[https://gist.github.com/anonymous/5d7331deacd821b0f6246d3dc36fdf6a](url)

**Comment by lpirl** [comment] 2017-02-07 15:22
offtopic: @spacebast could you maybe contact me (github@lukas-pirl.de) - I'd like to ask some really quick questions regarding Vanir in combination with the Xcover2 and I couldn't find your email address. Thx!

**Comment by Lesik** [comment] 2017-02-17 14:23
I am using a Nexus S with Android 4.4.4 (CM 11) and am having the same issue, due to the QR code being out of focus. The WhatsApp app is constantly refocusing, but Signal does nothing.

The workaround (screencapping the QR code, then enlarging it in GIMP) solved the issue, but this isn't a suitable workaround for newbies, which is who the app is mainly targeted towards.

**Comment by ypsy** [comment] 2017-03-02 20:06
I copied the workaround provided by f41c0r (see above) to a fork of the current Signal (his original workaround was applied to WebSocket LibreSignal), as this was still not working on my Xperia M with latest Lineage OS: [https://github.com/ypsy/Signal-Android](url) 

Works fine now for me! You have to scan the code using an external app and then enter the link into signal manually.

Disclaimer: I really have no clue about all this, just reproduced the changes made by f41c0r, who originally wrote the workaround. If there's anything I did wrong, let me know.

**Comment by ngulden** [comment] 2017-03-13 19:23
I no longer observe this issue on my Samsung Galaxy SII (GT-I9100) running LineageOS 14.1-20170307-NIGHTLY (Android 7.1.1) and Signal 3.30.4.

**Comment by ypsy** [comment] 2017-04-27 14:27
Still not working for me on Sony Xperia M (nicki) with newest Lineage OS (build from 20.04.17) and a fresh install of the latest Signal.

**Comment by skom91** [comment] 2017-04-28 17:26
Also same for me in Xperia M same Lineage OS. 
Barcode scanner com.google.zxing.client.android is working fine, camera, focus, everyting else too, just the in app scanner is not able to scan the QR-Code even if its focused.
A Workaround solution like that would also be fine:
https://github.com/WhisperSystems/Signal-Android/pull/5538
This would also solve Problems with Broken Cameras for example.

**Comment by SergeBouchut** [comment] 2017-05-11 16:04
Same problem on Sony Xperia M C1905 with LineageOS 14.1 (nicki) and latest Signal.

**Comment by hundertsieben** [comment] 2017-07-01 14:39
The smartphone I'm using has a really bad camera and won't scan the code. Not even in a QR code scanner. I tried enlarging the picture and I tried cleaning the lense. I'm stuck. And a bit pissed that Signal obviously wants me to be a wealthy person to use all of its features.

**Comment by kousu** [comment] 2017-08-07 12:28
I have a [MotoE first gen](https://wiki.lineageos.org/devices/condor) whose camera is pretty good but has zero ability to focus, and I cannot link devices. After reading this thread, the take-a-screenshot-and-zoom trick worked for me, but it seems kludgy.

A lot of smartphones are cheap and will never be able to scan a dense QR code properly.

If #5538 isn't going to be merged, what if that workaround was at least documented in the [FAQ](https://support.whispersystems.org/hc/en-us/sections/203364607-Signal-Desktop-FAQ)?

**Comment by MarcelNehring** [comment] 2017-11-06 16:38
What is the official comment on this issue?

Samsung Galaxy S 2 (GT-I9100) with Lineage OS 14.1.20171101-NIGHTLY-i9100 here and no way to link devices. The screenshot & zoom-in workaround does also not work. Other QR code apps recognize the code without problems.

**Comment by automated-signal** [comment] 2018-04-02 22:01
GitHub Issue Cleanup:
See #7598 for more information.

**Closed by automated-signal** 2018-04-02 22:01 UTC
Labels: bug
