### ISSUE TITLE
UK number with country code +44 not visible in contacts

### ISSUE THREAD

**Issue by rajil** [signalapp/Signal-Android#10515] opened 2021-01-12 01:18 UTC
I have +44 for UK mobile numbers. Unfortunately, Signal does not recognize it.  Once I replace +44 with 0, then the contact is visible.

**Comment by ak79235** [comment] 2021-01-12 05:35
I'll work on this issue.

**Comment by ak79235** [comment] 2021-01-12 12:12
The issue is fixed with the android app.
Signal now recognises +44 for UK.

**Closed** 2022-02-03 10:25 UTC
Labels: wontfix
