### ISSUE TITLE
recipient lookup sporadically fails for message notifications

### ISSUE THREAD

**Issue by huxys** [signalapp/Signal-Android#2612] opened 2015-03-07 10:56 UTC
Hi,

I'm using the latest version of TS (googleplay) in Kitkat.

When I receive a SMS from a contact in my contacts list, sometimes the notification shows the number instead of the name.
It seems to be random, If i receive a SMS from ,A, can show 90xxxx and next can show ,A,...

The SMS are sent through carrier, any of my contacts use TS...

Thanks

**Comment by generalmanager** [comment] 2015-03-07 11:53
I guess that's because you saved some numbers in a different format. Maybe without the national prefix or special characters.

**Comment by agrajaghh** [comment] 2015-03-07 12:01
is it really happening with the same number? Or with different contacts?

**Comment by huxys** [comment] 2015-03-07 16:21
It happens with the same number.

I've a contact named Jonh Doe with the number 91x xxx xxx.
If that contact sends a SMS, in the notification can appear, "message from 91x xxx xxx" as the next one can appear "message from Jonh Doe".

I've made a test, where I sent a SMS from my daughter's phone, 

1 - The sound of the notification were 2 beeps instead of one, and the notification showed her number.
2- I've  exit the TS and locked him.
3- I've sent another SMS and now only one beep, and her name in the notification.

I'm seeing a  pattern that every time the notification shows the number instead of the name, it makes 2 beeps instead of one (if I've the sound on.... :D)

My notification sound is the hangouts sound.
No other SMS app installed in my phone, Hangouts is frozen.

**Comment by agrajaghh** [comment] 2015-03-07 17:13
Could you please post a debug log where TS is displaying the number and one where its displaying the name?

**Comment by huxys** [comment] 2015-03-07 18:01
with name
https://gist.github.com/anonymous/af23da5edc6fff9fc84f

without name
https://gist.github.com/anonymous/1c37445d4f35091bdc97

I've rebooted the phone to get the notification without the name, as I been testing, it was showing the name.

**Comment by rhodey** [comment] 2015-03-13 18:14
this issue appears to be a duplicate of #1943 however because it is more recent and contains more debugging information I will be closing the original.

**Comment by huxys** [comment] 2015-03-13 19:27
Thanks for the attention,

I didn't see that post... maybe I need to change my glasses... :D

If there is anything that I can do to help, you only need to say it.

**Comment by McLoo** [comment] 2015-03-25 19:41
had this today on 2.8.0 - and of course I checked the log. Only thing regarding contacts was some entry from XPrivacy and I did not dare to post the log ;-)
Usually it works just fine. Keeping an eye on it.

**Comment by Grot4x** [comment] 2015-04-09 08:06
I can confirm this for TextSecure messages.
In some notifications the contact info is missing so instead of the contact image you see the gray standard icon and instead of the name you can see the tel. number.
I didn't find a way to reproduce this, and whats even more confusing is that sometimes it works as intended and in the next minute it fails.
TextSecure: 2.10.2
Android: 4.4.4
Device  : motorola XT1039 (peregrine_retde)

I was able to create a log after i got a buggy notification and a few minutes later getting a new message (same contact) and it worked flawless:

Bug: https://gist.github.com/anonymous/55a97781b0c9d0d7df28

Working: https://gist.github.com/anonymous/972d9cd9a415a9cbee38

**Comment by rhodey** [comment] 2015-05-12 03:25
the logs that @Grot4x posted seem to show that the buggy behavior may be related to asynchronous `RecipientProvider` lookups, ie both logs contain multiple `W/RecipientProvider(28686): Cache miss [ASYNC]!` messages but only the "working" log contains a `W/RecipientProvider(28686): Cache miss [SYNC]!` message.

**Comment by automated-signal** [comment] 2018-04-02 21:33
GitHub Issue Cleanup:
See #7598 for more information.

**Closed by automated-signal** 2018-04-02 21:33 UTC
Labels: bug
