### ISSUE TITLE
Images taken in locked portrait mode with device held in landscape get posted in portrait position.

### ISSUE THREAD

**Issue by codeForX** [signalapp/Signal-Android#10454] opened 2021-01-10 17:27 UTC
In whatsapp the camera detects that the phone was held in landscape and automatically flips it while in signal the picture just gets posted in portrait with no option later to flip it.

**Comment by selimrecep** [comment] 2021-01-10 17:28
Actually I can't reproduce this. I have enabled automatically flip feature on Android, and photo flips with no issue. And you should include debug log, screenshot and etc.

**Comment by codeForX** [comment] 2021-01-10 17:39
> Actually I can't reproduce this. I have enabled automatically flip feature on Android, and photo flips with no issue. And you should include debug log, screenshot and etc.

Hi sorry its my first issue, ill try to have the debug log and others up shortly. the problem isn't when auto rotate is enabled its when it isn't, In other apps they flip the picture anyway.

**Comment by Frivolous2** [comment] 2021-01-10 17:50
> Actually I can't reproduce this. I have enabled automatically flip feature on Android, and photo flips with no issue. And you should include debug log, screenshot and etc.

The issue is about that other apps flip images even when auto rotation is disabled, which is a desired behaviour that's absent in Signal. Flipping auto rotate because you need landscape for 2 seconds is annoying, so some/a lot of people don't do it, and whatsapp I assume mitigates for that by enabling the sensor in camera mode, so that images shot as landscapes don't appear in portrait, because that's undesired/annoying.

**Comment by Frivolous2** [comment] 2021-01-10 18:38
That said, feature requests belong in the forum - https://community.signalusers.org/c/feature-requests/17

**Comment by QJKX** [comment] 2021-01-26 10:37
Duplicate of #8611?

**Closed** 2021-01-27 04:33 UTC
