### ISSUE TITLE
After leaving group user is still able to read new messages

### ISSUE THREAD

**Issue by dolohow** [signalapp/Signal-Android#7103] opened 2017-10-16 10:30 UTC
### Bug description
After leaving group user is still able to read new messages.  Whats funny that, he cannot leave the group anymore and he is not visible in the group members.

### Steps to reproduce
- Add user to group
- Let the user leave the group

**Actual result:** User is still able to receive and read new messages.
**Expected result:** User is not able to receive and read new messages.

### Device info
**Signal version:** 4.10.12

**Comment by janvlug** [comment] 2017-10-16 19:39
I think that this is a duplicate of issue #1115

**Comment by FeuRenard** [comment] 2017-10-17 06:52
@janvlug Are you sure you linked the correct issue? #1115 doesn't seem like a duplicate to me.

**Comment by janvlug** [comment] 2017-10-17 09:07
Sorry, I did not realize that the bug I wanted to refer to is in the Signal Desktop repo:
https://github.com/WhisperSystems/Signal-Desktop/issues/1115

BTW: I think the following issues are also related:
#4520
#6394 
#6177

See also this topic on the community board:
https://whispersystems.discoursehosting.net/t/large-groups-tend-to-become-unusable-over-time/952

**Comment by automated-signal** [comment] 2018-04-03 04:34
GitHub Issue Cleanup:
See #7598 for more information.

**Closed by automated-signal** 2018-04-03 04:34 UTC
Labels: bug
