### ISSUE TITLE
"Error downloading MMS..." in group messages with non-Signal users.

### ISSUE THREAD

**Issue by dscotese** [signalapp/Signal-Android#9188] opened 2019-11-13 17:48 UTC
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
With increasing frequency, groups that contain non-Signal users don't show messages but instead show "Error Downloading MMS message, tap to retry."  This is actually a duplicate of #6234, but that one is closed and not resolved.

### Steps to reproduce
- Create a group that contains contacts who are not using Signal.
- wait for someone to send a message to the group.
- If you get the message as usual, then keep the conversation alive until you get the error.

**Actual result:** I see "Error Downloading MMS message, tap to retry." in the group message.
**Expected result:** The message sent by my contact should appear.

I was able to get one recent message from a non-Signal user after enabling "'WiFi Calling' compatibility mode," AND restarting my phone, though I don't use WiFi calling.

### Device info

**Device:** Samsung Galaxy S7
**Android version:** 8.0.0
**Signal version:** 4.49.18

### Link to debug log
https://debuglogs.org/1065bd97a8eb1f39bbcedda5f91b5a74e0ff562c924e284b33ca90275d829c36

**Comment by Tursko** [comment] 2019-11-13 18:10
This issue has already been created. Please make sure you check before creating an issue - https://github.com/signalapp/Signal-Android/issues/9173

**Comment by dscotese** [comment] 2019-11-13 19:53
The issue to which you referred is different because my phone receives MMS from individual non-Signal users just fine.  It's only the group messages that present a problem.

**Comment by Tursko** [comment] 2019-11-13 22:09
It's probably related to the same issue though. It still seems like a duplicate.

**Comment by dscotese** [comment] 2019-11-13 22:23
I agree it's probably related.  I was thinking that Apple might have tweaked their implementation of the MMS protocol in a legal (according to the spec) but peculiar way in an effort to discredit iOS competitors (Android) who aren't careful about implementing it.  The reason I wanted to create a separate issue is that it would be a shame for Signal devs to examine the code to solve only one of these two intimately related problems.  I will add my debug log to the other issue.  Thanks for suggesting that.

**Comment by Tursko** [comment] 2019-11-13 22:26
According to that other thread, the issue seems to be isolated to ATT users (and other sub-carriers). Also its only when using SMS/MMS through Signal. No one has any issues getting MMS from the default Google Messages app. So it seems like a Signal related issue.

**Comment by madfusker** [comment] 2019-11-20 21:52
Same annoying issue on ATT SSGS9 on Android 8.   :/

**Comment by greyson-signal** [comment] 2019-11-22 17:21
Closing as a duplicate of #9173

**Closed by greyson-signal** 2019-11-22 17:21 UTC
