### ISSUE TITLE
Closing Signal from Android Overview closes the overview

### ISSUE THREAD

**Issue by ScreamingHawk** [signalapp/Signal-Android#7775] opened 2018-05-09 02:04 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When closing the application from the Android Overview view the user is directed to the launcher / home screen. 

### Steps to reproduce
- Open a bunch of apps
- Open signal
- Press the `Overview` button. The square one
- Close the signal app by swiping it away

**Actual result:** The Overview view is closed and the user is left at the launcher / home screen.
**Expected result:** Signal is closed and the user can continue to use the Overview view. 

### Screenshots
![screenshot_20180509-140447](https://user-images.githubusercontent.com/1460552/39791922-35f2b14c-5392-11e8-92a6-68fb9ca6f15c.png)

Please excuse the wife's complaints about McDs 😅

### Device info
**Device:** Nexus 6P
**Android version:** 8.1.0
**Signal version:** 4.19.3

### Link to debug log
https://debuglogs.org/8fea47c3e0519c46b97f98c0fff981e80dbf1530aa56300b09daf14a88f2cf3f

**Comment by bme13** [comment] 2018-05-09 04:47
Don't know about the McD, but I think this issue is a duplicate of #1037.

**Closed** 2018-05-09 06:52 UTC
