### ISSUE TITLE
app crashing when trying to share location

### ISSUE THREAD

**Issue by fareszr** [signalapp/Signal-Android#9777] opened 2020-06-23 02:07 UTC
### Bug description
when i try to share a location the app crashes when trying to genrate link preview for google maps(my guess)

### Steps to reproduce
- open the desired chat
- click the location icon
- select the place you want to share

**Actual result:** the app crashed after selecting the location
**Expected result:** the app should not crash and should continue to operate normally and be able to send the message

### Screenshots
![signal-2020-06-23-050244](https://user-images.githubusercontent.com/35614734/85352789-6d3be480-b50f-11ea-8fb9-f891796f2ec0.jpeg)

### Device info

**Device:** Galaxy S10+
**Android version:** Linage os 17.1(android 10) with micro G
**Signal version:** 4.61.6

### Link to debug log
https://debuglogs.org/2bd20f61f07803a8fdf52ac666cfb89511c0b281bb1d514961e323572018f284

**Comment by JanZerebecki** [comment] 2020-07-17 13:43
Duplicate of #9101

**Closed** 2020-07-28 14:29 UTC
