### ISSUE TITLE
Cannot unlock app as no passphrase was set before locking

### ISSUE THREAD

**Issue by deshant** [signalapp/Signal-Android#10367] opened 2021-01-08 05:45 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
A new user, just downloaded the app, registered myself. Now I am locked out of the app and can't unlock. I have clicked on "lock signal" from notification bar, and cannot unlock. I had not set any passphrase after registration. 

### Steps to reproduce
- Fresh registration
- Do not setup any PIN or passphrase or go to any settings even. 
- Send a text to someone. (mentioning this as I did this, else I don't this this matters)
- Notification starts appearing that Signal is unlocked.
- Lock it from notification
- Can't unlock using device PIN or even after setting passphrase in device security settings. 

**Actual result:** Cannot unlock app using device PIN or passphrase. No PIN or passphrase was set in Signal app.
**Expected result:** Should be able to unlock using device PIN or passphrase.

### Device info

Manufacturer  : Motorola
Model         : Motorola one power
**Android version:** 10 (8f02e, QPTS30.61-18-16-3)
**Signal version:** 5.0.8

### Link to debug log
https://debuglogs.org/ba84dc270117d72705c1da4ac122c73666c01453efafb9b09ff23472fe4f138c

### Comments
I have fingerprint unlock enabled. I know it is not used by signal but I was expecting my PIN to be accepted since I have not explicitly set any from the app after installing. 
If no separate unlocking mechanism is set in app, then either the app should let user set it first before locking them out or let the device PIN or passphrase work.

**Comment by bme13** [comment] 2021-01-08 15:42
Hi @deshant and welcome,
To me it seems you enabled the screen lock. This should use the device fingerprint method to unlock.

**Comment by theprojectsomething** [comment] 2021-01-09 00:11
Same issue. There is no fingerprint option available, only passphrase which hasn't been set. No way around it.

**Comment by endercrest** [comment] 2021-01-09 00:12
I am having a similar problem. Restarted phone and is now prompting for a passphrase to unlock. I never used the lock notification.

**Comment by deshant** [comment] 2021-01-09 15:52
> Hi @deshant and welcome,
> To me it seems you enabled the screen lock. This should use the device fingerprint method to unlock.

Not happening anything when I put my finger on fingerprint scanner. Not able to unlock in any way possible.

**Comment by theprojectsomething** [comment] 2021-01-11 02:43
Some more context - I had the app installed (but unused) and updating in the background for some time (possibly across phones). All phones had a fingerprint sensor. Joining the beta program had no effect. Deleting the app completely (losing my conversations) and reinstalling resolved the issue.

**Comment by deshant** [comment] 2021-01-11 11:58
@theprojectsomething This is barely a workaround, can't accept it as a solution. The app is having a bug which is locking users out. Let's hope some contributor picks this up. 

Meanwhile I am keeping the app as it is, so that if someone fixes it I can test the new update. There is only 1 test message from my friend so nothing to lose here.

**Comment by theprojectsomething** [comment] 2021-01-11 12:19
@deshant apologies, I needed to continue using the app which was why I opted for the nuclear option ... definitely wasn't suggesting deleting as a useful workaround - just providing context for any potential deep-dig.

Looks like beta channel is only a few patches behind master (I'm currently running a 4 day old build), so here's hoping your  persistence pays off (pre whatsappageddon)!

**Comment by lewispollard** [comment] 2021-01-11 15:54
Same issue, except my phone (Pixel 4) doesn't have a fingerprint reader, and I use face unlock.

From reading the documentation it looks like my phone's PIN should unlock but it doesn't. I have also tried disabling face unlock, leaving only the PIN option, clearing cache and restarting the phone.

**Comment by greyson-signal** [comment] 2021-01-13 04:59
@deshant I think I see one possible problem in your debuglog where we don't properly do the initialization we're supposed to do after your first-ever app launch. I put some failsafes in the upcoming 5.2.x.

If anyone else sees this again, please take a debuglog asap and share it here, thank you!

**Comment by deshant** [comment] 2021-01-13 07:06
@theprojectsomething Hey its fine, I was only pointing out that resetting app is not a solution to avoid any misunderstanding. You need to continue using the app, or else you would also have helped in re-testing from scratch, since you have anyways sacrificed your messages.

@greyson-signal Glad the logs could help. Please help clear my understanding of the fix. 

> @deshant I think I see one possible problem in your debuglog where we don't properly do the initialization we're supposed to do after your first-ever app launch. I put some failsafes in the upcoming 5.2.x.

Correct me if I am wrong here, the fix will now properly initialize for `first-ever app launch` and this issue will not occur. This means for cases like me (already locked out), even if I upgrade to the build with the fix, I will still be locked out as the fix only works for initial launches.

If I am right here, I will have to nuke the app just like @theprojectsomething did.

**Comment by c-rizz** [comment] 2021-01-13 12:36
> @deshant I think I see one possible problem in your debuglog where we don't properly do the initialization we're supposed to do after your first-ever app launch. I put some failsafes in the upcoming 5.2.x.
> 
> If anyone else sees this again, please take a debuglog asap and share it here, thank you!

I belive I'm having the same issue. A few days ago I reinstalled signal after a long time I haven't used it, now I'm locked out of the app. It says "Signal is locked" and requires a "passphrase". I don't remember setting it. Two questions:
- Is it a signal passphrase or is it supposed to be the android unlock?
- Will the failsafes you mentioned allow to see currently unread messages or do they still require a reinstall?

I'm attaching a debug log

Thanks! 

https://debuglogs.org/c89f6b83b2ba58309a12f2d5770ab835566d20e55a4ad9576c38fc7472b73907

**Comment by mulmschneider** [comment] 2021-01-13 13:21
Encountered the same issue. Also had the app installed for a long time, but wasn't using it. Completed initial setup yesterday, and then pressed 'lock' (without setting any kind of passphrase).

Logs: https://debuglogs.org/c47853c7e23dc1871e04d39cc2d98459e59937afe7f43ea379b1e15861ff7946
Note: I updated to the latest version in the app-store after hitting the passphrase screen, but before generating the logs.

**Comment by greyson-signal** [comment] 2021-01-13 15:11
@deshant I believe the best course of action would be to reinstall the app, yes. There's actually a bunch of less-visible state that probably is also screwed up besides this particular flag. I'm sorry :( I'm guessing you haven't been able to use the app for the past 5 days though?

The other users who are describing scenarios where they installed the app a long time ago but just opened it for the first time makes more sense to me why this may happen, but I find your scenario (where you downloaded and opened soon after) more confusing. Do you recall doing anything else of note?

**Comment by rboyer** [comment] 2021-01-13 16:20
This just happened to me as well on my old Moto X test phone on Android 5.1 (very recently installed with no backup restored):

https://debuglogs.org/1144aa2430498b069d6c6d1fa55952b1a71ce3c8cc2b6ab62acd0d729ab6c7b9

**Comment by c-rizz** [comment] 2021-01-13 16:49
> @deshant I believe the best course of action would be to reinstall the app, yes. There's actually a bunch of less-visible state that probably is also screwed up besides this particular flag. I'm sorry :( I'm guessing you haven't been able to use the app for the past 5 days though?
> 
> The other users who are describing scenarios where they installed the app a long time ago but just opened it for the first time makes more sense to me why this may happen, but I find your scenario (where you downloaded and opened soon after) more confusing. Do you recall doing anything else of note?

I belive I installed it on the 11th, used it a bit, then didn't use it until today when I tried to open it.
Also, I'm not sure if this is helpful, the precise error it gives is "Invalid passphrase!"

**Comment by lewispollard** [comment] 2021-01-13 16:52
> @deshant The other users who are describing scenarios where they installed the app a long time ago but just opened it for the first time makes more sense to me why this may happen, but I find your scenario (where you downloaded and opened soon after) more confusing. Do you recall doing anything else of note?

I'm one of those who've never used Signal before up until now. Installed 2 days ago, activated, at some point I didn't like the persistent "unlocked" notification so I pressed "lock", and haven't been able to unlock since. I'm going to uninstall and reinstall as it doesn't sound like there's any hope of getting the messages I received since then in the meantime (thankfully only 2 days worth)

**Comment by danilobellini** [comment] 2021-01-13 19:55
Same issue here (phone without a screen locker, not using Signal for the first time).

https://debuglogs.org/a2a0202f7698d8e69045e6cd09b1a5f4b6242fa1bc75f26abfe91ba2287357d3

**Comment by greyson-signal** [comment] 2021-01-13 22:30
Ok so I jumped the gun a little bit on suggesting reinstall. We thought more about it and came up with something that should fix existing installations that are stuck in this state. Getting a prod hotfix ready, 5.1.9. Hopefully that'll get everyone back in working shape!

@danilobellini Your case is a bit more odd. Curious if this works for you too, let me know.

**Comment by dev-au** [comment] 2021-01-14 00:58
I installed Signal on my Galaxy S7 3 days ago after getting sick of Whatsapp. I did not got a confirmation text and/or call straight away. the calls and text came 12 hours after when i was in deep sleep. This should be something that the developers can look at.
However when i woke up and tried to setup Signal again the text came straight away and the verification boxes got prefilled and my phone was verified.

Anyway the issue now is that i got the error "Signal is Locked Enter Passphrase" when i opened signal https://i.imgur.com/S3Xwr2V.jpg

I did not lock signal at all and set any PIN or passphrase during setup and now i am stuck. The message app was taken over by Signal (With my permission). Now i cannot see any messages which are coming. I can only see Locked on screen.

and here is Signal debug log:
https://debuglogs.org/1942ca5f579257b8ddc948d407d1fdcd35dd9760a3e6922669da412bc282f2b0

**Comment by deshant** [comment] 2021-01-14 12:48
@greyson-signal Yes, not able to use from the day I installed and reported this issue, but since I am a new user it is not a big problem for me (not many contacts messaged yet), given that my installation's current state may be needed for testing any potential fixes. Viewing the comments, found lewispollard in exact same scenario I am right now.

Good to know that there may be a way to fix it without nuking. Will be testing the hotfix via prod release. Still keeping it in locked state till then.

**Comment by lewispollard** [comment] 2021-01-14 12:57
I just installed 5.2.0 from the Firebase App Distribution beta site, and happy to say it solved the problem without having to nuke my messages :+1:

**Comment by martinflack** [comment] 2021-01-14 15:22
@greyson-signal how long do you think it will be for the fixed version to hit phones via normal update on Google Play? Thanks!

**Comment by greyson-signal** [comment] 2021-01-14 18:21
@martinflack We're unfortunately seeing terrible Play Store delays lately. I submitted 5.1.9 around 20 hours ago as a hotfix to production, and it's still not live. You can also download the APK from our website. It's signed with the same key, so you can just install it over your current build. https://signal.org/android/apk/

**Comment by danilobellini** [comment] 2021-01-14 18:39
I've just installed v5.1.9 from the https://signal.org/android/apk/ link, it's still locked here. New dump: https://debuglogs.org/b8ca01022476320e8fa9fffc9c33086fedc0e7075ca2b6e1306e865a58d23282

**Comment by ACarolan** [comment] 2021-01-14 18:51
> 
> 
> I just installed 5.2.0 from the Firebase App Distribution beta site, and happy to say it solved the problem without having to nuke my messages 👍

Do you have a link to where you downloaded from? I was only able to find 5.1.9 on the official site https://signal.org/android/apk/

And according to the above comment that might not resolve it^

**Comment by agnyp** [comment] 2021-01-14 22:04
I also have the same problem, Galaxy S10, and installing 5.1.9 did not help either, regrettably. Any news?

**Comment by martinflack** [comment] 2021-01-14 22:13
Thanks @greyson-signal - I installed from https://signal.org/android/apk/ and it DID work for me on a Pixel 5.

**Comment by ProductiveRage** [comment] 2021-01-14 22:51
Installing (5.1.9) from [https://signal.org/android/apk/](https://signal.org/android/apk/) fixed it for me, too. Pixel 4. Android 11 update installed earlier this week (either yesterday or the day before, I think).

**Comment by bfreed** [comment] 2021-01-14 23:48
> 
> 
> Installing (5.1.9) from https://signal.org/android/apk/ fixed it for me, too. Pixel 4. Android 11 update installed earlier this week (either yesterday or the day before, I think).

Me too. Pixel 4A. Installed Signal for first time yesterday, used it all day. Android security update overnight, rebooted this morning, got the passphrase thing. 5.1.9 from the apk link above fixed it! Thanks

**Comment by ACarolan** [comment] 2021-01-15 02:45
> 
> 
> > Installing (5.1.9) from https://signal.org/android/apk/ fixed it for me, too. Pixel 4. Android 11 update installed earlier this week (either yesterday or the day before, I think).
> 
> Me too. Pixel 4A. Installed Signal for first time yesterday, used it all day. Android security update overnight, rebooted this morning, got the passphrase thing. 5.1.9 from the apk link above fixed it! Thanks

@bfreed Did you do anything specific? I also have a 4A and upgrading to 5.1.9 didn't do it for me, downloaded from the same link too.

**Comment by gbeach** [comment] 2021-01-15 04:11
I got locked out after rebooting my phone [Galaxy s10e) yesterday.  I installed 5.1.9 from Google Play but I'm still locked out.  I'll give 5.2 a try before reinstalling.  Any word when it will be available?

**Comment by ACarolan** [comment] 2021-01-15 05:24
> 
> 
> I got locked out after rebooting my phone [Galaxy s10e) yesterday. I installed 5.1.9 from Google Play but I'm still locked out. I'll give 5.2 a try before reinstalling. Any word when it will be available?

5.2 beta is available on APKmirror [here.](https://www.apkmirror.com/apk/signal-foundation/signal-private-messenger/signal-private-messenger-5-2-0-release/) Or you can download officially from firebase by signing up [here.](https://appdistribution.firebase.google.com/pub/i/397cab497b126839)

**Comment by deshant** [comment] 2021-01-15 05:35
Got update from Play Store, updated to 5.1.9. Was prompted to set a new PIN. Tried but got error dialog "PIN creation failed". From logs it seems it was network issue. Saw log:

```
[5.1.9] [9701] 2021-01-15 10:36:23.196 GMT+05:30 I WebSocketConnection: onOpen() connected
[5.1.9] [9701] 2021-01-15 10:36:23.197 GMT+05:30 I ApplicationDependencyPr: onConnected()
[5.1.9] [main] 2021-01-15 10:36:28.583 GMT+05:30 D LoggingFragment: [ConfirmKbsPinFragment] onCreate()
[5.1.9] [main] 2021-01-15 10:36:28.604 GMT+05:30 D LoggingFragment: [ConfirmKbsPinFragment] onStart()
[5.1.9] [main] 2021-01-15 10:36:28.609 GMT+05:30 D LoggingFragment: [CreateKbsPinFragment] onStop()
[5.1.9] [9671] 2021-01-15 10:36:33.056 GMT+05:30 I ConfirmKbsPinRepository: Setting pin on KBS
[5.1.9] [9671] 2021-01-15 10:36:33.058 GMT+05:30 I PinState: onPinChangedOrCreated()
[5.1.9] [9671] 2021-01-15 10:37:04.097 GMT+05:30 W ConfirmKbsPinRepository: null
[5.1.9] [9671] 2021-01-15 10:37:04.097 GMT+05:30 W ConfirmKbsPinRepository: org.whispersystems.signalservice.api.push.exceptions.PushNetworkException: java.net.SocketTimeoutException: failed to connect to api.backup.signal.org/52.168.69.235 (port 443) from /192.168.111.58 (port 38646) after 30000ms
[5.1.9] [9671] 2021-01-15 10:37:04.097 GMT+05:30 W ConfirmKbsPinRepository: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeRequest(PushServiceSocket.java:1576)
[5.1.9] [9671] 2021-01-15 10:37:04.097 GMT+05:30 W ConfirmKbsPinRepository: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeRequest(PushServiceSocket.java:1529)
[5.1.9] [9671] 2021-01-15 10:37:04.097 GMT+05:30 W ConfirmKbsPinRepository: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.getKeyBackupServiceToken(PushServiceSocket.java:798)
[5.1.9] [9671] 2021-01-15 10:37:04.097 GMT+05:30 W ConfirmKbsPinRepository: 	at org.whispersystems.signalservice.api.KeyBackupService.newSession(KeyBackupService.java:105)
[5.1.9] [9671] 2021-01-15 10:37:04.097 GMT+05:30 W ConfirmKbsPinRepository: 	at org.whispersystems.signalservice.api.KeyBackupService.newPinChangeSession(KeyBackupService.java:62)
[5.1.9] [9671] 2021-01-15 10:37:04.097 GMT+05:30 W ConfirmKbsPinRepository: 	at org.thoughtcrime.securesms.pin.PinState.onPinChangedOrCreated(PinState.java:178)
[5.1.9] [9671] 2021-01-15 10:37:04.097 GMT+05:30 W ConfirmKbsPinRepository: 	at org.thoughtcrime.securesms.lock.v2.ConfirmKbsPinRepository.lambda$setPin$0(ConfirmKbsPinRepository.java:29)
[5.1.9] [9671] 2021-01-15 10:37:04.097 GMT+05:30 W ConfirmKbsPinRepository: 	at org.thoughtcrime.securesms.lock.v2.-$$Lambda$ConfirmKbsPinRepository$lFMW5TONsUzJJUSPLox3_iutROw.run(Unknown Source:6)
[5.1.9] [9671] 2021-01-15 10:37:04.097 GMT+05:30 W ConfirmKbsPinRepository: 	at org.thoughtcrime.securesms.util.concurrent.SimpleTask.lambda$run$3(SimpleTask.java:54)
[5.1.9] [9671] 2021-01-15 10:37:04.097 GMT+05:30 W ConfirmKbsPinRepository: 	at org.thoughtcrime.securesms.util.concurrent.-$$Lambda$SimpleTask$rqL8ZWOBfkFEAc1QHVMzppc4b8Y.run(Unknown Source:4)
[5.1.9] [9671] 2021-01-15 10:37:04.097 GMT+05:30 W ConfirmKbsPinRepository: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[5.1.9] [9671] 2021-01-15 10:37:04.097 GMT+05:30 W ConfirmKbsPinRepository: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[5.1.9] [9671] 2021-01-15 10:37:04.097 GMT+05:30 W ConfirmKbsPinRepository: 	at java.lang.Thread.run(Thread.java:919)
[5.1.9] [9671] 2021-01-15 10:37:04.097 GMT+05:30 W ConfirmKbsPinRepository: Caused by: java.net.SocketTimeoutException: failed to connect to api.backup.signal.org/52.168.69.235 (port 443) from /192.168.111.58 (port 38646) after 30000ms
[5.1.9] [9671] 2021-01-15 10:37:04.097 GMT+05:30 W ConfirmKbsPinRepository: 	at libcore.io.IoBridge.connectErrno(IoBridge.java:191)

...

[5.1.9] [9671] 2021-01-15 10:37:04.097 GMT+05:30 W ConfirmKbsPinRepository: 	at okhttp3.RealCall.execute(RealCall.java:93)
[5.1.9] [9671] 2021-01-15 10:37:04.097 GMT+05:30 W ConfirmKbsPinRepository: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeRequest(PushServiceSocket.java:1570)
[5.1.9] [9671] 2021-01-15 10:37:04.097 GMT+05:30 W ConfirmKbsPinRepository: 	... 12 more
[5.1.9] [9671] 2021-01-15 10:37:04.156 GMT+05:30 I PinState: onPinCreateFailure()
[5.1.9] [main] 2021-01-15 10:37:08.544 GMT+05:30 I RegistrationUtil: Registration is not yet complete.
[5.1.9] [main] 2021-01-15 10:37:08.544 GMT+05:30 I RegistrationUtil: java.lang.Throwable
[5.1.9] [main] 2021-01-15 10:37:08.544 GMT+05:30 I RegistrationUtil: 	at org.thoughtcrime.securesms.registration.RegistrationUtil.maybeMarkRegistrationComplete(RegistrationUtil.java:38)
[5.1.9] [main] 2021-01-15 10:37:08.544 GMT+05:30 I RegistrationUtil: 	at org.thoughtcrime.securesms.lock.v2.ConfirmKbsPinFragment$2.onAnimationEnd(ConfirmKbsPinFragment.java:126)
[5.1.9] [main] 2021-01-15 10:37:08.544 GMT+05:30 I RegistrationUtil: 	at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
```

Was able to set PIN in next attempt and enable screen lock from privacy settings. Tested screen lock by locking the app from notification and unlocking via biometric. 


Now able to access app without losing any messages. Will be closing this issue now. Thanks @greyson-signal, everyone!

**Comment by c-rizz** [comment] 2021-01-15 12:57
Installed 5.1.9 from the store and it did not solve the problem. Installed 5.2.0 by joining the beta in the play store, also didn't fix the problem. I will reinstall the app, I hope received messages are just new contacts notifications.

Debug log:
https://debuglogs.org/9821b30922f550cfd51ad511ee88d3ff660b8337a55831d8a9adb28f48a81300

**Comment by iamvitali** [comment] 2021-01-15 14:16
Installed Signal yesterday for the first time, only thing I did was enter a new PIN because Signal asked me to, messaged some friends and enabled backup. And also enabled Beta version after installing just so I can be up to date with latest features.

But now it’s asking for a passphrase. My phone is protected with a fingerprint/pattern.
Signal is not asking for a fingerprint, so can’t unlock that way. Also not sure how to put my pattern into the passphrase???

My debug log https://debuglogs.org/088f29f4bc6bf0a21b2feaed8a4496e4453796f1dc46bdabafd70d678edc18c6
Says I’m version 5.1.8. I’m using Play Store Beta.

Updated with Play Store today to 5.2.0, still the same. A new debug log https://debuglogs.org/b7d5a7ce6b3a9e1017af20093e695f66d1f464cbd061011417e7cd09d8f76ab4

**Comment by c-rizz** [comment] 2021-01-15 14:31
> Installed 5.1.9 from the store and it did not solve the problem. Installed 5.2.0 by joining the beta in the play store, also didn't fix the problem. I will reinstall the app, I hope received messages are just new contacts notifications.
> 
> Debug log:
> https://debuglogs.org/9821b30922f550cfd51ad511ee88d3ff660b8337a55831d8a9adb28f48a81300

After reinstalling (actually I just cleared the storage from android settings) the app works correctly. After enabling "screen lock" in the settings it correctly asks for the fingerprint instead of whatever passphrase it required before.
Clearly I lost the messages I received before resetting, but now, with 5.2.0, it works.
To me, it looks like the problem was more in the passphrase activity than in anything else. It should always have just asked for the fingerprint.

**Comment by danilobellini** [comment] 2021-01-16 08:16
Is there an open issue? Or should I create a new one? Signal is still locked for me, asking a passphrase that doesn't exist (I tried to set the system one for screen locking, but that made no difference).

In my two debug dumps, it's clear that the issue happened between:

> 5.0.8 2021-01-13 12:43:54.929 BRT D PassphraseRequiredActivity: routeApplicationState(), state: 0
> [...]
> 5.0.9 2021-01-13 15:56:52.309 BRT D PassphraseRequiredActivity: routeApplicationState(), state: 2

That state 2 is `STATE_PROMPT_PASSPHRASE`, I assume it's telling the passphrase should be entered. That's also the first time I opened Signal after it got updated from 5.0.8 to 5.0.9, from Play Store (automatic). Should I downgrade it back to 5.0.8?

**Comment by deshant** [comment] 2021-01-16 11:46
@danilobellini version working for me is 5.1.9 and 5.0.8 has this issue so better stay on 5.1.9. Force close the app and restart it.
On 5.1.9 I was not asked for any passphrase, if it is still asking set biometric / PIN for the device. Force close and restart.

If that didn't work you can ping greyson-signal here and ask him to reopen this issue. If the debug logs suggest entirely different problem then you can submit new issue.

**Comment by danilobellini** [comment] 2021-01-17 18:07
I tried that way before you closed this issue. Nothing worked, and I'm clearly not the only one, so this issue should not had been closed. Some people in a situation like mine destroyed their history, but that's not an option (actually, that's the single main reason I'm avoiding WhatsApp: I want to have control over my own data, instead of encrypting it just to make myself unable to see my own data while a third party backup server have the data unencrypted). I'm locked out of Signal because of this passphrase screen lock which I just want to get rid of, and I'm not going to wipe my data, that defies the main reason I was trying Signal in the first place. @greyson-signal

**Comment by passaca** [comment] 2021-01-17 19:29
Yes, please open the issue again. It's happening here on a Samsung Galaxy S10 with the 5.1.9 version from the Play Store.

This is a very critical bug as it makes using the app impossible. And deleting the data is indeed not a solution.

**Comment by iamvitali** [comment] 2021-01-17 19:34
@passaca I'm on version 5.2.3 looking at my notifications saying I've got messages and still can't read them! It's been days now. Impossible to recommend Signal to anyone at this point. And if it'll take significant time to fix I'll just have to give up honestly, I can't be losing messages. 

https://debuglogs.org/eedc72433400559e0b564934e785f856f166ee2e0d29f40022c77384d2ee6a45

**Comment by deshant** [comment] 2021-01-18 05:32
Ok, opening it for @greyson-signal to have a second look, if he thinks it is fit he can close this and ask you guys to report a separate issue.

**Comment by polyrain** [comment] 2021-01-20 23:12
Same issue here, not sure what the solution is at this point

**Comment by ZeeArrEss** [comment] 2021-01-22 08:29
Count me among the list of people who haven't been able to get into signal for nearly two weeks now.

@greyson-signal what's going on here? No more replies here or on the SignalUsers forum (or on reddit), despite many, many having this problem.

**Comment by iamvitali** [comment] 2021-01-22 11:03
@greyson-signal just left us hanging.

@ZeeArrEss yep a week+ with no access to messages and ability to reply to them. If this happened with WhatsApp it would have been all over the news, YouTube etc.

**Comment by Grhu** [comment] 2021-01-24 11:04
So did you guys gave up and reinstalled the app and deleted your messeges (I have new messeges that I cannot read) or are you still waiting?

**Comment by iamvitali** [comment] 2021-01-24 12:39
> So did you guys gave up and reinstalled the app and deleted your messeges (I have new messeges that I cannot read) or are you still waiting?

I'm just using WhatsApp for now. 
Working app > privacy

**Comment by polyrain** [comment] 2021-01-28 13:15
latest update fixed this for me

**Comment by danilobellini** [comment] 2021-01-28 16:09
> latest update fixed this for me

Same here!

**Comment by iamvitali** [comment] 2021-01-29 10:11
> latest update fixed this for me

Finally!!!
Updated to 5.3.8 (I'm on Beta channel) and it let me in!

**Comment by ZeeArrEss** [comment] 2021-01-31 05:24
Same here. 5.3.9

**Comment by chrylis** [comment] 2021-02-02 03:48
Just updated to 5.3.10 and still having the same problem.

**Comment by chrylis** [comment] 2021-02-21 01:00
@greyson-signal Still locked out as of 5.4.7.

**Comment by chrylis** [comment] 2021-04-04 19:07
5.6.2. What a clown show.

**Comment by lewiji** [comment] 2021-04-04 19:14
@chrylis have you pursued other forms of support on this issue? It seems to be fixed in most cases since 2 months or more so yours must be quite unique and may need a second pair of eyes.

**Comment by cody-signal** [comment] 2021-04-05 14:13
> 5.6.2. What a clown show.

Got a debug logs link so this clown can have a chance at helping you? There's an overflow menu item to submit them in the top that'll give you a link that you can post here. Thanks! 🤡

**Comment by aquarichy** [comment] 2022-01-28 07:49
I see it's marked as wontfix by a bot too days ago. Unfortunately for me, I just upgrade Signal to 5.29.7 and had this happen.  Upon restarting, I was prompted for a non-existent passphrase without any alternative options. I tried using my phone's PIN, tried interacting with the fingerprint reader randomly, tried the PIN for Signal (that it tests me on every month or so) and even tried my backup passphrase, and nothing work.  

Thankfully, I do regular backups, so I've only lost a few hours of messages. 

Upon restoring from a backup, though, I now have a persistent option that I can't dismiss in my notification bar, about Signal being unlocked and giving me an option to lock it.  If I do that, I am still not prompted to set a passphrase, but just locked out, and I basically have to reinstall and restore from backup again.

**Comment by haffenloher** [comment] 2022-02-11 10:41
Another user just reported this over at the forums. Their post includes a debug log:

https://community.signalusers.org/t/locked-out-of-signal-due-to-passphrase-not-being-accepted/41694

**Comment by der-dom** [comment] 2022-02-11 14:47
Thank you @haffenloher - that was me. Indeed it seems I have the exact same issue (Original post [here](https://community.signalusers.org/t/locked-out-of-signal-due-to-passphrase-not-being-accepted/41694)). 

For me this happend after migrating my Signal account and messages of 6+ years to a new phone. I am not at all inclined just to reset Signal, as this would mean losing all my messages. On the old phone the internal storage was to low to make backups on the new one I could not do it before I got locked out. Any help would be greatly appreciated. @cody-signal or @greyson-signal? Thank you so much!

**Comment by greyson-signal** [comment] 2022-02-14 15:15
The most recent report seems to be that they had an old legacy password (a feature that was deprecated > 4 yrs ago) and it looks like we may not handle it well in certain backup restore/transfer situations. @der-dom I've reached out to you in the forums to help you resolve the issue.

**Comment by johanw666** [comment] 2022-03-17 19:43
Reviving this old thread: I assume the root problem is that TextsecurePreferences.isPasswordDisabled() gives a default value of false. Set the default to true to fix this.

**Comment by Apfelwurm** [comment] 2022-04-07 08:43
I have reinstalled my phone a few days ago and installed signal again without importing a backup, entered the registration pin, which was successful, but today i encounter the described issue here.

I have not set any pin on signal (even though i think i used the old legacy password sometime in the past) and now i'm not able to access signal anymore.
Rebooting, killing the app or clearing cache does not change the behaviour.

I also tried to set a fingerprint to test if this would enable me to ulock it, but this does also change nothing.

Here is the debuglog: https://debuglogs.org/android/5.34.5/bf7b6bb4a989f1ce3758243cf64ba8b82a830539288b8c0d5759ec4f48462006 where also the "Password Disabled    : false" entry appears that @greyson-signal mentioned in the forums.

Luckily my connected desktop app still works like expected, so i can currently use it nevertheless as long as i use my pc.
Is there any way to fix this with preventing this to happen again in the future? :) 

Thanks!

**Comment by Apfelwurm** [comment] 2022-04-16 00:19
Any chance to get help on this one? I use signal as my main messenger and since 9 days i can only access it from my main pc, which means as soon as i leave my flat i'm not able to communicate or react to anything :D 
Thanks!

**Comment by greyson-signal** [comment] 2022-04-16 20:21
Something about your log looks... not right? You claim to have done a fresh install, but you "Days installed" count is Days 4844, which would only be saved if you did a backup restore. You're also going through some funny initialization steps that wouldn't happen in a fresh install. I also see that your APK isn't signed by us -- so I'm assuming you've built the app yourself? Have you modified anything?

If you're making your own build, you can get out of this problem by changing [this](https://github.com/signalapp/Signal-Android/blob/31e4db218637f9a40aca1bc4dbc6dc748665c798/app/src/main/java/org/thoughtcrime/securesms/util/TextSecurePreferences.java#L652) to always return `true`.

**Comment by Apfelwurm** [comment] 2022-04-16 20:50
Thanks for your answer!
Well, thats really strange, i honestly have no explanation for that. This time i had no backup because i screwed up hard, i only used the registration pin while setting up signal. 
I should have mentioned that i build my custom Android rom with signal built in on a weekly base.I am using the apk that is served here https://updates.signal.org/android/latest.json and it seems it gets automatically resigned when it gets built into the rom, but i did no modifications other than that.
I mean, i can look into building it myself so that i can modify that function, if this is not a problem that is somehow related to my number/account. 
But i'm now really wondering even more, how it got so messed up in the first place.
Is it somehow possible that anything in the installation process without the backup and with the registration pin leads to the messy database?

**Comment by Apfelwurm** [comment] 2022-04-17 01:35
Okay, i have built it into my automated build process using the reproducable build container and patched the line you suggested and i'm back in finnaly. Thank you very very much :)  I guess then i have to build it as long as this will not be removed / changed.

**Comment by greyson-signal** [comment] 2022-04-17 14:10
> I assume the root problem is that TextSecurePreferences.isPasswordDisabled() gives a default value of false. Set the default to true to fix this.

I was avoiding doing it because I don't know what the access pattern was of that variable 4.5+ years ago, but I think it's safe to assume that setting a password manually sets `passwordDisabled=false`, which means that it should be safe to change the default to true. Also we've been turning it off on first installs and backup restores for years now.

@Apfelwurm I'll make this change for 5.36, so you can try not-building at that point :+1:

**Comment by johanw666** [comment] 2022-04-17 14:55
I have re-activated password lock in my fork, and it runs perfectly fine with a default of true there. Settijg aa password indeed changes the value. I did comment out your manually forcing the password off at startup or Signal didn't run at all anymore.

**Closed** 2022-04-20 19:34 UTC
