### ISSUE TITLE
FullBackupImporter: Bad MAC for attachment ! Can't restore it.

### ISSUE THREAD

**Issue by bobnonsum** [signalapp/Signal-Android#9169] opened 2019-11-08 11:11 UTC
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic
----------------------------------------

### Bug description
When importing a backup file from the old smartphone to the new one, the app crashes in the middle of it. The log information states:
"2019-11-08 11:44:08.410 CET W FullBackupImporter: Bad MAC for attachment 1560553295199! Can't restore it."

The backup file was successfully tested using the signal-back program.

### Steps to reproduce
- Copy the backup file to the Signal/Backups folder on the new device
- Install Signal app from Play Store
- Open Signal
- Tap continue
- Tap Restore backup
- Type in the passphrase

**Actual result:** 
The program starts to import the messages, but around approx. the message 4600 the app crashes.

**Expected result:** 
All messages successfully imported, or if not possible at least a user friendly error message.

### Device info

**Device:** asus ASUS_I01WD (EU_I01WD)
**Android version:** 9 (16.1220.1909.194-0, PPR2.181005.003.WW_Phone-16.1220.1909.194-0)
**Signal version:** 4.49.17 (5642)

### Link to debug log
https://debuglogs.org/334ad907afcb84483a2f2d9126f588e3bec1afc085568a7adf3003ae76530886

**Comment by alan-signal** [comment] 2019-11-08 11:47
Related to #9154 

In that these are both caused by misreading a frame size.

**Comment by greyson-signal** [comment] 2019-11-08 23:39
Closing as duplicate of #9154

**Closed by greyson-signal** 2019-11-08 23:39 UTC
