### ISSUE TITLE
Accessibility Text Size Not Respected with Message Replies

### ISSUE THREAD

**Issue by bitmold** [signalapp/Signal-Android#10188] opened 2020-11-12 21:02 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
It seems that the text size for message replies is always "normal". If you change the text size to be either really small or big the text size in the replies always stays the "normal" size.

I've noticed too that if you reply to something that's not a text message, the italicized text (such as "*Photo*") respects the text size that the user set; this bug only pertains to message replies to text messages.

### Steps to reproduce
- Reply to a message
- Change the text size to something that's not normal
- Return to your conversation and see that the text for a message itself is the size that you set but not the replied to text.

**Actual result:** inconsistent text sizes
**Expected result:** all text sizes should respect the setting that the user set 

### Screenshots
![big](https://user-images.githubusercontent.com/22125581/98995926-15bf0500-2500-11eb-833a-fcf2b596cbc3.jpeg)
![small](https://user-images.githubusercontent.com/22125581/98995928-15bf0500-2500-11eb-85a3-16c06dad3c33.jpeg)
These are the smallest and largest text sizes supported within the app. I only screenshotted one message, but if you were to look at an entire conversation it becomes disorienting (and potentially inaccessible) to see two different text sizes.

### Device info
**Signal version:** 4.76.3

**Comment by mullinger** [comment] 2020-11-13 16:07
Reproduced with commit e294a895e84c2d24f2c6d9e9627debbd4640a260 (HEAD -> master, tag: v4.77.1, origin/master, origin/HEAD) on a Fairphone 3 (playStagingDebug) with a "self message" and highest text size

![image](https://user-images.githubusercontent.com/645185/99093152-656e0100-25d2-11eb-8af1-02bf5c7f5a83.png)

**Comment by mullinger** [comment] 2020-11-13 16:53
The textsize is configurable with preference key "MESSAGE_BODY_TEXT_SIZE_PREF".
For regular chat items the text size will be adjusted in ConversationItem#setBodyText Line 612
`bodyText.setTextSize(TypedValue.COMPLEX_UNIT_SP, TextSecurePreferences.getMessageBodyTextSize(context));`

The quotes seem to live in QuoteItem.
Updating QuoteItem#setQuoteText to include

```
if (!TextUtils.isEmpty(body) || !attachments.containsMediaSlide()) {
      bodyView.setVisibility(VISIBLE);
      bodyView.setText(body == null ? "" : body);
      
      // The following line will also respect the configured text size for quotes
      bodyView.setTextSize(TypedValue.COMPLEX_UNIT_SP, TextSecurePreferences.getMessageBodyTextSize(getContext()));
      mediaDescriptionText.setVisibility(GONE);
      return;
    }
```

Screenshot including the fix:
![image](https://user-images.githubusercontent.com/645185/99098209-fa73f880-25d8-11eb-8058-fa0e92c698c9.png)


I will supply a pull request with the fix later

**Comment by cody-signal** [comment] 2020-11-13 16:59
We cache views to improve rendering performance, we were not invalidating said cache when the system font scaling value changed. An upcoming release, most likely 4.77.2 will address it.

**Comment by mullinger** [comment] 2020-11-13 17:11
> We cache views to improve rendering performance, we were not invalidating said cache when the system font scaling value changed. An upcoming release, most likely 4.77.2 will address it.

As I understand it the current issue is more about inconsistent scaling between quotes and items when setting the text size inside signals own preferences (pref_message_body_text_size).
From my understanding this is unrelated to system-wide font scaling.

**Comment by cody-signal** [comment] 2020-11-13 21:45
@mullinger Okay, feel free to submit a PR!

**Comment by mullinger** [comment] 2020-11-14 07:24
@cody-signal Will do!

**Comment by JitinDhillon** [comment] 2021-01-10 22:48
Hi guys, also facing this issue. I see @mullinger has fixed the code but I don't see a pull request for it, I hope it hasn't been forgotten.

**Comment by christophgrander** [comment] 2021-01-13 20:11
can confirm this issue on Signal 5.0.10

**Comment by mullinger** [comment] 2021-01-13 21:03
The pull request can be found here : https://github.com/signalapp/Signal-Android/pull/10197

It seems the PR is somehow not linked to the issue. I'm new to contributing, so I'm not sure whats missing here.

In the meantime there were some changes to the code on master.
I updated the branch/PR and verified again that the issue is fixed in the branch.

@cody-signal Can you take care of the PR, or tell me what is missing to get the issue fixed? Thank you

**Closed** 2021-06-08 21:02 UTC
