### ISSUE TITLE
Signal does not respect DND

### ISSUE THREAD

**Issue by praetp** [signalapp/Signal-Android#8530] opened 2019-01-14 20:00 UTC
### Bug description
Signal does not respect DND mode.
At night or at work, I put Signal in DND mode to not be disturbed. However, my phone still makes sound and vibrates when I receive messages when I am DND mode which is highly annoying.

### Steps to reproduce
- Put phone in DND
- Receive message
- Phone makes sound/vibrates (and should not)

**Device:** Xiaomi Pocophone F1
**Android version:** 9.1.0
**Signal version:** 4.31.7

**Comment by 2-4601** [comment] 2019-01-19 14:15
I cannot reproduce this on Android 9. Tested calls and messages.

> **Android version:** 9.1.0

What is Android 9.1.0? I thought 9.0.0 is the latest version of Android Pie?

Does this also occur with other apps or just Signal?

Related #8257.

**Comment by chintchary** [comment] 2019-04-16 05:07
I've had this problem on Android 9 for about a week. However the notifications don't come through immediately, they're delayed for 4-5 hours. This is, of course, much worse.

**Comment by mdentremont** [comment] 2019-04-18 14:12
This is something I've been noticing recently as well - it's only occurring for Signal, I'm on the latest build from Google Play, on a Pixel 2 with the March build (Android 9)

**Comment by loopingzzz** [comment] 2019-11-14 09:27
Same here on Xiaomi 9T Pro Android 9. Vibrate while dnd and vibration set to off.

**Comment by thesmart1** [comment] 2019-11-27 06:53
Same issue here. Super annoying.

**Comment by KoltesDigital** [comment] 2019-12-26 23:24
This bug is happening on my Redmi Note 7, Android 9. This does not happen with any other app.

**Comment by igalic** [comment] 2020-10-21 14:51
i have a related, but opposite problem. with the following DND settings, signal does not ring:
![Screenshot_20201021-161326](https://user-images.githubusercontent.com/497249/96737166-a4d37400-13bd-11eb-9238-29582999092f.jpg)

**Comment by vertigo220** [comment] 2020-12-16 20:30
@igalic - I could be wrong, but it's probably because Signal, even for calls, is considered by the OS to be a messaging app. "Calls" are probably limited to the context of the default phone app, i.e. normal voice calls. To allow Signal to ring, you probably need to change the SMS... setting.

Personally, due to the combined issues with Signal and with Android's DND feature, which is often on when it shouldn't be, I used Automagic to manage all DND and notification functions, so Signal never makes any sound and Automagic analyzes notifications to determine whether or not to, based on whether DND (as managed by Automagic) is on and who the call or text is from and its content, in the case of a text. One benefit to this, aside from resolving the above issues, is that it allows me to silence spam texts (as well as autoreply "STOP"), something Signal has no option for, since you can mute individual conversations, but that doesn't help for spam, where you need to be able to mute all but selected ones. Just one of many instances of missing critical features that make this "messaging" app barely functional at its main job.

**Comment by igalic** [comment] 2020-12-17 13:04
> "Calls" are probably limited to the context of the default phone app, i.e. normal voice calls. To allow Signal to ring, you probably need to change the SMS... setting.

this same setting works for WhatsApp.

**Comment by vertigo220** [comment] 2020-12-18 17:18
And maybe there's something different between them, e.g. maybe WhatsApp is set to be seen as a calling app and Signal as a messaging app. Did you even try it? If you did, you could then report back some useful info, such as it worked, so Signal *isn't* failing to respect DND, but rather needs to be recognized differently in order for DND to work properly with it, or it didn't work, in which case the issue really is that it's not respecting DND. Two completely different problems.

**Closed** 2022-02-03 14:26 UTC
Labels: wontfix
