### ISSUE TITLE
Incorrect date handling for image files. ('Last Modified' is always set to 1.1.1970 1:00)

### ISSUE THREAD

**Issue by abzicht** [signalapp/Signal-Android#10140] opened 2020-10-26 14:36 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Image files saved with the dedicated functionality are saved with an incorrect date tag for 'Last modified'. The date found in the metadata of image files is 1.1.1970 01:00. This indicates that, with a recent update, UNIX timestamp handling became faulty.

### Steps to reproduce
- Open Signal
- Enter a chat with images
- Store any image using the dedicated functionality
- Open any file browser or gallery and locate the image file
- Check the metadata, search for the date of 'Last modified'.

**Actual result:** For every image, the metadata field 'Last modified' is set to 1.1.1970 1:00.
**Expected result:** The metadata field 'Last modified' should be set to when the image was stored.

### Device info

**Device:** ZTE V10
**Android version:** 9, Kernel: 4.4.146+
**Signal version:** 4.74.3

**Comment by Genis-Sage** [comment] 2020-10-28 08:04
hey @abzicht 
I could not reproduce this behaviour on my Android 10 Nokia device

but just from the title, it seems to be fixed here: [Fix SMS, bad MODIFIED timestamp, and API19 beta crash. ](https://github.com/signalapp/Signal-Android/commit/373d622535280a8b3e9d7251c1574ad877f18e29)

perhaps you can try out the beta version, or wait, until 4.75.x productive version is released

**Comment by greyson-signal** [comment] 2020-10-29 13:48
Yeah, I believe this is fixed in 373d622535280a8b3e9d7251c1574ad877f18e29.

**Closed by greyson-signal** 2020-10-29 13:48 UTC
