### ISSUE TITLE
Missing incoming messages

### ISSUE THREAD

**Issue by LNow** [signalapp/Signal-Android#5253] opened 2016-02-17 18:00 UTC
I'm experiencing missing incoming standard SMS (from non signal user).
What I've found that it happens only when I accidentally turn off app. It doesn't matter if app is set as default messaging app or no. If I turn it of I'm loosing all incoming messages.

Is there any way to avoid that and recover those missing messages?

**Comment by moxie0** [comment] 2016-02-17 18:42
How does one "turn an app off?"

**Comment by LNow** [comment] 2016-02-17 18:55
Maybe not turn off but close. You know, from task manager.
Close, turn off - this is the same thing, right?

So when app is closed (turned off) and set as default messaging app all incoming messages are sucked by "black hole". I don't get any notification. And there is no way to read those missed messages, I just don't see them.

**Comment by moxie0** [comment] 2016-02-17 19:07
I still don't really know what you mean, but if you "force close" an app from settings, it will not be revived by external events (incoming SMS, incoming push, etc...)

**Comment by LNow** [comment] 2016-02-17 19:23
OK, I've got your point. I have no idea how stock app receives all events even if I'll close it in the same way. But let's leave it, as it is just a minor issue - I can live without notification if I turn off an app.

The main problem is that all messages, that someone have sent to me while Signal is off are gone. Senders sees them as delivered but I have no access to them. Where can I find those messages if they are not accessible trough Signal and stock app?

**Comment by moxie0** [comment] 2016-02-17 19:25
I still don't know what you're doing, but if you click the "force close" button in Settings -> Applications -> Signal, I believe all subsequent incoming SMS messages will be lost.  You can submit a debug log if you'd like.

**Comment by RiseT** [comment] 2016-02-17 19:29
@LNow Do you mean "closing" by using the Android's navigation bar (soft keys)?

**Comment by LNow** [comment] 2016-02-17 19:41
@RiseT closing from builtin task manager. Like this one ![screenshot_2015-10-22-11-15-23](https://cloud.githubusercontent.com/assets/829210/13122230/4452393a-d5b6-11e5-8ea6-548f7c57fb33.png)

**Comment by CarstenLarsen** [comment] 2016-02-19 09:48
+1 for this issue.

When I use Signal for SMS messages, some messages will disappear. Not all. I have signed up for a SMS service which sends me 4 messages a day and when using Signal some of these messages are never delivered. However if I use Google Messenger as SMS client I receive all incoming messages.

I'm on Galaxy S6 Edge.

**Comment by moxie0** [comment] 2016-02-19 18:39
Without reproducible steps or a debug log for the missing message, "it doesn't work" isn't much to go on.  Please see: https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md

**Comment by CarstenLarsen** [comment] 2016-02-27 13:37
I have updated to Android 6.0.1 and everything works like a charm now. Thanks a lot for a great app and your hard work.

**Comment by messwitit5** [comment] 2016-03-10 21:20
I have the exact same issue, randomly missing incoming SMS, that I'm only aware of because the person thinks I'm ignoring them. 

I've included the debug log: https://gist.github.com/messwitit5/a472cd8b20d37d6494ec

If there's anything I can do to help get this issue resolved, I would love to help. Device is Galaxy S6 on 5.1.1

**Comment by simonft** [comment] 2016-03-11 15:14
I'm seeing the same thing, on the same phone as @messwitit5. If you need another debug log, one is here:
https://gist.github.com/anonymous/d45b81d33b187f9c2287
It was taken shortly after missing a few messages.

I've switched to using the default messenger and it doesn't seem to be dropping messages. Please tell me if there's anything else you'd like me to try.

**Comment by HaMF** [comment] 2016-03-19 11:51
Same here. Samsung SM-A300FU (a3ultexx), Signal 3.14.2 I tend to realize this pretty late usually so the debug log is quite cluttered. On another related issue you referred to a branch which generates more debug output. Is this still up to date would a debug log there help, moxie0?

**Comment by rebeccaroisin** [comment] 2016-03-19 23:18
I have a similar issue of messages getting dropped, also using Samsung S6 (SM-G920F) running Android 5.1.1. Signal version is 3.14.2

There is a debug log here from < 5 min after a dropped message. 
https://gist.github.com/anonymous/91021c5b6543654a4a49

Specifically, I expected to receive an automated message containing a Netflix 2-factor authentication code. The first message never arrived, but when I triggered the "resend" option a message arrived immediately. Hopefully some of this is captured.

This might be a reasonable way to try and reproduce the bug -- I've had dropped authentication codes before.

**Comment by mickenordin** [comment] 2016-05-03 17:46
I have this issue too on Samsung Galaxy Note 4 with Android 5.1.1 and Signal 3.15.2

**Comment by wischweh** [comment] 2016-07-11 07:56
I have a similar Issue using a Dual-SIM phone (ASUS Zenphone 2) with Android 5.0. I am also using Snowball and have ASUS SMS App installed. Snowball is able to detect the Message, but if i click on it i am forwarded to Signal, but the new Message is not shown. If i switch to the original SMS App i can not find it there either. For me this is a no go and i had to uninstall Signal.

**Comment by tomaszmadeyski** [comment] 2016-07-31 20:35
Hi, I'm having the same issue, Samsung S5, Android 6.0.1  Here's debug info:
https://gist.github.com/anonymous/b78b86477e518f61cdbfd8412bb58073

**Comment by paalbra** [comment] 2016-09-14 10:23
Same issue. Some messages are just lost. Samsung Galaxy S4, Android 5.0.1, Signal 3.18.3.

I don't have any debug info since I've never experienced the issue when performing a test. Hours/days have passed when I realize that I'm missing a message.

**Comment by GLLM** [comment] 2016-10-13 10:29
Same issue here on never received SMS :
* Samsung Galaxy  GT-I9505 on f/w I9505XXUHPF4
* Android 5.0.1
* Signal 3.20.4

I cannot reproduce consistently the issue ... but one of my contacts' SMS are systematically lost.
If I switch the default SMS app back to my phone'e default SMS app : I do receive the new one he would send (the old non-received one remain lost).

Hoping a reproducible test case will appear at some point !!

Thanks for the amazing app anyway :)

**Comment by GitHorst** [comment] 2017-01-12 00:35
I though I had that issue too, then I realized my phone took a few seconds to retrieve the proper time from the network after power-up. In the meantime the SMS that was sent while the phone was off, was received and listed at the very top of the conversation (since it was 1970 for my phone).
@moxie0 if 1970 is the standard year for such cases, maybe add the SMS to the conversion according to the time it was sent?

**Comment by kbless551** [comment] 2017-02-10 17:11
It just happened to me again, sometimes I tap a message to read it, and it slides off the edge of the screen and disappears.  About ready to uninstall the app. This last one was very important to me

**Comment by paalbra** [comment] 2017-02-10 17:55
May I suggest that you all post phone, Android version and Signal version when posting?

If I haven't missed anyone, this seem to have happened on the following phones:
* Samsung Galaxy A3
* Samsung Galaxy Note 4
* Samsung Galaxy S4
* Samsung Galaxy S5
* Samsung Galaxy S6
* Samsung Galaxy S6 Edge
* ASUS Zenphone 2

The trend is quite clear. This might be a Samsung (Galaxy) issue.

**Comment by kbless551** [comment] 2017-02-10 22:36
I am using a ZTE Warp Elite. Android v 5.1  and the most current version of signal because when I looked in play store for an update, all it gave was the was no Update button, just uninstall and Open....

**Comment by kylebarbour** [comment] 2017-02-10 22:44
Unclear to me if this is related to #4851 or not, so I apologize for crossposting, but wanted to make sure my report goes to the right people.

+1, also having occasionally dropped SMSes. Seems random - it's not happening with every contact or in every message. Also happens with group messages. The only way I know I didn't get the messages is that people call me later asking why I didn't respond. Doesn't ever happen with Signal messages, just SMS. [Here's the debug log](https://gist.github.com/anonymous/3db5bc46e2025e67e317f28df953e4b3).

My Signal version is 3.28.4, I'm on Android 6.0.1 on a Motorola Droid Turbo 2. I don't believe that I have any other SMS app that could be capturing the SMSes; I never actually even set up the native Messaging app.

**Comment by asmith999** [comment] 2017-02-10 23:00
Still not resolved I see.. I dropped Signal some time back.. not knowing if your messages are being delivered is sort of a deal breaker for a messaging ap.

**Comment by kbless551** [comment] 2017-02-10 23:14
Only occasionally with me too. I will see the msg in the list and when I tap to open it, it slide off to the side to who knows where?

**Comment by liliakai** [comment] 2017-02-11 00:23
@kbless551 This issue is about messages that do not arrive at all. (Rather than ones that arrive and then go missing).

>  I will see the msg in the list and when I tap to open it, it slide off to the side to who knows where?

Sounds like you might be unintentionally archiving the conversation. Try searching for that contact or group name to find it again, then unarchive it from the conversation menu. If you have further questions, please open a separate issue or simply contact support@whispersystems.org, so as not to clog this thread with unrelated discussion. Thanks!

**Comment by kbless551** [comment] 2017-02-11 01:52
Either way, I installed a different messenger today, it was the last straw

**Comment by ajft** [comment] 2017-02-15 02:55
Adding myself to the list of affected customers.  I've an S6, Telstra Australia Android 6.0.1, and if I set Signal as my default message handler I end up never receiving some of the plain SMS messages sent (and usually it ends up being ones from my family that I _need_ to receive).  With the default Samsung msg app I've never knowingly missed an SMS.

**Comment by moxie0** [comment] 2017-02-16 07:19
Question for those affected: do you often/ever swipe Signal out of the "recents" app list?

**Comment by ajft** [comment] 2017-02-16 07:30
@moxie0 to the best of my knowledge I've never swiped Signal off recents

**Comment by paalbra** [comment] 2017-02-16 08:08
@moxie0 No. I can remember ever doing that.

**Comment by GLLM** [comment] 2017-02-17 08:46
Not that I remember.

Ever since I got the problem, I removed Signal as being the default SMS app ... no problem anymore.
Oh, and I also changed phone, and didn't try again to use Signal for non-Signal SMS (i.e. other than encrypted msgs)

Hope this can help...

**Comment by moxie0** [comment] 2017-02-17 22:07
Thanks, I'd also be curious to know if everyone here has enabled "local encryption" (passphrase), or if that's not a factor either?

**Comment by ajft** [comment] 2017-02-19 23:02
@moxie0 passphrase is not enabled for me, AFAICT it was/is a default installation on the S6

**Comment by tomaszmadeyski** [comment] 2017-02-20 07:53
@moxie0 it is/was not enabled for me too

**Comment by GLLM** [comment] 2017-02-21 18:16
Passphrase was NOT enable for me too.

**Comment by paulhart** [comment] 2017-02-23 02:21
Same issue here; Asus Zenfone 2 ZE551ML, Android 6.0.1, latest firmware build from Asus. Built-in messaging app has no issues, Signal silently appears to drop messages. Not actively closing the app.

**Comment by moxie0** [comment] 2017-02-23 17:56
@paulhart If you can reproduce it, a debug log captured immediately after a dropped SMS would be helpful

**Comment by ahal** [comment] 2017-03-02 17:02
Also hitting this on a Zenfone 2. Only know because people started wondering why I wasn't responding. No swiping from notifications and no local encryption. Unfortunately had to uninstall, so can't get a debug log anymore.

**Comment by haywardgb** [comment] 2017-03-18 17:37
Same issue with lost texts.  
Galaxy S7 , Android V5.0.1
Encrypted Device *Full Disk*

I cannot put my trust in this app right now. 
It nearly cost me dearly from the first missing text, I'll have to stick with Whatsapp!

**Comment by moxie0** [comment] 2017-03-18 18:06
@haywardgb this issue only applies to SMS, you can still use signal without making it your default SMS/MMS app

**Comment by balajiramanathan** [comment] 2017-03-26 14:29
I have an ASUS Zenfone 2, and I receive only messages that are sent twice (only the second one reaches me, the first one never comes to me).  I have stopped using Signal as my default SMS app because of this issue.  I have swiped both the regular messaging app as well as Signal off my recents multiple times (I try to keep the number of running apps to a minimum on my phone).

**Comment by moxie0** [comment] 2017-03-26 16:59
@balajiramanathan If you can easily reproduce this, it'd be helpful if you reproduced the behavior and posted a debug log.

**Comment by balajiramanathan** [comment] 2017-03-26 22:21
Well, the latest update seems to have fixed it.  I re-enabled signal as my default sms app (I went back to the regular messaging app on my phone for the past week or so) and had people text me as a test, and I received all their texts on the first attempt without any problem.  So far, so good.

**Comment by balajiramanathan** [comment] 2017-03-26 23:21
I spoke too soon.  I was sent an SMS at 16:20 today, and I never received it.  This is the debug log from before I got that message:
https://gist.github.com/f475ea5e2ba1bfbfee7f602d61dc23f3

Then, the person resent the message, and I received it immediately.  Here is the debug log from after I got the message:
https://gist.github.com/92f84af18d26765e3700c891c979be35

**Comment by moxie0** [comment] 2017-03-27 01:56
@balajiramanathan Strangely, *neither* of those logs show you receiving an SMS message in Signal.

**Comment by balajiramanathan** [comment] 2017-03-27 13:36
Well, that **is** strange.  So, where does that leave us in terms of being able to get to the bottom of this?

One more datapoint to consider:  it looks like short text messages do get delivered right away.  The message for which I submitted the logs above was longer than 140 characters.  Don't know if it is significant or even relevant, but thought I would throw it out there anyways.

**Comment by haywardgb** [comment] 2017-03-27 15:48
@balajiramanathan the SMS integration doesn't work for me either, BUT... after turning the SMS integration off, Signal now works 100% and imho it's better this way. You're only going to get the full benefits of the app if both you and the recipient are using it anyway ;)

**Comment by moxie0** [comment] 2017-03-27 16:28
@balajiramanathan Both of those logs are very short, which could be a clue. As if perhaps Signal is constantly being killed by your ROM or something.

Would you be capable of installing adb on your computer and getting logs through 'adb logcat'?

**Comment by balajiramanathan** [comment] 2017-03-27 23:21
I do have android studio on my computer (it is probably not the latest version though because I stopped doing android development a couple of years back).  And my phone is set up with developer options turned on.  But I am not familiar with 'adb logcat', so if you can walk me through how to do it, I would be happy to help out.

**Comment by kylebarbour** [comment] 2017-03-28 03:47
Confirming also that Signal is still dropping messages for me; I was able to clearly demonstrate this tonigh. Interestingly I am able to receive MMS messages with multiple recipients from the sender but no SMS messages via Signal.

System info:
- Signal 4.1.0
- Android 7.0
- Droid Turbo 2

I've attached my debug log.
[debug.txt](https://github.com/WhisperSystems/Signal-Android/files/874432/debug.txt)

**Comment by BastiTee** [comment] 2017-03-29 18:31
Hi there, 

I switched to Signal a couple of months ago and I have two contacts in my list (out of 30+) who regularly report (in contrast to all the others with whom I don't have any messaging issues) that they didn't receive my messages or that messages are delayed and sometimes I don't get their messages either. The interesting thing: Both of them use a Galaxy S6. 

Person 1:
Galaxy S6 (Germany) 
Android 6.0.1 
Build MMB29K.G920FXXU5DQA7
Baseband G920FXXU5DPL3

Person 2: See above... 8O 

Unfortunately I don't have any other spec or log available at the moment, but if I have to guess, I'd say either it will be reproducable on any other phone with the above spec or this is quite a coincidence.

**Comment by larkaen** [comment] 2017-06-07 16:22
Any update?

I use signal on a Galaxy S6 for SMS.  I've had two friends on iPhones used signal, then stopped.  They both can still send me messages, but no longer receive mine.  On my end it appears as if I have successfully sent encrypted messages.

Android 6.0.1, krnl 3.10.61-76010624
Signal 4.1.6

**Comment by haffenloher** [comment] 2017-06-07 20:08
@larkaen that's a separate problem (this issue is about incoming SMS being dropped, not Signal messages). Your friends can unregister here: https://signal.org/signal/unregister/
Also, if you have further questions, support@whispersystems.org can help you.

**Comment by badwolf7** [comment] 2017-08-04 03:06
+1 ... I thought I loved this app but now I have found that I've been missing messages, if only because people though I was purposefully ignoring them. Thanks for that BTW. Would love to see this bug resolved.

**Comment by moxie0** [comment] 2017-08-04 16:05
@badwolf7 So would I! I have never missed an SMS on my device or any of my test devices, so I'm having a hard time figuring out what's happening. The best way to help, if possible, would be to figure out how to reproduce this and get a debug log for the period that it happens.

**Comment by sylvanax** [comment] 2017-08-08 21:00
I've just encountered the same issue with missing (never having arrived) text messages.
I'm using Asus Zenfone Zoom S.
@moxie0 my wild guess would be that my Asus device (and probably some other affected devices) is doing some heavy battery life optimizations, and so it is unloading Signal from the memory now and then, effectively preventing the messages from arriving.
One way to verify it would be adding an option preventing that system behavior. Xabber has something like this, I think it's called "Prevent sleep mode". Since I've enabled it, I'm getting system messages about Xabber eating up memory, but it works in the background seamlessly now.
Why not try to explore this possibility.

**Comment by jeremymasters** [comment] 2017-08-08 22:34
@sylvanax I think the issue here is that people are just never getting the messages.  If Signal goes to sleep somehow, it would still receive the message when waking up, which is a different issue.

**Comment by sylvanax** [comment] 2017-08-08 22:49
@jeremymasters Indeed, it is a different issue, which, by the way, I noticed with Signal used on my previous device - Sony Xperia T3 with Kitkat. And while that Xperia issue was just a mere nuisance (I was getting the text messages after all, even if delayed by hours), losing text messages permanently is a deal breaker, particularly when I'm using these for 2FA.
I'm not saying it's related. It just *might* be, particularly *if* the battery management system behavior is aggressive and/or bugged and, instead of putting the 'battery-offending' apps to sleep, it just unconditionally terminates them.
What I have noticed: when I perform an action requiring SMS authentication while my device sits idle, the *first* authentication SMS token never reaches Signal. Then, the second one arrives when I repeat the action with Signal in the foreground. Hence my suspicion. 
I have yet to try to perform some action when I put Signal to foreground first and try to authenticate later, to make some conclusions, but that would have to wait a few days (I'm not expecting to have to authenticate any time soon).

**Comment by jeremymasters** [comment] 2017-08-08 23:16
@sylvanax If you haven't already, I'd write up what you described here separately.

**Comment by moxie0** [comment] 2017-08-10 02:54
@sylvanax If you can reproduce it that reliably, please capture a debug log and post it here.

**Comment by korya** [comment] 2017-10-23 19:57
Same issue here. I have Samsung Galaxy S7 running Android 7.0. When a phone is locked (display show a lock screen) for couple minutes, I do not receive any SMS message. The problem is that when I "unlock" the phone I expect to see those message that were sent while it was "sleeping", but I don't. If I shutdown the phone completely and turn it on again couple minutes later, all the messages sent in that period of time are correctly received.

I believe it is related to the fact that a phone enters some kind of "sleep" mode (or energy-safe mode). I don't know whether it is an Android issue or Samsung specific. But I did not have this issue on OnePlus One phone.

**Comment by asmith999** [comment] 2017-10-23 22:35
A messaging app that doesnt deliver messages... maybe. Think about that :).

**Comment by moxie0** [comment] 2017-10-25 18:15
@korya Awesome, it sounds like you can reproduce this issue reliably? Could you capture a debug log immediately after you've reproduced it and post it here?

**Comment by korya** [comment] 2017-11-02 17:49
Sorry, I don't have time for that now. May be I will try to provide you the logs some day later. But that is a response that I got from Rogers:

> Samsung devices have a battery saving mode that will put the messages app into sleep mode. You can disable this feature by following the steps below
1 Setting
2: Device Maintenance
3: Battery
4: unmonitored
5: Added
6;Select the Messages App>click Done
This should resolve the issue

**Comment by jeremymasters** [comment] 2017-11-02 18:05
@korya Did Rogers' steps resolve the issue for you?

**Comment by korya** [comment] 2017-11-02 18:08
Not sure yet :) Just wanted to share. I need my messages to work for the next couple weeks, so I have switch back to the native messaging app. Probably I can get back to it in December.

**Comment by daman17** [comment] 2017-11-27 03:47
Similar to @korya I resolved my issue by going to "Always Sleeping Apps" and removing Signal from this designation. Inadvertently while using Samsung's battery saving mode Signal got placed in here.

**Comment by jgruenais** [comment] 2017-12-07 21:43
To reproduce this issue : 
go to android' setting then signal app settings and click on force stop.
Send sms to your smartphone ... You wont receave it. 
However, with others SMS' app even stopped you will still receave it.

**Comment by moxie0** [comment] 2017-12-08 02:18
`````
To reproduce this issue :
go to android' setting then signal app settings and click on force stop.
Send sms to your smartphone ... You wont receave it.
However, with others SMS' app even stopped you will still receave it.
`````

Just tried that, doesn't reproduce on any of my test devices.

**Comment by KeBiu** [comment] 2017-12-09 22:11
It works on asus ASUS_Z00AD (WW_Z00A).
1/ Stop signal then do not open it
2/ Send your sms and nothing happend, the sms sent is not receaved by Signal ...

Here's a log : 
https://gist.github.com/anonymous/de30b5166ac5858e11b95b25cec3793e

I killed Signal
I tried to send sms to my asus (nothing happend)
I opened Signal and I sent log from signal  (my smarphone goes to sleeping mode after)
Sent again sms (nothing happend)
Sent a log (this one)

To get sms a have to stay on Signal ...

**Comment by KeBiu** [comment] 2017-12-09 22:31
Ok, thanks to korya, I checked power management's setting.
To solve it on Asus smartphone : 
Setting > Power management > Auto start Manager then allow Signal.

I did 4 - 5 tests and it worked after killing Signal or even when smartphone is sleeping.

**Comment by Enginemanshawn1** [comment] 2017-12-25 19:46
Is anyone using a battery saves and or greenify? This may be something other than the application. I am uding signal on S4 7.1.2 LineageOS. I get delays from SMS when screen is locked. Check settings. Keeping it simple for simple users.

**Comment by Enginemanshawn1** [comment] 2017-12-25 20:23
Is anyone using a battery saver, and or greenify? This may be something other than the application. Check app permissions as well. I am using signal on S4 7.1.2 LineageOS. I get delays from SMS when screen is locked. Check seetings. Keeping it simple for simple users.

**Comment by mscain** [comment] 2018-03-25 14:26
I have experienced missing SMS texts yesterday and today. The fittest missing ones we're important. Then my friend and I tested and could reproduce the loss. They sent me the numbers 1-5 as separate messages and I got 3, 5, 4. Then this morning the same test resulted in 1, 3, 4, 5.

They're on an iPhone stock messaging app. I'm on a Nexus 5. Log: https://hastebin.com/apucuzurip

**Comment by automated-signal** [comment] 2018-04-02 23:35
GitHub Issue Cleanup:
See #7598 for more information.

**Closed** 2018-04-02 23:35 UTC
Labels: sms
