### ISSUE TITLE
PiP inside video call doesn't respect where you place it 

### ISSUE THREAD

**Issue by Tursko** [signalapp/Signal-Android#12942] opened 2023-05-12 12:03 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
This is a regression that I noticed after the redesign of the call screen. No matter where you put your small PIP video stream, if you tap the screen to show the buttons and then tap again it will always go back to the bottom of the screen. Which means the area you put it isn't actually respected.

### Steps to reproduce
- start a video call
- while on the video call, move your pip window to the top
- tap the screen a couple times to show and hide the buttons

**Actual result:** pip window will always go back to the bottom
**Expected result:** it should go back to wherever you placed it. 

### Device info

**Device:** Pixel 7
**Android version:** 13
**Signal version:** 6.19.8

**Comment by nicholas-signal** [comment] 2023-05-31 19:32
Hello,

Are you still able to reproduce this issue? I wasn't able to reproduce it on my Pixel 6a:

https://github.com/signalapp/Signal-Android/assets/112583042/fc0eb2b0-9a7d-4239-aaf9-39fc0e687fd7

The PiP window moves out of the way of the title/buttons but no matter how many times I toggled the buttons, it still returned where it was supposed to be.

**Comment by Tursko** [comment] 2023-05-31 23:41
Still encountering the issue on 6.21.3 on my Pixel 7. I typically talk to an iPhone user (if that makes a difference).

**Comment by alex-signal** [comment] 2023-06-01 12:10
This is my bad from when I redid some of the call ui. The bounding box for the pip is not resizing itself properly. I'll fix this today.

**Comment by Tursko** [comment] 2023-06-07 20:34
Hopefully the fix 

https://github.com/signalapp/Signal-Android/commit/cd9a160cae370a93b68b4a7e501562e02d0ef6aa

**Comment by nicholas-signal** [comment] 2023-06-12 15:52
@Tursko feel free to close this GitHub Issue once you've validated the issue is fixed!

**Closed** 2023-06-21 02:46 UTC
