### ISSUE TITLE
Unable to open signal app from recent apps

### ISSUE THREAD

**Issue by Zombiekat** [signalapp/Signal-Android#9380] opened 2020-02-04 16:12 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Unable to open signal app from recent apps tray after closing app by back button. 

### Steps to reproduce
- open signal
- close app by back button
-  open recent apps
- choose signal

**Actual result:** 
Nothing happens

**Expected result:** 
Launch signal app

### Screenshots
https://imgur.com/a/ccKQfib

### Device info
**Device:** Redmi 5a
**Android version:** 8.1.0
**Signal version:** 4.55.1

### Link to debug log
https://debuglogs.org/2e24b49bcef4ccd632ff1d656476a8184dd6a5c544909132fe58eced17cd58f2

**Comment by bme13** [comment] 2020-02-05 09:17
Hi, This seems like a duplicate of https://github.com/signalapp/Signal-Android/issues/9292.

**Comment by Zombiekat** [comment] 2020-02-05 17:48
Thanks for replying.  Sorry my bad.

**Closed** 2020-02-05 17:48 UTC
