### ISSUE TITLE
Recording audio for a voice message should stop media playback - Android 7, Signal 4.16.9

### ISSUE THREAD

**Issue by jcollum** [signalapp/Signal-Android#7569] opened 2018-03-25 20:05 UTC
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When recording voice audio media playback (audio e.g. podcast) should stop. It's very hard to listen and talk at the same time. **Telegram manages to do this, Signal should as well.** 

### Steps to reproduce
- start audio playing, like a podcast or music
- send a voice message to yourself (or anyone else) via Signal

**Actual result:** recorded voice message will have music in the background

**Expected result:** recorded voice message has no music in the background

### Screenshots
Can provide if needed, but I don't know how I'd capture it without doing a screen recording. 

### Device info 
**Device:** LG G5
**Android version:** see title 
**Signal version:** see title

**Comment by FeuRenard** [comment] 2018-03-25 20:57
Duplicate of #5914

Please search open and closed issues for duplicates before opening new issues!

**Closed** 2018-03-25 23:16 UTC
