### ISSUE TITLE
KDEconnect SMS

### ISSUE THREAD

**Issue by anarchotaoist** [signalapp/Signal-Android#9587] opened 2020-05-05 01:37 UTC
SUMMARY
KDEconnect SMS connects to the non-default set Android stock messaging app.
The default set SMS app, Signal, is not used.

STEPS TO REPRODUCE
1. Opening KDEconnect SMS reveals a few messages from first install.
2. Send messages to contact works -but from the pre-installed SMS app - not the set default SMS app Signal.
 

OBSERVED RESULT
Message sent - but not from Signal

EXPECTED RESULT
Open KDEconnect SMS and send to contacts in default SMS app (Signal).

SOFTWARE/OS VERSIONS
Operating System: Kubuntu 20.04
KDE Plasma Version: 5.18.4
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
Kernel Version: 5.4.0-28-generic
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-7820HQ CPU @ 2.90GHz
Memory: 31.2 GiB of RAM

### Device info

**Device:** OnePlus 5T
**Android version:** 9
**Signal version:** 4.58.5

**Comment by grandchild** [comment] 2020-05-05 07:33
Wouldn't this be an issue with KDEconnect? It seems to me they are sending messages through the Android SMS API (just as Signal does). Signal doesn't "listen in" on other apps sending SMS directly.

KDEconnect would have to either rewrite [their code](https://github.com/KDE/kdeconnect-android/blob/master/src/org/kde/kdeconnect/Plugins/SMSPlugin/SMSPlugin.java) to send through Signal, which Signal would have to support (it doesn't right now, right?), or Signal would have to start to listen for new SMS being sent, and import these on the fly.

The latter sounds easier to do when looking from far away, but either way: This would be a feature request -- so this issue tracker is sadly not the place to discuss it. Try and have a discussion about it on the [forums](https://github.com/KDE/kdeconnect-android/blob/master/src/org/kde/kdeconnect/Plugins/SMSPlugin/SMSPlugin.java)!

**Comment by Genis-Sage** [comment] 2020-05-05 10:35
hey @anarchotaoist 

please search for existing Github issues before opening a new one

this is a duplicate of #9442 


the behaviour is completely as intended, since KDE Connect writes to the system wide SMS database,which can be accessed by all apps with the right to read / write SMS, while Signal has it's own encrypted database

and @grandchild is right
this is a feature request for the forum
https://community.signalusers.org/t/provide-api-so-kde-connect-gsconnect-can-access-sms-history/5644

**Closed** 2022-02-04 03:51 UTC
Labels: wontfix
