### ISSUE TITLE
Calls not going through and directing to spam number

### ISSUE THREAD

**Issue by moejoeward** [signalapp/Signal-Android#12101] opened 2022-03-27 18:50 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When using the call feature or video call feature to a confirmed Signal user, the call would show a message stating "Your network does not support video calls. Please place a voice call instead." Then it would place a voice call to this number: +1(216) 555 0000, which is a spam number. 

### Steps to reproduce
- Open Signal
- Select a contact to call whom is a confirmed Signal user
- Select either "Call" or "Video Call" to place a call. 

**Actual result:** Call did not go through to recipient. Notice of "Your network does not support video calls. Please place a voice call instead" shown at the bottom of the screen. App switched from Signal to phone and called spam number 1(216) 555 0000.
**Expected result:** Recipient would have received the call.  

### Screenshots

![IMG_20220327_160937](https://user-images.githubusercontent.com/32314201/160296225-67e117d3-5960-401a-9ee1-7a03f3d7b356.jpg)

![IMG_20220327_160953](https://user-images.githubusercontent.com/32314201/160293661-57d154b8-4f9b-488f-83a9-1de7b56ef26d.jpg)

https://user-images.githubusercontent.com/32314201/160296084-c7cfa897-3b5a-416d-a8a3-eaac094eff96.mp4

### Device info

**Device:** HUAWEI P30 lite
**Android version:** 10.0.0
**Signal version:** 5.34.4

### Link to debug log

https://debuglogs.org/android/5.34.4/39107ce7587c2528ef32b0a16b9e560245d687a90aba62fc36c09f6ab6374af0

**Comment by Genis-Sage** [comment] 2022-03-28 08:28
hey @moejoeward 
it seems, your case is (nearly) identical to #12097

at least, the root cause of both tickets should be some bug in the telecom implemenation at huawei side

**Comment by greyson-signal** [comment] 2022-03-28 15:50
Closing as duplicate of #12097

**Closed by greyson-signal** 2022-03-28 15:50 UTC
